environments/icds-new/public.yml

@dimagi/scale-team I think this is what was decided on in the meeting

Update icds redis to use 5 GB

---

docs/commcare-cloud/index.md
docs/index.md

I realized a lot of good content was hidden away at the bottom or on another page. Did a quick pass to make the useful stuff more front and center.

Reorganize docs front page

---

docs/changelog/index.md
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/manage_commcare_cloud/changelog.md.j2
src/commcare_cloud/manage_commcare_cloud/make_changelog.py
src/commcare_cloud/manage_commcare_cloud/make_docs.py
src/commcare_cloud/manage_commcare_cloud/manage_commcare_cloud.py

https://github.com/dimagi/commcare-cloud/pull/1954#discussion_r205833635
Addressing @dannyroberts's comments from that PR^^^

Autogenerate changelog fixes

---

Makefile
docs/changelog/0003-update-supervisor.md
docs/changelog/index.md
src/commcare_cloud/manage_commcare_cloud/changelog.md.j2
src/commcare_cloud/manage_commcare_cloud/make_changelog.py

Changelog item for: https://github.com/dimagi/commcare-cloud/pull/1946#event-1753466749

Add update supervisor to 3.3.4 to changelog

---

src/commcare_cloud/commands/fab.py

https://github.com/dimagi/commcare-cloud/issues/1937

Add branch check to fab commands

---

src/commcare_cloud/ansible/roles/postgresql/templates/pg_hba.conf.j2

Will deploy on staging before rolling out.

Remove block from pg_conf

---

commcare-cloud-bootstrap/bootstrap.sh

Reverts dimagi/commcare-cloud#1999

Revert "Separate out deploy_stack playbooks in bootstrap.sh"

---

control/init.sh

I've seen this too many times for "not sure how it got that way" to feel like a good excuse. This should detect and then fix if there's a problem with the pycryptodome install.
I expect to have it happen either 0 or 1 times for each person's env on each control machine. Definitely not something I expect to have to be run on a regular basis or anything.

No module named Crypto

---

src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
src/commcare_cloud/ansible/roles/datadog/tasks/remove_integrations.yml

Oversight in my last PR (https://github.com/dimagi/commcare-cloud/pull/2015)

Only create datadog config for cloudant on the one host

---

commcare-cloud-bootstrap/commcare_cloud_bootstrap.py

Not deleting the env directory on new runs means that I can miss changes to the files that get populated here.

Delete the env dir if it exists

---

.travis/environments/travis/app-processes.yml
commcare-cloud-bootstrap/environment/app-processes.yml.j2
docs/changelog/0004-add-analytics-queue.md
environments/64-test/app-processes.yml
environments/development/app-processes.yml
environments/echis/app-processes.yml
environments/enikshay-reference/app-processes.yml
environments/icds-new/app-processes.yml
environments/pna/app-processes.yml
environments/production/app-processes.yml
environments/softlayer/app-processes.yml
environments/staging/app-processes.yml
environments/swiss/app-processes.yml
src/commcare_cloud/environment/schemas/app_processes.py

Add analytics queue

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/ansible/service.py

https://github.com/dimagi/commcare-cloud/issues/2005

Add a 'logs' command for each service

---

docs/changelog/0004-add-analytics-queue.md

@snopoke https://github.com/dimagi/commcare-cloud/pull/2025#discussion_r210698891

Add required commit to the changelog

---

commcare-cloud-bootstrap/commcare_cloud_bootstrap.py
commcare-cloud-bootstrap/environment/private.yml.j2

https://trello.com/c/mL2fpRPS/130-generate-new-passwords-in-commcare-cloud-bootstrap
- Generate passwords instead of hardcoding them
- Get rid of references to touchforms in the vault.yml file

Generate new passwords in commcare-cloud-bootstrap

---

environments/icds-new/public.yml
src/commcare_cloud/ansible/requirements.yml

https://github.com/andrewrothstein/ansible-couchdb-cluster/pull/7

disable couchdb reduce_limit on ICDS

---

.travis.yml
Makefile
README.md
docs/commcare-cloud/commands/index.md
src/commcare_cloud/ansible/ansible.cfg
src/commcare_cloud/ansible/plugins/inventory/csv.py
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/environment/exceptions.py
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/paths.py
src/commcare_cloud/help_cache/ansible-playbook.txt
src/commcare_cloud/help_cache/ansible.txt
tests/csv_env/multi_file/inventory/couch.csv
tests/csv_env/multi_file/inventory/postgres.csv
tests/csv_env/single_file/inventory.csv
tests/test_csv_inventory.py

See docs and examples in diff for how it works and expected format.
Also see here for another example: https://docs.google.com/spreadsheets/d/1WlamplK6thSqbPt2fMWsoHkPwOan9kdzN63uwu_G7Zo/edit#gid=403315111

CSV inventory plugin

---

src/commcare_cloud/commands/migrations/copy_files.py
src/commcare_cloud/commands/migrations/templates/file_migration_rsync.sh.j2
tests/file_migration_data/file_migration_rsync.sh
tests/test_file_migration.py

(on top of https://github.com/dimagi/commcare-cloud/pull/2047)

don't require specifying files list

---

.travis.yml
README.md
src/commcare_cloud/__init__.py
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/patch_environ.py

See discussion here: https://github.com/dimagi/commcare-cloud/pull/2050#discussion_r212009107

patch environment with ansible.cfg location

---

environments/icds-cas/migrations/README_couch.md
environments/icds-cas/migrations/couchdb-files.yml
environments/icds-cas/migrations/elastic-files.yml
src/commcare_cloud/commands/migrations/config.py

migration tweaks

---

environments/icds-cas/migrations/postgresql-files.yml

Postgres migration fixes

---

src/commcare_cloud/commands/ansible/service.py

Haven't fully tested this yet, but I think this bit us during the CSP migration dry run today. 
Currently if you use `service <service> stop` to stop a service it will come back within a minute because monit will restart it. This PR should change that so that the service will not come back until you explicitly start it.

Use monit for some services

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/airflow/tasks/main.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/ansible/roles/common/tasks/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/bionic_apt_installs.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/trusty_apt_installs.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/trusty_apt_repos.yml
src/commcare_cloud/ansible/roles/postgresql/tasks/main.yml
src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml
src/commcare_cloud/ansible/roles/supervisor/templates/supervisord.systemd.service.j2

Started looking at this in some downtime that I had.
These changes get us through `deploy_common`

ubuntu 18.04 changes

---

environments/icds-cas/migrations/README_couch.md
environments/icds-cas/migrations/couchdb-files-plan.yml
environments/icds-cas/migrations/couchdb-files-post.py

updated migration instructions for couchdb

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/ssh/tasks/main.yml
src/commcare_cloud/ansible/roles/ssh/templates/sshd_config.j2

Allow ssh key by user

---

environments/icds-new/inventory.ini

@calellowitz initial PR. 
I think you might also need to add some configs in postgresql.yml but I am not sure. 
Feel free to edit this.

Added airflow and warehouse

---

environments/icds-cas/migrations/riak-files.yml

@dimagi/scale-team to not conflict with perf testing

Target a new directory

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/manage_commcare_cloud/commands.md.j2

@dannyroberts what do you think about this to make it easier to differentiate between command content.
Other thoughts I had were to have one page per command instead of one page for all.
buddy @Rohit25negi

clearer delineation of commands

---

environments/icds-cas/migrations/elastic-files.yml

ES to a different directory

---

requirements.txt
setup.py

cryptography: https://nvd.nist.gov/vuln/detail/CVE-2018-10903
pycryptodome: https://nvd.nist.gov/vuln/detail/CVE-2018-15560

Apply security updates for python crypto libraries

---

src/commcare_cloud/ansible/group_vars/all.yml

https://manage.dimagi.com/default.asp?282645#1526181
@emord 
@gbova fyi in case you want to change this solution at all when you get back

switching billing email to sales@

---

src/commcare_cloud/terraform/.gitignore
src/commcare_cloud/terraform/modules/commcarehq/main.tf
src/commcare_cloud/terraform/modules/commcarehq/variables.tf
src/commcare_cloud/terraform/modules/network/main.tf
src/commcare_cloud/terraform/modules/network/outputs.tf
src/commcare_cloud/terraform/modules/servers/main.tf
src/commcare_cloud/terraform/modules/servers/variables.tf
src/commcare_cloud/terraform/staging/terraform.tf
src/commcare_cloud/terraform/staging/variables.tf

- update proxy to use public subnet
- bring pre-existing RDS instance under terraform's control

Update staging terraform

---

environments/icds-cas/public.yml

I have tested this FROM mail via telnet
@calellowitz

default mail from for ICDS

---

environments/icds-cas/app-processes.yml

(I sent an email about the next steps for this)

Enable processing scheduled messages on new cluster

---

environments/production/app-processes.yml

hoping this helps with the lagging pillows
@emord should this just work? interrupt buddies @proteusvacuum @mkangia

move xform pillow to pillow3 and double concurrency

---

environments/production/app-processes.yml

on pillow 3
added 2 processes for `kafka-ucr-main`
added 1 for `FormSubmissionMetadataTrackerPillow`
on pillow 0 
added one for `kafka-ucr-main` since one pillow was removed from it earlier [here](https://github.com/dimagi/commcare-cloud/pull/2162/files)

Add more pillows

---

src/commcare_cloud/ansible/add-ssh-keys.yml

This speeds it up since it can run them in parallel.
Also make it possible to only update a subset of hosts
by using '--limit'

make update-local-known-hosts faster

---

environments/production/app-processes.yml

High form submissions not letting form meta data to catch up.. so added two more pillows for that. kafka-ucr-main all down to 0 so reverted changes done for those
Previous PRs:
https://github.com/dimagi/commcare-cloud/pull/2163
https://github.com/dimagi/commcare-cloud/pull/2166

revert kafka-ucr-main additonal pillows and add 2 more for form meta data

---

environments/production/inventory.ini

Adding web worker to prod http://manage.dimagi.com/default.asp?283306
was asked to add two but pushing back if we need actually need 2. So starting with one here.

Add new webworker

---

src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

Bump JS versions

---

environments/production/postgresql.yml

send more load to hqdb0 standby

---

environments/icds-cas/public.yml

https://sentry.io/dimagi/commcarehq/issues/683237869/?query=is:unresolved

change email so that TCL relay accepts these connections

---

environments/production/terraform.yml
src/commcare_cloud/terraform/README.md
src/commcare_cloud/terraform/modules/openvpn/main.tf

Setting up production instance on AWS. (Already deployed.)

Terraform production

---

environments/production/inventory.ini

Reverts dimagi/commcare-cloud#2179

Revert "remove django5 temporarily"

---

environments/production/postgresql.yml

got these from https://pgtune.leopard.in.ua/#/ @proteusvacuum @jmtroth0

pgtune production

---

environments/production/app-processes.yml

start_processes -> start_process

---

environments/production/app-processes.yml

Just temporarily until the queue goes back to 0.

Add one more process for kafka-ucr-main

---

environments/staging/proxy.yml
environments/swiss/proxy.yml
src/commcare_cloud/ansible/letsencrypt_cert.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml

- Enabled SSL on Swiss
- Improved LetseEncrypt setup playbook

LetsEncrypt Cleanup and Swiss SSL

---

environments/icds-cas/public.yml

Deployed this to ICDS. same as https://github.com/dimagi/commcare-cloud/pull/2189/commits/9225ed0489478dec2b5905ceba02b29ed3341609

Set kafka API version for ICDS

---

src/commcare_cloud/fab/fabfile.py

Don't copy tf settings

---

src/commcare_cloud/ansible/status_check.yml

Simple checks that will tell what is wrong on ICDS

Quick Status Check playbook to find issues in ICDS

---

environments/icds-cas/app-processes.yml
environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Adding some pillows with a more recent offset. i'll monitor this over the next couple of days and write up something based on the perfomance seen

Add new "current" form pillows

---

src/commcare_cloud/ansible/deploy_db.yml
src/commcare_cloud/ansible/deploy_kafka.yml

@snopoke @calellowitz @dannyroberts I think this is something similar to what we were talking about at the devops summit session. let me know if i'm misremembering

Add a standalone kafka playbook

---

.travis.yml

Make Travis cron build prove deploy

---

environments/icds-cas/inventory/riakcs.csv

Update mountpoint for riak on ICDS

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

Already deleted this machines from rackspace :)

Remove rackspace staging webworkers

---

src/commcare_cloud/ansible/deploy_control.yml
src/commcare_cloud/ansible/roles/ansible-control/meta/main.yml
src/commcare_cloud/ansible/roles/common_installs/meta/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml
src/commcare_cloud/ansible/roles/git/tasks/main.yml
src/commcare_cloud/ansible/roles/python/tasks/main.yml

@pr33thi this is from our work on Monday—I think I just never PR'd.

Streamline deploy control

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml
src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml

This is deployed and added to the ES cluster

Add staging aws es node

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

This is deployed: our cluster now spans the two data centers!

Enable AWS production ES!

---

environments/production/public.yml
src/commcare_cloud/ansible/roles/commcarehq/defaults/main.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

[Fogbugz ticket](https://manage.dimagi.com/default.asp?284131)
Since I can't test this, I feel like it isn't actually ready for review, but here's what I've come up with so far. Somehow `{% if host == inventory_hostname %}` doesn't feel right to me, but I want it to only apply this change on hosts that match what is specified in public.yml 
@emord 
code buddy @jmtroth0

Conditionally add the ddtrace app to LOCAL_APPS if the hostname matches

---

src/commcare_cloud/commands/terraform/entrypoint.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/commcarehq/main.tf
src/commcare_cloud/terraform/modules/commcarehq/variables.tf
src/commcare_cloud/terraform/modules/network/outputs.tf

I started doing this because I thought it would be useful for ES, but then realized it was kind of pointless to prioritize. (Thanks Farid!)
Still worth PRing because it's still a good change. The only part that makes it incomplete is the part I commented on, but I think even with that blemish, this change is still an improvement.

Allow specifying AZs other than a, b, c in terraform

---

src/commcare_cloud/commands/ansible/ansible_playbook.py

and have the command-line specified user override the default

Make bootstrap-users work with -u <user>

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
src/commcare_cloud/ansible/roles/datadog/templates/tcp_check.yaml.j2

Monitor network performance for various services.

Add datadog TCP checks

---

environments/development/public.yml

set var in development

---

environments/production/app-processes.yml

https://app.datadoghq.com/dash/141098/celery-overview?live=true&page=0&is_auto=false&from_ts=1539845504854&to_ts=1539859904854&tile_size=m&fullscreen=185712938&tpl_var_environment=production#%23*

add ucr-indicator-queue

---

src/commcare_cloud/ansible/host_group_aliases.yml

This works and is a bit faster than the previous version
but not enough to make it worth while.
@dannyroberts I'm wondering if there isn't a way we can improve this, for ICDS we can incorporate it into the CSV inventory but not so for the other envs.

attempt to speed up

---

src/commcare_cloud/ansible/group_vars/all.yml

I was getting a warning about this
@dannyroberts buddy: @Rohit25negi

removing doubled line

---

src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2

@sravfeyn buddy: @Rohit25negi 
this actually has the output i wanted

improving string

---

src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

temporarily increase timeout for ICDS

---

environments/softlayer/public.yml

http://manage.dimagi.com/default.asp?284632
@snopoke @jmtroth0

Set couch data reduce limit to False for Softlayer

---

environments/staging/app-processes.yml
environments/staging/inventory.ini

Intermediate step before fully provisioning the new pillow machine
@dannyroberts 

Set up so that none of the pillow stuff changes on deploy yet

---

src/commcare_cloud/commands/ansible/service.py

Fix es rolling restart when no --limit is specified

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/ansible/ansible_playbook.py

@pr33thi maybe this would have helped clarify the thing you ran into today. (I've also run into it a number of time, so it's a gotcha worth documenting.)

Improve deploy-stack --first-time help text

---

environments/icds-new/public.yml

Start testing custom reports created in https://github.com/dimagi/commcare-hq/pull/21228
buddies @biyeun @Rohit25negi

Compare more UCR reports

---

src/commcare_cloud/ansible/roles/bootstrap-users/tasks/remove_users.yml
src/commcare_cloud/ansible/roles/ksplice/tasks/main.yml
src/commcare_cloud/ansible/roles/ufw/tasks/main.yml
src/commcare_cloud/ansible/roles/ufw/tasks/proxy_ufw.yml

because they just run a shell commmand to read something
Just a few annoying little things I found while doing other stuff.

Make some tasks never report "changed"

---

environments/production/public.yml

The dbs are sync'd and I'm in the process of updating the views

Move apps and fluff-* dbs over to new couchdb2 on production

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

- Changes were made directly to inventory.ini here, added those changes to inventory.ini.j2
- Running aws-fill-inventory to capture the fact that the airflow hosts should be uncommented
@dannyroberts 

Update inventory files

---

src/commcare_cloud/ansible/roles/redis/tasks/setup_cluster.yml

don't reshard existing redis deployment; add a todo

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Rabbit staging migration to AWS

---

src/commcare_cloud/commands/terraform/migrations/0000_example.py

Change all occurances of peudocode to pseudocode

---

environments/production/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.tfvars.j2
src/commcare_cloud/commands/terraform/templates/variables.tf.j2
src/commcare_cloud/environment/schemas/terraform.py

Elasticache is how we're going to host redis on AWS

Create production elasticache

---

environments/staging/inventory.ini

They mistakenly all said formplayer0 before.

Fix the staging couch machine hostnames

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

@dannyroberts 
Code buddy @sravfeyn

Remove hqes0, it has been migrated

---

environments/staging/inventory.ini.j2

@dannyroberts 
Code buddy @sravfeyn

Fix the couch hostnames in inventory.ini.j2 template file

---

environments/icds-cas/public.yml

I added this today so that the new optimized UCR will have new data. (already deployed)

Added new person case UCR to pillows

---

src/commcare_cloud/terraform/modules/network/main.tf

needs this for a couple things during deploy

Give public subnet (proxy) access to redis

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Adding new projects from transifex

add new projects

---

src/commcare_cloud/ansible/roles/postgresql/templates/postgresql.conf.j2

currently fails on undefined variable

Fix barman setup in postgresql.conf

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

add ability to use tmux's server option when running management command

add ability to pass server for tmux session

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/terraform.py

fixes https://github.com/dimagi/commcare-cloud/issues/2410

Read from COMMCARE_CLOUD_DEFAULT_USER env var

---

environments/icds-cas/public.yml

the files has been already added and nginx config was changed manually on the proxy machine
Link added https://www.icds-cas.gov.in/tamil_icds-cas_files

add tamil files

---

src/commcare_cloud/ansible/roles/datadog/templates/datadog.conf.j2

Don't need this and it's extra cost

disable datadog process monitoring

---

environments/production/terraform.yml

upsize django manage

---

environments/icds-cas/public.yml

Redoing https://github.com/dimagi/commcare-cloud/pull/2386

Test new person case UCRs

---

environments/production/terraform.yml

This change has already been applied (I didn't apply it to celery2 because @dannyroberts did)
@dannyroberts 

Increase RAM on celery machines

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

See https://github.com/dimagi/commcare-hq/pull/22566

drop bulk delete chunksize for TCL blobdb

---

src/commcare_cloud/ansible/roles/java/defaults/main.yml
src/commcare_cloud/ansible/roles/java/tasks/main.yml

https://manage.dimagi.com/default.asp?279459
https://trello.com/c/kLQoW3ds/119-jdk-update-to-v8

upgrade to jdk8

---

environments/production/public.yml

@dannyroberts 
code buddy @calellowitz 
Rolling out the changes now

Added BIGCOUCH settings to production

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

It has already been deleted on rackspace.
@dannyroberts 

Remove hqdb1 from inventory.ini

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

This can be done now that the staging couch migration is complete
@dannyroberts 
code buddy @calellowitz 
Reverts dimagi/commcare-cloud#2451

Revert "Temporarily comment out web0 from the staging inventory"

---

environments/production/postgresql.yml
environments/production/public.yml
src/commcare_cloud/ansible/roles/postgresql/defaults/main.yml
src/commcare_cloud/ansible/roles/postgresql/templates/pg_hba.conf.j2

This is to fix the downtime we just had

Bring back hba

---

changelog/0007-reorganize-pillows.yml
docs/changelog/0007-reorganize-pillows.md

doc update

---

environments/staging/terraform.yml

Already made these changes, this just updates the terraform.yml file
@dannyroberts 
code budy @calellowitz

Increase volume size here to match reality

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/staging/aws-resources.yml
environments/staging/inventory.ini.j2
src/commcare_cloud/commands/terraform/aws.py

Includes some small changes to make this easier.  (Can follow along commit-by-commit.)
Again, this is just setup for the downtime this weekend, none of this is hooked up yet.

Add production RDS to the inventory

---

environments/staging/postgresql.yml

This change has already been applied.
@dannyroberts 

Increase pgbouncer_max_connections on staging

---

environments/production/terraform.yml

Enable multi-az on all production RDS instances

---

environments/icds-cas/public.yml

Add new ucr('ls_vhnd_form') to include list

Add ls vhnd form to ucr list icds

---

environments/production/postgresql.yml

I rolled this out over the weekend to address errors, and forgot to PR at the time. There's a brief retro coming out about this shortly.

Increase production pgbouncer_max_connections

---

changelog/0008-blob-metadata-part-1.yml
changelog/0009-blob-metadata-part-2.yml
docs/changelog/0008-blob-metadata-part-1.md
docs/changelog/0009-blob-metadata-part-2.md
docs/changelog/index.md
src/commcare_cloud/manage_commcare_cloud/make_changelog.py

Add blob metadata migrations to change log

---

src/commcare_cloud/ansible/roles/common/handlers/main.yml
src/commcare_cloud/ansible/roles/common/tasks/main.yml
src/commcare_cloud/ansible/roles/common/tasks/syslog.yml

Following AWS Suport's recommendation in
https://console.aws.amazon.com/support/v1?#/case/?displayId=5612595231&language=en.
I can't say I deeply understand what this does, but I don't think it
affects what ends up in /var/syslog.

Try to fix "serial8250: too much work for irq4"

---

environments/production/terraform.yml

Minor changes and then I'm going to push this out. (Never originally pushed out the origninal change, so no ec2 instances have groups yet.)

Fix and tweak production ec2 instance groups

---

environments/production/terraform.yml

[[Jira ticket]](https://dimagi-dev.atlassian.net/secure/RapidBoard.jspa?rapidView=53&projectKey=PLAT&modal=detail&selectedIssue=PLAT-21&quickFilter=46)
@dannyroberts 
cody buddy @nickpell

Increase cpu on celery1-production

---

src/commcare_cloud/commcare_cloud.py

by doing less redundant setup on the machine

Make --control flag run faster

---

environments/softlayer/inventory.ini

I wasn't able to complete this in time, so better not to have it in the inventory
Realized I had an issue setting these up and now I'm going home. Will resume in the morning.

Temporarily disable new softlayer couch nodes

---

environments/staging/public.yml

Already applied.
https://dimagi-dev.atlassian.net/browse/PLAT-79
@dannyroberts

Disengage staging blob db migration mode

---

environments/production/app-processes.yml

the machine it's on (celery0) has plenty of spare RAM
https://dimagi-dev.atlassian.net/secure/RapidBoard.jspa?rapidView=53&projectKey=PLAT&modal=detail&selectedIssue=PLAT-77

Add capacity to production repeat_record_queue

---

environments/softlayer/postgresql.yml

increase connection limits for softlayer pgbouncer

---

environments/icds-cas/public.yml

password file has been added and the link is setup

Add english files link

---

environments/staging/terraform.yml

I think we just never updated here after increasing the disk some time ago

Update staging pgproxy0 disk size to real value

---

environments/production/aws-resources.yml
environments/production/terraform.yml

Changes already applied.
@dannyroberts

Terminate pgproxy0-production

---

environments/icds-cas/inventory/postgresql.csv
environments/icds-cas/postgresql.yml

This is also a temporary PR to take PGucr out of rotation for changing the replication.

Removed 2 ucr

---

environments/icds-cas/public.yml

Add Meghalaya

---

environments/production/terraform.yml

The view indexing is up to date so now I'm going to go from the single
copy to storing in triplicate as recommended.
This is already applied.

Add disk to couch[3-10] to hold replicas

---

changelog/0012-generalize-load-case-from-fixture.yml
docs/changelog/0012-generalize-load-case-from-fixture.md
docs/changelog/index.md

Docs explaining what to do after https://github.com/dimagi/commcare-hq/pull/23117/

Update docs for app migration

---

environments/icds-cas/public.yml

Add the new UCR for CBE forms
other related Pr: https://github.com/dimagi/commcare-hq/pull/23073/files

Add the new UCR for CBE forms

---

src/commcare_cloud/ansible/roles/backups/tasks/main.yml
src/commcare_cloud/ansible/roles/backups/templates/check_s3_backup.py.j2
src/commcare_cloud/ansible/roles/devops_scripts/tasks/main.yml

Script to check backup upload status to S3

Script to check backup status of s3 upload

---

README.md

@dannyroberts Diff is kinda weird 'cause I accidentally pushed to master.  I have a revert commit and then a commit adding it back in.

Update location of bash completion file

---

environments/icds-cas/inventory/postgresql.csv

setup pgnondashboarducr0 as standby

---

environments/icds-cas/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_pillowtop.conf.j2

Thinking to roll this out and see if number of connections from pillow5 to ucr-main DB will reduce.

increase UCR pillow chunk size to 20 on pillow5

---

.github/PULL_REQUEST_TEMPLATE.md

Addig a pull request template to have a defined way of making PRs
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
NA
This will lure the dev to add more helpful information in the PR and will also improve the PR process.

Addtion of Pull Request Template

---

environments/icds-cas/app-processes.yml

chunk size to 100 on pillow5

---

environments/icds-cas/public.yml

https://dimagi-dev.atlassian.net/browse/ICDS-348
credentials file added and this is all set on proxy0

add gujarati link

---

environments/icds-cas/public.yml

(depends on https://github.com/dimagi/commcare-hq/pull/23269/)
PR description may be a bit incomplete/wrong, sorry.
Adds three new reports to the laboratory setting for the ICDS `person_case` data source migration.
ICDS
Local settings
```
commcare-cloud icds-cas update-config
```
* Before
```
(I haven't run this but the settings dict should get three new entries)
```
* After
```
(I haven't run this but the settings dict should get three new entries)
```

add remaining reports

---

environments/icds-cas/app-processes.yml

chunk size to 100

---

environments/icds-cas/public.yml

Hoping that reducing this from 100% will have less impact on the cluster.
icds
See https://redislabs.com/ebook/part-2-core-concepts/chapter-4-keeping-data-safe-and-ensuring-performance/4-1-persistence-options/4-1-3-rewritingcompacting-append-only-files/
buddies @esoergel @emord

set aof-rewrite-percentage to 50

---

src/commcare_cloud/ansible/promote_pg_standby.yml

use postgresql_version var

---

environments/icds-cas/postgresql.yml
src/commcare_cloud/ansible/roles/postgresql/templates/pgbouncer_hba.conf.j2

Going to flip writes to non dashboard DB today. Will be using this PR to update localsettings.
@snopoke 
cc @nickpell

Non dashboard DB switch settings update

---

docs/firefighting/index.md

As suggested in the email thread "Retro: Recent data missing from reports in many project spaces Feb 15-19", I'm adding a section on "couch rewinds" to the firefighting docs.
None

Add section on couch rewinds to firefighting docs

---

environments/icds-cas/public.yml

Removing some UCR comparison tests due to issues
icds
UCR comparison
@pr33thi is going to send out more info detailing issues with child_health monthly reports

Remove UCR comparisons

---

environments/staging/app-processes.yml
environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Request to Remove Celery1 and add Pillow1(bionic) to the staging
Staging
ubuntu Upgrade.

Added Pillow1 with Bionic Image

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

gather unique pillow names

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

Add CitusDB servers in SoftLayer. 
* Install Postgresql
* Install CitusDB
* Do not add any database. 
Softlayer/India
CitusDB

Added Citus in softlayer

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

This is an attempt to fix the drop-off in form submission success rate. We're not sure why the split would have caused the drop, but at this point we're grasping at straws.
Waiting for approval before applying this change to production.
Attempt to fix https://dimagi-dev.atlassian.net/browse/PLAT-103
production
@dannyroberts

Undo split prod webworkers

---

changelog/0016-invoke-celery-directly.yml
changelog/0019-remove-celery-results-backend-from-localsettings.yml
docs/changelog/0016-invoke-celery-directly.md
docs/changelog/0019-remove-celery-results-backend-from-localsettings.md

add max version before celery 4.x upgrade

---

environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Removes Pillow0
Adds PgProxy1
staging
```paste below
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
~ update in-place
- destroy
Terraform will perform the following actions:
~ module.network.aws_security_group.db-private
ingress.#:                                 "9" => "10"
ingress.1033539001.cidr_blocks.#:          "1" => "1"
ingress.1033539001.cidr_blocks.0:          "10.201.20.112/32" => "10.201.20.112/32"
ingress.1033539001.description:            "" => ""
ingress.1033539001.from_port:              "9200" => "9200"
ingress.1033539001.ipv6_cidr_blocks.#:     "0" => "0"
ingress.1033539001.prefix_list_ids.#:      "0" => "0"
ingress.1033539001.protocol:               "tcp" => "tcp" …
```

Add Pgproxy, Remove Pillow0

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
src/commcare_cloud/commands/migrations/couchdb.py
src/commcare_cloud/commands/migrations/plays/assert_couch_files.yml

They're no longer part of the cluster and they're being removed so we can stop paying for them.
india

Remove india couch{2,3,4} from inventory

---

src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

update virtualenv clone

---

src/commcare_cloud/ansible/setup_pg_standby.yml

Updating vars_files path to postgresql_base

Updating vars_files path to postgresql_base

---

src/commcare_cloud/fab/operations/release.py

Returns submodule URLs to their remote counterparts after pulling them locally. This was causing an issue on deploy when (we think) commits didn't exist in the local submodule repos but were referenced elsewhere.
None
Deploy

Return submodules to remote URLs after fetching

---

environments/icds-cas/inventory/postgresql.csv
environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Cleanup Upgraded Servers from Staging. 
```paste below
```
* Before
```paste below
```
* After
```paste below
```

Cleanup Staging Files

---

environments/india/aws-resources.yml
environments/india/terraform.yml
src/commcare_cloud/commands/terraform/templates/variables.tf.j2

The VPN is now reporting UP (big step!) but I'm not actually able to ping/ssh from AWS to softlayer or vice versa yet. Working on figuring out where in the network there's an issue, but thought it was worth PRing this.
india (and it's a no-op)

Fix india VPN

---

environments/production/inventory.ini

Looks like this was caused by https://github.com/dimagi/commcare-cloud/pull/2746. Thanks @nickpell

Fix production/inventory.ini to match inventory.ini.j2

---

environments/icds-cas/postgresql.yml

Moving formplayer from pgucr to main

Change formplayer host

---

environments/icds-cas/app-processes.yml

Added Celery112 in app process

---

environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Addtion of
web1
web2
airflow1
formplayer1
```paste below
```
* Before
```paste below
```
* After
```paste below
```

Added new servers

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

Adding new servers in ansible group on staging env

Adding new servers in ansible group on staging env

---

scripts/example-terraform-resize-disk.sh

I had put this together for a recent bit of maintenance and figured it was worth saving somewhere.

Add example script for resizing disk on aws

---

environments/staging/proxy.yml
environments/staging/public.yml
src/commcare_cloud/ansible/deploy_common.yml
src/commcare_cloud/ansible/deploy_proxy.yml
src/commcare_cloud/ansible/stop_servers.yml

Changes the REACH proxy setup to depend on a separate proxy, similar to CAS and PNA setups
staging
nginx

Add reach_proxy inventory

---

src/commcare_cloud/environment/main.py

respond to https://github.com/dimagi/commcare-cloud/pull/2767#pullrequestreview-224524586
deduplicate hosts

Clean up check_known_hosts function

---

environments/datadog_envs.yml

- send swiss to #alerts-swiss
- send softlayer and india to #alerts-softlayer AND #alerts-india (for now)
I eventually want to send india to #alerts-india and shutdown #alserts-softlayer, with the intermediate step of sending softlayer to #alerts-softlayer to make sure we're not getting anything under that environment name. For now though I want to make it a clean switchover so I can announce that everyone should start watching #alerts-india and ignoring #alerts-softlayer.
Datadog monitors
output:
```
Diff for 'SSL Cert Expiry'
---
+++
@@ -2,15 +2,21 @@
{{#is_warning}}SSL Cert will expire in less than 28 days{{/is_warning}}
{{#is_alert}}SSL Cert will expire in less than 14 days{{/is_alert}}
{{check_message}}
+  {{#is_match "host.environment" "softlayer"}} @slack-alerts-softlayer …
```

Update datadog env_notifications

---

environments/icds-cas/public.yml

update max memory and eviction policy
FYI @dimagi/scale-team

update redis config

---

environments/icds-cas/app-processes.yml

More resources for ICDS SMS queues

---

src/commcare_cloud/ansible/deploy_common.yml

Updating nameservers failed on some machines in india environment

Fix setup of nameservers

---

environments/icds-new/app-processes.yml
environments/icds-new/inventory.ini
environments/icds-new/postgresql.yml

Reconcile NIC inventory file with what exists today.
Legacy NIC environment
n/a
not sure if the build will pass on this, but it makes it easier to run shell commands against NIC and not have to wade through a bunch of errors related to missing/dead servers

Nic cleanup

---

environments/india/postgresql.yml

This has actually been an issue for sometime
but was especially bad this weekend.
india

Increase pgbouncer_max_connections on india to 4000

---

environments/production/terraform.yml
src/commcare_cloud/environment/schemas/terraform.py

and roll this out to all current instances
production, staging
RDS (logging)

Enable pg_stat_statements logging on RDS by default

---

src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py
src/commcare_cloud/manage_commcare_cloud/monitors/disk.yml
src/commcare_cloud/manage_commcare_cloud/monitors/es_cluster_node_connection.yml

To make this a little easier, I also added a the file path to the datadog monitor config to the diff output.

Sync datadog monitor changes to configs

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

Remove old Elasticsearch and Redis servers in the staging environment

Remove old Elasticsearch and Redis servers in staging environment

---

src/commcare_cloud/manage_commcare_cloud/monitors/.ignore.yml

Just another PR to keep datadog monitors in sync

Add new support datadog monitor to ignore list

---

src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer_hba.conf.j2

review by commit
I believe the first commit will fix this error: https://sentry.io/organizations/dimagi/issues/679225746/

pgbouncer hba tweaks

---

environments/icds-cas/inventory/elasticsearch.csv

turn off data for ICDS ES master nodes

---

control/init.sh

Correct echo command in init.sh

Add echo to command in init.sh

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
src/commcare_cloud/commands/terraform/aws.py

This is motivated by the new bionic vars that we're needing, but also the amount of copy-paste-edit-edit-edit we've been doing to maintain the template.
production, staging (and to a tiny extent india)
inventory / aws-fill-inventory

Make inventory template dryer

---

environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Adding new RabbitMQ server in staging environment which has bionic os

Adding new RabbitMQ server in staging environment

---

environments/icds-cas/public.yml

add new links

---

control/init.sh
src/commcare_cloud/ansible/deploy_control.yml

I stumbled upon this when I was bootstrapping the new staging control machine this morning
```
cchq staging ansible-playbook deploy_control.yml
```
now proceeds smoothly.

Fix deploy control by adding the host_group_aliases.yml boilerplate

---

environments/india/terraform.yml

I meant to get this in to the previous PR (https://github.com/dimagi/commcare-cloud/pull/2824)

Update proxy1-india machine size

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

Removing old RabbitMQ server from the staging environment

Removing old RabbitMQ server from staging environment

---

environments/production/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py

https://github.com/dimagi/commcare-cloud/pull/2685#discussion_r260631767

Rename terraform.yml redis to elasticsearch

---

environments/production/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_workers.conf.j2

so celery4 and celery6 are exact mirrors of each other
This is my stab at fixing https://dimagi-dev.atlassian.net/browse/PLAT-156
production

Redistribute queues across celery{4,5,6}-production

---

docs/howto/add-celery-machines.md
docs/index.md

Update docs; link to adding celery vm

---

environments/india/postgresql.yml
src/commcare_cloud/ansible/deploy_citusdb.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/main.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_cordinator.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_worker.yml
src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml

The tag changes make it easier to update config / create db's etc without having to run all the installation tasks.
```
cchq india ap deploy_citusdb.yml --tags=configure
```

add citusdb to india config

---

docs/firefighting/index.md

Firefighting notes for replication delay

---

docs/system/system-overview.md

Update docs to say we use Ubuntu 18.04
None
README
I see a number of references to `ansible_distribution_version == '14.04'` - do those need to be updated with the OS upgrade?  Similarly, I see references to `os: trusty`, which may need updates.
Both of those are potentially substantive changes which I'm considering outside the scope of this PR.

Update docs to say we use 18.04

---

docs/firefighting/index.md

I made a few substantive changes (like stopping datadog), and the rest is just reformatting.

Update firefighting docs for nfs hanging

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

Reverts india kafka broker id back to 0 to keep it consistent with already created topics.

change kafka broker back to 0

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/fab/operations/release.py

Requires https://github.com/dimagi/commcare-hq/pull/24397
@dimagi/py3

change references to requirements-python3_6 to requirements-python3

---

environments/india/public.yml

I just selected a few UCRs for comparison

enable UCR comparisons on ICDS UCRs

---

environments/icds-cas/fab-settings.yml

Not sure why this is disabled.

enable deploy emails for ICDS

---

src/commcare_cloud/commands/terraform/templates/variables.tf.j2

I noticed these had changed, good to stay up to date.
These are the AMIs we use to create a new machine, so it doesn't affect existing machines.

Update bionic AMIs to 20190514 release

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/public.yml

Remove all softlayer machines now that s3 migration is complete
india

Finish india s3 migration

---

docs/howto/migrate-s3-to-s3.md

While doing this recently I took the opportunity to expand on the parts I had to look up or ask @millerdev about.

Update blobdb migration docs

---

environments/icds-cas/fab-settings.yml

Updates the suggested maintenance window for ICDS to prevent conflicts with the aggregation. I also pushed the front up a bit because I think there is no reason to avoid deploying at the tail end of the india day and this gives a slightly wider window (although it won't actually prevent you from deploying so its more of a suggestion anyway)
@emord @snopoke @sravfeyn @Rohit25negi

update icds maintenance window

---

environments/production/terraform.yml

Short term fix for https://docs.google.com/document/d/1U3h-IVdQLH_encgSM0Q42L4fJ1rRwomysfyeXgDMvSY/edit?ts=5ced7cdc#
This is already rolled out
production

Increase production celery resources for async_restore_queue

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml

https://github.com/dimagi/commcare-cloud/pull/2899#issuecomment-497320405

create virtualenvs when CREATE_NEW_VIRTUALENV is set

---

src/commcare_cloud/ansible/deploy_postgres.yml
src/commcare_cloud/ansible/roles/postgresql_base/defaults/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/handlers/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/templates/systemd_limits.conf.j2

For Ubuntu 18.04 it doesn't work to change `/etc/security/limits.conf`

configure file limit of PG

---

src/commcare_cloud/ansible/roles/postgresql_base/tasks/set_up_dbs.yml

This is already happening in python during setup

drop host assert

---

environments/pna/public.yml
src/commcare_cloud/ansible/deploy_common.yml
src/commcare_cloud/ansible/deploy_couchdb2.yml
src/commcare_cloud/ansible/deploy_postgres.yml
src/commcare_cloud/ansible/roles/backups/tasks/main.yml
src/commcare_cloud/ansible/roles/commcarehq/defaults/main.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/ansible/roles/common/tasks/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2-preinstall/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/java/tasks/main.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml
src/commcare_cloud/ansible/roles/nginx/tasks/set_site_present.yml
src/commcare_cloud/ansible/roles/nginx/vars/main.yml
src/commcare_cloud/ansible/roles/postgresql/tasks/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
src/commcare_cloud/ansible/roles/redis/tasks/main.yml

Various deprecation warnings and cleanup I've found over past couple of days
none

Various ansible cleanup

---

environments/echis/app-processes.yml
environments/pna/app-processes.yml
environments/swiss/app-processes.yml
src/commcare_cloud/ansible/roles/jython/defaults/main.yml
src/commcare_cloud/ansible/roles/jython/files/install_jython.sh
src/commcare_cloud/ansible/roles/jython/meta/main.yml
src/commcare_cloud/ansible/roles/jython/tasks/main.yml
src/commcare_cloud/environment/schemas/app_processes.py
src/commcare_cloud/environmental-defaults/app-processes.yml
src/commcare_cloud/fab/fabfile.py

Get out of here jython
none
nothing
probably should have been removed as part of https://github.com/dimagi/commcare-cloud/pull/2161/

Get out of here jython

---

src/commcare_cloud/ansible/migrate_on_fresh_install.yml

specify --noinput for migrationso
none

Don't ask for input on migrations

---

control/init.sh

I think we've given enough time to people to update their muscle memory at this point. 
None

Remove old commands and references to ansible control

---

docs/setup/new_environment.md

Adds some docs on how to setup a monolith server on 18.04
none

New monolith setup docs

---

environments/india/app-processes.yml

I'm not sure if this will work / still be enough processing power, but I wanted to try one last thing before throwing money at it
india

Reduce concurrency on india celery queues to lower memory usage

---

docs/setup/new_environment.md

More updates to monolith installation. There a still a few updates to the scripts that I'm going to make, but we want to get this documentation into the hands of the partner today.

Updates to monolith documentation

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

Replacing trusty(ubuntu 14.04) CouchDB servers with Bionic(ubuntu 18.04) CouchDB servers in India environment

Replacing trusty(ubuntu 14.04) CouchDB servers with Bionic(ubuntu 18.04) CouchDB servers in India env

---

environments/icds-cas/public.yml

Adds two new locations on nginx for file sharing on ICDS
ICDS
This is already deployed.
I had to only add for Assamese but i found that sikkim one was missing in commcare-cloud but was present on the server so i added that as well.
fyi @Rohit25negi i think sikkim was added by you last time, pinging to confirm that you didn't add it to commcare-cloud and so it should be present now

add missing sikkim and new asm

---

environments/staging/aws-resources.yml
environments/staging/terraform.yml

Terminating old servers(ubuntu 14.04)  in staging environment

Terminating old servers(ubntu 14.04) in staging environment

---

environments/icds-cas/public.yml

Adds a new locations on nginx for file sharing on ICDS
ICDS
This is already deployed.

Add kan location

---

docs/setup/new_environment.md

This is why I needed to log out and log in again... oops.

Load config immediately

---

environments/icds-cas/inventory/citusdb.csv

set citusdb pgbouncer max_connections to 3500 from default 100

---

src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

Reverts dimagi/commcare-cloud#2941
@proteusvacuum @dannyroberts

Revert "Uninstall existing Python 3.6 so it can be replaced with 3.6.8 from PPA"

---

environments/icds-cas/postgresql.yml

Enable query stat collection for the main database
icds
pg
Planning to deploy this on Monday so that I can use pghero to find any slow queries on pgmain. We have this on ucr database and i've used it to optimize indexes previously.

Enable query stat collection for the main database

---

src/commcare_cloud/ansible/migrate_on_fresh_install.yml

Configures PL/Proxy after migrating the DB for the first time.
Requires: https://github.com/dimagi/commcare-hq/pull/24646

Configure PL/Proxy after first migration

---

scripts/tcl/reset.yml

add tcl reset password util

---

environments/icds-cas/app-processes.yml

move agg from 10 workers to 20 since we are spawning twice as many tasks

double agg process while testing citus

---

docs/howto/redis_cluster.md
docs/index.md
src/commcare_cloud/ansible/roles/redis/tasks/setup_cluster.yml

Add redis cluster docs

---

docs/commcare-cloud/env/index.md
docs/setup/control_machine.md

I was asked to write documentation about a "control machine"...
Are there any sections here you think I should add?

Add control machine documentation

---

environments/icds-cas/app-processes.yml
environments/icds-cas/public.yml

Adds citus comparisons on ICDS
icds
celery

add icds citus comparison queue

---

docs/commcare-cloud/backup.md

Adds documentation for postgresql backups. Other services to come, need something to show for a meeting this afternoon.

Add postgres backup docs

---

environments/icds-cas/fab-settings.yml
environments/india/fab-settings.yml
environments/pna/fab-settings.yml
environments/production/fab-settings.yml
environments/swiss/fab-settings.yml

include Python 3 virtualenv in all managed environments

---

Makefile
src/commcare_cloud/ansible/ebsnvme/files/_vendor/ebsnvme-id
src/commcare_cloud/ansible/ebsnvme/tasks/main.yml

Follow up to conversation here: https://github.com/dimagi/commcare-cloud/pull/2991/files#r300454645

Vendorize ebsnvme-id in case the gist is deleted

---

docs/commcare-cloud/basics.md

Documentation updated for running Django mgmt commands.

Update Docs for running django mgmt commands

---

environments/swiss/app-processes.yml

I rolled this out while stabilizing the new swiss server. Flower is needed for some of the datadog celery metrics.
swiss

Add flower back to swiss

---

docs/firefighting/index.md

Add formplayer dashboard to firefighting page
None
Firefighting docs

Add formplayer dashboard link to firefighting page

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/PLAT-178
production

Increase shareddir0-production disk to 100GB

---

src/commcare_cloud/environment/main.py

Make it possible to use the UI `Ansible` filter

add source to allow filtering in UI

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Increase app media cache for CAS before the next app release.
icds
nginx

Update cas.commcarehq.org app media cache size

---

docs/changelog/index.md
tests/test_autogen_docs.sh

I noticed this a while ago and tracked it down. The autogen test wasn't failing

Fix test_autogen_docs.sh (make it fail and then fix failure)

---

.github/PULL_REQUEST_TEMPLATE.md

Updates pull request template
None

Update pull request template for downtime required pull requests

---

environments/production/proxy.yml
src/commcare_cloud/ansible/roles/nginx/templates/site.j2
src/commcare_cloud/environment/schemas/proxy.py

Add support for blocking IPs and ranges in nginx
icds
proxy
https://nginx.org/en/docs/http/ngx_http_access_module.html#deny

Add support for blocking IPs and ranges in nginx

---

docs/commcare-cloud/backup.md
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2/templates/restore_couchdb_backup.sh.j2

Adds a restore script for monolith installations of couchdb.

Add couchdb restore script

---

docs/commcare-cloud/backup.md

Expand instructions for postgres restores

---

environments/icds-cas/inventory/postgresql.csv

* setting up pgsynclog0standby
ICDS

setting up pgsynclog0standby

---

environments/icds-cas/public.yml

Prevent CouchDB compaction from continuing beyond allocated time period.
ICDS
CouchDB
https://docs.couchdb.org/en/stable/config/compaction.html#compaction-daemon-rules

set strict window for couch compaction on ICDS

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/ansible/ops_tool.py
src/commcare_cloud/commcare_cloud.py

Example output for ICDS:
```
Pillow                                | Processes   
------                                | ---------   
AppDbChangeFeedPillow                 | 1           
ApplicationToElasticsearchPillow      | 1           
CacheInvalidatePillow                 | 1           
CaseToElasticsearchPillow             | 120         
DefaultChangeFeedPillow               | 1           
DomainDbKafkaPillow                   | 1           
FormSubmissionMetadataTrackerPillow   | 16          
GroupPillow                           | 1           
GroupToUserPillow                     | 1           
KafkaDomainPillow                     | 1           
LedgerToElasticsearchPillow           | 1           
SqlSMSPillow                          | 1           
UpdateUserSyncHistoryPillow …
```

pillow resource report

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/couchdb2/defaults/main.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/compact.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2/templates/compact_couchdb.sh.j2

Temporary measure to compact couch databases and views until we can upgrade to >= 2.3.1
ICDS

add script to compact couch views and DBs

---

src/commcare_cloud/ansible/roles/bootstrap-users/tasks/remove_users.yml

This is simpler and also fixes the issue when the username gets
truncated in the output e.g. 'userna+'

fix check for user processes

---

docs/services/postgresql.md
environments/icds-cas/inventory/citusdb.csv

* Doc link updated for hot standby node setup
* fixed typo in one of citusdb standby node hostname
ICDS

Doc link updated. fix typo in hostname

---

environments/icds-cas/inventory/couchdb2.csv
environments/icds-cas/migrations/remove-couch3.yml

Seeing high CPU Stolen on couch3 so removing it from the cluster to
see if there are any improvements to performance
ICDS

remove couch3

---

src/commcare_cloud/ansible/roles/haproxy/defaults/main.yml
src/commcare_cloud/ansible/roles/haproxy/templates/haproxy.cfg.j2

I noticed that we're hitting the limit on ICDS so bumping this up.

increase maxconn for haproxy

---

scripts/format_disk_benchmark.pl

From https://docs.google.com/document/d/1zFrfHjHY6UzBrBHcCGFlaldxENlff2UfbIMSXCHWm9Y/edit# with some fixes

disk benchmarking script

---

environments/production/terraform.yml

Follow up to https://dimagi-dev.atlassian.net/browse/HI-778
production

Increase production formplayer volume size

---

environments/icds-cas/inventory/postgresql.csv
environments/icds-cas/postgresql.yml

- Downtime Pull Request
```paste below
```
* Before
```paste below
```
* After
```paste below
```

swap pgshard9

---

src/commcare_cloud/ansible/roles/datadog/templates/disk.yaml.j2

* Add squashfs in blacklist for mount point monitoring
ALL

Add squashfs in blacklist for mount point monitoring

---

environments/icds-cas/app-processes.yml

Add three processes to ledger -> ES queue
I think that this is all we would need to avoid falling behind again. i currently have 16 deployed to ICDS to catch up
icds
pillows

Add three processes to ledger -> ES queue

---

src/commcare_cloud/fab/fabfile.py

These got removed halfway through the PR that added them. Now they are back

add missing airflow vars

---

environments/icds-cas/inventory/postgresql.csv
environments/icds-cas/postgresql.yml

Makes pgshard3 the primary again
icds
- Downtime Pull Request
downtime scheduled for today
postgres

Swap pgshard3

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Set CAS submissions to 180 r/s
icds
nginx
already changed on proxy0

Set CAS submissions to 180 r/s

---

src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml

fixed ownership of custom dd-config
ALL

fixed ownership of custom dd-config

---

scripts/example-apply-terraform-rolling-restart.sh

with rolling restart. E.g. to increase the size of each couch node one
by one. Adding to the collection of not-that-hardened scripts I use to perform some repetitive tasks. Still hope to eventually integrate some of these infra maintenance ops into nicer commands for wider use, but this is a better than nothing.

Add example script for resizing a group's machines

---

scripts/tcl/reset.yml

Slightly easier password reset

use prompts for passwords

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

This I think will prevent the situation we hit in https://dimagi-dev.atlassian.net/browse/HI-824 longer term.
india

Add 8GB swap to india couch nodes

---

environments/india/aws-resources.yml
environments/india/terraform.yml

They've already been stopped for months now, so we weren't incurring
charges or anything, but this is good cleanup we forgot to do.
india (but doesn't really affect anything)

Remove old india couch nodes

---

src/commcare_cloud/ansible/roles/bootstrap-machine/tasks/main.yml

Reset the Ansible SSH connection to force a re-login.

resent ssh connection after changing umask

---

environments/icds-cas/inventory/elasticsearch.csv

Remove old ES nodes from inventory
ICDS
Elasticsearch
* new ES nodes live
* all shards migrated
* old ES processes stopped
* encrytped drive on old ES nodes unmounted

remove old ES nodes from inventory

---

docs/setup/new_environment.md

Document adding a CommCare build to a server
none

Document adding a CommCare build to a server

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

These are the current values on the rate limits for ICDS. 
icds
nginx

Update mobile rate limiting

---

src/commcare_cloud/commands/ansible/service.py

Noticed this while messing with formplayer. Not sure if this was broken by https://github.com/dimagi/commcare-cloud/pull/3170 or not; if it was I didn't figure out quite how.
general

Fix `cchq <env> service formplayer status` etc

---

src/commcare_cloud/fab/operations/staticfiles.py

Same thing as https://github.com/dimagi/commcare-cloud/pull/3148, but I missed a place where this happens. I'm not sure why there are two places at the moment.
all
deploy

Change resource_versions.py -> yaml

---

environments/icds-cas/public.yml

Include localhost in /etc/hosts

---

src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml

* Changed retention period of wal archived logs
* ICDS

Changed retention period of wal archived logs

---

environments/icds-cas/app-processes.yml

To be used in combination with https://github.com/dimagi/commcare-hq/blob/master/corehq/ex-submodules/pillowtop/management/commands/create_checkpoints_for_merged_pillows.py
I have intentionally not included form pillows here, because it would add unknownuserspillow processor which adds some couch/redis hits and I think we may want to remove`FormSubmissionMetadataTrackerPillow` as well if we move the app status over. This does remove ~200 processes (and db connections) as it is now so I think its still worthwhile.
My plan:
1. Deploy on Monday/Tuesday (don't want to change this over weekend)
2. Figure out any corrections on pillow/partition sizing (probably need half of these servers at most)
3. investigate how hard it will be to remove those form pillows
4. If goes well, make change to …

Combine pillows for ICDS

---

environments/production/app-processes.yml

This is a change I'd rolled out a couple weeks ago while firefighting but forgot to PR.
production

Increase throughput on production celery queue

---

scripts/es_snapshot.py

Opening for opinions. Does this belong here or in a separate repo? It's standalone so could easily go in a separate repo.
####tl;dr
Python script that has the following tools:
* clean: delete all files in container that aren't part of 'live' ES snapshots
* verify: check snapshot version to see if all references files are present
* delete: delete snapshot version and all associated data
* info: print basic info
Currently only supports Swift as the target container.

tool for working with ES snapshots

---

environments/production/terraform.yml

They were previously not matching what was deployed
production

Fix terraform specs for production ES master nodes

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/staticfiles.py

See https://github.com/dimagi/commcare-hq/pull/25284 
all
Bugfix Pull Request
deploy

Stop removing resource_versions.yaml during deploy

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

add rate limit for multimedia downloads. apply rate limit for app downloads
ICDS
nginx

update icds rate limiting

---

decisions/0003-implement-one-command-to-deploy.md

Following up for from https://github.com/dimagi/commcare-cloud/pull/3204#issuecomment-528245936
@snopoke I wasn't sure on the 100% on what this should exactly cover, but I think I got the main points in here.
none

Add decision record about removal of hotfix_deploy

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/proxy.yml

Add proxy1 to the deploy in preparation for the flip. Will promote to the real proxy later by changing the elastic IP configuration in AWS
production

Add proxy1-production to deploy

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

No effect until https://github.com/dimagi/commcare-hq/pull/25285 is deployed. The default is that these are True, so there is no need to deploy other environments.
icds
localsettings/pillows

Configure ICDS combined pillows

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

jinja template

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

On Friday I routed traffic over to proxy1-production without issue, so we can kill this machine now.
production

Remove old proxy0-production

---

src/commcare_cloud/ansible/roles/thp/tasks/main.yml

fix typo in grub

---

src/commcare_cloud/cli_utils.py
src/commcare_cloud/colors.py
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/downtime.py
src/commcare_cloud/commands/ansible/helpers.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/commands/ansible/service.py
src/commcare_cloud/commands/command_base.py
src/commcare_cloud/commands/deploy.py
src/commcare_cloud/commands/fab.py
src/commcare_cloud/commands/migrations/couchdb.py
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/commands/validate_environment_settings.py
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/manage_commcare_cloud/configure.py
src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py
src/commcare_cloud/manage_commcare_cloud/install.py
src/commcare_cloud/patch_environ.py

As @emord suggested in https://github.com/dimagi/commcare-cloud/pull/3241, this changes our codebase to use semantic color aliases.
In a few cases, I took the liberty of changing colors to match the semantic values and thus the new convention.

Semantic CLI color aliases

---

src/commcare_cloud/fab/operations/release.py

after the pip install. Goes with https://github.com/dimagi/commcare-hq/pull/25333, but is backwards compatible.
all
pip install

Apply uninstall-requirements-after-install.txt during deploy

---

environments/icds-cas/app-processes.yml

Now that https://github.com/celery/celery/issues/4737 is merged and https://github.com/dimagi/commcare-cloud/pull/3227 is deployed, after the next code deploy we can combine these.
I also consolidated the case pillow servers. I can do something similar for forms once this is deployed and monitored for a bit. As of now I think we're just outside of running them all on one server.
icds
pillows

Combine XForm pillows

---

environments/staging/public.yml

temporarily remove `STATIC_URL` and `STATIC_CDN` from staging's localsettings
staging
localsettings

remove cdn from staging's settings to troubleshoot requirejs

---

environments/staging/public.yml

adds static cdn info back to staging localsettings
staging
localsettings

add static cdn back

---

environments/production/terraform.yml

Increasing memory for Elasticsearch nodes on the production environment

Increasing memory for Elasticsearch nodes on production environment

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

Adding auditd package and changing TCL object storage resolved Ip address

Adding auditd package

---

src/commcare_cloud/ansible/deploy_commcarehq.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/formplayer.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2
src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
src/commcare_cloud/ansible/roles/datadog/templates/jmx.yaml.j2
src/commcare_cloud/ansible/roles/formplayer/defaults/main.yml
src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
src/commcare_cloud/ansible/roles/formplayer/vars/main.yml
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/deploy.py
src/commcare_cloud/environment/main.py

Reverts dimagi/commcare-cloud#3253
This broke formplayer deploy. I must not have tested it at the commit I thought I had.

Revert "Set up formplayer in ansible"

---

src/commcare_cloud/ansible/deploy_commcarehq.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/formplayer.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2
src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
src/commcare_cloud/ansible/roles/datadog/templates/jmx.yaml.j2
src/commcare_cloud/ansible/roles/formplayer/defaults/main.yml
src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
src/commcare_cloud/ansible/roles/formplayer/vars/main.yml
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/deploy.py
src/commcare_cloud/environment/main.py

Reverts dimagi/commcare-cloud#3267

Revert "Revert "Set up formplayer in ansible""

---

src/commcare_cloud/ansible/roles/formplayer/defaults/main.yml
src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
src/commcare_cloud/ansible/roles/formplayer/vars/main.yml
src/commcare_cloud/commands/ansible/ansible_playbook.py

Followup PR to https://github.com/dimagi/commcare-cloud/pull/3253. Inspired in large part by this suggestion: https://github.com/dimagi/commcare-cloud/pull/3253#discussion_r325394831, but includes a couple other fix-ups.
all
- Change Pull Request (invisible)
formplayer (deploy / update-config)

Refactor formplayer ansible tasks logic for readability

---

docs/services/keepalived.md

* Adding docs for keepalived
ICDS

Adding docs for keepalived

---

src/commcare_cloud/ansible/roles/airflow/tasks/main.yml

Set new airflow var
icds
staging
india
See https://github.com/dimagi/pipes/pull/14

create airflow var for python env

---

src/commcare_cloud/ansible/roles/kafka/tasks/main.yml

* Corrected path to copy script
ICDS

Corrected path to copy script

---

src/commcare_cloud/ansible/group_vars/airflow.yml
src/commcare_cloud/ansible/roles/datadog/defaults/main.yml
src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
src/commcare_cloud/ansible/roles/datadog/templates/airflow.yaml.j2

@calellowitz @snopoke 
This integration already sends enough airlfow metrics I think.
(currently deploying/testing)

Add airflow datadog integration

---

src/commcare_cloud/manage_commcare_cloud/monitors/agent_check.yml
src/commcare_cloud/manage_commcare_cloud/monitors/disk.yml
src/commcare_cloud/manage_commcare_cloud/monitors/disk_icds.yml
src/commcare_cloud/manage_commcare_cloud/monitors/es_cluster_node_connection.yml
src/commcare_cloud/manage_commcare_cloud/monitors/projected_disk.yml
src/commcare_cloud/manage_commcare_cloud/monitors/site_down.yml

This is a routine thing to do, but will help if we're moving things around for e.g. https://github.com/dimagi/commcare-cloud/pull/3229 to start with a clean sync

Update datadog monitor files to match what is in datadog

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Add ICDS middleware to localsettings
ICDS
With https://github.com/dimagi/commcare-hq/pull/25472

local middleware

---

src/commcare_cloud/fab/operations/formplayer.py

Tiny change I forgot to include in https://github.com/dimagi/commcare-cloud/pull/3269

Simplify a boolean return statement

---

src/commcare_cloud/manage_commcare_cloud/monitors/ntp.yml

Monitor with alerting for NTP check.
Datadog

add monitor for ntp check

---

environments/production/aws-resources.yml
environments/production/inventory.ini

production inventory.ini was slightly out of sync

Run cchq production aws-fill-inventory

---

environments/icds-cas/postgresql.yml

Subset of https://github.com/dimagi/commcare-cloud/pull/3292 that doesn't require any other tasks
ICDS

remove UCR standby DBs from settings

---

environments/icds-cas/postgresql.yml

Switch to querying new Citus Master.
Will merge after switch is done on Sat 5th.
ICDS

move citus to vmware

---

src/commcare_cloud/ansible/roles/datadog/templates/airflow.yaml.j2

send tags to airflow datadog service check

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

@snopoke 
The first commit is how it already exists, the second commit is the new change to actual list. 
Also, sidenote, there's ton of other manual changes to icds_cas_commcare that are not in ansible.

Whitelist IPs nginx

---

docs/howto/add-celery-machines.md
src/commcare_cloud/ansible/roles/pgbouncer/defaults/main.yml

https://github.com/dimagi/commcare-cloud/pull/2863#issuecomment-537389730
none

Remove references to pgbouncer_hba

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

I think this was added for a test and is no longer needed.
@sravfeyn is that right?
staging

Remove rds_pg0_replica

---

src/commcare_cloud/ansible/roles/backups/tasks/set_up_check_s3_backups.yml

to avoid getting emails like
> [ALERT] No daily blobdb backup in last two days
on Sundays
swiss

Check backups before day change

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Add session access log file

---

src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/elasticsearch/templates/systemd/elasticsearch.service.j2

* Adding heap dump location for elasticsearch
ALL

Adding heap dump location for elasticsearch

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/group_vars/all.yml

Adding new RabbitMQ server in celery broker URL on ICDS env

Adding new RabbitMQ server in celery broker URL on ICDS env

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

* Disable groovy script execution on icds
* ICDS

Disable groovy script execution on icds

---

environments/india/terraform.yml

I did this a while ago while firefighting and never PR'd it. Not sure if it should stay like this (it doubled the RAM), but for now I just want to line it up with reality
india

Align india config with AWS

---

environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/postgresql/main.tf

and engine version (to accommodate changing instance class from t2 to t3).
I already rolled this out through the AWS console, so this change is to just to bring our config into alignment
staging

Change staging RDS instance class, size

---

docs/firefighting/celery.md

Add check_services to celery firefighting docs.
None
Celery docs

Add check_services to celery firefighting docs

---

src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

Goes with https://github.com/dimagi/commcare-hq/pull/25663
all
formplayer

Give SMS forms sticky sessions by regognizing alternative session header

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/terraform.yml

Also slightly increase couch5-india disk to avoid daily peaks over the 80% mark.
india

Downsize india couch machines

---

environments/india/terraform.yml

Resources are still largely unused: https://app.datadoghq.com/dashboard/6kr-yqd-dsy/rds-dashboard?from_ts=1569094447268&live=false&tile_size=m&to_ts=1571686447268&tpl_var_environment=india
india

Further downsize india rds

---

environments/production/app-processes.yml

Following up on https://dimagi-dev.atlassian.net/browse/SAASP-197
production

Combine production pillows

---

src/commcare_cloud/ansible/roles/airflow/templates/airflow.cfg.j2

statsd on on airflow machines

---

environments/icds-cas/postgresql.yml
src/commcare_cloud/ansible/roles/pgbouncer/defaults/main.yml
src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml

* PGBouncer Kernel settings changed according to 2ndquadrant report
* ICDS

PGBouncer Kernel settings changed according to 2ndquadrant report

---

environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Got the go-ahead from @snopoke to remove hwarehouse0-staging. Originally for ICDS to test setup, but no longer used
staging

Remove hwarehouse0-staging

---

environments/staging/terraform.yml

I think there's no reason for this machine to be as big as it is
staging

Downsize control0-staging

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Companion to https://github.com/dimagi/commcare-hq/pull/25683
icds
localsettings

Set STATIC_DATA_SOURCE_PROVIDERS to empty for ICDS

---

environments/india/terraform.yml

Lower CPU on formplayer1-india for cheaper machine.
india

Downsize formplayer1-india

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

ICDS local settings for Kafka audit logging.
https://github.com/dimagi/commcare-hq/pull/25799

add log settings for kafka audit logging

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Reverts dimagi/commcare-cloud#3370
This is causing an error during startup failing for some reason. Reverting till I figure it out.

Revert "add log settings for kafka audit logging"

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Revert 3374 revert 3370 sk/kafka audit

---

src/commcare_cloud/fab/fabfile.py

Updated the Tuesday translation notice to be on Wednesday since deploys happen weekly on Wednesdays now.
Production
deploy

update translation notice to be wednesday instead of tuesday

---

environments/india/public.yml

Adding ICDSAuditMiddleware to India local settings to tracks user activity on dashboard
@calellowitz  this is for the Usage report testing.

Added ICDS Audit Middleware for India

---

docs/firefighting/index.md

* Updating firefighting doc to handle WAL deletion
* ICDS

Updating firefighting doc to handle WAL deletion

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Adding Swap size of 8GB to formplayer servers on prod env

Adding Swap size of 8GB to formplayer servers on prod env

---

environments/production/app-processes.yml

We've had it not be able to keep up recently, so adding some concurrency may help.
production

Increase max concurrency on production celery_periodic

---

docs/firefighting/index.md

* Update firefighting doc for wal deletion
* ALL

Update firefighting doc for wal deletion

---

docs/setup/new_environment.md

These are some changes I made while going through the process of setting up a monolith.  Got more coming, but figure this'll be a start.  Read commit-by-commit - the messages explain the changes.
None
New environment documentation

Misc docs updates for monolith setup

---

docs/system/hosting-considerations.md

"Cluster Management" is the more broadly applicable section of the two - figured it makes sense to start with it, rather than saying "skip to ... if this doesn't apply".  Might break these out in to two docs at some point.
None
"Hosting considerations" docs

Reorganize  "Hosting Considerations" docs

---

src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

Thanks @millerdev for noticing! Couldn't tell from the history if it ever worked, but anyway this makes it do what I always intended it to and pass on the status code.

Make django-manage use manage.py's return code as its own

---

src/commcare_cloud/commands/fab.py
src/commcare_cloud/fab/README.md

Minor. There might be other docs that are outdated now that running fab directly is no longer supported, these are just the ones I ran into today.
None
Docs Pull Request

Update docs and fix `fab -l`

---

src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2

Commit by commit. These options are to help debug or potentially fix the apparently unbounded memory growth issues on formplayer that we've had since Nov 11.
all (but targeting prod)

Change formplayer java options

---

docs/commcare-cloud/env/index.md
docs/setup/new_environment.md

Rename default user group to "admins".  In conjunction with https://github.com/dimagi/sample-environment/pull/3

Rename default user group to "admins"

---

environments/icds-cas/app-processes.yml

https://dimagi-dev.atlassian.net/browse/IIO-595
Temporary measure to reduce load on ES
ICDS

half number of workers for reminder_rule queue

---

src/commcare_cloud/fab/utils.py

Followup from https://github.com/dimagi/commcare-cloud/pull/3408

Don't attempt to generate diff URL w/o deploy tags

---

environments/icds-cas/postgresql.yml

Not sure why we don't have this already, but seems like a good thing for us to add.
icds
citus

Add pg_stat_statements to icds citus

---

src/commcare_cloud/ansible/deploy_postgres.yml
src/commcare_cloud/ansible/roles/pgbouncer/defaults/main.yml
src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.ini.j2
src/commcare_cloud/environment/schemas/postgresql.py

fix pgbouncer missing vars

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml
src/commcare_cloud/ansible/roles/nginx/vars/cchq_http_j2me.yml
src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
src/commcare_cloud/ansible/roles/nginx/vars/pna_ssl.yml
src/commcare_cloud/ansible/roles/nginx/vars/reach_ssl.yml

these will be managed by django moving forwards:
- dependent on https://github.com/dimagi/commcare-hq/pull/26089
https://docs.google.com/document/d/1gg1sAJ6Qd9yb5mzIwfTKw7h8CyVTWG8EMJpIrvYIBbU/edit
- all
Nginx
```paste below
cchq <env> ansible-playbook deploy_proxy.yml --limit=proxy
```
* diff
```paste below
server_name example.com;
-              add_header X-Frame-Options SAMEORIGIN;
```

remove X-Frame-Options headers from nginx configs

---

docs/howto/Migrating-zookeeper.md

* Doc for migrating zookeeper
* ALL

Doc for migrating zookeeper

---

src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.users.j2

give default value

---

environments/icds-cas/postgresql.yml

* Switch pgmain and pgsynclog 
* ICDS 

Switch pgmain and pgsynclog

---

environments/production/terraform.yml

Revert "Add more RAM to django_manage VM"

---

src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/inventory_lookup/getinventory.py
src/commcare_cloud/fab/checks/check_servers.py

CommCare HQ has a number of custom Django checks which help to validate settings and configuration. This adds an option to running these after updating localsettings.

run django checks after updating config

---

src/commcare_cloud/ansible/roles/datadog/tasks/main.yml

* Add DD integration tag on datadog-parser pull
* ALL

Add DD integration tag on datadog-parser pull

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/airflow.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/formplayer.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/management_commands.yml

* Fix permission issue on https://github.com/dimagi/commcare-cloud/pull/3460 
* ALL

Fixed permission issue

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/pillowtop.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/proxy_websockets.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/webworkers.yml

I think this should have also gone with https://github.com/dimagi/commcare-cloud/pull/3466/ ?
@rohit-dimagi @snopoke

fix permission issue

---

environments/icds-cas/app-processes.yml

Increases the kafka-ucr-main pillow until we can remove the added data sources
Increase xform-pillow-dashboard because that's been lagging today
decrease xform-pillow-non-dashboard for fewer writes to ES and because it was actually quite up to date.
icds

Change ICDS pillow config

---

environments/icds-cas/inventory/other.csv

* Remove formplayer on kvm host
* ICDS

Remove formplayer on kvm host

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

This was already in the config - just adding it to ansible

add app profile location to nginx

---

src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml

Deployed to staging and clicked around a bit, didn't see anything unusual.

Upgraded LESS

---

environments/icds-cas/inventory/other.csv

* remove old airflow machine
* ICDS

remove old airflow machine

---

environments/icds-cas/app-processes.yml

@snopoke 
Reducing this to see if the ES issue related to cache size hitting a max limit.

reduce xform es pillow chunk size

---

src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

By running tmux as the logged in user it solves a few problems:
* makes it easy to see who's tmux is running by looking at the process owner
* prevents joining another users tmux session when running a command

run tmux as logged in user instead of cchq

---

src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

* remove Blocked PPA for python3.6
* ALL

Rk/remove ppa python3.6

---

src/commcare_cloud/ansible/roles/postgresql/tasks/main.yml

* Create dummy file for emergency delete
* ICDS

Create dummy file for emergency delete

---

environments/jenkins/inventory.ini

As per @shubham1g5's request: https://github.com/dimagi/commcare-cloud/pull/3510#discussion_r365041378.
jenkins

Add swap to jenkins_mobile_agent_2

---

commcare-cloud-bootstrap/bootstrap.sh
docs/howto/enable-https.md

These examples are wrong so I'm fixing them; came out of conversation around https://dimagi-dev.atlassian.net/browse/ICDS-1173.

Fix examples of deploy commands with ignore_kafka_checkpoint_warning

---

environments/icds-cas/migrations/nic_to_tcl/README.md
environments/icds-cas/migrations/nic_to_tcl/README_couch.md
environments/icds-cas/migrations/nic_to_tcl/README_elastic.md
environments/icds-cas/migrations/nic_to_tcl/README_postgresql.md
environments/icds-cas/migrations/nic_to_tcl/README_riak.md
environments/icds-cas/migrations/nic_to_tcl/README_static-files.md

Add some more context to the NIC to TCL migration docs

update migration docs

---

docs/howto/Airflow_setup.md
docs/index.md
docs/services/airflow.md
docs/services/airflow/migration_guide.md

Move airflow docs and add link in index. Also include steps to remove the old supervisor configs

more airflow migration docs

---

environments/icds-cas/app-processes.yml

* Increase xform dashboard and non-dashboard pillow process
* ICDS

Increase xform dashboard and non-dashboard pillow process

---

environments/production/public.yml

Pointing TDH site to production proxy server

Pointing TDH site to production proxy server

---

environments/production/terraform.yml

See commits for more detail, but pretty straightforward. Downsizing celery12-production and pillow1-production.
production

Resize machines planned

---

environments/india/public.yml

Es upgrade on India environment to 2.4.6 version
This is a cleanup of https://github.com/dimagi/commcare-cloud/pull/3518

Update india public.yml for ES upgrade

---

environments/production/public.yml

Update prod public.yml for ES upgrade

Update prod public.yml for ES upgrade

---

src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml

updating cloud-aws plugin name for elastic search 2.4.6 version

updating cloud-aws plugin for elasticsearch 2.4.6 version

---

docs/services/nginx.md
docs/services/nginx/migration_guide.md

* Doc for Proxy migration
* ALL

Doc for Proxy migration

---

src/commcare_cloud/manage_commcare_cloud/monitors/disk_rw_status.yml

* Adding monitor for disk status check
* ICDS

Adding monitor for disk status check

---

environments/icds-cas/postgresql.yml
src/commcare_cloud/ansible/deploy_postgres.yml
src/commcare_cloud/ansible/roles/pg_repack/defaults/main.yml
src/commcare_cloud/ansible/roles/pg_repack/files/pg_repack.py
src/commcare_cloud/ansible/roles/pg_repack/tasks/main.yml
src/commcare_cloud/environment/schemas/postgresql.py

* Python script to run pg_repack if conditions are met. 
* Ansible role to install pg_repack and configure the cron job with the script
ICDS
PostgreSQL / pg_repack
Already rolled out to ICDS

pg repack script, install and cron

---

docs/howto/transfer-domain.md

Docs changes to accompany https://github.com/dimagi/commcare-cloud/pull/3525

Add instructions for setting up a mobile alias URL

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/nginx/files/dynamic_cfg_change_nginx
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml

* Adding dynamic config script for ICDS
* ICDS

Adding dynamic config script for ICDS

---

environments/icds-cas/app-processes.yml
environments/icds-cas/public.yml

This should allow the data needed for the app status report to be updated more quickly while ES is having issues.
ICDS

separate form meta pillow from xform pillow

---

docs/index.md
docs/services/pillowtop.md
docs/services/pillwotop/split.md

commcare-cloud docs for pillowtop
NA

pillowtop docs

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

separate rate limit for profile downloads

---

environments/swiss/public.yml

Elasticsearch upgrade on Swiss environment

Elasticsearch upgrade on Swiss environment

---

src/commcare_cloud/ansible/roles/nginx/files/dynamic_cfg_change_nginx

Fix env problem

---

src/commcare_cloud/environment/schemas/app_processes.py

Prevent mistypes in key names.
NA

use schema to validate pillow process settings

---

src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml

@snopoke 
https://www.elastic.co/guide/en/elasticsearch/reference/master/vm-max-map-count.html

Tune vm.max_map_count

---

environments/production/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Partner PR to https://github.com/dimagi/commcare-hq/pull/26546
production

Set STALE_EXPORT_THRESHOLD to 30 min on production

---

docs/services/postgresql.md
docs/services/postgresql/migrating_plproxy.md

Doc for plproxy migration

---

environments/production/terraform.yml
scripts/example-terraform-resize-disk.sh

Maintenance I did last week. I can't wait to scale these bad boys down in a few months!
production

Increase couch disk

---

environments/production/terraform.yml

This I rolled out during the server issues Mon/Tue, and I think it's a good long term size for the machine.
production

Resize pgmain0-production back to what it was a few weeks ago

---

src/commcare_cloud/fab/operations/staticfiles.py

This will be necessary to support https://github.com/dimagi/commcare-hq/pull/26601

Run fab npm_install on proxy machine as well

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/sentry.py

previous API has changed
https://docs.sentry.io/api/events/get-group-events/

update sentry export

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/datadog/tasks/main.yml
src/commcare_cloud/ansible/roles/datadog/templates/datadog.conf.j2
src/commcare_cloud/ansible/roles/datadog/vars/main.yml
src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

* Parser changed to use a single function to parse all nginx timing data.
* https://github.com/dimagi/datadog-parsers/pull/37
* Use different log paths for different sites
ICDS
Datadog

update DD log parsing for nginx

---

src/commcare_cloud/ansible/roles/elasticsearch/templates/systemd/elasticsearch.service.j2

* Add restart always to elasticsearch
* ALL

Add restart always to elasticsearch

---

environments/production/app-processes.yml
src/commcare_cloud/environment/schemas/app_processes.py

ILS Gateway ended a while ago.

Removed ils-gateway sms queue

---

environments/india/terraform.yml

* change instance type of proxy
* india
Logstash and filebeat deployment need extra RAM.

change instance type of proxy

---

environments/icds-cas/public.yml

ES upgrade on ICDS

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Remove rate limit on app downloads: https://dimagi-dev.atlassian.net/browse/IIO-730
We still rate limit access to `profile.ccpr`.
ICDS
Already rolled out

remove rate limit on app downloads

---

environments/icds-cas/elasticsearch.yml

Index is very small so no need to sharding
ICDS

limit domain ES index to a single shard

---

src/commcare_cloud/ansible/roles/nginx/files/dynamic_cfg_change_nginx

Modify script

---

environments/icds-cas/app-processes.yml

* Increase submission_reprocessing_queue process count
* ICDS

Increase submission_reprocessing_queue process count

---

environments/_users/dimagi.yml

Remove jemord from dimagi users

---

src/commcare_cloud/ansible/roles/pg_repack/files/pg_repack.py

only look at tables in public schema

---

environments/icds-cas/public.yml

* change proxy ip in `public.yml`
* ICDS

change proxy ip in icds env

---

environments/production/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://dimagi-dev.atlassian.net/browse/SAAS-10245
Companion PR to https://github.com/dimagi/commcare-hq/pull/26670
production

Set REQUIRE_TWO_FACTOR_FOR_SUPERUSERS on production

---

environments/production/terraform.yml

(Already rolled out)
production

Increase size of formplayer2-, formplayer3-production

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/public.yml
src/commcare_cloud/ansible/requirements.yml
src/commcare_cloud/ansible/roles/deploy_logstash.yml

* Logstash on india env 
* INDIA (Rolled out already)

Logstash on india env

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

remove rate limit on multimedia

---

requirements.txt

requirements.txt was out of sync with setup.py, so ran `make requirements` to update

Run make requirements

---

environments/production/terraform.yml

Increase couch12 data volume size

---

docs/howto/transfer-domain.md

Add more documentation on the process of transferring a domain.   I need to add more tooling and docs around wiping data, will do that separately.
None

Transfer domain documentation

---

docs/firefighting/index.md

Some takeaways from @millerdev's firefighting this morning is that some key elements of what to do in this situation were missing from the docs, so this is an attempt to fill that in.

Update firefighting docs for couch disk full situation

---

docs/firefighting/index.md

Note in firefighting docs that Dimagi stores couch data in triplicate

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://github.com/dimagi/commcare-hq/pull/26695/ is merged

allow ES form index customization

---

environments/icds-cas/inventory/other.csv
environments/icds-cas/public.yml
src/commcare_cloud/ansible/deploy_common.yml
src/commcare_cloud/ansible/deploy_lpar2rrd.yml

* setting lpar2rrd os agent
* ICDS 

setting lpar2rrd os agent

---

src/commcare_cloud/ansible/roles/nginx/templates/site.j2
src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Simplify mapping and add comments + fix bug
ICDS

refactor geo mapping

---

src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_flower.conf.j2

This has been bothering me for probably a year. Not sure why it only occurred to me now how very easy it is to fix.

Kill flower after 10s if it hangs on deploy

---

src/commcare_cloud/ansible/deploy_lpar2rrd.yml

* added missing dir path
* ICDS

added missing dir path

---

src/commcare_cloud/ansible/roles/datadog/defaults/main.yml
src/commcare_cloud/ansible/roles/datadog/templates/redisdb.yaml.j2

* add redis password in datadog conf
* ALL

add redis password in datadog conf

---

src/commcare_cloud/manage_commcare_cloud/monitors/pillow_lag.yml

Corresponds to this monitor: https://app.datadoghq.com/monitors/16132440
currently just alerting on production

Add pillow_lag datadog monitor

---

src/commcare_cloud/manage_commcare_cloud/monitors/pillow_lag.yml

Followup to https://github.com/dimagi/commcare-cloud/pull/3679. We're receiving alerts in slack now.

Fix notifications on pillow lag metrics; tweak config

---

environments/development/inventory.ini
src/commcare_cloud/ansible/deploy_etckeeper.yml
src/commcare_cloud/ansible/deploy_http_proxy.yml
src/commcare_cloud/ansible/requirements.yml

* remove Etckeeper external role
* ALL

remove Etckeeper external role

---

src/commcare_cloud/commands/deploy.py

Followup for https://github.com/dimagi/commcare-cloud/pull/3676/

Fixed deploy script to no longer require commcare-rev

---

environments/staging/public.yml

Removing temp domain from staging proxy server

Removing temp domain from staging proxy server

---

environments/production/public.yml
environments/staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Companion PR to https://github.com/dimagi/commcare-hq/pull/26747. I already rolled this out this morning and it seems to have been effective
production, staging

Add USE_KAFKA_SHORTEST_BACKLOG_PARTITIONER setting (production + staging)

---

environments/icds-staging/public.yml
environments/india/public.yml

this is set statically in localsettings

remove legacy setting

---

environments/staging/inventory.ini
environments/staging/terraform.yml

Creating secondary volumes with encryption for CouchDB servers on the staging environment.

Creating secondary volumes with encryption for CouchDB servers on staging environment

---

environments/production/terraform.yml

Disk expansion on ES data nodes on the production environment

Disk expansion on ES data nodes on production environment

---

environments/production/app-processes.yml

Followup to yesterday's change
production

Have one process per partition for case-pillow on production

---

environments/production/terraform.yml

See https://github.com/dimagi/commcare-cloud/pull/3368
Reverts dimagi/commcare-cloud#3451

Add more RAM to django_manage VM (again)

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/datadog/vars/main.yml

* remove dogstream from proxy server
* ALL

remove dogstream from proxy server

---

environments/production/app-processes.yml

There was another burst today that this helped get through, so I'm going to leave at this higher setup.
production

Double processes for reminder_case_update_queue

---

src/commcare_cloud/ansible/roles/kafka/templates/kafka-server.service.j2

* Incread fd limit on kafka
* ALL

Incread fd limit on kafka

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
src/commcare_cloud/ansible/roles/datadog/templates/datadog.conf.j2

Add `METRICS_PROVIDERS` setting to support https://github.com/dimagi/commcare-hq/pull/26876
icds, icds-staging, india, production, pna, staging, swiss

metrics providers

---

environments/staging/inventory.ini
src/commcare_cloud/ansible/encrypt_dir.yml
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/ecryptfs/tasks/main.yml
src/commcare_cloud/ansible/roles/ecryptfs/tasks/tmp.yml
src/commcare_cloud/commands/terraform/aws.py

Making ecryptfs as optional in Ansible playbooks

Making ecryptfs as optional in Ansible playbooks

---

environments/production/terraform.yml

Back to what it was in early Jan
production

Double production RDS pgshard machine sizes

---

environments/icds-cas/app-processes.yml

* Increase form reprocessing queue
* ICDS

Increase form reprocessing queue

---

src/commcare_cloud/ansible/deploy_common.yml
src/commcare_cloud/ansible/roles/lpar2rrd/defaults/main.yml
src/commcare_cloud/ansible/roles/lpar2rrd/handlers/main.yml
src/commcare_cloud/ansible/roles/lpar2rrd/tasks/install_agent.yml
src/commcare_cloud/ansible/roles/lpar2rrd/tasks/install_master.yml
src/commcare_cloud/ansible/roles/lpar2rrd/tasks/main.yml
src/commcare_cloud/ansible/roles/lpar2rrd/templates/apache2.conf.j2

* create separate role for lpar2rrd
* ICDS

create separate role for lpar2rrd

---

environments/icds-cas/app-processes.yml

Reverts dimagi/commcare-cloud#3724

Revert "Increase form reprocessing queue"

---

docs/setup/new_environment.md

https://dimagi-dev.atlassian.net/browse/SC-303
Add instructions to the new environment doc to set the domain name
None

Instruct users to update SITE_HOST

---

environments/staging/inventory.ini
environments/staging/terraform.yml

Moving staging ES servers to EBS encrypted volumes

Moving staging ES servers to EBS encrypted volumes

---

environments/production/terraform.yml

increasing disk size for celery servers on prod environment

Increasing disk size for celery servers on prod environment

---

src/commcare_cloud/ansible/deploy_logstash.yml

* https://dimagi-dev.atlassian.net/browse/IIO-794
* ICDS

Adjust kernel buffer

---

src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/templates/systemd/elasticsearch.service.j2

https://dimagi-dev.atlassian.net/browse/IIO-731
* ALL

Disable java heap dump on elasticsearch

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2

* https://dimagi-dev.atlassian.net/browse/IIO-808
* ALL

fix cpu count for nginx worker process

---

src/commcare_cloud/ansible/requirements.yml
src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2

* https://dimagi-dev.atlassian.net/browse/IIO-807
ALL

Logging format change for Nginx

---

environments/staging/inventory.ini
environments/staging/terraform.yml

Moving staging Kafka ecryptfs volume to EBS encrpted volume

Moving staging Kafka ecryptfs volume to EBS encrpted volume

---

environments/icds-staging/public.yml

* Allow Unixadmin TO login with ssh password 
* ICDS-STAGING

Allow unixadmin with password login

---

environments/staging/inventory.ini
environments/staging/terraform.yml

Moving Redis ecryptfs volume to EBS encrypted volume

Moving Redis ecryptfs volume to EBS encrypted volume

---

control/init.sh
docs/setup/manual_installation.md

https://dimagi-dev.atlassian.net/browse/CDTW-2
commcare install process via init.sh and 
setup doc for manual installation updated

update git-hook in init.sh and updates setup docs

---

environments/staging/inventory.ini
environments/staging/terraform.yml

Moving Staging formplayer and pgproxy server volumes to EBS encrypted volumes

Moving Staging formplayer and pgproxy server volumes to EBS encrypted volumes

---

src/commcare_cloud/ansible/roles/devops_scripts/tasks/main.yml
src/commcare_cloud/ansible/roles/devops_scripts/templates/intruder.sh
src/commcare_cloud/ansible/setup_devops_scripts.yml

https://dimagi-dev.atlassian.net/browse/IIO-829
ICDS

added intruder.sh script

---

src/commcare_cloud/ansible/roles/lpar2rrd/tasks/install_agent.yml

Password expiry to never for lpar2rrd agent
ICDS

Password expiry to never

---

src/commcare_cloud/ansible/roles/devops_scripts/templates/intruder.sh

https://dimagi-dev.atlassian.net/browse/IIO-829
ICDS

updated to collect sudo attempts

---

environments/india/terraform.yml

Increase disk size for ES servers on India environment

Increase disk size for ES servers on India environment

---

environments/india/public.yml

Making ES heapsize as half of the Memory on India env

Making ES heapsize as half of the Memory on India env

---

environments/production/terraform.yml

Encode updates to pgmain0-production rolled out in RDS console last week

---

environments/icds-staging/inventory/commcare.csv
environments/icds-staging/inventory/postgresql.csv

https://dimagi-dev.atlassian.net/browse/IIO-527
ICDS-staging
Changing airflow host from pg1 to web1

changes the airflow host in icds-staging environment

---

environments/icds-staging/inventory/elasticsearch.csv

added elasticsearch master tio icds-staging

---

environments/icds-staging/public.yml

changing name for es-cluster to icds-staging
icds-staging

updated es cluster name for icds-staging

---

environments/india/terraform.yml

Updating Terraform changes in India environment

Updating Terraform changes in India environment

---

environments/icds-staging/postgresql.yml
environments/icds-staging/proxy.yml
environments/icds-staging/public.yml

@shyamkumarlchauhan here are some more changes I'm recommending for icds-staging env. I'll comment inline. I got these by comparing with `icds-cas` settings.
Note this is a PR into: https://github.com/dimagi/commcare-cloud/pull/3793

updates to icds staging settings

---

environments/icds-staging/proxy.yml
environments/icds-staging/public.yml

setup cas_site_host value for icds-staging
icds-staging

updated cas_site_host value

---

environments/icds-cas/prometheus.yml
environments/icds-cas/public.yml
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/paths.py
src/commcare_cloud/environment/schemas/prometheus.py

* https://dimagi-dev.atlassian.net/browse/IIO-725
ALL

Create env file for prometheus

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2

Volume backup for Elasticsearch on India and Production environment

Volume backup for Elasticsearch on India and Production Enviornment

---

src/commcare_cloud/ansible/roles/common/files/audit.conf
src/commcare_cloud/ansible/roles/common/tasks/audit.yml
src/commcare_cloud/ansible/roles/common/tasks/main.yml

* https://dimagi-dev.atlassian.net/browse/IIO-851
* ALL

logging for all commands run by all user

---

docs/index.md
docs/system/maintenance-expectations.md

From [3rd Party Devops Communication Strategies](https://docs.google.com/document/d/1Ra7jZIf9sm8z_eZNLNbzLE7baBfyKcEMYecg0hl4uwQ/edit#heading=h.7mybl9t4a4zw)
With some additional elaboration

Add documentation for maintenance expectations

---

environments/production/terraform.yml
environments/staging/aws-resources.yml

in preparation for much higher usage
Looking to roll this roll this out late tonight (~11pm ET)
production

Double size of production formplayer machines

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2

https://dimagi-dev.atlassian.net/browse/IIO-864
* ALL

compress audio/images files

---

environments/icds-cas/prometheus.yml
src/commcare_cloud/ansible/deploy_prometheus.yml
src/commcare_cloud/ansible/requirements.yml

https://dimagi-dev.atlassian.net/browse/IIO-725
* ICDS

More prometheus exporter

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

adding whitelisted ip address to the code
ICDS

added whitelisted IP addresse to the code

---

environments/india/aws.yml
environments/production/aws.yml
environments/staging/aws.yml
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/paths.py
src/commcare_cloud/environment/schemas/aws.py

We're switching over to using AWS SSO for access management across our AWS accounts. There's going to be a bit of pain here, but I'll be careful to create accounts for everyone that's used console or CLI access in the last 90 days to minimize short term risk; on top of that, reach out to me if you need access that hasn't been provided. I'll also need to update our related docs on confluence. Overall, the new setup is much simpler for securely managing access to all of the accounts in our AWS Organization.

AWS SSO CLI credentials

---

src/commcare_cloud/commands/terraform/aws.py

Followup to https://github.com/dimagi/commcare-cloud/pull/3819
`_has_valid_session_credentials_for_sso` is a mediocre heuristic
so just assume it was wrong and refresh the sso credentials before failing hard
inside `_sync_sso_to_v1_credentials`
SaaS only

Try refreshing SSO before failing hard

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
src/commcare_cloud/terraform/modules/ga_alb_waf/variables.tf
src/commcare_cloud/terraform/modules/network/main.tf
src/commcare_cloud/terraform/modules/network/outputs.tf
src/commcare_cloud/terraform/modules/openvpn/main.tf
src/commcare_cloud/terraform/modules/server/main.tf

This encodes the POC I did on staging to insert a Web Application Firewall between our machines and the internet, so traffic is filtered before it even gets to our nginx proxy.
This applies cleanly on staging, and I've also rolled it out on production. (Have not yet done anything on india, but likely will there too.)
production, staging, india

Set up Global Accelerator => Application Load Balancer (for WAF)

---

environments/production/app-processes.yml

Just a routine bump in preparation for increased SMS usage
production

Increase sms_queue concurrency on production

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.tfvars.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/server/main.tf
src/commcare_cloud/terraform/modules/server/variables.tf

production immediately, feature available to production, india, staging

Add ability to configure encrypted root drives in terraform

---

environments/production/proxy.yml
src/commcare_cloud/environment/schemas/proxy.py

From takeaways from security audit. Already rolled out
production

Change nginx's ciphers on production

---

environments/india/terraform.yml
environments/production/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/environment/schemas/terraform.py

Making EBS encryption default value as True

Making EBS encryption default value as True

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2

Already rolled out
production, india, staging (only affects how devs access AWS Console/API)

Remove IAM users for credential_style = sso

---

environments/production/terraform.yml

I think this was just a mistake in https://github.com/dimagi/commcare-cloud/pull/3840
production

Put back volume_encrypted: yes where it was before

---

environments/india/terraform.yml
environments/production/terraform.yml
src/commcare_cloud/environment/schemas/terraform.py

Making Default encryption value True for Block devices

Making Default encryption value True for Block devices 

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

Noticed the health checks were incorrectly reporting as "unhealthy"
production

Fix ALB health check in terraform

---

environments/production/public.yml

Our CPU usage is never particularly high throughout the day, so I believe we can afford to do this.
production

Roll out 24h compaction on all dbs on production

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Companion for https://github.com/dimagi/commcare-hq/pull/27559

Track load from ES on ICDS

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

production/staging/(eventually india)

Add idle timeout to ALB of 10 minutes

---

src/commcare_cloud/commands/terraform/constants.py
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
src/commcare_cloud/terraform/modules/ga_alb_waf/variables.tf

terraform's support for wafv2 is still in progress, so I'm putting things into code as they become available.
production/staging/india

Add regexes for custom WAF rule

---

environments/_users/icds-aws.yml
environments/icds-cas/meta.yml

remove fissionlab access from icds

---

environments/icds-staging/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-527
icds-staging

updated default email for icds-staging

---

environments/india/public.yml

Updating CouchDB local settings

Updating CouchDB local settings

---

environments/production/terraform.yml

instance type change for ES masters on prod env

Instancetype change for esmasters on prod env

---

environments/icds-staging/public.yml

remove unwanted configurations.
icds-staging

remvoed unwanted configurations

---

environments/india/terraform.yml

Increasing RAM for Elasticsearch masters on India environment

Increasing RAM for elasticsearch masters on India enviornment

---

environments/icds-staging/public.yml

adding redis config for websocket

---

environments/icds-staging/app-processes.yml
environments/icds-staging/inventory/citusdb.csv

Removed celery from db1 ND DB2
ICDS-STAGING

removed celery from db1 and db2

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2
src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

https://dimagi-dev.atlassian.net/browse/SAAS-10914
production, staging, india

Let x forwarded for pass through

---

docs/services/kafka/upgrade.md
environments/icds-staging/public.yml
src/commcare_cloud/ansible/roles/kafka/defaults/main.yml
src/commcare_cloud/ansible/roles/kafka/tasks/main.yml
src/commcare_cloud/ansible/roles/kafka/templates/server.properties.j2

https://dimagi-dev.atlassian.net/browse/IIO-752
* ICDS-STAGING

updating kafka on icds staging

---

src/commcare_cloud/ansible/deploy_postgres.yml

exclude plproxy from wal drive setup

---

src/commcare_cloud/commands/ansible/ansible_playbook.py

It's something we added for backwards compatibility with a mistake we made,
so we need that option, but we don't want to apply it to any new hosts.
Follow up to https://github.com/dimagi/commcare-cloud/pull/3887
None unless you try to use the banned config on a new machine (current machines using it on production, staging are retroactively allowed)

Refuse to set up new machines that have datavol_fstype=xfs

---

src/commcare_cloud/commands/terraform/constants.py
src/commcare_cloud/commands/terraform/terraform.py

Goes along with https://github.com/dimagi/commcare-hq/pull/27814. Thanks for the suggestion @millerdev!

Move WAF regex compaction from commcare-hq to here

---

environments/production/app-processes.yml
environments/production/terraform.yml

Add memory to production formplayer

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2

Removing the old ES servers from the Production env

Removing the old ES servers from the Production env

---

src/commcare_cloud/commands/terraform/constants.py

https://dimagi-dev.atlassian.net/browse/SAAS-10996
rolls out https://github.com/dimagi/commcare-hq/pull/27834
production

Update WAF rules

---

environments/production/app-processes.yml

Increase production ucr_queue concurrency

---

environments/production/public.yml

Increase formplayer_archive_time_spec on production

---

environments/icds-cas/app-processes.yml

Increasing submission reprocessing worker to churn through huge backlog after we faced object storage downtime.
* ICDS

Increasing submission reprocessing queue

---

environments/india/public.yml

* https://dimagi-dev.atlassian.net/browse/IIO-752
INDIA

Kafka Upgrade

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2

Removing the old Elasticsearch servers from production env

Removing the old elasticsearch servers from production env

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/formplayer.yml

Looks like this was broken in https://github.com/dimagi/commcare-cloud/pull/3796 but it was an easy fix
all

Fix formplayer deploy

---

environments/production/terraform.yml

Terminating old Elasticsearch servers

Terminating old Elasticsearch servers

---

docs/firefighting/index.md

More specific docs

---

environments/icds-cas/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-885
* ICDS

Increased memory for redis

---

environments/india/terraform.yml

Increasing the RAM for formplayer on India environment

Increasing the RAM for formplayer on India environment

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2

Removing web10 server from production env

Removing web10 server from production env

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/deploy.py
src/commcare_cloud/environment/schemas/meta.py

https://dimagi-dev.atlassian.net/browse/SC-302
Gonna make this the default for 3rd party envs - should remove one piece of complexity from maintaining a setup, at the expense of a small amount of downtime.
:classical_building: 
None

Add option to always deploy formplayer

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/deploy.py
src/commcare_cloud/environment/schemas/meta.py

https://dimagi-dev.atlassian.net/browse/SC-302
------
Making Formplayer deployment configurable.
if nothing has been mentioned in the component if it will verify for always_deploy_formplayer variable in the config file and it is present respective component will be deployed. If not present then 'commcare' will be deployed.

reading deploying component from config file. Updated index.md file with deployment changes

---

environments/production/terraform.yml

Terminating web10 on production environment

Terminating web10 on production enviornment

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
src/commcare_cloud/terraform/modules/ga_alb_waf/variables.tf

Add config for NO_WWW_SITE_HOST in terraform ga_alb_waf

---

docs/services/rabbitmq.md
docs/services/rabbitmq/upgrade.md
environments/staging/public.yml
src/commcare_cloud/ansible/roles/rabbitmq/defaults/main.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/install_latest.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/install_old.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/IIO-880
staging

RabbitMQ upgrade to version 3.8.5

---

src/commcare_cloud/ansible/roles/devops_scripts/files/audit_log.sh

Updated the script to collect the audit log requirements.
ICDS
ICDS-STAGING

updated audit log script

---

src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

Add full WAF ACL to terraform

---

src/commcare_cloud/commands/terraform/templates/variables.tf.j2

Updating Bionic AMI

---

src/commcare_cloud/environment/schemas/meta.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/release.py

PR into https://github.com/dimagi/commcare-cloud/pull/3934
Update deploy to support pulling in changes from 'extra' git repos: https://docs.google.com/document/d/1z21WtL33XpLdmn5GnC58Tkb5ra8tm20UYymAIrg9wgg/edit#
Tested on staging as follows:
```
git_repositories:
- url: https://github.com/dimagi/metrics_analysis.git
dest: metrics_analysis
version: master
requirements_path: requirements.txt
$ cchq staging fab setup_limited_release
```

deploy changes to support multiple repos

---

src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml
src/commcare_cloud/fab/const.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/offline.py
src/commcare_cloud/fab/operations/staticfiles.py

https://dimagi-dev.atlassian.net/browse/SAAS-10881
right now only staging should be affected, as it's the only branch with `yarn.lock`

Bower to yarn updates when yarn.lock is present

---

environments/icds-cas/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-752
* ICDS

Upgrade kafka on icds

---

environments/icds-cas/public.yml
environments/icds-staging/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-880
Setting up RabbitMQ in cluster in icds-staging environment.
and making the entry in public.yml of ICDS environment.
ICDS
ICDS-STAGING

adding RabbitMQ for cluster configuration

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

Followup to https://github.com/dimagi/commcare-cloud/pull/3933
SaaS envs

Add kinesis firehose policy

---

environments/icds-cas/prometheus.yml

https://dimagi-dev.atlassian.net/browse/IIO-883
* ICDS

Add smtp config to grafana

---

src/commcare_cloud/ansible/deploy_proxy.yml

changing logrotation for nginx logs

---

src/commcare_cloud/ansible/roles/sentry/templates/sentry.conf.py.j2

* https://dimagi-dev.atlassian.net/browse/IIO-868
* ICDS

Disable user registration in sentry

---

src/commcare_cloud/fab/utils.py

https://github.com/dimagi/commcare-hq/issues/27838
Deployers will now be able to see a list of pull requests since the last deploy, in order to facilitate more visibility between code authors and deployers.

Migration alerts before deployment

---

environments/icds-cas/public.yml
environments/icds-staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Part of https://docs.google.com/document/d/1z21WtL33XpLdmn5GnC58Tkb5ra8tm20UYymAIrg9wgg/edit#
* icds
* icds-staging
HQ changes: https://github.com/dimagi/commcare-hq/pull/28055

add ICDS custom messaging content to localsettings

---

environments/icds-cas/inventory/other.csv

Increase connection for postgresql
* ICDS

Increase max connection on sentry db

---

src/commcare_cloud/ansible/deploy_proxy.yml

Compress proxy logs without waiting for next cycle.
* ALL

no wait for compressing log

---

environments/icds-cas/prometheus.yml
src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml
src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

The variables file is evaluated even for envs that aren't using the feature.
* ICDS

fix default val for grafana group

---

environments/production/terraform.yml

Double formplayer machine sizes on production

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

Add swap to staging celery

---

environments/_users/dimagi-interns.yml
environments/_users/dimagi.yml
environments/staging/meta.yml

add dimagi-interns user file for staging access

---

src/commcare_cloud/commands/migrations/couchdb.py

Example output:
```
DB                             couch00    couch01    couch02    couch03    couch04    couch05    couch06    couch07    couch08
---------------------------  ---------  ---------  ---------  ---------  ---------  ---------  ---------  ---------  ---------
_replicator                          0          0          0          4          4          4          4          4          4
_users                               0          0          0          4          4          4          4          4          4
commcarehq                           0          0          0          0          0          0          8          8          8
commcarehq__apps                     3          3          3          2          2          2          3          3          3 …
```

print shard allocation

---

environments/icds-cas/public.yml
environments/icds-staging/public.yml
environments/production/public.yml
src/commcare_cloud/ansible/roles/commcarehq/defaults/main.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Continuation of https://docs.google.com/document/d/1z21WtL33XpLdmn5GnC58Tkb5ra8tm20UYymAIrg9wgg/edit#
ICDS

move more ICDS settings to localsettings

---

src/commcare_cloud/ansible/roles/elasticsearch/templates/monit.elasticsearch.j2

https://dimagi-dev.atlassian.net/browse/IIO-915
added kill operation to stop elasticsearch in monit .
ICDS
ICDS-Staging
Production
India
Staging

added kill operation to stop elasticsearch in monit

---

environments/icds-staging/app-processes.yml

Adjusting the celery queues on icds-staging environment.
icds-staging

adjusted celery queues on icds-staging

---

src/commcare_cloud/commcare_cloud.py

Changing to be in line with https://github.com/dimagi/commcare-cloud/pull/3978
all

Update --control to avoid now-deprecated syntax

---

docs/commcare-cloud/commands/index.md
docs/setup/troubleshooting.md
scripts/inventory/README.md
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

follow on from  https://github.com/dimagi/commcare-cloud/pull/3978

update host selection syntax

---

environments/production/app-processes.yml

Split up reminder_case_update_queue across 2 process per machine on prod

---

environments/staging/public.yml

Enable 2FA SMS on staging

---

src/commcare_cloud/terraform/modules/network/main.tf

Shut off public ports on proxy sg

---

environments/icds-cas/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-880
ICDS

RabbitMQ upgrade on ICDS

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

Add the ip block list that is on staging

---

src/commcare_cloud/commands/terraform/constants.py

Incorporates https://github.com/dimagi/commcare-hq/pull/28163

Add bulk app translations to waf allow list

---

src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/variables.tf.j2
src/commcare_cloud/environment/schemas/terraform.py

https://aws.amazon.com/marketplace/pp/B0821T9RL2
none yet; production, india, staging will be able to take advantage of it

Add option for Ubuntu Pro 18.04 LTS ami

---

src/commcare_cloud/ansible/requirements.yml

Update logstash collection to latest release
* ALL

bump up logstash collection version

---

environments/production/terraform.yml
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/postgresql/main.tf

Autoscaling RDS storage

---

environments/production/public.yml
src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml

Don't compress formplayer dbs on prod

---

environments/icds-staging/public.yml

fixed Type error in public var file 
ICDS-STG

typo fixed

---

environments/icds-cas/public.yml
environments/icds-staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

HQ PR: https://github.com/dimagi/commcare-hq/pull/28094
* icds
* icds-staging

move icds urls to localsettings

---

environments/production/terraform.yml

Will roll out later today at an off-peak time
production

Bump up prod couchdb2 resources

---

environments/icds-staging/public.yml

* https://dimagi-dev.atlassian.net/browse/IIO-763
*  ICDS-STG

Upgrade redis on icds-staging

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

part of a plan outlined here https://docs.google.com/document/d/1NL9CHRAUgFDxnmsOv0Zb5AB4gvVcZl2lX4r9CemwudA/edit#
production

Make just formplayer-a031 use efs for its data directory

---

environments/production/terraform.yml
src/commcare_cloud/terraform/modules/postgresql/main.tf

Increase compute on prod pgshard RDS instances

---

environments/production/public.yml

Add back icds settings to fix pillows in prod

---

environments/india/public.yml

Similar to https://github.com/dimagi/commcare-cloud/pull/4015
india

Add back icds settings to fix pillows in india

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Reverts dimagi/commcare-cloud#4014

Revert "Make just formplayer-a031 use efs for its data directory"

---

environments/production/public.yml
environments/staging/public.yml

https://docs.google.com/document/d/1LLrD_jgtdP6VmoxvjqGEEPTvsDGv9WyhNzQcHrDkD8c/edit?ts=5f0ce3e9#
Required for https://github.com/dimagi/commcare-hq/pull/28191
Production

Add COVID custom case actions

---

environments/india/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-880
RabbitMQ upgrade to version 3.8.5
https://dimagi-dev.atlassian.net/browse/SAAS-11143
India

RabbitMQ upgraded on india environment

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Old pickles will not be affected since the pickle version is embedded in the pickle.
all

Do not pin pickle version

---

environments/icds-cas/public.yml
environments/icds-staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

see https://github.com/dimagi/commcare-hq/pull/28186
icds, icds-staging

move icds repeaters to localsettings

---

src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/environment/schemas/tests/test_terraform_schema.py

PR followup to https://github.com/dimagi/commcare-cloud/pull/4004 and https://github.com/dimagi/commcare-cloud/pull/4003
none

Rename server to server_spec in code where it could be multiple

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

define prometheus push gateway only for celery processes

---

environments/icds-cas/inventory/other.csv
environments/icds-cas/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-763
* ICDS

Upgrade redis on icds

---

environments/production/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2

Two unrelated things
- undo harmless procedural mistake between my PR and Sanjay's that both ended up adding the same machine (twice)
- resolve very minor drift

Some changes to make prod terraform apply cleanly

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/git_repository.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/schemas/meta.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/release.py

Reverts dimagi/commcare-cloud#4029

Revert "Revert "ansible support for checking out additional git repositories""

---

environments/icds-cas/public.yml
environments/icds-staging/public.yml

SSH access for NIC individuals
ICDS
ICDS-STAGING

allow ssh access for nic

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

make firehose role shareable

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2

Updated nginx configuration
Icds

updated nginx configuration

---

environments/production/aws-resources.yml
environments/production/terraform.yml

Cleanup, already applied
production

Remove old already-unused machines from prod terraform

---

environments/icds-staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

I had to deploy this to fix 500s on icds-staging for all custom ICDS urls.
@snopoke

Add icds extension to icds-staging

---

environments/icds-cas/public.yml

add icds extensions

---

src/commcare_cloud/commands/terraform/migrations/0006_create_firehose_stream_module_in_logshipping.py
src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
src/commcare_cloud/terraform/modules/logshipping/firehose_stream/main.tf
src/commcare_cloud/terraform/modules/logshipping/firehose_stream/outputs.tf
src/commcare_cloud/terraform/modules/logshipping/firehose_stream/variables.tf

https://trello.com/c/prhWvkky/37-hipaa-logging-improvements
Creates a firehose stream module within the logshipping module that creates a kinesis stream. Moves the same kinesis code from ga_alb_waf to this module and renames the vars to make them generic. Also creates a migration file to rename the kinesis code that the ga_alb_waf used. Already applied on staging.

create firehose stream module in logshipping

---

src/commcare_cloud/commands/terraform/terraform_migrate_state.py

Avoid terraform migrate state getting stuck

---

docs/commcare-cloud/commands/index.md
scripts/checkyaml.py

from PR comment: https://github.com/dimagi/commcare-cloud/pull/4050#discussion_r464614141

use io.open

---

environments/india/fab-settings.yml
environments/india/proxy.yml
environments/production/fab-settings.yml
environments/production/proxy.yml

tested this on staging, and already rolled this out (i.e. to production and india as well). See also
* https://confluence.dimagi.com/display/internal/How+to+add+a+new+proxy+machine
* https://github.com/dimagi/commcare-cloud/pull/4059
production, india

Enable multiple proxies on production and india

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

scraper bot of some kind, making lots of requests that just 400

Block another IP address

---

docs/monitoring/setup_datadog.md

Celery dashboard path correction.
N/A

Correct celery dashboard json path

---

docs/setup/new_environment.md

A couple minor tweaks to the new env instructions - see commit messages for details

New environment instructions

---

src/commcare_cloud/ansible/deploy_kafka.yml
src/commcare_cloud/ansible/requirements.yml
src/commcare_cloud/ansible/roles/kafka/tasks/main.yml

I looked at log4j.properties to achieve this but it's really kinda looked confusing. so i chose cron.
* ALL

Add cron to clean kafka system logs

---

environments/icds-cas/prometheus.yml
src/commcare_cloud/ansible/requirements.yml

Upgrade grafana,alertmanager,prometheus
* ICDS
* ICDS-STG

upgrade versions

---

environments/_users/dimagi.yml

https://dimagi-dev.atlassian.net/browse/IIO-934
ICDS
ICDS-STAGING
STAGING
PRODUCTION
INDIA

Remove sgoswami account from servers

---

environments/india/public.yml
environments/production/public.yml
environments/staging/public.yml
src/commcare_cloud/ansible/deploy_formplayer.yml
src/commcare_cloud/ansible/roles/kinesis_agent/tasks/main.yml
src/commcare_cloud/ansible/roles/kinesis_agent/templates/agent.json.j2
src/commcare_cloud/ansible/roles/kinesis_agent/vars/main.yml

https://trello.com/c/prhWvkky/37-hipaa-logging-improvements
- Creates a `kinesis_agent` role
- creates a tmp dir, git pulls source code, installs from setup script, then removes directory
- generates config file and enables service
- Adds `kinesis_agent` role to deploy_formplayer.yml
- Requires a `kinesis_flow` nonempty list to be defined to run
- Can be added to prod once everything set up 
Staging

added kinesis_agent role and included in formplayer

---

environments/india/terraform.yml

The type of these machines was out of sync with what we had here in code
india

Sync to india/terraform.yml chnages already existing

---

docs/services/rabbitmq/upgrade.md

Add instructions for the "switch and drain" method of upgrading rabbitmq

---

environments/india/public.yml
environments/production/public.yml

Potential solution for issues related to https://github.com/dimagi/commcare-hq/pull/28301
production, india

Remove icds local settings from india and production

---

environments/production/terraform.yml

Peak in the last month was around 20%
production

Halve CPU on ES data nodes based on very low CPU usage

---

environments/icds-cas/postgresql.yml
src/commcare_cloud/ansible/roles/pg_repack/files/pg_repack.py
src/commcare_cloud/ansible/roles/pg_repack/tasks/main.yml

Automated repacking of the tables in pgmain that we routinely delete a lot of data from.
icds

pgrepack pgmain tables

---

environments/production/postgresql.yml
environments/production/terraform.yml

See commit messages for notes on how they're applied.
production

Changes during pgsynclog0-production fire

---

src/commcare_cloud/ansible/README.md
src/commcare_cloud/environment/secrets/backends/abstract_backend.py

Docs followup to https://github.com/dimagi/commcare-cloud/pull/4118 and https://github.com/dimagi/commcare-cloud/pull/4114.
none

Document secrets management

---

docs/firefighting/index.md

Adding something that helped recently to firefighting docs

Add command in firefighting docs for killing formplayer sockets to solve lock issue

---

environments/icds-cas/public.yml
environments/icds-staging/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-947
ICDS
ICDS-STAGING

Allow SSH access to read  only users created for NIC

---

src/commcare_cloud/ansible/roles/lpar2rrd/defaults/main.yml

https://dimagi-dev.atlassian.net/browse/IIO-946
ICDS

updated LPAR2RRD Master version

---

src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml

Followup to https://github.com/dimagi/commcare-cloud/pull/4125

CloudWatch Logs updates

---

environments/india/app-processes.yml
environments/india/terraform.yml

Increase india formplayer resources

---

environments/icds-sandbox/inventory/citusdb.csv
environments/icds-sandbox/public.yml

https://dimagi-dev.atlassian.net/browse/IIO-930
ICDS-SANDBOX

added couch cluster

---

environments/icds-sandbox/inventory/citusdb.csv
environments/icds-sandbox/public.yml

Reverts dimagi/commcare-cloud#4140
Will push it into the private commcare-cloud-icds repo
so reverting it from here.

Revert "added couch cluster"

---

src/commcare_cloud/environment/main.py

This is useful for test output;
```diff
- test_environments.test_all(<commcare_cloud.environment.main.Environment object at 0x7ff79ef35e10>, {}) ... ok
+ test_environments.test_all(Environment(name=development), {}) ... ok
```

add repr to Environment

---

src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

Required by ICDS security audit.
all

add x-xss-protection header

---

environments/production/inventory.ini
environments/production/terraform.yml

Followup to https://github.com/dimagi/commcare-cloud/pull/4147 and https://github.com/dimagi/commcare-cloud/pull/4165 (3/)
production

Remove 5 old production formplayer machines

---

src/commcare_cloud/ansible/roles/airflow/tasks/main.yml

* https://dimagi-dev.atlassian.net/browse/IIO-929
* ICDS , ICDS-STG

update airflow to support py3

---

src/commcare_cloud/ansible/deploy_prometheus.yml
src/commcare_cloud/ansible/requirements.yml

Upgrade exporters
ICDS
ICDS-STAGING

upgrade exporters settings

---

src/commcare_cloud/ansible/roles/postgresql_base/templates/pg_hba.conf.j2

Allow airflow exporter to access pgmain 
ICDS
ICDS-STG

Allow airflow exporter to acess pgmain

---

src/commcare_cloud/commands/terraform/terraform.py

Refuse to run terraform destroy

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://github.com/dimagi/icds-commcare-environments/pull/4
none in this repo

update captcha settings if available

---

src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
tests/test_ssh.py

I don't think there is any harm in doing this and it makes many more commands useful.

always force a TTY from ssh commands

---

environments/production/app-processes.yml

increased UpdateUserSyncHistoryPillow processes from 1 to 2.
added one more partition to synclog-sql topic. Changes are reflected in the production now. 
Production.

increased UpdateUserSyncHistoryPillow processes from 1 to 2.

---

.flake8

Copied from https://github.com/dimagi/commcare-hq/blob/master/.flake8

Add flake8 config

---

src/commcare_cloud/ansible/roles/nginx/tasks/install.yml

https://dimagi-dev.atlassian.net/browse/IIO-987
None , at the this time.
this is a prep requirement to upgrade the nginx to latest version by defining the "nginx_version" variable in public.yml file.

Prep required for nginx version upgrade

---

.gitignore

Ignore .python-version file associated with pyenv setup.

Ignore pyenv python-version file

---

src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml
src/commcare_cloud/ansible/roles/cloudwatch_logs/tasks/main.yml
src/commcare_cloud/ansible/roles/cloudwatch_logs/templates/cloudwatch_logs.json.j2

Logship /var/log/{syslog,auth.log,audit/audit.log}

---

control/update_code.sh

@mkangia this will make it easier to update both repos at the same time for ICDS

update separate envs repo if it exists

---

environments/production/terraform.yml

This is a bit of a shot in the dark for https://dimagi-dev.atlassian.net/browse/SAAS-11347
but I want to rule such a simple change out as helping.
production

Switch production formplayer machines to "higher quality" VMs

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://dimagi-dev.atlassian.net/browse/SAAS-137
all envs

fix intermittent failures in redis py due to celery upgrade

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Reverts dimagi/commcare-cloud#4215

Revert "fix intermittent failures in redis py due to celery upgrade"

---

src/commcare_cloud/ansible/roles/nginx/templates/site.j2
src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml
src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

Recommendation from ICDS security audit
ALL

set Content-Type-Options header to nosniff

---

tests/test_modernize.sh

Test is inexplicably failing on Python 3 in https://github.com/dimagi/commcare-cloud/pull/4220

Skip test_modernize.sh on Python 3

---

src/commcare_cloud/ansible/roles/pg_repack/files/pg_repack.py
src/commcare_cloud/commands/terraform/postgresql_units.py

Step 3 of [this document](https://docs.google.com/document/d/17QQu5BAAwle5KHTMawTlsf4o78ZRXElIKlrBdHjrU8M/edit#).

Replace classic division with floor division where applicable

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://dimagi-dev.atlassian.net/browse/SAAS-11355 (and possibly the P2 that came up)
all

add health check interval to redis config

---

src/commcare_cloud/ansible/roles/kinesis_agent/tasks/main.yml
src/commcare_cloud/ansible/roles/kinesis_agent/templates/agent.json.j2
src/commcare_cloud/ansible/roles/kinesis_agent/vars/main.yml

Move kinesis-agent checkpoint file to a location whose permissions we control

---

environments/production/terraform.yml

Increase formplayer_b{i}-production disk

---

src/commcare_cloud/ansible/roles/postgresql_base/tasks/cleanup.yml
src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/templates/monit.postgresql.j2
src/commcare_cloud/commands/ansible/service.py

This makes it easier to install a new version during the upgrade process.

version specific files for PostgreSQL

---

src/commcare_cloud/ansible/roles/setup_auth_keys.yml

Avoid overwriting the tmp file for each new host

host specific files

---

docs/firefighting/index.md

This is something I find myself doing regularly which according to these docs also means I should add more disk ;)

Add couch db compaction to firefighting docs

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://github.com/dimagi/commcare-hq/commit/0e2683ef5015b5fef7b9c8879f265c0a325d08b2#diff-bdf3ecebd8379ca98cc89e545fc90899
None

remove removed setting

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://dimagi-dev.atlassian.net/browse/SAAS-11352
all environments

lower health check interval to 15 sec

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
src/commcare_cloud/ansible/roles/citusdb/defaults/main.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/main.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_cordinator.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_worker.yml
src/commcare_cloud/ansible/roles/citusdb/vars/pgbouncer_workers.yml
src/commcare_cloud/environment/schemas/postgresql.py

* rename some vars to make it clearer what they are for
* enforce only 1 citusdb cluster (1 master node)
* specify the version of the citusdb extension to install. This will have the effect of upgrading the extension when a new version is specified

prep for citus upgrade

---

src/commcare_cloud/ansible/group_vars/prometheus.yml

Previous change only included the `node.yml` target file.

fix prometheus config to include all files

---

environments/staging/app-processes.yml
environments/staging/public.yml
environments/staging/terraform.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2
src/commcare_cloud/ansible/roles/datadog/tasks/main.yml
src/commcare_cloud/environment/schemas/app_processes.py
src/commcare_cloud/environmental-defaults/app-processes.yml

This adds django and java tracing from datadog to staging, as well as turns on some postgres settings that should allow greater insight into performance.
Staging

tracing staging

---

environments/production/terraform.yml

Upgrade redis0-production in response to full disk

---

src/commcare_cloud/ansible/filter_plugins/py2filters.py
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml

The error started [causing tests to fail](https://travis-ci.org/github/dimagi/commcare-cloud/builds/735737545) today. Not sure why.
maybe only travis tests or maybe all?

Work around pip2 SSL error
