dimagi/commcare-cloud

README.md
ansible/roles/common/meta/main.yml
ansible/roles/newrelic/tasks/main.yml

@TylerSheffels this includes your suggestion of listing tags in README

Activate New Relic

---

ansible/roles/users/tasks/main.yml

rename sudoers file to sudoers.d/cchq

---

ansible/group_vars/all.yml
ansible/roles/users/tasks/main.yml

needs to be set to something different on prod. (Matters very little)

break out dev_group name as a variable

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/templates/localsettings.salt.py.j2
scripts/sync-localsettings.sh

fixes #44 
Note that this breaks the localsettings sync from salt. Most recent salt changes synced here: https://github.com/dimagi/commcarehq-ansible/pull/43

use correct server environment for preindex

---

ansible/roles/touchforms/tasks/main.yml
ansible/roles/touchforms/templates/localsettings.py.j2
ansible/roles/touchforms/vars/main.yml

http://manage.dimagi.com/default.asp?155377#870144
@dannyroberts @TylerSheffels

add cron job to delete old touchforms sessions

---

Vagrantfile
ansible/deploy_proxy.yml
ansible/roles/hq_status/defaults/main.yml
ansible/roles/hq_status/tasks/main.yml
ansible/roles/hq_status/templates/hq_status
ansible/roles/hq_status/templates/index.html

@dannyroberts @TylerSheffels 
Noah and I worked on this today

add hq status site to proxy machines

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/vars/main.yml
ansible/roles/webworker/tasks/main.yml
ansible/roles/webworker/vars/main.yml

Note, this is dependent on this PR: https://github.com/dimagi/commcare-hq/pull/5956
@TylerSheffels

Purge old restore files

---

ansible/roles/webworker/tasks/main.yml

tag for restore payload dir creation

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@dannyroberts 
Good catch @snopoke

Quote variable

---

ansible/roles/commcarehq/templates/localsettings.py.j2

For https://github.com/dimagi/commcare-hq/pull/6067

add segment analytics private variable

---

ansible/roles/commcarehq/templates/localsettings.py.j2

For http://manage.dimagi.com/default.asp?157984
@benrudolph

add variables for new invoice template

---

ansible/roles/commcarehq/templates/localsettings.py.j2

add saved export timeout option to localsettings

---

ansible/deploy_db.yml

@benrudolph something like this

tag ecryptfs role

---

ansible/deploy_db.yml
ansible/roles/elasticsearch/tasks/main.yml
ansible/roles/elasticsearch/templates/config/logging.yml.j2

@dannyroberts @czue 
code buddy: @millerdev 
Going to give this a spin on the india server. would be nice to just have to update this and deploy via ansible

Add logger.yml to ES setup

---

ansible/deploy_stack.yml

Need to setup shared dir before we deploy the webworkers

Deploy shared_dir before web worker

---

ansible/roles/elasticsearch/tasks/main.yml

Tags for updating es conf

---

ansible/roles/postgresql/tasks/main.yml

Update postgres conf regardless of pg_install

---

ansible/roles/common/meta/main.yml

makes it easier to run just this

add tag to common_installs

---

ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/roles/postgresql/templates/postgresql.conf.j2

@snopoke @dannyroberts 
cc: @esoergel 
Used these as reference:
http://pastebin.com/pXk09qte - `pg_hba.conf` diff
http://pastebin.com/kDRYdZqJ - `postgres.conf` diff
needs: https://github.com/dimagi/commcare-hq/pull/6590

Update pg conf

---

ansible/deploy_proxy.yml
ansible/group_vars/all.yml
ansible/roles/shared_dir.yml
ansible/roles/shared_dir/tasks/setup_host.yml
ansible/roles/shared_dir/vars/main.yml
ansible/roles/webworker/tasks/main.yml
provisioning/control.sh

@benrudolph
This adds another shared folder and also adds the nfs drive to the proxy machines. This is in prep for using django-transfer.
buddy ping @sravfeyn

Transfer folder

---

ansible/group_vars/all.yml
ansible/roles/shared_dir/tasks/setup_host.yml
ansible/roles/shared_dir/vars/main.yml

fix spelling and use shared var name

---

ansible/group_vars/all.yml
ansible/roles/apache2/tasks/main.yml
ansible/roles/apache2/templates/cchq.j2
ansible/roles/shared_dir/tasks/setup_host.yml
ansible/roles/shared_dir/vars/main.yml

add xsendfile apache mod

---

ansible/roles/shared_dir.yml

@benrudolph 
Going to need this for files generated by celery

add nfs drive to celery machines

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cchq.yml

add x-accel location to nginx config

---

ansible/roles/postgresql/templates/postgresql.conf.j2

@benrudolph 
I though we had autovacuum setup but its definitely not running now. Perhaps a change when we updated the config files.

enable autovacuum

---

ansible/roles/postgresql/templates/pg_hba.conf.j2

correct db access for sentry

---

ansible/group_vars/all.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/shared_dir/tasks/setup_host.yml
ansible/roles/shared_dir/vars/main.yml

@benrudolph 
this folder gets used by uploads e.g. https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqmedia/views.py#L283

Shared temp

---

ansible/roles/touchforms/templates/localsettings.py.j2

Remove extraneous log

---

ansible/roles/postgresql/tasks/main.yml

This reverts commit 835cb579cbdd0678cb41848e25a1c4ef2cac8020.
@benrudolph

Revert "add posgresql tag"

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@millerdev this'll probably fix what you were seeing. going to update tomorrow
elf: @snopoke

Use log home instead of ..

---

ansible/roles/postgresql/templates/pg_hba.conf.j2

make sentry opional

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/postgresql/templates/pg_hba.conf.j2

turn ssl off for postgresql

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2

use correct user for admin

---

ansible/roles/touchforms/templates/localsettings.py.j2

Adding setting for touchforms postgres persistence

---

ansible/roles/touchforms/templates/localsettings.py.j2

@snopoke not critical, but will need when this gets in: https://github.com/dimagi/touchforms/pull/118/files

Redis config for touchforms

---

ansible/roles/touchforms/templates/localsettings.py.j2

Use port variable

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/vars/dev.yml

adjust pgbouncer settings

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/vars/dev.yml

allow specifying the pgbouncer pool mode

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@benrudolph see https://github.com/dimagi/commcare-hq/pull/6792

remove SQL_REPORTING_DATABASE_URL

---

ansible/roles/touchforms/templates/localsettings.py.j2

quote just host

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/roles/touchforms/templates/localsettings.py.j2

see https://github.com/dimagi/touchforms/commit/f5957b989545b8d1e3b72fc62999222bdad24a37
@benrudolph

updates to get touchforms working on staging

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2

switch off connection logging in pgbouncer

---

ansible/deploy_db.yml
ansible/deploy_proxy.yml
ansible/group_vars/all.yml
ansible/group_vars/postgresql.yml
ansible/group_vars/proxy.yml
ansible/group_vars/rabbitmq.yml
ansible/group_vars/redis.yml
ansible/roles/newrelic/tasks/plugin-agent.yml
ansible/roles/newrelic/templates/newrelic-plugin-agent.cfg.j2
ansible/roles/nginx/templates/default.j2
ansible/vars/dev.yml

add newrelic plugin agent

---

ansible/roles/nginx/templates/default.j2

Add server to nginx default config

---

ansible/deploy_proxy.yml
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/main.yml

@dannyroberts 
I still want to figure out how this will work if two servers are specified as default  (e.g. staging and prod in this configuration).

Add default_server for nginx processing and correct http spelling

---

ansible/roles/touchforms/defaults/main.yml
ansible/roles/touchforms/templates/localsettings.py.j2

@TylerSheffels @wspride 
easier to set default var
elf: @czue

Variable for uses postgres

---

ansible/roles/nginx/templates/nginx.conf.j2
ansible/roles/nginx/vars/cchq_ssl.yml

@dannyroberts 
@snopoke Buddy!

Add timing log format and timing to cchq

---

ansible/roles/common_installs/tasks/main.yml

@TylerSheffels 
https://mosh.mit.edu/#getting

install mosh

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cchq_ssl.yml

http://manage.dimagi.com/default.asp?174935
@dannyroberts @czue

Nginx forwarded for

---

ansible/roles/nginx/vars/commtrack_http.yml
ansible/roles/nginx/vars/commtrack_ssl.yml

Redirect commtrack.org/ -> supply anchor on CCHQ

---

README.md
ansible/deploy_control.yml
ansible/inventories/localhost

currently just adds users and installs editors

add deploy_control.yml to set up ansible control machine

---

ansible/deploy_load_test.yml
ansible/roles/load_test/defaults/main.yml
ansible/roles/load_test/tasks/install_prototype.yml
ansible/roles/load_test/templates/prototype_localconfig.py.j2

setup for prototpe service

---

ansible/roles/load_test/tasks/install_prototype.yml
ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/tasks/main.yml
ansible/vars/prototype.yml

prototype provisioning tweaks

---

ansible/deploy_proxy.yml
ansible/roles/nginx/vars/motech.yml
ansible/roles/nginx/vars/motech_http.yml

Adds a motech reverse proxy for: http://manage.dimagi.com/default.asp?175901#edit_0_175901
@dannyroberts

Add motech

---

ansible/roles/postgresql/defaults/main.yml

See https://github.com/dimagi/commcarehq-ansible/pull/163/files#r35277171

fix bad quoting

---

ansible/roles/bennojoy.redis/templates/redis.conf.j2

related to http://manage.dimagi.com/default.asp?177250
@dannyroberts @benrudolph @TylerSheffels

reduce timeout

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/dev.yml

@czue @orangejenny this is the ansible portion for https://github.com/dimagi/commcare-hq/pull/7623

Add dropbox vars

---

ansible/roles/commcarehq/templates/localsettings.py.j2

related to http://manage.dimagi.com/default.asp?177091
@snopoke cc @esoergel

use notify logger for notify logger in template

---

ansible/roles/commcarehq/templates/localsettings.py.j2

enable couchlog search

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/dev.yml

Dropbox app name

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@czue will use this branch on ansible to update staging local vars so i can actually deploy. no need to merge until redis has actually passed QA

redis_cache backend

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Safer redis settings

---

ansible/group_vars/proxy.yml
ansible/roles/nginx/templates/default.j2

swith to nginx

---

ansible/deploy_db.yml

tag couch role

---

ansible/group_vars/all.yml
ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/commcarehq/vars/main.yml
ansible/roles/common/meta/main.yml
ansible/roles/common_installs/tasks/main.yml

Reverts dimagi/commcarehq-ansible#187

Revert "Update code_root"

---

ansible/roles/touchforms/defaults/main.yml

Default to using postgres

---

ansible/roles/common/meta/main.yml
ansible/vars/dev.yml

don't default to installing new relic on dev machines

---

ansible/roles/postgresql/tasks/main.yml

create postgres directory

---

ansible/vars/dev.yml

don't install new relic machine in dev setup

---

ansible/roles/commcarehq/templates/localsettings.py.j2

remove old (and clearly wrong) jad_tool key

---

ansible/deploy_proxy.yml
ansible/roles/nginx/vars/icds_tableau.yml
ansible/roles/nginx/vars/icds_tableau_http.yml
ansible/roles/nginx/vars/tableau.yml

@sravfeyn Add nginx handling for ICDS Tableau server.

Icds tableau

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/templates/localsettings.py.j2

@NoahCarnahan 
cc @TylerSheffels

changes for zambia

---

ansible/group_vars/all.yml
ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/commcarehq/vars/main.yml
ansible/roles/common/meta/main.yml
ansible/roles/common_installs/tasks/main.yml

Reverts dimagi/commcarehq-ansible#194

Revert "Revert "Update code_root""

---

ansible/roles/commcarehq/templates/localsettings.py.j2

add environment hosts mapping to localsettings

---

ansible/roles/common_installs/tasks/main.yml

@esoergel gonna be using this branch to test out git version upgrade after reading the release notes
cc: @czue

add git ppa

---

ansible/roles/commcarehq/templates/localsettings.py.j2

codebuddy @gcapalbo 
interrupt @TylerSheffels @esoergel @nickpell

add ANALYTICS_ID_PUBLIC_COMMCARE to analytics ids

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Add template for HQ_PRIVATE_KEY

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Add couch logging

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/vars/main.yml
ansible/roles/common_installs/tasks/main.yml

the ansible component for djangobower: https://github.com/dimagi/commcare-hq/pull/8364

Djangobower

---

ansible/roles/nginx/templates/nginx.conf.j2

@dannyroberts @TylerSheffels added timestamp so amelia can do better analytics

Add time in Common Log Format

---

ansible/deploy_db.yml

@snopoke @TylerSheffels Adding postgres log rotation. went to debug some postgres stuff the other day and `ls` took minutes to run because there are so many files in there

Add postgres log rotation

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/vars/dev.yml

This adds the ability to specify a custom database that will be created in postgres

Custom ucr databases

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/vars/dev.yml

Reverts dimagi/commcarehq-ansible#225

Revert "Custom ucr databases"

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@TylerSheffels 
here too: https://github.com/dimagi/commcare-hq/pull/8578

Mia localsettings

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/common/meta/main.yml
ansible/roles/datadog/handlers/main.yml
ansible/roles/datadog/tasks/main.yml
ansible/roles/datadog/templates/datadog.conf.j2
ansible/vars/dev.yml

install datadog agent & localsettings

---

ansible/roles/commcarehq/templates/localsettings.py.j2

http://manage.dimagi.com/default.asp?184654

set log level for elasticsearch to ERROR

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Remove sentry from ES logging

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@gcapalbo @dannyroberts 
Goes with: https://github.com/dimagi/commcare-hq/pull/8750

Add S3 access and secret keys to localsettings

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/vars/main.yml

Remove bower directory creation

---

ansible/roles/postgresql/templates/pgbouncer.users.j2

iterate over dict values

---

ansible/deploy_common.yml
ansible/inventories/monolith
ansible/roles/nginx/tasks/install.yml
ansible/vars/dev.yml

mostly relevant to @TylerSheffels though all are tiny

More install tweaks

---

ansible/roles/redis/templates/redis.conf.j2

We aren't really using this data and even if we do it doesn't seem like we need that much
@benrudolph

reduce slowlog max len

---

ansible/roles/datadog/templates/rabbitmq.yaml.j2

only get stats for the vhost we use

---

ansible/roles/datadog/tasks/main.yml
ansible/roles/datadog/templates/datadog.conf.j2
ansible/roles/datadog/vars/main.yml

@snopoke have yet to give it a spin, but this is the general idea. 
related: https://github.com/dimagi/datadog-parsers/pull/1
cc: @esoergel

Datadog nginx parser

---

ansible/roles/datadog/templates/datadog.conf.j2

@snopoke @czue goes with https://github.com/dimagi/datadog-parsers/pull/2

add web worker couch parser

---

ansible/roles/datadog/templates/datadog.conf.j2

add more groups to dog stream

---

ansible/roles/commcarehq/templates/localsettings.py.j2

remove old settings

---

ansible/roles/datadog/templates/datadog.conf.j2

@dannyroberts 
cc: @proteusvacuum

Add parse_nginx_apdex parser

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/dev.yml

goes with https://github.com/dimagi/commcare-hq/pull/9017 @esoergel or whoever

remove legacy settings

---

ansible/roles/nginx/tasks/install.yml
ansible/roles/nginx/tasks/main.yml

Add update-cert tags to run SSL updating faster

---

ansible/roles/postgresql/tasks/main.yml

use correct port

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/dev.yml

remove pingdom vars

---

ansible/roles/datadog/templates/datadog.conf.j2

Allow for undefined vars in parser

---

ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/main.yml

http://manage.dimagi.com/default.asp?187354
@TylerSheffels how does this look? cc @proteusvacuum

use primary_ssl_env to determine the default nginx site

---

ansible/roles/common/meta/main.yml
ansible/roles/common_installs/tasks/main.yml
ansible/roles/newrelic/tasks/main.yml

@dannyroberts @emord some fixes while going through the deploy

Webworker deploy fixes

---

ansible/roles/common_installs/tasks/main.yml

Correct the less.js repo URL

---

ansible/roles/common_installs/tasks/main.yml

As discussed in #275 but opening a new PR just because this one's name isn't misleading. @snopoke cc @gcapalbo

Install client from Postgres apt repo

---

ansible/roles/couchdb/tasks/main.yml

Another small one. @snopoke cc @gcapalbo

Extract couchdb tar in home directory

---

ansible/roles/commcarehq/templates/localsettings.py.j2

add inactivity timeout to localsettings

---

ansible/roles/redis/vars/main.yml

Another little one. @benrudolph cc @gcapalbo

Can't use wildcards in package versions

---

ansible/roles/datadog/vars/main.yml

Add nginx counter

---

ansible/deploy_proxy.yml
ansible/roles/nginx/vars/motech1.yml
ansible/roles/nginx/vars/motech1_http.yml
ansible/roles/nginx/vars/motech2.yml
ansible/roles/nginx/vars/motech2_http.yml
ansible/vars/dev.yml

For this ticket:
http://manage.dimagi.com/default.asp?187743

Add MOTECH Test Servers to Nginx Proxy

---

ansible/roles/shared_dir/tasks/setup_host.yml

follow up to https://github.com/dimagi/commcarehq-ansible/pull/286

add shared_dir_host machine to /etc/exports as well

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/datadog/vars/main.yml

ddog logger

---

ansible/deploy_proxy.yml

@TylerSheffels cc @snopoke buddies @calellowitz @sravfeyn

Logrotate config needs sudo

---

ansible/roles/ecryptfs/tasks/main.yml

add user,noauto to /opt/data mount

---

ansible/roles/common_installs/defaults/main.yml
ansible/roles/postgresql/defaults/main.yml

@snopoke buddies @sravfeyn @calellowitz

Default to PostgreSQL 9.4

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/dev.yml

remove dead analytics IDs

---

ansible/roles/nginx/vars/cchq_ssl.yml

Fixes: http://manage.dimagi.com/default.asp?189184#1061462
@benrudolph, @nickpell, @orangejenny

Switch to use SAMEORIGIN for exframe options

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Add `s` to handler in LOGGING dict

---

ansible/roles/touchforms/templates/localsettings.py.j2

update to new local settings

---

ansible/deploy_db.yml

@TylerSheffels http://manage.dimagi.com/default.asp?190030#1067824

install java on celery

---

ansible/roles/touchforms/templates/localsettings.py.j2

@snopoke @TylerSheffels https://github.com/dimagi/commcarehq-ansible/pull/272/files#r49047688

Use raw and endraw for tf local settings

---

ansible/roles/nginx/vars/motech1.yml
ansible/roles/nginx/vars/motech2.yml

Remove host header to fix redirection (not clear cause)

---

ansible/roles/nginx/vars/motech1.yml
ansible/roles/nginx/vars/motech1_http.yml
ansible/roles/nginx/vars/motech2.yml
ansible/roles/nginx/vars/motech2_http.yml

@TylerSheffels can you review and merge?

Update MOTECH server config To properly pass host to DHIS2

---

ansible/group_vars/all.yml
ansible/roles/apache2/templates/cchq.j2
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/supervisor/handlers/main.yml
ansible/vars/dev.yml

@benrudolph @dannyroberts @emord

Fix shared dirs in proxy config files

---

ansible/roles/users/tasks/main.yml

http://manage.dimagi.com/default.asp?204574#1077085
This looks like it worked on my local vagrant setup, but I'm not that familiar with ansible yet.
@czue
cc: @sravfeyn

Add ansible user with sudo

---

ansible/roles/users/tasks/main.yml
ansible/vars/dev.yml

http://manage.dimagi.com/default.asp?204574#1078258
Set up the ansible user with a password.
Used http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
After deploying  this using --ask-sudo-pass with ansible user should work on prod
cc @sravfeyn

set up ansible with a password

---

ansible/roles/users/tasks/main.yml
ansible/vars/dev.yml

Exclusive ssh key

---

ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/templates/create_postgres_dump.sh.j2

Be more specific with postgres backup dir, parametrize shell script

---

ansible/roles/commcarehq/templates/localsettings.py.j2

adding two factor gateway to localsettings

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
ansible/roles/elasticsearch/templates/upstart/elasticsearch.conf.j2

drop support for es 0.x

---

ansible/roles/ecryptfs/tasks/main.yml

Fix permissions on blobdb

---

ansible/roles/riakcs/tasks/admin_user.yml
ansible/roles/riakcs/tasks/install.yml
ansible/roles/riakcs/tasks/join_nodes.yml
ansible/roles/riakcs/tasks/main.yml
ansible/roles/stanchion/tasks/main.yml

@millerdev fixes the issue about starting riak and it failing hard. riak is now running on staging. you should also check out `ansible/roles/riakcs/README.md`
cc: @emord

use service instead of command

---

ansible/deploy_db.yml
ansible/roles/backups/defaults/main.yml
ansible/roles/backups/tasks/main.yml
ansible/roles/backups/templates/create_blobdb_backup.sh.j2
ansible/vars/dev.yml

This adds a similar script to the postgres backup script I wrote, but this one tar's the blobdb drive. I would like to do a bit of refactoring (this is a bit of copy/paste) to the postgres backup script after this is ironed out, but wanted to wait until I am clear what will end up being parametrized.
@kaapstorm @snopoke

Blobdb backups

---

ansible/es_rolling_restart.yml
ansible/roles/elasticsearch/tasks/main.yml
ansible/roles/elasticsearch/tasks/rolling_restart.yml
ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

allow groovy scripts on ES

---

ansible/roles/commcarehq/templates/localsettings.py.j2

add ELASTICSEARCH_HOSTS to localsettings

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

http://manage.dimagi.com/default.asp?216752
@biyeun 
already run on prod.

allow groovy in inline search

---

ansible/roles/commcarehq/templates/localsettings.py.j2

logging was set up for analytics a while ago by @sravfeyn but the log files were never created or added to localsettings
@millerdev

adding analytics log file

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@benrudolph this should fix the issues you saw

correcting settings for analytics logging

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/common_installs/tasks/main.yml
ansible/roles/touchforms/tasks/main.yml
ansible/roles/touchforms/templates/application.properties.j2
ansible/vars/dev.yml

Java tf deploy

---

ansible/group_vars/all.yml
ansible/roles/commcarehq/templates/localsettings.py.j2

Fix --tags=localsettings with missing riakcs group

---

README.md

@czue some instructions
cc: @gcapalbo

monolith setup

---

ansible/inventories/test-vagrant
ansible/roles/commcarehq/tasks/main.yml
ansible/roles/supervisor/tasks/main.yml
ansible/roles/users/tasks/main.yml

@benrudolph cc @dannyroberts @snopoke

Move cchq to supervisor role

---

ansible/deploy_commcarehq.yml
ansible/deploy_riakcs.yml
ansible/roles/riakcs/get_admin_keys.yml

Load Riak CS keys for localsettings in check mode

---

ansible/group_vars/riakcs.yml
ansible/roles/datadog/templates/riak.yaml.j2
ansible/roles/datadog/templates/riakcs.yaml.j2
ansible/roles/riakcs/README.md
ansible/roles/riakcs/configure/templates/riak.conf.j2
ansible/roles/riakcs/sync_keys/handlers/main.yml
ansible/roles/riakcs/sync_keys/tasks/main.yml

This has been deployed to the prod cluster.
@snopoke cc @dannyroberts @benrudolph

Add datadog agent config for riak and riakcs

---

ansible/roles/couchdb/defaults/main.yml
ansible/roles/postgresql/tasks/main.yml

some small changes

---

ansible/roles/elasticsearch/defaults/main.yml
ansible/roles/elasticsearch/templates/upstart/elasticsearch.conf.j2

@dannyroberts thanks for your help.  i think this might be the best route

Better es memory

---

ansible/ansible.cfg
ansible/deploy_commcarehq.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/handlers/main.yml
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/vars/dev.yml

setup for creating sharded DB

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Fix CSRF_SOFT_MODE = "False" (string evals to True)

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/dev.yml

localsettings.ENABLE_DRACONIAN_SECURITY_FEATURES

---

ansible/roles/common_installs/tasks/main.yml

Remove depth = 1

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/vars/main.yml

@emord upgrades our setup tools. staging was already on 18, this bumps us to 20. no breaking changes that looked relevant to us. will leave on staging for a bit before deploying to the rest of the machines
cc: @gcapalbo

easy_install setup tools

---

ansible/deploy_db.yml
ansible/inventories/test
ansible/roles/Rackspace_Automation.cloud-backup-agent/.drone.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/README.md
ansible/roles/Rackspace_Automation.cloud-backup-agent/defaults/main.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/handlers/main.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/meta/.galaxy_install_info
ansible/roles/Rackspace_Automation.cloud-backup-agent/meta/main.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/tasks/Debian.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/tasks/RedHat.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/tasks/main.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/tasks/unsupported_os.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/templates/RedHat.repo
ansible/roles/Rackspace_Automation.cloud-backup-agent/tests/main.yml
ansible/roles/Rackspace_Automation.cloud-backup-agent/tests/roles.list
ansible/roles/Rackspace_Automation.cloud-backup-agent/vars/main.yml

@czue @benrudolph @calellowitz 
http://manage.dimagi.com/default.asp?221540#1113032
I have a manual backup running at the moment on staging (will auto email devops once done), but looks like this works. Most files are just from installing https://github.com/rack-roles/cloud-backup-agent

Rackspace cloud agent

---

ansible/roles/elasticsearch/tasks/main.yml
ansible/roles/touchforms/tasks/main.yml

Ran into a number of problems while trying to do an ansible deploy to new machines.  These are the changes I made to get it to pass
@benrudolph @millerdev @dannyroberts

Make deploy_stack work

---

ansible/roles/postgresql/defaults/main.yml

based on discussion with @benrudolph

postgresql_ssl_enabled defaults to False

---

ansible/roles/common_installs/tasks/main.yml
ansible/roles/kafka/tasks/main.yml
ansible/roles/kafka/templates/kafkatcfg.j2

ranger everywhere and kafkat on kafka machines
@benrudolph

Install ranger and kafkat

---

ansible/roles/commcarehq/templates/localsettings.py.j2

default analytics to blank

---

ansible/roles/postgresql/tasks/main.yml

@NoahCarnahan / anyone
diff isn't that clear but it just swaps the order of the two tasks

create role before databases

---

ansible/roles/touchforms/tasks/main.yml

tag formplayer check

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Cloudcare url

---

ansible/roles/touchforms/templates/application.properties.j2

goes with https://github.com/dimagi/formplayer/pull/26

Use redis host property

---

ansible/roles/postgresql/tasks/main.yml

set encoding on new databases

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2

ignore geqo in pgbouncer conenctions

---

ansible/roles/captain/tasks/main.yml
ansible/roles/captain/templates/supervisor/tailon.conf.j2

Allows us to tail log files for captain @millerdev

tailon for captain

---

ansible/roles/captain/tasks/main.yml
ansible/roles/captain/templates/config.py.j2

@millerdev adds github api key to captain

Add github api key

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2

give devreadonly user access to pgbouncer console

---

ansible/deploy_commcarehq.yml
ansible/roles/celery_hq/tasks/main.yml

@snopoke http://manage.dimagi.com/default.asp?225026 sets up purgin'. no good place to put this, so made a new role.
cc: @millerdev

Add cron purge job

---

ansible/roles/common/tasks/main.yml
ansible/vars/dev.yml

add lines to hosts

---

ansible/roles/captain/tasks/igor.yml
ansible/roles/captain/tasks/main.yml
ansible/roles/captain/templates/igor/config.json.j2
ansible/roles/captain/templates/supervisor/igor.conf.j2
ansible/roles/captain/vars/main.yml

@snopoke @millerdev this moves igor off of the jenkins machine and on to hqcaptain where it can better be maintained

Captain igor

---

ansible/roles/captain/tasks/main.yml
ansible/roles/captain/templates/supervisor/django.conf.j2

Rename to captain

---

ansible/roles/nginx/vars/cchq_http_j2me.yml

allow downloading form XML over http

---

ansible/roles/commcarehq/templates/localsettings.py.j2

set couch-stale setting to update_after

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Needed quotes. Also, added a check that the j2me setting existed before setting it.

couchdb stale = 'ok' and j2me

---

ansible/roles/commcarehq/templates/localsettings.py.j2

See https://github.com/dimagi/commcare-hq/pull/11614 Also removed env-setting from softlayer.yml
@proteusvacuum

remove csrf_soft_mode setting

---

ansible/deploy_common.yml
ansible/group_vars/all.yml
ansible/roles/elasticsearch/defaults/main.yml
ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
ansible/roles/ufw/tasks/proxy_ufw.yml

@proteusvacuum @nickpell this only allows certain traffic for monoliths, so no one can see our entire database...
http://manage.dimagi.com/default.asp?225659
cc: @millerdev

Monolith ufw

---

ansible/roles/nginx/vars/motech.yml

@emord 
Can you review and deploy again?

Fix indenting in MOTECH proxy

---

ansible/deploy_proxy.yml
ansible/roles/nginx/vars/cas_ssl.yml

http://manage.dimagi.com/default.asp?227311#1153291
https://github.com/dimagi/commcare-hq-deploy/pull/21
move cas to its own proxy
cc @esoergel

split out cas proxy to a different group

---

ansible/deploy_db.yml

Start ecryptfs on Riak machines

---

ansible/roles/couchdb/tasks/main.yml

seperate couchdb-install as it requires sudo privilege

---

ansible/roles/nginx/vars/motech.yml
ansible/roles/nginx/vars/motech_http.yml

@emord 
Figured out the problem with my Nginx config.  This should fix it.

Fix nginx config for MOTECH

---

ansible/roles/couchdb/tasks/main.yml

use correct paths

---

ansible/roles/commcarehq/templates/localsettings.py.j2

related to https://github.com/dimagi/commcarehq-prelogin/pull/80 and https://github.com/dimagi/commcare-hq/pull/11889
@czue @emord cc: @biyeun

adding fullstory_id to localsettings template

---

ansible/deploy_common.yml
ansible/inventories/development
ansible/roles/datadog/defaults/main.yml
ansible/roles/datadog/tasks/cloudant_integration.yml
ansible/roles/datadog/tasks/integrations.yml
ansible/roles/datadog/templates/celery.yaml.j2

add celery datadog integration

---

ansible/roles/common_installs/tasks/main.yml

add tmux to machines

---

ansible/roles/ssh/tasks/main.yml

Disable ssh password

---

provisioning/control.sh

use ansible 1.9 ppa

---

ansible/roles/ecryptfs/tasks/main.yml

verify that line ends up in fstab

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

@dannyroberts @snopoke @esoergel

restore max_local_storage_nodes setting

---

ansible/group_vars/all.yml

This line depends on this variable:
https://github.com/dimagi/commcarehq-ansible/blob/b3002b43dd42e986380125acf2f85956250e19a3/ansible/roles/datadog/tasks/integrations.yml#L7
@snopoke @millerdev

There's a hard failure if this isn't set

---

ansible/roles/nginx/vars/cas_ssl.yml

add missing locations to cas config

---

ansible/roles/postgresql/tasks/main.yml

Use postgres port

---

ansible/roles/ecryptfs/tasks/main.yml

Check fstab instead of mtab

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

Use null check properly

---

ansible/run_role.yml

@benrudolph @dannyroberts @snopoke
Are there any instances where we don't want this?

Include sudo for running individual roles

---

ansible/group_vars/all.yml

Add ability to skip checking riak control machine

---

ansible/roles/datadog/templates/riakcs.yaml.j2

I'm sure I this get fixed recently but can't find it.
@nickpell

use template variables

---

ansible/roles/datadog/templates/kafka.yaml.j2

remove v0.8.2.x stats

---

ansible/roles/commcarehq/templates/localsettings.py.j2

explicit LOG_HOME var

---

ansible/roles/datadog/templates/postgres.yaml.j2

don't use SSL for datadog connection to postgres

---

ansible/roles/datadog/templates/rabbitmq.yaml.j2

point datadog to rabbit host

---

ansible/roles/ansible-control/templates/sudoers.j2

Let the ansible user sudo without a password

---

ansible/group_vars/all.yml
ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cas_ssl.yml
ansible/roles/nginx/vars/cchq_http.yml
ansible/roles/nginx/vars/cchq_http_j2me.yml
ansible/roles/nginx/vars/cchq_http_redirect.yml
ansible/roles/nginx/vars/cchq_redirect.yml
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/commtrack_http.yml
ansible/roles/nginx/vars/commtrack_ssl.yml
ansible/roles/nginx/vars/dhis.yml
ansible/roles/nginx/vars/dhis_http.yml
ansible/roles/nginx/vars/hq_status.yml
ansible/roles/nginx/vars/icds_tableau.yml
ansible/roles/nginx/vars/icds_tableau_http.yml
ansible/roles/nginx/vars/motech.yml
ansible/roles/nginx/vars/motech1.yml
ansible/roles/nginx/vars/motech1_http.yml
ansible/roles/nginx/vars/motech2.yml
ansible/roles/nginx/vars/motech2_http.yml
ansible/roles/nginx/vars/motech_http.yml
ansible/roles/nginx/vars/riakcs.yml
ansible/roles/nginx/vars/wiki.yml
ansible/roles/nginx/vars/wiki_http.yml
ansible/roles/touchforms/templates/application.properties.j2

@wpride @snopoke (wasn't sure who to ping) this adds the ability to specify multiple balancers. essentially we'll be routing `/formplayer` requests to the formplayer server. i also did a pass to cleanup how locations were dealt with. Easiest read 🐟 . quite a lot of tech debt in this role
cc: @biyeun

Nginx formplayer proxy

---

README.md

Clarify ssh ForwardAgent instructions

---

ansible/roles/touchforms/templates/application.properties.j2

@wpride settings for formplayer. this is still pending on being able to set authentication params in the formplayer

Beginnings of smtp email for formplayer

---

ansible/roles/datadog/templates/cloudant.yaml.j2
ansible/vars/dev.yml

add separate credentials for cloudant monitoring

---

ansible/roles/touchforms/tasks/main.yml
ansible/roles/touchforms/vars/main.yml

@wpride @esoergel on the way to making the formplayer build a separate repo

Deploy local settings to both dirs

---

ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml
ansible/vars/swiss/swiss_public.yml

add Manish to all envs

---

ansible/roles/postgresql/tasks/main.yml

make notify use list

---

ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml

disable blobdb backup on prod and india

---

README.md
control/init.sh

small fixes to readme and aliases

---

README.md

update readme refs to reset-vms

---

ansible/roles/touchforms/tasks/main.yml

@wpride @czue more removing of the formplayer submodule

do not put app props in submodule directory

---

git-hooks/pre-commit.sh

@benrudolph this should fix the git hook
cc @czue

Fix git hook

---

ansible/vars/softlayer/softlayer_public.yml

Missed this in earlier PR
@czue @gcapalbo

Actually add private key to localsettings

---

ansible/roles/users/tasks/main.yml
ansible/roles/users/templates/sudoers.j2
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml
ansible/vars/swiss/swiss_public.yml

@dannyroberts @snopoke cc @esoergel @NoahCarnahan

De-authorize ansible public key

---

ansible/roles/kafka/templates/server.properties.j2

@benrudolph @snopoke I think this is safer than the current 1 week

bump kafka log retention to 4 weeks

---

ansible/group_vars/all.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml
ansible/vars/swiss/swiss_public.yml

@snopoke cc @NoahCarnahan @esoergel

Move dev users to group_vars/all.yml

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@czue @NoahCarnahan log file part

Export migration log file

---

ansible/roles/touchforms/templates/application.properties.j2

cross https://github.com/dimagi/formplayer/pull/90
@benrudolph

Add back in redis.hostname for locking

---

ansible/roles/ssh/tasks/main.yml

@millerdev @emord cc: @sravfeyn 
still not sure how that line got into the config but this should make sure it is removed. did a little readability cleanup as well

disabling challenge response authentication

---

ansible/roles/ssh/tasks/main.yml

@millerdev 
typo in last PR. this one runs

regexp not regex

---

ansible/roles/commcarehq/templates/localsettings.py.j2

http://manage.dimagi.com/default.asp?235774
@emord
cc @NoahCarnahan

add initiative

---

ansible/roles/nginx/vars/motech.yml

New server is in Virginia, and I already configured the DNS for motech3.internal.commcarehq.org

Add CDC motech server

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/softlayer/softlayer_public.yml

The first step in http://manage.dimagi.com/default.asp?235385

Add new postgres db to softlayer for ICDS ucrs

---

ansible/roles/nginx/vars/motech.yml

Reverts dimagi/commcarehq-ansible#514

Revert "Add CDC motech server"

---

ansible/deploy_db.yml
ansible/roles/touchforms/tasks/main.yml
ansible/roles/touchforms/templates/application.properties.j2
ansible/roles/touchforms/vars/main.yml

@wpride @dannyroberts this adds the dataDir property for formplayer

Make data dir for formplayer

---

ansible/roles/nginx/vars/motech.yml

Some MOTECH pages take a very long time to respond.

Increase time outs for MOTECH servers

---

ansible/roles/nginx/tasks/install.yml
ansible/roles/nginx/tasks/site.yml
ansible/roles/users/templates/sudoers.j2
ansible/vars/swiss/swiss_public.yml

@snopoke @dannyroberts this'll allow cchq to run `nginx` commands

Add nginx to cchq sudo abilities

---

ansible/roles/nginx/vars/motech.yml

@biyeun 
Let me know if this looks right (already created the DNS entry for this)

Change Motech 3 internal URL to internal-va

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/formplayer/templates/application.properties.j2
ansible/vars/dev/dev_public.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml
ansible/vars/swiss/swiss_public.yml

@wpride this'll add the appropriate couch settings for formplayer
cc: @gcapalbo

Couch settings

---

ansible/roles/formplayer/templates/application.properties.j2

Add database name to formplayer config

---

ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/roles/touchforms/templates/localsettings.py.j2
ansible/vars/swiss/swiss_public.yml

@gcapalbo this returns PG to working with localhost. also fixes cloudcare to properly request localhost since we don't have a cert on swiss, the call to the host would always fail
http://manage.dimagi.com/default.asp?237630

Back to localhost for swiss

---

ansible/roles/common_installs/tasks/main.yml
ansible/roles/elasticsearch/defaults/main.yml
ansible/roles/elasticsearch/tasks/main.yml

@snopoke @benrudolph 
I think that having separate buckets for each environment will be neater. adding this in before i deploy to prod/india

adding unique repos for each environment

---

ansible/vars/softlayer/softlayer_public.yml

add WS4REDIS_CONNECTION_HOST to softlayer env

---

ansible/roles/postgresql/templates/postgresql.conf.j2

@sravfeyn 
https://www.postgresql.org/docs/9.4/static/runtime-config-statistics.html#GUC-TRACK-FUNCTIONS

track function calls in postgresql

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

making es snapshot use correct aws region

---

ansible/roles/nginx/vars/motech.yml

This adds the entry for Pathfinder LAD motech server
@NoahCarnahan @emord @snopoke

Add Pathfinder LAD server

---

ansible/deploy_riakcs.yml
ansible/inventories/development
ansible/roles/ecryptfs/tasks/main.yml
ansible/roles/swap/tasks/main.yml

Review commits individually.
Prerequisite: https://github.com/dimagi/commcare-hq-deploy/pull/131
I tested this locally in vagrant. It has not yet been applied to prod.
@snopoke cc @kaapstorm @proteusvacuum

Add swap and fix mounts on riakcs hosts

---

ansible/roles/pg_standby/tasks/main.yml
ansible/roles/pg_standby/templates/restore_from_backup.sh.j2
ansible/roles/pg_standby/templates/retrieve_backup.py.j2

@snopoke @czue @benrudolph 
This provides scripts to allow 1 command for restoring postgres from a backup stored in s3.

adding restore command for pg s3 backups

---

ansible/roles/datadog/tasks/main.yml

restart datadog agent after pulling git changes

---

ansible/roles/pg_standby/templates/restore_from_backup.sh.j2

@snopoke 
From feedback on last PR. added a final prompt before copying into the data directory.

adding one more prompt

---

ansible/roles/swap/tasks/main.yml

Tested locally.
@proteusvacuum

Fix riakcs deploy without swap file

---

ansible/roles/common/tasks/main.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml

better etc hosts management

---

ansible/vars/softlayer/softlayer_public.yml

Add repeat record queue to softlayer

---

ansible/es_rolling_restart.yml
ansible/roles/elasticsearch/tasks/rolling_restart.yml

ES is configured to bind to it's IP so curls to `localhost` don't work
@benrudolph  @emord  @esoergel 
buddy @biyeun

use correct host for es curl commands

---

ansible/roles/formplayer/templates/application.properties.j2
ansible/vars/swiss/swiss_public.yml

@wpride this adds the deploy env to formplayer (hasn't been deployed yet)

Add deploy env

---

ansible/roles/nginx/tasks/restart.yml

@nickpell @czue 
adapted from https://github.com/jdauphant/ansible-role-nginx/blob/cc5cb82c5742d5a442b98c8ca2515459e75a07d1/handlers/main.yml#L17-L22
buddy @esoergel

check nginx -t

---

ansible/roles/commcarehq/templates/localsettings.py.j2

re: https://github.com/dimagi/commcare-hq/pull/13877#pullrequestreview-7957457
@czue @proteusvacuum

remove LUCENE_ENABLED from localsettings

---

ansible/vars/icds/icds_public.yml

Add tableau DBs to env

---

ansible/roles/postgresql/templates/pg_hba.conf.j2

Adding these users manually to `pg_hba.conf`

add tableau pg users to hba.conf

---

ansible/roles/http_proxy/tasks/main.yml

no proxy for local IPs

---

ansible/roles/commcarehq/templates/localsettings.py.j2

right now these files are getting logged to the code directory
@proteusvacuum @dannyroberts

Add UCR Laboratory logs

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/vars/icds/icds_public.yml

@calellowitz @czue 
The dirty hack to tableau hosting at `icds-cas.gov.in/reporting/`.

host tableau at /reporting/ hq url suffix for icds env

---

ansible/group_vars/all.yml
ansible/group_vars/formplayer.yml
ansible/roles/datadog/tasks/integrations.yml
ansible/roles/datadog/templates/jmx.yaml.j2

@snopoke @wpride this is up and running on formplayer and the jmxfetch process is running, but it's unclear if any metrics are actually being collected. will poke at it some more tomorrow. got list of beans from spring actuator

Initial JMX monitoring

---

ansible/roles/formplayer/templates/application.properties.j2

@snopoke @wpride adds the actuator endpoints to the application properties

Add actuator endpoints

---

ansible/roles/common_installs/tasks/main.yml

anyone. no matter what, there are always ansible error on a deploy_stack

Misc fixes

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/swiss/swiss_public.yml

activate preview A/B test by setting ONBOARDING_DOMAIN_TEST_DATE

---

ansible/roles/formplayer/meta/main.yml

Add java dep to formplayer

---

ansible/roles/riakcs/README.md
ansible/roles/riakcs/configure/tasks/main.yml
ansible/roles/riakcs/configure/vars/main.yml
ansible/roles/riakcs/create_admin_user/tasks/main.yml
ansible/roles/riakcs/install/tasks/main.yml
ansible/roles/riakcs/join_cluster.yml
ansible/roles/riakcs/sync_keys/tasks/main.yml

Probably easiest to review commits individually 🐠 
@snopoke

Make riak deploys safer: no config updates by default and make --check work

---

ansible/roles/riakcs/README.md
ansible/roles/riakcs/configure/handlers/main.yml
ansible/roles/riakcs/configure/tasks/main.yml
ansible/roles/riakcs/install/tasks/main.yml
ansible/roles/riakcs/join_cluster.yml
ansible/roles/riakcs/sync_keys/tasks/main.yml

Also more fixes for --check
@snopoke

More tweaks to make riak deploys to individual nodes possible

---

provisioning/control.sh
provisioning/nodes.sh

@millerdev  cc @dannyroberts @mkangia

Some fixes for working with vagrant

---

README.md
Vagrantfile
Vagrantfile-monolith
ansible/roles/couchdb/tasks/main.yml
ansible/roles/couchdb/vars/main.yml
ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
ansible/vars/dev/dev_public.yml
provisioning/control.sh

We're getting there.
Small changes, but might be easier to :tropical_fish: so you can see the comment on 1262b514
@millerdev cc @dannyroberts @mkangia

Fix developer setup

---

ansible/deploy_formplayer.yml
ansible/roles/common_installs/tasks/main.yml
ansible/roles/newrelic-java/tasks/main.yml
ansible/roles/newrelic-java/templates/newrelic.yml.j2
ansible/roles/newrelic-java/vars/main.yml

@snopoke this install the newrelic java agent on our machines. just need to update our supervisor conf to point to it
cc: @emord

newrelic java

---

ansible/roles/datadog/templates/jmx.yaml.j2

@snopoke @wpride according to the datadog [docs](https://help.datadoghq.com/hc/en-us/articles/207874586-Collecting-Composite-type-JMX-attributes) this is how you add a composite data bean... i'm not confident this will work, but going to try and play around with it since it'd be really nice to have
cc: @emord

Add Perm Gen bean

---

ansible/deploy_riakcs.yml
ansible/roles/riakcs/configure/tasks/main.yml

@czue - has already been used to deploy prod, so can be merged any time.

Fix riak_nodename not set for control node

---

ansible/roles/common_installs/tasks/main.yml

add iotop to default installs

---

ansible/vars/icds/icds_public.yml

move commcarehq db to new postgresql server

---

ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/vars/icds/icds_public.yml

adding performance tuning options to ICDS, and postgresql.conf template support for these options. @snopoke @kaapstorm

icds postgresql performance tuning, fogbugz 248996

---

ansible/vars/softlayer/softlayer_public.yml

@snopoke @benrudolph 
per our discussion on slack

doubling softlayer pgb connections

---

ansible/deploy_http_proxy.yml
ansible/inventories/development
ansible/roles/http_proxy/tasks/main.yml
ansible/roles/http_proxy/templates/bowerrc.j2
ansible/vars/dev/dev_public.yml
ansible/vars/icds/icds_public.yml

it improves on existing role: adds ftp proxy, uses https "insteadOf" for git, etc. already tested on my vagrant environment but you're welcome to give it a try as well.

forward proxy deployment

---

ansible/roles/nginx/vars/cas_ssl.yml

no remote ip based rate limit

---

ansible/roles/postgresql/tasks/main.yml

@snopoke @sravfeyn i've used this before to just make changes to postgresql config and of course notify (restart)

tag postgresql configuration

---

ansible/vars/icds/icds_public.yml

we have to change this before next ansible deploy in icds

changes kafka log dir

---

ansible/roles/nginx/vars/icds_tableau.yml

http://manage.dimagi.com/default.asp?250699

set client max body size to 100m for tableau

---

ansible/roles/shared_dir/tasks/setup_host.yml

i wonder if max_age should allow a different setting per environment, please comment.

purge restore_payloads +mmin 8 hours

---

ansible/vars/icds/icds_public.yml

goes with https://github.com/dimagi/commcare-hq-deploy/pull/227
@sravfeyn @snopoke

combine icds pillows

---

ansible/roles/commcarehq/tasks/main.yml

fix localsettings deploy

---

ansible/roles/common/tasks/main.yml
ansible/vars/icds/icds_public.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml

this'll bump the file limits. the default on softlayer was 4096 when formplayer began running out of file descriptors and it wasn't anywhere near running out of memory (8GB machine). doesn't quite work, i think in the current form it requires a restart to take affect. looking into a work around

File limits increase

---

ansible/vars/staging/staging_public.yml

PR for password hashing is on staging now
https://github.com/dimagi/commcare-hq/pull/15490
Corresponding change to localsettings for staging to enable it

enable password hashing on staging

---

ansible/vars/production/production_public.yml

adding to actual localsettings

---

ansible/vars/production/production_public.yml

fixing syntax error

---

ansible/vars/dev/dev_public.yml

this just fixes proxy settings in dev_public, so that we can keep testing stuff in dev.

fixes proxy vars in development

---

ansible/roles/pg_standby/tasks/main.yml
ansible/roles/postgresql/tasks/main.yml

postgresql role in ansible relied heavily on sudo_user, this fixes it

replace sudo_user by pipelining in postgresql role

---

ansible/roles/nginx/tasks/errorpages.yml

again avoiding sudo, use pipelining instead

uses pipelining for errorpages

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/http_proxy/tasks/main.yml
ansible/roles/shared_dir/tasks/setup_host.yml

fix flattened and pipelining

---

ansible/roles/common/tasks/main.yml
ansible/vars/dev/dev_public.yml
ansible/vars/icds/icds_public.yml

this allows to set the hostname when "hostname" is defined , and domain name if specified

allows to set hostname

---

ansible/roles/common/tasks/main.yml

fitst step to allow setting timezone to UTC in all servers

sets timezone to UTC

---

ansible/roles/common/tasks/main.yml

disables and stops antivirus

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/http_proxy/tasks/main.yml

ansibale -> ansible

---

ansible/roles/datadog/vars/main.yml

this should allow us to get proper datadog timings from out couch logs

use proper hostname

---

ansible/roles/http_proxy/templates/bowerrc.j2

bower proxy config did not include port

bower proxy config needs port

---

ansible/vars/icds/icds_public.yml

already deployed (ok well, made changes manually) so no time pressure here, just wanted to make sure to get this into ansible
cc @orangejenny buddy

add adhaar_id_scanner_apk to icds_public.yml

---

ansible/roles/nginx/templates/default.j2

removes semicolon

---

ansible/vars/icds/icds_public.yml

@benrudolph @sravfeyn @javierwilson 
I bumped this change manually on pg2 while firefighting. someone had already done the same on pg1 and pg0.

bumping max connections

---

ansible/vars/softlayer/softlayer_public.yml

remove http:// from tableau server (nginx already adds http://)

---

ansible/roles/kafka/files/log4j.properties
ansible/roles/kafka/tasks/main.yml

kafkServer.out gets as big as 9GB these days

kafka stdout control

---

ansible/group_vars/couchdb.yml
ansible/roles/datadog/tasks/integrations.yml
ansible/roles/datadog/templates/couch.yaml.j2

couchdb datadog

---

ansible/deploy_riakcs.yml
ansible/roles/ecryptfs/tasks/main.yml
ansible/roles/lvm/tasks/main.yml
ansible/roles/riakcs/get_admin_keys.yml
ansible/roles/swap/tasks/main.yml

```
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
```
buddy @nickpell

swtich form always_run to check_mode

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/vars/icds/icds_public.yml

@sravfeyn @javierwilson @emord 
Changes for things that came up during the db migration, and the migration itself

moving dbs and fixng pgbouncer issue

---

ansible/roles/riakcs/configure/tasks/main.yml
ansible/roles/riakcs/install/defaults/main.yml

@millerdev this will create the log directories that i had to create by hand on pg2. Tested on pg3 and it works correctly

create log directory

---

ansible/roles/formplayer/templates/application.properties.j2
ansible/roles/formplayer/vars/main.yml
ansible/vars/icds/icds_public.yml

@sravfeyn @javierwilson fixes some settings for formplayer. still needs to be tested

fix up fp settings for icds

---

ansible/vars/icds/icds_public.yml

https://github.com/dimagi/commcare-hq-deploy/pull/240

new pillows

---

ansible/vars/icds/icds_public.yml

@emord I split this into it's own PR so that we can deploy the settings changes separately from the split
(this is a PR into #715 )

move icds userdb

---

ansible/roles/couchdb/tasks/main.yml
ansible/roles/couchdb/templates/couch-restarter.sh.j2

couch db restarter

---

ansible/roles/couchdb/templates/couch-restarter.sh.j2

(the fix has already been applied)

Fix couch restarter

---

ansible/deploy_zabbix.yml

stops and disables zabbix services

removes zabbix

---

ansible/roles/couchdb/templates/local.ini.j2

Enable {nodelay, true}

---

ansible/vars/staging/staging_public.yml

depends on https://github.com/dimagi/commcare-hq-deploy/compare/dm/staging-new-riakcs
@javierwilson cc @emord

Prepare to end riak migration on staging

---

ansible/roles/datadog/templates/process.yaml.j2

Add couch to process ddog integration

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cas_ssl.yml

Couple of fixes for nginx role
@dimagi/scale-team @millerdev

fix rate limiting

---

ansible/roles/postgresql/tasks/main.yml
ansible/vars/icds/icds_public.yml

https://github.com/dimagi/commcare-hq-deploy/pull/247

move pg connection setting to inventory

---

ansible/deploy_db.yml

disable transparent huge pages THP

---

ansible/roles/nginx/vars/cas_ssl.yml

@dimagi/scale-team Talked in the meeting about bumping this up on monday if this weekend goes well
@dannyroberts

Bump up submissions rate limiting

---

ansible/roles/nginx/vars/cas_ssl.yml

Keeping it to a conservative 100 for now
@dimagi/scale-team @dannyroberts

add burst to submissions

---

ansible/roles/backups/templates/create_couchdb_backup.sh.j2

@javierwilson @snopoke 
this just adds remote backups to the couch machines

finishing couch backups for icds

---

ansible/vars/icds/icds_public.yml

Now the same across all envs: https://github.com/dimagi/commcare-hq/pull/16258

remove custom ICDS logging

---

ansible/roles/couchdb/templates/create_couchdb_backup.sh.j2

pruning remote couch backup dir

---

ansible/roles/nginx/vars/couchdb2.yml

ICDS app is > 1 MB so this needs to be larger

increase max client body size for couch

---

ansible/roles/couchdb2/vars/main.yml
ansible/roles/nginx/vars/couchdb2.yml

@dimagi/scale-team deployed these changes to icds

couch2 improvements

---

ansible/vars/softlayer/softlayer_public.yml

@javierwilson this changed with your recent pr. I fixed this on the webworkers manually

update flower url

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/formplayer/tasks/main.yml
ansible/roles/touchforms/tasks/main.yml

@emord as discussed. if it looks ok, i'll notify the team so people are aware
cc: @mkangia

Localsettings tags

---

ansible/group_vars/pg_standby.yml
ansible/roles/postgresql/templates/postgresql.conf.j2

also, cleaning up postgresql config, because if we need to, we should read the docs elsewhere

use default postgresql config for standbys

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/staging/staging_public.yml

@sheelio This will also need to change on icds and softlayer if you want to test there later

icds test staging

---

ansible/vars/icds/icds_public.yml

adding new ucrs to pillows

---

ansible/vars/icds/icds_public.yml

This will may halve the riak GETs we have since a forms get_document gets the form xml for every form.

one static form pillow

---

ansible/requirements.yml

adds https://github.com/emord/ansible-couchdb-cluster/commit/826df6010e191f17c35be598e9e4ba79d538c47f

update couchdb role for service script

---

ansible/vars/icds/icds_public.yml

@calellowitz I'll deploy this today

Combine static cases and child_health case pillows

---

ansible/roles/common/tasks/main.yml
ansible/roles/couchdb/tasks/main.yml
ansible/roles/datadog/tasks/main.yml
ansible/roles/ecryptfs/tasks/main.yml
ansible/roles/elasticsearch/tasks/main.yml
ansible/roles/kafka/tasks/main.yml
ansible/roles/newrelic/tasks/main.yml
ansible/roles/nginx/tasks/main.yml
ansible/roles/postgresql/tasks/main.yml
ansible/roles/redis/tasks/main.yml
ansible/roles/riakcs/configure/tasks/main.yml

first effort to try to automate tasks to be run after a machine is rebooted

after reboot tasks

---

ansible/ping.yml

this is a first effort, more complex tests should be added.  this is like a os-level check_services

ping hosts and checks status

---

ansible/roles/formplayer/vars/main.yml

@emord this was the whitespace issue

Kill whitespace

---

ansible/vars/icds/icds_public.yml

Combining some pillows. I think the ccs record monthly should be up to date soon and then this can be deployed.
@calellowitz

combine pillows

---

ansible/roles/datadog/templates/couch.yaml.j2

This is going to need the username for the new couch2 datadog integration.
buddy @esoergel

Updated couch.yaml for new datadog integration.

---

ansible/group_vars/all.yml

add datadog_integration_vmware

---

ansible/roles/couchdb2/vars/main.yml

@dimagi/scale-team this might be useful until we can implement https://trello.com/c/KGl4dlaN/123-cycle-synclogs-database-regularly

Compact synclogs more frequently

---

ansible/roles/nginx/tasks/errorpages.yml
ansible/roles/nginx/vars/main.yml
ansible/vars/icds/icds_public.yml

and use icds branding on icds
Puts https://github.com/dimagi/commcare-hq-errorpages/pull/12 into action

add support for different 50x.html pages

---

ansible/vars/softlayer/softlayer_public.yml

raise india pgbouncer_max_connections to 1000

---

ansible/vars/icds/icds_public.yml

for when https://github.com/dimagi/commcare-hq/pull/16938 and https://github.com/dimagi/commcare-hq/pull/16937 are merged and deployed tomorrow

Removed old v1 datasources.

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/icds/icds_public.yml

for https://github.com/dimagi/commcare-hq/pull/16967

Added off peak timings for ICDS.

---

ansible/vars/icds/icds_public.yml

@sheelio This should probably change in sol dev's code eventually but it's fine for now
buddy @esoergel

Point dashboard to real data.

---

ansible/roles/common/tasks/main.yml
ansible/roles/common_installs/tasks/main.yml

these lines failed if not defined, fixing it.
i also i like tagging NPM as it always re-installs and is slow (maybe also add to tag "slow"?)

small fixes go a long way

---

ansible/roles/common/tasks/main.yml
ansible/roles/common_installs/tasks/main.yml

Reverts dimagi/commcarehq-ansible#838

Revert "small fixes go a long way"

---

ansible/vars/icds/icds_public.yml

We have more queues, so going to queue more up at one time
@esoergel

Queue more async indicators at once on icds

---

ansible/group_vars/postgresql.yml
ansible/vars/production/production_public.yml

goes with https://github.com/dimagi/commcare-hq-deploy/pull/326

changes for hqdb1

---

ansible/requirements.yml

btw, ansible does a lousy job at handling role versions... so we may need to ansible-galaxy install --force -r requirements.yml

update ansible galaxy requirements

---

ansible/vars/icds/icds_public.yml

@dimagi/scale-team This should relieve a little stress on pg1/pg3 as there are 8 less processes trying to grab every case that comes in. it finally caught up over the backlog this weekend

Remove person pillow.

---

ansible/roles/couchdb/tasks/main.yml
ansible/roles/redis_monitoring/tasks/main.yml

so we only get an email if job fails

silent stdout for cron job

---

ansible/requirements.yml

:( had the wrong repo
@mkangia thisis important to fix and do a  ansible-galaxy install --force

fix couchdb2 requirement

---

ansible/roles/couchdb/templates/couch-restarter.sh.j2

No relaxation happening here :x: :relaxed: 
buddy  @orangejenny

couchdb2 restarter

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/softlayer/softlayer_public.yml

Add enikshay queue

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cas_ssl.yml

nginx proxy caching

---

ansible/roles/nginx/templates/site.j2

custom log format that includes cache status

---

ansible/deploy_proxy.yml
ansible/roles/nginx/templates/site.j2

Rotates the proxy and fixes a bug with log formatting
@biyeun

Log rotate couch proxy

---

ansible/roles/redis/vars/main.yml

https://raw.githubusercontent.com/antirez/redis/4.0/00-RELEASENOTES

upgrade to redis 4

---

ansible/roles/riakcs/configure/templates/riak.conf.j2

this will help us with the new cluster, and I don't see how it would hurt any other cluster.

set port range for riak inter-node communication

---

ansible/vars/icds/icds_public.yml
ansible/vars/softlayer/softlayer_public.yml

Added pg stats to ICDS and softlayer UCR.

---

ansible/roles/nginx/templates/default.j2
ansible/roles/nginx/templates/nginx.conf.j2
ansible/roles/nginx/templates/site.j2

This can only be defined once, but it's getting defined for every site
@snopoke @nickpell

fix log format

---

ansible/roles/riakcs/sync_keys/tasks/main.yml
ansible/vars/enikshay/enikshay_public.yml

not using proxy right now.
also, adding missing tag

datadog fixes for enikshay

---

ansible/roles/couchdb2/templates/couch2-restarter.sh.j2

Couchdb 2 restarter should be different than couch 1

---

ansible/deploy_http_proxy.yml
ansible/inventories/development
ansible/requirements.yml
ansible/roles/http_proxy/tasks/main.yml
ansible/vars/dev/dev_public.yml

tested this on my dev environment works fine, but each environment must add the parent vars for it to work

adding squid to http_proxy

---

ansible/vars/enikshay/enikshay_public.yml

@mkangia @snopoke @javierwilson

Set update_after for enikshay

---

ansible/vars/enikshay/enikshay_public.yml

this solves the connection timeout when trying to reach domains that resolve to a public IP

local ips for enikshay domains

---

control/init.sh

Add newline to printed output

---

ansible/roles/postgresql/tasks/main.yml
ansible/vars/icds/icds_public.yml

@dimagi/scale-team Just deployed this to icds. Will check in on it tomorrow

pg1 query stats

---

ansible/deploy_etckeeper.yml

for each git commit in /etc we were getting git errors

get rid of git error messages

---

ansible/vars/staging/staging_public.yml

Enable sms queuing on staging

---

ansible/deploy_common.yml
ansible/roles/common_installs/tasks/main.yml
ansible/roles/monit/tasks/main.yml
ansible/roles/monit/templates/monitrc.j2
ansible/roles/redis/tasks/main.yml
ansible/roles/redis/templates/monit.redis.j2
ansible/roles/redis_monitoring/tasks/main.yml

we can easily add more services (to be monitored), just wanted to start with redis

using monit to restart redis

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/enikshay/enikshay_public.yml

Bump max daily rule updates for enikshay

---

ansible/vars/enikshay/enikshay_public.yml
ansible/vars/production/production_public.yml

enable gzip archving on production

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Deploy after https://github.com/dimagi/commcare-hq/pull/17552

use hiredis for redis parser

---

ansible/stop_servers.yml

useful before shutting down a server or cluster.

playbook to stop all services

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/vars/dev/dev_public.yml
ansible/vars/enikshay/enikshay_public.yml
ansible/vars/icds/icds_public.yml
ansible/vars/l10k/l10k_public.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml
ansible/vars/swiss/swiss_public.yml

reporting databases

---

ansible/deploy_db.yml

nano commit to tag deploy_riakcs. i like skip-tagging riakcs

tagging riakcs

---

ansible/vars/softlayer/softlayer_public.yml

@snopoke This is needed for QA
@biyeun @proteusvacuum

Add icds ucr database for softlayer

---

ansible/vars/enikshay/enikshay_public.yml

Fixes max connections issues
@emord @javierwilson

double postgresql_max_connections on enikshay

---

ansible/stop_servers.yml

@snopoke this is in reference to https://github.com/dimagi/commcarehq-ansible/pull/898

postgresql and pgstandby go down together

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/postgresql/tasks/main.yml
ansible/vars/dev/dev_public.yml
ansible/vars/enikshay/enikshay_public.yml
ansible/vars/icds/icds_public.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml
ansible/vars/swiss/swiss_public.yml

buddy @kaapstorm 
along with https://github.com/dimagi/commcare-hq/pull/17643

handle read-only databases separately

---

ansible/vars/icds/icds_public.yml

@snopoke creating this for you and merging. thanks for fixing

migrate icds-ucr

---

ansible/group_vars/couchdb2.yml
ansible/roles/couchdb2/tasks/main.yml
ansible/roles/couchdb2/templates/monit.couchdb2.j2
ansible/roles/monit/handlers/main.yml
ansible/roles/redis/meta/main.yml
ansible/roles/redis/tasks/main.yml
ansible/roles/redis_monitoring/tasks/main.yml

also fixing removal of redis restarter and absense of couchdb_dir

monit couchdb2 / restarter

---

ansible/roles/postgresql/tasks/main.yml

@snopoke needed now that we have es0 in postgresql_dbs on ICDS
@biyeun @proteusvacuum

Fixed check to allow standby server

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2

testing this for enikshay, as it works for other users with firewall issues

keeping pgbouncer connections alive

---

ansible/roles/common/tasks/cron.yml
ansible/roles/common/tasks/main.yml
ansible/roles/elasticsearch/tasks/main.yml

extra load start at 6am UTC, just keeping it safe and moving these tasks out of the way

moving crontab tasks to nadir hour, also using modulus operator

---

ansible/vars/softlayer/softlayer_public.yml

remove ENIKSHAY_QUEUE from softlyaer

---

ansible/deploy_captain.yml
ansible/deploy_cleanup.yml
ansible/deploy_commcarehq.yml
ansible/deploy_common.yml
ansible/deploy_control.yml
ansible/deploy_db.yml
ansible/deploy_formplayer.yml
ansible/deploy_load_test.yml
ansible/deploy_lvm.yml
ansible/deploy_mailrelay.yml
ansible/deploy_proxy.yml
ansible/deploy_riakcs.yml
ansible/deploy_stack.yml
ansible/deploy_tmpreaper.yml
ansible/deploy_touchforms.yml
ansible/deploy_webworker.yml
ansible/deploy_zabbix.yml
ansible/es_rolling_restart.yml
ansible/run_role.yml
ansible/set_password.yml

fixing this in a few places, not all... yet.

sudo becomes become

---

ansible/vars/icds/icds_public.yml

@dimagi/scale-team I had to deploy this as es0 was not responsive today. After this things went mostly back to normal

Remove standby reads

---

ansible/roles/supervisor/tasks/main.yml
ansible/roles/users/tasks/main.yml

[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

replace always_run with check_mode

---

ansible/group_vars/all.yml
ansible/group_vars/celery.yml
ansible/group_vars/couchdb2.yml
ansible/roles/datadog/tasks/add_integrations.yml
ansible/roles/datadog/tasks/remove_integrations.yml
ansible/roles/datadog/templates/couchdb2.yaml.j2
ansible/vars/enikshay/enikshay_public.yml
ansible/vars/icds/icds_public.yml
ansible/vars/l10k/l10k_public.yml

only deploy config to one server

fixes for couchdb2 and celery datadog monitoring

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cchq_ssl.yml

@dannyroberts @javierwilson 
I'm going off of the `cas_ssl` example and these docs: 
https://www.nginx.com/resources/admin-guide/content-caching/

cache prelogin pages

---

ansible/vars/enikshay/enikshay_public.yml

Increase pgbouncer settings

---

ansible/ansible.cfg
ansible/deploy_control.yml
ansible/roles/ansible-control/tasks/main.yml

ansible logging

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/icds/icds_public.yml

goes with https://github.com/dimagi/commcare-hq/pull/17865
@gcapalbo @sravfeyn

soft limit ucr

---

ansible/vars/icds/icds_public.yml

@gcapalbo @sravfeyn mistake from yesterday's PR

Run async queue until 7:55

---

ansible/vars/icds/icds_public.yml

This is in the inventory now https://github.com/dimagi/commcare-hq-deploy/pull/381/files
@sravfeyn

Remove work_mem from ICDS

---

ansible/roles/datadog/defaults/main.yml
ansible/roles/datadog/tasks/add_integrations.yml
ansible/roles/datadog/tasks/remove_integrations.yml
ansible/roles/datadog/templates/jmx.yaml.j2

Also found a followup bug to https://github.com/dimagi/commcarehq-ansible/pull/948.
This is already deployed to enikshay and production

fix formplayer jmx stats by checking port 9998 too

---

ansible/roles/nginx/vars/cas_ssl.yml

This is what's actually deployed at the moment @snopoke @gcapalbo @calellowitz

Update submission rate limiting

---

ansible/deploy_chaos.yml
ansible/roles/chaos/defaults/main.yml
ansible/roles/chaos/templates/burnio.j2

Hopefully this will allow me to create more IO disruption on hosts with very low IO activity. Worked very well when tested locally on vagrant.
@snopoke

Add BurnIO scale

---

ansible/vars/swiss/swiss_public.yml

This reverts commit 37f2f901755910bac7bb1bdac0d5dcb1a3d7d104.

Revert "add couchdb2 settings template to swiss_public.yml"

---

ansible/vars/enikshay/enikshay_public.yml

no enikshay prelogin

---

ansible/vars/icds/icds_public.yml

buddy @nickpell 
https://manage.dimagi.com/default.asp?262322

point formplayer at icds-cas.gov.in

---

ansible/requirements.txt

necessary for a fresh install to work

upgrade to cryptography==2.1.1

---

ansible/vars/pna/pna_public.yml

java 32bit doens't support more than 2GB heap

---

ansible/roles/nginx/vars/cas_ssl.yml
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/enikshay_ssl.yml

This will enable http2 on all envs except swiss @snopoke

Enable http2

---

ansible/requirements.txt

@dannyroberts your pr was released.
side note that we should probably pin the others to a version
buddy @snopoke

Upgrade ansible 2.4.1

---

ansible/deploy_netvault.yml

deploy netvault

---

ansible/roles/postgresql/templates/postgresql.conf.j2

disable temp file logging

---

ansible/roles/nginx/vars/pna_ssl.yml

@emord cc @javierwilson @snopoke buddy @millerdev

Increase client_body_buffer_size

---

ansible/ansible.cfg

This speeds up successive playbook runs and also runs that span multiple playbooks

cache facts

---

ansible/roles/postgresql/tasks/main.yml

check if we need to download pghashlib

---

ansible/group_vars/all.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/enikshay/enikshay_public.yml
ansible/vars/icds/icds_public.yml
ansible/vars/production/production_public.yml

@dannyroberts 
Feedback about the daily deploy emails, so changing them to only go eNikshay / ICDS / production. 
Does this work?

Only send daily deploy for certain environments

---

ansible/roles/common_installs/tasks/main.yml

Stop installing LESS 1.3

---

ansible/roles/nginx/tasks/install.yml
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pgbouncer.defaults.j2
ansible/roles/postgresql/templates/pgbouncer.init.j2
ansible/roles/redis/tasks/main.yml
ansible/vars/dev/dev_public.yml

for nginx, pgbouncer and redis

makes sure ulimit can be set high

---

ansible/roles/users/tasks/main.yml

without this, aps led to killing ALL processes on my VMs. scary.

only kill if there are users to remove

---

commcare-cloud/commcare_cloud.py
control/init.sh

Add better `commcare-cloud -h`, validate environment arg, and ease onboarding through the ansible control banner.

Commcare cloud help

---

ansible/deploy_common.yml
ansible/vars/dev/dev_public.yml

FYI currently net_static_route only works on some network devices (cisco routers ans similar) not in debian, and it's still experimental :(

 possibility of adding static routes to hosts

---

control/init.sh
control/update_code.sh

found these were causing error output

fix harmless init errors

---

ansible/roles/postgresql/tasks/main.yml

was getting errors since standbys are read only

don't create extension on standby

---

commcare-cloud/commcare_cloud.py

First few commit come from https://github.com/dimagi/commcarehq-ansible/pull/1052

bootstrap user command + run shell command

---

ansible/roles/datadog/vars/main.yml

remove old datadog parsers

---

ansible/vars/icds-new/icds-new_public.yml

Fix couch 2 password

---

ansible/requirements.txt
ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/vars/icds-new/icds-new_public.yml

This also makes it unnecessary to change PG config when we add more nodes

simplify pg_hba.conf by using IP ranges

---

ansible/roles/common_installs/tasks/main.yml

this allows to move a running process into a tmux session.

adding reptyr

---

commcare-cloud/commcare_cloud.py

pass through extra args

---

commcare-cloud/commcare_cloud.py

Closes https://github.com/dimagi/commcarehq-ansible/issues/1087

Commcare cloud warn on diff check

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/pna/pna_public.yml

Override email addresses for PNA

---

commcare-cloud/commcare_cloud.py

was previously giving `You are not on branch master. To deploy anyway, use --branch=(HEAD`

commcare-cloud: detect remote branch

---

commcare-cloud/commcare_cloud.py

changing only what is different

make run-shell-command help output conform to ansible -h

---

commcare-cloud/commcare_cloud.py
control/update_code.sh

Tweak scripts

---

ansible/promote_pg_standby.yml
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/recovery.conf.j2
ansible/setup_pg_standby.yml

buddy @biyeun 
Taken from https://opensource.com/article/17/6/ansible-postgresql-operations

playbooks for setting up PG standby nodes and for failover

---

ansible/deploy_proxy.yml
ansible/inventories/development
ansible/vars/dev/dev_public.yml
ansible/vars/enikshay/enikshay_public.yml
ansible/vars/icds-new/icds-new_public.yml
ansible/vars/icds/icds_public.yml
ansible/vars/l10k/l10k_public.yml
ansible/vars/pna/pna_public.yml
ansible/vars/softlayer/softlayer_public.yml

PR into #1122 
Goes with https://github.com/dimagi/commcare-hq-deploy/pull/463

only install couchdb2 proxy on couchdb2_proxy group

---

ansible/group_vars/all.yml
ansible/vars/enikshay/enikshay_public.yml

Override riakcs_proxy_port on enikshay

---

ansible/vars/icds-new/icds-new_public.yml

change icds-new hostnames

---

ansible/vars/icds/icds_public.yml

from old cluster to the new one

nic static route

---

ansible/roles/couchdb2/tasks/main.yml
ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2

mkdir wont work from script since it requires w permission to parent (my bad)

creates couchdb backup dir

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/production/production_public.yml
ansible/vars/staging/staging_public.yml

For https://github.com/dimagi/commcare-hq/pull/18841 and https://github.com/dimagi/commcare-hq/pull/18859 but can be merged/deployed independently.
@calellowitz

Add analytics debug flag and log level

---

ansible/roles/backups/templates/create_blobdb_backup.sh.j2
ansible/roles/couchdb/templates/create_couchdb_backup.sh.j2
ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2

couch and blob backups in PNA not being copy to s3 due to missing quote

fix missing quote

---

ansible/roles/postgresql/templates/postgresql.conf.j2

increase wal senders

---

ansible/ansible.cfg

I've been using this for a while and haven't had any issues with it.

enable pipelining

---

ansible/roles/couchdb2/tasks/main.yml

cleans up old cron tasks with misleading name

---

ansible/deploy_cleanup.yml
ansible/roles/touchforms/defaults/main.yml
ansible/roles/touchforms/tasks/cleanup.yml

this cleans up touchforms garbage when touchforms is disabled or mvoed.
@kaapstorm should we touchforms_enabled: false for PNA?

clean up touchforms

---

ansible/stop_servers.yml

remove lingering commands from stop_server.yml

---

ansible/vars/icds-new/icds-new_public.yml

Now that pgucrstandby is back up we can do this again.

user ucr standby for read only queries

---

ansible/setup_pg_standby.yml

use correct version of pg_basebackup

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Introduced in https://github.com/dimagi/commcarehq-ansible/pull/1132
https://manage.dimagi.com/default.asp?267202
@proteusvacuum

ANALYTICS_CONFIG.DEBUG should be a bool

---

ansible/vars/icds-new/icds-new_public.yml

old es0 as squid

---

ansible/roles/backups/defaults/main.yml
ansible/roles/riakcs/create_admin_user/tasks/main.yml
ansible/vars/dev/dev_public.yml

@sravfeyn  @calellowitz you didn't catch the include_vars error for riak? maybe because of the version of ansible you were using?

fixing undef vars for dev environment

---

fab/fab/environments.yml

more pillows for processing cases

---

fab/fab/environments.yml

correct IP for pillow2

---

fab/fab/environments.yml

Enable messaging on icds-new

---

ansible/roles/nginx/vars/cas_ssl.yml

bump form rate limit

---

ansible/vars/icds-new/icds-new_public.yml

@dimagi/scale-team if anyone's around I'd like to have the option of merging/deploying this if I want to later

double queue size

---

ansible/vars/icds-new/icds-new_public.yml
fab/fab/inventory/icds-new

port 3128 is open, time to go back to real patch

use real proxy

---

fab/fab/inventory/icds-new

adding disks to riak

---

ansible/vars/icds-new/icds-new_public.yml

doesn't look like we're keeping up with the incoming rate of indicators yet so increasing this some more

double again

---

ansible/deploy_mailrelay.yml

this removes unbutu's initial bind to localhost, allows to listen to other hosts

unbind postfix form localhost

---

ansible/vars/icds-new/icds-new_public.yml

I think this should probably be okay?

get a few more hours of processing in

---

ansible/deploy_mailrelay.yml

not sure why this was set to error in mail relay (web0)

 fix postfix default to error

---

commcare-cloud/commcare_cloud/commcare_cloud.py

finally getting around to this. Fixes #1175

Make run shell command quiet

---

control/check_install.sh

I had meant to include this in the previous commit. Quick followup to https://github.com/dimagi/commcarehq-ansible/pull/1204

change check_install.sh to print cononical paths

---

commcare-cloud/commcare_cloud/commcare_cloud.py

currently only (slight) advantage is that you can run a fab command
from any directory (as long as you are in the virtualenv, of course)
also sort of a followup to https://github.com/dimagi/commcarehq-ansible/pull/1179#issuecomment-354874251

add fab command to commcare-cloud

---

fab/fab/environments.yml

Should only be merged once https://github.com/dimagi/commcare-hq/pull/18997 is merged
@orangejenny

Increase production sms workers

---

ansible/roles/datadog/vars/main.yml

Followup to https://github.com/dimagi/datadog-parsers/pull/21

add nginx.error_log via datadog_parsers var

---

scripts/inventory/mosh
scripts/inventory/ssh

make scripts/inventory/ssh runnable from any dir

---

commcare-cloud/commcare_cloud/commcare_cloud.py

and as a bonus, make it runnable outside the virtualenv!
(You can run ~/.virtualenvs/ansible/bin/commcare-cloud
or more practically link it to somewhere on your PATH.)

fix i/o issues with commcare-cloud <env> fab

---

commcare-cloud/commcare_cloud/commcare_cloud.py

good with [?w=1](https://github.com/dimagi/commcarehq-ansible/pull/1226/files?w=1)

clean up Fab command

---

commcare-cloud/commcare_cloud/commcare_cloud.py
commcare-cloud/commcare_cloud/paths.py

add virtualenv bin directory to PATH upon start, thus ensuring that any subprocesses use the virtualenv version

run any commcare-cloud command outside virtualenv

---

environments/production/app-processes.yml

Increase sms worker concurrency

---

commcare-cloud/README.md

https://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html#setvirtualenvproject
@dannyroberts

virtualenvwrapper has a command for this

---

commcare-cloud/README.md
install.sh
requirements.txt

Feedback from https://github.com/dimagi/commcarehq-ansible/pull/1234

respond to feedback on commcare-cloud docs

---

commcare-cloud/commcare_cloud/commcare_cloud.py

add after-reboot command

---

commcare-cloud/README.md
control/check_install.sh
control/init.sh

OK I found what I believe to be a much nicer way to do this. A lot easier to tell the user what to do in the README.

Link to executables dir

---

README.md

update vault commands in README

---

commcare-cloud/commcare_cloud/commcare_cloud.py

Simpler way to find current branch

---

ansible/roles/commcarehq/templates/localsettings.py.j2
environments/icds-new/public.yml

https://github.com/dimagi/commcare-hq/pull/19100
@czue @nickpell

Added new async queue variable to icds.

---

fab/fab/etc_hosts.py
fab/fab/fabfile.py
fab/fab/operations/supervisor.py
fab/fab/utils.py

I came across this and could see it right away it hadn't been updated for the recent fab reorganization. This both fixes it and simplifies it to use shared helper functions.

fix fab/fab/etc_hosts.py

---

control/init.sh

Update control banner to give alternate for 'ae'

---

commcare-cloud/commcare_cloud/getinventory.py

broken since #1260 (author: me).

fix ssh command

---

control/check_install.sh

to support rename of commcarehq-ansible repo to commcare-cloud

make check_install.sh rename origin if recognized as old origin

---

environments/icds
environments/icds/fab-settings.yml

Make icds an alias to icds-new

---

fab/fab/operations/supervisor.py
fab/fab/services/templates/supervisor_handle_survey_actions.conf

Depends on https://github.com/dimagi/commcare-hq/pull/19161
@proteusvacuum

Add a process for handle_survey_actions

---

ansible/roles/commcarehq/templates/localsettings.py.j2
environments/icds-new/public.yml
environments/softlayer/public.yml

Merge and deploy after dimagi/commcare-hq#18962 is live

remove legacy ICDS UCR settings

---

ansible/roles/nginx/vars/main.yml

currently envs without this defined fail

give nginx_hsts_max_age a default value

---

environments/icds-new/public.yml

@czue  you may have been onto something with https://github.com/dimagi/commcare-hq/pull/19100#discussion_r160874006
I'll do a followup with test for real
@dannyroberts

Fixed queue times

---

ansible/group_vars/all.yml
ansible/roles/ssh/tasks/main.yml
environments/swiss/public.yml

some clusters still need this.

allows to enable ssh passwords

---

ansible/roles/postgresql/templates/pg_hba.conf.j2
environments/swiss/public.yml

- In `ansible/roles/postgresql/templates/pg_hba.conf.j2`
devreadonly is added since it was there in the pg_hba.conf of Swiss Postgres and it's vault file

modification to make Swiss Ansible deployable 

---

ansible/roles/kafka/tasks/main.yml

added ignore errors in Kafka role

Added ignore errors in kafka : install ruby

---

environments/swiss/public.yml

also, it's using 127.0.0.1 (not a host listed in the inv)

no hosts since swiss is a monolith

---

ansible/roles/newrelic-java/tasks/main.yml

since it's a check, zip file won't exist

ignore unzip error on check

---

environments/production/app-processes.yml

Goes with https://github.com/dimagi/commcare-hq/pull/19235
@orangejenny

Add ils_gateway_sms_queue worker

---

environments/swiss/public.yml

Added Backup Flags for local backup.

Enabled backup flags

---

ansible/deploy_proxy.yml

added tag to control nginx_sites

added tag nginx_sites

---

ansible/roles/nginx/vars/cas_ssl.yml

@calellowitz @snopoke I think you guys were changing this on the server? Looks like this is what it is currently

Set submissions rate limiting to 25 r/s

---

ansible/roles/elasticsearch/tasks/main.yml
ansible/roles/elasticsearch/templates/create_es_snapshot.py.j2
environments/swiss/public.yml

- Added Flag to change days of backup to keep. 
- Added check snapshot status , Delete function was throwing error since create snapshot was not completed. 
`elasticsearch.exceptions.TransportError: TransportError(503, u'ConcurrentSnapshotExecutionException[[pna_es_snapshot:pna_es_snapshot_2017_12_23] another snapshot is currently running cannot delete]')`

Modifications in elasticesearch snapshot script

---

ansible/roles/datadog/templates/datadog.conf.j2

https://www.datadoghq.com/blog/live-process-monitoring

enable process agent

---

ansible/deploy_touchforms.yml
environments/pna/public.yml

no key store and no new relic, also, tagging touchforms (to ble able to skip it)

clean up vars for PNA

---

environments/production/app-processes.yml
environments/production/inventory.ini

Add hqpillowtop2

---

environments/pna/app-processes.yml

Added celery queue to PNA.

---

ansible/group_vars/all.yml
ansible/roles/elasticsearch/tasks/main.yml
ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
ansible/roles/elasticsearch/templates/create_es_snapshot.py.j2

- es_local_repo variable added to enable or disable local backups. 
- the local backup will occur only if the remote s3 backup is false. 
- the default value of es_local_repo is false, set in group_vars/all.yml

added local backup plays

---

environments/enikshay/app-processes.yml
environments/icds-new/app-processes.yml
environments/l10k/app-processes.yml
environments/pna/app-processes.yml
environments/production/app-processes.yml
environments/softlayer/app-processes.yml
environments/staging/app-processes.yml
environments/swiss/app-processes.yml
tests/test_environments.py

replaces https://github.com/dimagi/commcare-cloud/pull/1337

case_rule_queue

---

environments/production/inventory.ini

Nodes were running out of memory:
https://app.datadoghq.com/monitors#1278009?to_ts=1518560272157&group=device%3A%2Fdev%2Fmapper%2Fconsolidated-data1%2Cenvironment%3Aproduction%2Chost%3Ahqriak31&from_ts=1515968272157

add hqriak32, hqriak33, hqriak34

---

commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commcare_cloud.py

same as bootstrap-users but does not run as root.
Good for keeping user config in sync on an ongoing environment

add update-users command

---

ansible/roles/shared_dir/tasks/setup_host.yml
environments/icds-new/app-processes.yml
environments/icds-new/inventory.ini

new celery and pillow VMs

---

docs/.gitignore
docs/Gemfile
docs/README.md
docs/_config.yml
docs/index.md

this should get github pages working

add jekyll config for doc site

---

ansible/roles/setup_auth_keys.yml

delegate to full hostname

---

ansible/deploy_common.yml
environments/icds-new/public.yml

disable UFW for ICDS

---

commcare-cloud/commcare_cloud/commands/ansible/run_module.py

`--become-user` does not imply `become`
buddies @millerdev @esoergel

always add '--become' if specified

---

environments/icds-new/app-processes.yml

https://sentry.io/dimagi/commcarehq/issues/474867872/?referrer=slack

Fix indentation

---

ansible/roles/commcarehq/templates/localsettings.py.j2

fix syntax

---

environments/icds-new/public.yml

Add new partitioned thr_forms to pillow

---

.travis.yml
commcare-cloud/setup.py
control/init.sh
test_requirements.txt

install using `source control/init.sh` rather than duplicating just the important bits

test init.sh script in travis

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/getinventory.py

@dannyroberts re: https://github.com/dimagi/commcare-cloud/pull/1415#issuecomment-369724345

Fix inventory lookup (ssh, mosh, etc.)

---

control/init.sh

Log in and update-code on control machines should now be a raging success. Sorry for not testing this better: https://github.com/dimagi/commcare-cloud/pull/1414

fix init script on control machine

---

environments/production/app-processes.yml

To help balance resource usage a bit
@nickpell @orangejenny

Move case_rule_queue consumer to hqcelery1

---

environments/enikshay/public.yml
environments/softlayer/public.yml

Just adds the nginx location for data dumps for enikshay on enikshay and india.
All files are in place and this is tested.

Add location for data dumps

---

ansible/roles/common/tasks/main.yml
ansible/roles/common/tasks/mount.yml

solving post-merge comments in https://github.com/dimagi/commcare-cloud/pull/1416
also, this should be applied to all our playbooks.

import mount task (not include)

---

docs/_config.yml
docs/howto/move-partitioned-database.md

https://github.com/dimagi/commcare-cloud/pull/1428

PR feedback for #1428

---

ansible/roles/commcarehq/templates/localsettings.py.j2
environments/icds-new/public.yml

comainion to: https://github.com/dimagi/commcare-hq/pull/19701

disable repeaters on ICDS

---

commcare-cloud/commcare_cloud/environment/paths.py

== memoized_property
https://github.com/dimagi/commcare-cloud/pull/1438/files/cadae44a56442b04ae96691e086afd6ca9d9ac76#diff-32c9d882b7ec6336c78cff296844bf2f

use lazy_immutable_property alias in DefaultPaths

---

ansible/group_vars/all.yml

default link seems to have broken

override couchdb mirror to one that works

---

ansible/roles/commcarehq/templates/localsettings.py.j2

adding warehouse db alias to localsettings

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/common_installs/defaults/main.yml
ansible/roles/pg_backup/defaults/main.yml
ansible/roles/postgresql/defaults/main.yml
environments/enikshay/public.yml
environments/production/public.yml
environments/staging/public.yml

@snopoke https://github.com/dimagi/commcare-cloud/pull/1447#issuecomment-371179211

synclogs db on staging

---

README.md
control/init.sh

can review per commit :fish: 
buddies @sravfeyn @esoergel

install script fixes and tweaks

---

ansible/roles/newrelic-java/tasks/main.yml

noticed this when running deploy_formplayer.yml

fix newrelic-java role (for formplayer)

---

environments/l10k/public.yml
environments/swiss/public.yml

@snopoke forgot these two in the previous PR. The `motech` env is not really in existence, yeah?

synclogs db on swiss, l10k

---

environments/icds-new/app-processes.yml

https://github.com/dimagi/commcare-hq/pull/19738
@proteusvacuum @dannyroberts

Add four workers for the dashboard reports

---

commcare-cloud/commcare_cloud/environment/schemas/app_processes.py
environments/softlayer/app-processes.yml

follow up for https://github.com/dimagi/commcare-cloud/pull/1464
Didn't realize that we statically check this. pretty cool @dannyroberts 
also adding for softlayer so that QA works

Include queue for softlayer

---

environments/softlayer/public.yml

Remove unused DB in softlayer

---

fab/fab/checks/check_servers.py
fab/fab/fabfile.py
fab/fab/operations/db.py

see https://github.com/dimagi/commcare-hq/pull/19766

run django checks after migration

---

ansible/roles/common_installs/tasks/main.yml
commcare-cloud-bootstrap/bootstrap.sh
commcare-cloud-bootstrap/commcare_cloud_bootstrap.py
commcare-cloud-bootstrap/environment/public.yml
commcare-cloud-bootstrap/specs/example_spec.yml

add bootstrap script to patch all the steps together

---

environments/production/inventory.ini

deploying off this branch (re: http://manage.dimagi.com/default.asp?272339)

change production formplayer machine

---

commcare-cloud/commcare_cloud/commcare_cloud.py

add --control before any command to run it on the control machine instead
What do you think?

add ability to run on control machine instead

---

environments/icds-new/public.yml

Reverts dimagi/commcare-cloud#1482

Revert "Changed p5 and p6 host"

---

environments/icds-new/public.yml

Forgot to add earlier, and kicking off a build of this data source

Add postnatal care forms to icds ucr

---

ansible/roles/backups/templates/backup_snapshots.py.j2
ansible/roles/backups/templates/create_blobdb_backup.sh.j2
ansible/roles/couchdb/templates/create_couchdb_backup.sh.j2
ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2
ansible/roles/pg_backup/templates/plain/create_postgres_dump.sh.j2
environments/production/public.yml

Upload Files with the same name. 
This will cause them to have different versions in s3. if versioning is enabled.

Modification to use Versioing in S3

---

environments/production/public.yml

1st commit is just a refactor
Don't merge

move prod synclog DB to new host

---

ansible/group_vars/all.yml
ansible/roles/redis/defaults/main.yml
ansible/roles/redis/tasks/main.yml
ansible/roles/redis/templates/redis.conf.j2
environments/enikshay/public.yml
environments/icds-new/public.yml
environments/l10k/public.yml
environments/pna/public.yml
environments/production/inventory.ini
environments/production/public.yml
environments/softlayer/public.yml
environments/staging/public.yml
environments/swiss/public.yml

buddies @sravfeyn @esoergel 
Can review per commit :fish:

redis conf refactor

---

.travis/environments/travis/app-processes.yml
commcare-cloud-bootstrap/environment/app-processes.yml.j2
commcare-cloud/commcare_cloud/environment/schemas/app_processes.py
environments/enikshay/app-processes.yml
environments/icds-new/app-processes.yml
environments/l10k/app-processes.yml
environments/pna/app-processes.yml
environments/production/app-processes.yml
environments/softlayer/app-processes.yml
environments/staging/app-processes.yml
environments/swiss/app-processes.yml

Add export download queue to each env

---

commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commands/ansible/helpers.py

fix weird password prompting for bootstrap-users

---

commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commands/ansible/run_module.py
commcare-cloud/commcare_cloud/commands/fab.py
commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
commcare-cloud/commcare_cloud/commands/validate_environment_settings.py
commcare-cloud/commcare_cloud/commcare_cloud.py

arose from discussion at https://github.com/dimagi/commcare-cloud/pull/1475#discussion_r176152232.

rename args.environment to args.env_name

---

fab/fab/utils.py

https://github.com/dimagi/commcare-cloud/pull/1504#discussion_r175884165

raise exception with actionable error message

---

commcare-cloud-bootstrap/environment/app-processes.yml.j2
environments/enikshay/app-processes.yml
environments/icds-new/app-processes.yml
environments/l10k/app-processes.yml
environments/pna/app-processes.yml
environments/production/app-processes.yml
environments/softlayer/app-processes.yml
environments/staging/app-processes.yml
environments/swiss/app-processes.yml

I thought I had already done this, but back in May I removed these from the HQ code https://github.com/dimagi/commcare-hq/pull/15972

Remove old blob deletion pillows

---

ansible/roles/datadog/tasks/main.yml

https://help.datadoghq.com/hc/en-us/articles/360000886852-Agent-APT-Repo-Key-Rotation
hit this today when deploying the datadog role

Datadog rotated their key

---

commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commcare_cloud.py

Following up with an alias from my last PR. Happy to change the name if something else makes sense.

Added cchq command to update services.

---

ansible/deploy_proxy.yml
commcare-cloud-bootstrap/environment/public.yml
environments/development/public.yml
environments/production/public.yml
environments/staging/public.yml
environments/swiss/public.yml

I think since https://github.com/dimagi/commcare-cloud/pull/1123 couchdb2 proxy
just doesn't get updated

fix couchdb2_proxy setup

---

commcare-cloud/commcare_cloud/commands/celery_utils.py
commcare-cloud/commcare_cloud/environment/main.py
fab/fab/fabfile.py
tests/test_environments.py

the right one to use should be the easier one to use

rename to app_processes_config and raw_app_processes_config

---

environments/enikshay/public.yml
environments/softlayer/public.yml

Required files/directory already added on the server.

add location under nginx for private sector data dumps

---

ansible/add-ssh-keys.yml
commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commcare_cloud.py
commcare-cloud/commcare_cloud/environment/main.py

`commcare-cloud production update-local-known-hosts`

add update-local-known-hosts command to commcare-cloud

---

environments/icds-new/app-processes.yml

Reduce reminder_queue celery workers in ICDS

---

commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py

fix AfterReboot + --limit

---

environments/production/app-processes.yml

Add 1 reminder_queue worker to production

---

commcare-cloud/commcare_cloud/commcare_cloud.py

Not sure how I messed this up even after testing: https://github.com/dimagi/commcare-cloud/pull/1536

fix typo in run_on_control_instead

---

commcare-cloud/commcare_cloud/environment/schemas/postgresql.py

Follow up to discussion comment: https://github.com/dimagi/commcare-cloud/pull/1570#discussion_r179688064

statically check shard config

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

- Use `-o UserKnownHostsFile=<environment_known_hosts>` with ssh commands.
- Use `-t` with `django-manage shell` and `django-manage dbshell`
@dannyroberts

SSH options

---

environments/production/inventory.ini

Added hqdb3
Corrected the commented line of pgsyncstandby (In case if we will add it )

Added hqdb3 in inventory

---

ansible/roles/formplayer/meta/main.yml
ansible/roles/touchforms/meta/main.yml

From https://github.com/dimagi/commcare-cloud/pull/1577#issuecomment-380495404

make formplayer and touchforms depend on supervisor role

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

for running from a releases (i.e. not current/)

add --release option to django-manage

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

so you know how old it is and who to ask about it

name tmux tabs like "droberts (2018-04-13)"

---

environments/icds-new/inventory.ini

@snopoke can you suggest if anything else also needs to be added for new couch nodes.

Added couch nodes

---

environments/icds-new/postgresql.yml

send more read load to ucrstandby

---

environments/production/app-processes.yml
environments/softlayer/app-processes.yml

I added this to the repeat records queue as this also uses gevent, and does similar "forwarding stuff"

Add sumologic_logs_queue to prod and softayer

---

ansible/deploy_commcarehq.yml
ansible/roles/newrelic/tasks/main.yml
ansible/roles/newrelic/templates/newrelic.ini.j2
commcare-cloud/commcare_cloud/environment/schemas/app_processes.py
environmental-defaults/app-processes.yml
environments/development/inventory.ini
environments/production/app-processes.yml
fab/fab/operations/supervisor.py
fab/fab/services/templates/supervisor_django.conf

Add back NewRelic Python agent on prod for apdex reporting
Originally removed here: https://github.com/dimagi/commcare-hq-deploy/pull/470

newrelic again

---

fab/fab/utils.py

Reverts dimagi/commcare-cloud#1625
@esoergel

Revert "handling particular github exception"

---

commcare-cloud/commcare_cloud/cli_utils.py
commcare-cloud/commcare_cloud/commands/ansible/downtime.py
commcare-cloud/commcare_cloud/commcare_cloud.py
commcare-cloud/commcare_cloud/environment/paths.py
commcare-cloud/commcare_cloud/environment/schemas/meta.py
commcare-cloud/setup.py
environments/enikshay/meta.yml
environments/icds-new/meta.yml
environments/pna/meta.yml
environments/production/meta.yml
environments/softlayer/meta.yml
environments/swiss/meta.yml

Every time I have to do maintenance I want this.
buddy @gbova

command to manage downtime

---

ansible/roles/commcarehq/templates/localsettings.py.j2
commcare-cloud/commcare_cloud/environment/schemas/postgresql.py
docs/env/postgresql_yml.md
environments/icds-new/postgresql.yml

@snopoke 
As discussed in https://github.com/dimagi/commcare-hq/pull/20201 this adds load balancing for users and accounting since they get hit a lot, but don't necessarily need to be up to date. I can continue to add more as I look through the apps.

standby reads for users and accounting

---

environments/icds-new/public.yml

https://github.com/dimagi/commcare-hq/pull/20311/

Add dashboard growth monitoring form UCR

---

docs/index.md
setup.py
src/commcare_cloud/ansible/README.md
src/commcare_cloud/manage_commcare_cloud.py
src/commcare_cloud/manage_commcare_cloud/__init__.py
src/commcare_cloud/manage_commcare_cloud/configure.py
src/commcare_cloud/manage_commcare_cloud/get_path.py
src/commcare_cloud/manage_commcare_cloud/install.py
src/commcare_cloud/manage_commcare_cloud/manage_commcare_cloud.py

cleanup after https://github.com/dimagi/commcare-cloud/pull/1639. Can review commit by commit.

Cleanup after pip install PR

---

src/commcare_cloud/fab/const.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/release.py

Reverts dimagi/commcare-cloud#1651

Revert "adding manage role to deploy just to webworkers[0]"

---

docs/commcare-cloud/commands/index.md

followup to https://github.com/dimagi/commcare-cloud/pull/1657#issuecomment-384675617

Add table of contents to commands doc

---

setup.py
src/commcare_cloud/environment/schemas/app_processes.py

i'll bump this to a non-alpha release when it's ready.

bring CeleryOptions into use and fix

---

environments/softlayer/app-processes.yml
environments/softlayer/inventory.ini

This PR removes the following server from the inventory. 
celery1
django1
pillow3

Removed 1 celery , django and pillowtop servers

---

environments/icds-new/postgresql.yml

Reverts dimagi/commcare-cloud#1696

Revert "add load to pgucrstandby1"

---

environments/icds-new/postgresql.yml

Reverts dimagi/commcare-cloud#1697

Revert "Revert "add load to pgucrstandby1""

---

src/commcare_cloud/fab/fabfile.py

@jmtroth0 @dannyroberts @orangejenny

Fix means of calling update_code

---

src/commcare_cloud/ansible/deploy_control.yml
src/commcare_cloud/ansible/roles/ansible-control/defaults/main.yml
src/commcare_cloud/ansible/roles/ansible-control/tasks/main.yml

make it install commcare-cloud environment for each dev user

fix and extend deploy_control.yml

---

environments/pna/app-processes.yml

adding celery main queue to pna

---

environments/softlayer/public.yml
src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

Want to do it with Postgres downsizing.

Added Elasticsearch Vars

---

tests/test_environments.py

remove redundant tests

---

src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/fab.py

while there are still supervisor confs that get updated in fab

make update-supervisor-confs also update via fab

---

commcare-cloud-bootstrap/bootstrap.sh
docs/commcare-cloud/commands/index.md
src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/helpers.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/commands/shared_args.py
src/commcare_cloud/commcare_cloud.py

The test wasn't running, I think because it was merged. Reverting so the tests can run.

Revert "Changing the way auth is done"

---

environments/softlayer/app-processes.yml

I have halved the concurrency for SoftLayer.  But looking for some suggestions on what would be a good number.

Reduce concurrency of few workers.

---

environments/production/app-processes.yml

Should help with https://manage.dimagi.com/default.asp?276610#1497043

Reduce export_download_queue concurrency to 6

---

src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

set elasticsearch minimum_master_nodes to at most 2

---

environments/production/inventory.ini

remove production old_elasticsearch

---

src/commcare_cloud/fab/fabfile.py

https://github.com/dimagi/commcare-cloud/pull/1755#discussion_r190305399

cod_branch -> code_branch

---

git-hooks/pre-commit.sh

To fix this issue:
https://github.com/dimagi/commcare-cloud/issues/1633

Git-hooks: do not match on paths starting with tests or containing development

---

.gitignore

Adding pickle files to gitignore.

Gitignore pickle files

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

useful for monoliths without having to futz with the configuration

ref pg host as 127.0.0.1 if on same machine

---

src/commcare_cloud/commands/ansible/service.py

`supervisorctl status all` results in a command line error

fix service commcare status

---

setup.py

Fix until https://github.com/dimagi/commcare-cloud/pull/1792 get's in

pin couchdb-cluster-admin version

---

environments/production/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_django.conf.j2
src/commcare_cloud/environment/schemas/app_processes.py
src/commcare_cloud/environmental-defaults/app-processes.yml

Commented on this https://github.com/dimagi/commcare-cloud/pull/1779#discussion_r190741451 but totally dropped it

newrelic_django_prefix -> django_command_prefix

---

environments/swiss/public.yml
src/commcare_cloud/ansible/roles/backups/defaults/main.yml
src/commcare_cloud/ansible/roles/couchdb/defaults/main.yml
src/commcare_cloud/ansible/roles/couchdb2/defaults/main.yml
src/commcare_cloud/ansible/roles/pg_backup/defaults/main.yml

It will keep 
2 older and 1 current backup = 3 backups.

Keep 2 older backups

---

commcare-cloud-bootstrap/environment/public.yml
environments/_users/dimagi-qa.yml
environments/_users/dimagi.yml
environments/development/public.yml

Remove javier from users

---

docs/howto/move-partitioned-database.md

rename partition[12] to commcare_p[12]

---

environments/softlayer/inventory.ini

I think this was removed a couple weeks ago?

Remove db0 from softlayer

---

environments/icds-new/app-processes.yml
environments/icds-new/inventory.ini

Reverts dimagi/commcare-cloud#1809
Breaking deploy will follow up

Revert "Added web10 and web11"

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

use public IPs in ALLOWED_HOSTS

---

docs/basics/troubleshooting.md
docs/index.md

As questions come up and we help people troubleshoot, might be worth adding our suggestions here so that we end up with a bit more of a knowledge bank we can point people to.

troubleshooting docs

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

add test project

---

src/commcare_cloud/ansible/roles/common/tasks/main.yml

Fix hostname check

---

environments/pna/proxy.yml
environments/pna/public.yml
src/commcare_cloud/ansible/letsencrypt_cert.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml
src/commcare_cloud/ansible/roles/nginx/templates/site.j2
src/commcare_cloud/environment/schemas/proxy.py

Certificate in PNA is on automated renewal.

PNA certbot automation

---

src/commcare_cloud/fab/fabfile.py

Had to hotfix the deploy code before I could hotfix the code 
I think this was broken since https://github.com/dimagi/commcare-cloud/pull/1661

Fix hotfix deploy

---

environments/icds-new/app-processes.yml

Found memory for these. already added the kafka partitions necessary

Add 8 form processors

---

docs/commcare-cloud/commands/index.md
environments/development/inventory.ini
environments/echis/inventory.ini
environments/staging/inventory.ini
environments/swiss/inventory.ini
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

can merge once #1838 is out and the code has been deployed to prod and softlayer

use django manage

---

.gitignore

which gets generated when nosetests is run

Add tests/.../migration_build_env1_plan to .gitignore

---

src/commcare_cloud/ansible/deploy_proxy.yml

Followup to post-merge discussion on https://github.com/dimagi/commcare-cloud/pull/1859

Fix new riakcs site_present condition

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

update icds app download limits

---

src/commcare_cloud/commands/ansible/service.py

@pr33thi and I spent a while debugging couchdb being down before realizing what the issue was; this would have made potentially made it quicker

Add couchdb2 proxy to couchdb2 service

---

environments/echis/fab-settings.yml
environments/icds-new/public.yml
src/commcare_cloud/ansible/roles/commcarehq/defaults/main.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/schemas/fab_settings.py
src/commcare_cloud/environmental-defaults/fab-settings.yml

Tweak commcarehq repo config

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

fixes: https://github.com/dimagi/commcare-cloud/pull/1877#discussion_r198736911

Fix recently broken logic for file-based email

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

And add cache locking.
Docs for cache locking: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_lock

remove rate limiting from app downloads 

---

commcare-cloud-bootstrap/environment/public.yml
src/commcare_cloud/ansible/deploy_proxy.yml
src/commcare_cloud/ansible/roles/nginx/handlers/main.yml
src/commcare_cloud/ansible/roles/nginx/tasks/dropsite.yml
src/commcare_cloud/ansible/roles/nginx/tasks/restart.yml
src/commcare_cloud/ansible/roles/nginx/tasks/site.yml

- Restart nginx after adding / dropping a site
- Delete the unused nginx-related tasks

Restart nginx after adding / dropping a site

---

docs/howto/enable-https.md

I'd been meaning to toss up these docs, even if they're incomplete and even if (or maybe especially because) not fond of the process and hope to improve it.

Add docs for enabling https with letsencrypt

---

environments/icds-new/proxy.yml
environments/softlayer/proxy.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml
src/commcare_cloud/environment/schemas/proxy.py

Link to certificate generated by certbot.

adding softlayer

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/webworkers.yml

add back newrelic env vars

---

environments/echis/fab-settings.yml
src/commcare_cloud/fab/fabfile.py

Disable Email for eCHIS for fab deploy

---

environments/production/inventory.ini

adding swap to rabbit machine

---

environments/production/app-processes.yml

based on https://github.com/dimagi/commcare-hq/pull/21143/

Remove world vision pillows

---

environments/staging/inventory.ini

We rebuilt the machine so the IP changed.

Update aws staging control host

---

src/commcare_cloud/ansible/deploy_commcarehq.yml

My recent PR removed this in a merge commit

Add pillowtop group

---

docs/changelog/index.md
docs/index.md

I'll write up a quick github issue to automate this, but I wanted to PR this as a sort of example format to work off.

Add changelog index

---

requirements.txt
setup.py

added here https://github.com/dimagi/commcare-cloud/commit/68aca9bd04ee4fc28774c449e4d784b19a25613e#r29726053
for reasons not obvious or documented and that I no longer remember

Remove pycrypto dependency

---

docs/changelog/0002-supervisor-service-definitions.md

Tried to give roughly the same amount of info as https://github.com/dimagi/commcare-cloud/pull/1907

Add documentation for #1791

---

src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/airflow/templates/airflow.cfg.j2
src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
src/commcare_cloud/ansible/roles/formplayer/vars/main.yml

rather than through an intermediate ansible variable
Followup to https://github.com/dimagi/commcare-cloud/pull/1802 and https://github.com/dimagi/commcare-cloud/pull/1902

Reference database hosts directly from postgresql_dbs

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Further normalize ENVIRONMENT_HOSTS

---

src/commcare_cloud/ansible/letsencrypt_cert.yml

The site template already includes this location: https://github.com/dimagi/commcare-cloud/blob/bd00274a8faebfa912d210282b81dcd266125a14/src/commcare_cloud/ansible/roles/nginx/templates/site.j2#L106

don't create duplicate locations

---

environments/production/app-processes.yml

@mkangia @NitigyaS 
To deal with the saved export woes on prod

add more saved export workers
