- environments/production/terraform.yml
Because of having shifted around some instance class types in the last few months, we're currently slightly underutilizing the Reserved Instances of the t3 and m5 instance types.
production
> Use all current RIs

- environments/production/inventory.ini
- environments/production/inventory.ini.j2
It's not ready yet. This caused issues after a formplayer deploy because formplayer deploy now updates the formplayer config as well, and doing that made it point to the new redis node which apparently wasn't properly set up yet, as it resulted in these errors: https://sentry.io/organizations/dimagi/issues/619342116/?environment=production&project=136860&query=is%3Aunresolved.
production
redis
> Comment out redis0 in inventory

- src/commcare_cloud/ansible/roles/backups/tasks/set_up_check_s3_backups.yml
It was sending e.g. "/opt/data/backups/couchdb2/s3_backup_status.txt"
as the body, instead of sending the contents of that file as intended.
I rolled this out to swiss a few weeks ago but then apparently forgot to PR it.
mostly just swiss
> Fix body of backup check email

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
This was a takeaway from the Retro entitled
> Retrospectives: Formplayer error "CLUSTERDOWN Hash slot not served" for ~20 minutes Oct 17, 2019
all
> Do not update config files on formplayer deploy

- environments/production/terraform.yml
The effect of what the todo is suggesting (once implemented) is to cut pillowtop memory in half, which it can handle: https://app.datadoghq.com/dashboard/nbz-bie-nip/host-groups?abstraction_level=1&aggregate_up=false&display_timeline=false&from_ts=1569251988093&is_auto=false&live=true&page=0&per_page=30&tile_size=m&to_ts=1571843988093&tpl_var_environment=production&tpl_var_host_group=pillowtop&use_date_happened=true, as well as keep the number of vCPUs the same but with better CPU performance.
production (but no change right now)
> Add todo switch away from r5a in Q1

- environments/icds-cas/app-processes.yml
Increase UCR queue blockage threshold.
ICDS
Celery
Since we've been stopping and starting the queue quite a lot I changed this to 1 day to reduce the noise of alerts since it fails the `serverup` check.
> increase ucr_indicator_queue threshold

- control/init.sh
I must have never tested this experience well at the time that I wrote it (https://github.com/dimagi/commcare-cloud/pull/2832), and assumed it just wouldn't happen because of the cleanup script I ran. (Apparently whatever I ran didn't fix it for everyone.)
It now prints exactly what you have to do to fix, and returns out of the script rather than producing a bunch of irrelevant output that obscures this message.
> Make resolution of bad python3 env smoother

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
There was a point early in the migration to Ubuntu bionic that we were suffixing group names in `terraform.yml` with `:bionic` to get it to use the bionic image, which we quickly replaced with setting `os: bionic` on the server in `terraform.yml`. This removes support for the old convention
None
> Remove support for old *:bionic naming convention

- src/commcare_cloud/ansible/roles/setup_auth_keys.yml
* Fixed local temp pub key deletion during auth setup of postgres
* ALL
> Fixed local temp pub key deletion during auth setup of postgres

- environments/staging/aws-resources.yml
- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
- environments/staging/postgresql.yml
- environments/staging/terraform.yml
Similar to https://github.com/dimagi/commcare-cloud/pull/3357 @snopoke flagged that airflow1-staging was very likely not needed anymore.
staging
> Remove airflow1-staging

- environments/production/terraform.yml
Increase size of django_manage VM on production.
production
django_manage
This is for the Couch to SQL migration, which has been running out of memory for the case diff process lately. It can be reverted once that is no longer an issue.
Commands (already run)
```paste below
$ cchq production terraform init
$ cchq production terraform plan -target module.server__djangomanage1-production.aws_instance.server
$ cchq production terraform apply -target module.server__djangomanage1-production.aws_instance.server
$ cchq production after-reboot django_manage --branch=dm/bigger-django-manage
```
> Add more RAM to django_manage VM

- environments/icds-cas/postgresql.yml
- environments/india/postgresql.yml
These databases are no longer in use by ICDS. The data in the DBs has been migrated to CitusDB.
* india
* icds-cas
> remove references to no-longer used ICDS DBs

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/service.py
Yesterday I found that `cchq icds postgresql stop` does not also stop the postgres instances for citus and we don't really have a way to do that now so I needed to run `monit stop` on the master node manually. 
I'm not opposed other methods to solve this (such as adding the citus servers to the postgresql group in the inventory), but this was the quickest solution I could think of that would not require more investigation of the difference between our current groups.
icds
citus
> Add citusdb service

- environments/icds-cas/inventory/citusdb.csv
@rohit-dimagi I saw that the archive_command is `/bin/true` on all citus workers. Is this expected? I couldn't find a PR that included this change
icds
citusdb
A deploy currently looks like this:
```
--- before: /etc/postgresql/11/main/postgresql.conf
+++ after: /home/jemord/.ansible/tmp/ansible-local-581vMquJM/tmpHuNyIp/postgresql.conf.j2
@@ -35,7 +35,7 @@
archive_mode = on
-archive_command = '/bin/true'
+archive_command = 'cp %p /opt/data/postgresql/wal_archive/%f'
archive_timeout = 300
wal_level = hot_standby
```
> Set archive_command to /bin/true for citusdb

- environments/icds-cas/public.yml
@ctsims changed this to 21 days temporarily during firefighting. (personally I think we should go even lower, but can open that for discussion)
I believe that this can be done without downtime by applying to one kafka node at a time since we have replication
icds
kafka
> Change kafka log retention to 21 days

- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2
Removes management and debug options that were attached to formplayer while we debugged memory leaks after the recent library updates, as well as VisualVM Debugging commands that I believe Will added which shouldn't have been on there for security reasons.
Shouldn't meaningfully affect anything other than a slight reduction in resources and locking down access to the process.
All
Formplayer
> Remove management / debugging options from Formplayer 

- src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
Making localsettings.py user-readable only
> Making localsettings.py user-readable only

- environments/icds-cas/fab-settings.yml
- environments/india/fab-settings.yml
- environments/production/fab-settings.yml
- environments/staging/fab-settings.yml
- environments/swiss/fab-settings.yml
- src/commcare_cloud/environment/schemas/fab_settings.py
- src/commcare_cloud/fab/utils.py
Currently, we attempt to tag the commits for all deploys.  This requires credentials with write access to the commcare-hq repo.  If the user hasn't copied over fab/config.yml, they'll be nudged to do so and prompted for a username and password, though they can leave this blank.  To silence the prompt, the user needs to copy that config and set their API key to use auth, or leave it as `None` to not tag their deploys.  In this latter case, they still get a warning that release tags are not being created.
None of this makes sense for non-Dimagi users, since they'll never be able to create tags.  This PR is my proposal for addressing that.  I'm introducing a flag to enable tagging deploy commits for specific environments - those controlled by Dimagi.  For these environments, I've attempted …
> Only tag deploy commits for Dimagi-controlled environments

- src/commcare_cloud/ansible/roles/haproxy/templates/service.j2
This template was previously attempting to lookup the machine's IP dynamically.  This led to an issue where a the resulting IP address was one which was inaccessible from other machines.
This commit switches it to use the address defined in the inventory, as is done in nginx:
https://github.com/dimagi/commcare-cloud/blob/b4a72c49ba680f6f00ce1fe098217f8967be4f55/src/commcare_cloud/ansible/roles/nginx/templates/site.j2#L15-L16
Shout out to @dannyroberts for assistance debugging and finding a solution.
@snopoke looks like you were the last person to do work on these files, do you know of a reason not to do this change?
haproxy
> Use correct IP address for haproxy config

- scripts/es_snapshot.py
Write new command class for ES Snapshot management script that downloads all files for a snapshot.
Usage:
```shell
$ export ST_KEY=...
$ export ST_CONTAINER=...
$ export ST_USER=...
$ export ST_AUTH=...
$ python3 es.py info                    
Account info:                           
Objects:    118626                   
Capacity:   46.0% (10.7TB / 23.1TB) 
Live snapshot versions:
....
icds_es_snapshot_2019_9_27 [SUCCESS]
$ mkdir /opt/data/icds_es_snapshot_2019_11_27
$ python3 es.py verify icds_es_snapshot_2019_11_27
Snapshot version icds_es_snapshot_2019_11_27:
File count: 8644
Total size: 5.4TB
State:      VALID
$ python3 es.py download icds_es_snapshot_2019_11_27 /opt/data/icds_es_snapshot_2019_11_27 -vv
2019-11-28 14:15:00,167 INFO     Found 54 live snapshots …
```
> update es snapshot script to support downloading to disk

- src/commcare_cloud/commands/ansible/ops_tool.py
A partner reported this error when running list-postgresql-dbs:
```
TypeError: to_generated_variables() takes exactly 2 arguments (1 given).
```
Looks like the postgresql_config version of `to_generated_variables` requires that `environment` be passed in as of https://github.com/dimagi/commcare-cloud/pull/2863
list-postgresql-dbs
> Fix list-postgresql-dbs

- src/commcare_cloud/ansible/deploy_postgres.yml
This was causing pgbouncer to not be installed/configured on the new standby nodes
icds
> Fix pgbouncer host definition

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Think these have been unnecessary since MVP was removed.
Just happened to see them in a slack chat.
> remove unused variables from localsettings

- src/commcare_cloud/fab/fabfile.py
When I moved deploy into its own commcare-cloud command, I neglected
to retain the behavior of the many other fab calls we use regularly
but less frequently (setup_limited_release, etc.), and they would fail
unless you added e.g. `--set code_branch=master` to them.
This brings back earlier behavior of choosing the default branch
specified in fab_settings.yml
> Fix direct fab calls without `--set code_branch=...`

- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
Currently when a user logs out and logs back in, they are routed
randomly to one of the formplayer machines. This change gives the caller
the freedom to route based on whatever they like, and we will use that
in commcare-hq to route based on user_id instead of django sessionid.
The caller can now route by setting either the X-FORMPLAYER-SESSION
header or the formplayer_session cookie. A blemish of this
implementation is that if they sometimes but not always send _both_ the
header and the cookie, that will break sticky routing.
Note that this is not safe to roll out until https://github.com/dimagi/commcare-hq/pull/26127 is rolled out. If that happened the behavior would either be to break sticky routing entirely or to always route to the same machine, I'm not sure.
production for sure, but …
> Route by new formplayer_session cookie instead of sessionid cookie

- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_pillowtop.conf.j2
Add env var to pillowtop processes to allow them to read from plproxy shard standbys if they are configured and available.
Not making this optional since it will only have effect if the proxy standbys are configured in localsettings.
ALL (though only practically ICDS)
> set pillows to read from standbys

- src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.ini.j2
This would ignore an options parameter in pgbouncer. The main point of this would be to be able to use https://gitlab.com/postgres-ai/postgres-checkup. I tested this on the old warehouse db that is not used anymore and this was a blocker on the postgres stats. (postgres-checkup also allows you to use ssh to get general system information).
An example full report can be found here https://gitlab.com/postgres-ai/postgres-checkup-tests/blob/master/1.3.0/md_reports/1_2019_11_05T11_03_58_+0000/0_Full_report.md This appears to be much more comprehensive than pghero and there's a roadmap of adding more features and checks.
They also have some other checkup services mentioned on the company's site https://postgres.ai/ (the slackbot query optimizer looks really cool, but probably not worth setting …
> Ignore options startup parameter in pgbouncer

- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- environments/swiss/public.yml
I'm trying to see if I can differentiate environments based on modifiers to the FROM address in Amazon SNS bounce notifications. If amazon ends up removing the `+` modifiers, then I think the next action is to have different from addresses based on environment.
prod, india, swiss, staging
`localsettings` `DEFAULT_FROM_EMAIL`
> [Amazon SES] add modifiers to commcarehq-noreply emails based on environment

- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- environments/swiss/public.yml
It looks like Amazon SES does, in fact, strip the `+` modifiers from email addresses. I verified these new emails with SES and now have SNS notifications forwarding to `commcarehq-bounces@dimagi.com`. From there I should be able to process the more reliably-formatted SNS notifications *per environment* with the raw emails as a fallback.
production, india, swiss, staging
`localsettings` `DEFAULT_FROM_EMAIL`
> [Amazon SES] remove modifiers to commcarehq-noreply and use separate emails

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/ops_tool.py
- src/commcare_cloud/commcare_cloud.py
To make it easier to find out where a Kafka topic is assigned.
NA
> utility command to get pillow topic assignments

- environments/production/terraform.yml
This updates the postgres version to 9.6.15 (from 9.6.6), which I've already rolled out, switches the machines to the t3 class (from t2) and downsizes all machines. They've always been underutilized but since our RDS Reserved Instance 1-year commitment ran out a few days ago, we can actually do something about it. The postgres upgrade was necessary in order to upgrade to t3, which is a slightly better deal than t2.
production
> Update production RDS

- src/commcare_cloud/ansible/letsencrypt_cert.yml
https://github.com/ansible/ansible/issues/25893
When VAR is a string:
when: VAR | bool  ->  False
when: not VAR  ->  False
Only "yes", "on", "true", "1", and 1 result in True when [cooerced to boolean](https://github.com/ansible/ansible/blob/0fa556f75183238633396c7ab59bddd23c9a1931/lib/ansible/plugins/filter/core.py#L91)
Any with a `NO_WWW_SITE_HOST` specified
certbot
This pattern here seems to function as I'd like, and I see it used elsewhere.  When `NO_WWW_SITE_HOST` is defined (prod), I see:
```
task [run certbot command when there is a www host] ******
skipping: [10.202.20.47] => {"changed": false, "msg": "skipped, running in check mode"}
task [run certbot command when there is no www host] ******
skipping: [10.202.20.47] => {"changed": false, "skip_reason": …
```
> Coercing to a bool doesn't work like you think

- environments/production/public.yml
One of the machines (couch12) recently got out of its normal good compaction cycle and grew without limit until the disk filled up. I'm not 100% sure it's because there wasn't enough compaction time to keep up versus something more incident oriented (like the process responsible for scheduling compaction getting killed or something). So I'm not totally sure this change is necessary, but it's something I rolled out while looking at this, and I don't think it'll hurt.
production
> Dedicate a longer window to couch compaction on production

- environments/production/public.yml
I'm getting the sense that the `USER_REPORTING_METADATA_BATCH_ENABLED = False` is being maintained as an afterthought at this point, since ICDS is the only division actively working changes to user reporting metadata and they're on `USER_REPORTING_METADATA_BATCH_ENABLED = False`, and recent changes ICDS has made has caused a high volume of errors on production (and likely affected the freshness/accuracy of the reports). I think if that's the case, then our best bet is to get production on the new system and to remove the flag and keep only the new implementation.
production
> Use USER_REPORTING_METADATA_BATCH_ENABLED on production

- commcare-cloud-bootstrap/environment/app-processes.yml.j2
- environments/64-test/app-processes.yml
- environments/development/app-processes.yml
- environments/production/app-processes.yml
- src/commcare_cloud/environment/schemas/app_processes.py
These were deleted a few months ago from commcare-hq, just never got around to doing the cleanup.
For other environments that have these pillows in their list (or others we deprecate in the future), they'll get a warning like so:
probably just production, which is affected by not getting harmless warning-level errors on every deploy/service restart.
> Filter out deprecated pillows

- environments/icds-cas/elasticsearch.yml
New SMS index being created without `_all` field: https://github.com/dimagi/commcare-hq/pull/26515
Create index with 10 shards instead of 5.
ICDS
> increase shard count for new smslogs index

- environments/india/public.yml
- src/commcare_cloud/ansible/roles/airflow/defaults/main.yml
- src/commcare_cloud/ansible/roles/airflow/templates/airflow.cfg.j2
current parallelism variables were too high for the size of the india airflow machine. This allows the agg to run there without swamping the machine.
> more appropriate airflow config for india

- src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
allow-origin "null" means allowing requests from file:// urls.
So if you run Elasticsearch Head locally from file://.../index.html
then this will re-enable it.
I haven't fully validated this, but my guess is that the upgrade to ES 2
gave cors a stricter default setting.
all
Elasticsearch
> Fix ES CORS to enable Elasticsearch Head

- environments/icds-cas/inventory/postgresql.csv
As part of postgresql tuning , adjusting the "random_page_cost" value  to 1.1
pg_shards
pg_main
plproxy
pg_synclog
changing random_page_cost value from 4.0 to 1.1
ICDS
Merge will be done over a downtime window.
pg_shards
pg_main
plproxy
pg_synclog
> changed random_page_cost value to 1.1

- src/commcare_cloud/commands/ansible/helpers.py
ansible 2.9 uses argparse which requires special treatement of ssh-common-args
See https://github.com/ansible/ansible/issues/64897
> fix ssh-common-args for ansible 2.9

- src/commcare_cloud/ansible/roles/pg_repack/tasks/main.yml
Run pg_repack more aggressively (at 5% dead tuple ration instead of 10%)
ICDS
PostgreSQL, pg_repack
Already rolled out to ICDS
> trigger pg_repack at 5% dead tuples

- environments/icds-cas/public.yml
- environments/india/public.yml
- environments/phi-cas/public.yml
- environments/pna/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- environments/swiss/public.yml
- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Turns out there were still a few @dimagi.com emails hardcoded in localsettings.  This PR defaults a those to example.com, then explicitly sets the values back to the dimagi.com addresses for Dimagi managed envs.  This means that there shouldn't be any diff next time localsettings is deployed on those envs (verified on prod and staging).
None
localsettings
> Default a few more emails to example.com

- src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml
to prevent errors like
```
[10.203.20.59] out: unix:///tmp/supervisor.sock no such file
[10.203.20.59] out:
[10.203.20.59] sudo: supervisorctl reread
[10.203.20.59] out: error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228
```
and to generally leave app process machines in good shape after reboot.
> Start supervisord in after-reboot

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/production/terraform.yml
Reopening https://github.com/dimagi/commcare-cloud/pull/3606 as this PR
They're no longer serving any connections. Followup to https://github.com/dimagi/commcare-cloud/pull/3593
production
> Remove pgproxy2- and pgbouncer1-production

- src/commcare_cloud/manage_commcare_cloud/monitors/saas_data_disk.yml
It looks like ICDS has its own /opt/data monitor so I'm just making an equivalent one for SaaS environments. This will send us a slack alert whenever an /opt/data disk is 80% or fuller
production, india, staging, swiss
> Add /opt/data disk monitor for SaaS envs

- src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml
Data analysis of nginx logs show a significant portion of requests
being rate limited at 2/s. Bumping to 6/s allows 95% of users
to sync.
ICDS
> adjust per ip limit

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/server/main.tf
- src/commcare_cloud/terraform/modules/server/variables.tf
This will let us eventually use native AWS EBS encryption
instead of ecryptfs for our large data volumes.
Down the road this will enable zero-intervention startup, which is a prerequisite for any kind of automatic scale up and down, whether it's stopping a couple webworkers during trough periods, or actual autoscaling. It also may reduce the cost of our couch snapshot backups.
I spiked this and it appears to work, so I wanted to just get it in the the caveat so I could come back to it when I have time
> Add ecrypted option on block_device in terraform.yml

- environments/production/app-processes.yml
I increased the number of partitions in form, form-sql, case, case-sql topics to 32 each, and this PR increases the number of processes to 8 each for form-pillow and case-pillow. (Needed to increase partitions to be able to increase processes, but I increased more than I needed to to be able to increase processes again in the future.)
production
> Increase processors for form & case pillows on production

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Turns out the extra ':' is necessary
> fix url for redis auth

- environments/production/app-processes.yml
- environments/production/terraform.yml
How much money? About an extra $330/mo (before applying any savings). For the extra throughput it affords us (and it really did help), it seems totally worth it. We still have work to do beyond throwing money at it, but I'm increasingly convinced that we won't be able to meet ambitious lag time goals without this change (at least not in a reasonable amount of time).
production
> Increase resources dedicated to case-pillow

- environments/production/app-processes.yml
Yesterday I rolled this out with num_processes: 2, and today I scaled it back to this.
In steady state we have very few of these, but occasionally we get a huge number of task,
and when we do, high gevent concurrency is enough to really speed up our processing of the backlog
production
> Increase concurrency for reminder_case_update_queue on production

- environments/production/app-processes.yml
I had upped case-pillow to 64 while trying to figure out
why the processing pattern was so weird. That appears to be fixed in
https://github.com/dimagi/commcare-hq/pull/26842, so I think it makes
sense to give it 16 processors which is still 4x what it has until recently been.
production
> Give case-pillow and form-pillow both 16 processors

- src/commcare_cloud/ansible/group_vars/citusdb_worker.yml
- src/commcare_cloud/ansible/roles/postgresql_base/templates/postgresql.conf.j2
The child health monthly step of the aggregation seems to have very different performance characteristics based on whether or not the postgres query planner chooses to partially materialize the query. This penalizes materialization in the planner costing algorithm, although it will still use it if required for correctness. I suspect the best option is to try to improve postgres stats so it will just choose the correct plan, but given turnover in these tables (we delete and recreate a substantial part of it in each agg), that might be hard to do.
ICDS
India
Citus
> disable materializing for citus workers

- environments/icds-cas/public.yml
We normally only queue indicators at night but given the lower form submissions as AWCs, we will run them all day to help clear the backlog.
ICDS
> queue async indicators all day

- environments/64-test/public.yml
- environments/icds-cas/public.yml
- environments/icds-staging/public.yml
- environments/india/public.yml
- environments/phi-cas/public.yml
- environments/pna/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- environments/swiss/public.yml
- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
This removes the email address constants that were deprecated in https://github.com/dimagi/commcare-hq/pull/26927 and https://github.com/dimagi/commcare-hq/pull/25919/
It also updates the support email address for ICDS environments.
@dannyroberts  is there a standard way to communicate dependencies on HQ PRs, or a typical length of time to wait before merging the dependent PR? This shouldn't be merged until https://github.com/dimagi/commcare-hq/pull/26927 is merged.
All
> Remove unused support and exchange emails; update ICDS support email

- environments/production/public.yml
Without this change https://github.com/dimagi/commcare-hq/pull/26842, which was reverted,
the "shortest backlog" partitioner exacerbates lag issues by preventing larger queues
from getting any new messages, whereas the new maessages are what trigger it to keep processing.
Once the bug in that PR is resolved, we can reintroduce this.
production
> Revert (temporarily?) to default partitioner on production

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
This gives a way to redirect output to a file on the remote machine, which comes in handy for workflows where the output of one command is the input of another, or simply for saving the output more durably especially in conjunction with `--tmux`
> Add --tee arg to django-manage command

- environments/production/terraform.yml
The original motivation for the change to m5.8xlarge was to consolidate
instance classes back when we were primarily using EC2 RIs. Now that we are
using savings plans instead, this is a moot point, and c5.9xlarge is a slightly
better fit
production
> Switch couch14-production back to c5.9xlarge

- src/commcare_cloud/commands/inventory_lookup/getinventory.py
Changes the `cchq <env> ssh <host>` command to respect the `COMMCARE_CLOUD_DEFAULT_USER` env variable that terraform commands and deploy use. It has the same meaning (your name of your ubuntu user on the host), and not using it after a user went through the trouble of setting it is surprising behavior. If the env variable is not set, it will still use <host> instead of explicit <user>@<host> to let whatever is in .ssh/config take control.
None specifically
> Respect COMMCARE_CLOUD_DEFAULT_USER in ssh commands

- requirements.txt
- setup.py
Solved issue on my new mac
> ```
> # 2.8 solves issue on MacOS Catalina
> # https://github.com/pypa/pip/issues/7254
> # but 2.9 fails to compile
> ```
> Update cryptography to 2.8

- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
This (probably among other things) preserves ipython history when using django-manage shell.
Small thing I noticed that has bothered me before, where I do some discovery in the shell and then log out by mistake before copying it somewhere so I can turn it into a useful script or something, and then I have to log back in and recreated what I'd done earlier.
all/none specifically
> Have django-manage use login shell

- src/commcare_cloud/ansible/roles/elasticsearch/templates/monit.elasticsearch.j2
Took me hours to figure this out. I was testing something out on staging ES, and as a side effect deployed monit. Apparently it was checking for a file that didn't exist and just restarting ES in a loop, because fixing the path to the correct path for the log file fixed it.
Fixed would-be issue in all environments but ICDS
> Fix ES monit

- src/commcare_cloud/fab/operations/release.py
Seeing errors like this on deploy across environments. Likely related to the upgrade to git 2.26.1.
```
[10.203.10.117] out: fatal: git upload-pack: not our ref 59cbfc3f2b9469367c4946b32075ea6e49dc4ff7
[10.203.10.117] out: fatal: remote error: upload-pack: not our ref 59cbfc3f2b9469367c4946b32075ea6e49dc4ff7
[10.203.10.117] out: Errors during submodule fetch:
[10.203.10.117] out:    corehq/apps/hqmedia/static/hqmedia/MediaUploader
```
https://docs.google.com/document/d/161EpZDZYAoiag4Ya2PPYlQ1jMYVYUv4T25qet2kesB4/edit#heading=h.j3m99ov3z102
all
> Refetch tags on first failure

- environments/production/app-processes.yml
Bumping up max concurrency on the queues most often facing delays on production. They're both very peaky in that they start once a day at the same time every day, so if just bumping it up doesn't help much and it becomes a user-facing issue, that might be the next thing to look at, but I expect a couple rounds of this kind of thing will be all that's needed for now
production
> Increase prod queue processors

- src/commcare_cloud/commcare_cloud.py
ICDS now has two control machines, which interferes with usage of the `--control` flag.
None
> Defaulted --control to use first control machine

- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_workers.conf.j2
This is the documented default but I recently saw
many more than 4 * concurrency tasks in a workers Reserved queue.
If the docs are correct and we're not overriding this in our code (or library code), which it appears we're not, then this change will have no effect, and then it's a mystery why I was seeing so many reserved tasks earlier today. If this helps, it's a mystery why `--prefetch-multiplier` wasn't already set to 4, the documented default. I can't imagine that this will _hurt_. If somehow our current settings have unlimited prefetch, then this could _theoretically_ introduce some (sub-second) latency, but only if the processing of tasks is uniformly way, way faster than pulling a task off the rabbitmq queue; it seems a low risk.
all
> Set --prefetch-multiplier=4 on celery tasks

- docs/howto/wipe_persistent_data.md
- src/commcare_cloud/ansible/roles/kafka/templates/server.properties.j2
- src/commcare_cloud/ansible/wipe_kafka.yml
- src/commcare_cloud/ansible/wipe_postgres.yml
Context: [SC-514](https://dimagi-dev.atlassian.net/browse/SC-514)
Two short playbooks to:
* Wipe Postgres databases created by `set_up_dbs.yml`
* Wipe Kafka topics created by the `create_kafka_topics` Django management command
Both commands require 
wipe_environment_enabled: True
to be set in in public.yml. This is a precaution against running these playbooks in the wrong environment.
Only environments that have `wipe_environment_enabled: True` in public.yml. The `wipe_postgres.yml` playbook does not work with remote DBs like Amazon RDS.
> Wipe Postgres DBs, Kafka topics

- environments/production/app-processes.yml
Formplayer machines are now 32G RAM, so setting formplayer max memory to 15G (just under 50%). The reason for not going closer to 100% is because formplayer does appear to benefit from using RAM for a fair amount of os caching.
production
> Increase prod formplayer_memory to ~50% of available memory

- environments/icds-cas/app-processes.yml
As a follow up https://github.com/dimagi/commcare-cloud/pull/3829
which upgraded the 
`reminder_rule_queue` to process two such rules in parallel and
`reminder_case_update` workers from 20 to 36
Since we are running the processing per shard now, there are more cases being sent for processing with task `sync_case_for_messaging_rule`
So to keep up with that change, need to add more power on "reminder_case_update"
Added 24 more workers to make 60 in total which is not exactly the double because worried if that would put major load of db and redis. Hence increasing by 24 as of now.
ICDS
> add 24 more workers for reminder_case_update

- src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml
this was causing formplayer restart whenever we run update-supervisor-confs
(even if you say no to reloading the services afterward).
all
> Skip stopping supervisord when nothing changed

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Removed in https://github.com/dimagi/commcare-cloud/commit/ae45e90253f9ace19d1dc721b44bb04a93c464b7
(mistakenly I believe)
production, india, swiss
> Add back TWO_FACTOR_GATEWAY_ENABLED option

- environments/staging/terraform.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
- src/commcare_cloud/terraform/modules/ga_alb_waf/variables.tf
And set staging to most restrictive ssl policy, `ELBSecurityPolicy-FS-1-2-Res-2019-08` (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies)
staging
> Make the aws ssl policy configurable

- docs/setup/troubleshooting.md
Recently, we ran into an issue with "npm_install". Phantomjs package was unable to download. therefore I had to download it manually and set the path.  Later, issue got resolved.
> Updating the npm install error - resolution steps

- src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml
This appeared to be a necessary step in fixing a blocking phantomjs install during deploy
> Update npm 6.4.1 => 6.14.5

- environments/production/terraform.yml
This will make our Monday switchover to using the load balancer WAF setup result in no change to our cipher set. Followup to https://github.com/dimagi/commcare-cloud/pull/3837
Similar to what we did for staging in https://github.com/dimagi/commcare-cloud/pull/3838
production
> Use ssl_policy ELBSecurityPolicy-FS-1-2-Res-2019-08 on production

- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
when the server arg is e.g. control:0 instead of control.
Introduced by https://github.com/dimagi/commcare-cloud/commit/608612f4553f9d53543a1dd09dd2ece9c8b1df97
Made this change last week and forgot to PR
> Fix --control by adding back -A ssh flag

- environments/production/terraform.yml
This doubles CPU while keeping memory constant. (ES has a step change degradation in performance if you allocate more than ~30g of head, so adding more memory to these nodes is of limited utility. We may want to do so soon by adding a new node though.)
production
> Add more CPU to production ES machines

- docs/setup/new_environment.md
Changes:
1. Requesting user to set valid root_email address. This is to validate the SSL certificates which we are provision using Letsencrypt without any issues.
2. Adding SSL.md instructions link in the new_environment.md so that the user can obtain Valid SSL certificates for the monolith env.
Please let me know your suggestions. Thanks.
> requesting valid root_email address and adding SSL.md Document link

- environments/india/public.yml
- environments/production/public.yml
We already changed how we do this on production/india
and I believe this is now broken anyway.
Having it around is just one more moving part we need to worry about.
production, india
> Remove config for backup_es_s3 on production/india

- environments/icds-staging/app-processes.yml
- environments/icds-staging/inventory/citusdb.csv
https://dimagi-dev.atlassian.net/browse/IIO-527
moving celery workers to other nodes to reduce the load on web machines.
icds-staging
> moved celery workers to other machines

- environments/production/inventory.ini
- src/commcare_cloud/commands/terraform/aws.py
- src/commcare_cloud/environment/schemas/terraform.py
in which case it should be set if the boot volume is encrypted.
I will roll this out at a low-traffic time by rebooting the affected webworkers and confirming they start back up without the /opt/tmp using ecryptfs after `after-reboot`.
production (and others going forward)
> Add root_encryption_mode=aws logic for when there is no block_device

- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
- src/commcare_cloud/ansible/roles/ecryptfs/defaults/main.yml
- src/commcare_cloud/ansible/roles/ecryptfs/tasks/main.yml
This was the key issues causing the sequence of events that led today's ES outage. Our ansible automation was not properly mounting the secondary volume at `/opt/data` (now that we're relying on AWS EBS encryption), and so it filled up the boot volume quickly, and Sanjay had to intervene and fix it manually. Review with ?w=1.
production
> Mount secondary volume even when root_encryption_mode=aws

- src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
I've been porting the WAF setup to terraform code bit by bit as terraform introduces support for the different components (e.g. [this one merged a week ago](https://github.com/terraform-providers/terraform-provider-aws/pull/12677))
production, staging
> Add commcare waf rule group to terraform

- src/commcare_cloud/commands/ansible/helpers.py
Lately I've noticed the `UserKnownHostsFile` param sometimes not being respected, and today I dug into it, and indeed I was able to prove to myself that even with the `UserKnownHostsFile` option we clearly think we're sending, it was using my `~/.ssh/known_hosts`.
Looks like this issue was introduced some time around https://github.com/dimagi/commcare-cloud/commit/c03291403c2d5237cf308e13c25ef25e2d51009d (either by that commit or by the thing that commit was trying to fix).
This PR simplifies the shlex quoting and is in line with the issue linked from that commit message, so I do believe it's the right fix. I can confirm it fixed the issue locally for me.
all
> Fix the shlex quoting of --ssh-common-args value

- src/commcare_cloud/ansible/roles/ebsnvme/tasks/main.yml
This was another thing I had to do to get the setup of a new machine with a secondary volume on AWS working. This code hasn't changed in a while, and I'm originally responsible for it, but still I have no idea how it ever worked. I don't think `file` could have ever been copying it, and I don't think `ebsnvme-id` could have ever referred to `_vendor/ebsnvme-id`
production/india/staging
> Fix vendorized ebsnvme-id

- environments/production/app-processes.yml
- src/commcare_cloud/environment/schemas/app_processes.py
These collectively cause spikes in requests to ES that we could easily smooth out
over a few hours without serious user-facing effects.
Reducing drastically for now to reduce ES spikes, will increase judiciously
if the workload delays become long enough to have user-facing effects.
production
> Reduce concurrency of daily bulk workloads on production

- src/commcare_cloud/ansible/deploy_couchdb2.yml
A day's worth on prod is about 3.5G, 35x the 100M file limit. This change will have it rotate 24x as often and keep 10x the number of files, for a total of ~100h (~4.2 days) instead of ~10 days.
Update: I changed this to store 3x as long by raising the file limit, so now about what it was before, but compressing more often
all, targeting production
> Rotate couch logs hourly

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
We saw these files owned by root at some point and aren't quite sure how. This PR makes each step explicitly set the owner. There's not a strong story that says this will fix it, but it's more explicit and it's correct (i.e. can't hurt) and I want to just eliminate the possibility that it's somehow this task.
production
> Add explicit permissions on copied formplayer config

- src/commcare_cloud/ansible/roles/nginx/vars/cas_sentry.yml
The variables file is evaluated even for envs that aren't using the feature.
(These are set up this way to support removing nginx config files no longer needed.)
So make sure all the variables evaluate without erroring.
> Make sure cas_sentry.yml doesn't break other envs

- environments/production/terraform.yml
I rolled this out during firefighting this morning. As far as we can tell the issues from this morning were caused by "too much memory". Presumably too much memory per machine. Very odd, but fairly conclusive
production
> Revert "Double formplayer machine sizes on production"

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/commands/terraform/templates/variables.tf.j2
dynamically fetched by querying AWS
production
> Always use latest bionic AMI

- environments/production/aws-resources.yml
- environments/production/terraform.yml
Followup to https://github.com/dimagi/commcare-cloud/pull/3974. Will merge once pgbouncer2's active connections (https://app.datadoghq.com/dashboard/unt-6cf-nbs/postgres---overview?from_ts=1594668866477&fullscreen_end_ts=1594683587568&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1594669187568&fullscreen_widget=256956003&live=true&to_ts=1594683266477&tpl_var_exclusions=pg_standby) goes to zero, which will be at the least after the next time we restart formplayer
production
> Remove pgbouncer2-production

- environments/icds-staging/fab-settings.yml
For supporting 
https://github.com/dimagi/commcare-hq/pull/27980 
we need to add `default_branch` in `environments/icds-staging/fab-settings.yml` so that we don't have to pass `--commcare-rev icds-autostaging` with every deploy
icds-staging
> Add default branch for icds-staging

- src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml
Note that `deploy-stack --tags=npm` will have to be re-run before the next set of deploys
> tag command that sets node version under "npm"

- src/commcare_cloud/commands/terraform/aws.py
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/environment/schemas/terraform.py
Easiest with ?w=1
Lets you add something like
`terraform.yml`
```
- server_name: "formplayer_a{i}-production"
server_instance_type: r5.2xlarge
network_tier: "app-private"
az: "a"
volume_size: 600
group: "formplayer"
os: bionic
count: 32
```
`inventory.ini.j2`
```
{{ __formplayer_a__ }}
[formplayer:children]
formplayer_a
```
And it'll create 32 identical machines and put them in the inventory for you under individual groups (`[formplayer_a000]` as well as a group that contains all of them `[formplayer_a]`)
None yet, but about to use on production
> Add support for defining N identical machines in terraform

- src/commcare_cloud/fab/fabfile.py
- src/commcare_cloud/fab/operations/release.py
- src/commcare_cloud/fab/utils.py
Implements https://github.com/dimagi/commcare-hq/issues/27838, using @AliRizvi1 's work in https://github.com/dimagi/commcare-cloud/pull/3951
```
[10.201.11.173] Executing task 'deploy_commcare'
List of PRs since last deploy:
1. Bump statici18n to version supporting Django 2.2 https://github.com/dimagi/commcare-hq/pull/28084 | product/invisible
2. [ICDS Dashboard] Pull the program summary data on the same level https://github.com/dimagi/commcare-hq/pull/28075 | product/custom
3. Fix sorting for FCT count column https://github.com/dimagi/commcare-hq/pull/28087 | product/all-users-all-environments
Are you sure you want to preindex and deploy to staging? [y/N] y
```
Since this significantly increases API requests to github, all users are now prompted to set up a github API key, though they …
> Integrate migration alerts into deploy

- src/commcare_cloud/fab/utils.py
Paranoid followup from https://github.com/dimagi/commcare-cloud/pull/3970
I was thinking of ways this might go bad, so I figured I'd put a couple guardrails on it.   Bonus colors for pizzazz too.
> Don't display too many PRs on deploy

- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
- src/commcare_cloud/ansible/deploy_formplayer.yml
- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/aws-efs/defaults/main.yml
- src/commcare_cloud/ansible/roles/aws-efs/tasks/main.yml
- src/commcare_cloud/ansible/roles/bootstrap-users/defaults/main.yml
- src/commcare_cloud/ansible/roles/bootstrap-users/tasks/main.yml
- src/commcare_cloud/ansible/roles/shared_dir/defaults/main.yml
- src/commcare_cloud/ansible/roles/shared_dir/tasks/setup_client.yml
- src/commcare_cloud/ansible/roles/shared_dir/vars/main.yml
The main important change here is that it lets you hardcode the `cchq` user's uid/gid for an inventory group (like formplayer) so that it has the same uid/gid across those machines, letting them share a drive without a confusing uid to user mapping.
(on staging and production formplayer machines, we already manually made this the case. On new machines it's safe, but I wouldn't recommend using this to _change_ existing machines uids.)
staging, soon to be production
> Clean up how we mount a formplayer EFS drive

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- src/commcare_cloud/ansible/roles/aws-efs/tasks/main.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- `_netdev` change is based off of https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-nfs-mount-settings.html
- security group change is just putting into terraform something I'd realized was missing and done manually before.
production, staging, eventually india
> Tweak efs mount setup

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
I found 100,000+ empty dirs on a formplayer machine.
The files get deleted by tmpreaper, but the dirs stick around forever!
all
> Clean up empty sqlite dirs

- environments/production/terraform.yml
7 x (36 vCPU / 72G RAM) => 8 x (32 vCPU / 128G RAM)
production
> Increase RAM for production ES cluster

- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
Reverts dimagi/commcare-cloud#4038
I think I misunderstood what "% FIREHOSE_STREAM_NAME%" means. I thought it was some reflexive IAM policy syntax. According to https://docs.aws.amazon.com/firehose/latest/dev/create-configure.html though it's a meaningless placeholder and "You can safely ignore or safely delete lines with" them.
I think this change didn't cause serious problems because the permission being changed isn't that important; it grants access to log to cloudwatch when there's an error in the kinesis stream, something that never or almost never happens.
> Revert "make firehose role shareable"

- src/commcare_cloud/ansible/roles/postgresql_base/defaults/main.yml
- src/commcare_cloud/ansible/roles/postgresql_base/templates/postgresql.conf.j2
shared buffer is getting set to 0GB for smaller machines.
ALL
> Check if shared buffer is 0GB

- environments/india/public.yml
Since 'india' is no longer an ICDS env this is not needed.
india
> remove icds middleware from india

- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
This was an experiment to see whether EFS would be performant enough to use as the disk for formplayer sqlite dbs, and the result of the experiment is that it wasn't. We won't be using this on prod, so I'm rolling back on staging as well.
staging
> Turn off use_formplayer_efs on staging

- src/commcare_cloud/ansible/roles/commcarehq/templates/django_bash_runner.sh.j2
This script was leaving the child process running.
icds, icds-staging
> kill child process on exit

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
- src/commcare_cloud/terraform/modules/logshipping/firehose_stream/main.tf
- src/commcare_cloud/terraform/modules/logshipping/firehose_stream/variables.tf
- src/commcare_cloud/terraform/modules/logshipping/main.tf
- src/commcare_cloud/terraform/modules/logshipping/variables.tf
Part 2 of https://trello.com/c/prhWvkky/37-hipaa-logging-improvements
Staging:
```
Terraform will perform the following actions:
- module.server__rabbit1-staging.aws_instance.server
+ module.logshipping.module.firehose_stream.aws_iam_role.firehose_role
id:                                                       <computed>
arn:                                                      <computed>
assume_role_policy:                                       "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"firehose.amazonaws.com\"},\"Action\":\"sts:AssumeRole\",\"Condition\":{\"StringEquals\":{\"sts:ExternalId\":\"737236193635\"}}}]}\n"
create_date:                                              <computed>
force_detach_policies: …
```
> add firehose stream to logshipping module

- src/commcare_cloud/fab/operations/release.py
https://github.com/dimagi/commcare-hq/issues/27839
Related to https://github.com/dimagi/commcare-hq/pull/28234, this PR is updating the commcare-cloud code to match the new commit field in the HqDeploy model.
Deployments will now use the `--commit` flag of the `record_deploy_success` management command automatically.
> Add commit field to record_successful_deploy()

- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
- src/commcare_cloud/ansible/roles/commcarehq/vars/main.yml
- src/commcare_cloud/ansible/roles/rabbitmq/tasks/install_latest.yml
This adds a new option to migrate rabbitmq to a new machine rather than upgrading in place. It's not as clean as I'd hoped: specifically while `CELERY_BROKER_READ_URL` can take a list of endpoints, it actually just uses the first one unless it fails; i.e. further endpoints in that list are failover endpoints, not equal members in the list. What that means is basically that we need some celery nodes to have these "straddling" settings and others to have the future setup (so that they're reading from _and_ writing to the new rabbitmq instance) until the old rabbitmq instance is fully drained.
The alternative to this is to set up a cluster and learn to do the upgrade one node at a time when that's possible. We may want to have both options in our tool belt.
available to all
> Add ability to straddle two rabbitmq instances 

- src/commcare_cloud/ansible/roles/ecryptfs/tasks/tmp.yml
Previously weren't creating /opt/tmp but still passing it in as TMPDIR
and processes were falling back to /tmp, which didn't have tmpreaper set up,
causing unbounded disk growth.
This commit both adds /opt/tmp and sets up tmpreaper on /tmp.
> Fix tmp dir situation on AWS encrypted disks

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/terraform/modules/logshipping/outputs.tf
- src/commcare_cloud/terraform/modules/server/iam/main.tf
- src/commcare_cloud/terraform/modules/server/iam/outputs.tf
- src/commcare_cloud/terraform/modules/server/iam/variables.tf
- src/commcare_cloud/terraform/modules/server/main.tf
- src/commcare_cloud/terraform/modules/server/variables.tf
https://trello.com/c/prhWvkky/37-hipaa-logging-improvements
We need to create a new `CommCareServerRole` that gives servers write access to the request response firehose stream.
Changes:
- create a `server/iam` module directory
- `server/iam` module creates commcare server role, attaches the aws managed cloudwatch and managed instance roles, creates a role policy for the request response stream writes, and creates the instance profile to be used by `aws_instance`
- Passes in the newly created instance profile to aws instances
NOTE: `iam_instance_profile` is only used during instance creation according to the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#iam_instance_profile), so adding this attribute does not replace the iam role on instances. …
> create commcare server role in tf

- environments/production/terraform.yml
We recently added a second proxy node for the CPU.
Reducing the memory so that combined it is what this alone was before,
and so the two machines are the same.
(already applied)
production
> Resize proxy2-production

- environments/production/app-processes.yml
Our current data suggests when we're close to the max gunicorn
workers, our normalized system load peaks around .4.
That suggests to me we could server many more concurrent requests
per webworker than we currently are.
production
> Increase gunicorn_workers_factor on production from 1 to 2

- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/logback-spring.xml.j2
A continuation of https://github.com/dimagi/commcare-cloud/pull/4077
- Changes kinesis file_pattern so we detect log rotation
- increase the limit of formplayer logs from 1MB to 1GB while maintaining 3 extra log rotated files instead of just 1. 
staging, prod, india
> changed kinesis file pattern and increased formplayer log limit

- src/commcare_cloud/ansible/roles/sentry/defaults/main.yml
- src/commcare_cloud/ansible/roles/sentry/templates/sentry.conf.py.j2
sometimes sentry stops processing altogether because of too many requests, this has happened a few times. if this fix doesn't work we have to apply quota limit instead.
ICDS
> scale sentry workers

- src/commcare_cloud/fab/fabfile.py
- src/commcare_cloud/fab/operations/supervisor.py
This was a bridge during the transition, but enough time has passed
and the condition is no longer ever fulfilled.
Just something I came across
all (but it's no change other than being faster)
> Remove unused formplayer formplayer restart code from deploy

- src/commcare_cloud/commands/ansible/ansible_playbook.py
- src/commcare_cloud/commands/ansible/run_module.py
- src/commcare_cloud/environment/secrets/backends/abstract_backend.py
- src/commcare_cloud/environment/secrets/backends/ansible_vault/main.py
- src/commcare_cloud/manage_commcare_cloud/list_vault_keys.py
Some small updates to https://github.com/dimagi/commcare-cloud/pull/4114 based on Simon's insightful feedback.
- Clean up the interface a bit
- Make `AnsibleVaultSecretsBackend` inherit from an abstract base class with a clean interface that's generic (and not vault-specific. The only things a sub class is forced to define are (1) `get_secret` (the central capability of a secrets backend) and (2) `get_generated_variables` (which defines how the backend fetches secrets and assigns them to ansible variables).
all, but it's a no-op
> Secrets backend with abstract base class

- src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml
- src/commcare_cloud/fab/fabfile.py
- src/commcare_cloud/fab/operations/staticfiles.py
A fresh environment sometimes tries to install js packages with npm instead of yarn, which causes errors.
this affects deploy on all environments
> clean up npm and bower commands on deploy and always default to yarn

- environments/production/public.yml
We have a routine issue where ever couple weeks couch disk usage goes about 80% and I can resolve it by manually running compaction. Compaction is automatically running continuously which makes that really confusing. Last week I tested a hypothesis that the threshold, set at 6% fragmentation, was too low, and thus too many view and data files were being targeted for compaction at once, resulting in the compaction process not picking the most useful files to start with and not being able to keep up with the queue of things presumably needing compaction. To test this, I set couch14's threshold to 20% instead of 6%, telling it to focus on files with a higher bang for the buck. (If I set that too high, it'll wait too long to compact, so I still believe there's a sweet spot.)
The results were …
> Change production compaction settings

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/downtime.py
- src/commcare_cloud/commands/ansible/ops_tool.py
- src/commcare_cloud/commands/ansible/run_module.py
- src/commcare_cloud/commands/secrets.py
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/commcare_cloud.py
- src/commcare_cloud/environment/secrets/backends/abstract_backend.py
- src/commcare_cloud/environment/secrets/backends/ansible_vault/main.py
- src/commcare_cloud/environment/secrets/secrets_schema.py
- src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py
Example usage:
```
cchq production secrets view POSTGRES_USERS.commcare.password
```
Currently the `set_secrets` method on the only currently existing secrets backend isn't implemented, so the `edit` command isn't useful yet. It's a little tricky to implement for vault without reformatting the vault file each time (and getting rid of comments) so I decided to punt for now. Will be useful for the new backend I'm working on though.
> Add 'secrets' command for working with secrets values

- src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml
- src/commcare_cloud/ansible/deploy_stack.yml
- src/commcare_cloud/ansible/roles/cloudwatch_logs/defaults/main.yml
- src/commcare_cloud/ansible/roles/cloudwatch_logs/tasks/main.yml
- src/commcare_cloud/ansible/roles/cloudwatch_logs/templates/cloudwatch_logs.json.j2
https://dimagi-dev.atlassian.net/browse/SAAS-11088
`cloudwatch_logs` role creates log config json and loads it to the cloudwatch agent. Creates something like
Note: Not all of these have been applied to staging. 
TODO: 
- Right now for some log dirs, we just glob them altogether but a finer grain separation might be desired
- The simplest approach seemed to be to pass the var into the ansible call e.g.
```
vars:
log_files_collect_list:
- file_path: "/home/cchq/www/{{ deploy_env }}/log/**.log**"
log_group_name: "proxy"
log_stream_name_suffix: ""
```
Mainly because I didn't know how to pass in a single entry from a global dict var. But we might want to do that and use terraform to create the [log groups](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_l …
> add cloudwatch_log role and deploys

- environments/icds-cas/public.yml
- environments/india/public.yml
- environments/production/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
This lets us control whether device logs are enabled from the commcare-cloud environment rather than a global setting in `commmcare-hq/settings.py`.
This also adds india to that list
india
> Control NO_DEVICE_LOG_ENVS with new DEVICE_LOGS_ENABLED setting

- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/roles/cloudwatch_logs/defaults/main.yml
- src/commcare_cloud/ansible/roles/cloudwatch_logs/tasks/main.yml
Previous introduction of cloudwatch logs did not isolate environments. This isolates it to staging, production, and india. 
Staging, Production, India
> only enable cloudwatch logs on certain environments

- src/commcare_cloud/ansible/deploy_kafka.yml
- src/commcare_cloud/ansible/roles/kafka/files/log4j_2.4.1.properties
DailyRollingFileAppender has been observed to exhibit synchronization issues and data loss.
In addition to that it makes it very hard to use in conjunction with logrotate. 
This PR updates the Kafka logging configuration to use a vanilla `RollingFileAppender` which will also take care of cleaning up old logs.
all
> update kafka log config

- environments/production/terraform.yml
It has been growing for about 8 weeks and our retention period is 9 weeks
so I think there is a chance it will level out at a new steady state
in a week or two. If it does not, then we will really need to investigate
the cause and make some optimizations before the disk becomes an even more major expense
production
> Increase pgsynclog0-production max_storage

- .travis.yml
- .travis/tests.sh
The best little idea that never came to be. This build has sadly never passed, and we aren't able to get any value out of it. Rather than hold on, I think it's finally time to let it go. Any solution to the same problem (and I hear there's some work outside of SaaS on it) will likely end up being done differently anyway.
:(
none
> Remove defunct prove-deploy build

- environments/production/public.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
- src/commcare_cloud/ansible/roles/formplayer/vars/main.yml
Allows environments to direct Spring Boot to natively process `X-Forwarded-For` headers as provided by load balancers or proxies.
> Allow configuration of Forwarding Header Processing

- environments/india/proxy.yml
- environments/production/proxy.yml
- environments/staging/proxy.yml
- src/commcare_cloud/ansible/roles/nginx/templates/site.j2
- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
- src/commcare_cloud/environment/schemas/proxy.py
This adds a variable, trusted_proxies, to proxy.yml, and then uses it to configure nginx to set the `X-Forwarded-For` to the real client IP address as opposed to either (1) the full chain including whatever the user passed in or (2) just the upstream proxy's IP address.
https://dimagi-dev.atlassian.net/browse/SAAS-11335
production, staging, india
> Fix X-Forwarded-For with set_real_ip_from

- tests/__init__.py
- tests/test_couch_migration.py
- tests/test_csv_inventory.py
- tests/test_getinventory.py
- tests/test_service.py
Tests were failing because of `COMMCARE_CLOUD_DEFAULT_USERNAME` in my environment.
> Fix tests and eliminate deprecation warning

- src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
Known port required for setting up couchdb cluster  on ICDS-SANDBOX due to NIC infrastructure port issue.
ICDS-SANDBOX
> known port setting for Erlang couchdb cluster

- src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
Installing couchDB cluster on a already known port .
None, at this time.
> fixing line entry

- CONTRIBUTING.md
Zsh uses square brackets for pattern matching, so when passing as part of an argument, the argument needs quotations. Made this clear in the Contributing readme.
> Update Contributing readme for zsh users

- src/commcare_cloud/commands/ansible/helpers.py
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
Review commit-by-commit. The third commit is the only behavior change. Typical of escaping, we never noticed this because we so far haven't used ssh options that require escaping (due to presence of ` `, `'`, `"`, etc), and so by accident the escaped and unescaped versions are the same. This fixes it to work for ssh option values that contain those characters.
> Shlex quote ssh options

- src/commcare_cloud/ansible/deploy_commcarehq.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/celery_cron.yml
- src/commcare_cloud/fab/fabfile.py
Celery tasks
- soft kill > 36h
- kill immediately > 46h. 
Increased previous release folders retention period to 48 hours by default.
> adding cron job entries to kill celery tasks after 36h

- scripts/example-apply-terraform-to-single-server-and-bring-back-up.sh
I use these scripts as a starting point for some operations, and this is a generally useful change I made during a recent rollout.
none
> Make scripts/example-apply-terraform-to-single-server-and-bring-back-up.sh accept multiple hosts

- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
I have upgraded ES to 7.9.1 using the es4 and es5 machines. I have already rolled this out. 
We can now delete the es6 and es7 machines. @dannyroberts @sanjay2916
> update staging es machines

- src/commcare_cloud/commands/secrets.py
This was necessary to make a change to the POSTGRES_USERS secret.
I needed to change the path `POSTGRES_USERS.userX.privs.0.objs`:
```yaml
userX:
privs:
- objs: userY
type: group
username: username
```
`cchq <env> secrets edit POSTGRES_USERS.userX.privs.0.objs` failed this error:
```
File "/home/skelly/.commcare-cloud/bin/cchq", line 11, in <module>
load_entry_point('commcare-cloud', 'console_scripts', 'cchq')()
File "/home/skelly/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 183, in main
exit_code = call_commcare_cloud()
File "/home/skelly/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 174, in call_commcare_cloud
exit_code = commands[args.command].run(args, unknown_args)
File …
```
> parse secret as json before storing

- src/commcare_cloud/commands/ansible/ansible_playbook.py
Also standardise pattern using ',' (people generally understand what a ',' does better than a ':' for separating lists of items)
> allow either ',' or ':' to be used in limit patterns

- src/commcare_cloud/ansible/roles/postgresql_base/templates/pg_hba.conf.j2
This would error in envs without the `main_dbs` group which is and ICDS specific thing.
> more robust airflow db check in pg_hba

- src/commcare_cloud/ansible/group_vars/alertmanager.yml
- src/commcare_cloud/ansible/group_vars/prometheus.yml
- src/commcare_cloud/environment/main.py
- src/commcare_cloud/yaml.py
https://github.com/dimagi/commcare-prometheus/pull/36
Changes to YAML loading are required to preserve the `unsafe` tag for any vars which are used in [icds prometheus config](https://github.com/dimagi/icds-commcare-environments/blob/master/environments/icds-cas/prometheus.yml#L26)
> add prometheus group vars

- environments/production/app-processes.yml
1. added 2 more kafka paritions to the topic=synclog-sql. Total: 4 now
2.  increased UpdateUserSyncHistoryPillow processes from 2 to 4.
>  increased UpdateUserSyncHistoryPillow processes from 2 to 4

- environments/production/postgresql.yml
- environments/production/terraform.yml
- raise postgres connection limit 300 => 500
- increase size of pgmain0
I was tempted to also change these settings to match [pgtune](https://pgtune.leopard.in.ua/#/) recommendations, but I chose not to hold off since changing any of these could conceivably have a _negative_ effect on performance. (Before we do, we should at least understand what the current/default values are in RDS/postgres.)
```
shared_buffers: 16GB
effective_cache_size: 48GB
maintenance_work_mem: 2GB
default_statistics_target: 100
random_page_cost: 1.1
effective_io_concurrency: 200
work_mem: 20971kB
min_wal_size: 1GB
max_wal_size: 4GB
max_worker_processes: 16
max_parallel_workers_per_gather: 4
```
production
> Increase production postgres connection limit

- src/commcare_cloud/ansible/roles/postgresql_base/handlers/main.yml
- src/commcare_cloud/ansible/roles/postgresql_base/templates/monit.postgresql.j2
Although the version was specified already it was being ignored (note from the docs "While using remote hosts with systemd this setting will be ignored.")
Also the `init.d` script that monit was using doesn't work since it gets redirected to using systemd.
> specify pg version in monit and handlers

- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
This PR is basically acknowledging that an IP deny list is a more dynamic thing than we want to hard code in a setting in a git repo
saas aws envs
> Have terraform ignore manual changes to the IP deny list

- src/commcare_cloud/ansible/roles/citusdb/tasks/setup_cordinator.yml
- src/commcare_cloud/ansible/roles/citusdb/tasks/setup_worker.yml
There are two issues that make this necessary.
1. The version of the citus extension does not match the version of the package (the package does not include the 'patch' version). This works OK for installing the extension the first time but after that the `postgresql_ext` ansible module will complain that `9.4 < 9.4.1`. 
2. The `postgresql_ext` ansible module does not correctly sort available versions. To work around the 1st point you can set the version to `latest` but a bug in the Ansible module where it's not sorting the versions means that the version it tries to install is somewhat random: https://github.com/ansible-collections/community.general/pull/1078
This change queries the DB for the latest available version that is >= the specified version and uses that as the input to the …
> get correct version from DB to fix postgresql_ext bug

- environments/_users/fission-warehouse.yml
The only environment to include fission-warehouse users is staging. Adil still works with USH so will maintain access to staging. 
Staging
> Revoke access for fission warehouse

- environments/production/terraform.yml
When firefighting yesterday I made a small oversight that results in something super cost-inefficient: paying for db.m5's when we've already prepaid for db.t3's that we now aren't using. This PR switches the pgshard machines back to db.t3 while keeping the current "size" of RAM and CPU. I expect this to have no effect on performance and a ton of effect on cost (versus staying the course we set yesterday).
production
> Use db.t3.* in production to align with RIs

- environments/production/terraform.yml
This was an oversight from https://github.com/dimagi/commcare-cloud/pull/4284 I found only after merging it.
> Do the same to pgshard1-production as the rest of the shards

- src/commcare_cloud/terraform/modules/postgresql/main.tf
added in https://github.com/dimagi/commcare-cloud/pull/4283 but inadvertently not actually used
> Use new monitoring_interval rds setting

- src/commcare_cloud/commcare_cloud.py
```
src/commcare_cloud/commcare_cloud.py:184: SyntaxWarning: "is not" with a literal. Did you mean "!="?
```
> fix syntax warning

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/ops_tool.py
This can be useful when doing migrations (using the `migrate-couchdb` command) when the source cluster is no longer available (docs etc. still to be worked out).
> option to dump current couchdb shard allocation

- environments/staging/postgresql.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/deploy_postgres.yml
- src/commcare_cloud/ansible/group_vars/postgresql.yml
- src/commcare_cloud/ansible/roles/pg_repack/defaults/main.yml
- src/commcare_cloud/ansible/roles/pg_repack/files/pg_repack.py
- src/commcare_cloud/ansible/roles/pg_repack/tasks/main.yml
Installed pg_repack 1.4.3 version on staging pg_bouncer server to add an extension on the staging commcarehq_synclog database. Faced some issues in pg_repack tasks/main.yml with the item variable. Fixed it. 
- Updated pg_repack script to connect to the remote database. 
- we need superuser (root) credentials to allow repacking on the databases/tables. 
Please review my changes related pg_repack.py. If looks good will apply the changes in staging env first. thanks.
> pg_repack extension created for staging commcarehq_synclog

- src/commcare_cloud/commands/terraform/aws.py
https://dimagi-dev.atlassian.net/browse/SAAS-11451. I also updated the commcare-india account role settings in the console to have the same configuration as production, staging, so that now this default is right for all of them.
saas aws envs
> Change default aws sso_role_name to match online configuration

- environments/staging/terraform.yml
Staging has been rolled back to ES2 using the original ES2 nodes. These ES7 nodes are no longer in use.
I tried running `terraform plan` but got permission denied errors on a number of resources so someone else will have to roll this out.
staging
> remove es7 nodes from staging

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/fab/fabfile.py
Little utility that can be run with
```
$ cchq production fab preview_deploy
```
None
> Add simple task to preview PRs about to be deployed

- environments/production/terraform.yml
`pgsynclog0-production` triggered the 90% disk usage threshold today. 
production
> bump max_storage of pgsynclog0-production from 20TB to 30TB

- environments/india/inventory.ini
- environments/india/inventory.ini.j2
- environments/india/postgresql.yml
- environments/india/terraform.yml
This cluster is not longer used. It has already been (removed from localsettings](https://github.com/dimagi/commcare-cloud/pull/3907).
We are still keeping the 'test' cluster for now while we continue to test the rebalancing tool.
`india`
> remove main citus cluster from india

- src/commcare_cloud/commands/ansible/service.py
After changing the PosgreSQL service to be version
specific the 'monit' check broke since it was
looking for exact matches.
> check for prefix instead of full match

- .travis.yml
This may be the reason why Ansible uses pip2 instead of pip3 on Travis (unlike our production machines).
travis (tests only)
> Use bionic image on Travis since most (all?) envs are now on 18.04

- docs/howto/wipe_persistent_data.md
- src/commcare_cloud/ansible/wipe_kafka.yml
Fetch the list of topics from kafka itself, rather than django.  On a multi-server environment, kafka is often on a machine that doesn't have a django environment setup, so you can't run management commands directly.
This only affects environments where we're wiping all data in preparation for restore from backups or data dumps - it shouldn't affect any production environment.
> Use kafka-topics.sh --list to get topics for kafka data wipe

- scripts/es_snapshot.py
- src/commcare_cloud/python_migration_utils.py
[Prepare for Python 3 Compatibility](https://dimagi-dev.atlassian.net/browse/SAAS-11366)
Also added a util method for properly handling `json.dump(s)` conflicting behaviors on Python 2 and 3.
None
> Explicitly use io.open in scripts directory files

- src/commcare_cloud/ansible/deploy_commcarehq.yml
Fixed the template not found issue by switching from import_tasks to import_role. Tested in staging and did work.
Please review. thanks
> switched from import_tasks to import_roles

- src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml
Was previously not shipping any es logs on production because no logs matched the patterns. This fixes that
prod, india, staging
> Fix es log paths for log shipping

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
it is already handled by a more general one that is on all machines. This was causing harmless but spammy errors when two different processes tried to delete the same files.
all
> Remove redundent tmpreaper task on formplayer /tmp directory

- control/init.sh
- src/commcare_cloud/commcare_cloud.py
Set the environment variable `CCHQ_VIRTUALENV` to `cchq` (or anything other than `ansible`) when running `commcore-cloud --control` commands to cause the virtualenv with that name to be used on the control machine. The virtualenv with will be created with python3 if it does not exist. Example:
```sh
CCHQ_VIRTUALENV=cchq commcare-cloud <env> --control ...
```
Use of virtualenvwrapper by init.sh will be phased out with Python 2.
None. This is currently for testing only. Running `commcare-cloud` with Python 3 is still in development.
> Enable commcare-cloud --control with python3

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/couch_utils.py
- src/commcare_cloud/commands/ansible/ops_tool.py
Add document counts to `couchdb-cluster-info` output:
**--shard-counts**
```
Shard allocation
00000000-1fffffff    20000000-3fffffff    40000000-5fffffff    60000000-7fffffff    80000000-9fffffff    a0000000-bfffffff    c0000000-dfffffff    e0000000-ffffffff
----------------  -------------------  -------------------  -------------------  -------------------  -------------------  -------------------  -------------------  -------------------
commcarehq        c1,c2,c3             c1,c2,c3             c1,c2,c3             c1,c2,c3             c1,c2,c3             c1,c2,c3             c1,c2,c3             c1,c2,c3
...doc_count      20203549,+637,-1302  20209048,+1050,-951  20205735,+969,-1415  20207806,+1035,-886  20205643,+901,-1019  20208597,+895,-1137  20207946,+990,-1080 …
```
> add shard document counts to "couchdb-cluster-info" command output

- src/commcare_cloud/environment/main.py
- src/commcare_cloud/environment/paths.py
- src/commcare_cloud/environment/secrets/backends/ansible_vault/main.py
- src/commcare_cloud/environment/secrets/backends/ansible_vault/tests/test_secrets_list.py
- src/commcare_cloud/environment/secrets/backends/aws_secrets/tests/test_secrets_list.py
- src/commcare_cloud/environment/secrets/secrets_schema.py
- src/commcare_cloud/manage_commcare_cloud/tests/test_environments.py
- src/commcare_cloud/python_migration_utils.py
A continuation of work done for this ticket. This addresses all of the uses of `open` in the `environments` directory.
None
> Explicitly use io.open in environments directory

- docs/commcare-cloud/commands/index.md
- scripts/es_snapshot.py
- src/commcare_cloud/commands/ansible/ops_tool.py
- src/commcare_cloud/commands/migrations/config.py
- src/commcare_cloud/commands/migrations/copy_files.py
- src/commcare_cloud/commands/migrations/couchdb.py
- src/commcare_cloud/commands/terraform/aws.py
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/commands/terraform/terraform_migrate_state.py
- src/commcare_cloud/environment/main.py
- src/commcare_cloud/python_migration_utils.py
In addition to addressing the areas in the `commands` directory that use `open`, I added a new helper in `python_migration_utils` aimed at replacing the existing methods since all address the same issue/have the same implementation. 
None
> Explicitly use io.open in commands directory

- docs/commcare-cloud/commands/index.md
- scripts/es_snapshot.py
- src/commcare_cloud/commands/ansible/ops_tool.py
- src/commcare_cloud/commands/migrations/config.py
- src/commcare_cloud/commands/migrations/copy_files.py
- src/commcare_cloud/commands/migrations/couchdb.py
- src/commcare_cloud/commands/terraform/aws.py
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/commands/terraform/terraform_migrate_state.py
- src/commcare_cloud/environment/main.py
- src/commcare_cloud/manage_commcare_cloud/configure.py
- src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py
- src/commcare_cloud/python_migration_utils.py
Continuation of a list of PRs for this ticket. This fixes `open` calls in the `manage_commcare_cloud` directory.
Wait to merge until [this](https://github.com/dimagi/commcare-cloud/pull/4347) is merged.
The first new commit is https://github.com/dimagi/commcare-cloud/pull/4354/commits/d6ac1a4172a2e67927d80c393136d9900ebecdd9
None
> Explicitly use io.open in manage_commcare_cloud directory

- src/commcare_cloud/ansible/plugins/inventory/csv.py
- src/commcare_cloud/ansible/plugins/lookup/cchq_aws_secret.py
- src/commcare_cloud/cli_utils.py
- src/commcare_cloud/fab/utils.py
- src/commcare_cloud/parse_help.py
Continuation of the PRs to replace open calls in python 2/3 with io.open calls. 
None
> Explicitly use io.open in remaining files in src/commcare_cloud

- src/commcare_cloud/ansible/hq_rolling_restart.yml
I used this today to roll out config changes without impacting usage. In the long run it could be made into a dedicated command with better error handling etc. but just putting it here for now.
> rolling restart playbook for webworkers and formplayer

- environments/staging/public.yml
https://dimagi-dev.atlassian.net/browse/USH-482
This now matches [the limit on prod](https://github.com/dimagi/commcare-cloud/blob/98b4f21d5b60043a289da00a93de9a957d1f7540/environments/production/public.yml#L86).
staging
> Increased couchdb2_client_max_body_size on staging

- src/commcare_cloud/commands/shared_args.py
This removes the restriction on which callback options can be used allowing the 'user' to choose any of the available options.
> allow any callback options (remove 'choices')

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/run_module.py
This allows adding arbitrary tags to events sent to Datadog such as the host or group the event is related to.
> allow adding tags to datadog events

- src/commcare_cloud/environment/exceptions.py
- src/commcare_cloud/fab/operations/release.py
Discovered this issue when HQ code was removed from formplayer machines. The machines were unable to create a new virtual environment during deploy. This is ok behavior since an ansible command handles creating a virtualenv when first being setup, and we do not expect to remove the /current directory from any machine that needs it. This will make it easier to debug in the future if it ever comes up.
None
> Raise exception if /current release directory does not exist when deploying 

- environments/production/terraform.yml
It hasn't been increased this year while the rest of the cluster expanded around it.
It's the only db.t3 we use in production and since the maintainance in the last couple weeks
we are no longer using all of our RIs. Based on those two things it seemed worth it to throw
more hardware at this instance since we are already committed to paying for that regardless.
production
> Increase pgucr0-production RDS instance to make use of RIs

- src/commcare_cloud/fab/const.py
- src/commcare_cloud/fab/fabfile.py
Removing 'formplayer' from the `ROLES_ALL_SRC` role means that the commcare-hq code
will not get deployed to these nodes. In the past formplayer was deployed inside the HQ code deploy structure
but that is no longer the case. There is no need to have the HQ code on formplayer machines.
ALL
> remove commcare-hq source from formplayer machines

- environments/production/terraform.yml
This is to avoid tomorrow morning the brownout we had earlier today due to pgbouncer getting too close to using all its memory https://app.datadoghq.com/dashboard/nbz-bie-nip/host-groups?from_ts=1607459910000&fullscreen_end_ts=1607472475285&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1607467785000&fullscreen_widget=274741947&live=true&to_ts=1607488710000&tpl_var_environment=production&tpl_var_host_group=postgresql.
production
> Add RAM to pgbouncer3-production

- src/commcare_cloud/ansible/deploy_commcarehq.yml
- src/commcare_cloud/ansible/host_group_aliases.yml
Followup to https://github.com/dimagi/commcare-cloud/pull/4361. This is both just nice cleanup and something that we found since that PR was merged blocks us from running `update-config`. Once a formplayer deploy has gone out, current/localsettings.py will no longer exist and a task that tries to update it fails.
all
> Remove commcare-hq src from formplayer (part 2)

- src/commcare_cloud/ansible/roles/bootstrap-users/templates/sudoers.j2
Followup to #4361 and #4387. Those changes would have removed an important line from the sudoers file on formplayer, and this adds it back
general
> Include supervisor commands in formplayer sudoers file

- src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml
It is not super clear (1) how this worked before and (2) why it stopped working in some cases.
But it should be fine to use elevated permissions to do this step. @millerdev you suggested this as a possible solution the other day when we talked and I was too baffled to make a decision, but I looked again and it seems like a reasonable fix even if we don't know what made this change now
My guess is either that something changed the permissions of /usr/local/bin or /usr/bin, or the location of where supervisorctl was installed (?) or the permissions of the supervisor binaries after install. Not sure if that rings any bells for anyone but it doesn't for me.
we've seen this on staging (not sure if it affects other environments, but I'd default to assuming so)
> Use become to link supervisor binaries

- control/init.sh
Prevents errors like
Python 2:
```
pkg_resources.DistributionNotFound: The 'importlib-metadata==3.1.0' distribution was not found and is required by commcare-cloud
```
Python 3
```
pkg_resources.DistributionNotFound: The 'ndg-httpsclient' distribution was not found and is required by commcare-cloud
```
Explanation: `pip install --editable .` writes package metadata, including a list of requirements, in the directory containing the "editable" dependency. This is a problem since requirements are different for Python 2 and 3. Errors happen when metadata for the opposite version of Python is present when running commcare-cloud commands. Removing requires.txt disables the run-time check of requirements by pkg_resources.
n/a (commcare-cloud on Python 3 is currently still being tested on …
> Allow switch between Py2/3 virtualenvs

- src/commcare_cloud/fab/README.md
- src/commcare_cloud/fab/fabfile.py
Found myself a little lost trying to setup a private release on icds-staging the other day with specific branches.
So
1. Added an example in code itself for quick reference
2. Adding an example in the README for extensions
3. Added a link to README's relevant section in the common method called for both deploy and private releases, where i think it is relevant, though we might then need to rename the README title to "Manage releases" instead of "Private releases" if that makes sense?
None
> Add more doc and link to setting up releases

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
A change made for https://dimagi-dev.atlassian.net/browse/SAAS-11511 wasn't backwards compatible, and this PR makes it backwards compatible.
production, india (staging had a different config so wasn't hit by it)
> Fix terraform for configs without elasticache_cluster

- src/commcare_cloud/ansible/requirements.yml
- src/commcare_cloud/ansible/roles/formplayer/defaults/main.yml
- src/commcare_cloud/ansible/roles/formplayer/meta/main.yml
- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/logback-spring.xml.j2
- src/commcare_cloud/ansible/roles/formplayer/templates/monit.formplayer.j2
- src/commcare_cloud/ansible/roles/formplayer/vars/main.yml
[Monit Investigation](https://dimagi-dev.atlassian.net/browse/SAAS-11555)
This is a solution to a symptom of recent formplayer issues, which is frequent OOMs that do not bring the entire formplayer process down. Similar to elasticsearch, the method here is to search the formplayer logs for an OOM and restart using supervisor if/when that occurs. 
None
> Add monit to formplayer to restart if OOM occurs

- environments/production/inventory.ini
- environments/production/inventory.ini.j2
[Use monit to restart if OOM due to GC occurs](https://github.com/dimagi/commcare-cloud/pull/4386)
This PR is the next step in using monit to restart formplayer machines if an OutOfMemory error due to garbage collection occurs. To be conservative, we will start by rolling this out to one machine that has exhibited issues and monitor the impact.
Production
> Enable monit for formplayer c023

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
`<var> == true` does not work. The variable on its own errors due to a deprecation so `<var>|bool` seems to be correct and it works when tested on staging.
> Use a conditional check for monit that will actually work

- src/commcare_cloud/ansible/deploy_formplayer.yml
Properly include the monit reload handler to give the formplayer playbook access to it/the ability to run it. Tested by making no-op changes on c023 and verified that monit reloaded as expected.
None
> Include monit handlers to have access to 'reload monit'

- src/commcare_cloud/ansible/deploy_stack.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/formplayer.yml
Following the process outlined [here](https://confluence.dimagi.com/pages/viewpage.action?spaceKey=internal&title=How+to+create+a+new+machine+in+an+AWS+environment) for a formplayer machine failed on 2 steps:
- an inability to find /dev/sd[x], because that device did not exist
- accessing a directory in formplayer which did not exist
The first seems to have been caused by the common mounting operations overriding the work of deploy_ebsnvme_mapping. The error encountered:
`
TASK [ecryptfs : Format block storage volume] *******************************************************************************************************************************
fatal: [10.201.10.118]: FAILED! => {“changed”: false, “msg”: “Device /dev/sdf not found.“}
`
The second is caused by referencing a folder that was …
> Formplayer deployment fixes

- src/commcare_cloud/commcare_cloud.py
As part of the Python 3 migration on commcare-cloud, this change ensures users are aware they need to upgrade to Python 3. If they must use Python 2 they can still to do so, but this makes it slightly more difficult (must pass in `--force-commcare-cloud-to-use-python2`). We will merge this once we feel Python 3 is ready for use on all environments. 
None
> Enforce python 3 usage

- src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2
- src/commcare_cloud/ansible/roles/nginx/templates/site.j2
Some of the code within jinja templates referred to unsupported code from python 2. This specific PR just handled those templates still using `.iteritems()` rather than `.items()`.
> Updated proxy template files to support python 3

- environments/production/terraform.yml
This is to reflect the current live state. We found in our recent P1 that autoscaling storage
has a very dangerous side effect of, if it does not add enough during autoscaling,
preventing you from making any further changes for about 12 hours.
(That time probably depends on a lot of factors including how much data you have on disk.)
In addition to this, we will lower the monitor alert threshold for disk usage to 75%. Regardless of whether or not we have autoscaling storage enabled, getting close to the allocated storage is (as we found yesterday) extremely dangerous.https://app.datadoghq.com/monitors/20795740
production
> Disable storage autoscaling on pgmain0-production

- src/commcare_cloud/ansible/roles/pg_repack/files/pg_repack.py
- src/commcare_cloud/commands/ansible/ops_tool.py
```
File "/Users/grahamherceg/.pyenv/versions/cloud/bin/cchq", line 11, in <module>
load_entry_point('commcare-cloud', 'console_scripts', 'cchq')()
File "/Users/grahamherceg/code/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 213, in main
exit_code = call_commcare_cloud()
File "/Users/grahamherceg/code/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 204, in call_commcare_cloud
exit_code = commands[args.command].run(args, unknown_args)
File "/Users/grahamherceg/code/commcare-cloud/src/commcare_cloud/commands/ansible/ops_tool.py", line 367, in run
updated_keys_by_host = _get_host_key_map(lines)
File "/Users/grahamherceg/code/commcare-cloud/src/commcare_cloud/commands/ansible/ops_tool.py", line 411, in _get_host_key_map
csv_hosts, …
```
> Subprocess stdout and stderr return bytes-like objects

- control/init.sh
When users ssh into a machine, the init script still defaults to python 2. This will use the `cchq` venv running python 3, and install it if it does not exist.
None
> Default to cchq (python 3 venv) in init script

- environments/staging/app-processes.yml
Staging's usage is low enough that this threshold gets in the way of the QA team.
staging
> Lowered default pillow batch size on staging

- environments/india/terraform.yml
- environments/production/terraform.yml
- environments/staging/terraform.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/elasticache-cluster/CHANGELOG.md
- src/commcare_cloud/terraform/modules/elasticache-cluster/main.tf
- src/commcare_cloud/terraform/modules/elasticache-cluster/output.tf
- src/commcare_cloud/terraform/modules/elasticache-cluster/variables.tf
- src/commcare_cloud/terraform/modules/r53-private-zone-create-update/main.tf
- src/commcare_cloud/terraform/modules/r53-private-zone-create-update/variables.tf
The latest Elasticache-cluster terraform module & other files can create AWS Elasticache-cluster disable mode in Staging environment. Present, it can supports for cluster-disabled mode only.
Here, we added "create option" in terraform [environments/staging/terraform.yml] environments files and creates infra based on create key value i.e. yes|no.
Updated files other than terraform module:
environments/staging/terraform.yml
environments/india/terraform.yml
environments/production/terraform.yml
file - src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2 : updated file to create commcarehq.tf with latest attributes
file - src/commcare_cloud/environment/schemas/terraform.py: updated file to get the latest values from environments-terraform files.[ example: …
> Elasticache-cluster terraform module update: support for Elasticache-cluster disabled ref. SAAS-11653 (after rebase)

- environments/staging/public.yml
Information about changes:
This change [environments/staging/public.yml] can update the redis_host URL in services configuration.
Here, I am adding the cluster end-point (internal hosted-zone record) in place of redis URL.
These changes are related to the STAGING environment only.
> updating REDIS_HOST and WS4REDIS_CONNECTION_HOST with Elasticache end-point: Staging env.

- src/commcare_cloud/fab/operations/release.py
We had a P1 triggered on the date this PR was created which resulted in all but the current release folder being deleted. As a result, when a rollback was attempted there was no other release to roll back to
Two key points:
- added a safeguard check to make sure that if less than three valid releases are found, we do not delete previous releases ever
- when `use_sudo=True` on `files.contains`, we should always use `shell=True`
all
> Fix Clean Releases

- src/commcare_cloud/fab/fabfile.py
We currently never checkpoint the completion of clean releases so `resume` will always run it again even if it has finished. That caused issues today, and is generally unnecessary, so this should properly checkpoint it, by caching state on completion rather than before attempting tasks.
> cache state after clean releases

- environments/india/terraform.yml
- environments/production/terraform.yml
Currently on master running
```
cchq production terraform init
```
results in
```
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: Error parsing /Users/danielroberts/dimagi/commcare-cloud/environments/production/.generated-terraform/commcarehq.tf: At 4293:17: Unknown token: 4293:17 IDENT null
```
Same with `cchq india terraform init`.
@rameshganne
production
> Fix terraform error when route53 disabled

- src/commcare_cloud/alias.py
Resolve error in Django checks phase of `cchq ... update-config`. Given the location of the issue, I'm assuming could have affected other commands as well.
```
File "src/commcare_cloud/cli_utils.py", line 96, in <genexpr>
command = ' '.join(shlex_quote(arg) for arg in command)
File "/usr/lib/python3.6/shlex.py", line 314, in quote
if _find_unsafe(s) is None:
TypeError: expected string or bytes-like object
```
In this case the `arg` was a `ansible.inventory.host.Host` object, which must be converted to a string before it is passed to `shlex_quote`.
all / none specifically
> Fix command printing

- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
Using this DS for flyway should resolve the session locking issue we've been experiencing: https://dimagi-dev.atlassian.net/browse/SAAS-11716
We have pgbouncer  configured in transaction pooling model which means that multiple connections from different Formplayer machines could end up using the same PG connection (session). It also means that successive transactions from Flyway could end up using different connections which can result in locks left hanging:
1: *connection A*: SELECT pg_try_advisory_lock(lockNum);
2. *connection X*: Perform some other queries
3. *connection B*: SELECT pg_advisory_unlock(lockNum);
If step 1 and 3 do not get assigned the same DB connection from pgbouncer then the lock will be left in the lock state until either  pgbouncer closes the connection or perhaps …
> use separate DS for flyway which bypasses pgbounce

- environments/production/app-processes.yml
Setting dedicated_migration_process to False as we have observed that for process_nums (case-SQL-15 and form-SQL-15, 31)  the `changes to process by Kafka Partition` is consistently growing after deploying these change. 
We will investigate more on this. thanks.
> setting dedicated_migration_process to False

- src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.ini.j2
- src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
These are just generic things that help when configuring pgbouncer especially the ones related to pl/proxy. The logic fix generalizes better to other situations, and the tag just makes it easier to update the pg_hba when needed to accommodate a new pgbouncer machine if necessary.
None
> Changes that help when reconfiguring pgbouncer

- src/commcare_cloud/ansible/requirements.yml
This is a temporary change while we wait for https://github.com/andrewrothstein/ansible-couchdb-cluster/pull/12 to be merged and the published version on galaxy to be updated.
> Update couchdb-cluster role galaxy requirement

- src/commcare_cloud/commands/terraform/aws.py
aws-cli seems to return the timestamp in ISO-8601 format, let's use
dateutil.parser to convert it in a datetime.datetime object.
None
> Fix parsing of aws-cli expiration timestamp

- src/commcare_cloud/ansible/roles/pgbouncer/defaults/main.yml
- src/commcare_cloud/ansible/roles/pgbouncer/handlers/main.yml
- src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml
Use reload instead of restart for already running processes when
scaling up or down, to avoid downtime.
All
> PgBouncer multiprocess use reload

- src/commcare_cloud/ansible/requirements.yml
Update andrewrothstein.couchdb-cluster to include https://github.com/dimagi/ansible-couchdb-cluster/commit/0a43d64e4336a49c5d7eabb13f3b3e3820be43ec, which was also submitted upstream in https://github.com/andrewrothstein/ansible-couchdb-cluster/pull/13
Tested on Python 2 and 3
n/a
> Fix for couchdb_password_hash() in couchdb-cluster

- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
Add location and mappings to nginx config to cache app resources on the proxy. This is something we had set up for ICDS which protects the Django workers from multiple requests for the same resource.
all
> add caching at the proxy for app resource downloads

- environments/production/public.yml
- restrict to low traffic time window
- raise the threshold to compact
- disable parallel_view_compaction
From https://docs.couchdb.org/en/2.3.1/config/compaction.html
> parallel_view_compaction: If set to true, the database and its views are compacted in parallel. This is only useful on certain setups, like for example when the database and view index directories point to different disks. It defaults to false.
production
> Change production couchdb compaction settings

- src/commcare_cloud/ansible/roles/postgresql_base/tasks/set_up_dbs.yml
On Python 3 the item (ansible_loop_var) was the dict_values object unless explicitly converted to a list. Apparently Ansible wraps non-list objects in a list.
Before:
```
item=dict_values([{'a': 1}, {'b': 2}])
```
After:
```
item={'a': 1}
item={'b': 2}
```
On Python 2 the conversion is implicit, but explicit conversion works too. Before and after:
```
item={'a': 1}
item={'b': 2}
```
The bug was verified and fix tested locally against Python 2 and 3.
> Fix iteration over dict values

- src/commcare_cloud/ansible/roles/nginx/templates/default.j2
- src/commcare_cloud/ansible/roles/nginx/templates/site.j2
https://dimagi-dev.atlassian.net/browse/SAAS-11731
deploy this PR 
Change the Target group end point to /healthz
change success . code from . 302 to 200
and then set  the interval . to 29s
Observe the status of health . check . 
set the interval back to 30s
Staging [ It first need to be tested here]
India 
Production
> nginx health check endpoint

- src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml
- src/commcare_cloud/ansible/roles/pgbouncer/templates/tmpfiles.postgresql-pgbouncer.conf.j2
Add tmpfiles configuration for pgbouncer-multiprocess socket directories,
which are otherwise deleted by systemd-tmpfiles.
All
> PgBouncer multiprocess tmpfiles configuration

- src/commcare_cloud/commands/ansible/ops_tool.py
The encoding parameter was introduced in 3.6.
> Py2 compat: universal_newlines instead of encoding

- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
The DimagiBlockRules rule in the AWS WAF frontend-waf ACL should come first
in order to block any IP address manually added to the related IP sets
regardless of paths explicitly permitted in other rules.
Fix: https://dimagi-dev.atlassian.net/browse/SAAS-11562
All
> Prioritize BlockRules in AWS WAF frontend ACL

- environments/production/terraform.yml
This may help autovacuum go faster on massive TOAST table for `formplayer_sessions`. https://dimagi-dev.atlassian.net/browse/SAAS-11816
production
> Increase maintenance_work_mem for formplayer db instance (pgmain0-production)

- environments/india/terraform.yml
In the process of Redis migration, I am adding a AWS Elasticache resource in India env. This resource can have a primary node and a read replica node. We are using Multi-AZ & Auto-failover options for Elasticache cluster. 
Primary & Read replica node type: cache.r5.large ( 2 vCPU & 13.07 GiB memory )
At the completion of Elasticache cluster creation, these changes can add Route-53 private hosted zone [ india.commcare.local ] & create record [ redis.india.commcare.local ] with value of elasticache primary end-point. 
> Redis migration - adding elasticache resource in India env. ref: SAAS-11719

- environments/india/public.yml
This change [environments/india/public.yml] can update the redis_host URL in the services configuration.
Here, I am adding the cluster end-point (an internal hosted-zone record) in place of the Redis URL. I am also removing custom nameservers IPs from the "resolv.conf" file.
These changes are related to the STAGING environment only.
Ref: SAAS-11824
> removing custom nameservers & updating REDIS_HOST and WS4REDIS_CONNECTION_HOST with Elasticache end-point: India env.

- src/commcare_cloud/ansible/deploy_logstash.yml
- src/commcare_cloud/ansible/requirements.yml
_filebeat.yml.j2_ installed by the [_geerlingguy.filebeat_](https://github.com/geerlingguy/ansible-role-filebeat) role uses a variable called `filebeat_inputs` to populate the config file. [`filebeat_inputs`](https://github.com/dimagi/commcare-cloud/blob/690e8a96fcc6b52a481282987b0f2f76763e21fe/environments/staging/public.yml#L31-L35) is set in our environments' _public.yml_, but it's the wrong format for geerlingguy's role, which means the config file is initially configured incorrectly. The first time filebeat tries to start it fails due to bad config:
```
Exiting: Failed to start crawler: starting input failed: Error while initializing input: No paths were defined for input accessing 'filebeat.inputs.0' (source:'/etc/filebeat/filebeat.yml')
```
The …
> Remove redundant geerlingguy.filebeat role

- environments/india/terraform.yml
As per datadog historical data [ last 13 months] related to India env Redis instance, The maximum used memory is 5.72 GiB out of usable memory 13.52 GiB. In this case, we can use cache.m5.large which is having 2 vCPU & 6.38 GiB memory. Presently, we are using an r5.large [ 2 vCPU & 16 GiB memory ] instance for Redis service.
We can scale up the Elasticache cluster node type based on service metrics like Memory usage, Evictions, Swap Usage & Memory fragmentation ratio.
> Updating elasticache cluster node type - India env only

- src/commcare_cloud/ansible/deploy_common.yml
Here, I am updating the deploy_common playbook to update the symbolic link of /etc/resolv.conf file. 
Updated file: deploy_common.yml
**/run/systemd/resolve/resolv.conf** - this file contains the nameserver & domain search details. This update does not impact the public-domain resolutions. It can also resolve Route-53 private hosted-zones.
These changes can update the symbolic link for all environments { **Staging, Prod & India** }
> internal domain: updating resolv.conf symbolic link for OS-distribution Ubuntu

- src/commcare_cloud/ansible/roles/cloudwatch_logs/handlers/main.yml
- src/commcare_cloud/ansible/roles/cloudwatch_logs/tasks/main.yml
On a fresh run the config file would be created and its status is not changed, so the reload will not happen. I couldn't find a way to run if it changed or was created, but removing it should also work and we always reload.  
I think the better thing to do is to use handlers and notify a reload, but that would be a bigger refactor.
> cloudwatch_logs remove config file check

- changelog/0041-python3-support.yml
- control/check_install.sh
- control/init.sh
- docs/changelog/0041-python3-support.md
- docs/commcare-cloud/commands/index.md
- docs/setup/installation.md
- docs/setup/manual_installation.md
- docs/setup/new_environment.md
- provisioning/control.sh
- src/commcare_cloud/ansible/roles/python/tasks/main.yml
- src/commcare_cloud/commands/ansible/ansible_playbook.py
- src/commcare_cloud/commcare_cloud.py
Since we plan to no longer support Python 2 in the very near future this should recommend to use Python 3 (specifically 3.6). Feel free to improve wording.
None
> Recommend python 3.6 for Manual Installation

- environments/production/app-processes.yml
- src/commcare_cloud/environment/schemas/app_processes.py
Dedicated queue for running USH background tasks to avoid blocking the existing queues. Currently the only task that would use this is the USH formplayer restore priming.
@calellowitz can I have moved the user import tasks to use this queue as well: https://github.com/dimagi/commcare-hq/pull/29181
I think this is safe to do since the user import tasks shouldn't be running in parallel with the formplayer priming tasks.
I've left the `user_import_queue` config in place for now to make the changes easier to roll out / roll back.
production
> celery queue for ush background tasks

- environments/production/terraform.yml
As per datadog historical data [ last 13 months] related to Production env Redis instance, The maximum used memory is 53.44 GiB out of usable memory 128 GiB and average used memory 14.75 GiB & 20.75 GiB per 6 months. 
In this case, we can use cache.r5.2xlarge which is having 8 vCPU & 52.82 GiB memory. Presently, we are using an r5.4xlarge [ 16 vCPU & 128 GiB memory ] instance for Redis service.
We are going to use three Elasticache nodes for high availability & launching these in different availability zones within the region.
We can scale up the Elasticache cluster node type based on service metrics like Memory usage, Evictions, Swap Usage & Memory fragmentation ratio.
ref: SAAS-11834
> Adding Elasticache cluster node type & other attributes - Prod env only

- environments/production/public.yml
This change [environments/production/public.yml] can update the redis_host URL in the services configuration.
Here, I am adding the cluster end-point (an internal hosted-zone record) in place of the Redis URL.
These changes are related to the Production environment only.
Ref: SAAS-11511
> Updating redis_host & ws4redis_connection_host endpoint with Elasticache-Production env

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
- src/commcare_cloud/ansible/roles/formplayer/templates/logback-spring.xml.j2
- src/commcare_cloud/ansible/roles/formplayer/templates/sentry.properties.j2
Changes to formplayer config for sentry upgrade.
This needs to be rolled out in conjunction with the formplayer changes: https://github.com/dimagi/formplayer/pull/886
The logging config changes particularly will error if the old version of formplayer is running.
Is it worth trying to split this up into two:
1. Deploy config changes
2. Deploy formpalyer
3. Deploy logging changes (with restart)
all
> update config and logging for formplayer sentry upgrade

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/production/terraform.yml
I am doing a instance termination process for **_redis0-production_** (i-055334f56a475b851). We had completed migration process (redis - elasticache ) in prod env. 
We are not using redis0-production [**_i-055334f56a475b851_**] host for redis db service.
ref: SAAS-11906
> removing redis0-production instance from inventory & terraform resource list. ref: SAAS-11906

- environments/production/public.yml
Initially tested on [this PR](https://github.com/dimagi/commcare-cloud/pull/4536) on staging, but also just tested a branch with an empty `detailed_tag_names` list on staging to ensure it behaves as expected which it does. 
Rolling this out empty so that we can first add domains, then update which tags are considered "detailed" after. This will allow for a smooth transition from a reporting metrics side since `form_name` is already deployed. 
Production
> Add detailed tagging domains to production

- environments/india/terraform.yml
- environments/production/terraform.yml
- environments/staging/terraform.yml
- src/commcare_cloud/ansible/requirements.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/efs_file_system/CHANGELOG.md
- src/commcare_cloud/terraform/modules/efs_file_system/README.md
- src/commcare_cloud/terraform/modules/efs_file_system/main.tf
- src/commcare_cloud/terraform/modules/efs_file_system/mount-point/README.md
- src/commcare_cloud/terraform/modules/efs_file_system/mount-point/main.tf
- src/commcare_cloud/terraform/modules/efs_file_system/mount-point/output.tf
- src/commcare_cloud/terraform/modules/efs_file_system/mount-point/variables.tf
- src/commcare_cloud/terraform/modules/efs_file_system/output.tf
- src/commcare_cloud/terraform/modules/efs_file_system/variables.tf
- src/commcare_cloud/terraform/modules/r53-record-create-update/main.tf
- src/commcare_cloud/terraform/modules/r53-record-create-update/variables.tf
I am adding the "**_efs_file_system_**" terraform module to create an AWS EFS file system with access-point & mount targets. 
In the process of EFS creation in environments, I am also updating template, schema & resource files. 
Here, Based on provided availability-zones in the resource file(terraform.yml), we are creating EFS mount targets. 
About the EFS file system, access-point, mount-target & internal DNS map, we are providing options-based flags to create.
Example:     
create: yes
    create_access: no
    create_mount: yes
    create_record: yes
Verified & Created EFS resource in Staging, India & Production environments.
updating file : commcare-cloud/src/commcare_cloud/ansible/requirements.yml 
reference: https://galaxy.ansible.com/cloudalchemy/node_exporter
ref: Due to …
> Updated required files to create EFS,Access-point & mount-targets - all environments

- src/commcare_cloud/fab/utils.py
This should make the changes more readable when they are copied into an email / slack / text doc
> prepend PR with '- ' to make it more readable when copied

- environments/india/public.yml
- environments/swiss/public.yml
These changes have [been on staging](https://github.com/dimagi/commcare-cloud/pull/4279) for awhile now and should be safe to roll out. Will start with India and Swiss and then rollout to Production.
India, Swiss
> Enable django security middleware on swiss and india

- environments/production/terraform.yml
production.
Downsizing pg0-formplayer RDS instance from m5.8xlarge to m5.4xlarge. 
We have separated formplayer db from pg0-main RDS instance and also routed formplayer requests to new instance.
> downsizing prod pg0-formplayer RDS instance 

- src/commcare_cloud/commcare_cloud.py
Change current warning message to specify Python 2 is no longer supported and remove the option to use a flag to run Python 2.
> Remove Python 2 support

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/secrets.py
There are lots of domains to add to the `detailed_tagging_domains` secret and this will make my life a bit easier. Most secrets are not lists so this may not be that useful long term, but is definitely useful now. 
None
> Add append and remove operations to secrets command

- .travis.yml
Python 2 is no longer supported on commcare-cloud.
I've checked for specific python 2 tests by searching for `six.PY[23]`, `sys.version_info` and `platform.python_version()`. 
None
> Stop running tests on Python 2.7

- src/commcare_cloud/ansible/roles/kafka/tasks/main.yml
- src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
You must either add a leading zero so that Ansible's YAML parser knows it is an octal number (like 0644 or 01777) or quote it (like '644' or '1777') so Ansible receives a string and can do its own conversion from string into number.
Previously seen in ansible output
```diff
TASK [postgresql_base : Configure service limits] ******************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
{
-    "mode": "0644",
+    "mode": "01204",
"path": "/etc/systemd/system/postgresql@.service.d/limits.conf"
}
```
Might be related to the Python 3 upgrade?
> Fix bad permissions modes

- environments/staging/postgresql.yml
- environments/staging/public.yml
- src/commcare_cloud/environment/constants.py
- src/commcare_cloud/environment/schemas/postgresql.py
- tests/test_envs/2018-04-04-development-snapshot/.generated.yml
- tests/test_envs/2018-04-04-enikshay-snapshot/.generated.yml
- tests/test_envs/2018-04-04-icds-new-snapshot/.generated.yml
- tests/test_envs/2018-04-04-pna-snapshot/.generated.yml
- tests/test_envs/2018-04-04-production-snapshot/.generated.yml
- tests/test_envs/2018-04-04-production-snapshot/postgresql.yml
- tests/test_envs/2018-04-04-softlayer-snapshot/.generated.yml
- tests/test_envs/2018-04-04-staging-snapshot/.generated.yml
- tests/test_envs/2018-04-04-swiss-snapshot/.generated.yml
- tests/test_postgresql_config.py
Prepare to write auditcare data to PostgreSQL instead of CouchDB. This mirrors configuration that will be used on prod: separate DB, custom routing. Unlike prod, it uses the same pg host as other dbs (prod will use a separate RDS instance).
https://dimagi-dev.atlassian.net/browse/SAAS-11381
staging
> Auditcare db and routing setting for staging

- src/commcare_cloud/ansible/roles/postgresql_base/tasks/set_up_dbs.yml
set_up_dbs.yml on remote db may have been broken by https://github.com/dimagi/commcare-cloud/commit/7b5a7f456ea16fde7c95428bc1aedd7fe2127cf9
> Do not run service check on remote database

- environments/staging/aws-resources.yml
- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
- environments/staging/postgresql.yml
- environments/staging/terraform.yml
Staging. 
updated pgbouncer URL to routed Via a new Network Load Balancer. This helps in handling high availability and routing requests to multiple servers.
> moving main, ucr and synclogs routing via NLB

- environments/staging/aws-resources.yml
- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
- environments/staging/terraform.yml
I am doing a instance termination process for redis2-staging ( i-0ba9234c3f9c17993). We had completed migration process (redis - elasticache ) & NFS to EFS in Staging env.
We are not using redis2-staging ( i-0ba9234c3f9c17993) host for redis db & NFS service.
ref: SAAS-11830
> terminating redis2-staging(shared_dir_host) & removing from resources list.

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
Just something I found while looking at https://dimagi.github.io/commcare-cloud/commcare-cloud/commands/#tmux
None
> Fix typos in the docs for tmux command

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/production/postgresql.yml
- environments/production/terraform.yml
Production.
updated pgbouncer URL to routed Via a new Network Load Balancer. This helps in handling high availability and routing requests to multiple servers.
> Production - routing pgbouncer traffic via NLB for main, ucr and synclogs dbs 

- src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.ini.j2
and increase tcp_keepcnt by the same factor.
The logic for lowering tcp_keepidle is that we need to send keepalive packets
to keep the NLB from timing out. The logic for raising tcp_keepcnt is to keep
the total length of time during which we are willing to send a keepalive the same.
I believe this to be the cause of the increased (but low) rate of postgres errors since we switched a number of pgbouncer connections to go through an AWS NLB: https://app.datadoghq.com/dashboard/g9s-pw6-tpg/hq-vitals?from_ts=1616094587232&fullscreen_end_ts=1616268783670&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1616095983670&fullscreen_widget=200684876&live=true&to_ts=1616267387232. I got the idea from a web search of the error I found in …
> Change pgbouncer tcp_keepidle to be less than AWS NLBs hard timeout

- src/commcare_cloud/environment/schemas/meta.py
- src/commcare_cloud/fab/utils.py
The use of a password in this context has been deprecated and we need to use our token to login when deploying, not a password.
From what I've experienced, following the current text and putting a token in for the first field ("Github username or token") does not work.
None
> Update password text to token for Github

- src/commcare_cloud/ansible/deploy_commcarehq.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
Add the needed "DigiCert SHA2 Secure Server CA" intermediate
certificate to certifi, in order to fix the validation error
with smspro.mtn.ci until they can fix their configuration to
serve the complete certificate chain.
https://dimagi-dev.atlassian.net/browse/SAAS-11999
All
> Add additional certificate to certifi for celery

- src/commcare_cloud/environment/schemas/meta.py
- src/commcare_cloud/fab/utils.py
Take 2. A premature merge of [this PR](https://github.com/dimagi/commcare-cloud/pull/4601) resulted in an issue and needed to be reverted. I've pulled in the commits from that PR into the first commit here, and the second commit fixes the issue originally seen (which was the credentials not being asked for).
@snopoke I know the logic for forcing a token was in question during the last PR, and I've changed it back to an `and` statement because I believe that is what we want. You mentioned "The intention is to allow blank tokens unless 'force=true' in which case a token is required" so if force is true, regardless of the value of `GITHUB_TOKEN`, we want to fetch the token from the config file or ask the user again.
> Only ask for github token (not username)

- environments/staging/proxy.yml
- environments/staging/public.yml
[Classic Ticket](https://dimagi-dev.atlassian.net/browse/SAAS-11207)
Overcomplicated this with [this PR](https://github.com/dimagi/commcare-cloud/pull/4537) but this is a much more promising and simple solution. We want the nginx value and django value to match, and this is the easiest way to maintain that moving forward. I'll roll out to other environments when we are sure this is error free (should be pretty safe).
I tested locally by running `cchq staging update-config --branch=gh/set-value-in-proxy` after updating the value to 500 and saw that the django setting `SECURE_HSTS_SECONDS` was updated as well.
Staging
> Reference proxy hsts value for django setting

- environments/india/proxy.yml
- environments/india/public.yml
- environments/production/public.yml
- environments/swiss/proxy.yml
- environments/swiss/public.yml
Followup to [this PR](https://github.com/dimagi/commcare-cloud/pull/4621), updates these envs to reference the proxy value for hsts_max_age. Worth noting all of these environments have already had this value set to 300 in django, so adding it to the proxy _should_ not change anything. 
Production, India, Swiss
> Reference proxy hsts max age value for django settings

- environments/production/app-processes.yml
Fewer gevent threads, more workers.
We have a hypothesis that too many gevent threads each running long tasks
causes the BrokenPipeError that halted some of the workers
https://docs.google.com/document/d/1-zJLGSgWTNYbqVdmjDCjCJgJYd1ZC_gptGDIgJTsWIw/edit
production
> Increase reminder_case_update_queue concurrency by 88% on production

- environments/production/postgresql.yml
- environments/production/terraform.yml
Production
Adding two instances as target machines for pgmain, pgsynclogs and pgucr NLB's. 
This way there is redundancy and we can swap in and out pgbouncer nodes without downtime for those dbs. 
We will be running cchq <env> terraform apply command for specific targets. 
@dannyroberts Please let me know if I have to run update-config as well. 
Thanks.
> adding pgbouncer6, pgbouncer7 as targets for pgmain, pgucr and pgsynclog NLB

- environments/india/proxy.yml
- environments/production/proxy.yml
- environments/staging/proxy.yml
- environments/swiss/proxy.yml
Max age is the time the browser will remember that our site is only accessible via HTTPS. Previously was 5 minutes, and this PR bumps to 24 hours. The recommended value is ~1 year.
Production, India, Swiss, Staging
> Bump hsts max age to 24 hours

- environments/india/app-processes.yml
- environments/production/app-processes.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/swiss/app-processes.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2
- src/commcare_cloud/environment/schemas/app_processes.py
- src/commcare_cloud/environmental-defaults/app-processes.yml
include -XX:+UseG1GC and -XX:+UseStringDeduplication in defaults
increase heap size in production (31g from 30g)
add -XX:+ParallelRefProcEnabled
add -XX:G1HeapRegionSize (set based on the heap size - default: 2m, production: 16m, india: 8m, swiss: 1m)
change -XX:MaxMetaspaceSize (512m from 128m)
https://dimagi-dev.atlassian.net/browse/SAAS-11943
All
> New settings for formplayer java process

- src/commcare_cloud/commands/deploy.py
- src/commcare_cloud/events.py
- src/commcare_cloud/fab/fabfile.py
- src/commcare_cloud/fab/operations/release.py
Move `publish_deploy_event` to a common place and call it on successful formplayer release.
The first commit is minor lint cleanup.
Deploy events are currently only enabled on staging
> Run QA tests on formplayer deploy

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
In rare cases this could delete /opt/formplayer/logs when no logs were written for a while, which could cause issues.
I played around with these commands and I think they work, but we'd need to test it more before deploying to production.
> Prevent cleanup from deleting formplayer log files

- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
This setting was added as part of the SQL auditcare work. It is useful for tracing requests across the system.
Also remove an obsolete setting.
> Add localsettings.AUDIT_TRACE_ID_HEADER

- environments/production/app-processes.yml
During the course of https://dimagi-dev.atlassian.net/browse/SAAS-12077, we discovered that a concurrency of 3 per process (for a total concurrency of 3 x 6 = 12) was enough to get through most of a workday's worth of backlogged process_repeat_record tasks in less than an hour. That should be more than enough to keep up with the steady state while creating a little bit of elasticity during very high submission periods.
production
> Drastically lower concurrency for repeat_record_queue in production

- environments/production/app-processes.yml
Reverts dimagi/commcare-cloud#4658
This was applied Apr 15 during https://dimagi-dev.atlassian.net/browse/SAAS-12077.
> Revert "Lower concurrency for repeat_record_queue in production to 1 x 6"

- src/commcare_cloud/ansible/roles/nginx/templates/site.j2
- src/commcare_cloud/ansible/roles/nginx/vars/couchdb2.yml
e.g.
```
cchq <env> ap deploy_couchdb2.yml --limit couchdb2_proxy --tags=proxy -e couch_excluded_hosts=<couch_host>
```
Tooling created to make restarting couch nodes one at a time without downtime simpler during https://dimagi-dev.atlassian.net/browse/SAAS-12077.
production
> Add way to exclude couch host from couch proxy

- src/commcare_cloud/ansible/roles/couchdb2/templates/extras.ini.j2
Applied during https://dimagi-dev.atlassian.net/browse/SAAS-12077
production
> Increase production couch os_process_timeout to 20s

- src/commcare_cloud/commands/deploy/formplayer.py
- src/commcare_cloud/commands/deploy/sentry.py
- src/commcare_cloud/fab/deploy_diff.py
[USH-935](https://dimagi-dev.atlassian.net/browse/USH-935)
Include full commit data in sentry releases. This should allow Sentry to give more accurate 'suspect commits': https://docs.sentry.io/product/releases/setup/manual-setup-releases/#using-the-api
> add commit data to sentry releases

- docs/setup/new_environment.md
Step: 'Add a new CommCare build'
Refer user to new add_commcare_build management command instead of directing user to /builds/edit/
See ticket [here](https://dimagi-dev.atlassian.net/browse/SC-751).
> Update new_environment.md step:

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/deploy/command.py
I thought this had previously been possible. Is this a good idea or will it not work? I think it's supposed to be the default behavior if no component is specified and the environment metadata has `always_deploy_formplayer: true`, but it doesn't look like that option is used by any of our environments.
Motivation: the deploy process now specifies that both HQ and formplayer should be deployed by on-call SaaS developer. Would be nice to be able to kick that off with a single command.
n/a
> Add option to deploy both commcare and formplayer

- src/commcare_cloud/ansible/deploy_common.yml
To resolve the below listed issue, updating it to check /etc/resolv.conf status: Path exists and is a symlink
verified in staging env.
ref: https://forum.dimagi.com/t/update-config-failing/8171/9
> checking resolv.conf status - Path exists and is a symlink

- environments/staging/fab-settings.yml
- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/deploy/formplayer.py
- src/commcare_cloud/commands/deploy/sentry.py
- src/commcare_cloud/environment/schemas/fab_settings.py
- src/commcare_cloud/fab/deploy_diff.py
See https://github.com/dimagi/commcare-cloud/pull/4693#issuecomment-831722189
Since the staging branch is rebuilt and force pushed frequently the concept of a diff is misleading since the branch history is not linear. This disabled the generation of the deploy diff for staging.
> disable deploy diffs for staging

- src/commcare_cloud/commands/deploy/command.py
Previously `Deploy.run` returned immediately after commcare (HQ) deploy, even if both commcare and formplayer were meant to be deployed.
> Deploy formplayer after commcare

- docs/howto/new-machine.md
- docs/index.md
This is documented internally: https://confluence.dimagi.com/pages/viewpage.action?spaceKey=internal&title=How+to+create+a+new+machine+in+an+AWS+environment
But if external people are adding new machines, the process is hard to figure out.
> Add docs on adding a new machine

- environments/staging/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12091
Use newer cipher set `ELBSecurityPolicy-FS-1-2-Res-2020-10` on staging which removes CBC-based ciphers
staging only
> Use newer cipher set ELBSecurityPolicy-FS-1-2-Res-2020-10 on staging

- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/deploy/formplayer.py
- src/commcare_cloud/commands/deploy/utils.py
https://dimagi-dev.atlassian.net/browse/SAAS-12177
We want to be notified when something is deployed outside of the normal deploy processes eg -  hotfix deploys. 
The change updates `announce_deploy_start`. Now if a branch is deployed with `--comcare-rev` the deploy start email subject will be updated. 
This will affect all environments
> Update announce deploy

- environments/staging/aws-resources.yml
- environments/staging/inventory.ini
- environments/staging/inventory.ini.j2
- environments/staging/postgresql.yml
- environments/staging/terraform.yml
Staging
Configured form_processing partitions to route traffic via NLB with pgbouncer0 as the target node. 
Updated shards configuration to use NLB URL instead of pgproxy2 ip.
> adding pgshard_nlb for form_processing partitions

- src/commcare_cloud/cli_utils.py
- src/commcare_cloud/commands/ansible/ansible_playbook.py
- src/commcare_cloud/commands/deploy/command.py
- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/deploy/formplayer.py
- src/commcare_cloud/commands/deploy/utils.py
- src/commcare_cloud/commands/inventory_lookup/getinventory.py
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
- src/commcare_cloud/commands/terraform/aws.py
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/fab/deploy_diff.py
- src/commcare_cloud/user_utils.py
- tests/__init__.py
Redo of https://github.com/dimagi/commcare-cloud/pull/4715
This is useful for checking the SSH username and giving early warning / error messages when the local SSH username differs from what's required by commcare-cloud.
First few commits are moving similar code around into a new package.
Can review by commit.
> check ssh user

- src/commcare_cloud/commands/terraform/constants.py
Ticket: https://dimagi-dev.atlassian.net/browse/INDIV-8
WAF was blocking some of the requests from this endpoint. As this endpoint allows XML kind of script to be taken from the user so it needs to be whitelisted.
relevant PR:  https://github.com/dimagi/commcare-hq/pull/29674
> White listed URL

- src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
https://dimagi-dev.atlassian.net/browse/SAAS-12204
We are getting the errors like `Error installing provider "archive": openpgp: signature made by unknown entity. & No available provider "archive" plugins are compatible with this Terraform version.`  at the time executing terraform init command in Staging, India & Prod environments. 
To resolve it, We are including archive provider version in terraform.tf.j2 file. The provided version(1.3.0) can support for terraform v11. 
The latest versions of [archive providers](https://github.com/hashicorp/terraform-provider-archive/blob/main/CHANGELOG.md) does not support for terraform v11.
> adding terraform archive provider version -1.3.0 ref: SAAS-12204

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/terraform/modules/server/iam/main.tf
- src/commcare_cloud/terraform/modules/server/iam/outputs.tf
Production Control1 server. 
@dannyroberts made small modifications to the formplayerlogbucket role. 
- Learned that a separate resource section is not required to add a policy to the role so, I removed that section and used `aws_iam_role_policy` 
- retrieving new role values using output.tf. 
- renamed the role and policy name.
```
{% if server_name == "control1-production" %}
iam_instance_profile = "${module.server_iam_role.formplayerlogbucket_instance_profile}"
{% else %}
iam_instance_profile = "${module.server_iam_role.commcare_server_instance_profile}"
{% endif %}
```
remove/comment `"iam_instance_profile"` from the lifecycle and add back after a change has been applied. 
```
file:  src/commcare_cloud/terraform/modules/server/main.tf
lifecycle {
ignore_changes = ["user_data", …
```
> modify control1-production instance role 

- src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
This was something @skodde and I noticed locally when running terraform. Removing just this one line fixes it. The error is
> Error: provider.archive: : invalid or unknown key: source
> Fix terraform v0.11 error w/ archive provider

- src/commcare_cloud/commands/deploy/sentry.py
This was causing an issue on eCHIS on deploy as github was not accessible, and the default setting was set to `True`
> Set commits to None on github error

- src/commcare_cloud/commands/deploy/command.py
- src/commcare_cloud/commands/inventory_lookup/getinventory.py
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
- tests/__init__.py
- tests/test_ssh.py
First commit from PR comment: https://github.com/dimagi/commcare-cloud/pull/4733#discussion_r636384125 I think it's extremely unlikely that there will be more than 1 `@` symbol here but in the interest of caution I've added the change.
I've also changed the `get_server_address` function to remove the `get_default_username` lookup. This may break someone's workflow if they were relying on the `COMMCARE_CLOUD_DEFAULT_USERNAME` to set their SSH username.
`COMMCARE_CLOUD_DEFAULT_USERNAME` is now only used by `get_default_username` and `get_dev_username`:
* Terraform calls `get_default_username` to specify the public key to place on new servers
* Deploy calls `get_default_username` to get the username of the user doing deploy (or announce workflows)
* `update-users` command calls …
> split at first occurrence & don't mutate username during address lookup 

- src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
- src/commcare_cloud/terraform/modules/server/iam/main.tf
Here I am placing terraform version local. Allowing ~>12.0, <12.31 versions. Suggesting to use 12.30
resolving` Error: Argument or block definition required` related to `commcare-cloud/src/commcare_cloud/terraform/modules/server/iam/main.tf`
> Adding terraform version lock [ ~>12.0, <12.31 ]

- environments/staging/terraform.yml
- src/commcare_cloud/terraform/modules/server/iam/main.tf
In the process of gp2 to gp3 volume-type, Updating EBS volume-type (gp2 --> gp3) to proxy-servers & web-workers in staging env.
> Updating EBS volume-type (gp2 --> gp3) to proxy-servers & web-workers in staging env

- src/commcare_cloud/terraform/modules/network/main.tf
Staging 
Allowing 6432 port from DB-private-subnets. This is to fix the NLB connectivity issue from the pgproxy2 machine.
> adding ingress rule for db-private-sg

- src/commcare_cloud/commands/terraform/constants.py
See route annotation PR [here](https://github.com/dimagi/commcare-hq/pull/29753).
All
This PR contains changes which I did not make but were on CCHQ master when I executed `./manage.py list_waf_allow_patterns` (I pulled master before executing). I added the relevant reviewers for the other changes.
> Add WAF routes to terraform const.py

- environments/production/app-processes.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12291?focusedCommentId=146855
Adding this temporarily to reprocess Case Search pillows as the index was down. The case-search pillow [checkpoint](url) was reset to case-pillow's [Friday checkpoint](https://www.commcarehq.org/admin/hqadmin/historicalpillowcheckpoint/58597/change/?_changelist_filters=q%3Dcase-pillow-hqcases_2016-03-04-case_search_2018-05-29-messaging-sync).
@snopoke @calellowitz
> Add CaseSearch only pillow to prod

- commcare-cloud-bootstrap/environment/private.yml.j2
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
- src/commcare_cloud/environment/secrets/backends/ansible_vault/tests/expected-generated-variables.yml
- src/commcare_cloud/environment/secrets/backends/aws_secrets/tests/expected-generated-variables.yml
- src/commcare_cloud/environment/secrets/secrets.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12284
Now that feature flags are available in formplayer, detailed tagging domains do not need to be stored in secrets. This PR removes all references to detailed tagging domains, but leaves the detailed tags themselves as those are still applied at this level.
> Remove references to detailed tagging domains

- environments/production/app-processes.yml
Reverts dimagi/commcare-cloud#4767
@calellowitz FYI you can use this to roll out the pillow to do the extra backfilling:
```
cchq production update-supervisor-confs
```
Then to reset the checkpoint:
```
{
"CaseSearchToElasticsearchPillow": "sequence from the historical checkpoint"
}
python manage.py fix_checkpoints_from_file checkpoint.json
```
> Revert "Revert "Add CaseSearch only pillow to prod""

- environments/production/public.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12284
This would make it so that a domain needs to have the detailed tagging feature flag enabled in order to collect metrics related to these 2 tags.
Prod
> Add formplayer_detailed_tags on prod

- environments/_users/dimagi-support.yml
- environments/_users/dimagi.yml
We can add these users back to staging if/when needed, but unfortunately our tooling (with the whole present/absent thing) doesn't make it easy to do that in one step. Once it's applied we can clean it up.
> Remove users

- requirements.txt
Reverts dimagi/commcare-cloud#4771
boto3 and requests also need to be upgraded for this to work, but the `datadog==0.2.0` pin in `setup.py` is preventing that. It's unclear if it is safe to upgrade `datadog` to a more recent version.
> Revert "Bump urllib3 from 1.25.10 to 1.26.5"

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/terraform/modules/server/iam/main.tf
- src/commcare_cloud/terraform/modules/server/iam/variables.tf
There may be discrepancies between the environment name we set in
terraform and the actual name of the environment, so let's use
account_alias instead as the prefix for the secrets.
All
> Fix CommCareSecretsAccess target prefix

- environments/staging/terraform.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
In the process of v12 validation & testing, I am updating EFS attribute `transition_to_ia`  from staging resource file & removing `{% if not loop.first %}, {% endif %}`  from template file.
> updated EFS-staging transition_to_ia & template file to add multi EFS ref:SAAS-12263

- environments/india/terraform.yml
India. 
We switched to a higher instance when we were running some migrations on India env. It's completed, so we are rolling back to the previous instance type.
> rolling back to t3.small since the memory requirement has been completed

- requirements.txt
- setup.py
Reviewed [change log](https://github.com/DataDog/datadogpy/blob/master/CHANGELOG.md) and verified that we are not using any APIs with backward-incompatible changes.
This was originally done as a precursor for another library upgrade, but then after I had verified the safety of this change I realized it was not strictly required for that other upgrade. Therefore I am spinning it off as a separate PR so that work doesn't go to waste.
> Upgrade datadog client library

- docs/firefighting/index.md
https://dimagi-dev.atlassian.net/browse/SAAS-12298
The reroute example command was not correctly ended with brackets and quotes. Fixed them and added another example. 
@shyamkumarlchauhan @dannyroberts Thanks
> fixing reroute example command which was not ended correctly 

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/production/public.yml
- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12150
Production. 
Routing Couch requests via ProxyALB.
> adding couchalb_proxy to route couch traffic via ALB - Production 

- environments/staging/app-processes.yml
I believe due to multiple queues being handled by the same worker, it has been going down repeatedly, and the resolution has been to restart this worker.
This PR just extracts out the celery queue, out, which is the default queue and should be handling lots of tasks, and hence it would reduce the load on the worker.
`staging`
> Extract celery queue

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12426
Production.
After couchproxy3 machine has been stopped, couch metrics on datadog stopped reporting. Therefore, we resized the instance for now. 
cc: @shyamkumarlchauhan
> resizing couchproxy3 machine to get metrics on datadog

- src/commcare_cloud/ansible/openvpn_playbooks/mark_vpn_user_claimed.yml
Helpful check for what our team already does, namely use a password manager and randomly generated passwords of a reasonable length.
Discussion on https://dimagi-dev.atlassian.net/browse/SAAS-12455
> Have our tooling enforce 24 char minimum length for openvpn password

- environments/swiss/public.yml
Disable swiss device logs to stop daily spike of 5xx errors.
Jira: [SAAS-12451](https://dimagi-dev.atlassian.net/browse/SAAS-12451)
- swiss
> Disable swiss device logs

- src/commcare_cloud/ansible/roles/kafka/tasks/main.yml
https://dimagi-dev.atlassian.net/browse/SAAS-11220
All
Avoid restarting the Kafka service when already started in case of after-reboot.
> Make after-reboot idempotent (no restarts!)

- src/commcare_cloud/commands/ansible/ops_tool.py
- tests/test_ops_tool.py
A self-hosting partner has a `known_hosts` file that has multiple key_type-key pairs on the same line. (See **tests/test_ops_tool.py:23** `test_get_host_key_map()` for an example.)
This change is to support that. Current behavior is preserved.
No Dimagi environments are affected.
> Don't error on key_type-key pairs

- src/commcare_cloud/ansible/roles/couchdb2-preinstall/tasks/main.yml
This is the repo listed in the couchdb docs: https://docs.couchdb.org/en/stable/install/unix.html 
The previous bintray address has been sunset: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> Change the couch apt repo from bintray to jfrog

- environments/production/public.yml
[Ticket](https://dimagi-dev.atlassian.net/browse/SUPPORT-10242) and another installment of changing "user_case" to "usercase"
This now matches in hq [here](https://github.com/dimagi/commcare-hq/blob/master/custom/covid/rules/custom_criteria.py#L12) when before it was preventing this rule to run.
> Renamed user_case to usercase

- environments/production/terraform.yml
- src/commcare_cloud/commands/terraform/postgresql_units.py
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/internal_alb/main.tf
- src/commcare_cloud/terraform/modules/internal_alb/variables.tf
- src/commcare_cloud/terraform/modules/server/main.tf
Updating RDS,server,internal_alb terraform modules & templates. ref: SAAS-12440.
- updating the param value for log_min_duration_statement
- including backup_window,backup_retention,monitoring_interval and parameter value for max_connections based on original state of RDS resources
- including the temporarily ignore changes in server terraform module-level related to EBS volume-type & "BackupPlan" tag until it's managed properly
- Adding variable based attribute to internal_alb target_group : _health_check_interval_ 
Reference: https://github.com/dimagi/commcare-cloud/pull/4846
Verified on Production env. 
Review Request @dannyroberts @shyamkumarlchauhan
> Updating RDS,server,internal_alb terraform modules .ref: SAAS-12440

- environments/production/terraform.yml
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
- src/commcare_cloud/terraform/modules/server/main.tf
https://dimagi-dev.atlassian.net/browse/SAAS-12037
https://dimagi-dev.atlassian.net/browse/SAAS-11592
Adding auto-recovery, gp3 default EBS type:
- Adding **_server_auto_recovery_** option to the formplayer instance group
- Updating terraform server volume by removing EBS volume **_type_** from ignore_changes
- updating ga_alb_waf terraform module by adding **_health_check_path_**  in the ignore_changes block
- Updating default EBS volume type - **_gp3_** for all volumes [boot & secondary]
Review request: @dannyroberts @shyamkumarlchauhan 
Validated on Production.
> Adding auto-recovery, gp3 default EBS type

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
Updating secondary_volume_type default type & EFS part to create multiple file-systems
- secondary_volume_type EBS default - gp3
- removing commas(,) when we are creating EFS multiple file-systems [ identified in v12 validation process ]
https://dimagi-dev.atlassian.net/browse/SAAS-11946
https://dimagi-dev.atlassian.net/browse/SAAS-12535
review request: @shyamkumarlchauhan @dannyroberts
> updating secondary_volume_type default type & EFS part to create multiple file-systems

- environments/production/inventory.ini.j2
- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12426
Production 
Couchproxy3 server has been replaced with Aws Application Loadbalancer one month ago. 
We have moved all datadog monitoring metrics to couch11 server and we are no longer using this machine.
> terminating stopped couchproxy3 production server.

- src/commcare_cloud/commands/terraform/aws.py
https://dimagi-dev.atlassian.net/browse/SAAS-12187
Updating "commcare-cloud/src/commcare_cloud/commands/terraform/aws.py" to request instance metadata through the token.
These are the draft changes related to IMDS-v2.
> adding token based instance metadata URL- supports IMDS-v2

- environments/india/app-processes.yml
- environments/swiss/app-processes.yml
https://dimagi-dev.atlassian.net/browse/SAAS-11496
Minor. There are far fewer bulk pillows than I thought on these environments, but I still think this is worth doing. All swiss ones now have batch size of 1. I left the case and form pillows on india bulk, because I think they have enough volume there to avoid the bad situations (the swiss ones were already not bulk since they use the old and not combined form and case pillows).
India
Swiss
> use batch size of 1 for low volume bulk pillows

- control/init.sh
- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/helpers.py
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
- src/commcare_cloud/commands/terraform/aws.py
- src/commcare_cloud/commcare_cloud.py
Note: currently requires `export COMMCARE_CLOUD_USE_AWS_SSM=1` to work
This is the "main" change. This adds an alternative to using the VPN: using SSM to log onto the control machine and running all further commands from the control machine. Eventually this will be the default, but in the short term to use this functionality you will need to add `export COMMCARE_CLOUD_USE_AWS_SSM=1` to your `~/.profile` or run it once per new terminal tab you open. After that, you can just use the `cchq` command normally: `cchq staging ssh control` and `cchq --control staging deploy`, etc. all work as they did before; the difference is to do anything that request connecting to a machine other than control, you first have to run `cchq staging ssh control`, and then run the command from there.
The first …
> Add ability to use aws ssm to connect through the control machine

- environments/india/public.yml
- environments/swiss/public.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12473
This is my first attempt at making the kafka checkpoint warnings on deploy more meaningful. Retaining messages for longer should minimize the odds that the change corresponding to the last checkpoint is deleted, especially when combined with my previous PR to lower the chunk size for bulk processing in these domains.
I did a quick look at space on both machines, and total kafka data size was less than 1gb in both places
India
Swiss
> increase kafka retention on india and swiss

- environments/india/app-processes.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12473
I made a few changes to the india celery workers with this PR. To address the linked ticket, I pulled the UCR queues, and the case rule queue, two queues that can spin off very long running tasks, into their own worker so as not to affect the queues that whose throughput is more critical. Second, I increased the concurrency of the more critical workers so that clogs were less likely and would be resolved sooner. Finally, to make room for all these new workers, I cut the linked domain queue concurrency since it did not seem super necessary. I checked the resources for the india celery machines and they do have a lot of headroom, so I don't think the reduction was needed, but I do think it adds a bit of safety. 
India
> shuffle india celery queues

- src/commcare_cloud/ansible/roles/bootstrap-users/templates/sudoers.j2
where we cannot reference formplayer machines. This is basically just a syntax level change to make things work on confluence without changing the behavior elsewhere.
Found during https://dimagi-dev.atlassian.net/browse/SAAS-12551
confluence
> Fix confluence update-users

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12565
Production.
During Cost optimization planning we observed that resources are underutilized. Therefore, we have planned to right-size the instance.
> reducing rabbitmq instance size from c5.4xlarge to m5.2xlarge

- environments/india/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12563
India
During Cost optimization planning we observed that resources are underutilized. Therefore, we have planned to right-size the instance.
> India: resizing the webworkers instances from t3.2xlarge to r5a.xlarge

- src/commcare_cloud/ansible/roles/couchdb2/templates/extras.ini.j2
https://dimagi-dev.atlassian.net/browse/SAAS-12222
This makes couch compaction more aggressive (when the ratio of total to live docs is lower than the current setting).
Yes, couch calls their compaction process `smoosh`. No, I did not laugh either.
All
> lower compaction ratio

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/ansible/ops_tool.py
- src/commcare_cloud/commands/ansible/run_module.py
- src/commcare_cloud/commands/command_base.py
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
- src/commcare_cloud/commcare_cloud.py
The assumption is that for ~commands that don't have a branch arg~ some commands (django-manage, ssh, etc.) ~the branch it's run on doesn't matter that much: that's why it doesn't use the --branch mechanism to force the user to think about what branch they're on. For such commands, then,~ pulling the latest code on the control machine and re-running the install steps
is an unnecessary waste of time.
~Commands that do have the --branch option ('ansible-playbook', 'deploy', etc.) have essentially declared that they are sensitive to the latest changes. These commands will continue to trigger --control to do a full reset on the control environment as it has been doing.~
I've tested it locally with `cchq --control staging django-manage shell` and `cchq --control staging update-users` and it …
> Skip setup on --control for commands that don't need it

- src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
@dannyroberts is there a reason we need to run this during formplayer deploy?
> remove formplayer_deploy tag from datadog task

- src/commcare_cloud/fab/operations/staticfiles.py
Longstanding bug that was not affecting deploy but causing directory `{env.shared_dir_for_staticfiles}` with subdirectory `{git_hash}` to be created.
> format string with directory name

- src/commcare_cloud/fab/operations/staticfiles.py
https://dimagi-dev.atlassian.net/browse/SAAS-12555
I am not certain this would have prevented the issue in the ticket, and it is probably too late to know for sure, but it seems plausible. Specifically, I have confirmed that if copying a file is interrupted (with `cp`), a partially copied file is left, and I have confirmed that if a partial file exists in the staticfiles directory, it is not replaced with the full file when you run `collectstatic` again.
Beyond that, this seems pretty safe. I don't love that the directory is hardcoded, but we use it elsewhere, and because its hardcoded rather than interpolated there is no risk of it ending up null and trying to delete root.
> clean staticfiles before collecting

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12617
Production
Yesterday we have increased the instance size to prevent OOM errors and handle the requests. Since the requirement is completed and resources utilization is also under 20% of the total, we are switching back to the previous version of the instance type.
> switching back to r5.4xlarge from r5.8xlarge instanceType.

- src/commcare_cloud/terraform/modules/postgresql/main.tf
https://dimagi-dev.atlassian.net/browse/SAAS-11793
All
Additions to PR: https://github.com/dimagi/commcare-cloud/pull/4796
We have observed that the `create_db_subnet_group` parameter value is only considering bool value and failing due to the recent changes I have made. Therefore I changed 1, 0 to True and False and it is working as expected. 
```
Error:
The given value is not suitable for child module variable
"create_db_subnet_group" defined at
.terraform/modules/postgresql__pg0-staging.postgresql/variables.tf:251,1-34:
bool required.
```
> fixed issue with create_db_subnet_group var value mismatching.

- src/commcare_cloud/terraform/modules/server/main.tf
https://dimagi-dev.atlassian.net/browse/SAAS-12081
All
We identified that root volume tags are set to `null` when ebs_vol and ebs_vol_att state is removed and imported back to tfstate. Therefore, we have fixed it in a proper way. 
```
~ root_block_device {
delete_on_termination = true
device_name           = "/dev/sda1"
encrypted             = true
iops                  = 3000
kms_key_id            = "arn:aws:kms:us-east-1:737236193635:key/8cd2c194-9e71-492f-9b0d-7c36f49ae892"
~ tags                  = {
- "Environment" = "staging" -> null
- "Group"       = "couchdb2" -> null
- "Name"        = "vol-couch15-staging" -> null
- "ServerName"  = "couch15-staging" -> null
}
throughput            = 125
volume_id             = "vol-0dadba609d5743504"
volume_size           = 30
volume_type …
```
> fixing root volume tags removal issue when new state imported

- environments/production/postgresql.yml
- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12566
Production. 
In the process of "Consolidate the pgbouncer machine to 4 machines," we are replacing pgbouncer5,8 with pgbouncer 6,7,9 server.
> consolidating production pgbouncer servers.

- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_pillowtop.conf.j2
- src/commcare_cloud/environment/schemas/app_processes.py
Pillows that handle UCRs support this option, so adding that support to config.
Depends on https://github.com/dimagi/commcare-cloud/pull/4900
> Handle exclude_ucrs option

- docs/howto/perf_testing.md
- docs/index.md
Refer commcare-cloud users to commcare-perf for performance testing.
Context: [SC-1735](https://dimagi-dev.atlassian.net/browse/SC-1735)
None. This is a documentation change.
> Refer commcare-cloud users to commcare-perf

- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
Old behavior available with COMMCARE_CLOUD_USE_AWS_SSM=0
This PR is scheduled to be merged on Oct. 1, 2021.
Based on the rollout plan outlined in https://docs.google.com/document/d/1Q8iKWxk2tP9v9jjmcQRcl90gMrCQb0Whx-OIlgGv0U4/edit#.
> Make COMMCARE_CLOUD_USE_AWS_SSM=1 the default

- src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml
Use http instead of https.
Note that packages are signed and apt will verify their validity.
All
> Fix nodejs repository

- environments/production/fab-settings.yml
Enables publication of production deploy events to the dimagi-qa repo, which will cause QA tests to run.
In addition to this PR, a new _dimagi-qa-production-deploy-event_ token was created on the @dimagi/qa account, and the [confluence page](https://confluence.dimagi.com/display/saas/SaaS+Env+Secrets+and+Accounts) was updated. The value of that token was set on the production `deploy_event_token` secret.
production
> Add deploy_event_url for production

- environments/production/postgresql.yml
- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12566
Production
- We recently removed pgbouncer9 from formplayer and main NLB. updating the same in postgresql.yml (https://dimagi-dev.atlassian.net/browse/SAAS-12656)
- marking pgbouncer5, 8 for decommissioning, based on cost optimization plan. 
- Adding Pgbouncer6,7 to the Pgshards_nlb for HA.
> Consolidate pgbouncers nodes

- src/commcare_cloud/ansible/roles/couchdb2-preinstall/tasks/main.yml
erlang-mode is not needed and the version set for CouchDB 2.3.1 is currently unavailable in the erlang-solutions repository.
All
> Remove unnecessary CouchDB dependency

- docs/commcare-cloud/commands/index.md
- src/commcare_cloud/commands/secrets.py
which can be used to override the value set in meta.yml. This is useful for taking a backup of secrets values.
https://dimagi-dev.atlassian.net/browse/SAAS-12773
None
> Add --to-backend option to migrate-secrets

- commcare-cloud-bootstrap/environment/private.yml.j2
- docs/index.md
- docs/services/bitly.md
https://dimagi-dev.atlassian.net/browse/SC-1871
Users deploying locally might not know they need to add a bitly oauth token. 
None
> Add docs for bitly

- environments/staging/public.yml
Reverts dimagi/commcare-cloud#4965
Rolling back to 3.6 to test the workflow of rolling back.
Once rolled back, the pickle protocol will be pinned at a version that is supported by both 3.6 and 3.9 to decouple the Python version change from the pickle protocol change, making future rollbacks smoother. In the mean time, some celery tasks that were created by Python 3.9 processes will not be able to be processed after rolling back to 3.6.
> Revert "Python 3.9 on staging"

- environments/india/proxy.yml
- environments/production/proxy.yml
- environments/staging/proxy.yml
- environments/swiss/proxy.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12042
1 year is the minimum value needed to be eligible for the HSTS preload list, so this should be the last of these PRs that bump the hsts value.
Production, India, Swiss, Staging
> Bump HSTS value to 1 year for all envs

- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- environments/swiss/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
- src/commcare_cloud/ansible/roles/nginx/templates/site.j2
- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
This was brought up as part of [this ticket](https://dimagi-dev.atlassian.net/browse/SAAS-12042). I didn't realize that duplicate headers were being returned, so we need to change our approach. 
In a perfect world, we could set these values in django to take advantage of up to date security warnings when services are checked, in addition to setting these values in nginx to take advantage of being on the perimeter of our system. Unfortunately it looks like we have to compromise, and it is more important to have these values set in nginx so they apply to all requests, not just requests coming back from django services. 
I removed the security related variables from the local settings template, and silenced the django warnings that resulted from not setting these security vars. I saw that …
> Set security related headers in nginx only, remove from django

- src/commcare_cloud/fab/checks/check_servers.py
Disable these for now since these are causing the deploy to fail. This is safe to have disabled as long as there are no config changes that affect DB routing.
> temporarily disable deploy database checks

- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
Followup to [the PR](https://github.com/dimagi/commcare-cloud/pull/4971) that moved all security related header setup to nginx. I was cautious about including `includeSubDomains` in the header, but in hindsight I'm not sure why since we were already doing this at the django level. Alas, here we are so this is a very small PR that I plan to roll out by running `cchq --control <env> ansible-playbook deploy_proxy.yml --tags=nginx_sites --limit proxy`
None
> Add includeSubDomains to Strict-Transport-Security header

- src/commcare_cloud/fab/checks/check_servers.py
Reverts dimagi/commcare-cloud#4979
To be merged after https://github.com/dimagi/commcare-hq/pull/30736
> Revert "temporarily disable deploy database checks"

- environments/production/app-processes.yml
Decrease concurrency from 4 to 3 for:
- case_rule_queue
- saved_exports_queue
https://dimagi-dev.atlassian.net/browse/SAAS-12815
Production
> Decrease celery concurrency

- environments/india/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
v2 has been long deprecated.
https://dimagi-dev.atlassian.net/browse/SAAS-12634
https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/
All
> Set S3 signature to v4

- docs/setup/new_environment.md
- src/commcare_cloud/manage_commcare_cloud/configure.py
Debian derivatives, incl. Ubuntu, use ~/.profile. The default ~/.profile in Debian and Ubuntu calls ~/.bashrc. If ~/.bash_profile (or ~/.bash_login) exists, then ~/.profile is ignored. ([More details on bash startup files here](https://www.golinuxcloud.com/bashrc-vs-bash-profile/).)
CommCare Cloud already calls ~/init-ansible from ~/.profile. The existing instruction creates a new ~/.bash_profile, so ~/.bashrc and ~/init-ansible are no longer called.
If ~/.commcare-cloud/load_config.sh should be called *before* ~/init-ansible, then this line should be appended to ~/.bashrc, not ~/.profile. If it should be called *after* ~/init-ansible, or if it doesn't matter, then the change in this commit should be correct.
None. This PR only affects instructions to the user.
> Use ~/.profile instead of ~/.bash_profile

- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/deploy/formplayer.py
Minor followup for https://github.com/dimagi/commcare-cloud/pull/4848/ - deploy failure notifications are failing with `AttributeError: 'str' object has no attribute 'get_meta_value'`
None
> Updated calls to record_deploy_failed

- environments/production/app-processes.yml
The reminder_queue takes ~an hour to process. Last week, we bumped concurrency to 40 to handle a larger than usual backlog, but that change was reverted. Now that we are consistently seeing slower times, it makes sense to bump this value permanently.  
Production
> Bump concurrency from 20 to 40 for the reminder_queue

- environments/production/app-processes.yml
Reverts dimagi/commcare-cloud#5002
It looks like we actually still need these.
> Revert "undo temporary increase in reminder processing"

- src/commcare_cloud/cli_utils.py
- src/commcare_cloud/commcare_cloud.py
For commands that check the branch before running the command:
- Error if there are unstaged or uncommitted changes.
- Error if local master has diverged from upstream.
- Suggest how to recover.
All.
> Check more thoroughly when deploying from master (without --branch=...)

- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
Add a new DimagiAllowRules rule group with a single rule called
StaticContent that allows requests matching a URI path starting with
"/static/hqwebapp/js/requirejs_config.js".
Add the new group to the default Web ACL frontend-waf with priority
of 1, immediately after DimagiBlockRules.
https://dimagi-dev.atlassian.net/browse/SAAS-12870
All
> Add new DimagiAllowRules rule group to AWS WAF

- environments/production/app-processes.yml
I'm applying this to capture more persistently the current state that `malt_generation_queue`. @skodde @gherceg please review this retroactively, and give it approval but then we can just close it.
production
> Temporarily remove malt_generation_queue altogether

- environments/production/terraform.yml
Change RDS instance type from t3.xlarge to m5.xlarge due to EBS
bandwidth limit.
Production
> Scale up pgsynclog0-production and pgucr0-production

- environments/production/terraform.yml
Change (again) RDS instance type from m5.xlarge to m5.2xlarge, due
to CPU usage.
Production
> Scale up pgucr0-production

- environments/production/terraform.yml
40% of 16GB is 6.4GB, raising this from our default of 25% or 4GB
Prod
> increase shared buffers to 40%

- environments/production/terraform.yml
Change (again) RDS instance type from m5.xlarge to m5.2xlarge, due
to CPU and EBS usage.
Production
> Scale up pgsynclog0-production

- environments/production/terraform.yml
This PR incorporates changes from https://github.com/dimagi/commcare-cloud/pull/5026 that have already been approved and applied as part of the migration work in https://dimagi-dev.atlassian.net/browse/SAAS-12493. Getting this in before the whole thing is complete will let us continue to manage chagnes to pgsynclog0-production consistently in the interim.
production
> Add pgtransport extension params in pgsynclog0 parameter group

- environments/production/terraform.yml
Reverts dimagi/commcare-cloud#5074
This didn't work and may have negative effects, so reverting for now.
> Revert "increase shared buffers to 40%"

- src/commcare_cloud/ansible/roles/elasticsearch/tasks/misc_v2.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12847
This should help with the recurring `java.lang.OutOfMemoryError: Direct buffer memory` errors we get on production (and sometimes india) ES nodes, and is the solution adopted by ES itself in later versions (https://github.com/elastic/elasticsearch/pull/25759)
All
> enable explict gc for es

- environments/staging/app-processes.yml
https://dimagi-dev.atlassian.net/browse/USH-1403
This adds a flag to enable/disable OpenTracing globally so we can limit it to staging.
See conversation on https://github.com/dimagi/commcare-core/pull/1063
This can be merged any time but will not be read until https://github.com/dimagi/commcare-core/pull/1063 is merged.
staging
> Add enableOpenTracing flag to formplayer_command_args

- environments/production/postgresql.yml
We have 3 pgbouncer machines, so this limits connections from 150 (3 * 50) to 48 (3 * 16), in an effort to make sure that at the limit, the machine is still functional.
Production
> Lower connection limits for auditcare

- environments/production/terraform.yml
Change CouchDB instance type from c5a.24xlarge to c6i.24xlarge.
Production
> Change CouchDB instance type

- hosting_docs/source/training/0-index.rst
Note that this PR is based off the **sr/docs** branch.
Easier to review [the rendered document](https://github.com/dimagi/commcare-cloud/blob/nh/training_plan/hosting_docs/source/training/0-index.rst).
Please let me know if you think there is anything missing, prerequisites I've skipped, useful links I should add, etc.
None. Documentation only.
> Self-hosting training plan

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12493
Production. 
Adding new RDS instance pgsynclog1 with less disk storage i.e 5TB. To this instance, we will copy the data from the pgsynclog0 instance using the pg_transport extension
Old PR1: https://github.com/dimagi/commcare-cloud/pull/5026 
Old PR2: https://github.com/dimagi/commcare-cloud/pull/4920
> adding new pgsynclog1 rds with smaller disk

- environments/production/postgresql.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12493
Production.
replacing rds_pgsynclog0 with rds_pgsynclog1 rds instance in PostgreSQL configurations. This task is already completed. 
@dannyroberts @shyamkumarlchauhan could you please merge this PR? 
Thanks
> replacing rds_pgsynclog0 with rds_pgsynclog1 rds instance in yaml

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12493
Production
We have recently replaced this rds instance with new one `pgsynclog1`. And also stopped `pgsynclog0` instance yesterday. Now, we are planning to terminate the old instance.
> terminating pgsynclog0 rds instance

- environments/production/postgresql.yml
This reverts commit a765a68e24fee1fda7d02b753786ac4a0e2ab77b.
This commit from https://github.com/dimagi/commcare-cloud/pull/5111 appears to have caused serious problems for reasons I don't fully understand. Reverting it should make the rest of that PR safe to apply.
Production
> Revert "Lower the pgbouncer reserve pool size for auditcare db"

- environments/production/public.yml
Update made to `ALTERNATE_HOSTS` to allow for proxy URLs to be used on mobile devices in preparation for the data migration for the onse-iss domain (instructions [here](https://commcare-cloud.readthedocs.io/en/latest/reference/howto/transfer-domain.html)).
Production
> Update public.yml file ALTERNATE_HOSTS

- docs/Commcare_Ports_information.md
The table definition for the CommCare Ports table seemed to be broken (no biggy, it's available [here](https://github.com/dimagi/commcare-cloud/blob/master/docs/Commcare_Ports_information.md)), but this is the fix.
This is docs, so none.
> Fix table def

- environments/production/terraform.yml
This was one of AWS Supports suggestions in https://dimagi-dev.atlassian.net/browse/SAAS-12885
```
~ resource "aws_db_instance" "this" {
...
~ monitoring_interval                   = 0 -> 60
...
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
production
> Enable Enhanced Monitoring on pgauditcare0-production RDS instance

- environments/production/postgresql.yml
This reverts commit 6017d3d96441c5a43303729dd39bf20ffddb6e66.
This will lower the normal pool size to 18 and the reserve pool size to 6, total. That would put the max "burst" connection limit at 24, which is the current size of the "normal" pool.
Production
> Lower the pgbouncer pool size (reserve & normal) for auditcare db

- src/commcare_cloud/ansible/roles/datadog/defaults/main.yml
- src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
- src/commcare_cloud/ansible/roles/datadog/tasks/remove_integrations.yml
With multiple subgroups under the main celery group, the old syntax to
choose the celery host where to install the datadog agent stops working.
Let's explicitly select the one where flower is running.
https://dimagi-dev.atlassian.net/browse/SAAS-12911
All
> Correctly identify the celery host for datadog

- environments/staging/app-processes.yml
This is part of the [broad pickle removal efforts](https://dimagi-dev.atlassian.net/browse/SAAS-11385), specifically focusing on the reports and phonelog apps. These apps have tasks that use dedicated celery queues and need them for proper testing on staging (QA). 
Unless there's a reason staging didn't have/support these queues, I could also keep these changes after testing. 
Staging
> Temporarily add celery queues to Staging

- environments/swiss/app-processes.yml
Just noticed [this](https://app.datadoghq.com/dashboard/bdu-k5b-bz5/celery-overview?fullscreen_end_ts=1644537853285&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1641859453285&fullscreen_widget=185712938&tpl_var_celery_queue=malt_generation_queue&tpl_var_environment=swiss&from_ts=1641859450000&to_ts=1644537850000&live=true), which was due to a blocking task that creates subtasks it depends on on the same queue (has since been resolved), but when concurrency is 1 and there is only 1 worker, this is no good. 
Bumping concurrency temporarily should relive this issue.
Swiss
> Temporarily bump concurrency to help swiss get through a backlog

- src/commcare_cloud/ansible/roles/zookeeper/defaults/main.yml
- src/commcare_cloud/ansible/roles/zookeeper/tasks/main.yml
All.
We are facing the below error due to an incorrect variable set to `zookeeper_server_id`. I have corrected it and also add when the condition to ignore tasks when `zookeeper_cluster: False`
> fixed incorrect variable and task missing when condition

- environments/production/public.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12956
Only kill celery workers after waiting 36 hours for their last task to finish, rather than current 10
Production
> Increase celery hard kill timeout

- docs/howto/wipe_persistent_data.md
Add the `--skip-check` flag to command which is used to recreate the db's after a db wipe.
This change only concerns the docs
> Add --skip-check to command

- docs/firefighting/index.md
- docs/services/blobdb/migrate-fs-to-s3.md
- docs/services/postgresql/migrating_plproxy.md
- src/commcare_cloud/commands/ansible/service.py
This was prompted by a history of occasional operation errors resulting from unclear guidance (both on the team and from the tool itself) on which command to use to restart webworkers and/or services based on commcare-hq code. `cchq <env> service commcare restart` is a trap because (1) it does a non-rolling restart of webworkers, resulting in webworker downtime (2) it does a formplayer restart which always causes downtime. Similarly `cchq <env> service webworkers restart` has problem 1 as well.
This change makes those two commands (specifically/only with the restart action) to display an error message suggesting alternatives and then refuse to proceed (exiting with return code 1).
None
> Reject `cchq <env> service commcare restart`

- environments/production/terraform.yml
Increase celery_c machines volume size from 80GB to 120GB.
https://dimagi-dev.atlassian.net/browse/SAAS-13215
Production
> Increase celery volume size

- src/commcare_cloud/user_utils.py
While trying run `cchq <env> terraform` commands I noticed that if your username on the AWS machines is different than your dev workstation username, the message that prompts you to run `export COMMCARE_CLOUD_DEFAULT_USERNAME={AWS machine username}` would give an error and exit the process. 
None
> Fix format statement for COMMCARE_CLOUD_DEFAULT_USERNAME_ENV_VAR_MESSAGE

- environments/india/postgresql.yml
- src/commcare_cloud/ansible/roles/common_installs/defaults/main.yml
- src/commcare_cloud/ansible/roles/pg_backup/defaults/main.yml
- src/commcare_cloud/ansible/roles/postgresql_base/defaults/main.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12875
All.
Since my previous modification to default values will impact third-party users who have not yet updated the PostgreSQL version to 10. Therefore reverting back my changes to default values and as we can also control this variable from public.yml `postgresql_version: '9.6'` updated India files and production will do when performing it. 
Old PR: https://github.com/dimagi/commcare-cloud/pull/5062
> changing postgres_version default value to 9.6 from 10 in ansible Roles

- src/commcare_cloud/ansible/roles/zookeeper/tasks/main.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12484
All new envs
The commcare installation is failing with the following error in the new environments.
```
"fatal: [172.31.22.36]: FAILED! => {\\"changed\\": false, \\"gid\\": 0, \\"group\\": \\"root\\", \\"mode\\": \\"0755\\", \\"msg\\": \\"chown failed: failed to look up user zookeeper\\", \\"owner\\": \\"root\\", \\"path\\": \\"/opt/zookeeper/logs\\", \\"size\\": 4096, \\"state\\": \\"directory\\", \\"uid\\": 0}",
```
This is happening in new installations only. The existing servers wherein zookeeper is already installed using `apt` has user, group created automatically. Zip file-based installation doesn't get created by default so faced this issue. Sorry for the inconvenience. 
@proteusvacuum please review and let me know your …
> fixed zookeeper user error

- src/commcare_cloud/ansible/roles/postgresql_base/templates/pg_hba.conf.j2
Jira: [SC-2011](https://dimagi-dev.atlassian.net/browse/SC-2011)
Formplayer needs to connect to both PgBouncer and Postgres. Connecting to PgBouncer using the details stored in  **/home/cchq/www/cluster/formplayer_build/current/application.properties** succeeds, but connecting to Postgres fails.
This change adds entries to **pg_hba.conf** to trust Formplayer hosts.
**BEFORE**
Postgres configuration:
ansible@db1:~$ sudo cat /etc/postgresql/9.6/main/pg_hba.conf
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
host   all	all	192.168.122.4/32   trust
host   all	all	192.168.122.4/32   trust
host   all	all	192.168.122.4/32   trust
host   all	all	192.168.122.4/32   trust
host   all	all	192.168.122.4/32   trust …
> Formplaye DB host must trust Formplayer hosts

- src/commcare_cloud/ansible/roles/ufw/tasks/main.yml
- src/commcare_cloud/ansible/roles/ufw/tasks/proxy_ufw.yml
From Ubuntu 18.04.6 LTS, users must install the net-tools package to use `ifconfig`. It is deprecated in favor of `ip`.
This change uses `ip` instead of `ifconfig`.
Stupidly, I tested the happy path first, and now I can't go back to test the unhappy path (an incorrectly configured interface) on that particular VM. I have not yet tested the unhappy path on a new VM. But I figured I'd open the PR in the meantime. (I do expect it to work though. `ip addr show dev invaliddevice` returns nothing to STDOUT, and an error message to STDERR.)
Affects new environments, and provisioning new VMs in existing environments, when VMs have a fresh Ubuntu 18.04 image.
> net-tools not in Ubuntu 18.04.6 LTS by default

- environments/staging/public.yml
Part of our [efforts to remove pickles](https://dimagi-dev.atlassian.net/browse/SAAS-11385) from HQ. In order to properly test the changes made to the `phonelog` app on staging, which has one task that handles sending logs to SumoLogic, the endpoint url for the staging needs to be added as a secret. 
The steps for adding secrets [outlined here](https://confluence.dimagi.com/pages/viewpage.action?spaceKey=saas&title=How+to+add+new+secrets+or+other+local+settings) were followed but since the `sumologic_url` for other environments were already in place most of it was already done. 
Staging
> Add SUMOLOGIC_URL to staging

- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/utils.py
When this command was moved out of `fab` the `sudo` function changed from `sudo -u cchq` to just plain `sudo`, and there is no need to be root to get the latest commit hash. This has the added bonus of no longer requiring the swiss vault password to deploy swiss, which should never have been necessary.
> lookup deploy version without sudo

- docs/howto/transfer-domain.md
No ticket; just general improvement.
Change:
Add link from [Prepare the new environment to be populated](https://commcare-cloud.readthedocs.io/en/latest/installation/migration/1-migrating-project.html#prepare-the-new-environment-to-be-populated) to [How to Wipe Persisted Data](https://commcare-cloud.readthedocs.io/en/latest/reference/howto/wipe_persistent_data.html).
Only docs
> Add link to wipe_persisted_data page

- src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml
- src/commcare_cloud/ansible/roles/couchdb2-preinstall/tasks/main.yml
- src/commcare_cloud/ansible/roles/python/tasks/main.yml
- src/commcare_cloud/ansible/roles/sentry/tasks/snuba.yml
This PR replaces PR #5211 
It updates the default pip used by Ansible, so that it is available universally and can be used consistently.
Affects new deploys.
> Update pip in common_installs

- src/commcare_cloud/ansible/roles/pgbouncer/defaults/main.yml
- src/commcare_cloud/ansible/roles/pgbouncer/handlers/main.yml
- src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml
- src/commcare_cloud/ansible/roles/pgbouncer/templates/monit.pgbouncer.j2
- src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer-classic.defaults.j2
- src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer-classic.ini.j2
- src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer-multiprocess@.service.j2
Changes prompted by https://dimagi-dev.atlassian.net/browse/SAAS-12182
- Bump the minimum required version to 1.13 so that we can use `Type=notify` with systemd
- Add a `pgbouncer_version` variable that can be set per environment if necessary, and set the default to the currently latest available version (1.17)
- Remove unnecessary `become` keywords and "pgbouncer" tags, which are already set in the playbook
- Reorder the handlers to avoid unnecessary multiple restarts
- Remove unnecessary hardcoded pgbouncer "classic" restart
- Remove outdated after-reboot actions (open fd limit is set in the systemd unit)
- Uniform configurations for "classic" and "multiprocess"
- Correct the start/stop commands for monit, which were inverted
- Adjust `with_sequence` to avoid "to count backwards make …
> PgBouncer various fixes and cleanups

- environments/india/terraform.yml
- environments/production/terraform.yml
- environments/staging/terraform.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
https://dimagi-dev.atlassian.net/browse/SAAS-11914
Perhaps easiest to follow when reviewed commit-by-commit.
This is an alternative approach to https://github.com/dimagi/commcare-cloud/pull/5244 that allows for different environments to have different values as we roll it out, without keeping a PR open for the duration of the rollout.
Only the value for staging is changed
> Add ec2_metadata_tokens_required option and set to True on staging

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
To manage Formplayer, Supervisord needs the log directory to exist, otherwise it will not start. But the log directory is not created on a Formplayer-only VM:
(cluster) cchq@formplayer2:~$ supervisord
Error: The directory named as part of the path /home/cchq/www/cluster/log/formp
layer-spring.log does not exist in section 'program:commcare-hq-cluster-formspl
ayer-spring' (file: '/home/cchq/www/cluster/services/cluster_supervisor_formpla
yer_spring.conf')
For help, use /usr/local/bin/supervisord -h
I copied the approach [used for installing nginx](https://github.com/dimagi/commcare-cloud/blob/71f659dbef8d260e076f5eabd1d02eeb524116c5/src/commcare_cloud/ansible/roles/nginx/tasks/install.yml#L67).
Only affects new deploys where Formplayer is running on its own VM.
> Make sure the log directory exists

- src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
- src/commcare_cloud/terraform/modules/logshipping/main.tf
https://dimagi-dev.atlassian.net/browse/SAAS-13313
All
Adding comment lines only for this review and once approved I will remove them if suggested.
--
When these resources were added in .tf file we don't have to apply them since they are already, instead we have to import them using terraform import commands. 
Whereas, for acl it is asking us to apply the change even after importing. And I see that it is safe to apply,
> adding separate resource section for aws_s3_bucket_acl & server_side encryption

- src/commcare_cloud/ansible/roles/pgbouncer/defaults/main.yml
- src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml
The pgbouncer package from postgresql.org is only available for the
latest version. We cannot set it to an arbitrary version as it would
break new installations.
The 'configure' tag allows us to perform normal operations without
upgrading the package, so let's set the version to 'latest' to avoid
manual interventions when we actually want to upgrade it.
All
> Always install the latest pgbouncer version

- environments/production/public.yml
Reverts dimagi/commcare-cloud#5114
This was creating a hard-to-resolve terraform diff. Offlined with @Charl1996; looks like this was a little premature and the project team can redo this change when they're ready.
> Revert "Update public.yml file ALTERNATE_HOSTS"

- environments/production/terraform.yml
We had increased the disk space for c1 production last time when we faced disk space issues. 
Now, in order to fix the terraform diff, I'm raising the PR with that change.
> adding disk space for c1 prod.

- src/commcare_cloud/ansible/roles/backups/templates/create_blobdb_backup.sh.j2
- src/commcare_cloud/ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2
- src/commcare_cloud/ansible/roles/pg_backup/templates/plain/create_postgres_dump.sh.j2
https://dimagi-dev.atlassian.net/browse/SAAS-13494
All
@dannyroberts @shyamkumarlchauhan 
It seems like the Previous swiss backup scripts were edited on the server directly. Because of that when we ran the `deploy-stack` command on the swiss server recently, it has replaced the existing backup scripts, and backups were not `uploaded` to the s3 bucket. 
As a fix, I'm adding the cchq python virtualenv path to the python script as the using the default Python (2.7) the scripts are failing. Tested this process on the server and it is working as expected. 
--
Need Suggestions: 
adding {{ deploy_env }} is right option or {{ virtualenv_home }} which one is the right option to choose. Please suggest.
> adding virtualenv path for upload script. It is failing with default python

- src/commcare_cloud/environment/schemas/app_processes.py
The management part was removed long ago from 'reminder_queue',
'submission_reprocessing_queue', and 'sms_queue'.
It is now safe to remove them from 'SOLO_QUEUES'.
All
> Remove unnecessary queues from 'SOLO_QUEUES'

- quick_monolith_install/cchq-install.sh
Recently this prompt was updated to timeout after 30 seconds, so make the init-ansible default for those who use quick-install.
@proteusvacuum
> Make init-ansible default for quick-install

- changelog/0048-update-supervisor-confs.yml
- docs/changelog/0048-update-supervisor-confs.md
Fix for changelog added by #5298.
The commit in this changelog was a commcare-cloud commit SHA, there is no commcare-hq change associated with this changelog entry.
- all
> Remove commit from changelog entry

- hosting_docs/source/installation/migration/1-migrating-project.rst
- hosting_docs/source/reference/howto/wipe_persistent_data.rst
This PR updates the [migration docs](https://commcare-cloud.readthedocs.io/en/latest/installation/migration/1-migrating-project.html#import-the-data-to-the-new-environment) specifically with the understanding that an env needs to be code-deployed before migration and the DBs to be reset only if there is test data that the user wants to be deleted. There are also other updates to rebuild UCRs and to remove cleanliness_flag command (it's not needed anymore).
@proteusvacuum @Charl1996
> Correct domain migration docs

- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
This is purely cleanup of an env var there is no longer any reason to use
> Make COMMCARE_CLOUD_USE_AWS_SSM=1 the only available behavior

- requirements.txt
- setup.py
Need to upgrade to at least v1.0.0 of jsonobject which added support for python 3.10. couchdb-cluster-admin also depends on jsonobject, and has been upgraded to support v2.0.0 so this is the last step.
As far as safety of this goes, the main change to jsonobject is how [ListPropertys accept iterables now](https://github.com/dimagi/jsonobject/blob/master/CHANGES.md) (my understanding). There are lots of ListProperty usages in commcare-cloud, and it is hard to say with confidence that we do not depend on this previous BadValueError exception being raised for iterables. Welcoming any suggestions for gaining a better understanding there.
> Bump jsonobject to 2.0.0

- requirements.txt
- setup.py
We use pytz in very standard ways, calling `pytz.timezone(...)` and using `pytz.utc.localize` to localize utc datetimes. I admittedly haven't been able to find a clear changelog for pytz, but reading through documentation [here](https://pypi.org/project/pytz/2022.1/), I have no reason to believe these behaviors have changed.
> Bump pytz from 2017.2 to 2022.1

- src/commcare_cloud/commands/deploy/commcare.py
This is an in-line documentation change to match my recent documentation changes in https://confluence.dimagi.com/display/GTD/Deploy+Process and https://confluence.dimagi.com/display/saas/Internationalization+and+Localization+-+Transifex+Translations, based on our consensus from last Friday to make the automated workflow the default process.
> Change Update Translations help text during deploy

- environments/india/app-processes.yml
Adjust formplayer memory settings based on the current instance type
of formplayer1-india, which has 16GB of RAM.
India
> [india] Adjust formplayer memory settings

- environments/production/public.yml
I realized that we needed a separate interim URL for migration. The previous URL should be the final URL, so it shouldn't need to be here.
@shyamkumarlchauhan
> Use subdomain for onse migration

- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
- src/commcare_cloud/ansible/roles/formplayer/vars/main.yml
Current we create the release in Sentry when we deploy using this name but all events from formplayer are tagged with a different release name (the git commit hash). This will tie the events to the correct release.
> configure sentry with formplayer relase name

- hosting_docs/source/scaling/sizing.rst
[Ticket](https://dimagi-dev.atlassian.net/browse/SC-1821)
This PR expounds a little on determining the parameters for the commcare_resource_model's sections. It may be redundant, since the docs already exist in the already provided links which is included in the existing sections, but I thought it might be helpful for a person who is currently visiting the page to have the "how to determine parameters" sections also on this page, even though it links out to the same page whose link is already provided. Someone who is searching for a how-to might not necessarily want to first scan through other docs to find an answer. 
Only docs
> Add sections on determining resource model sections' params

- src/commcare_cloud/commands/inventory_lookup/getinventory.py
Fixed because I noticed it.
- all
> Update error message in `get_server_address` to use non-deprecated syntax

- src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2
All. 
The current `terraform.lock.hcl` file is generated from a Linux machine and when trying from a mac it is reusing those hashes and not downloading versions for mac systems. This is blocking us from running the tf plan command. 
To fix the problem I have generated a lock file for all platforms using the below command
`terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64` 
Another way to solve the problem is not to commit lock.hcl itself and generate new ones every time.
References:
https://github.com/hashicorp/terraform/blob/be263151e776e84688f1b0648084a1a6f280d78a/website/docs/commands/providers/lock.html.md#lock-entries-for-in-house-providers
https://github.com/hashicorp/terraform/issues/27135#issuecomment-738679614
> generate the terraform lockfile for all platforms

- .github/workflows/tests.yml
- .tests/tests.sh
- Makefile
- setup.py
- src/commcare_cloud/commands/ansible/ansible_playbook.py
- src/commcare_cloud/commands/ansible/run_module.py
- src/commcare_cloud/commands/fab.py
- src/commcare_cloud/help_cache/ansible-playbook.txt
- src/commcare_cloud/help_cache/ansible.txt
- src/commcare_cloud/parse_help.py
- src/commcare_cloud/patched_fab.py
https://dimagi-dev.atlassian.net/browse/SAAS-13500
First step in upgrading commcare-cloud to work with python 3.10. Once tests pass, we should be able to test this on staging.
None
> Add support for python 3.10

- src/commcare_cloud/ansible/roles/datadog/tasks/main.yml
https://dimagi-dev.atlassian.net/browse/SAAS-13167
Docs: https://docs.datadoghq.com/agent/guide/linux-agent-2022-key-rotation/?tab=debianubuntu
See also https://forum.dimagi.com/t/error-installing-datadog-on-new-server/9207 for context. 
all that use datadog
> Update datadog apt key to the new one from the docs

- control/init.sh
We want to upgrade commcare-cloud to support 3.10, and this is a step needed to test cchq commands on 3.10.
> Add option to use python3.10 in init.sh

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/commands/terraform/templates/terraform.tfvars.j2
- src/commcare_cloud/commands/terraform/templates/variables.tf.j2
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/terraform/modules/server/iam/main.tf
- src/commcare_cloud/terraform/modules/server/iam/variables.tf
https://dimagi-dev.atlassian.net/browse/SAAS-13894
This is the other side of https://github.com/dimagi/commcare-hq/pull/32071. Both are required before we can set s3 credentials to `None` and rely on EC2 roles.
> Add access to s3 blobdb bucket to CommCareServerRole

- control/init.sh
- quick_monolith_install/cchq-install.sh
This should allow us to switch from `virtualenv` to `venv` as users move onto 3.10, without breaking any existing 3.6 workflows.
> Use venv instead of virtualenv on 3.10

- quick_monolith_install/cchq-install.sh
It seems sometimes the VENV variable is not set (i.e. is blank) when `cchq-install.sh` is executed, which is weird, because `echo y | source "$DIR/../control/init.sh"` is executed correctly according to the output.
This PR attempts to mitigate the VENV issue by defaulting to the value that it's supposed to be when `init.sh` executes and would have set it to.
(not sure if a deeper investigation is warranted?)
Quick monolith install
> Check if VENV is set, otherwise default

- hosting_docs/source/installation/2-manual-install.rst
- provisioning/control.sh
- quick_monolith_install/cchq-install.sh
- src/commcare_cloud/ansible/roles/ansible-control/tasks/main.yml
We no longer use any virtualenvwrapper syntax in commcare-cloud, so the dependency is unnecessary. If a user wishes to install it for their own use, they are welcome to do so.
> Remove virtualenvwrapper dependency

- src/commcare_cloud/ansible/roles/nginx/defaults/main.yml
- src/commcare_cloud/ansible/roles/nginx/tasks/install.yml
This change ...
* removes nginx's mainline repo
* adds nginx's stable repo
* sets "nginx_version" in defaults/main.yml to the current stable version
All
> Set default nginx_version to current stable

- src/commcare_cloud/ansible/group_vars/elasticsearch.yml
- src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
https://forum.dimagi.com/t/elasticsearch-installation-error/9247
The issue was caused by the recent ansible upgrade and a behavior change in ansible
between versions on how |map("extract", ...) handles undefined values
all
> Fix issue updating es conf

- control/init.sh
- quick_monolith_install/cchq-install.sh
Followup to https://github.com/dimagi/commcare-cloud/pull/5409
Daniel flagged the above PR as I happen to be working in this area as well. I ran some tests locally, creating parent.sh and child.sh bash scripts to test the scope of variables between the two. It appears the crux of the issue is that we invoke the init script with a pipe: `echo y | source "$DIR/../control/init.sh"`.
The problem with the pipe is that it results in the init script running in a forked process, and variables defined in the this child process are not available in the parent process. I figured the `echo y | ...` portion of that line is to answer yes to the prompt about setting up commcare-cloud on login when running the init script.
My solution is to create a new variable in the init script named `NO_INPUT` which …
> Fix VENV issue in cchq-install script

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-13906
Production
We have increased the server capacity due to network issues with the t3 instance and to speed up the migration process.
> adding more resources to speed up the migration process

- requirements.txt
- setup.py
Add missing pyOpenSSL dependency (22.x), as we've been relying on a system
package that gets installed indirectly, and bump cryptography to 38.x.
The current system provided version of pyOpenSSL (python3-openssl) is no
longer compatible with the authorized_key ansible module.
All
> Add missing pyOpenSSL dependency

- environments/production/app-processes.yml
- environments/production/public.yml
Temporary pillow to backfill the new case search index and keep it up to date until we switch.
See plan doc: https://docs.google.com/document/d/1OlU3k5bEjQydUIIwDaAfKdHr_vvZuzMFLO_iIP6vGpQ/edit#
Production
> temporary backfill pillow for case search ES

- src/commcare_cloud/commands/terraform/constants.py
https://dimagi-dev.atlassian.net/browse/SAAS-12315
Update `terraform/constants.py` with the output of `./manage.py list_waf_allow_patterns` after adding https://github.com/dimagi/commcare-hq/pull/32190
All the environments that use WAF
> update constants with output of list_waf_allow_patterns

- control/init.sh
This is a minor update that I was initially going to make on https://github.com/dimagi/commcare-cloud/pull/5424, but it felt more fitting to keep it separate as it leaves 3.10 optional (easier for internal testing).
This will make it so that when we do upgrade to 22.04, because 3.10 will already exist, the virtualenvs will be named 'cchq', rather than 'cchq-3.10' which is minor, but convenient.
> Create and use 3.10 venv if 3.10 is installed

- control/init.sh
Fix venv naming issue. See https://github.com/dimagi/commcare-cloud/pull/5526 for more context.
> Save 3.10 venv to a new var

- src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
Deploy was failing with the errors described in https://bbs.archlinux.org/viewtopic.php?id=280571 on new machines that had an updated version of git. The root cause of that is a change to the most recent version of git referenced in the release notes [here](https://lore.kernel.org/lkml/xmqq4jw1uku5.fsf@gitster.g/). This changes the config back to the old behavior, and existing behavior on all old machines. The reason for the change in git was a security concern about locally cloning malicious repositories. Since we are only cloning our own repositories, this seems like less of a concern.
> allow git file transport

- src/commcare_cloud/commands/terraform/constants.py
- src/commcare_cloud/commands/terraform/tests/test_compact_regexes.py
https://dimagi-dev.atlassian.net/browse/SAAS-14023
There have been recent changes to HQ to allow more endpoints to bypass the WAF. This updated regex is the output of the command `./manage.py list_waf_allow_patterns`.
none
> Update WAF regex with most recent version of HQ

- src/commcare_cloud/ansible/roles/rabbitmq/tasks/main.yml
- src/commcare_cloud/ansible/roles/rabbitmq/templates/rabbitmq.conf.j2
- src/commcare_cloud/ansible/roles/rabbitmq/templates/rabbitmq.config.j2
https://dimagi-dev.atlassian.net/browse/SAAS-13912
Followup to https://github.com/dimagi/commcare-cloud/pull/5552 which was not successful in setting the `consumer_timeout` rabbitmq param.
According to
- https://www.rabbitmq.com/logging.html#log-message-categories
- https://www.rabbitmq.com/configure.html#config-file-formats
Applied on staging with
```
cchq --control staging deploy-stack --tags=rabbitmq --branch=dmr/fix-rabbitmq-conf
```
> Fix comsumer_timeout param by moving rabbitmq.config to rabbitmq.conf (location and format)

- environments/production/public.yml
Mainly surfacing so that we can take action on this, whether that is removing it or creating a ticket to investigate. 
https://github.com/dimagi/commcare-cloud/pull/3737 commented this out in what was supposed to be temporary, but must have gotten dropped. @dannyroberts I'm curious to hear your thoughts on if this is still something worth looking into or not. 
prod
> Remove commented out USE_KAFKA_SHORTEST_BACKLOG_PARTITIONER: true

- src/commcare_cloud/commands/inventory_lookup/getinventory.py
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
- tests/test_getinventory.py
Also show group names associated with each server
Sample output:
```
$ cchq staging lookup formplayer
10.201.10.18 - formplayer4, formplayer, all
10.201.10.139 - formplayer5, formplayer, all
```
Previous output:
```
$ cchq staging lookup formplayer
usage: cchq
{64-test,confluence,development,echis,enikshay-reference,india,jenkins,pna,production,staging,swiss} lookup
[-h] [server]
cchq
{64-test,confluence,development,echis,enikshay-reference,india,jenkins,pna,production,staging,swiss} lookup: error: 
There are 2 servers in the 'formplayer' group
Please specify the index of the server. Example: formplayer[0]
```
None.
> Make "lookup" command show all servers in group

- src/commcare_cloud/commands/terraform/aws.py
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/commands/terraform/templates/variables.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
Add support for Ubuntu Jammy 22.04 AWS AMI and remove obsolete
default images and variables or conditionals.
All
> Initial Ubuntu Jammy 22.04 AWS AMI support

- control/init.sh
Manish raised concern around the old virtualenv taking up unnecessary space which is totally fair. The only reason for not deleting the old directory was to facilitate reverting in urgent situations, but realistically the old virtualenv can be recreated easily, only adding a few additional minutes of setup.
I'm still in favor of keeping the name cchq-3.10 for the 3.10 venvs on 18.04 as a way to distinguish the unique setup that exists, and reserving `cchq` for default system python versions.
> Inform user that old virtualenv still exists

- environments/production/terraform.yml
- environments/staging/terraform.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/backup/main.tf
- src/commcare_cloud/terraform/modules/backup/variables.tf
and try it on staging (but keep disabled on production)
https://dimagi-dev.atlassian.net/browse/SAAS-13845
This doesn't actually affect production, it just lets me test the idea of quarterly backup retention on staging.
staging (for now)
> Add aws backup quarterly retention option

- environments/production/terraform.yml
I believe the use of the default value (30) was accidental.
production
> Set standard backup retention for {pgformplayer2,pgsynclog2}-production

- hosting_docs/source/installation/2-manual-install.rst
Manish brought up a good point that if someone is navigating these instructions step by step, they won't have the ability to run `update-code` or `manage-commcare-cloud configure`, nor will they need to. However I still want these instructions to apply to those who are retroactively upgrading to 3.10, so I've added a qualifier to state who should run those commands.
> Clarify which 3.10 directions are relevant for who

- environments/staging/public.yml
- hosting_docs/source/reference/1-commcare-cloud/commands.md
- src/commcare_cloud/commands/ansible/ansible_playbook.py
- src/commcare_cloud/commands/ansible/downtime.py
- src/commcare_cloud/commands/ansible/helpers.py
- src/commcare_cloud/commands/ansible/ops_tool.py
- src/commcare_cloud/commands/ansible/run_module.py
- src/commcare_cloud/commands/ansible/service.py
- src/commcare_cloud/commands/deploy/formplayer.py
- src/commcare_cloud/commands/migrations/copy_files.py
- src/commcare_cloud/commands/migrations/couchdb.py
- src/commcare_cloud/environment/main.py
- src/commcare_cloud/environment/secrets/backends/abstract_backend.py
- src/commcare_cloud/environment/secrets/backends/aws_secrets/main.py
Improve the efficiency of the test/development cycle for features that use ansible by allowing ansible commands to be executed against staging hosts directly from the development machine.
Previously ansible commands could not connect to AWS hosts unless they were run from the _control_ machine. `ProxyCommand` options can be used to route ansible SSH connections through an SSM session on _control_ machine (as a jump host) and then on to the target host. This feature is only enabled if the `COMMCARE_CLOUD_PROXY_SSM` environment variable is set to a non-empty string.
None.
> Ansible connect via AWS SSM through control host

- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
Add client_ip_preservation_enabled to AWS Global Accelerator endpoint,
which is now required by AWS for internal ALBs.
This option is already enforced by AWS on existing endpoints, so this
change won't affect any existing environment, but it will allow Terraform
to correctly create one without failing.
None
> Global Accelerator: preserve client IP addresses

- src/commcare_cloud/terraform/modules/backup/main.tf
https://dimagi-dev.atlassian.net/browse/SAAS-13845
This makes it so that every month at the same time EITHER a quarterly or a monthly backup is taken, where previously every third month BOTH a quarterly and a monthly backup were taken. The difference between the two is that the quarterly backups will be kept longer. (If quarterly backups are specified have a _shorter_ retention than the monthly backups, they fall back to being kept just as long as the monthly backups, so basically it gracefully degrades to quarterly backups == monthly backups.)
This has been applied on staging, using `cchq staging terraform init && cchq staging terraform apply -target module.backup_plan`, and will likewise be applied to production once merged.
> Make AWS Backup rules deduplicate monthly/quarterly backups

- hosting_docs/source/prereqs/5-requirements.rst
[Ticket](https://dimagi-dev.atlassian.net/browse/SC-2358)
Description:
This PR updates the [Hardware requirements section](https://commcare-cloud.readthedocs.io/en/latest/prereqs/5-requirements.html#hardware-requirements-and-deployment-options) in the deployment docs to state some system requirements in order to run HQ in docker locally for development purposes. Since we don't support running HQ in production using docker (yet), I'm only stating the minimum recommended requirements in order to run the containers.
None
> Add hardware requirements for running CommCareHQ in docker for development

- src/commcare_cloud/fab/diff_templates/console.txt.j2
- src/commcare_cloud/fab/utils.py
Fixed a typo and corrected the method rename introduced in 11b0931ce813d7f6c496ba2f70381bd924cd89d8.
```
Error getting changelogs: name '_get_file_content' is not defined. Please report this at https://forum.dimagi.com/c/developers/
```
None
> Fix issue with changelog output during deploy

- src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
A domain in prod is submitting forms larger than 100mb (the ES doc size limit), which are piling up in the pillow errors table, and painfully slow to retry. This increases the size limit so that those forms will successfully make it into ES.
All
> increase max_content_length

- environments/production/app-processes.yml
Scale back by one, from 3 to 2 (it was initially 1), and keep
prefetch_multiplier at 1 (it was initially absent).
Production
> Decrease submission_reprocessing_queue concurrency

- hosting_docs/source/reference/howto/wipe_persistent_data.rst
Couple of issues came up when we were following the documentation for rebuild on a test environment.
1. PG was not restarted post shut down to kill connections to execute data wipe. So that is now added
2. An initial migration is needed post wipe to setup tables before deploy. If this isn't done, deploy fails at `ensure_checkpoints_safe` task which needs `pillowtop_kafkacheckpoint` table to be present. So that is resolved by running the migrate_on_fresh_install playbook
None
> Fix rebuild commands

- src/commcare_cloud/commands/deploy/commcare.py
Currently the deploy script's deploy-diff feature is failing due to a bug in `_get_deployed_version` which produces below error. This fails silently so no one complained about this.
```
fatal: detected dubious ownership in repository at '/home/cchq/www/staging/releases/2023-01-11_06.14'
To add an exception for this directory, call:
git config --global --add safe.directory /home/cchq/www/staging/releases/2023-01-11_06.14non-zero return code
```
This is due to ansible not owning the current directory. This change fixes this by executing the command as cchq user.
> Fix git safe-directory warning bug that prevents deploy-diff feature

- src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml
Quick fix for the supervisor ansible role to work with Ubuntu 22.04.
The code can still be improved quite a lot, but the idea is to move
our custom services to systemd eventually, and drop this role entirely.
> supervisor ansible role update for Ubuntu 22.04

- changelog/0069-configure-java-17-for-formplayer.yml
- hosting_docs/source/changelog/0069-configure-java-17-for-formplayer.md
This PR is to fix an issue in the Changelog in which double curly braces, **{{**, get rendered as **{{ '{{' }}**. I couldn't find much on the web so I went for a hacky solution, I replaced the [code block](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#code-syntax-highlighting) with a [block break](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#block-breaks) (which can interpret HTML) and employed some inline styling to produce the same look as the code block. I will continue looking for a better option but in the meantime we can more comfortably release the instructions to 3rd parties.
> Fix Changelog issue related to rendering double curly braces

- src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml
Remove leftover copy_elasticsearch_upstart_result variable reference
from Elasticsearch restart task.
> Remove leftover elasticsearch_upstart reference

- Makefile
As the title explains, this was needed when supporting both 3.6 and 3.10, but since we have dropped support for 3.6, we do not need this special line in the makefile to ensure docs are formatted consistently regardless of using 3.6 or 3.10.
None
> Remove sed command from makefile (was used to support python 3.6)

- hosting_docs/source/reference/1-commcare-cloud/commands.md
This PR fixes the `commands.md` doc by regenerating it. What's interesting to me is that this time the generated text is different, meaning either 1. the previously generated docs were generated incorrectly or 2. I accidentally tampered with it (more likely, but I can't remember doing so)
N/A
> Fix the commands.md doc

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14317
This sets `autovacuum_vacuum_cost_limit` to the same value as `vacuum_cost_limit` , which is required as of postgres 14 in RDS, since it no longer defaults to `-1`, the setting to just use the value in `vacuum_cost_limit`.
Production
> set autovacuum_vacuum_cost_limit

- environments/production/app-processes.yml
- environments/production/elasticsearch.yml
- environments/production/public.yml
Production
This adds the XForm backfill pillow needed to process all changes that have happened since we kicked off the reindex.
I also noticed that our settings for the case search index were incorrect so updated them in a separate commit to reflect the actual state of production.
> xform backfill pillow

- environments/production/app-processes.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14330
Part of the switchover to the new index, this will stop running the backfill pillow
Production
> do not run xform backfill pillow

- src/commcare_cloud/ansible/commcare-audit.yml
- src/commcare_cloud/ansible/roles/commcare-audit/tasks/disk_usage.yml
- src/commcare_cloud/ansible/roles/commcare-audit/tasks/file_permissions.yml
- src/commcare_cloud/ansible/roles/commcare-audit/tasks/filesystem_health.yml
- src/commcare_cloud/ansible/roles/commcare-audit/tasks/main.yml
- src/commcare_cloud/commands/ansible/ops_tool.py
This PR is the same as [this one](https://github.com/dimagi/commcare-cloud/pull/5747), but with some fixes. It uses the same ticket as that PR, so please check out that PR to get the ticket. This PR basically just adds a filesystem healthcheck for all machines and saves the output in the host's folder that sits in the `~/.commcare-cloud/audits` directory. I also did a refactor of the commcare-audit ansible role.
All (Any)
> Refactor the commcare-audit role and add a filesystem healthcheck task

- src/commcare_cloud/commands/migrations/couchdb.py
- tests/test_couch_migration.py
Remote-to-remote authentication was broken when `PrivilegedCommand` was replaced with `run_ansible_module` in commit https://github.com/dimagi/commcare-cloud/commit/4285227c0832abd841f5dc41566086506a2fd5ee. `PrivilegedCommand` used `run_fab_task`, which used SSH agent forwarding in combination with `sudo -E` to facilitate remote-to-remote SSH connections. `setup_auth` configures SSH authentication between remote hosts.
https://dimagi-dev.atlassian.net/browse/SAAS-14368
:tropical_fish: Review commits individually.
None.
> Use setup_auth for couchdb-migrate rsync

- src/commcare_cloud/fab/fabfile.py
- src/commcare_cloud/fab/operations/db.py
All database migrations must be backward-compatible, so stopping services is unnecessary. Webworkers are not stopped, and they can do the same things that celery or pillow process do, so it does not make sense to treat pillow and celery processes specially. This should help to avoid deploy-related downtime that causes queue backups.
Service restart on error is no longer necessary since no services have been stopped at that point.
All.
> Do not stop celery and pillowtop before db migrate

- src/commcare_cloud/ansible/roles/rabbitmq/templates/rabbitmq.conf.j2
https://dimagi-dev.atlassian.net/browse/SAAS-14376
The recurring `repeat_record_queue` issues are strongly correlated with [heartbeat](https://www.rabbitmq.com/heartbeats.html) timeouts from rabbitmq, visible in the rabbitmq logs and as broken pipe errors in the celery logs, which appear to come from long running tasks. This PR seeks to remedy the issue by extending the heartbeat timeout, under the assumption that the celery workers failed to acknowledge the heartbeat pings because they were too busy processing those tasks and could not switch out of the greenlet in time. The new timeout was chosen to be longer than the problematic tasks, generally in the 300-400s range, but not so long as to be ineffective, since rabbitmq warns that too long a timeout can be problematic for message …
> increase rabbit heartbeat

- requirements.txt
- setup.py
Dependabot raised a [PR](https://github.com/dimagi/commcare-cloud/pull/5757) to update cryptography but tests were failing on it because the version of cryptography was not compatible with `pyopenssl`.
So this PR updates both `cryptography` and `pyopenssl`.
I am opening up this PR to see how tests behave with these changes.
There are a few breaking changes in the cryptography update but I am not sure if those affect us 🤔 
https://dimagi-dev.atlassian.net/browse/SAAS-14463
ALL
> Update cryptography and pyopenssl

- src/commcare_cloud/fab/fabfile.py
To allow "fab" commands to run without setting a release name. The release name they would have used previously was not meaningful.
All.
> Default release_name to NO_RELEASE

- src/commcare_cloud/ansible/library/setup_virtualenv.py
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/setup_release.yml
- src/commcare_cloud/fab/fabfile.py
- src/commcare_cloud/fab/operations/release.py
- tests/test_deploy/fake-venv-bin/pip
- tests/test_deploy/fake-venv-bin/pip-sync
- tests/test_deploy/fake-venv-bin/virtualenv-clone
- tests/test_deploy/test_setup_virtualenv.py
Step 2 in replacing Fabric with Ansible in commcare-hq deployment automation.
:tropical_fish: review by commit.
Tested on staging.
All.
> Ansible deploy HQ: part 2 - set up virtualenv

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Django 3.2.18 introduced a new setting, DATA_UPLOAD_MAX_NUMBER_FILES,
which defaults to 100.
Restore the previous behavior by setting it to None, leaving the
option for different per environment values.
https://dimagi-dev.atlassian.net/browse/SAAS-14469
All
> Set DATA_UPLOAD_MAX_NUMBER_FILES

- hosting_docs/source/reference/1-commcare-cloud/commands.md
- hosting_docs/source/reference/howto/tips.rst
- src/commcare_cloud/ansible/deploy_hq.yml
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/copy_release_files.yml
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/setup_release.yml
- src/commcare_cloud/commands/deploy/command.py
- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
- src/commcare_cloud/commands/preindex_views.py
- src/commcare_cloud/environment/main.py
- src/commcare_cloud/environment/remote.py
- src/commcare_cloud/fab/README.md
- src/commcare_cloud/fab/fabfile.py
- src/commcare_cloud/fab/operations/db.py
- src/commcare_cloud/fab/operations/release.py
- src/commcare_cloud/fab/utils.py
- tests/test_deploy/test_command.py
The `deploy` command argument `--setup-release` has been renamed to `--private`. Private releases are intended for running management commands, and therefore do not include static JavaScript files.
`preindex-views` now runs the management command in a tmux session rather than kicking it off in the background and returning immediately.
Tested locally in containers and with automated tests. Also tested on staging:
- private release (in which `./manage.py check_services` was run)
- `preindex-views`
- a full deploy.
All.
> Ansible deploy HQ: part 3 - remaining setup release tasks

- src/commcare_cloud/ansible/roles/bootstrap-machine/tasks/main.yml
Improves upon a general Ubuntu 22.04 improvement first attempted in https://github.com/dimagi/commcare-cloud/pull/5828.
Ubuntu 22.04
> Make "Set DIR_MODE for adduser" run on first time setup before users are created

- src/commcare_cloud/ansible/deploy_commcarehq.yml
Fixes issue first introduced in https://github.com/dimagi/commcare-cloud/pull/5723
all (fixes an issue that would have happened upon new formplayer machine setup on any env, but doesn't need to be applied to any working formplayer machine)
> Use become on "Formplayer Supervisor Config" due to order in which tasks are run

- src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14151
ES timeouts are linked to large and slow GC events. While the long term plan to reshard the case index still seems like the best way to prevent these memory spikes, ES [recommends](https://www.elastic.co/blog/a-heap-of-trouble) reducing heap size as a way to help keep GC events smaller, and heap usage on prod nodes never exceeds 24GB. Switching to G1GC may also help but ES does not recommend that until a higher version of the JDK than we currently run ES on, so it may be something to look into after the upgrade.
Production (could be all, but that is the only one with machines large enough to be affected)
> reduce ram for es heap

- src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
This code cleanup shouldn't affect Bionic, but makes it work on Jammy. The `python-*` installs are python 2 versions of things we now install using `python3-*`, and the `libreadline-dev` is already installed in the task right below it.
all (but it shouldn't have any affect)
> Remove redundant python2 installs that won't install on Jammy

- src/commcare_cloud/terraform/modules/backup/main.tf
This fixes a couple bugs in https://github.com/dimagi/commcare-cloud/pull/5791:
- Saturday cross region backups were being inadvertently excluded (this may be causing us to actually get charged **more** on Sundays because of a lack of a very-recent backup to piggyback off of, but that is just a hypothesis based on something I noticed in our cost data)
- On the first Sunday of the month, it wasn't deterministic whether it would do a Weekly backup or a Monthly/Quarterly backup.
> Fix recent aws backup changes

- src/commcare_cloud/ansible/library/clean_releases.py
- src/commcare_cloud/ansible/roles/commcarehq/tasks/git_repository.yml
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/clean_releases.yml
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/setup_release_common.yml
- src/commcare_cloud/commands/ansible/run_module.py
- src/commcare_cloud/commands/clean_releases.py
- tests/test_deploy/test_clean_releases.py
Reduce the number of places that need to know about the "git mirrors" directory:
- `clean_releases` and `list-releases` ignore hidden directories.
- People looking in the releases directory will be less likely to be confused because `.git_mirrors` is hidden from commands like `ls` by default.
This will have the side effect of breaking the git repositories in existing releases when `clean_releases` is run the first time after this is merged (it will delete the old `git_mirrors` directory). The only instance where this would likely matter is in a private release where someone was using git to update the release to a new version of the code. Probably the easiest  workaround there is to create a new private release and discard the old one. However, the following command can be used if a …
> Hide git mirrors directory

- src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
smspro.mtn.ci seems to have finally corrected their TLS configuration,
so we can remove the task that added the missing intermediate
certificate to the certifi CA bundle.
See also #4609
https://dimagi-dev.atlassian.net/browse/SAAS-12017
Note that this change won't actively remove the intermediate certificate
where installed, and I think it's ok to leave it until the next certifi update
and/or server rebuilding, which would remove it.
This avoids added complexity and another task to then go back to and
revisit/remove.
All
> Remove the addition of smspro intermediate cert

- src/commcare_cloud/ansible/roles/formplayer/defaults/main.yml
Introduced by https://github.com/dimagi/commcare-cloud/pull/5862/commits/54c291cd175f522d130c6ba399d134b0b9041967 of https://github.com/dimagi/commcare-cloud/pull/5862 
The scope where `release_name` is needed includes the `formplayer` role anywhere `formplayer_release_dir` or `_formplayer_target_dir` are referenced, which is currently only done by the main tasks file. This fix seems better than reverting the commit that introduce the issue since it maintains a more limited scope where `release_name` is set.
Fixes error on `cchq <env> deploy-stack`:
```
TASK [formplayer: Formplayer build dir] ***********
task path: .../commcare-cloud/src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml:98
fatal: [...]: FAILED! => {
"msg": "{{ formplayer_build_dir }}/releases/{{ release_name}}: …
```
> Add default release_name to formplayer role

- src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2
To suppoer ARM 64 Darwin architecture, updating the terraform lock file template.
> terraform lock file update for ARM64 darwin

- src/commcare_cloud/commands/deploy/commcare.py
This was missed when the deploy was converted from Fabric to Ansible.
All.
> Always pass unknown deploy args to Ansible

- hosting_docs/source/reference/1-commcare-cloud/commands.md
- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/commcarehq/vars/main.yml
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/setup_release_common.yml
- src/commcare_cloud/commands/deploy/command.py
- src/commcare_cloud/commands/deploy/commcare.py
Usually `localsettings.py` is copied directly from the previous release. Deploying with the new option will cause localsettings to be generated from the template. This is mainly intended to be used in private releases in conjunction with `--branch` for testing not-yet-deployed localsettings changes.
I am planning to use this while rolling out a new repeaters database.
Use with care on non-private releases. If an unexpected change is deployed it can be reverted with `cchq <env> deploy --resume=<previous-release>`.
This is an iteration on https://github.com/dimagi/commcare-cloud/pull/5824. Advantages of this approach:
- It's optional instead of the default.
- It updates localsettings after copying from the previous release, making the diff output meaningful.
Tested on staging.
All.
> Add option to update localsettings.py on deploy

- src/commcare_cloud/environment/secrets/backends/ansible_vault/main.py
We incorrectly opened the vault as a binary file and wrote to it as text.
All
> Fix write to ansible vault file

- environments/india/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Relates to https://github.com/dimagi/commcare-hq/pull/32969
This feature is no longer used and can be removed. The static UCRs that are removed in this PR no longer exist in commcare-hq which is why it is safe to remove.
> Remove UCR_COMPARISONS variable

- src/commcare_cloud/terraform/modules/logshipping/main.tf
https://dimagi-dev.atlassian.net/browse/SAAS-14607
We've applied this to other buckets in the past. No user-facing effect at all, just more cost effective.
> Enable intelligent tiering on log buckets

- environments/staging/terraform.yml
@shyamkumarlchauhan I noticed this discrepancy, where couch22-staging had been removed but was still mentioned in couch_alb-staging
staging
> Fix couch_alb-staging

- src/commcare_cloud/commands/deploy/commcare.py
https://dimagi.slack.com/archives/C0B44C0Q2/p1685566977608219
By grabbing the latest release from one django machine, we avoid the issue of a newly deploy machine with a different rev conflicting with the most recent deploy rev. My only hesitation is the potential for the newly deployed machine to be equivalent to django_manage[0] in certain scenarios, which would result in an incorrect diff.
> Only grab from first djangomanage machine

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
- src/commcare_cloud/environment/secrets/backends/ansible_vault/tests/expected-generated-variables.yml
- src/commcare_cloud/environment/secrets/backends/aws_secrets/tests/expected-generated-variables.yml
- src/commcare_cloud/environment/secrets/secrets.yml
This is for adding credentials file(JSON) of FCM to enable the capability of sending FCM Push Notifcations through HQ.
Jira Ticket : [INDIV-125](https://dimagi-dev.atlassian.net/browse/INDIV-125)
Design Document: [Link](https://docs.google.com/document/d/1m-atLS7gcPRKWWdPd_pW62JLfrW122hAxCkIVurWeyQ/edit#)
PR for the said feature:
https://github.com/dimagi/commcare-hq/pull/33047
All
[INDIV-125]: https://dimagi-dev.atlassian.net/browse/INDIV-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adds FCM creds to secrets

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
This is a follow up to this [PR](https://github.com/dimagi/commcare-cloud/pull/5982).
This is a minor change it to use json string directly instead of filter `to_json`.The required json contains `\n` characters and the said filter does not encodes it as `json.dumps` would do. This is turn causes an error.
Any other reccomendations are welcome.
All
> fcm creds load directly from json string

- src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.users.j2
- src/commcare_cloud/ansible/roles/postgresql_base/tasks/set_up_dbs.yml
Resolves an [issue](https://dimagi-dev.atlassian.net/browse/QA-5146) that occurred while rolling out https://github.com/dimagi/commcare-cloud/pull/5927
An alternate method of creating the user and assigning to the commcare role using `postgresql_user` and `postgresql_membership` Ansible commands was also implemented, but it was more verbose and had no obvious advantages over the more succinct `postgresql_query` task in this PR.
Tested with the following process:
```sh
cchq staging deploy --private --commcare-rev=dm/repeaters-db-split --branch=dm/repeaters-fdw-user
cchq staging downtime start
cchq staging ssh django_manage
sudo -iu cchq
cd /path/to/private/release
./manage.py migrate repeaters 0001_adjust_auth_field_format_squashed_0015_drop_connection_settings_fk
./manage.py migrate …
```
> Create user for postgres_fdw connections

- environments/india/postgresql.yml
- environments/india/public.yml
This is preparation for the first and second steps outlined in https://github.com/dimagi/commcare-hq/pull/33108
Apply with the following command:
```sh
cchq india ansible-playbook deploy_postgres.yml --tags=configure,remote_postgresql,pgbouncer --branch=dm/repeaters-db-india
```
To create the private release, use this command:
```sh
cchq india deploy --private --update-config --branch=dm/repeaters-db-india
```
This PR will be merged prior to running `update-config` to apply the new repeaters database routing to HQ services.
India
> Create repeaters database on India env

- src/commcare_cloud/ansible/roles/common/tasks/audit.yml
- src/commcare_cloud/ansible/roles/common/tasks/logging.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14661
This affects all machine types and change the default rsyslog configuration to rotate based on file size (instead of flat weekly) and check for rotation hourly (instead of daily).
The diff looks something like this (I removed repetition and names of machines)
```
TASK [common : Configure logrotate size limit in rsyslog (replacing weekly)] *********************************************************************************************************************************************************************************************************************************************************************************************
--- before: /etc/logrotate.d/rsyslog (content)
+++ after: /etc/logrotate.d/rsyslog (content)
@@ -14,7 +14,7 @@ …
```
> Make rsyslog and related logs rotate by size and check hourly

- environments/production/postgresql.yml
- environments/production/public.yml
This is preparation for the first and second steps outlined in https://github.com/dimagi/commcare-hq/pull/33108
Apply with the following command:
```sh
cchq production ansible-playbook deploy_postgres.yml --tags=remote_postgresql,pgbouncer --branch=dm/repeaters-db-production
```
To create the private release, use this command:
```sh
cchq production deploy --private --update-config --branch=dm/repeaters-db-production
```
This PR will be merged prior to running `update-config` to apply the new repeaters database routing to HQ services.
Production
> Create repeaters database on production env

- src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2
- src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
I did this locally while debugging something. It turned out not to be important, but then when I reverted it had altered the staging state in a way that wasn't backwards compatible.
This upgrade should be safe to do without much worry since it's a minor version. A simple run through works fine locally.
saas
> Upgrade hashicorp/aws to 4.67.0

- environments/india/app-processes.yml
https://github.com/dimagi/commcare-hq/pull/33047
Recently ID added a feature that relies on case pillow to process cases at an acceptable speed. Currently, India has a [pillow lag](https://app.datadoghq.com/dashboard/ewu-jyr-udt/change-feeds-pillows?fullscreen_end_ts=1687869307269&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1687696507269&fullscreen_widget=3845479150817126&tpl_var_env%5B0%5D=india&from_ts=1687868402253&to_ts=1687869302253&live=true) of order of minutes & at times an hour+. This is suspected to be due to low load on India.
The change here makes case pillow process cases right away instead of in chunks, which [waits](https://github.com/dimagi/commcare-hq/blob/20b1f6539d62a361a9f40fddd26a245a7b3a0404/corehq/ex-submodules/pillowtop/pillow/interface.p …
> Set india case pillow to not process cases in chunks

- environments/india/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14659
Having already rolled out https://github.com/dimagi/commcare-cloud/pull/6009 on staging, this PR does the same to india.
I'm choosing to downsize at the same time, because right now the memory usage such that there will not be evictions for a long time, whereas the point of this change is to change the eviction strategy to a preferable one. Since downsizing it is necessary for this change to have any immediate effect and since doing these together allows us to have only one (potentially lightly disruptive) restart instead of two, I decided to bundle them into one changeset to be applied together.
india
> Use maxmemory-policy=allkeys-lru on india redis and downsize

- environments/india/app-processes.yml
Reverts dimagi/commcare-cloud#6011
Using 0 resulted for `processor-chunk-size` resulted in the param to be ignored due to if condition [here](https://github.com/dimagi/commcare-cloud/blob/a6ee9daf0d05009c75872da1e4e9897425153bc8/src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_pillowtop.conf.j2#L12).
So 1 should be used instead
> Revert & Correct "Set india case pillow to not process cases in chunks"

- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_flower.conf.j2
This is a recent change in flower which does not allows the unauthenticated API requests. Since we use flower inside VPC so it makes sense for us to not care about the change and continue using the way we were using Flower APIs before.
setting `FLOWER_UNAUTHENTICATED_API` to true will bypass the recent authentication added to the APIs.
I have put the changes on staging and flower metrics are back on datadog.
ALL
> set FLOWER_UNAUTHENTICATED_API to true

- environments/production/app-processes.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14708
Put all production case-pillow processes on one machine, and move xform-pillow onto the other machine.
This is meant to simplify the configuration and to eliminate observed lag discrepancies between kafka case-sql topic partitions being processed on one machine versus the other.
I took a look at the history, and the way it ended up the way it is looks more _ad hoc_ than intentional, as the original split was followed by a number of reorganizations and changes in `num_processes`.
- Original split: https://github.com/dimagi/commcare-cloud/pull/5131
- Further split over three machines: https://github.com/dimagi/commcare-cloud/pull/5138
- Reduce `num_processes` and partially consolidate: https://github.com/dimagi/commcare-cloud/pull/5141 …
> Put all production case-pillow processes on one machine

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14659
This is along the same lines as the similar commit in https://github.com/dimagi/commcare-cloud/pull/6022, but one size smaller.
production
> Downsize production elasticache cluster (again) to cache.r6g.large

- environments/production/elasticsearch.yml
https://dimagi-dev.atlassian.net/browse/SAAS-12152
Production
I will be running this after this is applied to recreate secondary index with the shards info.
```
from corehq.apps.es.client import manager
from corehq.apps.es import case_adapter as adapter
from corehq.apps.es.migration_operations import CreateIndex
manager.index_delete(adapter.secondary.index_name)
CreateIndex(
adapter.secondary.index_name,
adapter.type,
adapter.mapping,
adapter.analysis,
adapter.settings_key,
).run()
```
> Update case index shards to 32

- environments/staging/terraform.yml
t3a.xlarge => t3a.large
There's no big story behind this; I just came across it and noticed these machines were larger than they needed to be.
staging
> Downsize staging webworkers

- requirements.txt
The commcare-cloud build has been failing for about 4 days. This was a shot in the dark, but it looks like it worked to fix the build.
The idea came from this section in the ongoing commcare-cloud build failure:
```
Collecting pyyaml==5.4.1 (from -r /tmp/tmp_2plar3l (line 45))
Downloading PyYAML-5.4.1.tar.gz (175 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 46.3 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
```
It wasn't obvious to me just from the text that pyyaml was the cause of the error that followed (as opposed to just being coincidentally close to when it …
> Bump pyyaml from 5.4.1 to 6.0.1 (to fix the build)

- environments/staging/app-processes.yml
leaving instructions for how to re-enable when temporarily needed for something.
The motivation here is to clean up datadog features we don't use so we don't get charged for them.
staging
> Switch to disabling APM on staging formplayer

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
I came across this when looking for datadog metrics in elasticsearch code. Looks like it was built for ICDS, and it's not enabled for any Dimagi envs or documented anywhere that I could find, so it feels pretty safe to remove.
See also https://github.com/dimagi/commcare-hq/pull/33281
None that I'm aware of, though it's possible third party environments have turned this on if they grepped through the codebase.
> Remove unused ICDS metric

- environments/production/aws-resources.yml
- environments/production/inventory.ini
- environments/production/inventory.ini.j2
- environments/production/terraform.yml
**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14750
> Change instance type of production Mobile Webworkers to m6a.2xlarge

- environments/staging/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
This allows setting a URL for ConnectID in HQ's localsettings, but only sets it for staging. It will be used for single sign on workflows, to verify tokens from ConnectID
Staging
> add connectid url

- environments/production/public.yml
Link to ticket [here](https://dimagi-dev.atlassian.net/browse/SC-2995).
A project is in the process of moving from producton to a self-hosted instance of CommCare. A step in this process involves adding their domain to the old environment's `public.yml` file (production in this case).
Production
> Add domain to alternate hosts in production public.yml

- .github/workflows/linter.yml
This adds the new linter(s) to the repo, lint-action and action-eslint.
See [this commcarehq PR](https://github.com/dimagi/commcare-hq/pull/33280) as example usage. 
In addition to the linked PR I also verified the following scenarios:
1. No .py or .js file changes should not run the linters (the jobs does run until it determines there's not relevant files to lint over).
2. If a linter is not run it should green check that particular linting job.
3. If only .js files changed only eslint should run and flake8 should not be invoked (green check it by default).
4. If only .py files changed only flake8 should run and eslint should not be invoked (green check it by default).
5. If a linter fails the PR can still be merged.
> Add action-eslint and lint-action

- .github/workflows/linter.yml
3.10 was being interpreted as a number, 3.1, instead of a string "3.10"
Noticed this error on https://github.com/dimagi/commcare-cloud/pull/6092. Not sure why this wouldn't have been pervasive on all PRs in the last two weeks.
None
> Fix python version specification in linter action

- src/commcare_cloud/ansible/restart_webworker_services.yml
Current HQ deploy fails due to rolling restart trying a restart on the full set of webworkers under `production_commcare_submissions` block.
This change would help with a smaller blocks
This would just cause a slightly longer deploy (~1 minute)
Using https://github.com/dimagi/commcare-cloud/pull/5852/files/f66001d7386ea30437e99a2093415f2a31d6702b#diff-3d7593c6d6f4d6c05a0a5c9a194301e3eaec3cc436f730dfa64b233fa5102054R3 as the guide to ensure that the change should be safe
All
> Updates to avoid big last batch

- src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
Beginning in recent versions of couch, the new default configuration file has couch bind only to localhost. This change removes that default so that it binds all (previous default) for external access within the network as well.
This change was initially incorporated as a manual step in the procedure; this PR automates that manual step.
All
> Make couch bind not just to localhost

- src/commcare_cloud/ansible/deploy_commcarehq.yml
- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/formplayer.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/management_commands.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/pillowtop.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/prometheus.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/prometheus_django_runner.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/proxy_websockets.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/webworkers.yml
- src/commcare_cloud/ansible/roles/commcarehq/vars/main.yml
- src/commcare_cloud/ansible/roles/supervisor/templates/supervisor_task.conf.j2
https://dimagi-dev.atlassian.net/browse/SAAS-14853?focusedCommentId=284526
This change prevents an issue that can happen when moving certain processes between machines; types of processes affected by this issue include: celery beat, celery flower, and the management commands, at least. The issue was that on the machine that is no longer supposed to have the process, the corresponding supervisor service file is simply _abandoned_, rather than deleted, which means it ends up running in both the old and new locations.
To fix this, this PR takes logic that was strewn through multiple files and centralizes it. Critically, it centralizes the logic dictating whether each individual service file is supposed to exist on a given machine or not. This allows the process that sweeps the service file …
> Fix supervisor service file management

- src/commcare_cloud/ansible/roles/elasticsearch/templates/systemd/elasticsearch.service.j2
The ES 5 was not respecting the config path and jvm options need to be specifically defined using Environment variable ES_JVM_OPTIONS
All
> Add jvm option path

- src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14864
I have tested out the changes on django-manage machine and ran `cchq --control staging deploy-stack --limit=web13 --tags=python --branch=ap/update-python-to-latest-patch`.
The command ran fine without any errors and changes were applied without any issues. 
After that I verified on django-manage machine that we got the latest patched python version
```
(staging) aphulera@web13-staging:~$ python3.9 --version
Python 3.9.18
```
However we have 3.9.16 on other machines, for eg - in Web14
```
(staging) aphulera@web14-staging:~$ python3.9 --version
Python 3.9.16
```
All
> Always install latest patch version of python

- src/commcare_cloud/commands/terraform/aws.py
https://dimagi-dev.atlassian.net/browse/SAAS-14935
AWS sso login recently changed to include a verification code to ensure the device that requested the login is the same as the one you are allowing authentication for. We used `check_output` to call `aws sso login`, which swallows the output and does not wait for the command to finish, meaning users could not verify the matching code. By switching to `subprocess.run`, we are able to see the command output as if running it directly, and therefore can verify the code.
None
> Use subprocess.run instead of check_output

- src/commcare_cloud/commands/ansible/ansible_playbook.py
It's confusing to get a "that option is managed automatically" error when attempting to run with --check. The operator is forced to guess how to accomplish a --check run when lacking a thorough understanding of how the automatic option management works. It seems appropriate to perform a single --check run if that was requested by the operator.
The situation is similar for --diff, although a duplicate option does not cause harm and does not change the run mode.
None.
> Allow --check and be less strict about --diff

- src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml
Noticed as part of recent maintenance that when run with `--tags=es_conf`, a change to elasticsearch's .service file made by the previous task does not cause a service reload like it should.
none in particular
> Make es_conf include elasticsearch service reload-daemon logic

- src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
Since we have reindexed all the environments, now we don't need to enable inline script updates on our cluster
All
Will run deploy-stack on all environments to disable the it.
> disable inline script updates in elasticsearch

- environments/production/migrations/0009-move-to-3-jammy-nodes/couchdb-step-1.yml
- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14844
- Step 0: https://github.com/dimagi/commcare-cloud/pull/6108
- **Step 1: https://github.com/dimagi/commcare-cloud/pull/6116**
- Step 2: https://github.com/dimagi/commcare-cloud/pull/6117
- Step 3: https://github.com/dimagi/commcare-cloud/pull/6124
- Step 4: https://github.com/dimagi/commcare-cloud/pull/6110
This PR will be applied using Phase 2 of https://confluence.dimagi.com/display/saas/Replace+a+Couch+node+in+Couch+cluster (applied to just this one node replacement).
production
> Replace production couch node 1

- environments/production/public.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14929
During COVID times, we [disabled formplayer DB compression](https://github.com/dimagi/commcare-cloud/pull/3997) as a tradeoff to increase performance (decompressing the database takes time). We now find ourselves in a steadier state, but disk usage across formplayer machines is nearing its limit. There are quite a few very large user DBs, so the hope is that by reintroducing this compression, we will free up enough disk space to make a meaningful difference.
We chose 3 days as the inactive threshold to ensure a more random distribution of decompressing DBs. We wanted to avoid "stampede effects", where users log on at the same time every morning and have to wait for their DB to be decompressed, or similarly log on Monday morning after the …
> Re-enable compressing formplayer DBs on production

- src/commcare_cloud/ansible/ansible.cfg
as recommended in https://github.com/ansible/awx/issues/14496. Fixes an incompatability with a change from today
Discovered from the broken build in https://github.com/dimagi/commcare-cloud/pull/6117.
None
> Set default ansible-galaxy url to legacy format endpoint

- environments/production/terraform.yml
Reverts one change done in https://github.com/dimagi/commcare-cloud/pull/6117, adds back `couch12` to target groups to match the state of production.
More details in https://dimagi-dev.atlassian.net/browse/SAAS-14844?focusedCommentId=290024
Production
> revert target nodes in couch target groups in load balancer

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-14844
This node is not currently in active use, and this will lower our costs until we're ready for it again.
production
> Downsize couch_a1-production again

- environments/64-test/public.yml
- environments/india/public.yml
- environments/pna/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/group_vars/all.yml
Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14988
All env will be affected: Staging, India, Swiss, Production
This is already deployed to staging.
I will run update-config, and restart service, to india, swiss and production, after this PR is approved and merged.
> Remove billing support email

- requirements.txt
https://dimagi-dev.atlassian.net/browse/SAAS-15034
gevent is only used by couchdb-cluster-admin which is used in the `couchdb-cluster-info` command. I ran `cchq --control staging couchdb-cluster-info --branch=gh/upgrade-gevent` on staging to make sure it still works, which it does.
None
> Update gevent (used by couchdb-cluster-admin)

- environments/production/terraform.yml
**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-15020 
**Environments Affected :** production
> Downsizing django_manage from m6a.xlarge_to_r6a.large in production

- .readthedocs.yml
I thought tools might not be required in https://github.com/dimagi/commcare-cloud/pull/6158, but it seems it is required in the doc config.
> Fix readthedocs - Add python version

- docs/source/scaling/2-webworkers.rst
- docs/source/scaling/3-postgres.rst
- docs/source/scaling/4-redis.rst
- docs/source/scaling/5-elasticsearch.rst
- docs/source/scaling/6-sizing-buckets.rst
I noticed these docs appeared when searching for "elasticsearch" in commcare-cloud docs. Given these docs are incomplete, we should prevent them from appearing in the search results. Adding the `:nosearch:` directive seems to do the trick. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html for more info on this directive.
Before:
After:
None
> Add nosearch directive for incomplete scaling docs

- environments/staging/public.yml
https://dimagi-dev.atlassian.net/browse/QA-5808
The use of this setting hasn't been deployed to any environments yet, but I want to set it to 2 for staging to test the change with QA. See the ticket above for more context.
Staging
> Add MAX_MOBILE_UCR_LIMIT of 2 to staging settings

- environments/production/terraform.yml
**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-15129
> Downsizing pgshard1-production from db.m5.2xlarge to db.m5.xlarge

- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/server/main.tf
- src/commcare_cloud/terraform/modules/server/variables.tf
https://dimagi-dev.atlassian.net/browse/SAAS-15177
The syntax is
```
servers:
- ...
additional_tags:
<tag_name>: <tag_value>
```
e.g.
```
- server_name: "proxy6-staging"
server_instance_type: "t3a.medium"
network_tier: "app-private"
az: "b"
volume_size: 80
volume_type: "gp3"
volume_encrypted: yes
group: "proxy"
os: jammy
additional_tags:
MyTag: test
```
None (just enables us to do this when we want)
> Allow us to set custom tags on individual servers via terraform

- src/commcare_cloud/commands/terraform/constants.py
https://github.com/dimagi/commcare-hq/pull/33798
https://docs.google.com/document/d/1TXplH3kNAONMWRmOWoObApzBtyniIehsxX6Ehc_jGho/edit
This adds WAF rules for Rich Text emails which save HTML from the frontend. 
It also adds an extra WAF rule that seems to not have been taken into account before. 
Production
> Add WAF rules for Rich Text Emails

- environments/production/terraform.yml
https://dimagi-dev.atlassian.net/browse/SAAS-15129
We're unhappy with the performance of the smaller configuration (`db.m*.xlarge`) so we're going to revert to the original larger one (`db.m*.2xlarge`). The use of m6g for some machines but not others is intentionally chosen to optimize our RI usage.
production
> Revert to larger pgshard nodes using m6g where cost-optimal

- src/commcare_cloud/terraform/modules/network/main.tf
https://dimagi-dev.atlassian.net/browse/SAAS-14154
During the terraform upgrade to 0.12, the defaults were accidently removed, this PR attempts to fix that.
See the comment - https://github.com/dimagi/commcare-cloud/pull/4849/files#r1023369662
The changes have been tested out while setting up backup-production environment recently.
All
> Add defaults for route table

- docs/source/reference/0-index.rst
- docs/source/reference/6-settings.rst
Adds reference documentation about the email addresses that are set in `public.yml`.
Context: [SC-3136](https://dimagi-dev.atlassian.net/browse/SC-3136)
None
Not applicable
[SC-3136]: https://dimagi-dev.atlassian.net/browse/SC-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Document email addresses set in `public.yml`

- quick_monolith_install/sample-environment/public.yml.j2
This change simply adds `couchdb_version` to the sample environment's public.yml file as per [this changelog](https://commcare-cloud.readthedocs.io/en/latest/changelog/0071-upgrade_to_ubuntu_22.04.html); the assumption is that any new project spinning up a new environment from this point on will use Ubuntu 22.04 as per the [prerequisites](https://commcare-cloud.readthedocs.io/en/latest/installation/1-quick-monolith-install.html?#prerequisites).
All newly installed environments.
> Add couchdb_version entry to sample env public.yml

- quick_monolith_install/sample-environment/postgresql.yml
- quick_monolith_install/sample-environment/public.yml.j2
This change only affects the quick_monolith_install script. It follows on from #6201
It updates the environment settings for running a monolith on Ubuntu 22.04, and aligns with corresponding updates to the sample environment config [here](https://github.com/dimagi/sample-environment/pull/16) and [here](https://github.com/dimagi/sample-environment/pull/18).
None
> Update quick_monolith_install script with settings for Ubuntu 22.04

- docs/requirements.txt
Updates to ReadTheDocs are failing because
```
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
More context: https://readthedocs.org/projects/commcare-cloud/builds/23167204/
None. Affects docs only.
> Fix Sphinx version error

- src/commcare_cloud/ansible/wipe_kafka.yml
Even when a task is skipped, information is still registered to the specified variable, which means this previously only worked for versions of kafka <= 0.9, since that was the last task to update `kafka_output`.
None
> Register different variable names depending on kafka version (wipe_kafka.yml)

- src/commcare_cloud/ansible/migrate_on_fresh_install.yml
We have a RequestReindex command that is used in a migration to specify that couch views should be reindexed. On fresh install, this will run because of [this migration](https://github.com/dimagi/commcare-hq/blob/master/corehq/preindex/migrations/0001_initial.py).
None
> Sync couch views happens as part of migrate_multi now

- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/deploy/formplayer.py
- src/commcare_cloud/commands/deploy/utils.py
I deployed formplayer at a non ideal time, and realized the existing maintenance window check we have for commcare deploys is not used for formplayer. This PR reuses that code for formplayer deploys as well.
Tested on production:
None
> Reuse maintenance window check for formplayer deploys

- docs/source/installation/migration/1-migrating-project.rst
A small doc fix that removes the command that do not exist anymore and is not required.
All
> Remove obsolete command `ptop_es_manage`

- src/commcare_cloud/commands/terraform/constants.py
Add WAF rule for project basic settings in which a custom logo is uploaded.
Ticket: https://dimagi-dev.atlassian.net/browse/USH-4025
Commcare-HQ PR: https://github.com/dimagi/commcare-hq/pull/34017
Production, India and Staging
> WAF whitelist XSS_BODY for logo upload

- docs/source/installation/migration/1-migrating-project.rst
- docs/source/reference/howto/wipe_persistent_data.rst
After going through this process a number of times, this is where I've landed. I've tried to simplify the steps (take out what seemed unnecessary), and added/updated anything that caused issues but was needed.
None
> Update documentation around migrating data

- docs/source/reference/howto/wipe_persistent_data.rst
This line is also necessary when "resetting" kafka once it has gotten into a broken state. I don't love that I hard code the paths here since theoretically a self hoster could setup a different path, but hopefully they would be aware of that and able to make the necessary change for their own system.
None
> Add removing kafka data for debugging kafka issues

- environments/india/app-processes.yml
The reminder_queue on India is [severely backed up](https://app.datadoghq.com/dashboard/bdu-k5b-bz5/celery-overview?fullscreen_end_ts=1707500480060&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1702143680060&fullscreen_widget=185712938&index=&refresh_mode=sliding&tpl_var_celery_queue%5B0%5D=reminder_queue&tpl_var_environment%5B0%5D=india&view=spans&from_ts=1702143675000&to_ts=1707500475000&live=true). This is an attempt to see if bumping concurrency makes any meaningful change to this issue.
Based on the average load celery8 and celery9 are currently experiencing, this is a safe operation.
India
> Increase concurrency on reminder_queue for india

- environments/india/app-processes.yml
We are not maxing out CPU or memory on the india celery machines that have reminder_queue workers, so we want to get more out of our current resources.
Once merged, I will run `cchq --control india update-supervisor-confs --limit=celery`
India
> Bump reminder_queue concurrency to 100

- environments/india/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
https://dimagi.atlassian.net/browse/SAAS-15294
We've been seeing timeout issues on the India environment, likely due to some long running tasks on the `reminder_queue`. My understanding is that [this code](https://github.com/dimagi/commcare-cloud/blob/3c579e8885e72346cfb91062fbd0e8436db470ae/src/commcare_cloud/ansible/roles/rabbitmq/templates/rabbitmq.conf.j2#L6-L6) sets the timeout on the server side (from rabbitmq's perspective), but the client (celery) also specifies a timeout value, and rabbit and celery agree to use the lower of the two values (docs [here](https://www.rabbitmq.com/heartbeats.html#heartbeats-timeout)).
So this PR's aim to specify the [broker_heartbeat](https://docs.celeryq.dev/en/v5.2.7/userguide/configuration.html#broker-heartbeat) value from celery's side so that …
> [India] Set broker heartbeat to match timeout specified in rabbitmq.conf

- environments/production/public.yml
Link to ticket [here](https://dimagi.atlassian.net/browse/SC-3498).
This change is part of an urgent request to rebuild a UCR datasource. To help speed up the process, we are increasing the amount of indicators that can be queued to 20k (default is 10k).
production
> Increase Indicator Queue Count Variable

- docs/README.md
- docs/source/prereqs/2-architecture.rst
[Ticket](https://dimagi.atlassian.net/browse/SC-3138)
This is a documentation update
None
> Add link to platform overview in docs

- docs/source/installation/migration/1-migrating-project.rst
- docs/source/installation/migration/2-migrating-instance.rst
- docs/source/reference/howto/wipe_persistent_data.rst
I forgot I had https://github.com/dimagi/commcare-cloud/pull/6216 open which has some overlapping changes. I'm going to move forward with this one first, and then resolve the conflicts on that PR separately.
There were a couple of defective links that I resolved as well as making it more clear to readers that services should not be started back up until after loading data into the new environment. I also replaced the deploy step with a simple downtime end call because a deploy step is now included when starting the steps for rebuilding an environment.
None
> Various documentation updates for data migration

- environments/staging/public.yml
No ticket, I just noticed that the link to the analytics server is broken. We have a staging instance, but staging doesn't point to that. This update should fix this.
Staging
No announcement needed, since this is staging
> Update COMMCARE_ANALYTICS_HOST for staging to point to the staging host

- src/commcare_cloud/ansible/roles/deploy_hq/tasks/staticfiles_collect.yml
See https://github.com/dimagi/commcare-hq/pull/34346 - once that PR is merged, this can be merged.
Once this is merged, https://github.com/dimagi/commcare-hq/pull/34349 will drop the param from the script.
None, this is a change to the deploy process
This does not need to be announced
> Removed second run of build_requirejs from staticfiles_collect.yml

- environments/production/public.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
- src/commcare_cloud/ansible/roles/formplayer/vars/main.yml
Change request: https://dimagi.atlassian.net/browse/SAAS-15447
Update DB connection pool configuration on production:
- maximum-pool-size
- Change from the default of 10 to 20 to better handle peak usage
- minimum-idle
- Change from the default of 10 to 5 to reduce off peak DB connections and connections from instances receiving less requests
Config options docs: https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#gear-configuration-knobs-baby
Production
> add custom properties to fomplayer config for DB connection pool

- environments/production/app-processes.yml
- src/commcare_cloud/ansible/roles/commcarehq/tasks/webworkers.yml
https://dimagi.atlassian.net/browse/SAAS-15465
This will only affect `mobile_webworkers` on production. I have tested that running update-supervisor-confs with this code (in check mode) does not result in any changes to any other supervisor conf files.
Here's what the change to each mobile_webworkers supervisor conf file looks like:
```
--- before: /home/cchq/www/production/services/production_supervisor_django.conf
+++ after: /home/droberts/.ansible/tmp/ansible-local-3337219uxey0k3z/tmpittijtka/supervisor_django.conf.j2
@@ -1,8 +1,8 @@
[program:commcare-hq-production-django]
directory=/home/cchq/www/production/current/
; gunicorn
-environment=TMPDIR="/opt/tmp",DATADOG_PATCH_MODULES="requests:true,gevent:true,psycopg:true,redis:true,sqlalchemy:true,elasticsearch:true",DATADOG_ENV="producti …
```
> Enable datadog APM on production mobile_webworkers

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-15471
Prod
> Change mobile workers instance type from `m6a.2xlarge` to `c6a.4xlarge`

- environments/production/public.yml
Follow up to https://github.com/dimagi/commcare-cloud/pull/6256.
At high enough load, these formplayer db connections are the clear bottleneck, with some machines using all 20, creating a pileup of requests waiting for connections. Likely harmless to go higher than 40, as pgbouncer is gatekeeping the actual connections to postgresql, but starting here to be safe.
production
> Increase production formplayer database connection pool size from 20 to 40

- src/commcare_cloud/ansible/roles/datadog/tasks/main.yml
https://dimagi.atlassian.net/browse/SAAS-15487
Clayton and I have a hypothesis that the current version of dd-java-agent we're on doesn't manage its memory very well. Regardless, it's good to be on a more recent version.
Apply with
```
cchq <env> deploy-stack --tags=datadog
```
production
> Update dd-java-agent.jar to 1.33.0 w/ explicit pinning and checksum

- environments/staging/public.yml
Ticket: https://dimagi.atlassian.net/browse/SAAS-15476
It seems like, any email sent to accounts@dimagi.org will create a SALES ticket. It might create noise for ops work. So we want to replace this email with dev+accounts@dimagi.org
Staging
> Update accounts_email for staging

- environments/production/terraform.yml
Doubles formplayer disk to ensure that we don't run out of space in load tests.
Production
> Double formplayer disk and make it 140 GB

- changelog/0080-copy-invitation-supply-point-fields-to-location.yml
- docs/source/changelog/0080-copy-invitation-supply-point-fields-to-location.md
Follow up to this [forum post](https://forum.dimagi.com/t/unable-to-deploy-prod-stable-b23df94-25-apr-2024/10754/3) to correct the previous released [PR](https://github.com/dimagi/commcare-cloud/pull/6277).
Non-Dimagi
> Corrects Changelog

- environments/production/terraform.yml
We want to have enough disk space for reindexing the case search index. This also makes all data nodes a consistent size.
Production
> Increase ES data nodes to 2800 GB

- environments/staging/public.yml
- src/commcare_cloud/ansible/deploy_hq.yml
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/run_webpack.yml
Associated ticket: https://dimagi.atlassian.net/browse/SAAS-15485
Adds support for running webpack while deploying HQ, if a webpack configuration file is found. This is not currently required by any live code, but allows us to test react and vue (and other javascript features) in the future
> Added webpack to the HQ deploy process

- src/commcare_cloud/ansible/roles/deploy_hq/tasks/run_webpack.yml
Staging (only if webpack is being used)
Changed the webpack command from `yarn build:react` to `yarn build:webpack` to be more accommodating if we use some framework other than React.
> Changed webpack command to be more generic

- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
This updates the formplayer configuration settings:
```diff
- sqlite.tmpDataDir=tmp_dbs/
+ sqlite.tmpDataDir=/opt/data/formplayer/tmp_dbs/
```
The impact of this is that formplayer will no longer store the temporary sqlite database relative to the release folder but will store them in the data directory. These DBs are used to store case search result data.
This is beneficial for two reasons:
1. Keep all user data together and on the drive with encryption and sized for user data
2. Persist tmp DBs across deploys (currently they are relative to the current release)
ALL
Post deploy steps (optional):
* Remove tmp_dbs from the current releases
> move formplayer sqlite temp DBs to the data directory

- environments/india/fab-settings.yml
Enables publication of india deploy events to the dimagi-qa repo, which will cause QA tests to run.
In addition to this PR, a new _dimagi-qa-india-deploy-event_ token was created on the @dimagi/qa account, and the [confluence page](https://confluence.dimagi.com/display/saas/SaaS+Env+Secrets+and+Accounts) was updated. The value of that token was set on the india `deploy_event_token` secret.
india
> Add deploy_event_url for India

- environments/staging/terraform.yml
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/backup/main.tf
- src/commcare_cloud/terraform/modules/backup/variables.tf
**Ticket :** https://dimagi.atlassian.net/browse/SAAS-15185
> Configure EBS_snapshot_archive using terraform

- environments/staging/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Adding this PR to test a separate index for `co-carecoordination-test` on staging env.
staging
> Starting syncing writes to sub-index of case-search on staging

- environments/production/public.yml
Enables multiplexer for `care-coordination` domain so that writes happen to both case_search and case_search_bha index 
Production
> Config to start multiplexing writes to case-search sub-index in Prod

- environments/production/postgresql.yml
https://dimagi.atlassian.net/browse/SAAS-15320
We don't need to run pg_repack on this machine anymore since we use partitioned tables that we periodically drop (so pg_repack isn't useful).
Production
> Remove pg_repack from pgbouncer_a6

- src/commcare_cloud/ansible/cleanup_pg_repack.yml
https://dimagi.atlassian.net/browse/SAAS-15320
I don't have plans to merge this PR, but wanted to get it reviewed before running. As Danny noted [here](https://dimagi.atlassian.net/browse/SAAS-15320?focusedCommentId=313527), we don't actually need to have pg_repack running on this database anymore since the entire point of partitioning this db is to make it easy to drop tables. The current working theory is that pg_repack runs are changing the table ownership to root, and making it impossible for our periodic celery task to drop these tables. After running this to disable pg_repack, we should be able to change the table ownership manually and have the celery task successfully drop tables again.
Production
> Add playbook to cleanup pg_repack on pgbouncer_a6

- environments/production/public.yml
Update production settings to start multiplexing case search writes to the dedicated bha index for co-carecoordination-perf.
Production
> Add co-carecoordination-perf domain to case_search_bha

- environments/staging/public.yml
No ticket.
Sending email to dev+accounts@dimagi.com will spam every tech people's email folder. So we decided send to commcarehq-ops+accounts@dimagi.com as discussed in product meeting.
Will update-config after it is merged.
Staging
> Update accounts email on staging

- docs/source/index.rst
- docs/source/installation/index.rst
- docs/source/reference/0-index.rst
- docs/source/reference/howto/index.rst
- docs/source/scaling/1-index.rst
Small documentation clean-up.
This is a prefactor before adding to documentation based on lessons learned from a recent data migration.
None. Documentation-only changes
> Prefactor: Small doc clean-up

- environments/production/app-processes.yml
Case pillows were put onto their own machine to prevent other pillows from disrupting case updates. I added 4 processes back to pillow_a2000 yesterday in hopes of adding some additional processing power, but it didn't realistically make enough of a difference to warrant permanently keeping that change.
Additionally, we've [already observed pillow lag](https://app.datadoghq.com/dashboard/ewu-jyr-udt/change-feeds-pillows?fromUser=true&fullscreen_end_ts=1718200654624&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_section=overview&fullscreen_start_ts=1718194256413&fullscreen_widget=210889790&refresh_mode=paused&view=spans&from_ts=1718194256413&to_ts=1718200654624&live=false) isolated to 6 specific partitions (which correlates with 1 process being behind since 1 process is …
> Remove additional pillow processes from pillow_a2000

- src/commcare_cloud/commands/deploy/utils.py
Context: [Forum](https://forum.dimagi.com/t/email-error-when-deploying/10812)
Email notifications of both the start of a deploy, and of a failed deploy, have empty message bodies. Azure Communication Services rejects emails with empty message bodies with the following exception:
> smtplib.SMTPDataError: (501, b'5.6.0 Request body validation error. Need either non-empty Html or PlainText body to be present.')
Only affects environments that use Azure Communication Services for SMTP. No Dimagi environments are affected.
> Ensure that SMTP message body is not empty

- environments/production/app-processes.yml
This is intended to deal with spikes in the repeat_record_queue better.
Context:
* [Slack](https://dimagi.slack.com/archives/C0B44C0Q2/p1719412357335229)
* https://github.com/dimagi/commcare-cloud/pull/4651
production
> Double repeat_record_queue concurrency

- environments/india/aws-resources.yml
- environments/india/inventory.ini
- environments/india/inventory.ini.j2
- environments/india/terraform.yml
India
Celery7 is removed in https://github.com/dimagi/commcare-cloud/pull/6334, but still exist in inventory file.
This PR is to remove it from the inventory so we don't try to connect to it when deploy.
> Remove celery7 from inventory file

- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
https://dimagi.atlassian.net/browse/SAAS-15627
This may not be as targeted as we want. We want to route all admin/phone/restore requests to mobile webworkers. Currently, the only admin/phone/ requests defined in admin/urls.py are the two restore requests (app aware and not).
> Route /hq/admin/phone/restore requests to mobile webworkers

- environments/production/inventory.ini
- environments/production/inventory.ini.j2
I realised after stopping the node that we would also need to remove/comment the machines from inventory otherwise every ansible command that gather facts will raise the issue of unreachable hosts.
@dannyroberts  Not sure if better way would be completely removing the nodes or commenting is fine?
Production
> Comment couch nodes that are currently stopped form inventory

- src/commcare_cloud/ansible/cleanup_deleted_dns_records_nginx.yml
Followup to https://github.com/dimagi/commcare-cloud/pull/6357 and https://github.com/dimagi/commcare-cloud/pull/6358. We need to actually remove the URLs that are no longer resolvable from the nginx config in order to prevent the nginx config check from failing during actions like deploys.
Production
> Remove deleted DNS records from nginx config

- environments/staging/app-processes.yml
Selfishly am testing something on staging with repeat records, and would benefit from a dedicated worker. There is plenty of memory and CPU on the celery mcahine so not too worried about capacity issues.
Staging
> Give repeat_record_queue a dedicated worker

- environments/production/app-processes.yml
Doubling concurrency for repeat record queue to get through the big backlog. 
Production
> Increase concurrency on repeat record queue

- environments/production/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
We currently delay between 0 and 15 minutes when a repeat record is rate limited. Increasing these values a bit seems reasonable to prevent records from immediately being queued again (in the case that a record is delayed by 0 to 5 minutes). I tested this change on staging as well.
Once merged, I'll need to run `cchq --control production update-config` and then `cchq --control production service commcare restart`
Production
> Update min and max delays for repeater rate limiting

- environments/staging/terraform.yml
We started seeing staging deploy failure due to CPU constraints, the machine would become unresponsive during the deploy. So we are scaling the machines which get CPU starved on deploy.
[Context](https://dimagi.slack.com/archives/C0WLJ3HRP/p1719494057721179)
This is already applied on staging.
Staging
> change instance type from t3a.medium to t3a.xlarge

- environments/production/app-processes.yml
- environments/production/public.yml
https://dimagi.atlassian.net/browse/SAAS-15906
Followup to https://github.com/dimagi/commcare-cloud/pull/6376
This creates a new celery worker for the repeat_record_datasource_queue, which will handle forwarding records specifically for datasource repeaters.
Production
> Use dedicated datasource queue on production

- environments/production/app-processes.yml
Following up on the work done in https://github.com/dimagi/commcare-cloud/pull/6377, to now bump up the queue's concurrency step by step to asses its impact and adapt for load on CommCare Analytics, which is the receiving end for the requests sent via this queue.
There are 4 celery servers, so with concurrency of 1, there were 4 requests being sent in parallel.
Bumping that to 4 for each server, so at max 16 requests will be sent at once.
Production
> Bump up data source queue concurrency

- environments/production/app-processes.yml
Just a follow up to https://github.com/dimagi/commcare-cloud/pull/6378 which went well.
Production
> Bump up data source queue concurrency to 6

- environments/backup-production/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
[Ticket](https://dimagi.atlassian.net/browse/SC-3844)
This PR simply adds an environment variable containing an email address that is used in HQ. This is needed so that local hosting projects' statistics don't end up spamming the inbox of this email address. See related [HQ PR here](https://github.com/dimagi/commcare-hq/pull/35073).
Staging/Production
No announcements needed.
> Add email as environment variable

- environments/production/app-processes.yml
A follow up to https://github.com/dimagi/commcare-cloud/pull/6380 to push more concurrency after the deploy of https://github.com/dimagi/commcare-hq/pull/35080 which should reduce the load on CCA to process each request.
Production
> Bump up data source queue concurrency to 9

- environments/production/app-processes.yml
A follow up to https://github.com/dimagi/commcare-cloud/pull/6385 to push more concurrency.
Production
> Bump up data source queue concurrency to 12

- environments/production/app-processes.yml
Final PR in the series of updates, following up on last PR, https://github.com/dimagi/commcare-cloud/pull/6389
Dropping concurrency to a level such that it does not hamper performance on HQ while keeping satisfactory level of updates on Analytics.
Production
>  Drop data source queue concurrency to 8

- environments/production/public.yml
Add third BHA domain to the dedicated case search index, in the same vein as https://github.com/dimagi/commcare-cloud/pull/6308
https://dimagi.atlassian.net/browse/USH-4878
Production
> Add UAT domain to dedicated index

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
https://dimagi.atlassian.net/browse/SAAS-15882
When running `update-config`, we pass in `"_should_update_formplayer_in_place": true` [here](https://github.com/dimagi/commcare-cloud/blob/cc8e9cf49fb6e0623e14af23d868c5473c799c69/src/commcare_cloud/commands/ansible/ansible_playbook.py#L282-L282). This variable is taken into consideration when setting [_formplayer_target_dir](https://github.com/dimagi/commcare-cloud/blob/cc8e9cf49fb6e0623e14af23d868c5473c799c69/src/commcare_cloud/ansible/roles/formplayer/vars/main.yml#L14-L18), but not when setting [sentry.release](https://github.com/dimagi/commcare-cloud/blob/8e375bdcdfd27eab93d2f38e93ce50c3bfb84d7c/src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2#L19-L19).
This PR makes the change for `sentry.release` to …
> Don't update sentry release in formplayer application.properties during `update-config`

- environments/backup-production/public.yml
https://dimagi.atlassian.net/browse/SAAS-16012
There are some settings that are added between last BCP test and now which should be same on both the envs. 
Especially the elasticsearch index duplication settings for BHA indices.
Backup Production
> Add settings that are not present in backup prod from prod

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
https://github.com/dimagi/commcare-cloud/issues/6401
Followup to https://github.com/dimagi/commcare-cloud/pull/6395
The previous solution didn't take into consideration a fresh install where the symlink for the current release has not been setup yet. This registers the output of `readlink {{ formplayer_current_dir }}` to a variable and sets the current release name based on if that variable is an empty string or not, in addition to the `_should_update_formplayer_in_place` flag.
None
> Only set current release if symlink is set

- src/commcare_cloud/ansible/roles/shared_dir/tasks/setup_client.yml
- Remove duplicate when that overrides the proper condition (shared_drive_enabled)
- Remove spurious check for /opt/data being mounted, is unrelated to the task
- FTR, this undoes changes introduced in commit 6fbac06754
> Remove duplicate 'when' in Create shared mount dir

- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_django.conf.j2
it would be easier to refer to gunicorn process. As of now we would be using it to pass -USR1 flag to the gunicorn process after we rotate the logs. This tells gunicorn to reload log files.
I will probably run `update-supervior-conf` on staging before merging.
https://dimagi.atlassian.net/browse/SAAS-15962
All
> Specify `pid` in the gunicorn config

- src/commcare_cloud/ansible/roles/ecryptfs/tasks/main.yml
- This fixes failure to create shared_data_dir when not shared_drive_enabled
- Note that all other tasks that perform this test already have the cast to bool
> Add cast to bool when checking shared_drive_enabled

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-16072
The load characteristics on rabbit are not very bursty, and therefore it makes more sense to use a machine type that is suitable for general usage. This is because on a t3a.2xlarge, the baseline usage is 40% per CPU. Once that is exceeded, the machine uses burst credits. Load on rabbit14 is consistently above 40% so we are always eating into our CPU credits.
Memory isn't an issue at all on these machines, so we can downsize from 32 to 16 GB, which makes the cost difference ~$25 of on demand per machine a month.
Production
> Switch to c6a (non burstable) for rabbit machines

- src/commcare_cloud/ansible/roles/aws-fsx/tasks/main.yml
This fixes the (minor) "[WARNING]: While constructing a mapping from [...] src/commcare_cloud/ansible/roles/aws-fsx/tasks/main.yml, line 11, column 5, found a duplicate dict key (shared_dir_group). Using last defined value only."
> Remove duplicate shared_dir_group key

- .github/workflows/codeql.yml
- .github/workflows/trivy.yml
This PR introduces a CodeQL workflow like we use [in HQ](https://github.com/dimagi/commcare-hq/actions/workflows/codeql-analysis.yml) to scan the Python and Ruby code in this repo.
It also adds [Trivy](https://github.com/aquasecurity/trivy-action/?tab=readme-ov-file#using-trivy-to-scan-your-git-repo), in two modes, "filesystem" mode, which scans packages and such (eg, checking for vulnerabilities in the ansible version), and [config](https://aquasecurity.github.io/trivy/v0.55/tutorials/misconfiguration/terraform/#trivy-config-command) mode, which scans terraform files and others.
* OS packages and software dependencies in use (SBOM)
* Known vulnerabilities (CVEs)
* IaC issues and misconfigurations
* Sensitive information and secrets
* Software licenses
These will run only once a week or …
> Add static analysis workflows

- src/commcare_cloud/terraform/modules/pgbouncer_nlb/main.tf
- src/commcare_cloud/terraform/modules/postgresql/main.tf
- src/commcare_cloud/terraform/modules/server/main.tf
we destroy it with terraform destroy after bcp is done and have to manually disable termination protection from aws console. So its better not to have it while we are creating the machines
Backup Production
> Disable termination protection on backup prod env

- src/commcare_cloud/ansible/roles/shared_dir/tasks/setup_client.yml
While running 
`cchq backup-proudction ap deploy_efs_mount_shared_dir.yml`,  I encountered following error . The reason is that jinja is interpreting the permission starting with 0 as octal number? changing it to string fixes the issue.
See - https://github.com/ansible/ansible/issues/56047#issuecomment-492293723
All ?
> Pass directory permissions as string

- environments/backup-production/terraform.yml
The current machine was hanging while running `deploy-stack` continuously. So I have change the instance type to be t3a.medium which has better specs.
Backup Production
> Backup Prod control machine instance type to be t3a.medium

- src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
This fixes the formplayer cron job "delete empty sqlite db dirs"
The previous job produced this diagnostic (emailed daily to `cchq`): `find: The -delete action automatically turns on -depth, but -prune does nothing when -depth is in effect.  If you want to carry on anyway, just explicitly use the -depth option.`
> Fix formplayer cron prune job

- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_django.conf.j2
Main concern was if pid file is deleted by some automated process then it would affect the log rotation until gunicorn is restarted. So adding it to a more permanent place
All
> Update pid path from tmp to services dir

- src/commcare_cloud/ansible/roles/backups/templates/create_blobdb_backup.sh.j2
- src/commcare_cloud/ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2
- src/commcare_cloud/ansible/roles/pg_backup/templates/plain/create_postgres_dump.sh.j2
From the commit message
> The -daystart option effectively makes the -mtime option measure calendar days instead of 24 hour increments from the current timestamp. Due to unintuitive behavior of the -mtime option, this ensures that backups modified close to 3 days ago at the time the find command is run are returned since they were last modified 3 calendar days ago.
The aim of this PR is to make our daily backup logic behave more intuitively. Currently, on an environment where we keep daily backups for 2 days, at any given point, the machine will have 4 daily backups. This is because of rounding done in `find ... -mtime "+2" ...`. This rounding makes it so that a file as to have been last modified over 3 days ago in order for it to be found when providing the `-mtime "+2"` option. In other …
> Use -daystart option in the `find` command when removing old backups

- src/commcare_cloud/ansible/roles/common/templates/etc_aliases.j2
This patch adds the monit, ansible, and cchq users to `/etc/aliases`, forwarding them (as all other system accounts) to root.
Without these aliases, postfix delivery to these local accounts either fails to deliver, or gets appended to `/var/mail/...`, where it most likely goes unseen.
> Add monit, ansible, cchq to /etc/aliases

- docs/source/reference/1-commcare-cloud/2-configuration.rst
- environments/development/app-processes.yml
- environments/echis/app-processes.yml
- environments/india/app-processes.yml
- environments/pna/app-processes.yml
- environments/production/app-processes.yml
- environments/staging/app-processes.yml
- environments/swiss/app-processes.yml
- src/commcare_cloud/environment/schemas/app_processes.py
Jira ticket [here](https://dimagi.atlassian.net/browse/SC-3864).
A new Celery queue for the Geospatial feature has been added. Currently, there is only one task planned to be run on this queue, which is related to [this](https://github.com/dimagi/commcare-hq/pull/35126) PR. This task was originally set to run as a serial task on the `background_queue`, however it takes very long to process a lot of cases. Given how long it takes, and that it is a serial task, any domains that are queued up for the task are highly likely to fail from getting locked out of the task for too long.
Adding a new Celery queue will resolve the issue mentioned above by allowing the Geospatial Celery task to be run in parallel without the risk of blocking up something like the `background_queue`. A concurrency of 1 …
> Add Geospatial Celery Queue

- src/commcare_cloud/ansible/deploy_webworker.yml
The path to the gunicorn.pid file was not updated in the actual ansible task after updating [here](https://github.com/dimagi/commcare-cloud/pull/6423). This means that after rotating the logs, the gunicorn process will not actually be reloaded.
All
> Update gunicorn.pid path in logrotate config

- docs/source/backups_dr/2-backups-guide.rst
Based on [couch default values](https://github.com/dimagi/commcare-cloud/blob/eec24250cd139bae29b38b389ad7f7028ed019f5/src/commcare_cloud/ansible/roles/couchdb2/defaults/main.yml#L9-L10) and [postgres default values](https://github.com/dimagi/commcare-cloud/blob/eec24250cd139bae29b38b389ad7f7028ed019f5/src/commcare_cloud/ansible/roles/pg_backup/defaults/main.yml#L9-L10), the default values in docs should be updated. [Blob backup values](https://github.com/dimagi/commcare-cloud/blob/eec24250cd139bae29b38b389ad7f7028ed019f5/src/commcare_cloud/ansible/roles/backups/defaults/main.yml#L5-L6) are correct in [docs](https://github.com/dimagi/commcare-cloud/blob/gh%2Fdocs%2Fupdate-backup-defaults/docs/source/backups_dr/2-backups-guide.rst#blobdb-backups).
> Reference accurate default backup values in docs

- environments/production/public.yml
Multiple devices using the same user account is causing a locking issue with the DB queries caused in the `users_userreportingmetadatastaging` table.
Disabling this processor will unblock normal processing of xforms at the cost of stale device metadata in the user models.
See https://github.com/dimagi/commcare-hq/blob/master/corehq/pillows/xform.py#L150
```
cchq prod update-config
cchq prod service pillowtop restart --only xform-pillow
```
prod
> temporarily disable form metadata processing

- environments/production/public.yml
Reverts dimagi/commcare-cloud#6445. This is safe to undo because of the changes made in https://github.com/dimagi/commcare-hq/pull/35485 which are currently being deployed.
Similar to before, steps to rollout will be:
```
cchq prod update-config
cchq prod service pillowtop restart --only xform-pillow
```
prod
> Revert "temporarily disable form metadata processing"

- environments/staging/terraform.yml
There was an increase in case load on staging due to some testing, and the kafka machines do not have enough disk to handle it. I think this small increase should be enough to handle the additional load (trying to be conservative since it is annoying to downsize).
Staging
> Double block storage on kafka machines

- src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
https://dimagi.atlassian.net/browse/SC-4038
Couple of improvements noticed while testing a full stack deploy.
All
This change is applicable to all environments but won't change anything about how they are setup since the changes are for the setup process and not for any actions taken during the setup
> Deploy stack improvements

- requirements.txt
From the [Jinja2 release notes](https://github.com/pallets/jinja/releases/tag/3.1.5)
> This is the Jinja 3.1.5 security fix release, which fixes security issues and bugs but does not otherwise change behavior and should not result in breaking changes compared to the latest feature release.
https://dimagi.atlassian.net/browse/SAAS-16432
None/all.
> Bump Jinja2 to 3.1.5

- src/commcare_cloud/commands/deploy/slack.py
We sometimes do not receive diffs during deploy so they have to be manually copied. On looking I found out it is because of the 3000 character limit on the message. The fix that is made here is chunking the longer messages and sending as separate messages on slack
[This](https://dimagi.slack.com/archives/C0B44C0Q2/p1736501423146569) is how the diffs will look like. 
There was another approach that I experimented with, which was sending different blocks in the same message like [this](https://dimagi.slack.com/archives/C0B44C0Q2/p1736502263670369)
In both the approaches the messages are getting truncated under `See More`. For the second approach the `See More` is hidden in the diff and hard to find. Although first approach is still not the best but it provides a good differentiation between …
> Make slack deploy diff work for longer diffs as well

- environments/india/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-16446
Needed to avoid OOM during deploy.
India
> [India] Increase memory on proxy machines

- docs/source/installation/2-manual-install.rst
I've run into various issues while setting up monoliths and am attempting to clarify those instructions in this PR.
This also notably updates documentation to be aligned with our removal of the suggestion to copy a private key to the server, and instead use `ssh -A` when/where appropriate.
Review by commit.
None
> Update commcare cloud setup instructions

- environments/india/terraform.yml
- environments/production/terraform.yml
- environments/staging/terraform.yml
In order to buy the reserved instances this month, we are consolidating production RDS machines to m6g family and updating the Staging and India RDS instances from t3 to t4g.
Production, India, Staging
> Switch to newer generation of RDS machines

- src/commcare_cloud/commands/deploy/slack.py
Two reasons for this:
* See how long deploy took. There are more systematic ways to do this, but I've sometimes wanted to informally see how long the last few deploys took, on either prod or staging.
* If you "get notified of new replies" on the original deploy message, you get a DM when the deploy is complete.
none
> Add threaded message on deploy completion

- src/commcare_cloud/ansible/roles/commcarehq/tasks/celery_cron.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/celery_bash_runner_kill.sh.j2
- src/commcare_cloud/ansible/roles/commcarehq/templates/celery_task_kill.sh.j2
https://dimagi.atlassian.net/browse/SAAS-16545
This is an improvement to an existing band-aid solution. The ticket outlines in detail the underlying issue, but basically we've seen celery processes, especially repeat_record_queue workers, fail to shutdown properly when receiving a SIGTERM. The investigation into this is ongoing, but in the meantime we should make this change since in the current state, if a celery process runs into an issue during shut down, supervisor is unaware of it and does not fire up a new worker. This way, supervisor will create a new worker. From what I've seen, the process that fails to shut down stops consuming from the queue, and there is still the hard kill that will come along to clean the rogue process up eventually.
You might ask "why do we do this in the …
> Soft kill celery processes via celery_bash_runner

- environments/india/terraform.yml
switch back to db.t3.medium as we have savings plans for db.t3.medium
https://dimagi.atlassian.net/browse/SAAS-16656
India
> switch back to db.t3.medium on India

- docs/source/installation/2-manual-install.rst
I made a change to docs in https://github.com/dimagi/commcare-cloud/commit/01c3af2fb359c593b01e924e4c5480f38d5163fe that resulted in no longer using `--first-time` when running `deploy-stack`, but needed to explicitly set `--skip-check` since that is set by the first-time option.
> Skip check when running deploy-stack

- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
https://dimagi.atlassian.net/browse/SAAS-16790
Followup to https://github.com/dimagi/commcare-hq/pull/35781. This setting is no longer used.
All
> Remove DEVICE_LIMIT_PER_USER setting

- environments/production/app-processes.yml
This queue can see transient spikes in load and should have higher concurrency to deal with these spikes. Given this workload is already parallelized across celery machines, it should be safe to continue increasing concurrency. There is a lock acquired on each case that the rule is run on, so if multiple rules are being processed in parallel, that could lead to some lock timeouts but I don't believe to be a sufficient reason not to make this change.
There are a few different tasks that are sent to this queue. In order of how they are called:
- run_messaging_rule
- run_messaging_rule_for_shard
- sync_case_chunk_for_messaging_rule
- sync_case_for_messaging_rule (only called asynchronously if there is a failure in the above task)
- set_rule_complete
The bottleneck is on …
> Add gevent concurrency to reminder_case_update_bulk_queue

- environments/production/app-processes.yml
Followup to https://github.com/dimagi/commcare-cloud/pull/6492 since things look good.
Possibly just temporary, though not opposed to leaving this in place permanently.
Production
> More concurrency reminder_case_update_bulk_queue

- environments/production/app-processes.yml
Reverts dimagi/commcare-cloud#6493
Looks like we hit a limit elsewhere based on [the average duration](https://app.datadoghq.com/dashboard/bdu-k5b-bz5/celery-overview?fromUser=false&refresh_mode=sliding&tpl_var_celery_queue%5B0%5D=reminder_case_update_bulk_queue&from_ts=1742390259923&to_ts=1742393859923&live=true) for these tasks increased after increasing concurrency more.
> Revert "More concurrency reminder_case_update_bulk_queue"

- environments/production/public.yml
This is the last older index on prod. This was swapped a couple of days back and we haven't seen any issues with the newer index. After this PR is applied we would be stopping writes to older apps index and will later delete the index.
Production
> Stop multiplexing apps index on prod

- src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml
The new ES tar.gz file is most likely not available at this point when running in check mode, so lets ignore errors for this task when in check mode.
> Ignore errors in check mode for Unarchive Elasticsearch

- environments/india/public.yml
Resolves `ClientError: An error occurred (301) when calling the HeadBucket operation: Moved Permanently`
with `botocore==1.37.15`
This error did not occur with `botocore==1.27.96`
Other versions not tested.
The new URL has been tested and verified to work on both old and new versions of botocore.
https://dimagi.slack.com/archives/CCXQZLECS/p1743020693118459
India
> Update India S3 URL for newer botocore versions

- environments/production/app-processes.yml
- environments/production/terraform.yml
Temporary change to ensure trainings go smoothly.
On demand usage per day is for 4xlarge is $16.59, and for 8xlarge is $33.18. That is a difference of $16.59, which for 4 machines is 4 x 16.59 = $66.36 per day. That is just under $200 for 3 days which is how long we plan to have this rolled out for.
Production
> Change from m6a.4xlarge to 8xlarge

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-16891
This is a temporary increase to accommodate more case pillow processes.
Production
> Increase pillow_b2000 machine to r6a.12xlarge temporarily

- environments/production/app-processes.yml
In theory, the repeat record queue should be strictly I/O bound, however in practice there are some funky repeaters that appear to consume quite a bit of CPU. This makes the roundtrip for the gevent loop take awhile, and thus our throughput for tasks on this queue decreases.
This creates an additional process to give more CPU to this queue.
Production
> Give repeat_record_queue more cpu

- environments/production/app-processes.yml
https://dimagi.atlassian.net/browse/SAAS-16482
Tasks on this queue can consume a lot of memory. Celerybeat is a smaller machine than the other celery machines, and sometimes experiences OOMs because of these tasks. We should not subject the celerybeat machine to this since it is important for it to remain up for the sake of periodic tasks.
Production
> Move the submission_reprocessing_queue off of celerybeat

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-16942
The price difference is ~$6.50 a day per machine, across 6 machines, ~$40 a day. I view this as a temporary change, and would be more interested in moving API workload onto its own machines, which will also increase costs, but give us better control over fairly different workloads.
Production
> Increase CPU on HQ webworkers

- src/commcare_cloud/ansible/requirements.yml
Ticket : https://dimagi.atlassian.net/browse/SAAS-16650
Environments Affected : ALL `staging, India and production`
We upgraded the DavidWittman.redis role from version 1.2.7 to 1.2.12 using the source from [GitHub](https://github.com/DavidWittman/ansible-redis), as the [Ansible Galaxy version](https://github.com/DavidWittman/ansible-redis) was not up to date. The update was tested in the Monolith environment and is functioning as expected.
> Upgrading Ansible dependency for DavidWittman.redis role

- src/commcare_cloud/ansible/requirements.yml
Ticket : https://dimagi.atlassian.net/browse/SAAS-16650
Environments Affected : ALL `staging, India and production`
We upgraded the sansible.logstash role from version v2.4.0-latest to 2.4.4 using the source from the [Ansible Galaxy version](https://galaxy.ansible.com/ui/standalone/roles/sansible/logstash/versions/). The update was tested in the Monolith environment and is functioning as expected.
> Upgrading Ansible dependency for sansible.logstash role

- src/commcare_cloud/ansible/requirements.yml
Ticket : https://dimagi.atlassian.net/browse/SAAS-16650
Environments Affected : ALL `staging, India and production`
We upgraded the cloudalchemy.alertmanager role from version 0.19.0 to 0.19.1 using the source from the [Ansible Galaxy version](https://galaxy.ansible.com/ui/standalone/roles/cloudalchemy/alertmanager/versions/). The update was tested in the Monolith environment and is functioning as expected.
> Upgrading Ansible dependency for cloudalchemy.alertmanager role

- environments/backup-production/app-processes.yml
- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-16942
Change mobile webworkers back from m6a.8xlarge to m6a.4xlarge, effectively reverting https://github.com/dimagi/commcare-cloud/pull/6510.
Production
> Downsize mobile webworkers

- src/commcare_cloud/ansible/requirements.yml
Ticket : https://dimagi.atlassian.net/browse/SAAS-16650
Environments Affected : ALL `staging, India and production`
Upgraded the Version 3.4.1 of gantsign.golang is not working for us. So, I checked the available versions listed [here](https://galaxy.ansible.com/ui/standalone/roles/gantsign/golang/versions/) and found that version 3.2.1 works fine. The update was tested in the Monolith environment and is functioning as expected
> Upgrading Ansible dependency for gantsign.golang role

- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
In theory this PR alone shouldn't change anything, but just updates the nginx config to route API requests to the api_webworkers group if that group exists, otherwise default to webworkers, similar to how mobile webworkers operates.
All
> Route API requests to API webworkers if specified

- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
Reverts dimagi/commcare-cloud#6519
On environments where there are distinct groups for hq and mobile webworkers specified, this change could lead to API requests moving from hq webworkers to all webworkers, including mobile webworkers. There is a fix in progress but safest to just revert for now.
> Revert "Route API requests to API webworkers if specified"

- environments/production/app-processes.yml
https://dimagi.atlassian.net/browse/SAAS-16892
Based on [machine resources](https://app.datadoghq.com/dashboard/nbz-bie-nip/host-groups?fromUser=false&refresh_mode=sliding&tpl_var_host%5B0%5D=pillow-b2000-production&from_ts=1743516404510&to_ts=1744121204510&live=true), there is room to add more processes still.
At peaks, memory usage is ~195 GB (conservatively), and each process takes up ~6GB, that is 96GB so memory will be fine. CPU isn't a concern.
Production
> Add 16 more case pillow processes

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-16892
~This is a difference of $23 per day. This increases RAM from 386 to 512. At 48 processes, we are consuming 250 GB of RAM so doubling will put us just around 500GB. I'm not sure if that is quite enough headroom to feel comfortable.~
Decided to increase to r6a.24xlarge instead. So this will be an added $65 per day. 
Production
> Add more RAM/CPU to case pillow machine

- src/commcare_cloud/ansible/roles/deploy_hq/tasks/staticfiles_collect.yml
https://github.com/dimagi/commcare-hq/pull/36073 migrated the last requirejs pages on HQ to webpack.
I ran a test deploy on staging.
None
> Removed build_requirejs from deploy

- src/commcare_cloud/commands/terraform/constants.py
- src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/commands/terraform/tests/test_compact_regexes.py
- src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf
- src/commcare_cloud/terraform/modules/ga_alb_waf/variables.tf
The work prompting this change was https://dimagi.atlassian.net/browse/SAAS-16494. However, it appears there were other exceptions that were added previously that had not been added here.
Should affect any environments which use the AWS WAF.
> Update WAF exceptions

- src/commcare_cloud/ansible/group_vars/all.yml
- src/commcare_cloud/ansible/roles/elasticsearch/templates/systemd/elasticsearch.service.j2
Use Java 17 on Elasticsearch 6.8.23.
Upgrading the java version allows us to use a garbage collection strategy that is a better fit for the size of our infra.
As outlined in [this matrix](https://www.elastic.co/support/matrix#matrix_jvm), Elasticsearch 6 clearly supports this version of Java, and we already have this version of Java installed on machines which makes it really convenient to switch.
This was tested on staging.
Production, India, Staging (environments with Elasticsearch 6.8.23)
> Use Java 17 with Elasticsearch 6

- docs/source/reference/1-commcare-cloud/commands.md
- src/commcare_cloud/commands/deploy/command.py
- src/commcare_cloud/commands/deploy/commcare.py
- src/commcare_cloud/commands/deploy/formplayer.py
- src/commcare_cloud/commcare_cloud.py
Just a minor `cchq` command to view the deploy diff, aka the PRs set to go out if we were to deploy right now. It is nice to get the list of PRs without interacting with the `deploy` command directly. I thought about adding a `--diff` option to the deploy command that clearly said "don't actually deploy, just show the diff", but there are already so many arguments for that command that creating a simple new command seemed fine.
None
> Create command to check deploy diff

- src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml
https://dimagi.atlassian.net/browse/SAAS-17337
Redo of https://github.com/dimagi/commcare-cloud/pull/6519, but updated the syntax to fallback to hq_webworkers _first_, and then all webworkers if that group doesn't exist.
I tested this on staging and it worked, and my understanding is that jinja is inspired by python syntax which this is.
All
> [Take 2] Route API requests to api group if available

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-17362
After increasing network, we still saw a bottleneck in CPU so increasing CPU as well. We don't need more RAM, hence the change to m6in instead of r6in.
Production
> Double CPU on ES Coordinator machines

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-17362
Add additional CPU to mobile webworkers. We don't need more RAM, so switching from m6a to c6a family.
Production
> More CPU on mobile webworkers

- environments/production/postgresql.yml
https://dimagi.atlassian.net/browse/SAAS-17395
This is increasing the default pool size on each pgbouncer machine from 36 to 43 for the main database, and from 6 to 12 for the repeaters db, both of which live on pgmain. There are two pgbouncer machines that handle requests for the main db, so this will result in an increase of 14 connections to the main db and 12 connections to the repeaters db.
Production
> Increase pgbouncer connections to pgmain

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-17395
The primary reason for this change is to get access to more IOPS, so we also want to provision enough IOPs on the volume to keep up with the instance capacity (20k).
Production
> Double size of pgshards

- environments/production/app-processes.yml
As a follow up to keep up with needs of async ucr indicators processing, bumping the concurrency from 3 to 5 across 4 machines. This means 20 parallel processes for async ucr indicators processing instead of 12.
Production
Should be a safe change keeping in mind the resources available on celery machines as of now.
> Bump up concurrency for ucr indicator queue

- src/commcare_cloud/ansible/roles/deploy_hq/tasks/staticfiles_collect.yml
- src/commcare_cloud/ansible/roles/deploy_hq/tasks/update_translations.yml
https://dimagi.atlassian.net/browse/SAAS-17389
`compilejsi18n` was not generating the desired js translation file with our deploy pipeline. However if the command was run on an already deployed release it generated correct output. 
@millerdev and I tried to test it by breaking the deploy script right after we run this command on staging. We found out that the translation js file was different than what we expected and had far less strings than that were in the translations file.
On looking source of [`compilejsi18n`](https://github.com/zyegfryed/django-statici18n/blob/main/src/statici18n/management/commands/compilejsi18n.py) I found out it is just an wrapper over Django's [JavascriptCatalogue](https://docs.djangoproject.com/en/5.1/topics/i18n/translation/#module-django.views.i18n) view. …
> Run compilejsi18n after all translations are compiled

- environments/production/terraform.yml
- src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/postgresql/main.tf
https://dimagi.atlassian.net/browse/SAAS-17462
Modeled after https://github.com/dimagi/commcare-cloud/pull/6538, but for storage throughput instead of IOPs.
Production
> Increase storage throughput on pgmain

- environments/production/terraform.yml
https://dimagi.atlassian.net/browse/SAAS-17513
Reverts https://github.com/dimagi/commcare-cloud/pull/6538/commits/11b0b87d1620c633f66abe857edd1e8b43066426 and https://dimagi.atlassian.net/browse/SAAS-17513.
Production
> Scale down pgshards

- src/commcare_cloud/ansible/deploy_postgres.yml
Building psycopg2 requires other dependencies and sometimes version issues can cause building binary to fail. Since we use this once and is installed on Django manage machine. And has been tested while setting up eu server
All
> When setting up RDS use psycopg prebuilt binary

- src/commcare_cloud/ansible/deploy_webworker.yml
- src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_django.conf.j2
A very late followup to https://dimagi.atlassian.net/browse/SAAS-15962
The service directory is "managed" by commcare-cloud in that [we will clean up non supervisor config files](https://github.com/dimagi/commcare-cloud/blob/7c1e0703ca9f6d4696c5e76718507b89905c2252/src/commcare_cloud/ansible/deploy_commcarehq.yml#L107-L113) in that directory. 
Rather than attempt to whitelist gunicorn.pid, it is easier to just move it up one level into the www_home directory.
None
> Save gunicorn.pid file in www_home

- src/commcare_cloud/ansible/restart_commcare_services.yml
https://dimagi.atlassian.net/browse/SAAS-17575
Oversight on my part when adding this new group. I don't expect us to split into more webworker groups than what we currently have, so I don't think it is worth trying to come up with a more dynamic way of doing this so that we don't run into this issue in the future.
All
> Restart api webworkers if split

- environments/eu/public.yml
This is a requirement after boto upgrade - https://commcare-cloud.readthedocs.io/en/latest/changelog/0086-s3-library-upgrade.html
EU
> Add `s3_blob_db_url` for EU env 

- src/commcare_cloud/ansible/roles/datadog/tasks/main.yml
When I added newer apt keys for Datadog in https://github.com/dimagi/commcare-cloud/pull/6570, it worked fine for newer machines. 
But when I tried to run it for production machines, I got following error - 
```
E:Conflicting values set for option Signed-By regarding source http://apt.datadoghq.com/ stable: /etc/apt/keyrings/DATADOG_APT_KEY_F14F620E.gpg != /etc/apt/keyrings/DATADOG_APT_KEY_C0962C7D.gpg, E:The list of sources could not be read.
```
The error was because `apt del <key>` was not cleaning the keys and also not cleaning the source lists. I tried the steps mentioned here in `django-manage` machine and was successful. 
So I added them to the playbook which worked fine.
https://dimagi.atlassian.net/browse/SAAS-17510
All
> cleanup existing keys for apt

- src/commcare_cloud/ansible/roles/rabbitmq/tasks/install_latest.yml
`lineinfile` will probably work, although could fail under certain conditions. For example, it will not add the blacklist item if an unrelated line after the blacklist (a delimited range in the file) matches the regex. Similarly it will add the item at the wrong place (at the end of the file) if the `regexp` and `insertafter` patterns do not match lines in the file, which seems possible if the file format changed in a subtle way.
This is a pragmatic solution that is probably good enough to meet our needs.
https://dimagi.atlassian.net/browse/SAAS-17458
All.
> Prevent unattended rabbitmq restart disrupting celery

- src/commcare_cloud/ansible/roles/deploy_hq/tasks/staticfiles_compress.yml
HQ is no longer compressing any javascript files.
There are a couple of places that [hqwebapp/base.html](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqwebapp/templates/hqwebapp/base.html) uses `compress js` blocks, but they're all within `if not use_js_bundler` blocks, and `use_js_bundler` is always true now. These remaining `compress js` blocks are being removed in https://github.com/dimagi/commcare-hq/pull/36474
Deploying https://github.com/dimagi/commcare-hq/pull/36474 to staging was failing because there's no more compressed js, which means that `purge_static_files` is no longer necessary, and instead was failing to find the js cache directory. I updated `purge_static_files` in that PR, in https://github.com/dimagi/commcare-hq/pull/36474/commits/92afa00dfeaf6a34f621e4 …
> Removed purge_static_files

- environments/staging/app-processes.yml
This [PR](https://github.com/dimagi/formplayer/pull/1712) and the corresponding [ticket](https://dimagi.atlassian.net/browse/USH-5218) introduced a feature flag to control whether tracing data is sent to Datadog. Only domains with the flag enabled will have their traces reported.
The motivation for this change was to allow us to set the sampling rate to 100%, ensuring we capture all traces — especially the slower ones that are most valuable for debugging performance issues.
Now that tracing can be toggled per domain, this PR enables it for staging and sets the sampling rate to 100%. Once the Formplayer PR is deployed to production, we’ll do the same there.
Staging
> Enable Formplayer APM Traces

- environments/production/app-processes.yml
This https://github.com/dimagi/formplayer/pull/1712 and the corresponding [ticket](https://dimagi.atlassian.net/browse/USH-5218) introduced a feature flag to control whether FP tracing data is sent to Datadog. Only domains with the flag enabled will have their traces reported.
The motivation for this change was to allow us to set the sampling rate to 100%, ensuring we capture all traces — especially the slower ones that are most valuable for debugging performance issues.
Now that tracing can be toggled per domain, this PR sets the sampling rate to 100% for production. (This has already been done on staging) - see this [PR](https://github.com/dimagi/commcare-cloud/pull/6594)
Production
> Enable 100% APM Trace sampling

- environments/india/terraform.yml
- environments/production/terraform.yml
- src/commcare_cloud/commands/terraform/templates/imports.tf.j2
- src/commcare_cloud/commands/terraform/terraform.py
- src/commcare_cloud/environment/schemas/terraform.py
- src/commcare_cloud/terraform/modules/logshipping/main.tf
https://dimagi.atlassian.net/browse/SAAS-17659
The config changes rule sets it up so that AWS Config changes are logged to a log group in CloudWatch. It was originally manually set up in production and india a long time ago. This change makes it part of our terraform configuration, as is standard.
I implemented this in such a way that I
- allow importing existing resources cleanly
- bring analogous setup to staging and eu
This also introduces some new support for terraform's relatively new [`import` block](https://developer.hashicorp.com/terraform/language/import), which can be used to acknowledge preexisting resources in code rather than requiring manual reconciliation with the terraform import command.
eu, staging
(production and india will have their terraform state updated to match …
> Bring existing rules to create config-changes log into terraform

- requirements.txt
- setup.py
https://dimagi.atlassian.net/browse/SAAS-17775
[Changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst)
This package is only used in the context of caching secrets. If our caching logic fails, it looks like we raise errors, so I'd expect any issues here to be very visible.
I tested running this locally to view some secrets but that is it. 
None
> Bump cryptography to 45.0.5

- requirements.txt
[Changelog](https://pypi.org/project/PyNaCl/)
There are two breaking changes:
> BACKWARDS INCOMPATIBLE: Removed support for Python 2.7 and Python 3.5.
> BACKWARDS INCOMPATIBLE: We no longer distribute manylinux1 wheels.
The first gets rid of the depedency on six, and the second I don't think effects us? This package is used by pygithub which is on the latest version already.
None
> Bump pynacl to 1.5.0

- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
The motivation for this change is v5 of redis changes the path to this parser, which causes issues. It turns out that in redis-py v4.5.4 (the currently installed version in commcare-hq), if hiredis is installed it defaults to use that parser: https://github.com/redis/redis-py/blob/v4.5.4/redis/connection.py#L512-L515.  This appears to have been supported in redis-py since v3. 
Just to confirm, [hiredis is part of our requirements](https://github.com/dimagi/commcare-hq/blob/4689cd6e4c54fa8e42cb735285e77cb8205d3315/uv.lock#L1560-L1562), so this should work and we shouldn't have to specify `PARSER_CLASS` in settings.
I'm opting to not announce this as it isn't breaking anything. If a self hoster has made a change to the parser used by redis, they are in uncharted territory and it is up to …
> Remove PARSER_CLASS in settings.py

- quick_monolith_install/sample-environment/public.yml.j2
- src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
ES 5 is no longer supported by commcare, so we should be defaulting to 6 for new setups.
None
> Default to elasticsearch 6.8.23

- src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml
Simple cleanup. ES 5 is officially no longer supported so this should be safe to remove.
None
> Remove task that downloads ES 5

- src/commcare_cloud/commands/terraform/templates/terraform.tfvars.j2
**Ticket :** https://dimagi.atlassian.net/browse/SAAS-18008
**Environments :** ALL
This PR removes the unused source variable from `terraform.tfvars` to eliminate Terraform warnings, improve clarity, and ensure clean plan outputs during upgrades. No functional changes to infrastructure.
> Remove unused source var to fix warning

- environments/backup-production/public.yml
- environments/eu/public.yml
- environments/india/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- src/commcare_cloud/ansible/group_vars/all.yml
https://dimagi.atlassian.net/browse/SAAS-16907
Relates to https://github.com/dimagi/commcare-hq/pull/36758
Updates growth email on Dimagi environments to `saas-revenue-team@dimagi.com`
production, eu, india, staging, backup-production, and "example" `growth_email`
> Change growth email on all relevant environments

- docs/source/services/postgresql/split-partitioned-database.rst
As of [Django 4.0](https://docs.djangoproject.com/en/5.2/releases/4.0/#id2), `SERIALIZE` test setting is deprecated as it can be inferred from the databases with the `serialized_rollback` option enabled. As of Django 5.0, the setting is removed.
https://dimagi.atlassian.net/browse/SAAS-17626
all/none
> Remove DATABASES[...]['TEST']['SERIALIZE'] setting

- .github/PULL_REQUEST_TEMPLATE.md
This came up during a discussion with @gherceg  where we can easily miss that a particular change might be affecting multiple environments. This shows up when we try to apply some other changes and its hard to find context on them. This is a small step to nudge people to think about other environments.
> Update PR template to include a checkbox to notify devs to ensure to be cognizant of changes that affects multiple envs

- environments/india/terraform.yml
- environments/production/terraform.yml
- environments/staging/terraform.yml
Updating RDS engine version to 14.18 in Production, India and Staging as a part of terraform environmental cleanup.
**Ticket :** https://dimagi.atlassian.net/browse/SAAS-18323
> update rds engine version to 14.18

- environments/eu/terraform.yml
Updating RDS engine version to 14.18 in EU.
**Ticket :** https://dimagi.atlassian.net/browse/SAAS-18323
> update rds engine version

- src/commcare_cloud/commands/ansible/service.py
`restart_webworker_services.yml` playbook expects `webworker_hosts` because of which currently `cchq commcare service webworker restart` is failing.
The PR splits up the functionality for commcare restarts and webworker restarts into two different functions.
Paired with @gherceg 
All
> Fix restart webworkers command

- environments/backup-production/public.yml
- environments/eu/public.yml
- environments/india/public.yml
- environments/pna/public.yml
- environments/production/public.yml
- environments/staging/public.yml
- quick_monolith_install/sample-environment/public.yml.j2
https://dimagi.atlassian.net/browse/SAAS-18564
Find-and-replace to update the `INVOICE_FROM_ADDRESS` in settings, plus the addition of `second_line` which is supported by HQ's `Address` class where this setting is used: [invoice_pdf.py](https://github.com/dimagi/commcare-hq/blob/1679d63ed17a696172486d471b1e57755fa8bd20/corehq/apps/accounting/invoice_pdf.py#L39).
production, eu, india, backup-production, staging
> Update Dimagi invoice_from_address

- commcare-cloud-bootstrap/environment/private.yml.j2
- docs/source/installation/troubleshooting.rst
- docs/source/reference/1-commcare-cloud/2-configuration.rst
- environments/development/public.yml
- src/commcare_cloud/ansible/plugins/inventory/csv.py
- src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
- src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
- src/commcare_cloud/ansible/roles/redis/meta/main.yml
- src/commcare_cloud/ansible/roles/redis/templates/redis_is_master.j2
- src/commcare_cloud/ansible/roles/sentry/tasks/snuba.yml
Fix issues or make improvements for HQ installation for cluster/monolith:
1. Generate redis password and use it when setting up redis.
2. Add example to show how a shared directory should be configured for a cluster
Earlier attempt: https://github.com/dimagi/commcare-cloud/pull/6604
None
> Fix HQ installation for a cluster

- src/commcare_cloud/commands/terraform/aws.py
Install Details: Ubuntu 25.04 / Python 3.13.3
The auth session check trawls through the AWS env looking for JSON files, using a decode exception to skip invalid files. In a clean install for me from this week, this handling path failed because one of the non-JSON files (a sqlite database) was failing with a different exception.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 98: invalid start byte
```
This PR just adds that handling path to the code, which worked for my install. 
None
> Fix auth check for session.db files 
