ansible/group_vars/all.yml

seeing stuff like `/home/cchq/www//production/code_root_preindex` is annoying me

remove unnecessary slash in dir

---

ansible/roles/commcarehq/tasks/main.yml

Previously this was just always updating the repo, which we don't want it to do yet (that's what deploy is for)

fix error detecting whether repo exists

---

ansible/group_vars/all.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/webworker/tasks/main.yml
ansible/roles/webworker/vars/main.yml

This smells bad to me, but I couldn't figure out a better way to do this. I'm trying to accomplish two things: one, setup the `restore_payloads` directory and a cron job to periodically clean the dir; two, fill the `RESTORE_PAYLOAD_DIR` variable in localsettings template. Originally I had the `restore_payload_dir` variable in the `webworker` role and that worked fine, but since the localsettings template is under the `commcarehq` role, i can't access that variable. I didn't want to declare the variable twice and couldn't figure out a way to share variables between roles. The reason this works for touchforms is that the task of creating the directory is in the same role as creating the localsettings file. This solution just declares a global `restore_payload_dir` variable, but that seems …

Restore payload tasks

---

ansible/group_vars/all.yml
ansible/roles/shared_dir/tasks/setup_host.yml
ansible/roles/webworker/tasks/main.yml

@dannyroberts 
This does a couple things. The dir permissions are pretty obvious. The other thing is `all_squash`.  This `all_squash` makes things work. Not in the most ideal way though. `all_squash` - "Convert incoming requests, from ALL users, to the anonymous uid and gid.". Unfortunately nfs does not have an option that says "Convert requests, from SOME users, to the anonymous uid and gid." So if we don't want to have to write as root, we have to allow every user on the machine to write to the shared dir. I tried really hard to make this work in such a way that only `cchq` could write the files, but short of syncing all the uids on all the servers, I think it's impossible. Here's a quote from one of the trouble shooting [guides](http://nfs.sourceforge.net/nfs-howto/ar01s07.html) I …

Refactor nfs

---

ansible/deploy_db.yml
ansible/roles/postgresql/templates/postgresql.conf.j2

@snopoke @dannyroberts 
cc: @millerdev 
This enables logging for postgres. Most of these values are the default settings. Important ones that aren't:
```
log_destination = 'csvlog' # this logs the statements in a csv format (default is stderr)
log_min_duration_statement = 300 # logs queries over 300ms
```

Pg logging

---

ansible/requirements.txt
ansible/roles/postgresql/templates/pg_hba.conf.j2

@dannyroberts this allows ansible to lookup the IP address of a hostname. Requires the version bump in ansible.
Other changes:
- Change `host` to `hostssl` (this is what we use in our prod environment)
- Allow access to postgres via devreadonly user (also used in prod environment)
The domain lookup was tested using my Vagrant machine

Postgres conf hostnames

---

ansible/roles/common_installs/tasks/main.yml

Had to do this on the fly today during deploy, but I think we should have it standardized in our deploy that'd be optimal. `n` allows you to update `node` really easily

More npm tasks

---

ansible/roles/postgresql/templates/postgresql.conf.j2

@benrudolph 
Was getting this error after the conf changes:
```
IpcMemoryCreate: shmget(key=5432001, size=415776768, 03600) failed: Invalid argument 
This error usually means that PostgreSQL's request for a shared memory 
segment exceeded your kernel's SHMMAX parameter. You can either 
reduce the request size or reconfigure the kernel with larger SHMMAX. 
To reduce the request size (currently 415776768 bytes), reduce 
PostgreSQL's shared_buffers parameter (currently 50000) and/or 
its max_connections parameter (currently 12).
```
@sravfeyn buddy ping

leave shared_buffers at default value

---

ansible/roles/apache2/templates/cchq.j2

Ask me not why this works on www, for I do not know. This fixes it on india.
This keeps apache from rewriting the Location header (that django sends back on a redirect) to use http

fix india http redirect issue

---

ansible/roles/touchforms/templates/localsettings.py.j2

@esoergel 
fyi @snopoke 
tested this out on vagrant. example output:
```
+#
+# Ansible managed: /vagrant/ansible/roles/touchforms/templates/localsettings.py.j2 modified on 2015-05-19 20:17:46 by vagrant on control
+#
+import os
+
+URL_ROOT = "https://192.168.33.17/a/{{DOMAIN}}"
+PERSISTENCE_DIRECTORY = "/home/cchq/www/dev/data/touchforms"
+FORMPLAYER_LOG_FILE = os.path.join('/home/cchq/www/dev/log','log',"formplayer.clean-192.168.33.16.log")
+
+from jython_ssl import SSLContext, TRUST_ALL_CONTEXT
+SSLContext.setDefault(TRUST_ALL_CONTEXT)
```
see: https://github.com/dimagi/touchforms/pull/116

define FORMPLAYER_LOG_FILE

---

ansible/roles/touchforms/templates/localsettings.py.j2

Reverts dimagi/commcarehq-ansible#128
@benrudolph this needs to be an int. Was getting this error on staging:
```
File "/home/cchq/www/staging/code_root/submodules/touchforms-src/touchforms/backend/xformserver.py", line 298, in <module>
main(
File "/home/cchq/www/staging/code_root/submodules/touchforms-src/touchforms/backend/xformserver.py", line 272, in main
xformplayer._init(init_gui())
File "/home/cchq/www/staging/code_root/submodules/touchforms-src/touchforms/backend/xformplayer.py", line 109, in _init
global_state = GlobalStateManager(ctx)
File "/home/cchq/www/staging/code_root/submodules/touchforms-src/touchforms/backend/xformplayer.py", line 60, in __init__
self.redis = Jedis(settings.REDIS_HOST, settings.REDIS_PORT)
TypeError: …
```

Revert "Quote variable"

---

ansible/deploy_proxy.yml
ansible/roles/nginx/vars/dhis.yml

This exposes dhis over nginx.  Should be merged before the actual nginx proxy switch.

Add dhis site to nginx proxy

---

ansible/roles/commcarehq/templates/localsettings.py.j2

This occurs when localsettings.DEFAULT_CACHE is unset, as it was on the india server.

Don't default to DEFAULT_CACHE to memcached

---

ansible/roles/touchforms/tasks/main.yml

@czue @TylerSheffels this is a pretty common operation and i think it makes sense to formally add a tag so i can stop tagging it manually on salt

Update tags for touchforms localsettings

---

ansible/deploy_proxy.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/wiki.yml
ansible/roles/nginx/vars/wiki_http.yml

This addresses:
* http://manage.dimagi.com/default.asp?171347 by raising the timeout and only ever trying one of the servers in the load balancing group
* http://manage.dimagi.com/default.asp?171406#960292 by adding a wiki and help endpoint
* The fact that it was hard to find the transfer server variable by making it dependent on the proxy_type (which it implicitly is)
@dannyroberts @czue @snopoke

Nginx Bug Fixes

---

ansible/roles/nginx/vars/wiki.yml

Somehow help.commcarehq.org was resulting in constant 302 redirects with the previous configuration.  I think it has to do with the response from confluence but haven't fully looked into it.

Fix 302 redirects

---

.gitmodules
ansible/deploy_proxy.yml
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/commtrack_ssl.yml
ansible/roles/nginx/vars/dhis.yml
ansible/roles/nginx/vars/dhis_http.yml
ansible/roles/nginx/vars/sentry.yml
ansible/roles/nginx/vars/tableau.yml
ansible/roles/nginx/vars/tableau_http.yml
ansible/roles/nginx/vars/wiki.yml
ansible/vars/dev.yml

This adds a few things:
* Handling for www.commtrack.org with the correct certificate
* Correct dhis not specifying the correct internal port
* Adds log rotating for site specific nginx logs
* Adds back in 502+503 error pages that I dropped in a rebase
* Adds an endpoint for sentry
* Adds handling for dhis and tableau redirection from http -> https
@dannyroberts 
@snopoke buddy

Nginx tweaks4

---

ansible/roles/nginx/vars/tableau.yml

Without these headers Tableau Server tries to guess the server name.

Set proxy headers for Tableau

---

ansible/roles/nginx/vars/cchq_ssl.yml

@dannyroberts @czue 
Even though new relic has this same data, I would like to have it in the nginx logs in order to look at things like requests per hour, or timing at a particular time of day.  @snopoke let me know if there is a better way/new relic does this already.

Adding timing log back

---

ansible/roles/nginx/vars/tableau.yml

@dannyroberts @czue 
This value is how long nginx waits for a response from the downstream server. I am on the fence for increasing it across the board, because I think its good to see what services are taking more than a minute to return.  If want to do that we would need a way to see 504 in the nginx logs, does that sound worth doing?

Add read timeout for tableau

---

ansible/roles/bennojoy.redis/templates/redis.conf.j2

decided 300 was a perfectly good redis timeout across infrastructures
we can parameterize this later if we ever need to, but didn't seem worth the effort

set redis timeout to 300

---

ansible/roles/bennojoy.redis/templates/redis.conf.j2

Reverts dimagi/commcarehq-ansible#169
after further debugging we now no longer suspect this is necessary

Revert "reduce timeout"

---

ansible/roles/bennojoy.redis/templates/redis.conf.j2

use the redis-server pid file consistent with init.d script

---

ansible/roles/redis/vars/main.yml

@snopoke @dannyroberts this is needed in order for ansible to actually upgrade the redis version. this is in effect on staging
@orangejenny

Pin version to 3.0

---

ansible/roles/nginx/templates/site.j2

@TylerSheffels was looking into the `OSError: [Errno 12] Cannot allocate memory` error we occasionally get. This ends up coming from us not being able to allocate enough space to run the `form_translate.jar`. I was looking at newrelic and our webworkers aren't that evenly balanced. hqdjango5 was maxed out in memory while hqdjango3 was only using 50%. I'm wondering if you think using a different load balancing schema will work better? was reading about it here: http://nginx.org/en/docs/http/load_balancing.html
buddy: @snopoke

least_conn load balance

---

ansible/roles/commcarehq/templates/localsettings.py.j2

@dannyroberts django gets screwy when we import `django-redis` before defining the `CACHES` variable. this fixes that
cc: @biyeun

Better find for redis module

---

ansible/roles/common_installs/tasks/main.yml

npm seems to install node, not the other way around

install npm instead of nodejs

---

ansible/roles/postgresql/tasks/main.yml

@benrudolph not sure if this is the right thing to do or not.
however as it currently works it installs both 9.4 and 9.1 and then fails trying to start them both up because there's a port conflict.

don't install multiple versions of postgres

---

provisioning/control.sh

@dannyroberts i was getting this error setting up postgres.
`fatal: [192.168.33.16] => {'msg': 'AnsibleFilterError: The ipaddr filter requires python-netaddr be installed on the ansible controller', 'failed': True}`
running this command on the controller fixes it, but I wasn't 100% sure this was the right way to make sure that happens.

install python-netaddr on the controller

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/supervisor/templates/supervisord.conf.j2
ansible/vars/dev.yml

@czue @dannyroberts @TylerSheffels 
What do you think about enabling the web interface for supervisor which would make it possible to start / stop services via the HQ system console (using XML-RPC)? I'm thinking of the pillows.

enable supervisor http iface

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Reverts dimagi/commcarehq-ansible#211
Not necessary if we merge https://github.com/dimagi/commcare-hq/pull/8233 now, since it adds this in settings.py

Revert "add locmem cache to localsettings"

---

ansible/roles/nginx/templates/nginx.conf.j2

Right now we only gzip `text/html`. I expect performance gains if we gzip css and js as well. I came across this optimization potential while preparing for the performance session for the upcoming summit. Hold off on merge because I haven't actually tested this yet.

Gzip all of the things

---

ansible/deploy_db.yml
ansible/roles/postgresql/templates/postgresql.conf.j2

@snopoke don't think the rotation was working quite how i planned. it ended up creating a bunch more files with `1`s appended at the end. i.e.:
```
<filename>.1.1
<filename>.1
<filename>
```
this is an alternative that keeps 1 weeks worth of logs

Fix pg rotation

---

ansible/roles/datadog/templates/datadog.conf.j2

@snopoke i deployed this and here were a few changes i had to make. it's unclear to me whether or not it's working. i can't find the metric yet in datadoghq. i'd imagine it'd be under `nginx.timings` since that what i called it [here](https://github.com/dimagi/datadog-parsers/pull/1/files#diff-04f4e797004c16d4737c308c9202e55cR28). are there datadog log files that you know i could check out see what's happening?

A few fixups for the datadog parser

---

ansible/roles/nginx/vars/main.yml

@TylerSheffels 
This is accompanied by a change in vars file to have each env point to its own ssl files (1fcc9e5 in secret repo)

use separate certs for separate envs

---

ansible/roles/nginx/tasks/install.yml

@czue @TylerSheffels this looks to be the culprit for the changing log dir permissions. we don't need to do this cause we already create the `log_home` in common with different permissions: https://github.com/dimagi/commcarehq-ansible/blob/nginx-log-dir-fix/ansible/roles/commcarehq/tasks/main.yml#L15
cc: @proteusvacuum

Don't create log dir

---

ansible/roles/common_installs/tasks/main.yml

the root cause of http://manage.dimagi.com/default.asp?186591 is that the clocks are out of sync on the machines by more than 10 minutes. yuck.
also verified that older machines (e.g. hqdb0) have ntp installed properly, but newer ones (e.g. hqdjango12) do not. 
I didn't run deploy_common because i was worried about side effects so just manually updated india. I *think* that prod might be fine because rackspace might handle it a level above our vms (?)

install ntp on all machines

---

ansible/roles/nginx/vars/cchq_ssl.yml

This prevents someone from embedding HQ in another page using an Iframe and hijacking clicks to perform other actions. @czue 
cc: @dannyroberts

Add X-Frame-Options

---

ansible/roles/apache2/tasks/main.yml

fwiw, despite that we don't use Apache any more, @snopoke, cc @gcapalbo 
Without this change, a2ensite in the next step fails, because /usr/sbin/a2ensite doesn't recognise the file as a site config if it doesn't end in ".conf"

Apache wants site configs to end in ".conf"

---

ansible/roles/nginx/tasks/install.yml

Last change to Ansible tasks for a while, I hope. 
Small. @snopoke, cc @gcapalbo

Ansible user must sudo to add an apt repo

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/dhis.yml
ansible/roles/nginx/vars/icds_tableau.yml
ansible/roles/nginx/vars/main.yml
ansible/roles/nginx/vars/motech.yml
ansible/roles/nginx/vars/tableau.yml
ansible/roles/nginx/vars/wiki.yml

This goes with https://github.com/dimagi/commcare-hq-errorpages/pull/5
After both PR's are merged we will need to run deploy_proxy on:

Reconfigure error pages to be generic for all nginx sites, add 400 page

---

ansible/roles/nginx/vars/motech1.yml
ansible/roles/nginx/vars/motech2.yml

@TylerSheffels I think this is the correct configuration.  I copied:
https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/nginx/vars/motech.yml

Fix DHIS2 Reporting Correct Server URL on motech1/motech2

---

ansible/roles/elasticsearch/defaults/main.yml
ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

**This is not tested.**
The new `elasticsearch_host` variable should be overridden in host-specific vars, and should be set to the internal IP address of the host. 
These changes are based on [Elasticsearch's blog post about the vulnerability](https://www.elastic.co/blog/scripting-security).
@czue, @snopoke, buddies @calellowitz, @sravfeyn

Secure Elasticsearch

---

ansible/deploy_common.yml
ansible/roles/ufw/readme.md
ansible/roles/ufw/tasks/main.yml
ansible/vars/dev.yml

@kaapstorm @snopoke this is deployed to softlayers and seems to be working well. rather than manually managing all our services to run on the right interfaces we can just disable all inbound traffic with a software firewall.

use ufw to restrict certain interfaces

---

ansible/roles/shared_dir.yml
ansible/roles/shared_dir/tasks/setup_host.yml

Fix `BlobDeletionPillow` failure:
`corehq.blobs.exceptions.Error: cannot initialize blob db: shared drive path is not a directory: '/mnt/shared_data'`
@dannyroberts @czue

Add shared dir to pillowtop server

---

ansible/roles/nginx/tasks/install.yml

This was a confusing one for me. On softlayer we don't run ansible as root, we smartly run it as the ansible user. The ansible user is a member of the sudoers group, so it can run any command it needs to, but for commands that require elevated permissions we need to specify `sudo: yes` on the actual task. We probably didn't notice this before because other environments run as root.
cc: @orangejenny @benrudolph @dannyroberts

Add sudo to SSL cert commands when running ansible as not root user

---

ansible/roles/shared_dir/tasks/install.yml

Forgot to create the group when not installing NFS.
@dannyroberts @benrudolph

Create shared dir group for shared files

---

ansible/roles/common_installs/tasks/main.yml

Looks like we weren't specifying a version of npm before. I checked locally that `npm install -g npm@3.6.0` works.
@benrudolph

pin npm to latest version

---

ansible/roles/nginx/vars/cchq_ssl.yml

@dannyroberts did some reading on the cache control header. it's still a little unclear to me why our static files were being cached at all since we never added that header. i'm assuming it has to do with the fact that it was coming from the same origin. this allows any system to cache our static files, which i think is fine since anyone can access our static files from our site anyways.
this will cache for a month. we should start seeing this effect take place on staging over the next 24 hours when the amazon cloudfront cdn starts expiring static files. note the Cache-Control header

add cache-control header

---

ansible/deploy_proxy.yml
ansible/roles/nginx/tasks/install.yml
ansible/roles/nginx/vars/icds_tableau.yml
ansible/roles/nginx/vars/main.yml

Because the ICDS tableau server is hosted on the India cloud we need a new certificate for an endpoint that isn't india.commcarehq.org.  There is a bit of copy pasting in the copying certs to proxy step that could be refactored in the future.
@nickpell

Custom icds cert

---

ansible/roles/commcarehq/templates/localsettings.py.j2

implementing the idea of @proteusvacuum from http://manage.dimagi.com/default.asp?217882
UCR postgres requests were trying to connect on the wrong port. it was only a problem on staging but limited testing on prod indicates it shouldnt break anything
this is deployed to staging and i tested it in a private release on prod
cc: @emord

adding port to psql address for ucr

---

ansible/roles/nginx/vars/riakcs.yml

Transfers from HQ to Riak CS were failing with 413 errors.
@benrudolph @snopoke

Increase max body size for Riak CS uploads

---

ansible/roles/ecryptfs/tasks/main.yml

This automates partitioning, formatting, and mounting of block storage volume as data drive. Currently the only machines that use it are riakcs hosts.
See also: https://github.com/dimagi/commcare-hq/pull/10675
@benrudolph @dannyroberts cc @snopoke

Format and mount block storage as data drive

---

ansible/roles/ecryptfs/tasks/main.yml

`/etc/fstab` was getting two lines to mount `/dev/xvdb1` and none to mount ecryptfs.
@benrudolph @dannyroberts @TylerSheffels cc @snopoke

Fix ecrpytfs mount check and write to fstab

---

ansible/roles/common_installs/tasks/main.yml

This is so django-simple-captcha can write text in images
@benrudolph cc @kaapstorm

Add libfreetype6-dev to common package installs

---

ansible/roles/redis/vars/main.yml

Version `3:3.0.5-1chl1~trusty1` is no longer available, now it's `3:3.0.7-1chl1~trusty1`
@NoahCarnahan @dannyroberts

Accept a variable redis version

---

ansible/roles/commcarehq/templates/localsettings.py.j2

In spite of enabling CSRF on India, no one filed a bug indicating an unexpected behaviour (there were around 130 request rejections). I have analyzed logs from last 3 months [here](https://docs.google.com/spreadsheets/d/1jq1MwUiMmMr0klz5_kh-H54HVbcG2_M1vnPUHlxLBdU/edit) (from india+prod). There are couple of doubtful csrf rejections, these are not reproducible and they even look like expected behaviours. At this point, we should turn on CSRF rejection on Prod for a day/week, let users report a bug if any rejection is unexpected and fix them
Before merging this in, it would be good for anyone to review the [logs analysis](https://docs.google.com/spreadsheets/d/1jq1MwUiMmMr0klz5_kh-H54HVbcG2_M1vnPUHlxLBdU/edit) Best way to review and discuss might be either through doc comments or a quick …

start rejecting csrf failures

---

ansible/roles/captain/tasks/main.yml

install apt requirements for captain (required for the github3py pip package). @millerdev

Add libffi task

---

ansible/roles/captain/tasks/main.yml
ansible/roles/common_installs/tasks/main.yml

@millerdev this is required now that github3py will be used in our prod environments

Move libffi to common installs

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

@nickpell @snopoke
First commit allows us to manually specificy machines to search for when performing cluster discovery.  This is necessary when the machines aren't on the same network.  See [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/modules-discovery-zen.html#unicast) for more info.
Second commit sets `network.host` as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/modules-network.html#modules-network)

Configure ES for cross-network clustering

---

ansible/roles/riakcs/join_cluster.yml

@millerdev @danielroberts
Danny just had this same issue coming up.  I think it's triggered by limiting the machines that you deploy - I think the variables aren't set on the control node if it's not processed in the ansible command

Comment on why the hostvars[riak_control] dict may be empty

---

ansible/roles/nginx/vars/cchq_ssl.yml

http://manage.dimagi.com/default.asp?226167#1148928
This was failing because the zip is almost 400MB, so nginx barfs. Manually edited on softlayer, but should probably be run on all other environments. 
@benrudolph @nickpell interrupt buddies
cc @dannyroberts code buddy

500MB limit for client_max_body_size

---

ansible/roles/nginx/vars/motech.yml
ansible/roles/nginx/vars/motech_http.yml

Moving to a model where motech servers are at motech.commcarehq.org/INSTANCENAME
This configuration sets this up for the servers required for the UN Supply project.  (It also removes the configuration for the unused endos-motech.commcarehq.org machine).  
@czue @calellowitz @emord 
Can one of you review, merge and deploy?

Setup proxy for a single MOTECH endpoint

---

ansible/roles/elasticsearch/tasks/rolling_restart.yml

@czue I think this is what happened with es2 earlier. Thoughts on adding a message to warn the restarter they might need to go and do things manually?
cc @proteusvacuum

Add message about restarting node

---

ansible/deploy_control.yml
ansible/roles/ansible-control/defaults/main.yml
ansible/roles/ansible-control/meta/main.yml
ansible/roles/ansible-control/tasks/main.yml
ansible/roles/ansible-control/templates/sudoers.j2

to auto-manage which users can `sudo -iu ansible bash` without a password

add /etc/sudoers.d/ansible file

---

ansible/roles/ecryptfs/tasks/main.yml

Reverts dimagi/commcarehq-ansible#387
We don't actually care about what's in `mtab`. The point is to add it `/etc/fstab` so that it's there after reboot.
This change broke the next task which actually adds it to `/etc/fstab`

Revert "Update main.yml"

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2

@dannyroberts @millerdev @nickpell
Setting up forced allocation awareness for the ES migration:
https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html
(with https://github.com/dimagi/commcare-hq/pull/12041, although they don't need to be merged together)

Set zone for ES nodes for allocation awareness

---

ansible/roles/touchforms/tasks/main.yml

@benrudolph: @wpride was proposing to rename this file from <env>.properties to application.properties. Any reason it was named <env>.properties originally? Seems like it always is copied in a specific environment's code root anyway.

Update config file name

---

ansible/roles/kafka/templates/kafkatcfg.j2

@proteusvacuum
You can see the correct path being used (hardcoded) here:
https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/kafka/files/kafka.sh#L2-L2

This kafka path was wrong

---

ansible/roles/users/tasks/main.yml

Now `deploy_common.yml` can run start to finish in check mode without failing! (That exclamation point is pretty depressing...)

run "find supervisorctl path" in check mode

---

ansible/deploy_db.yml
ansible/group_vars/all.yml
ansible/group_vars/kafka.yml
ansible/group_vars/zookeeper.yml
ansible/roles/datadog/templates/kafka.yaml.j2
ansible/roles/datadog/templates/kafka_consumer.yaml.j2
ansible/roles/datadog/templates/riakcs.yaml.j2
ansible/roles/datadog/templates/zk.yaml.j2
ansible/roles/kafka/tasks/main.yml
ansible/roles/zookeeper/defaults/main.yml

@snopoke initial setup with kafka monitoring. running into a couple issues that i'm still working out:
1. i can't seem to figure out or connect to the JMX port on prod or staging (can do so locally). without it, datadog can't pick up kafka stats
2. i'm confused as to how to figure out what the consumer groups are for each topic. i had thought that they would be the group-id for the consumer, but datadog doesn't seem to be picking any changes up. maybe @czue knows something

kafka monitoring

---

ansible/roles/ansible-control/templates/sudoers.j2

Reverts dimagi/commcarehq-ansible#458
This actually isn't necessary, and it's overwridden by the cchq sudoers file anyways.  I think you just need to do something manual during initial set-up.

Revert "Let the ansible user sudo without a password"

---

ansible/group_vars/all.yml
ansible/roles/shared_dir/tasks/setup_host.yml

@snopoke @czue @millerdev @benrudolph 
Our prod db machine comes with a 160GB data disk that no one seems to know existed and has remained unmounted since the migration to virginia. This PR allows us to mount that drive make it the nfs drive, to deal with repeated issues we have running out of disk space on db0 and the shared drive. Once we switch to the new drive, i can manually rsync the contents of the old one over.

putting shared drive on data disk

---

README.md
control/init.sh

use `--ask-vault-pass` instead of `--vault-password-file`
changed in the `ap`/`aps` aliases and in the README

do not encourage storing vault password in a plaintext file

---

README.md
control/init.sh

@snopoke @benrudolph @millerdev 
We could probably tune the user permissions a bit better so we can deploy control from our normal users, but this approach isn't too bad for an infrequent workflow.

Change deploy-control to output the commands used to deploy control

---

ansible/vars/softlayer/softlayer_public.yml

@snopoke 
I think this was just an oversight when certs were pulled out of ansible vault, but it was breaking `deploy_proxy`

fixing cas cert ref

---

ansible/deploy_common.yml

This pr should make the cas proxy no longer dependent on the proxy role. Then we can take it out of the proxy group, so we dont install the cchq site, and the bug where it has 2 default servers, prevent nginx from starting will be fixed.
@benrudolph cc: @snopoke

changing playbook to support the cas proxy removal from proxy group

---

ansible/roles/datadog/templates/datadog.conf.j2

Make it easier to query groups of hosts (such as "group:riakcs") in datadog.
Tested locally with vagrant to make sure it works as expected. Not deployed yet. Will deploy once reviewed/merged.
@esoergel

Add group tags to datadog conf

---

ansible/roles/nginx/vars/motech.yml

This previously failed because the DNS wasn't configured correctly for motech3.internal.commcarehq.org.   This has now been fixed.

Add CDC MOTECH Server

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cchq_ssl.yml

@wpride @dannyroberts ok so here's one option we talked about. Not positive it'll work, but this'll require formplayer to make all its requests like `/formplayer/my-domain/my-username` then it'll get proxied to the the `formplayer` upstream and be balanced with `hash $request_uri consistent` which will then hash based on domain and username. _hopefully_ this'll mean that data is divided equally among all servers that we have. and we can then avoid using the nfs and store directly on `/opt/data`, the encrypted drive

Route formplayer requests based on sessionid

---

ansible/roles/nginx/vars/riakcs.yml

Hopefully this will fix Riak node down causing error on client.
I've repeatedly observed errors like this in Riak CS access log when it's corresponding Riak service is down:
```
/var/log/riak-cs/access.log.2016_08_25_22:172.24.32.20 - - [25/Aug/2016:22:46:51 +0000] "PUT /buckets/blobdb/objects/commcarehq%2Fd<snip-production-doc-name>.xml.adf0e9982920427fb8353942c3828b58 HTTP/1.0" 403 309 "" "Boto3/1.2.3 Python/2.7.6 Linux/3.13.0-86-generic Botocore/1.3.30 Resource"
```
The cluster is usually still operational when this occurs, it (usually) just has one node down. This change should make the proxy try the request on the next node, which is hopefully not down and can service the request without causing the client to error out.
OOM killer has been the cause of Riak going down, and is the …

Proxy to next server on 403 from Riak CS

---

ansible/ansible.cfg

Comment was different for each user doing deploys causing annoying comment-only file changes. I would have liked to include the relative file path inside the ansible repo in the comment, but I couldn't find a way to format the `{file}` variable :(
@calellowitz @NoahCarnahan

Fix noisy ansible managed comment

---

ansible/roles/elasticsearch/tasks/main.yml
ansible/roles/elasticsearch/templates/create_es_snapshot.py.j2

moves the cron job to snapshot es restores from midnight to 4 so that the pillow checkpoint job from https://github.com/dimagi/commcare-hq/pull/13154 can finish running first

moving snapshot cron job back to allow checkpoints to happen first

---

ansible/roles/postgresql/templates/postgresql.conf.j2

@czue @snopoke @benrudolph 
It looks like the standby is lagging behind the master server (at least in the afternoon in boston) probably due to the low volume of writes. This forces the master to send an update to the standby ever 60 seconds even if the WAL is not filled which should cut down lag to a minute at most.

adding archive timeout

---

ansible/roles/formplayer/tasks/main.yml

@czue @wpride every time formplayer downloads a jar it temporarily saves it in `/tmp` so we have a huge number of ccz files in `/tmp`. also large number of `tomcat.*` directories which from a little reading shouldn't be deleted while the server is running. this task will just delete the old files (including the cczs, but excluding the tomcat dirs) while i figure out a way to safely delete the `tomcat.` dirs

Purge old formplayer files

---

ansible/group_vars/all.yml
ansible/group_vars/elasticsearch.yml
ansible/group_vars/kafka.yml
ansible/group_vars/postgresql.yml
ansible/group_vars/proxy.yml
ansible/group_vars/riakcs.yml
ansible/group_vars/webworkers.yml
ansible/roles/datadog/tasks/integrations.yml
ansible/roles/datadog/templates/elastic.yaml.j2

We're already running the agent on the ES machines. This just puts the ES integration on those machines instead of on the PG machine. This should make the builtin dashboards work better: https://app.datadoghq.com/screen/integration/elasticsearch

move elastic datadog integration to ES machines

---

ansible/roles/elasticsearch/tasks/main.yml

@snopoke @czue @benrudolph 
It turns out that the aws plugin for elasticsearch has a hardcoded list of supported regions which does not include the mumbai datacenter, so to get it to work in india i had to specify an endpoint instead of a region. (This is deployed and verified that the snapshots are succeeding)

specifying endpoint in es snapshot setup

---

ansible/requirements.txt
ansible/roles/java/files/install_java.sh

@dannyroberts @wpride this changes the owner of the java installations to cchq instead of root. this is necessary for monitoring the formplayer application. the formplayer service is run by cchq, but in order to access JMX it needs to read a couple files within the java directory. if you don't know what jmx is (i didn't), it's the recommended way to implement monitoring in java applications. i'm still new to the technology and wrapping my head around it, but it's built into java, which is why the files are located in the java directory. from the docs:
> The JMX specification defines an architecture, the design patterns, the APIs, and the services for application and network management and monitoring in the Java programming language.
> Using JMX technology, a given resource is instrumented …

cchq owns java

---

ansible/roles/nginx/vars/motech.yml

@sheelio motech5 isn't up, so it blocks nginx restarting.
@nickpell

Remove motech5 server

---

ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2
ansible/vars/staging/staging_public.yml

I deployed this on staging already.  Tested it out by attempting to submit a doc via curl:
```
$ curl -XPUT 'http://es-server.example.com:9200/fakeindex/type1/1?pretty' -d'
{
"test" : "Ethan is testing"
}'
```
This succeeded before the change, and fails after with an IndexMissingException.  I did confirm that we are still able to create indices the way we normally do (in python, `es.indices.create(index="fakeindex")`).
The rolling restart didn't work for me on staging (I got a "failed to connect" error) - I had to manually call the start command.  For this reason I'll do the restart for prod in the office while pairing just to make sure we minimize ES downtime.
@calellowitz @dannyroberts @snopoke

Set auto_create_index to false

---

ansible/roles/couchdb/defaults/main.yml
ansible/roles/couchdb/tasks/main.yml
ansible/roles/couchdb/templates/local.ini.j2

@nickpell @mkangia 
on monoliths (and other servers running couch) the data directory is not on the encrypted drive. This fixes that for new installs. I will migrate old ones.

moving couch installs to encrypted drive

---

ansible/vars/softlayer/softlayer_public.yml

@snopoke datadog is still not enabled, but this makes it easier to temporarily enable

Add ddog vars

---

ansible/roles/users/tasks/main.yml

Just sets a default value for `absent_user_keys.results` if the previous task has been skipped.
@snopoke cc @dannyroberts @mkangia

Handle when absent_user_keys has been skipped

---

ansible/roles/nginx/vars/main.yml

http://manage.dimagi.com/default.asp?246395
@millerdev The reason that using `--check` looked like it was doing the right thing, was because it was copying over the correct file, but then overwriting it with the next one.
buddies @benrudolph @snopoke

wrong cert name

---

ansible/roles/nginx/vars/motech.yml

This is a server that is needed for MOTECH / DHIS2 integration in Madagascar.   Can you review and deploy to the proxy server?
@emord @kaapstorm

Add Mikolo DHIS2 Server

---

control/init.sh

The vagrant user isn't going to be able to authenticate on GitHub. Clone using http so we only need read permissions. (This assumes we should be logging into vagrant boxes as vagrant ... and that we care about cloning commcare-hq-deploy, which afaik we won't really need on vagrant.)
@snopoke @millerdev

Allow vagrant user to clone commcare-hq-deploy

---

README.md

DimagiKeyStore should be mentioned in the docs before the user is told to run a full deployment.
"Obtain a copy" is pretty vague. Open to suggestions.
@millerdev cc @NoahCarnahan

Document DimagiKeyStore

---

ansible/roles/nginx/templates/site.j2

When fake_ssl_cert is true, nginx_ssl_(cert|key) won't be copied, resulting in an invalid nginx config. Instead of copying fake SSL certs, just point nginx at the ones it already has.
@snopoke cc @NoahCarnahan

nginx config when fake_ssl_cert

---

ansible/roles/nginx/vars/cchq_ssl.yml

@calellowitz pulled out the import part from https://github.com/dimagi/commcarehq-ansible/pull/618/commits/bc9860bbdf992c9dcb5dcbdc25f7803baa1347ff This'll block any deploy proxy so it'd be nice to get it in sooner than the icds stuff

Fix proxy deploy

---

ansible/deploy_riakcs.yml

Occasionally riak has lost an object. This will allow us to better track how often this is happening. See https://manage.dimagi.com/default.asp?248739 for more details.
The size of compressed access logs for the past month is about 50MB, so this will increase the storage requirements to about 600MB.
@dannyroberts cc @kaapstorm @javierwilson @snopoke

Keep riak-cs access logs for 1 year

---

ansible/roles/postgresql/templates/pgbouncer.ini.j2

Change pgbouncer.ini to include access for databases that are in the standby's master DB.

include dbs on standby

---

ansible/vars/icds/icds_public.yml

https://github.com/dimagi/commcare-hq/pull/15479
This creates specific pillows for curs that are important for ICDS. @sheelio can you take a look at this list to make sure I got the important ones correct?
@snopoke May also be good to split the "non-priority" pillow into two or three, but I'm not familiar with specs on the ICDS machines, so I don't want to overwhelm them. I think we'll likely want (number of cores - 1 or 2) number of static pillows running.
I think I recall you mentioning that our web workers are underutilized. Maybe we could start one or two pillows on those as well?

prioritize ucr pillows for icds

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cas_ssl.yml

Tested this on staging with ethan also hitting the server.
This will rate limit based on the server name so "cas.commcarehq.org" (which I think is what all phones will be hitting) It doesn't seem necessary to block the main site as that's only used via the web correct? if that's necessary, It'll also take some refactoring as we use the same base yml file for prod, softalyer and icds
@snopoke 
@gcapalbo @benrudolph

rate limit nginx

---

ansible/roles/nginx/vars/cas_ssl.yml

initial limit was for one webworker - now we're going to have 3

increase nginx rate limit

---

ansible/vars/icds/icds_public.yml

variables where in the vault, but not used

sentry vars actually used

---

ansible/group_vars/celery.yml
ansible/roles/datadog/tasks/integrations.yml
ansible/roles/datadog/templates/celery.yaml.j2

@dannyroberts either this is new functionality in 2.0 or we were getting lucky on prod. when `run_once` is specified, it only runs once even if it's skipped. so this never gets run unless celery is the first machine loaded
fyi: @emord @calellowitz

Remove run_once

---

ansible/deploy_mailrelay.yml
ansible/inventories/development
ansible/vars/dev/dev_public.yml
ansible/vars/icds/icds_public.yml

creates deploy_mailrelay that forces outbound email to go through the server defined at the "mailrelay" group (if defined at all)
also sets django mail server to localhost for ICDS (since we're taking care of thing at the MTA level)

mail relay configuration

---

ansible/roles/datadog/tasks/main.yml

datadog role will fail because of sudo_user in ansible 2, this fixes it.  this change however i have not actually tested on my dev environment. but since others almost identical have worked, i hope for the best!

datadog use pipelining (fails otherwise on ansible 2)

---

ansible/roles/couchdb/templates/local.ini.j2

@benrudolph @emord 
Here is auto compaction for couch. when the data size is less 30% of the db or 40% of the view, it will trigger a compact but only between 11pm and 4am. I only did it for the dbs that we have seen get large, because it seems like wasted resources otherwise, but happy to make it the default for all databases.

adding auto compact to couch for the two bad databases

---

ansible/roles/couchdb/tasks/main.yml

@kaapstorm @emord @benrudolph 
couch stores admin users by appending their name and password hash to the config file. every time we update the couch config the users gets deleted. this ensures that we remake the user each time we change the config.

remaking couch user whenever config changes

---

ansible/roles/http_proxy/tasks/main.yml
ansible/roles/nginx/templates/default.j2

this allows datadog to collect data even if /etc/hosts translates localhost to ::1

no proxy for localhost, also allow ::1 to check status

---

ansible/roles/load_test/tasks/install_prototype.yml
ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/vars/dev/dev_public.yml
ansible/vars/icds/icds_public.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml
ansible/vars/swiss/swiss_public.yml

This is to make it easier to override individual settings on a per host basis.
Goes with https://github.com/dimagi/commcare-hq-deploy/pull/238
buddy @nickpell

rename pg vars and add them to role defaults

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cas_ssl.yml

@emord I think this is what was causing the rate limit issues. 
> By default, the maximum burst size is equal to zero.
it still seems weird though... as soon as i added a burst size equal to the rate limit size, we stopped getting rate limiting errors

Require burst

---

ansible/vars/icds/icds_public.yml

@javierwilson @millerdev cc: @dannyroberts (i think you did the initial setup on this)
When trying to spin up a new riak machine on icds today i discovered that despite our configuration, existing nodes had been created with a ring size of 64, so in order to allow the new node to join its ring size, and all other new nodes, had to be 64 as well. I know we had good reasons to use 128 at first so I am curious if we think this is a long term problem or manageable.

fixes for new riak machine

---

ansible/roles/swap/tasks/main.yml

@dimagi/scale-team possibly part of the cause of our disk latency issues. On NIC the swappiness was set to 60 so postgres/riak were using swap even when there are gigs of memory available....
I don't think there's anything wrong with always setting swap to 0 no matter what so, i've removed the when check. 
I'm also not clear why there's swap in the first place. There is no swap_size defined in the inventory which is why this was never being run
@calellowitz run this on the new machines (esp pg3) before you fully migrate the db
buddy @millerdev

swappiness

---

ansible/deploy_common.yml

This change will make the role run twice during `deploy_stack`, once in `deploy_common` and once in `deploy_riak`. Adds a few seconds to the run but that's all.

run swap role on all nodes

---

ansible/vars/icds/icds_public.yml

@snopoke @javierwilson this was dropped in the reorganization of pg settings. noticed yesterday when migrating. considered also bumping up to 3500 since some machines are already there but figured that could be a different pr

adding back max connection variable

---

ansible/deploy_proxy.yml

hqproxy0 disk usage is > 85%, which we get alerted about. Log dir is 18G, total disk is 32G, so it's a significant portion.
Do you all think this is a reasonable response to that alert?

reduce size of nginx logs

---

ansible/roles/nginx/vars/cas_ssl.yml

Ran `awk -F\" '{print $2}' icds_cas_commcare-nginx_access.log* | awk '{print $2}' | cut -d/ -f 1,2,3,4,5 | sort | uniq -c | sort -nr` on the past two weeks of logs. Everything with > 1000 hits
```
21136256 /a/icds-cas/receiver/secure
4053911 /a/icds-cas/apps/download
1758144 /a/icds-cas/phone/restore
740852 /hq/multimedia/file/CommCareAudio
275377 /a/icds-cas/phone/keys
243680 /hq/multimedia/file/CommCareImage
39699 /a/icds-cas/receiver/9c3c742c280ef42b5a941496bb4de626
24762 /accounts/login/
6473 /hq/multimedia/file/CommCareVideo
1345 /
1329 /a/icds-cas/apps/dozZyXC.
```
Seems really strange that /hq/multimedia is being hit. I thought that those would only be hit on new installs and that all the phones had the app preinstalled. Either way it seems inefficient to have django handle those …

Endpoint rate limiting

---

ansible/group_vars/riakcs_new.yml

This should prevent datadog reporting from stopping when run against hosts in `riakcs_new` group.
@snopoke @calellowitz @emord

Add group vars for riakcs_new to fix datadog on hosts in that group

---

ansible/roles/shared_dir/tasks/setup_host.yml

@millerdev @javierwilson was debugging why formplayer wasn't working on swiss. it turns it out it couldn't download the application because when it'd attempt to, the nginx worker (user `www-data`) didn't have permissions to open the file. you cannot read a file unless you have access to the dir, so i figured that was the intent of the permissions already

Allow executable

---

ansible/roles/couchdb/templates/local.ini.j2

Was looking at https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1491675022153&to_ts=1494267022153&tile_size=m&exp_metric=couchdb.by_db.disk_size&exp_scope=&exp_group=db&exp_agg=avg&exp_row_type=metric#db:commcarehq_synclogs and saw that synclogs gets to almost 300 GB and hasn't been compacted ~1.5 weeks.
I think this should make compaction happen around every 4 days or so which seems better. Could probably do something more aggressive if we wanted as well

compact synclogs more

---

ansible/roles/swap/tasks/main.yml

@millerdev not urgent to do for icds, but figured we should get all of our machines on a similar setup

Increase swappiness to 1 because 0 disables swap

---

ansible/roles/couchdb/defaults/main.yml
ansible/vars/icds/icds_public.yml

@javierwilson 
This is actually set https://github.com/dimagi/commcare-hq-deploy/blob/master/fab/inventory/icds#L106

removing incorrect variable

---

ansible/vars/icds/icds_public.yml

This is used by the datadog integration as well. We could separate it into 2 different settings but waiting on feedback from @dannyroberts as to why this was commented out in the first place: https://github.com/dimagi/commcarehq-ansible/commit/0481f094022826160469637bee036e12fcf80dc2

set flower url for icds

---

ansible/roles/nginx/templates/site.j2

this is useful for icds, not sure if "warn" should better be an env var.

nginx error_log level to warn

---

ansible/roles/commcarehq/tasks/main.yml

after failing to deploy common due to easy_install requiring six, i switched to pip and it did solve the problem. my guess is pip module works better than easy_install in ansible 2.

using pip for setuptools

---

ansible/roles/webworker/meta/main.yml

also, automatic download of JDK7 is broken, which pushed to review if installing java was absolutely needed.  Time for openjdk?

we don't need no java for web workers!

---

ansible/roles/pg_standby/tasks/main.yml
ansible/vars/icds/icds_public.yml

it will be midnight by default, but we can change it by adding nadir_hour, I thnk this may change from env to env.

nadir hour not always midnight

---

ansible/roles/pg_standby/tasks/main.yml
ansible/roles/pg_standby/templates/create_postgres_dump.sh.j2
ansible/roles/pg_standby/templates/restore_from_backup.sh.j2

scripts should not live in /etc/cron.d, moving to /usr/local/sbin

moving system scripts to /usr/local/sbin

---

ansible/roles/commcarehq/tasks/main.yml

I had to do this manually on the last couple of deploys since the webworkers were redeployed @calellowitz and I tried to fix this before during the scale up but the PR had other issues. I think this should work correctly
@orangejenny

chown link to ~/www/env/current to cchq

---

ansible/deploy_stack.yml

besides installing postfix, this tasks are only played if mailrelay group is defined. not including this in deploy_stack before is what left the new webworkes with no email communication enabled.

mail relay deploy should be part of deploy_stack

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/icds/icds_public.yml

I've tested this locally by finding the next fire time for a task which lined up with the scheduled time in IST.

set celery timezone for ICDS

---

ansible/deploy_db.yml

Because an 11 GB log file is a bit much
@benrudolph any reason you put the couch 1 log rolling here? I just d this off of your work there
buddy @calellowitz

roll couchdb2 logs

---

ansible/deploy_http_proxy.yml
ansible/inventories/development

no need for all:!patch, because even patch server itself can use this, upstream path is defined at squid.conf level

fixing old mistake, http proxy for all

---

ansible/roles/commcarehq/templates/localsettings.py.j2

No idea why this is necessary, but recently a new machine was allocated on softlayer and it refused to connect to Riak CS.
Error on get object: `ClientError: An error occurred (InvalidRequest) when calling the GetObject operation: The authorization mechanism you have provided (AWS4-HMAC-SHA256) is not supported.`
On comparing this new machine (pillow3) to an existing machine (db0) I noticed they had slightly different client configs:
```
pillow3:
In [31]: bu.meta.client.meta.config._user_provided_options
Out[31]:
{'connect_timeout': 60,
'max_pool_connections': 10,
'read_timeout': 60,
'region_name': u'us-east-1',
's3': None,
'signature_version': 's3v4',
'user_agent': 'Boto3/1.4.4 Python/2.7.6 Linux/4.4.0-71-generic Botocore/1.5.71 Resource'}
db0:
In [12]: …
```

Set boto3 signature_version

---

ansible/deploy_mailrelay.yml
ansible/group_vars/all.yml
ansible/roles/common/tasks/main.yml
ansible/roles/common/templates/etc_aliases.j2

this is also to catch cron errors and in general to avoid mail to root to get lonely in /var/spool/mail...

RFC 2142 mail aliases

---

ansible/vars/icds/icds_public.yml

couch0 has always been running nginx for couch2 because I set it up in case anything went wrong during the initial deploy. @dimagi/scale-team

Updated couch proxy to be on couch0.

---

ansible/vars/softlayer/softlayer_public.yml

applied for softlayer, i applied same solution we sued for icds, however, i think kafka "logs" should probably not be in the same diretory as kafka logs which should be moved back to /var/log/kafka

moving kafka logs to /opt/data/kafka

---

ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/vars/production/production_public.yml
ansible/vars/staging/staging_public.yml

@dimagi/scale-team resolving #843 
This enables postgres's extension to track statistics.
Ideally wanted to use https://github.com/ankane/pghero because it can suggest indexes for us. https://github.com/ankane/pghero/blob/master/guides/Suggested-Indexes.md
It can be used when attached to the vpn with:
`docker run -ti -e DATABASE_URL="postgres://<user>:<pass>@<db_ip>:6432/<db_name>" -p 8080:8080 ankane/pghero`

Added postgres stat tracking.

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Minor change for password for enikshay private API password.

use md5 hash of password if available

---

ansible/group_vars/formplayer.yml
ansible/roles/formplayer/tasks/main.yml

@javierwilson @emord i tried using `tmpreaper` for this. i tested on staging doing `tmpreaper  7d /opt/data/formplayer` and checked the conf to make sure it updated correctly. i'm a little worried that using tmpreaper is too blunt. if formplayer gets deployed to a machine that needs a different config for tmpreaper than i'm not sure how we do that. this may make sense to use our old cron way of killing old files. what do you think?
cc: @proteusvacuum

tmpreaper for formplayer

---

ansible/roles/couchdb/tasks/main.yml
ansible/roles/couchdb2/defaults/main.yml
ansible/roles/couchdb2/tasks/main.yml
ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2

this fixes the permission denied issue for couch backups. but more importantly it adds backup scripts for couchdb2

couchdb2 backups

---

ansible/vars/softlayer/softlayer_public.yml

@nickpell This is a bad name for this variable, but that's what it is in the code for now. eventually it'll get moved to the other database alias

Add ICDS test alias to softlayer

---

ansible/roles/common/tasks/main.yml
ansible/vars/dev/dev_public.yml
ansible/vars/enikshay/enikshay_public.yml
ansible/vars/icds/icds_public.yml
ansible/vars/production/production_public.yml
ansible/vars/softlayer/softlayer_public.yml
ansible/vars/staging/staging_public.yml

there was a (race) condition, where sometimes we would end up with /etc/hosts with no extra etc_hosts_lines, this fixes it skipping any host auto-definition if that hosts is included in an extra custom etc_hosts_line

fixes /etc/hosts bug

---

ansible/roles/formplayer/defaults/main.yml
ansible/roles/formplayer/tasks/main.yml
ansible/vars/enikshay/enikshay_public.yml
ansible/vars/production/production_public.yml

Now with gzip archiving turned on, [production](https://app.datadoghq.com/dash/228649/formplayer-health?live=true&page=0&is_auto=false&from_ts=1503338161353&to_ts=1503942961353&tile_size=m&tpl_var_environment=production) and [enikshay](https://app.datadoghq.com/dash/228649/formplayer-health?live=true&page=0&is_auto=false&from_ts=1503338161353&to_ts=1503942961353&tile_size=m&tpl_var_environment=enikshay)'s formplayer data disks can very clearly support keeping these files around for a lot longer. You can see those disks are at 16-19%, and even if all of that were taken up by gzipped db files (they're not—there's also the commcare-hq releases which take up a fair amount of space, and of course the 10m worth of non-gzipped dbs), that's still a max of 75%, so space-wise this is quite safe. …

set formplayer_purge_time_spec to 8d on enikshay and production

---

ansible/deploy_localsettings.yml

Still needs to use --tags=localsettings at the command line. according to https://stackoverflow.com/a/25675696 there's no way to get around specifying it at the command line unless we go through and restructure it to not use tags
@biyeun @proteusvacuum

Add localsettings playbook

---

ansible/roles/pg_standby/tasks/main.yml

@calellowitz this will require a change in the wiki instructions, apparently this change (not allowing recovery in config dir) came from ubuntu packaging see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853868
I blame Myon, from #postgresql:
<xocolatl> Myon: I wonder if pg_ctlcluster should error out if it finds a recovery.conf in /etc
<Myon> possibly, yes
@nickpell this solves the issue you encountered

postgres complains if recovery.conf is in config dir

---

ansible/vars/enikshay/enikshay_public.yml

@javierwilson @mkangia @proteusvacuum 
I'm pulling this from the icds config https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/vars/icds/icds_public.yml
I didn't notice anything going wrong, just thought this might be a better setting. I think without this the enikshay task [0] is running at midnight UTC (530 IST). this would cause it to run at midnight IST
buddy @sravfeyn 
[0] https://github.com/dimagi/commcare-hq/blob/af4c010ee38dfeda5e6149a880be374c9dd16843/custom/enikshay/tasks.py#L62

Set celery timezone for enikshay

---

ansible/vars/enikshay/enikshay_public.yml

getting rid of message: [WARNING] found a duplicate dict key (ufw_private_interface)

fixes duplicate line in enikshay public vars

---

ansible/deploy_riakcs.yml
ansible/roles/riakcs/install/tasks/main.yml

after-reboot won't start riak because the whole "configuration and start riak" play is skipped, so I put this task separably. I am not sure it's the most elegant solution. opinions welcomed.

start riak after reboot

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cchq_ssl.yml

Reverts dimagi/commcarehq-ansible#923
@biyeun I'm reverting this as it makes it is blocking proxy deploys due to the syntax error.
I'm also against pushing this to prod since it has a really long cache (24 hours) and it doesn't look like the documentation covers the full HTTP endpoints we'd need to hit to clear it

Revert "cache prelogin pages"

---

ansible/deploy_chaos.yml
ansible/roles/chaos/defaults/main.yml
ansible/roles/chaos/tasks/main.yml
ansible/roles/chaos/templates/burnio.j2

Currently only supports one type of chaos: BurnIO, which I'm hoping to use for IO load testing on web workers.
@calellowitz cc @javierwilson @emord

Add playbook to deploy chaos to host(s)

---

ansible/roles/nginx/templates/site.j2
ansible/roles/nginx/vars/cas_ssl.yml
ansible/roles/nginx/vars/cchq_ssl.yml

@dimagi/scale-team pretty sure this will let us not rate limit after a 401.
According to https://en.wikipedia.org/wiki/Digest_access_authentication the authorization header is only on the second request. 
basing the nginx config off of this https://serverfault.com/questions/784852/nginx-conf-for-limit-req-based-on-http-header
@snopoke @sravfeyn

Don't rate limit when users are submitting authorization

---

ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/vars/enikshay/enikshay_public.yml

https://www.postgresql.org/docs/9.4/static/wal-configuration.html
We currently use the default value of 3 for `checkpoint_segments` which means a checkpoint is performed every 3 WAL segments (or every `checkpoint_timeout` minutes, which ever comes first; `checkpoint_timeout` defaults to 5 minutes).
Checkpointing too frequently can have the side effect of producing more WAL output than is necessary as described in the link above. I think this is part of the reason for the issues with the enikshay location import process creating runaway WAL.
The downside to setting a higher value means that it would take more time to perform a recovery if the db crashed since it has more to replay since the last checkpoint.
I've also seen warnings in the ICDS logs saying that checkpoints are happening too …

Update checkpoint parameters

---

ansible/roles/pgbackrest/tasks/main.yml
ansible/roles/pgbackrest/templates/pgbackrest.conf.j2

From what I'm seeing on enikshay, the incremental backups are taking up almost the same amount of room as the the full backups (looking at `repository backup size` in `pgbackrest info`).
I also don't see a way to expire incremental backups until the full backups they depend on expire, so this is causing us to run out of space on the standby machine unless we aggressively expire full backups.
What I'm proposing is that we switch from using incremental backups to differential backups so that we can use `retention-diff` to expire them. With this approach, based on our default settings in our ansible repo, we would then keep 4 weeks of weekly backups (`retention-full`) and 3 days of daily backups (`retention-diff`), mimicking the old pg basebackup method.
@javierwilson @snopoke

Switch to using differential backups

---

ansible/roles/pgbackrest/templates/pgbackrest.conf.j2

http://www.pgbackrest.org/configuration.html#section-expire
Our current pgbackrest config is archiving WAL logs and always keeping them around until the full backup they're associated with expires. This is causing us to run out of space on the enikshay standby and is limiting the number of backups we can actually store.
From my understanding this change should only keep the WAL archives since the last backup that happened (whether full, diff, or incr), which should help with the space issue. The downside is that we would only be able to do a point in time recovery (PITR) since the last backup. The upside is that we can store more backups.
I've already deployed this to enikshay since we're running out of space on the standby.
@javierwilson @snopoke

pgbackrest: only keep WAL archives since last backup

---

ansible/vars/enikshay/enikshay_public.yml

Now that we have rotating differential backups we can support more weekly backups. To add beyond this we'd need more storage.
@javierwilson @snopoke

Increase backup weeks for enikshay

---

ansible/requirements.txt

This is important for envs like ICDS that have more restricted firewall settings

use git+https instead of ssh

---

ansible/roles/postgresql/templates/postgresql.conf.j2

@snopoke @javierwilson cc: @kaapstorm 
The replication slots should ensure the correct number of WAL logs (i know thats redundant but it sounds better in my head) are kept for the standby, and nothing currently cleans up our WAL archive, which means these continue to pile up and have almost filled the disks on 3 of our machines. There is also nothing configured to read from this archive so it doesn't seem to serve much purpose. The postgres docs seem to imply that replication slots supersede WAL archiving for standbys.
Longer term if we want to keep this, it should be possible to properly cleanup but in the short term i think it makes more sense to get rid of it until we have a plan on what to do with it.

stop wal archiving

---

ansible/vars/dev/dev_public.yml

Hey @snopoke , it looks like couchdb2 should now be on 15984. am i reading this right?

couch_dbs now run on 15984

---

ansible/roles/couchdb2/vars/main.yml

We've had enough issues with synclogs not compacting that I'm not convinced this works, so I'm thinking about changing all of these to 10% which means that once the file size is 10% more than the data size it will compact. this should not really affect other dbs that much since they have a lot less data than synclogs. thoughts?
@dannyroberts @snopoke

Change couchbd2 compaction

---

ansible/roles/nginx/tasks/restart.yml

```
TASK [nginx : check nginx configuration] ***************************************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
```
@snopoke

Removed always_run usage.

---

ansible/roles/common_installs/tasks/main.yml

adding sysstat to our base os installs so we can gather better metrics on IO

add package sysstat to common installs

---

ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/roles/postgresql/templates/rotate_logs.sh.j2

https://trello.com/c/7OWkUCFl/173-improve-postgres-log-rotation-to-avoid-disk-filling-up
@calellowitz @snopoke @javierwilson A starting point for this. I haven't fully tested it being deployed, but think the basic idea is here. Workflow will be
1) postgres starts logging to files with the format postgresql-timestamp.log
2) postgres starts writing to a new log file after 100 MB
3) Every 15 minutes a script runs:
a) it removes the the log files except for the 20 newest ones
b) out of those 20 it gzips the 17 newest ones
Can easily change the 100 MB / 20 log files, but wasn't sure how much we want to keep around
buddy @mkangia

Postgres logging

---

ansible/vars/enikshay/enikshay_public.yml

Not yet deployed. More background here: https://docs.google.com/document/d/13Jlei5joToyME4DbnlHxRhQEpnrhUWvlQCtEDklz1po/edit#
This will require postgres downtime (restart).
@snopoke @dimagi/devops

Optimize pg mem settings on enikshay server

---

ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/templates/rotate_logs.sh.j2
ansible/vars/enikshay/enikshay_public.yml

100 log files = 10GB. This is temporary while analyzing and tuning performance. The previous setting retained less than 8 hours of logs at peak usage times.
Review commits individually 🐠 
@emord cc @calellowitz @javierwilson @snopoke

Tweak postgres log retention on enikshay

---

ansible/roles/common_installs/tasks/main.yml

Branched off of https://github.com/dimagi/commcarehq-ansible/pull/1019, only the last commit is new.
Can be merged once https://github.com/dimagi/commcarehq-ansible/pull/1019 and https://github.com/dimagi/commcare-hq/pull/18473 are deployed.
@emord

Remove 'remove lessc' task

---

.gitignore
commcare-cloud/commcare_cloud.py
commcare-cloud/setup.py
control/init.sh

This adds a `commcare-cloud` CLI tool, which currently has one command, `ansible-playbook`. To usage is essentially
```
commcare-cloud <env> ansible-playbook <...>
```
e.g.
```
commcare-cloud staging ansible-playbook deploy_localsettings.yml --tags=localsettings
```
The default behavior is to run with `--check` (`--diff` is always on), tell you whether it succeeded, and then prompt you whether to abort (default) or apply it. You can also run it with `--skip-check` to skip the check portion (in which case it will still ask you to confirm.
Other nice features:
- you only have to enter the vault password once per run and it'll use it for both check and apply.
- if you are not on master, it will fail, and tell you what cli arg to add to make it not fail.
- there's an additional shortcut for …

Commcare cloud

---

control/update_code.sh

so that the init script doesn't error on new machines (even if it is
harmless, it's annoying)
A better long term fix is to move the few remaining things from config/
into the ansible vault files

add commcarehq-ansible/config if it doesn't exist

---

control/.bash_completion

by respecting the ~/.commcare-cloud/ abstraction
@javierwilson found this when playing around with it locally

make bash completion run in other envs

---

control/.bash_completion

@javierwilson I don't know much about bash completion but when I was trying to debug locally, I noticed that this part looked the same as above (except for an extra `$` inside there) and figured that you had meant to replace this usage too. If not, feel free to close!

minorly simplify .bash_completion

---

ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/vars/dev/dev_public.yml
ansible/vars/icds/icds_public.yml

see https://www.postgresql.org/docs/9.4/static/runtime-config-replication.html
this is needed when using pg_dump from  the standby

allows (optional) replication delay

---

ansible/roles/kafka/defaults/main.yml

0.10 is the oldest available on apache.mirror.anlx.net. Switching to the archive site works for me. Alternatives to my proposed change include:
- changing the Kafka version
- setting the mirror above to `archive.apache.org` and adding the `/dist` to https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/kafka/tasks/main.yml#L16
I went with this single change because it was easier to PR from github—no offence taken if you implement one of the other methods above!

Apache no longer serves kafka 0.8.2.2 here

---

ansible/roles/nginx/templates/site.j2

"If the upstream directive does not include the zone directive, each worker process keeps its own copy of the server group configuration and maintains its own set of related counters. The counters include the current number of connections to each server in the group and the number of failed attempts to pass a request to a server. As a result, the server group configuration isn’t changeable.
If the upstream directive does include the zone directive, the configuration of the server group is placed in a memory area shared among all worker processes. This scenario is dynamically configurable, because the worker processes access the same copy of the group configuration and utilize the same related counters.
The zone directive is mandatory for health checks and on-the-fly reconfiguration of the …

add zone to nginx upstream config

---

ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/templates/postgresql.conf.j2
ansible/vars/enikshay/enikshay_public.yml

The current very low `work_mem` setting on enikshay is a likely cause of lots of disk access and inefficient query plans.
Numerous sources recommend at least 16MB, including http://pgtune.leopard.in.ua/ (when combined with other parameters from the enikshay server). Some sources say if you can't set `work_mem` to 16MB or more you need more RAM.
Note: I'm offline all next week, so unless you want to oversee this rollout, let's wait to merge until I'm back. Although feel free to roll it out before I'm back if you want to.
@snopoke @javierwilson

Make enikshay pg work_mem more reasonable (and update default)

---

ansible/roles/postgresql/templates/rotate_logs.sh.j2

Was missing .csv.gz and .log files, which means old log files were not being deleted at all because all but the most recent 3 end with .gz
This is too complicated...
@emord cc @javierwilson @snopoke @calellowitz

Fix find expression in log rotation script

---

ansible/roles/shared_dir.yml

@calellowitz @snopoke 
Looks like this is because we specify the vars file for share directory. before ansible 2.1.1.0 it also loaded group vars from the current working directory which was a "bug" (disagreement here: https://github.com/ansible/ansible/issues/16878)

Fix shared directory variables.

---

ansible/roles/common_installs/tasks/main.yml

Doing it this way will actually check if the version
is installed before installing it.

specify version correctly

---

control/.bash_completion

Bash completion now pulls options list from `commcare-cloud -h`, caching it in an env variable so it only has to calculate those once per login/session. This keeps us from having to independently update this file.
While I was at it I also made the playbook file completion a little less noisy.

Auto bash completion

---

ansible/roles/nginx/vars/motech.yml

Once this is deployed, I can actually pull down the servers from Rackspace.
@calellowitz @mkangia  (since you're on interrupt).

Remove unused MOTECH servers

---

ansible/es_rolling_restart.yml
commcare-cloud/commcare_cloud.py

this pushes the prompt/confirmation/user interaction
from es_rolling_restart.yml into commcare-cloud
Closes https://github.com/dimagi/commcarehq-ansible/issues/1093

add restart-elasticsearch command

---

ansible/roles/couchdb/defaults/main.yml
ansible/roles/couchdb/templates/create_couchdb_backup.sh.j2
ansible/roles/couchdb2/defaults/main.yml
ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2

Avoids: `/opt/data/backups/couchdb2': No such file or directory

fixing couchdb backup

---

control/init.sh

@nickpell thanks for raising the issue, this should fix it.
Fixes the following error
```
commcare-cloud production ansible-playbook deploy_proxy.yml
....
TASK [nginx : Copy cchq SSL cert] **********************************************
fatal: [hqproxy0.internal-va.commcarehq.org]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/home/npellegrino/.commcare-cloud/ansible/../config/production/ssl/commcarehq.org.combined.crt, Could not find or access '/home/npellegrino/.commcare-cloud/ansible/../config/production/ssl/commcarehq.org.combined.crt'"}
```
Solution was just to link `config` to the `~/.commcare-cloud/` dir.

link config dir to ~/.commcare-cloud/

---

ansible/cleanup.yml
ansible/roles/formplayer/tasks/cleanup.yml

i intend this to grow to cover all services, i'm starting with formplayer.
when we move services around, we have to cleanup cron jobs and other stuff (dbs probably best deleted manually?).

removes formplayer cron tasks

---

ansible/vars/pna/pna_public.yml

gladly, this error was being ignored by nginx, due the a conflicting server_name.

pna: fixes nginx redirect loop

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/nginx/vars/cas_ssl.yml
ansible/roles/nginx/vars/cchq_http.yml
ansible/roles/nginx/vars/cchq_http_j2me.yml
ansible/roles/nginx/vars/cchq_http_redirect.yml
ansible/roles/nginx/vars/cchq_redirect.yml
ansible/roles/nginx/vars/cchq_ssl.yml
ansible/roles/nginx/vars/commtrack_http.yml
ansible/roles/nginx/vars/commtrack_ssl.yml
ansible/roles/nginx/vars/enikshay_ssl.yml
ansible/roles/nginx/vars/icds_tableau_http.yml
ansible/roles/nginx/vars/motech2_http.yml
ansible/roles/nginx/vars/motech_http.yml
ansible/roles/nginx/vars/pna_ssl.yml
ansible/roles/nginx/vars/wiki.yml
ansible/roles/nginx/vars/wiki_http.yml

This allows Django to know whether a request is secure or not
https://docs.djangoproject.com/en/1.11/ref/settings/#secure-proxy-ssl-header
Without this `request.build_absolute_uri()` will use `http` as the request scheme instead of `https`. This is currently breaking dashboard feed URLs : https://manage.dimagi.com/default.asp?266533

 set secure proxy ssl header setting

---

ansible/vars/dev/dev_public.yml

root_email is used in /etc/aliases, sending all kind of alerts to the default dimagi.com email. this prevents it.

stop spam from dev env

---

ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/vars/production/production_public.yml

New synclog DB is up to date so we're ready to make the switch:

switch prod synclogdb

---

ansible/roles/monit/tasks/main.yml

autostarting monit is crazy, since must services need to be started after "after-reboot" is ran (ecrypt mounted)

monit should be manually started (after-reboot)

---

ansible/vars/softlayer/softlayer_public.yml

This will match https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/vars/icds/icds_public.yml#L144-L147
The dashboard tables are stored in the UCR database which has migrations and some QA happens on there
buddy @czue

Allow migrations on icds-ucr for softlayer

---

ansible/roles/postgresql/tasks/standby_progress.yml
ansible/setup_pg_standby.yml

This makes the pg basebackup run as an async task and then runs a loop of other tasks to compare the size of the standby node data with that of the master as a way of estimating progress

update set standby with progress

---

ansible/vars/icds-new/icds-new_public.yml

cleanup after performance testing

don't query pgmainstandby for ucrs

---

ansible/roles/setup_auth_keys.yml

this was necessary for the icds couchdb2 migration because 3 machines are rsyncing from a single one.
also, when I ran this for user ansible, it deleted all of our personal keys, which was really annoying to get out of

make setup_bidirectional_auth.yml not delete other keys

---

ansible/vars/icds-new/icds-new_public.yml

prodhqes-1.x is a holdover from the old cluster. The migration docs seemed to pretty clearly suggest we want the ES cluster on the new environment to be named icds-2.0.

change icds-new ES cluster name to icds-2.0

---

ansible/roles/nginx/vars/riakcs.yml

@dimagi/scale-team this in the riak proxy config but it's not in ansible

add client_body_buffer_size to riak proxy

---

ansible/roles/commcarehq/tasks/main.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/datadog/templates/elastic.yaml.j2
ansible/roles/datadog/templates/gunicorn.yaml.j2
ansible/roles/datadog/templates/jmx.yaml.j2
ansible/roles/datadog/templates/nginx.yaml.j2
ansible/roles/datadog/templates/pgbouncer.yaml.j2
ansible/roles/datadog/templates/postgres.yaml.j2
ansible/roles/datadog/templates/rabbitmq.yaml.j2
ansible/roles/datadog/templates/redisdb.yaml.j2
ansible/roles/formplayer/templates/application.properties.j2
ansible/vars/dev/dev_public.yml

This separates what the env name is that's used in Datadog and Django from what the env that's used for any folders or files.
So we can have `/home/cchq/www/icds/` and have the env on Datadog be `icds-new`.
This seems like a reasonable separation to me.

env separation

---

control/init.sh

I've had reports of people getting tripped up on having an old version of pip on their control env, and I've had this happen to me as well.
I think this is all we need to permanently fix it, unless anyone wants to advocate for the more conservative approach of pinning pip to a specific version, which I at this point think is probably overkill.

auto upgrade pip

---

fab/fab/environments.yml

celery core count bumped up to 8
One issue here is that these will still only be active at night. I'd like to figure out how to make these ones active during the day. Also thinking about making them use the PG standby nodes for DB reads. That seems tricky though.

increase async ucr processing

---

control/check_install.sh

First-time output looks like this:
```
→ Created ~/.commcare-cloud
→ Linked this repo to ~/.commcare-cloud/repo
→ Copied /Users/droberts/dimagi/commcare-hq/deployment/commcare-hq-deploy/fab/config.py to /Users/droberts/dimagi/commcarehq-ansible/fab/fab/config.py
```
First-time output where we couldn't find a previous config.py to copy from looks like this:
```
→ Created ~/.commcare-cloud
→ Linked this repo to ~/.commcare-cloud/repo
✗ /Users/droberts/dimagi/commcarehq-ansible/fab/fab/config.py does not exist and suitable location to copy it from was not found.
This file is just a convenience, so this is a non-critical error.
If you have fab/config.py in a previous location, then copy it to /Users/droberts/dimagi/commcarehq-ansible/fab/fab/config.py.
```
Steady-state (i.e. no-change) output …

make control/check_install.sh tell you what it is doing

---

fab/fab/operations/supervisor.py

new strategy is to copy fab/fab/services/templates/ to the legacy commcare-hq-deploy location on the remote server
and then let the make_supervisor*_conf management commands take it from there without being any the wiser
We can discuss how we want to do this long term—maybe it's time to move services out of the app deploy and into ansible?—but right now deploy is broken, and this is the lowest-touch fix.

Fix supervisor config templating

---

control/init.sh
fabfile.py

and go along with the fab convention rather than using the error-prone alias.
This also makes `~/commcarehq-ansible` rather than `~/commcarehq-ansible/ansible` the default starting directory on the control machine. This shouldn't affect any of the normal workflows, as `commcare-cloud` works fine from anywhere (right down to autocompleting playbook file names).

make fab require being in the commcarehq-ansible repo

---

commcare-cloud/setup.py
control/.bash_completion

Why? Because `commcare-cloud` is too long to type and doesn't auto-complete nicely
```
$ com<TAB><TAB>
comm            commcare-cloud/ compile-et.pl   complete
command         compgen         compile_et      compress
$ comm<TAB><TAB>
comm            command         commcare-cloud/
```
@dannyroberts

Add `cchq` alias for `commcare-cloud` tool

---

commcare-cloud/commcare_cloud/commcare_cloud.py
commcare-cloud/commcare_cloud/getinventory.py

Feedback from #1222
I thought about re-adding `scripts/inventory/getinventory.py` with contents:
```sh
#!/usr/bin/env bash
_env=$1
shift  # drop environment arg
commcare-cloud $_env lookup "$@"
```
But putting a bash script in a `.py` file felt dirty and I doubt anyone will really miss it. Let me know if you think it's still necessary.
@dannyroberts

commcare-cloud lookup and arg clarification

---

environments/icds-new/inventory.ini
environments/icds-new/public.yml

Small, but I remember this tripped me up during the migration. I checked that `commcare-cloud icds-new update-config`'s check mode doesn't show any diffs in localsettings.py (and then I didn't apply).

move hardcoded public IP to inventory file

---

commcare-cloud/README.md
requirements.txt

This adds a README to `commcare-cloud` with install instructions, and also documents how to hook up extra features like bash completion and running `commcare-cloud` anywhere outside the virtualenv.

document commcare cloud install

---

commcare-cloud/commcare_cloud/commcare_cloud.py

since capital N in [y/N] by convention means no is the default
Fixes #1237

make enter after [y/N] a negative answer

---

control/init.sh

rather than overwriting ~/.bash_completion
following up on: https://github.com/dimagi/commcarehq-ansible/pull/1242#pullrequestreview-87239064

just source .bash_completion on control machine

---

ansible/roles/postgresql/templates/pg_hba.conf.j2

was missing a /32 from the IP range

fix pg_hba.conf entry for tableau_readonly

---

ansible/roles/elasticsearch/defaults/main.yml

the reason to not go over 32 GB is because that's when ES starts using 64 bit pointers. Due to overhead that actually happens at 30.5 GB, but apparently 30 GB is more common usage. Could have caused issues when our servers on icds had 64 GB (48 GB now)

Cap ES at 30 GB

---

environments/staging/public.yml

Don't know why I set this to `False` in https://github.com/dimagi/commcarehq-ansible/pull/1132 ...can't test analytics on staging if debug is off.
Verified that the staging vault contains staging-specific keys for google and kissmetrics, and no key for hubspot, so we don't send staging data to real services.
@calellowitz

Turn on analytics debug flag on staging

---

environments/icds-new/public.yml

@czue I'm not running into the same issue you guys were running into where docs weren't being processed. I think we should turn this down because we're queueing a lot more now that  the related doc rebuilding ( https://github.com/dimagi/commcare-hq/pull/18843 ) has been merged
@nickpell

Reduce docs to queue

---

fab/fab/fabfile.py

by treating it as `{}` instead of as `None`

allow empty fab-settings.yml

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Just realized that the original PR was wrong when I was trying to deploy it. We don't want to wrap this in crontab anymore since it's not directly passed to the celery task decorator
@czue @nickpell

Fixed ASYNC_INDICATOR_QUEUE_TIMES in localsettings.

---

environments/icds-new/public.yml

Removing the old variable that used crontab and moving the timing back an hour. There weren't any issues with it, but it went a little longer in the morning than I originally meant to (10:30 AM IST).
@czue @nickpell

Async time changes

---

ansible/deploy_mailrelay.yml

postifx doesn't like that all VMs have the same hostname (template), also, some configs default to error.

fix postfix config

---

environments/icds-new/migrations/2017-12-01-initial/README.md
environments/icds-new/migrations/2017-12-01-initial/couchdb2-shard-plan.yml
environments/icds-new/migrations/2017-12-01-initial/role-mapping.yml

Hey @snopoke, I think I had originally mused about this with you during the recent ICDS migration, that it would be awesome if in the future we could write a "spec" for the migration and then write automation that works off of that. Imagine something like
```
commcare-cloud icds migration 2017-12-01-initial run postgresql
```
which would look at the mapping you'd specified of postgresql machines and initiate pairwise rsyncs. And then maybe
```
commcare-cloud icds migration 2017-12-01-initial check postgresql
```
would show you some progress information about the ongoing migration, as well as useful information like what logfiles to check to see the raw output of rsync commands, etc. for debugging. Anyway, that's the dream.
Anyway, I took a crack at writing down a file format for this …

add example (imaginary) migration spec for recent icds migration

---

ansible/roles/nginx/templates/site.j2
environments/production/public.yml

This PR adds HSTS (HSTS - a response header that tells browser that HQ is HTTPS only). This is not only a good security practice but also cuts rountrip cost of HTTP -> HTTPS redirect, as modern browsers will then automatically request HTTPS even when user enters an HTTP URL (see note on [this PR](https://github.com/dimagi/commcare-hq/pull/8076) about redirect time). But I have few questions before getting this merged in.
- Do we serve any HTTP traffic at all?
- Is 2 months expiry too high or too low?
- Should we include all subdomains as well?

HSTS config

---

ansible/roles/nginx/vars/cchq_ssl.yml

@ctsims noticed a lot of warnings related to this in enikshay logs. The default limits seem super low, so I'm upping this a bit to see if it changes the volume of these errors (which we can see in datadog).

increase proxy buffer size to 64k

---

control/check_install.sh

Enough of our control environments had an old version of git that I figure others inside and outside of our org also do, and having to upgrade git to make this work is a total pain and unnecessary.

fix check_install.sh on git 1.9

---

ansible/roles/couchdb/templates/local.ini.j2

ipaddr filter returns False if not an IP address.
i've changed it to ansible_default_ipv4, which works in monoliths, not sure if it works in prod.
perhaps we could just use {{ inventory_hostname }} ?

use ip address

---

environments/swiss/public.yml

play only tries to send keystore if it defined... so, removing.

no keystore for swiss

---

environments/swiss/inventory.ini

no external control on swiss (allows it to be a monolith)

no external control on swiss

---

fab/fab/operations/staticfiles.py

https://manage.dimagi.com/default.asp?267467
Bower commands need to run on webworkers because build_requirejs runs on webworkers and needs access to r.js
@dannyroberts 

Run bower commands on web workers

---

commcare-cloud/commcare_cloud/argparse14.py
commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commands/ansible/run_module.py
commcare-cloud/commcare_cloud/commands/command_base.py
commcare-cloud/commcare_cloud/commands/fab.py
commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
commcare-cloud/commcare_cloud/commcare_cloud.py
commcare-cloud/commcare_cloud/environment.py
commcare-cloud/setup.py
control/.bash_completion

This PR adds an alias `ap` for `ansible-playbook`
```
commcare-cloud <env> ap <playbook> ...
```
as well as doing some restructuring that makes adding other aliases trivial.
This required adding the latest pip argparse, which comes with python3 but not python2, as a dependency, and then doing a few lines of black magic to manually import that instead of the standard library argparse. (Python 2 Standard library `argparse` doesn't include support for aliases.) If this feels too gross to people, I can always scrap the alias feature and just PR the first commit (which which gives all command classes a shared base class), which is a nice change in itself.

Allow for commcare-cloud command aliases

---

commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commcare_cloud.py

Adds
```
commcare-cloud <env> deploy-stack <...>
```
with the alias `aps` as well. In its shortest form (also using the `cchq` alias) it could be
```
cchq <env> aps <...>
```

add deploy-stack commmand with alias aps

---

environments/production/inventory.ini

just stumbled across this, pretty sure this was just an oversight.
Not sure if the before and after are semantically equivalent or not,
but I think either way it is unlikely to have made a difference,
and the new way is surely the right one.

put each inventory variable on a different line (typo)

---

ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/templates/postgresql.conf.j2
environments/icds-new/public.yml

Current long queries are around 600ms. We could just turn it off but this seemed like a good first move

increase ICDS slow log threshold

---

fab/fab/utils.py

was previously sometimes using a Host object (rather than a string)
as dict key

fix check_and_translate_hosts

---

environments/production/public.yml

These settings were overlooked when the old cluster was decommissioned. See PR #1224 and branch dm/rm-old-riak-cluster.
@nickpell cc @emord

Set riak backend and ring size on prod

---

fab/fab/fabfile.py

@dannyroberts The reason that this didn't work earlier is that it was still basing the other directories (virtualenv_root, project_root, etc) on the old code_root. This overrides all directories that are dependent on   code_root before setting the config

Added task to update current supervisor config.

---

environments/icds-new/public.yml

@dimagi/scale-team as I mentioned in the meeting this morning. We'll see if this helps. Will retro if it fixes all our issues
manually dropped the extension

Remove query_stats for icds p6

---

ansible/roles/datadog/templates/celery.yaml.j2
ansible/roles/datadog/templates/nginx.yaml.j2
ansible/roles/datadog/templates/rabbitmq.yaml.j2

On ICDS we have proxy settings applied to the OS environment which get picked up by these checks requiring a settings change to force disable using the proxy settings.

fix datadog integrations

---

ansible/README.md

SSH requires additional permissions. Change to HTTPS for easier cloning

Clone from HTTPS instead of SSH

---

commcare-cloud/commcare_cloud/cli_utils.py
commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commands/ansible/run_module.py
commcare-cloud/commcare_cloud/commands/fab.py
commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
commcare-cloud/commcare_cloud/commcare_cloud.py

Similar to `commcare-cloud <env> fab manage:<command>` but (1) with nicer syntax and (2) without adding anything to stdout. (Fab has a bunch of extra output, and prefixes every line of manage command output with the host name, etc.)
Example:
```
$ cchq production django-manage list_couchdbs
ssh hqdjango0.internal-va.commcarehq.org 'sudo -u cchq /home/cchq/www/production/current/python_env/bin/python /home/cchq/www/production/current/manage.py list_couchdbs'
2018-02-16 20:02:25,702 INFO AXES: BEGIN LOG
commcarehq
commcarehq__domains
commcarehq__auditcare
commcarehq__users
commcarehq__meta
commcarehq__receiverwrapper
commcarehq__mvp-indicators
commcarehq__m4change
commcarehq__fluff-mc
commcarehq__apps
commcarehq__fixtures
commcarehq__synclogs_2017-11-01
commcarehq__fluff-bihar
```
Note that …

Add commcare-cloud <env> django-manage <command>

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

Looks like
```
django-manage       Run a django management command. `commcare-cloud <env>
django-manage ...` runs `./manage.py ...` on the first
webworker of <env>. Omit <command> to see a full list
of possible commands.
```

add help text to new django-manage command

---

commcare-cloud/commcare_cloud/environment.py

If you want to use environments outside this repo's `environments/` (eventually a main use-case), you can now at least do it super explicitly with
```bash
$ COMMCARE_CLOUD_ENVIRONMENTS='../outside-environments' commcare-cloud ...
```
Let me know what you think of this simple approach.

allow specifying a different environment set

---

ansible/roles/ecryptfs/tasks/main.yml
ansible/roles/elasticsearch/tasks/main.yml

this  is just to avoid initial --check crashing due to undefined values.

fix when so that --check doens't crash

---

docs/index.md

see if github pages supports markdown
Looks like anything at `docs/` should be available at https://dimagi.github.io/commcare-cloud (see https://help.github.com/articles/user-organization-and-project-pages/)

start github pages project site

---

environments/production/inventory.ini

This directive was not present for hqstandby0. I wonder how it sat up correctly.

Added data device

---

environments/enikshay/app-processes.yml

https://manage.dimagi.com/default.asp?270131#BugEvent.1457531
@proteusvacuum concluded that the CaseSearchToElasticsearchPillow was behind when users were reporting cases missing from the case search, so I'm bumping up the number of pillows.   The machine has plenty of [capacity](https://app.datadoghq.com/dash/host/328223540?live=true&from_ts=1516652242819&to_ts=1519244242819&page=0&is_auto=false&tile_size=m) to support the extra pillows.

increase number of case search pillows on enikshay

---

ansible/roles/supervisor/templates/supervisord.conf.j2

with logfile_backups=10, this will now save 200M per process
rather than 500M per process
production hqpillowtop0 logs were filling up disk
and with the current settings were going back almost a year

change supervisor logfile_maxbytes from 50M to 20M

---

.travis.yml
README.md
ansible/README.md
control/check_install.sh
control/init.sh
install.sh

I just had to setup my account on PNA and found some conflicting / differing instructions in `README.md` and `ansible/README.md`
There seems to be quite a bit of overlap between the two regarding setting up the environment. Any reason not to consolidate the install instructions into `README.md` and leave `ansible/REAMDE.md` for purely ansible info?
I was also thinking that it would be nice to have a script that you can just run from the web to do the full setup for you. Something like `bash <(curl -s https://raw.githubusercontent.com/dimagi/commcare-cloud/master/control/init.sh)`.
It seems like `init.sh` is basically there. Curious to hear others thoughts.
other buddy @esoergel

commcare cloud install

---

environments/icds-new/app-processes.yml

Would be good for this to run on its own for ICDS
@nickpell

Split case_rule_queue consumer to its own worker process

---

environments/icds-new/app-processes.yml

pillow 8 and 9 are both < 3 GB RAM used. so pushing them together and relieving pillow6 of some stress. Also may need to bump up form kafka topics soon. Will look into that tomorrow if ucr-forms is still slow
buddy @nickpell

Move ICDS form UCR pillow to it's own server.

---

ansible/requirements.txt
commcare-cloud/commcare_cloud/help_cache/ansible-playbook.txt
commcare-cloud/commcare_cloud/help_cache/ansible.txt
fab/requirements.txt

No idea if this will fix the
```
[ERROR]: failed to download the file: Failed to validate the SSL certificate
for github.com:443. Make sure your managed systems have a valid CA certificate
installed. You can use validate_certs=False if you do not need to confirm the
servers identity but this is unsafe and not recommended. Paths checked for this
platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs,
/usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was:
("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert
protocol version')],)",).
```
error, but it's just a patch release so it "can't" hurt.

update to Ansible 2.4.3

---

fab/fab/operations/supervisor.py

@dannyroberts I think this was introduced https://github.com/dimagi/commcare-cloud/pull/1415 but there were a lot of changes and I don't have an understanding of why this broke. Basically `inventory.groups['all'].hosts` is an empty list.
I think the real/ideal fix is not defining supervisor configs during deploy. I have an idea that I'll look to PR in the next week
@czue @nickpell should fix the issue we were talking about the past couple of days

Fix proxy definition

---

ansible/roles/common/tasks/main.yml
ansible/roles/common/tasks/mount.yml
environments/production/inventory.ini

In some clusters you may need to add an additional disk, specially if there's no support for LVM and need to mount it, currently, this process is manual, creating potential issues like the one when the proxy machine was rebooted and /mnt/storage not mounted.  This provides a fix for that, Ideally, we should migrate to LVM. @dannyroberts

support additional mount points

---

environments/enikshay/public.yml
environments/icds-new/public.yml
environments/softlayer/inventory.ini
environments/softlayer/public.yml

Changes based on feedback from https://github.com/dimagi/commcare-cloud/pull/1429#issuecomment-370682229
Validated this config with the following playbook:
```
- name: test
hosts:
- postgresql
- couchdb
- couchdb2
- redis
- elasticsearch
- rabbitmq
- zookeeper
- riakcs
- formplayer
- pg_standby
tasks:
- shell: mount | grep ecryptfs | cut -d" " -f 1
register: mount
check_mode: no
- assert: { that: "encrypted_root == mount.stdout"}
- debug: msg="{{encrypted_root}} == {{mount.stdout}}"
```

remove 'encrypted_root' var from public.yml files

---

ansible/deploy_cleanup.yml
ansible/deploy_common.yml
ansible/deploy_db.yml
ansible/deploy_load_test.yml
ansible/deploy_localsettings.yml
ansible/deploy_riakcs.yml
ansible/deploy_riakcs_new.yml
ansible/deploy_shared_dir.yml
ansible/es_rolling_restart.yml
ansible/roles/datadog/tasks/main.yml
ansible/roles/riakcs/create_admin_user/handlers/main.yml
ansible/roles/riakcs/sync_keys/handlers/main.yml
ansible/roles/shared_dir.yml
ansible/roles/zabbix_integrations/tasks/main.yml
ansible/setup_bidirectional_auth.yml

include is deprecated and "confusing" according to docs.
i have not tested riakcs playbook, but hanlders are supposed to be allowed to import tasks, so it should work.

getting rid of 'include'

---

ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/roles/postgresql/templates/postgresql.conf.j2

**Changes**
1) Changing auth-method to `trust` for Netvault user. 
2) Added directive `hot_standby_feedback = on`
I am concerned if it could have a negative impact on our Master nodes when a backup is happening.
According to https://www.postgresql.org/docs/9.6/static/runtime-config-replication.html `but can cause database bloat on the primary for some workloads`

Changed configuration for netvault user

---

environments/production/app-processes.yml

hqpillowtop2 is really high in memory. UCR pillows on prod take ludicrous amounts of memory. probably due to number of data sources. should probably go through and prune unused ones, but I'm not sure how easy that would be
buddy @czue

Move prod static UCR pillow

---

ansible/roles/common_installs/tasks/main.yml
ansible/roles/postgresql/tasks/main.yml

Getting closer to a smooth `deploy-stack`; in the last run I still had the following issues:
- What seemed like a short network connectivity error made me have to restart the process (at task `jython : Install Jython`)
- When I ran fab the way it failed made me notice supervisor wasn't properly set up, and running with `--tags=supervisor` fixed it—odd error both because that doesn't make a lot of sense and because this didn't happen in a previous run (yesterday)
- after trying again, I was then unable to connect to the celery machine. This has happened a couple times before, weirdly always to the celery machine
will keep investigating, but wanted to get these two fixes in anyway.

Two more tweaks for a smooth deploy-stack

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

adds -A to `commcare-cloud <env> ssh control`:
```
$ commcare-cloud production ssh control
ssh control.internal-va.commcarehq.org -A
```
fails over to `ssh` when using `mosh` (since it doesn't support ssh agent forwarding):
```
$ commcare-cloud production mosh control
! mosh does not support ssh agent forwarding, using ssh instead.
ssh control.internal-va.commcarehq.org -A
```

always include -A on ssh control

---

ansible/roles/postgresql/tasks/main.yml

use the pattern of flushing notify handlers rather than explicitly restarting

fix postgresql restart behavior on --tags=postgresql

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/getinventory.py
commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

enables this shortcut `cchq <env> ssh` for envs with only 1 server
buddies @sravfeyn @esoergel

don't require 'server' arg for monoliths

---

fab/fab/operations/release.py

In December I submitted [this PR](https://github.com/dimagi/commcare-cloud/pull/1116) to silence a very verbose Sentry warning. This required adding a new file `sentry.properties` at the same level as the existing `application.properties`. So I copied the pattern used for `application.properties` in that PR and added the single property needed in the file. Unfortunately that change doesn't seem to have worked as there is no `sentry.properties` file in the `formplayer` build directory. `grep`ing the code this seems to be what's missing, however I'd appreciate someone verifying that (or letting me know if Im way off)

Copy sentry.properties to formplayer dir

---

fab/fab/operations/release.py

was causing application.properties not to get copied

fix formplayer deploy (fixes #1474)

---

fab/fab/utils.py
fab/requirements.txt

This addresses https://manage.dimagi.com/default.asp?266529 by making sure the deploy fails fast instead of silently failing to create the release tag, and later failing hard when the release tag is not found on github.
If the github api key doesn't have the scope ```public_repo```, then the deploy fails right at the start with a 401 error.
Example release generated with new code: https://github.com/dimagi/commcare-hq/releases/tag/2018-03-19_23.08-staging-deploy

use newer github api library so deploy fails fast when api key doesn't have the right scope

---

fab/fab/utils.py

I thought https://github.com/dimagi/commcare-cloud/pull/1499 would be enough but there was an error when I was testing this.  The only way to know if you have permission to create a release is to try to - unfortunately you can't query this using the github api if you're using a token: https://developer.github.com/v3/oauth_authorizations/#oauth-authorizations-api

fail fast during setup_release

---

fab/fab/utils.py

Affects post-deploy emails - otherwise they always show as no changes because XXXXXX-production-setup_release equals XXXXXX-production-deploy.

distinguish between *-deploy and *-setup_release

---

ansible/roles/commcarehq/templates/localsettings.py.j2
environments/icds-new/public.yml

@snopoke I've seen some talk about taking this off of ICDS and this should do it, but I'm skeptical it will solve the issue. I tried to find correlation with any of the couchdb metrics we have in datadog, but couldn't find anything in particular.
My feeling is that https://github.com/dimagi/commcare-hq/blob/je/comp-feeding-forms-agg-script/corehq/ex-submodules/pillowtop/processors/form.py#L18 introduces too much churn on the users db but I have nothing to prove it other than at the end of the users DB is 15 GB and is then compacted to ~2 GB

Make auditcare configurable

---

commcare-cloud/commcare_cloud/commands/celery_utils.py

I think this would break if num_workers = 2

fix typo in get_celery_workers_config

---

environments/softlayer/inventory.ini

Because presently Backups are done only from standby.
and softlayer has no standby. Softlayer was not doing backups from September 2017 (_If I checked correctly_). That's a major issue.
I have here put db0 in the pg_standby group that enables backup scripts to be uploaded to db0. 
Though It is making a  change in `pg_hba.conf` that I think is not breaking anything. 
```
+# db0
+host   commcarehq	commcarehq	NXDOMAIN/32	md5
+host   commcarehq_p1	commcarehq	NXDOMAIN/32	md5
+host   commcarehq_p2	commcarehq	NXDOMAIN/32	md5
+host   commcarehq_p3	commcarehq	NXDOMAIN/32	md5
+host   commcarehq_p4	commcarehq	NXDOMAIN/32	md5
+host   commcarehq_p5	commcarehq	NXDOMAIN/32	md5
+host   commcarehq_proxy	commcarehq	NXDOMAIN/32	md5
+host   commcarehq_synclogs	commcarehq	NXDOMAIN/32	md5
+host …
```

Added db0 in pg_standby

---

ansible/roles/couchdb2/templates/monit.couchdb2.j2
ansible/roles/couchdb2/vars/main.yml
ansible/roles/redis/templates/monit.redis.j2

`ipaddr` filter can test for IP addresses and convert between various formats. If the value passed in isn't an IP address it returns false: https://docs.ansible.com/ansible/latest/playbooks_filters_ipaddr.html
These usages seem incorrect, at best they are a noop and at worse the convert a hostname like `hqdb0.internal....` to `False`.

incorrect usages of ipaddr

---

fab/fab/operations/supervisor.py

FYI @mkangia @dannyroberts 
This was causing the supervisor process name to be a blank string.

Fix django worker name

---

ansible/group_vars/proxy.yml
ansible/roles/datadog/tasks/add_integrations.yml
ansible/roles/datadog/tasks/remove_integrations.yml
ansible/roles/datadog/templates/http.yaml.j2

I want to test this out as a possible replacement for pingdom.
I've split out the `heartbeat` check from the others since that's usually the one that's flaky and has a lot of false positives.
Combine with https://github.com/dimagi/commcare-hq/pull/19880

datadog check for serverup

---

ansible/roles/datadog/templates/couch.yaml.j2

This check isn't necessary since in couch v1.0 environments there is only one couch server and in v2.0 environments the check here makes sure this only runs on a single host: https://github.com/dimagi/commcare-cloud/blob/462bb5a1feca95aba04a13e56aec38ee2a8fc32d/ansible/roles/datadog/tasks/add_integrations.yml#L54
The current check breaks PNA which uses `127.0.0.1` as the couch IP which is not what's in the inventory.

remove inventory host check in couch datadog config

---

environments/staging/inventory.ini

This is deployed through prod so on staging commands it fails because there's a different ansible/vault password.
buddy @proteusvacuum

Remove control from  staging

---

environments/icds-new/app-processes.yml

Evens out the number of workers consuming from the reminder_case_update_queue, and adds some for the reminder_queue.
@millerdev cc @biyeun

Rebalance celery workers used for messaging in icds

---

ansible/group_vars/all.yml

Datadog is skipping configs 
in https://github.com/dimagi/commcare-cloud/blob/ee1692663eddb6e10870cbf8c05f7991c1abfd0a/ansible/roles/datadog/tasks/add_integrations.yml#L38
since variable `datadog_integration_http` was not defined.

Added datadog_integration_http.

---

commcare-cloud/commcare_cloud/commcare_cloud.py
control/check_install.sh

This lets you run `cchq --control <env> fab deploy` and still be able to interact with prompts on the remote control machine.
I think I originally played around with this and then I let it slip and it didn't make it into the final (original) PR.

have --control run in interactive mode

---

commcare-cloud/commcare_cloud/commands/ansible/ansible_playbook.py
commcare-cloud/commcare_cloud/commands/shared_args.py
environments/staging/inventory.ini

Followup to https://github.com/dimagi/commcare-cloud/pull/1517 that still lets us run `cchq staging ssh control`, `cchq --control staging fab deploy`, etc.

specify staging control but skip it in ansible runs

---

commcare-cloud/commcare_cloud/commcare_cloud.py

this "metavar" thing (which changes the name of the variable in the help text) was something I did thinking I was clever when I renamed `environment` to `env_name`. But I wasn't being clever.

fix bash_completion

---

.travis/environments/travis/public.yml
ansible/group_vars/all.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/formplayer/vars/main.yml
ansible/roles/postgresql/tasks/main.yml
ansible/roles/postgresql/templates/pg_hba.conf.j2
ansible/roles/postgresql/templates/pgbouncer.ini.j2
ansible/roles/touchforms/templates/localsettings.py.j2
commcare-cloud-bootstrap/environment/public.yml
environments/development/public.yml
environments/enikshay/public.yml
environments/icds-new/public.yml
environments/l10k/public.yml
environments/pna/public.yml
environments/production/public.yml
environments/softlayer/public.yml
environments/staging/public.yml
environments/swiss/public.yml

I eventually want to pull out database config into its own file that is mediated by commcare-cloud and put in `.generated.yml` so we don't have all this `item.get('host', DEFAULT_POSTGRESQL_HOST)` stuff and so that the configs are easier to read and write and less error-prone / repetitive / redundant, but I thought I'd start with this refactor. Even if I never get there or it doesn't pan out, I still this refactor is a good one.

postgresql variable refactor

---

environments/enikshay/public.yml
environments/l10k/public.yml
environments/production/public.yml
environments/softlayer/public.yml
environments/staging/public.yml
environments/swiss/public.yml

Small change, but noticed this var isn't used anywhere. (And I can see that it was introduced in 94352ee and removed in cac766a.)

remove unused variable run_newrelic_plugin_agent

---

fab/fab/utils.py

@nickpell finally got to the bottom of this. Basically using a proxy is broken in this library: https://github.com/PyGithub/PyGithub/pull/709

Fix deploy for ICDS

---

ansible/roles/commcarehq/tasks/pillowtop.yml

can only go in playbooks. Noticed it was giving a warning about these being ignored.

remove hosts: in task file

---

environments/icds-new/postgresql.yml
environments/staging/postgresql.yml

This doesn't actually delete these databases; just removes them from ansible's awareness

remove remnants of commcarehq_icds_testdata

---

.travis/environments/travis/public.yml
ansible/group_vars/all.yml
ansible/roles/commcarehq/templates/localsettings.py.j2
ansible/roles/commcarehq/vars/main.yml
ansible/roles/datadog/templates/celery.yaml.j2
commcare-cloud-bootstrap/environment/private.yml
commcare-cloud-bootstrap/environment/public.yml
commcare-cloud/commcare_cloud/environment/main.py
commcare-cloud/commcare_cloud/environment/schemas/app_processes.py
environments/development/public.yml
environments/development/vault.yml
environments/enikshay/public.yml
environments/icds-new/public.yml
environments/l10k/public.yml
environments/pna/public.yml
environments/production/public.yml
environments/softlayer/public.yml
environments/staging/public.yml
environments/swiss/public.yml

Includes https://github.com/dimagi/commcare-cloud/pull/1583 (because otherwise they'd have a minor annoying conflict).
This changes `AMQP_HOST` from `127.0.0.1` to IP address on pna and from IP address to FQDN on swiss, neither of which I think should be a problem. For other envs there is no change.

Remove repetitive rabbitmq vars

---

ansible/roles/commcarehq/meta/main.yml
ansible/roles/common/meta/main.yml

No reason why all machines have to have supervisord

make supervisor dependency of commcarehq not common

---

fab/fab/fabfile.py

Cause now we run fab from `commcare-cloud`

Update message of update-translations.sh

---

.travis/environments/travis/proxy.yml
.travis/environments/travis/public.yml
ansible/group_vars/all.yml
ansible/roles/common/tasks/main.yml
ansible/roles/nginx/defaults/main.yml
ansible/roles/nginx/templates/nginx.conf.j2
ansible/roles/nginx/vars/main.yml
commcare-cloud-bootstrap/environment/proxy.yml
commcare-cloud-bootstrap/environment/public.yml
commcare-cloud/commcare_cloud/environment/main.py
commcare-cloud/commcare_cloud/environment/paths.py
commcare-cloud/commcare_cloud/environment/schemas/proxy.py
environments/development/proxy.yml
environments/development/public.yml
environments/enikshay/proxy.yml
environments/enikshay/public.yml
environments/icds-new/proxy.yml
environments/icds-new/public.yml
environments/pna/proxy.yml
environments/pna/public.yml
environments/production/proxy.yml
environments/production/public.yml
environments/softlayer/proxy.yml
environments/softlayer/public.yml
environments/staging/proxy.yml
environments/staging/public.yml
environments/swiss/proxy.yml
environments/swiss/public.yml

This is just refactoring without but also has the following change (lifted from the commit message):
> For envs that had nothing before, this adds a `worker_rlimit_nofile` directive to nginx confs
specifying the PAM file limit. I don't think in practice that changes anything.
a80e818
For example, staging `/etc/nginx/nginx.conf` will now have
```
worker_rlimit_nofile 4096;
```
Tested on

Move nginx / proxy vars to proxy.yml

---

ansible/letsencrypt_cert.yml

What it does.
1) Uses Certbot to get the certificate and uses HTTP-01 challenge. 
2) Uses SITE_HOST and NO_WWW_SITE_HOST variables.  
3) Dumps the certificate on the screen so the operator can copy paste it to vault file. 
4) copy the certs instead of creating a soft link (Soft link will be overridden by the deploy_proxy.yml )
What needs to be done. 
1) Allow using domains other than SITE_HOST which will require parameters to be passed as extra_vars.

Added playbook to automate letsencrypt certificate

---

environments/staging/postgresql.yml

I think the version was changed somehow to 9.4 in staging. 
I changed it to 9.6 in PR https://github.com/dimagi/commcare-cloud/pull/1376

Changed verison to 9.6

---

commcare-cloud/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

this makes ~ expand to /home/cchq/ rather than e.g. /home/droberts

for tmux sudo to cchq as a login shell

---

fab/fab/utils.py

`__last_tag` can be `None`, if a matching tag isn't found in the last 100.  This URL gets passed to a HQ management command, which splits this string back up:
https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqadmin/management/utils.py#L22
Brittleness of that aside, that probably *should* fail, so I opted to catch this edge case here.
@jmtroth0 @millerdev @biyeun

Don't fail if previous deploy isn't found

---

environments/icds-new/inventory.ini

Left over from https://github.com/dimagi/commcare-cloud/pull/1610 and https://github.com/dimagi/commcare-cloud/pull/1612.
Not sure if I did the right thing for `couchdb2_proxy`; I think you do need to specify that group, so I just arbitrarily picked the first `couchdb2` host.

remove refs to removed machines in icds inventory

---

fab/fab/utils.py

When the deploy fails during setup_release, it attempts to create the ref again resulting in this exception, which is fine.
```Executed: sudo -S -p 'sudo password:' -H  -u "cchq"  /bin/bash -l -c "cd /home/cchq/www/production/releases/2018-04-17_20.19 >/dev/null && /home/cchq/www/production/releases/2018-04-17_20.19/python_env/bin/python manage.py mail_admins --subject 'Deploy to production failed. Try resuming with fab production deploy:resume=yes.' 'Traceback:
File \"/home/jroth/.commcare-cloud/repo/fab/fab/fabfile.py\", line 505, in _deploy_without_asking
deploy_checkpoint(index, command.__name__, execute_with_timing, command)
File \"/home/jroth/.commcare-cloud/repo/fab/fab/fabfile.py\", line 471, in deploy_checkpoint
fn(*args, **kwargs)
File …
```

handling particular github exception

---

ansible/roles/commcarehq/templates/localsettings.py.j2

Tested on staging - no issues observed yet.  Including ```division``` and ```print_function``` is a little paranoid, but I'd rather air on the side of caution because ```modernize``` won't pass over this file.
@dimagi/py3

include from __future__ import * in localsettings

---

fab/fab/utils.py
requirements.txt

@nickpell @kaapstorm They just started using requests instead of httplib https://github.com/PyGithub/PyGithub/pull/664 which should fix the proxy issue

Revert 1544 je/proxy deploy

---

ansible/roles/commcarehq/templates/localsettings.py.j2
commcare-cloud/commcare_cloud/environment/schemas/postgresql.py
docs/env/postgresql_yml.md
environments/icds-new/postgresql.yml

Reverts dimagi/commcare-cloud#1624
@calellowitz @snopoke 
This breaks everything because you can't actually read app configs at this point https://github.com/dimagi/commcare-hq/blob/99d0cca8925caeaf6c30e88b9248ab4427dd63cd/corehq/sql_db/connections.py#L169
Error stack trace:
```
(python_env) cchq@web0:~/www/icds/releases/2018-04-20_17.45$ ./manage.py showmigrations
File "./manage.py", line 134, in <module>
execute_from_command_line(sys.argv)
File "/home/cchq/www/icds/releases/2018-04-19_07.29/python_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
utility.execute()
File "/home/cchq/www/icds/releases/2018-04-19_07.29/python_env/local/lib/python2.7/site-packages/django/core/management/__init__ …
```

Revert "standby reads for users and accounting"

---

ansible/roles/commcarehq/tasks/main.yml

For some reason when we upgrade python packages (like pip) it gets owned by root
fyi @NitigyaS

Chown virtualenv after upgrading python packages

---

ansible/roles/formplayer/vars/main.yml

@calellowitz This was concatenating the two main databases in the formplayer properties.
@dannyroberts not sure if you have a better idea of how to filer these sorts of configs
(going to go ahead and merge since ICDS localsettings are currently broken

Fix formplayer database definition

---

src/commcare_cloud/fab/operations/supervisor.py

https://github.com/dimagi/commcare-cloud/pull/1646/files#diff-ce4f14cae5d0b7b4c316c8c3ce4bbe5f
thought it would be innocuous, but it seems to be breaking

revert change that broke set_celery_supervisorconf in fab

---

fabfile.py

we've been running fab via commcare-cloud for a while now.
The recent reorganization for pip install broke the fab shim,
so this makes the fabfile just tell you what command you should be running

add deprecation message if you try to use fab directly

---

src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/helpers.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/commands/ansible/service.py

even when one of them is down. Previous behavior was to stop checking others
as soon as one of them was down (and thus returned a non-zero status).
Fixes #1634

make service status report all subservices

---

src/commcare_cloud/fab/const.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/release.py

This time with better testing... i.e. `cchq staging fab deploy` works, as well as just `cchq staging fab setup_<limited_>releases`. sorry @biyeun 
Apparently I didn't account for how the decorators worked with execute and just running setup_releases and setup_limited_releases wasn't the best test. The last commit (edit: f2dc175) is the one that changes things. The others are cleaning
tagging everyone who commented on #1651 --> @snopoke @dannyroberts @esoergel @emord 
buddy: @gcapalbo

Revert 1658 revert 1651 jr/single release

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/downtime.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/commands/ansible/service.py
src/commcare_cloud/commands/command_base.py
src/commcare_cloud/commands/fab.py
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
src/commcare_cloud/commands/migrations/couchdb.py
src/commcare_cloud/commands/shared_args.py
src/commcare_cloud/commands/validate_environment_settings.py
tests/test_command_docs.py

Pull out arguments so that they're defined statically on the command class as a list, rather than being added within `make_parser`. Any functionality from `make_parser` that was more complicated than that has been moved to the new `modify_parser` method, which only a few command classes have.
This lets me add a test that all arguments appear (somewhere) in the command docs. Not quite the dream of auto-generating docs that @czue mentioned on my last PR, but a small step in the right direction I think.
Opening for tests and review on general direction, will test more thoroughly that I didn't break any of the commands tomorrow.

Static arguments

---

src/commcare_cloud/environment/schemas/app_processes.py

I did a bit of testing it doesn't appear that the `CeleryOptions` class every wraps the raw dict. I played with it a bit but couldn't figure out how to get the wrapping to work (without manually wrapping each one).

add num_workers to celery config

---

README.md
control/init.sh

clean up from https://github.com/dimagi/commcare-cloud/pull/1626#discussion_r184796942
My best guess is that @pr33thi and I were making changes around the same time, and there was an interim period where she added this to get things to work, but I think it shouldn't be necessary on the latest version.

remove unnecessary ANSIBLE_ROLES_PATH env var

---

src/commcare_cloud/fab/operations/supervisor.py

Reverts dimagi/commcare-cloud#1652
Bringing this back now that CeleryOptions is _actually_ wrapping each `celery_processes[host][queue]`.

Revert "revert change that broke set_celery_supervisorconf in fab"

---

src/commcare_cloud/ansible/group_vars/all.yml

All datadog integrations (except those on postgresql machines) get skipped without this

add var to all.yml

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

I noticed the logging that i added in [1f3ef0dfc8](https://github.com/dimagi/commcare-hq/commit/1f3ef0dfc8833ada35cdb06263281dae6c6060b1) is not showing up in the file also created there. Looking at logfiles that are working, this pattern seemed like the successful one. 
Lemme know if there's something else that might be going on, since I don't know much about our logging scaffolding
@proteusvacuum

adding couch sql logfile to better place

---

environments/pna/app-processes.yml

@snopoke 
@dannyroberts is it intentional that inventory names do not work and only IPs do? Fine if thats the case, was just surprised this failed

using ip for server whitelist

---

environments/development/inventory.ini
environments/icds-new/inventory.ini
environments/softlayer/inventory.ini
environments/softlayer/public.yml
src/commcare_cloud/environment/main.py
src/commcare_cloud/fab/operations/supervisor.py
tests/test_environments.py

For environments like ICDS where host_string is an IP this will translate the IP address into the hostname as defined in the inventory file.
This makes it easier to know which host a process is running on when looking at the celery metric data:
`celery@10.247.164.40_reminder_case_update_queue_1`
becomes
`celery@celery0.internal-icds-new.commcarehq.org_reminder_case_update_queue_1`

use hostnames in celery worker names

---

environments/softlayer/inventory.ini
tests/test_environments.py

introduced in https://github.com/dimagi/commcare-cloud/pull/1712. Not sure why it only started failing on the second commit

fix test_hostnames for softlayer

---

environments/softlayer/inventory.ini

According to order or precedence, group vars in
inventory file get overridden by group vars in group_vars/all
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#id18

define var on hosts not groups

---

src/commcare_cloud/environment/main.py

Found this commit from an abandoned branch of mine that seems like a harmless check. Easy to remove later if we want to support external redis.

assert exactly one redis host

---

src/commcare_cloud/ansible/roles/datadog/templates/celery.yaml.j2

@snopoke 
I think this should be enough. It seems to be how the other templates do it and it looks like we pull this info into the check already https://github.com/dimagi/datadog-checks/blob/master/celery/celery.py#L76

adding env tag to celery check

---

src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

I think this is a relic from when we used to build formplayer on the formplayer machines. (Even then it didn't need to be installed on _all_ machines!)

remove gradle install

---

environments/icds-new/postgresql.yml

@dimagi/scale-team standbys should be able to handle more reads than the main DB and the main db has quite a bit higher load pretty consistently

Push more queries to ucr standby

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/utils.py

@gbova @esoergel sorry about the earlier error. 
The first commit adds a new method to find the latest commit. It defaults to using `last_tag`'s sha but otherwise it cd's into the current directory to find it there. I'm pretty sure this should never fail because we always assume that there's a current release (even on new servers ansible will create that symlink)
The second commit gives some more firm direction on what to do with the error. It tells you what branch you are deploying and how to rebuild the appropriate yaml files.
Let me know what you think and then I'll send a note to the dev team

More robust deploy last commit finder

---

.travis/environments/travis/public.yml
commcare-cloud-bootstrap/environment/public.yml
environments/development/public.yml
environments/icds-new/public.yml
environments/pna/public.yml
environments/softlayer/public.yml
environments/swiss/public.yml
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

can always override in public.yml, but no need to make every env specify
when it is this predictable

infer shared_drive_enabled from is_monolith

---

src/commcare_cloud/fab/utils.py

PNA deploys have been failing only on the very last step, `record_successful_release`, which has been confusing a lot of people. This PR moves the check for "name" back into `last_tag` so PNA deploys should go smoothly now.

Prevent check for 'name' when 'last_tag' DNE

---

src/commcare_cloud/ansible/roles/postgresql/handlers/main.yml
src/commcare_cloud/ansible/roles/postgresql/tasks/main.yml

Noticed that PG doesn't get started by `after-reboot`.
Was introduced here: https://github.com/dimagi/commcare-cloud/commit/cb131fcadbddceb282f01fb6e09acb7cf46033b0

start postgres after reboot

---

src/commcare_cloud/fab/utils.py

@esoergel I missed one and this broke today's `record_successful_release`. Hopefully this will fix it for Monday though

Prevent .name check on NULL last_tag

---

environments/icds-new/app-processes.yml
environments/softlayer/app-processes.yml
src/commcare_cloud/environment/schemas/app_processes.py

New celery queue for the aggregation script as these tasks only kick off SQL commands so they do almost nothing and these tasks will be in parallel several tasks at a time after https://github.com/dimagi/commcare-hq/pull/20633.
Keeping it as the same queue as the background queue on softlayer because it's very low use

Add new ICDS aggregation queue

---

src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2

Currently this is the UCR database on ICDS. not sure how intentional that was, but that's at least the current state.

Explicitly set formplayer database host

---

src/commcare_cloud/environment/schemas/postgresql.py
tests/postgresql_config/2018-04-04-development-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-enikshay-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-icds-new-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-l10k-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-pna-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-production-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-softlayer-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-staging-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-swiss-snapshot/.generated.yml
tests/test_postgresql_config.py

Aside from tests, the only change in functionality is that the generated `postgresql_dbs` variable comes sorted by db `name`. The other changes
- sort dbs in `tests/postgresql_config/*/.generated.yml` files to match this output and
- make the test work off the actual output rather than an internal/intermediate data structure
- simplify the test now that the variable comes pre-sorted
This is a prefactor to make changes to `postgresql_dbs` and updates to the test easier to eyeball for correctness

refactor generated postgresql_dbs test

---

src/commcare_cloud/ansible/letsencrypt_cert.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml

After making these changes I was able to run
```
commcare-cloud 64-test ansible-playbook letsencrypt_cert.yml --skip-check
commcare-cloud 64-test ansible-playbook deploy_proxy.yml --skip-check
```
to set up HTTPS on a test server. Even though there were a few things I had to update to make it work, @NitigyaS what you had done was a huge help and got me most of the way there, which was great!

fix letsencrypt_cert.yml

---

tests/test_jinja_templates.py

Example failure:
```
ERROR: tests.test_jinja_templates.test_jinja_templates
----------------------------------------------------------------------
File "/home/skelly/.virtualenvs/ansible/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/skelly/src/hqansible/tests/test_jinja_templates.py", line 16, in test_jinja_templates
jinja_env.parse(template.read(), filename=path)
File "/home/skelly/.virtualenvs/ansible/local/lib/python2.7/site-packages/jinja2/environment.py", line 493, in parse
self.handle_exception(exc_info, source_hint=source)
File "/home/skelly/.virtualenvs/ansible/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File …
```

test to validate jinja template syntax

---

environments/icds-new/app-processes.yml
environments/icds-new/inventory.ini

Reverts dimagi/commcare-cloud#1817
This is breaking the deploy due to what I believe is an upgrade to pip. These two servers have pip 10.0.1 installed and the other ones have 9.x. When running pip install you get hte following issues:
```
(python_env) cchq@web10:~/www/icds/releases/2018-06-04_17.47$ pip install --timeout 60 --quiet --requirement /home/cchq/www/icds/releases/2018-06-04_17.47/requirements/prod-requirements.txt --requirement /home/cchq/www/icds/releases/2018-06-04_17.47/requirements/requirements.txt --proxy 10.247.63.132:3128
flower 0.8.4 has requirement pytz==2015.7, but you'll have pytz 2017.2 which is incompatible.
django-two-factor-auth 1.6.2 has requirement qrcode<4.99,>=4.0.0, but you'll have qrcode 5.3 which is incompatible.
kombu 3.0.37 has requirement …
```

Revert "Revert "Added web10 and web11""

---

src/commcare_cloud/ansible/roles/http_proxy/tasks/main.yml

I discovered that on ICDS without the quotes the env vars
were getting cut off

quote env vars

---

src/commcare_cloud/ansible/letsencrypt_cert.yml

the backup file was getting interpreted as a duplicate site
by nginx

fix letsencrypt playbook error

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

This was breaking tests (or would if tests were running properly) and also breaking update-config for most environments.

fix ALLOWED_HOSTS hard failure

---

setup.py

until requests bumps its version requirement (https://github.com/requests/requests/issues/4681)
This fixes the error:
```
pkg_resources.ContextualVersionConflict: (idna 2.7 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('idna<2.7,>=2.5'), set(['requests']))
```

Pin idna to 2.6 temporarily

---

environments/swiss/app-processes.yml
src/commcare_cloud/environment/schemas/app_processes.py

the swiss server always has high memory usage, so figured we should combine these queues so kafka stops dying during deploy

combine swiss queues

---

src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/ecryptfs/tasks/main.yml
src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml

Rolling it will require to 
- stop services 
- deploy after-reboot (or just use it's tag)
- start services
results in 
`/$ mount`
`opt/data/tmp_storage on /tmp type none (rw,bind)`

mounting encrypted tmp_storage on /tmp

---

MANIFEST.in

I noticed that a wheel install wasn't giving us a .bash_completion

Add .bash_completion to manifest

---

commcare-cloud-bootstrap/environment/inventory.ini.j2
commcare-cloud-bootstrap/environment/public.yml

1. Add to the inventory.ini.2 template and entry that will add to inventory.ini:
```
[<host>:vars]
hostname='<host>'
```
for each host
2. Add an internal domain name so that this task does not get skipped here: https://github.com/dimagi/commcare-cloud/blob/master/src/commcare_cloud/ansible/roles/common/tasks/main.yml#L74
Reason: In order for kafka to start up, the hostname needs to be in `/etc/hosts`, and this was getting skipped because `internal_domain_name` was set to `null` here: https://github.com/dimagi/commcare-cloud/commit/d46527f156e4837c59ede9c7a47eba86b093c842

Update public.yml and inventory.ini.j2

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Some days I think about how YAML is way nicer than JSON to use, and then this kind of thing happens and I have no idea why anyone would want this.
Also @snopoke it looks like deploy_proxy wants to change the app cache's owner:
```
{
-    "owner": 33,
+    "owner": 1022,
"path": "/home/cchq/www/icds/app_downloads/cache"
}
```
I know you just worked on that. any ideas?
I hotfixed this on ICDS

on == True in yaml

---

.travis/spec.yml
commcare-cloud-bootstrap/specs/example_spec.yml

This is the same as this pr: https://github.com/dimagi/commcare-cloud/pull/1872, but I noticed that it had some reverts in the commit history that I don't want. This contains only the changes I wanted to make in 1 commit.
=======Description copy pasted from other ticket=======
This will make the django_manage group show up in the inventory.ini file, with the webworkers0 machine in the group when it is autogenerated during the fullstack deploy.
I also changed the couchdb proxy group to use the proxy machine, which already needs to have nginx running (so no longer 2 different machines running nginx). This might have made it easier to fix a bug @dannyroberts and I looked at earlier today.
Without this, we get an error when this ansible task is run: …

Add a django_manage group which contains the webworker

---

src/commcare_cloud/commands/ansible/ansible_playbook.py

This playbook really likes killing supervisor which can result in lots of zombie processes especially on celery servers. I think it's best to remove this for now until it can be tracked down. It's a bit harder because `--check` doesn't catch those restarts

Don't call supervisor ansible playbook

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

to get rid of "fake" localsettings changes
This also makes the output prettier (one line per group, rather than all on one line) but that's just a nice side effect.

Make ENVIRONMENT_HOSTS ordering consistent

---

src/commcare_cloud/fab/operations/supervisor.py
src/commcare_cloud/fab/services/templates/supervisor_formsplayer.conf

This should make it so that touchforms no longer runs anywhere.
All that's left is to remove all references to touchforms in the commcare cloud code and then remove the submodule from the hq code base. That's a bit more than I have capacity for right now but tracking that [here](https://trello.com/c/jGzPtKKR/120-remove-references-to-touchforms).
@wpride @snopoke

Stop running touchforms

---

src/commcare_cloud/ansible/roles/ecryptfs/tasks/main.yml

@jmtroth0 @NitigyaS 
The old grep matched the mount of the block storage device to `/opt/data`. This way properly matches only if ecryptfs is mounted to `encrypted_root`

fixing ecrypt grep

---

environments/swiss/app-processes.yml

Looks like we've been running an extra queue since february https://github.com/dimagi/commcare-cloud/commit/ef6c0eaa4bcbc9926013120e3d30c656dfb47614#diff-02338665690f88220a8d96f9c210ea2d
@dannyroberts fyi, not sure if we want to add something that checks running the same queue twice on one server

Remove duplicate repeat_record_queue from swiss

---

environments/staging/inventory.ini

Their presence as actual host meant they matched `all`
so e.g. updating users applied to them. Will uncomment
once VPN is more accessible and there is a better defined process
for deploying to old and new machines at once.

Comment out aws staging hosts

---

Makefile

long home directory paths (i.e. long usernames) otherwise cause
different text wrap behavior
Thanks @pr33thi for your long name!

Standardize help cache generation across environments

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/dbs.py
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/environment/main.py

G2 kept asking to verify which dbs on which machines should be copied, and I noticed we didn't really have a source of truth that showed the information in a decisive format. (`postgresql.yml` for instance doesn't show the actual names of the dbs, which are inferred; `.generated.yml` is an embarrassing place to ask someone to look, and kind of a mess to pull this out from.)

Add list-dbs command

---

environments/softlayer/app-processes.yml

Celery machine of softlayer is running full on memory.
Since there is not much activity on softlayer it should be fine to have less processes running since we wont need high number of tasks to be run in parallel.
i think its mainly the "number of workers" which is going to reduce the load by reducing the number of processes running.
Reduced concurrency at places to avoid memory spikes, just in case they are multiple tasks required of a worker.

Reduce workers and concurrency for softlayer celery

---

src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml

which on ubuntu 14.04 requires installing from pip
Curious what you all think about this. We've been on 3.0b forever, but it seems like with the occasional issues we have with supervisor not properly killing this, it'd be nice to rule out just being on an old version [May 2013](https://pypi.org/project/supervisor/3.0b2/).
The immediate ticket that prompted this was https://manage.dimagi.com/default.asp?276826. Not sure if we've seen that before (celerybeat process not getting killed on restart, resulting two celerybeat processes, resulting in duplicate period tasks), but it seems to be happening regularly now.

Use supervisor 3.3.4 instead of 3.0b

---

commcare-cloud-bootstrap/bootstrap.sh
commcare-cloud-bootstrap/environment/app-processes.yml.j2
src/commcare_cloud/fab/fabfile.py

1. Make an option to not run the `record_successful_release` task (which often errors during fullstack deploy and isn't actually necessary)
2. Remove non-required celery processes which seemed to be taking up too much memory.

Fix disconnects in fullstack deploy

---

environments/production/postgresql.yml
src/commcare_cloud/ansible/roles/postgresql/defaults/main.yml
src/commcare_cloud/ansible/roles/postgresql/templates/postgresql.conf.j2
src/commcare_cloud/environment/schemas/postgresql.py

Falls back to the current logic which is to allow if there is a netvault user defined
The change here (affecting only production) has already been deployed

Add allow_dump_from_pgstandby to switch on ability to pg_dump from standby

---

environments/echis/app-processes.yml

We typically use gevent pooling on these workers with a higher concurrency. It especially helps for the sms_queue worker which interfaces with the gateway and is largely io-bound.
@snopoke

Switch a few echis celery workers to gevent pooling

---

environments/icds-new/app-processes.yml

We pushed more reports to the background, without adding more queues. This makes celery5/6/7 have the same configuration as celery4
https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1532703411542&to_ts=1533308211542&tile_size=m&exp_metric=celery.tasks_queued&exp_scope=celery_queue%3Aicds_dashboard_reports_queue&exp_group=environment&exp_agg=sum&exp_row_type=metric

Add more ICDS reporting queues

---

Makefile

Same change I made on commcare-hq (https://github.com/dimagi/commcare-hq/pull/21341)

Split out `make requirements` vs. `make upgrade-requirements`

---

src/commcare_cloud/commands/ansible/run_module.py

it no longer appears to be the case that the ansible can run cchq commands without a password
so changing logic that assumes that. (Thanks, comment!)

Fix run-shell-command with --become-user cchq

---

src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

We have a lot of warnings about buffering to disk on prod. This is what we use for riak. we use 512k for icds & PNA.

Increase client_body_buffer_size to 128k for prod

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/utils.py

We've been generating a lot of extra tags because this ends up adding a tag even if you're trying to resume a failed deploy

Don't implicitly tag setup release

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2

@dimagi/devops Looking for some feedback
> $request_length - request length (including request line, header, and request body)
https://nginx.org/en/docs/http/ngx_http_log_module.html
This could be useful for current interrupt ticket to see how large of a request a mobile worker is trying to send. It seems like it could be useful in the future, but not sure if we have a preferred way to add these, or a reason to not add it.

Add request length to nginx logs

---

src/commcare_cloud/fab/const.py

as new code directories were deployed airflow was not being restarted so it pointed to old releases. this should fix that
@snopoke @emord @nickpell

restart airflow on service restart

---

environments/icds-new/app-processes.yml

@calellowitz fyi. trying this out today. this task has been taking longer ever since we deployed those UCR db changes (I think it has to do with the reduction in work_mem), but I think this should also be safe to do

Increase number of icds agg queues.

---

src/commcare_cloud/ansible/roles/couchdb/defaults/main.yml

Add this to the list of things shouldn't be done in a production instance. Will send out a more full retro for why I did it.
@dimagi/devops This is necessary because the package for 1.6.1 is no longer around.

Upgrade to couchdb 1.7.2

---

src/commcare_cloud/ansible/roles/supervisor/templates/supervisord.conf.j2

Should help swiss disks which have 14.7GB of logs. Also don't think we use these much.

drop supervisor logs kept to 5

---

commcare-cloud-bootstrap/bootstrap.sh

Before, the service check would return this for the postgres check, because no superuser existed in the new env:
```
FAILURE (Took   0.02s) postgres       : default:commcarehq:OK ucr:commcarehq_ucr:OK No users found in postgres
```

Add a superuser so the postgres service check passes

---

environments/icds-new/public.yml

For AKS audit,
enable password obfuscation on NIC.
Functionality enabled: https://github.com/dimagi/commcare-hq/pull/15490
fyi @snopoke

enable password obfuscation on NIC

---

environments/softlayer/public.yml

Enabling password obfuscation on india server as well since ICDS master app is on softlayer for which [we have enabled obfuscation](https://github.com/dimagi/commcare-cloud/pull/2051) and is blocking using of app on india server.

enable password obfuscation on softlayer

---

src/commcare_cloud/commands/ansible/service.py

- Env name gets added to the log locations
- Replaced `{}` with `<>` so that `.format()` doesn't get confused
In reference to this: https://github.com/dimagi/commcare-cloud/pull/2033#issuecomment-414816646

Add env name to logs

---

environments/icds-cas/app-processes.yml

Being fairly conservative here. We should still have plenty of RAM and CPU after this. main changes are form partitions 16 -> 24 and case partitions 36 -> 60. 
Going to start a doc about how I think scaling to 250k works with some current code changes that are being worked on.

icds-cas pillow & celery configurations

---

docs/_config.yml

This was particularly for the 'commands' page which has a very long TOC

limit toc levels to 4

---

.travis/environments/travis/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

This should make the pillow config diffs we deploy for ICDS less flexible, but much more readable

Rewrite local_pillows config

---

tests/test_autogen_docs.sh

currently if running `make` fails, it will only fail later incidentally
because the previous `make clean` created a diff. Now any failing command in this script
will bubble up directly

Make test_autogen.docs.sh fail loudly if any part of it fails

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Currently we are migrating from 'icds-cas-english' to 'icds-cas-app' on transifex.
So removing it from here for now to avoid any updates to it during migration.

temporarily remove project

---

environments/icds-cas/app-processes.yml

The reminder_queue workers are still commented out, so no scheduled alerts will be processed. But by enabling the sms_queue workers it lets us test the sms connectivity through the compose interface.

Start running sms workers again

---

environments/icds-cas/postgresql.yml

So `AsyncIndicator` reads from standby nodes

userreports listen to standby

---

src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml

potentially fixes bug that caused supervisor executable path to be
missing from the conf, which made it impossible to start supervisord
(using upstart at least) until upgrade-users had been run a second time

Simplify supervisord installation

---

src/commcare_cloud/ansible/deploy_db.yml

Ran this on production, but nowhere else.
@dannyroberts

Add encrypted dir to django_manage VM

---

environments/production/app-processes.yml

this might be a bit overboard in terms of numbers, but it seemed like hqpillowtop{2,3} had plenty of space to spare and I was curious to see how this would affect the (for now daily) [hills](https://app.datadoghq.com/dash/256236/change-feeds-pillows?live=true&page=0&is_auto=false&from_ts=1536090657826&to_ts=1536695457826&tile_size=m) kafka-ucr-static is crawling up
https://manage.dimagi.com/default.asp?282671#edit_1_282671
@emord @czue

adding more ucr static processors to see what happens

---

environments/pna/public.yml

Since the `pna.sn` and `commcare.pna.sn` are two different IP and `pna.sn` has not SPF records
sending mail from `pna.sn` will cause the mail to marked as spoofed mails. 
Should resolve the mail being delivered to spam.

Changed domain to correct domain name to avoid being spammed.

---

src/commcare_cloud/ansible/roles/couchdb2/defaults/main.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2/templates/extras.ini.j2

Seems like the default isn't big enough: 
http://docs.couchdb.org/en/stable/config/auth.html#couch_httpd_auth/auth_cache_size

add extra config with auth_cache_size

---

src/commcare_cloud/commands/fab.py

This allows calling two fab commands in a row.
https://docs.python.org/2/library/os.html
execvp:
> These functions all execute a new program, replacing the current process; they do not return
spawnvp waits until it returns
@dannyroberts any reason that we were using execvp originally? I haven't tested this out with other commands, but this is what I would have expected behavior to be. 
Also note that the python docs suggest using `subprocess` here. I tried that for a second, but got an error about not being able to find `fab`. I didn't look deeply into it, but that would probably be even better

Use spawnvp instead of execvp

---

environments/production/app-processes.yml

Looking for this to conclude all pillows changes during firefighting last week.
Before this was in [this](https://github.com/dimagi/commcare-cloud/blob/8aa90c026ad181fa51e5931043c4760fe9701b79/environments/production/app-processes.yml) state
So now effectively to address increase in [number of form submissions](https://app.datadoghq.com/dash/256236/change-feeds-pillows?live=true&page=0&is_auto=false&from_ts=1537781826772&to_ts=1537785426772&tile_size=m&fullscreen=211359693) , we have
1. Double `CaseToElasticsearchPillow`, from 2 -> 4
2. Double `ReportCaseToElasticsearchPillow`, from 1 -> 2
3. Double `XFormToElasticsearchPillow`, from 1 -> 2 and move it to pillow3 from pillow0
4. Double `FormSubmissionMetadataTrackerPillow` from 1 -> 2 and move it to pillow3 from pillow0. This should be …

Mk pillows conclude

---

environments/production/app-processes.yml

follow up from https://github.com/dimagi/commcare-cloud/pull/2177
Looks like increasing concurrency on the same server didn't go well. The queue restarted multiple times and then stopped accepting tasks as well.
So moving this to a different server instead and adding two more processes since the tasks get long running and tend to block new exports.

move and increase export_download_queue

---

environments/production/inventory.ini

Django5 was unresponsive and had to be hard rebooted twice in last few hours
Reached out to rackspace for help [here](https://portal.rackspace.com/tickets/details/180926-ord-0000189)
Removing django5 off the webworkers. This can be reverted once the above is resolved.

remove django5 temporarily

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/kafka/defaults/main.yml
src/commcare_cloud/ansible/roles/kafka/templates/server.properties.j2

@dimagi/scale-team we're still super far behind on forms from the really slow object storage. Increasing this to 60 days for now so that we don't run into a situation where we don't have the changes in kafka

Set icds log retention for 60 days

---

docs/commcare-cloud/commands/index.md
environments/staging-aws-test/inventory.ini.j2
environments/staging-aws-test/make-inventory.sh
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/environment/paths.py
src/commcare_cloud/terraform/modules/commcarehq/main.tf

Very rudimentary pattern here to allow templating an inventory and filling in IP addresses from what's on AWS. Helpful to be able to use the machine's name and have it fill in the address, and for when you need to rebuild a machine and have it change the IP for you.

Add command to fill inventory from AWS

---

commcare-cloud-bootstrap/bootstrap.sh

Otherwise check services has this line: `FAILURE (Took   0.01s) postgres       : default:commcarehq:OK ucr:commcarehq_ucr:OK No users found in postgres`
@dannyroberts 
code buddy @jmtroth0

Check_services should come after the postgres user was created

---

src/commcare_cloud/terraform/README.md

Make this change to match what currently exists in the terraform yml files, ie: https://github.com/dimagi/commcare-cloud/blob/master/environments/production/terraform.yml
@dannyroberts 
code buddy @jmtroth0

Replace 'aws_profile' with 'account_alias' in the readme

---

src/commcare_cloud/ansible/echo_vault_password.sh
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/run_module.py

This makes run-module and ansible-playbook commands use cleaner shell calls that allow those commands to act interactively. This allows us for example to put prompts in ansible playbooks. It's also just a more straightforward subprocess call.
We previously "had" to pass in the vault password via stdin because I couldn't think of a way to pass it in as an environment variable. This uses the same idea of passing in an executable to `--ansible-password-file`, but not the executable prints out the value of `ANSIBLE_VAULT_PASSWORD` rather than the output of stdin (which is what we were using `/bin/cat` to do).

Use cleaner ansible calls

---

environments/production/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/terraform/modules/commcarehq/variables.tf
src/commcare_cloud/terraform/modules/servers/main.tf

and always use cpu_credits = "unlimited"
This lets us elastically pay for more CPU usage when it's needed with no cap. If things are well calibrated this shouldn't cost very much but will save us from bursty performance issues; and if it's expensive one month we can upgrade the machine type for more provisioned CPU. (The change to t3 is just upgrading to the new generation which is both better and cheaper.)

Use cheaper and better AWS t3 instance class

---

.travis.yml
.travis/tests.sh

I think this nice built-in `timeout` should do what we were discussing earlier, about killing provable deploy after 45 minutes without failing the build, but still failing if it exits earlier with a non-zero status code.

[pv-deploy] Call provable deploy running for 45 minutes a success

---

src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

This is just a minor nuisance I stumbled upon. It's nice to be able to run e.g.
```
PROXY_IP=$(cchq ${ENV} lookup proxy:0)
```
or something like that to use it programmatically in a script, but you can't do that if lookup prints to stderr.

Print `cchq <env> lookup <group>` output to stdout, not stderr

---

src/commcare_cloud/ansible/host_group_aliases.yml

Another small thing I noticed that was annoying me. I recently added these tasks to dynamically create the `all_commcarehq` and `commcarehq` host groups so that playbooks can reference these and avoid copy-and-paste, but these in-memory tasks were always showing up as "changed". This will make them show up as "ok" instead.

Make host_group_aliases.yml result in ok, not changed

---

.travis/tests.sh

see https://travis-ci.org/dimagi/commcare-cloud/jobs/439120219
> You are not currently on the branch specified with the --branch tag. To deploy on this branch, use --branch=7809a83, otherwise, change branches
(Also responsible for today's cron build failure: https://travis-ci.org/dimagi/commcare-cloud/jobs/439623872)

Fix --branch issue on travis cron build

---

environments/icds-cas/public.yml

sumologic toggle is set to 0 so having this here just incurs another cache hit for nothing
can re-enable if we want to

remove sumologic url on icds

---

src/commcare_cloud/commands/ansible/service.py

@pr33thi there were a number of problems with the implementation as it was:
- A restart would stop _all_ the nodes, and then start _all_ the nodes, in that order, causing lots of downtime, instead of stopping and starting each node in sequence, which wouldn't cause downtime
- it didn't respect `--limit` (but didn't complain either) making it so there's no way to restart only a subset of nodes
- (minor) it was a bit chatty and asked for too many `y`s to keep going at different points

Fix rolling restart

---

src/commcare_cloud/commcare_cloud.py

Found this while working on https://github.com/dimagi/commcare-cloud/pull/2263. Nothing uses now, so better to remove than to keep around and confuse future me again.

Remove deprecated args.environment alias for args.env_name

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/alias.py
src/commcare_cloud/cli_utils.py
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commcare_cloud.py

`commcare_cloud('staging', 'fab', 'deploy')` is equivalent to `suprocess.call(['commcare-cloud', 'staging', 'fab', 'deploy'])`, except that it doesn't require forking a new process (which is in the case of python, _very_ expensive in terms of time).
Will test further but I think the general concept works.
I converted one usage just as an example, but if we like the pattern, I'll convert others as well. There's also some cleanup I can do with the way  `print_command` gets called in other places.

Add easy way to call other commcare-cloud commands

---

src/commcare_cloud/ansible/deploy_proxy.yml

a `tags` on `include_roles` just tags the _include_role_ task,
not any of the included tasks. To tag all of the included tasks (recursively),
you have to _also_ tag it in the `name` arg. (_Only_ tagging it here does not
work either; you have to tag it in both places.)

Give nginx_sites tag its intended purpose back

---

environments/softlayer/app-processes.yml

ICDS aggregation tasks are causing a celery backup on softlayer:
https://app.datadoghq.com/dash/141098/celery-overview?live=true&page=0&is_auto=false&from_ts=1539208017772&to_ts=1539294417772&tile_size=m&fullscreen=false&tpl_var_environment=softlayer

create separate process for icds_aggregation_queue on softlayer

---

environments/production/app-processes.yml

The AWS ones are currently running at 2 even because of the default CPU calculation. They're on t3.large machines which have "burstable" CPU, but present to the OS as having two CPUs. I'm honestly not sure what that translates to, but I think it's worth upping it to 8 workers and seeing the effect.

Hardcode 8 gunicorn workers for production

---

src/commcare_cloud/ansible/requirements.yml

prove-deploy failures seem to be related to couch, so I wanted to run this with part of https://github.com/dimagi/commcare-cloud/pull/2215 rolled back to see if it's related.

[pv-deploy] Add andrewrothstein.couchdb back to galaxy requirements

---

.travis/tests.sh
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/www_log_dir.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml

this issue appears in prove-deploy test: https://api.travis-ci.org/v3/job/442292654/log.txt
I think this full stack deploy bug was introduced in this PR https://github.com/dimagi/commcare-cloud/pull/2209, and I think this fixes it without breaking the positive use case. Running a prove-deploy build to confirm the former.
I'm pretty sure that `public.yml` will win if it's defined there (https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) and that the other interpolations in this file that use `couchdb_use_haproxy` will use the overridden value from `public.yml` and not the default value just because it's defined in the same file, but would appreciate someone if you could double check my logic @snopoke so I don't by …

[pv-deploy] Fix couchdb_use_haproxy undefined

---

environments/icds-cas/public.yml
environments/icds-new/public.yml
environments/staging-aws-test/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

This comes up every time we're switching proxies, since you'll want to test on the public IP before flipping the DNS

Include proxy.public_ip in ALLOWED_HOSTS

---

src/commcare_cloud/ansible/host_group_aliases.yml

Reverts dimagi/commcare-cloud#2288
Turns out this has the side effect of leaving the group with different membership when you use --limit, and in particular the group not existing at all if none of the --limit hosts are members. Since you seemed lukewarm about the change anyway, I'll suggest just reverting.

Revert "attempt to speed up"

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
src/commcare_cloud/ansible/roles/datadog/defaults/main.yml
src/commcare_cloud/ansible/roles/nginx/templates/site.j2
src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

Okay, this is deployed now. Settled on splitting it 50/50, because even though `receiver/` gets less than a third of requests, it's responsible for more than half of the requests that take longer than 2 minutes. So I figured giving allotting half the webworkers for just submissions seemed like a reasonable place to start.

Send submissions to a separate group of webworkers

---

environments/production/app-processes.yml
environments/production/terraform.yml

doubling to 32GB RAM and 8 vCPU
(I chose m5.2xlarge for the time being because there's a shortage of the similar-but-cheaper t3.2xlarge in us-east-1a.)
Already deployed, around 9:45-10AM ET

 Move all production webworkers to m5.2xlarge

---

.travis/environments/travis/app-processes.yml
commcare-cloud-bootstrap/environment/app-processes.yml.j2
environments/64-test/app-processes.yml
environments/development/app-processes.yml
environments/enikshay-reference/app-processes.yml
environments/pna/app-processes.yml
environments/swiss/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
src/commcare_cloud/environment/schemas/app_processes.py

I'll describe how I found this error which I think will explain what the error is.
[This task](https://github.com/dimagi/commcare-cloud/blob/master/src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml#L39) kept getting skipped on this `when` clause
So I added in this debug statement right before that task: `- debug: msg="{{ app_processes_config.celery_processes.get(inventory_hostname) }}"`, and the output was:
```
ok: [10.0.0.23] => {
"msg": {
"background_queue,case_rule_queue,celery,analytics_queue": {
"concurrency": 1,
"max_tasks_per_child": 50,
"num_workers": 1,
"optimize": false,
"pooling": "prefork"
},
"beat": {
"concurrency": 1,
"max_tasks_per_child": 50,
"num_workers": 1,
"optimize": false,
"pooling": "prefork"
},
"email_queue,reminder_case_update_queue": {
"concurrency": …
```

Update the list of queues that cannot share a process

---

environments/staging/app-processes.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2

I followed the steps I outlined [here](https://confluence.dimagi.com/pages/editpage.action?pageId=45615094) to migrate the pillow machines to AWS. Staging is currently working, and `cchq staging service pillowtop` gives me this, which makes me think the migration worked:
```
10.201.10.41 | SUCCESS | rc=0 >>
commcare-hq-staging-pillowtop-CaseToElasticsearchPillow-0             RUNNING   pid 9561, uptime 1:33:53
commcare-hq-staging-pillowtop-GroupToUserPillow-0                     RUNNING   pid 9747, uptime 1:33:42
commcare-hq-staging-pillowtop-CaseSearchToElasticsearchPillow-0       RUNNING   pid 9933, uptime 1:33:31
commcare-hq-staging-pillowtop-LedgerToElasticsearchPillow-0           RUNNING   pid 10119, uptime 1:33:20
commcare-hq-staging-pillowtop-ReportCaseToElasticsearchPillow-0 …
```

Get rid of references to the rackspace pillow machine now that the AWS pillow machine is up

---

src/commcare_cloud/ansible/group_vars/redis.yml

This will make redis kill client connections that are idle for 5 mins. This will prevent the buildup of redis connections we've been seeing (though won't fix the root cause).

set redis client timeout to 5 mins

---

environments/staging/app-processes.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

Builds off of [this PR](https://github.com/dimagi/commcare-cloud/pull/2326) (so this one can be merged and that one can be closed: closes #2328). Migrated staging celery from rackspace to AWS
@dannyroberts 

Staging- Migrate celery from rackspace to AWS

---

environments/production/public.yml

This reverts commit 6f0dbcf00088ca81dfea2ef478d320d80b412589.
Realized I merged in https://github.com/dimagi/commcare-cloud/pull/2330 with this, but that we're not quite ready for this yet. Will add back when we are.

Revert "Use local aws couchdb2 for production users and domains dbs"

---

environments/production/app-processes.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2

This PR follows up on #2332.
This has all been deployed: all new tasks are going to the new RabbitMQ (rabbit0) and picked up by the new celery workers (celery[0-4]). The old ones are still up to go through the backlog, and I'm leaving up a bit in case some process continued sending there before it died. I'll check and remove the old rabbit & celery machines tomorrow.

Migrate production celery and rabbitmq

---

environments/softlayer/app-processes.yml

This is needed after adding more parallel tasks for child health monthly @calellowitz

Update concurrency for softlayer icds aggregation queue

---

environments/production/app-processes.yml
src/commcare_cloud/environment/schemas/app_processes.py

Flower is still up to monitor things. Otherwise, these changes are fully deployed. (I also manually deleted things in the service directory, because of this issue: https://github.com/dimagi/commcare-cloud/issues/2335

Remove all queues from old celery

---

environments/production/public.yml

This reverts commit dd9e5e0dd4b94c5b4c631f058f12ddfd5a55dc64, which was itself a revert.
This is already deployed

Use local aws couchdb2 for production users and domains dbs

---

environments/staging/terraform.yml

Reason: the deploy was timing out because the pillowtop processes were using up basically all the ram on the 8GB machine, so this increase it to 16GB.
@dannyroberts 

Increase size of pillow0 machine

---

environments/staging/inventory.ini

This is part of changing the celery machine from db-private to app-private. Going to go ahead and merge this in.
@dannyroberts

Update the celery ip address

---

environments/production/app-processes.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2

We've been on the new setup for a day+ now, and the old queues have been stopped for a while.

Remove old celery and rabbit from prod inventory

---

environments/softlayer/app-processes.yml

[Source ticket](https://manage.dimagi.com/default.asp?285065)
Celery machine on softlayer has no memory to even do a location upload,
so this is to reduce the memory usage till we move it to AWS
My understanding is that activity on softlayer is minimal hence combining the queues and reducing the concurrency should be the right to do anyway
best review commit by commit

Mk minimize softlayer

---

environments/production/public.yml

This PR is continuing to follow the same pattern as https://github.com/dimagi/commcare-cloud/pull/2340 and https://github.com/dimagi/commcare-cloud/pull/2350

Switch to using local couchdb2 for production auditcare and fixutres dbs

---

environments/production/app-processes.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2

This has already been deployed. All pillows now on pillow0, none on the old ones.

Move production pillows to new aws machine

---

environments/production/public.yml

This PR is continuing to follow the same pattern as #2364, #2340, and #2350.

Move meta and receiverwrapper dbs over to new couchdb2 on production

---

environments/production/app-processes.yml

Saved exports is often stuck and needs a kick. Trying to avoid that by breaking it down into multiple workers instead, to avoid high concurrency by a single worker but keeping the overall number of concurrent tasks same.
This also helps avoiding complete stop on processing in case the queue is stuck.

break down saved exports

---

src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

Previously only submissions go to the `[mobile_webworkers]`, now restores (and the other more minor endpoints under /phone/) go there too

Send restores to "mobile_webworkers"

---

src/commcare_cloud/terraform/modules/network/main.tf

on all ports
This allows webworkers to make requests to the riak proxy.

Make public subnet accessible from other machines on the network

---

src/commcare_cloud/commands/terraform/migrations/0002_name_servers.py

had hardcoded something about production in there by mistake
Shouldn't really affect much since it's already rolled out to the only two environments that use terraform, but figured it couldn't hurt to commit the fix.

Fix terraform state migration 0002 for staging

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

We had purposely allocated too many resources to this earlier, and now we're "rightsizing".
Already deployed.

Remove web[3-5]-production hq_webworkers

---

requirements.txt
setup.py

Was getting deploy errors on prod because of merged with long PR names that were truncated and ended with `...`
Unsure if this fixes it, but we were on a prerelease before so seemed worth it to upgrade.
@emord 
code buddy @esoergel

Upgrade PyGithub to 1.43.3

---

environments/icds-cas/app-processes.yml
environments/icds-cas/inventory/commcare.csv

@calellowitz and I were deploying today and saw that celery2 had a corrupt git folder. in the deploy output it looked like:
```
[100.71.188.6] out: error: file ./objects/pack/pack-8c3f380a0e1e8af4ebdf638ece722adc4b14e2a2.pack is not a GIT packfile
[100.71.188.6] out: error: file ./objects/pack/pack-8c3f380a0e1e8af4ebdf638ece722adc4b14e2a2.pack is not a GIT packfile
[100.71.188.6] out: error: refs/remotes/origin/jls/ko-export-merge-conflicts does not point to a valid object!
```
I tried doing some `git fsck` and other things from stack overflow, but I believe we'll need to re-clone the repository.
I also tried running `clean_releases`, but received an error and then saw (files marked as directories):
```
```(icds) cchq@celery2:~/www/icds/releases$ ls -lh …

Remove celery2 from rotation

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/commands/terraform/terraform_migrate_state.py
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/iam/EnforceMFAPolicy.json
src/commcare_cloud/terraform/modules/iam/main.tf

While writing documentation on our AWS processes, I didn't feel great about the AWS default of storing access keys in plaintext at ~/.aws/credentials indefinitely, and I had a backlog item to force two-factor auth for all our IAM users.
Once I got started looking into it, a solution came together that satisfies both. This PR has the following changes:
- Forces 2FA for all our IAM users, including for CLI use
- Supports entering 2FA token via command line and storing the resulting session credentials
- They're still stored in ~/.aws/credentials, but now the permanent ones are pretty weak by themselves, and the strong ones are short-lived (30 minutes by default in this PR)
While a theoretical malicious program will still be able to find your strong auth, this change at least limits the …

AWS enforce Multi Factor Auth

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

FYI @jmtroth0 the new django_manage machine's on AWS. Let me know if there's anything you want me to do in terms of log files on the old one

Remove hqdjangomanage0 (rackspace)

---

environments/icds-cas/inventory/postgresql.csv

Decreased it based on the suggestion from PgTune, and postgresqltuner.pl and this PR here
https://github.com/dimagi/commcare-cloud/pull/1707
```
-----  Memory usage  -----
[INFO]    configured work_mem: 32.00 MB
[INFO]    Using an average ratio of work_mem buffers by connection of 150% (use --wmp to change it)
[INFO]    total work_mem (per connection): 48.00 MB
[INFO]    shared_buffers: 12.00 GB
[INFO]    Track activity reserved size : 1.58 MB
[INFO]    maintenance_work_mem=2.00 GB
[INFO]    Max memory usage :
shared_buffers (12.00 GB)
+ max_connections * work_mem * average_work_mem_buffers_per_connection (800 * 32.00 MB * 150 / 100 = 37.50 GB)
+ autovacuum_max_workers * maintenance_work_mem (3 * 2.00 GB = 6.00 GB)
+ track activity size (1.58 MB)
= 55.50 GB
```
`[BAD]     Max possible …

reduced worker_memory for UCR

---

environments/_users/dimagi-support.yml
environments/production/meta.yml

Added ksampat with empty ssh key, which has the effect of giving him access to the productoin AWS VPN without ssh access to the machines.

Add ksampat to users for the purpose of VPN

---

environments/staging/postgresql.yml

since we keep maxing out connections and getting sentry errors

Raise staging pgbouncer_max_connections

---

.travis/environments/travis/app-processes.yml
commcare-cloud-bootstrap/environment/app-processes.yml.j2
environments/64-test/app-processes.yml
environments/development/app-processes.yml
environments/echis/app-processes.yml
environments/enikshay-reference/app-processes.yml
environments/icds-cas/app-processes.yml
environments/icds-new/app-processes.yml
environments/pna/app-processes.yml
environments/production/app-processes.yml
environments/softlayer/app-processes.yml
environments/staging-aws-test/app-processes.yml
environments/staging/app-processes.yml
environments/swiss/app-processes.yml
src/commcare_cloud/environment/schemas/app_processes.py

Case imports are currently in the catchall queue.  As I understand it, this PR won't actually change anything, but it'll allow us to track the queues separately and split this off elsewhere if it looks necessary.
In conjunction with https://github.com/dimagi/commcare-hq/pull/22246
Full disclosure, I have a fairly rudimentary understanding of the implications of this change - it's largely mirrored off of https://github.com/dimagi/commcare-cloud/pull/1500

Split case imports queue off of 'celery'

---

environments/production/terraform.yml

Upgrade to r5a.4xlarge
It kept occasionally maxing out on memory and killing helper processes (datadog, sshd, etc.), about once or twice a week. Was $368/mo, now is $660/mo (not including disk which is $15/mo in both cases)

Increase pillow0-production RAM to 128G

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

* setting is not respected by celery < v4.2
* https://github.com/celery/celery/pull/4292
* 'gevent' gunicorn worker class can 'leak' connections
* https://github.com/benoitc/gunicorn/issues/996#issuecomment-93301359
After having this deployed for ~ 1 day I'm not seeing any improvement in performance and the large increase in open connections could cause issues on db hosts (e.g. max file descriptors). Given that and issues described above I think safest to revert.
reverts setting change from https://github.com/dimagi/commcare-cloud/pull/2396

remove CONN_MAX_AGE

---

src/commcare_cloud/commands/terraform/templates/variables.tf.j2
src/commcare_cloud/terraform/modules/server/main.tf

I've noticed that our EC2 instances print
```
*** System restart required ***
```
on login, on day one. I'm guessing that's because it immediately finds something to autoupdate, because we're not starting on the latest AMI for Ubuntu 14.04. This PR updates to the appropriate AMI currently listed on https://cloud-images.ubuntu.com/locator/ec2/ (Search for "us-east 14.04 amd64 hvm:ebs").

Update Ubuntu AMI

---

src/commcare_cloud/ansible/roles/nginx/vars/couchdb2.yml

I finally found what was blocking the cloudant to couchdb2 migration, and it was that couchdb2_proxy was blocking requests larger than 10MB, and not all but a good few _bulk_docs requests that happen during replication have been going over 10MB, getting an response from nginx, and failing to parse it as JSON, killing the replication process.
Setting the limit to something absurdly high like this fixes the problem, but we probably don't want to set the limit that high.
Pinging Simon and Emord in case you have insight into why these original numbers were chosen.
Update: the easiest way to deploy this change is
```
deploy-stack --tags=proxy --limit=couchdb2_proxy
```

Temp: make client_max_body_size on couchdb2_proxy ridiculously high

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2

This would previously fail (harmlessly) every time you run terraform because aws rejects the empty public key

Fix terraform for user with empty public key file

---

src/commcare_cloud/commands/terraform/migrations/0003_make_proxy_server_like_others.py
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/terraform_migrate_state.py
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/server/main.tf
src/commcare_cloud/terraform/modules/server/variables.tf

There's a hard limitation on Linux AMIs that the boot volume can't be larger than 2TB. Mostly we don't notice that but for CouchDB, we want volumes larger than 2TB. The right way to do this is to have small boot volumes (for the OS, etc) and a secondary volume—which has no size limitation—that we mount at /opt/data. That would be done like this:
```
servers:
- server_name: "couch0-production"
server_instance_type: m5.4xlarge
network_tier: "db-private"
az: "a"
volume_size: 40
block_device:
volume_size: 4000
```
This PR doesn't change any resources (though it does change the terraform resource address of the proxy machine as part of a refactor, but with no change to the actual AWS ec2 instance). In order to continue using terraform, you have to first run `cchq <env> …

Support defining secondary volumes in terraform

---

environments/icds-cas/app-processes.yml

https://sentry.io/dimagi/commcarehq/issues/707483906/events/37838715586/
This was introduced by me 16 days ago https://github.com/dimagi/commcare-cloud/pull/2368
Two servers were processing the same changes at around the same time so there were a large number of duplicate key errors even though we delete and then insert.
For the future this needs to be fixed one of two ways:
A) some more automatic configuration. This should be much easier now than when I first implented this since we have some configuration management with commcare-cloud, but still a bit tricky to handle since partitioning logic is split between commcare-hq and commcare-cloud
B) Upgrade to kafka > 0.9 and allow kafka to handle partition assignment and offsets for us. I think this is probably the better use of time …

Fix pillow process number

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

I have removed web0 from the rotation for staging so that it can reindex the couch databases on the new aws couch machine. It needs to be commented out for staging deploys to still work. This is a temp fix, and will be reverted after the aws couch migration is complete.
@dannyroberts
fyi @gbova  

Temporarily comment out web0 from the staging inventory

---

src/commcare_cloud/ansible/roles/airflow/tasks/main.yml

@pr33thi @snopoke @sravfeyn @NitigyaS 
Airflow rotates logs (one per day for the scheduler, one per dag run for the task logs), but does not purge old ones by default. This has caused disk space issues a couple times in the past. This command should resolve that

purge airflow logs

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

I've added a 5TB non-boot volume to each of the production couch machines. (They're already added.)
`couch1-production` already has its data migrated to this new volume, and that volume is properly mounted at `/opt/data/`.
As of now (2018-11-28 @ 10:30pm ET) `couch0-production` and `couch2-production` are in the process of copying their `/opt/data` to the new volume. This is being done in a tmux under the ansible user as an rsync in a loop. Both nodes are still operational, it's just copying the data in the background. Tomorrow morning when I wake up, I'm going to (one node at a time) shut off couch, do a final rsync, reboot the machine to make sure the drives are in their natural unmounted state, move the old /opt/data out of the way (e.g. to /opt/data-backup), and then mount the new …

Add 5TB disk to couch*-production

---

environments/staging/terraform.yml

Context is that an effort to increase couch disk sizes was underway and
then interrupted. Will be resumed later, but this commit updates to
what's currently there.

Get staging terraform.yml up to date with reality

---

src/commcare_cloud/ansible/roles/datadog/vars/main.yml

@snopoke @millerdev buddy: @kaapstorm 
figured it could be nice to have the couch logs from the migration given I might be abusing it a bit

include django manage couch logs

---

src/commcare_cloud/commands/terraform/migrations/0004_name_rds_instances.py
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.tfvars.j2
src/commcare_cloud/commands/terraform/templates/variables.tf.j2
src/commcare_cloud/environment/schemas/terraform.py

includes a rename with a corresponding terraform state migration
This is a prefactor for the change I want to make to be able to use terraform to set RDS parameters like `max_connections`. This removes a couple layers of indirection as well as some misleading unused variables.

Simplify terraform RDS

---

src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/terraform/modules/postgresql/main.tf
src/commcare_cloud/terraform/modules/postgresql/variables.tf

Builds off of https://github.com/dimagi/commcare-cloud/pull/2465.
The only param currently managed (after this change) is `max_connections`—everything else is ignored—but it's set up to make it very easy to manage other params, basically by just adding them to a whitelist mapping the param name to the ansible variable name. (Currently assumes it'll be one of the variables in `postgresql/defaults/main.yml`).

Manage RDS (postgresql) parameters in terraform

---

environments/staging/public.yml

Not going to merge this yet until the new couch machines are in use, just PRing this so you can look it over
@dannyroberts 

Point at AWS couch proxy instead of cloudant machine on staging

---

environments/production/postgresql.yml

Reason: RDS doesn't allow us to install pgbouncer on the postgrs machines themselves, so the plan is to increase the connection limit and just have pgbouncer installed on the proxy machine. We're applying this change to production now, so we can make sure that doesn't cause any big problems. Note: I haven't applied these changes yet, but did run in check mode
@dannyroberts 

Test prod without pgbouncer

---

environments/production/postgresql.yml

Reverts dimagi/commcare-cloud#2468
@calellowitz 
@dannyroberts 
Reverting the whole pr (not just the port changes) because the connections are maxed at 290 with pgbouncer, so the increase to 1000 would have no effect:  https://github.com/dimagi/commcare-cloud/blob/master/environments/production/postgresql.yml#L6

Revert "Test prod without pgbouncer"

---

environments/staging/postgresql.yml
src/commcare_cloud/ansible/roles/airflow/templates/airflow.cfg.j2
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2
src/commcare_cloud/ansible/roles/postgresql/templates/pgbouncer.ini.j2
src/commcare_cloud/environment/schemas/postgresql.py
tests/postgresql_config/2018-04-04-development-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-enikshay-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-icds-new-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-l10k-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-pna-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-production-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-softlayer-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-staging-snapshot/.generated.yml
tests/postgresql_config/2018-04-04-swiss-snapshot/.generated.yml

I tried or thought about a couple different approaches, and this seemed to be by a good margin the simplest. Basically there's a new `pgbouncer_host` option on each db, and it defaults to the same machine; throughout where looking up what host to access a db on, we'll now look at `pgbouncer_host` instead of `host`. On envs we're not changing, this should create no diff.
~Haven't yet been able to test this against staging (bad internet), but should be ready for review of the concept.~

Allow pgbouncer in front of remote dbs, and configure on staging

---

environments/production/terraform.yml

I discussed with @snopoke and he pointed out it'd be good to have one shard per db. I sized the each shard to be ~half the size of current hqdb1, which makes sense because hqdb2 has two partitions. Since hqdb5 is 2x hqdb1 but had 3 partitions, it's currently uneven, but after this change each partion will have the same amount of resources dedicated to it, and on average slightly more than now.

Rearrange how dbs map to rds instances

---

environments/icds-cas/public.yml

Reverts dimagi/commcare-cloud#2460
Turns out this is not needed right now so should be removed. Leaving the httpassword file around so that this can be added back when needed.

Revert "add tamil location"

---

docs/commcare-cloud/commands/index.md
environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/postgresql/main.tf
src/commcare_cloud/terraform/modules/postgresql/variables.tf

Loading is faster with multi-az turned off, so I'm not going to turn on multi-az (essentially hot standby) on prod until after the migration. But I wanted to be ready to do so with the implications tested on staging.
Takeaways for the rollout:
- Turning on multi-az did put the RDS instance into a "Modifying..." state for a while, but didn't appear to cause any downtime.
- Once staging was on multi-az, I resized an instance to see what the downtime of that is. I didn't personally notice it just clicking around, but sentry reports a total of 3 postgresql errors coming from things that pummel it with routine queries like the `run_sms_queue` and pillowtop. So not perfect, but very limited service interruption for changing the instance type (i.e. changing RAM, CPU, etc.)

Prepare for multi-az rds instances and test on staging

---

environments/production/terraform.yml

Follows https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_BestPractices.html#CHAP_BestPractices.PostgreSQL for what you should do to speed up a `pg_restore`

Tune production RDS for pg_restore (revert after migration)

---

environments/production/terraform.yml

Reverts dimagi/commcare-cloud#2499
Return RDS settings back to normal after migration to RDS. (They were set to settings optimized for doing a `pg_restore` but probably inappropriate for normal suage, so reverting this afterwards was the plan all along.)

Revert "Tune production RDS for pg_restore (revert after migration)"

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

I'd originally made webworkers absurdly large to rule out resource scarcity as a cause during firefighting of Oct slowness. After looking at the eye-popping numbers from Nov, I think it's time to go back to a reasonable size. Rolling these changes out will save us $1,600/mo. (The first commit just removes machines that were already stopped, so it doesn't affect anything—performance or price.)
From looking at datadog graphs (https://app.datadoghq.com/dash/510484/host-groups?tile_size=m&page=0&is_auto=false&from_ts=1541937600000&to_ts=1544529600000&live=true&tpl_var_host_group=webworkers), I made some estimates about peak resource usage on the two webworker types, and settled on the following:
hq_webworkers: 33% the CPU, 67% the RAM
mobile_webworkers: 25% the CPU, 50% the RAM
m5.2xlarge …

Remove unused webworkers and "rightsize" the rest

---

environments/production/terraform.yml

CPU on the new machines is too low: 
https://app.datadoghq.com/dash/510484/host-groups?screenId=510484&screenName=host-groups&from_ts=1544617920000&is_auto=false&live=true&page=0&tile_size=m&to_ts=1544632320000&tpl_var_environment=production&tpl_var_host_group=webworkers&fullscreen_widget=380325265
Once approved, I'll roll out the changes one by one and then merge this in.
@dannyroberts @snopoke

Increase CPU on production webworkers

---

src/commcare_cloud/ansible/roles/bootstrap-users/templates/sudoers.j2

This solves an issue that was seen in the echis domain. They had the `cchq` user in the `sudo` user group, so the `{{ cchq_user }}    ALL = (ALL) NOPASSWD: HQCOMMANDS` line was overwritten by a different line, and various sudo commands did not work for the cchq user that should have worked.
@dannyroberts @calellowitz

Move this line to the bottom of the file so it doesn't get overwritten

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

This came up recently as causing issues. There's no reason for us to still have this machine in the inventory.

Remove old prod rackspace proxy hqproxy0

---

changelog/0010-letsencrypt-restart-nginx.yml
docs/changelog/0010-letsencrypt-restart-nginx.md
docs/changelog/index.md
src/commcare_cloud/ansible/letsencrypt_cert.yml

using the built-in hook. Will have to roll this out to every env that
uses letsencrypt before it'll take effect.
Noticed from the discussion we currently do this manually, which adds to the confusion around certs.
@NitigyaS see any problems with this?

Make cert new cron job reload nginx after renewing

---

environments/production/terraform.yml

keeping CPU the same. m5.4xlarge => c5.4xlarge
These are a bit less expensive. We seem to make good use of the CPU, but not almost any of the RAM. I'll be locking in reservations for ec2 instances, so I'm doing a pass to make sure we're at least on the right instances classes for our major instances.

Halve RAM on production couch nodes

---

src/commcare_cloud/terraform/modules/openvpn/main.tf
src/commcare_cloud/terraform/modules/server/main.tf

This just adds an extra layer of friction for deleting machines, so that it's less likely that the disaster scenario of by mistake deleting important machines could happen. To delete a machine, you'll have to first turn off termination protection on that machine, which you can do from the AWS console

Turn on termination protection for all ec2 instances

---

src/commcare_cloud/terraform/modules/server/main.tf

Also call the group tag "Group" instead of "group_tag".

Add tags to AWS volumes

---

environments/production/terraform.yml

disks were over 80% full at 6TB, so I further increased it.
These changes are already rolled out.

Increase data volume on couchdb2 machines to 7.5 TB

---

environments/production/terraform.yml

I set commcarehq db to only store shards on couch0, and I'll index it there. This is following @emord's suggestion in #interrupt-team

Temporarily increase couch0-production for view indexing

---

environments/softlayer/app-processes.yml

and consolidate other queues.
There is also one fewer worker processes total,
leaving a little more memory and CPU headroom.

Give softlayer background_queue dedicated process

---

environments/production/terraform.yml

Reverts dimagi/commcare-cloud#2579
The do-everything-on-couch0 approach has really not been working well. Plan is to revert this to make couch0 normal-sized again, and then add dedicated nodes for the commcarehq db indexing

Revert "Temporarily increase couch0-production for view indexing"

---

src/commcare_cloud/commands/migrations/plays/assert_couch_files.yml

for shard files not created by couchdb-migrate,
the owner may be set such that the ansible user cannot perform operations
without escalation
Ran into this recently @snopoke I think this is the error I'd seen before (while working on softlayer) that I'd previously mistakenly identified as a checksum error.

Run "Assert couchdb shard files exist" as root

---

environments/icds-new/public.yml

I also had to manually run the following:
`cchq icds-new run-shell-command elasticsearch 'mv /opt/data/elasticsearch-1.7.6/data/icds-2.0 /opt/data/elasticsearch-1.7.6/data/icds-nic' --become`
Seems like all is well:
```curl -XGET http://10.247.164.15:9200/_cluster/health?pretty=true
{
"cluster_name" : "icds-nic",
"status" : "green",
"timed_out" : false,
"number_of_nodes" : 4,
"number_of_data_nodes" : 4,
"active_primary_shards" : 56,
"active_shards" : 58,
"relocating_shards" : 0,
"initializing_shards" : 0,
"unassigned_shards" : 0,
"delayed_unassigned_shards" : 0,
"number_of_pending_tasks" : 0,
"number_of_in_flight_fetch" : 0
}
```
(also verified index sizes look reasonable using `curl -XGET http://10.247.164.15:9200/_stats/index,store?pretty=true`)

rename elasticsearch cluster on NIC

---

environments/production/app-processes.yml

I chose celery0 because it has the most unused RAM. I chose to add gevent to reduce the amount of RAM needed to add these to that machine.

Add celery4 queues to celery0 with gevent

---

src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

@calellowitz 
fyi @mkangia This is why I was seeing `ReportConfigurationNotFoundError` when working in shell: the paths to the static report json configs are relative, so when the shell was running from `/home/my_username` it would error out.

Added cd into code directory when running django-manage

---

environments/production/terraform.yml

Already deployed, in response to these disks being at >90% this morning. These are the nodes that I'm using to host and reindex the `commcarehq` database only, at least for now.

Increase couch[3-10]-production volume sizes

---

environments/production/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

This puts us entirely on local couchdb2 and entirely off cloudant.

Switch to using local couchdb2 for production commcarehq db!

---

environments/production/app-processes.yml

Reverts dimagi/commcare-cloud#2597
There's no need now that celery4 is working well again, and it caused problems on celery0.
For the last day or so, `celery`, `case_import_queue`, and `export_download_queue` have all been running on both `celery0` and `celery4`

Revert "Add celery4 queues to celery0 with gevent"

---

environments/icds-cas/postgresql.yml

@snopoke Thoughts on deploying this tomorrow (today for you). Suggesting this to try lowering load on the main database
the standbys are almost always half of the disk read i/o as the main https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1546746838050&to_ts=1549338838050&tile_size=m&exp_metric=system.io.rkb_s&exp_scope=environment%3Aicds%2Cgroup%3Aucr_dbs&exp_group=host&exp_agg=avg&exp_row_type=metric
should only need to restart celery (really should just need icds_dashboard_reports_queue) and webworkers:
```
cchq icds webworker restart --limit=web0,web1,web2,web3,web4,web5
cchq icds webworker restart --limit=web6,web7,web8,web9,web10,web11
... other webworkers
cchq icds celery restart 
```
I think that would be safe to do during load. Other services could …

Increase reads going to UCR standbys

---

environments/icds-cas/public.yml

These are already written (and were present in the old NIC configurations). Deploying them so that we can see the differences

Laboratory child_health UCR

---

environments/production/terraform.yml

Final couchdb cluster will be 8 x (c5.2xlarge, 5.3TB disk). After migration, will terminate couch[0-2].

Expand existing nodes for final couchdb cluster

---

.gitignore
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/migrations/0004-migrate-non-main-dbs/couchdb-step-1.yml
environments/production/migrations/0004-migrate-non-main-dbs/couchdb-step-2.yml
environments/production/migrations/0004-migrate-non-main-dbs/couchdb-step-3.yml
environments/production/terraform.yml

These changes have already been applied. Our new allocation is
```
target_allocation:
- couch3,couch4,couch5,couch6,couch7,couch8,couch9,couch10:3
```
i.e. 3 copies evenly distributed across the eight new nodes, couch[3-10]. The data has been migrated and the old nodes couch[0-2] have been terminated. (I took a snapshot of their data volumes just in case before deleting, but I don't expect we'll need those.)

Finalize production couch

---

environments/production/terraform.yml

couch6 is consistently a bit higher than others and I did this this morning
to prevent disk from filling

Increase couch6 disk size

---

environments/production/public.yml

Previously they started at 7PM EST and would run all night and into the late morning,
which is our peak load time.

Start production backups at 11AM EST

---

environments/production/public.yml

I decreased this yesterday and things were _worse_ not better last night.
Though it may be unrelated, I am going to try taking this in the opposite direction.
It's possible such frequent reindexing caused unnecesary churn
and CPU spent on rarely accessed views when it was needed to process real requests.

Make COUCH_REINDEX_SCHEDULE less frequent on production

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

I had fixed this yesterday, but forgot to PR it

Fix COUCH_REINDEX_SCHEDULE assignment in localsettings.py

---

environments/icds-new/postgresql.yml
environments/softlayer/postgresql.yml

Without this [this other PR](https://github.com/dimagi/commcare-hq/pull/23199/files) would break ICDS UCRs on softlayer.

default icds-ucr-non-dashboard for softlayer and icds-new

---

environments/production/public.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
src/commcare_cloud/terraform/modules/server/main.tf

The tar/gzip-style backups we do are taking longer than 24h to run on production and take a _lot_ of space on the pricey SSDs. This turns off our manual backup strategy and replaces it with a policy of taking volume snapshots of couchdb2 data volumes. Currently set to once a day, saving the last 7.

Use built in AWS snapshots to backup production couchdb2 volumes

---

environments/production/terraform.yml
scripts/example-apply-terraform-to-single-server-and-bring-back-up.sh
src/commcare_cloud/environment/main.py

We've been getting http errors on CouchDB on production during IST ever since we got off Cloudant, and I want to do a conclusive test that will narrow the cause down to a CPU/RAM bottleneck. This PR doubles the CPU and RAM on all nodes. Then using the data I get from this, I will rearrange the couch nodes back down to a more cost-optimized node configuration (e.g. maybe fewer larger nodes, less total disk, etc).
I also included a little script I made while doing this that strings together the multiple steps involved in restarting nodes one by one. It's nothing fancy, and it may be better suited to be a `cchq` command in the future, but I wanted to jot down the quick and dirty version so I had something to iterate on as I continue to do similar operations.
production …

Temporarily double all production couch nodes to c5.4xlarge

---

src/commcare_cloud/ansible/roles/nginx/vars/cchq_ssl.yml

I inadvertently changed this setting in https://github.com/dimagi/commcare-cloud/pull/2324.
This PR changes it back to the pre-Oct 23 2018 value of 900s (https://github.com/dimagi/commcare-cloud/pull/2300)
All environments but mainly production
I'm not certain this will fix it, but this is attempting to fix an ongoing issue we've discovered that we've had since ~Oct 29, 2018 where form submissions have only a 50% (daily) success rate.
Mobile webworkers / form submissions

Update proxy_read_timeout for the receiver|phone endpoint to Oct 2018 value

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Update localsettings to remove old blobdb now that all data has been migrated to back to Riak.
* icds
```
cchq icds update-config
```
* Before
```diff
--- before: /home/cchq/www/icds/current/localsettings.py
+++ after: /tmp/ansible-local-22176_hIY2P/tmpZ27tq1/localsettings.py.j2
@@ -388,15 +388,6 @@
'bulk_delete_chunksize': 1000,
'config': {'signature_version': 's3'},
}
-OLD_S3_BLOB_DB_SETTINGS = {
-    'url': 'https://mowcdmum.ipstorage.tatacommunications.com',
-    'access_key': 'mowcdmumusr',
-    'secret_key': '316dfae92a322c17ea41eb1dee20c2d4',
-    's3_bucket': 'mowcdmum-c1',
-    'bulk_delete_chunksize': 200,
-    'config': {'signature_version': 's3'},
-}
-BLOB_DB_MIGRATING_FROM_S3_TO_S3 = True
```

remove TCL object storage

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/migrations/0005-reduce-couchdb-to-6-nodes/couchdb-step-1.yml
environments/production/terraform.yml

CouchDB for the last couple weeks was 8 x (8 CPU, 16GB RAM) nodes, and we were getting a lot of http errors from couch during IST work hours. Yesterday we doubled node sizes to 8 x (16 CPU, 32GB RAM), and the errors went away almost entirely. But that seems like an absurd amount of power to need. In addition, I was able to reclaim many terrabytes of space in the last week, we're now paying for too much disk as well. Because of these two things together, I'm estimating that 6 nodes with the same disk and node size is a good compromise position that balances cost and performance. (I'm still surprised at the CPU and RAM we need on this cluster to keep it running smooth at peak hours, but I don't have a good way to gauge what those number should be.)
Somewhat fortuitously, the current disk …

Reduce production couchdb to 6 nodes

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2

It was failing on a triviality---assinging a particular tag that conflicted with one copied over from a volume
production
CouchDB AWS snapshot backups

Fix automated AWS couch snapshot backups

---

environments/production/proxy.yml

This was recently doubled from 512, which helped but wasn't quite enough.
This is motivated by couchdb2_proxy (not the main site proxy, which it also affects).
production
CouchDB proxy (production)
```diff
TASK [nginx : Copy the nginx configuration file] ***********************************************************************************************************************************************************
--- before: /etc/nginx/nginx.conf
+++ after: /Users/droberts/.ansible/tmp/ansible-local-48309lH9bnS/tmp5GnJ_G/nginx.conf.j2
@@ -6,7 +6,7 @@
worker_rlimit_nofile 65536;
events {
-    worker_connections  1024;
+    worker_connections  2048;
}
```

Double production nginx_max_worker_connection to 2048

---

environments/softlayer/postgresql.yml

Adds AAA database used for the new dashboard
softlayer
postgresql
```bash
cchq softlayer ap deploy_db.yml --branch=je/add-aaa-db --tags=postgresql --limit=db1
cchq softlayer ap update-config --branch=je/add-aaa-db 
```
@NitigyaS I noticed that softlayer has a lot of diffs with the pgbouncer hba confs that I believe you've been working on. Can you look into resolving those? I was able to work around it today

Add AAA database

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

This hardcodes the version of pickle used by ```django_redis```, which enables backwards/forwards compatibility between python 2 and 3.
See https://github.com/dimagi/commcare-hq/pull/23284 for more information.
All
localsettings
Without this addition, the highest available pickle version is used in python 3, which then can't be used with python 2.
@dimagi/py3

specify redis pickle version in localsettings

---

environments/production/app-processes.yml

Increase the concurrency and number of workers on `email_queue`
Production
N/A
I'm increasing the capacity of `email_queue`, to avoid a lag in user's receiving the confirmation email (instead of creating a new queue entirely, detailed https://github.com/dimagi/commcare-hq/pull/23291 and https://github.com/dimagi/commcare-cloud/pull/2661)

Increase concurrency on prod email_queue

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/ansible/roles/commcarehq/vars/main.yml

Creates a new virtualenv for python 3.6 and adds requirements.  Coexists with the python 2 virtualenv.
Currently is only run if the variable ```py3_include_venv``` is set to true, since python 3.6 does not come by default with Ubuntu 14.04.
No environments are affected for now.  After the Ubuntu 18.04 migration is complete I will make these tasks standard for all environments.
@dimagi/py3

add tasks to optionally include a python 3.6 virtualenv

---

scripts/example-rolling-restart-couchdb2.sh

This is just an example snippet, something I used earlier to day that was effective. Like the other example snippet in this directory, I wasn't ready to turn this into a tool, but didn't want to lose the little tinkering I'd done to figure it out entirely.
none

Add example snippet for a couchdb2 rolling restart

---

src/commcare_cloud/ansible/roles/postgresql/tasks/set_up_dbs.yml

Addding Encryption Flag. https://github.com/ansible/ansible/issues/33753
Require in Postgresql >= 10
Will be required by CitusDB too. 
all
Ansible : PostgreSQL

Store Password Encrypted Require above PostgreSQL 10

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/formplayer.py

Previously, formplayer restarts during every deploy. Now it only restarts when the jar changes,
because for the time being restarting formplayer causes meaningful Web Apps downtime.
All that use Web Apps
This is mostly a hack to fix the 80% case. The "real" issue is that we don't have a way to restart formplayer without causing a service interruption.
Web Apps (formplayer)

Only restart formplayer when the jar has changed

---

src/commcare_cloud/terraform/modules/network/main.tf

Try number two of https://github.com/dimagi/commcare-cloud/pull/2677.
This should fix at least some of the low but consistent rate of postgres errors
we've been seeing.
production, staging
websockets

Give proxy access to pgbouncer port in AWS envs

---

changelog/0015-separate-celery-datadog-http-check.yml
docs/changelog/0015-separate-celery-datadog-http-check.md
docs/changelog/index.md
src/commcare_cloud/ansible/roles/datadog/templates/http_check.yaml.j2

This adds a specific http check for the celery check (serverup.txt?only=celery) to datadog.
Environments that are not relying on datadog for monitoring can ignore this change.
Datadog monitoring 
Example ansible diff:
```
--- before: /etc/dd-agent/conf.d/http_check.yaml
+++ after: /Users/droberts/.ansible/tmp/ansible-local-97263sd5Pmr/tmpygx_Im/http_check.yaml.j2
@@ -11,6 +11,12 @@
include_content: true
tags:
- check_type:serverup
+  - name: production Celery
+    url: https://www.commcarehq.org/serverup.txt?only=celery
+    check_certificate_expiration: false
+    timeout: 30
+    tags:
+      - check_type:celery
- name: production Heartbeat
url: https://www.commcarehq.org/serverup.txt?only=heartbeat
check_certificate_expiration: false
changed: [10.202.20.138] => …
```

Separate celery check

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/formplayer.py
src/commcare_cloud/fab/operations/release.py
src/commcare_cloud/fab/operations/supervisor.py

fixes https://github.com/dimagi/commcare-cloud/pull/2682
In addition, I found that another assumption from when I made that PR weren't correct. I found that since possibly forever, formplayer has been restarted _twice_ on every deploy: once unnecessarily before we've re-linked the current commcare-hq release (thus not picking up any changes) and once again afterwards when we restart services. In this PR I remove the first time entirely, and make the second time only happen if we detect an actual change in the formplayer jar
All
Formplayer deploy

Fix formplayer deploy after recent change

---

changelog/0017-monitor-specific-rabbitmq-queues.yml
docs/changelog/0017-monitor-specific-rabbitmq-queues.md
docs/changelog/index.md
src/commcare_cloud/ansible/roles/datadog/templates/rabbitmq.yaml.j2
src/commcare_cloud/environment/schemas/app_processes.py

Datadog has a 200 queue limit for RabbitMQ monitoring. Most of the queues are individual worker queues and not of great interest to us.
This changes the datadog configuration to only record metrics for the primary queues.
All
RabbitMQ Datadog integration

only monitor primary rabbitmq queues 

---

src/commcare_cloud/environment/schemas/app_processes.py

Just a little thing I come across sometimes. The comment here wasn't quite right for all queues there and I thought I could break it down a little more clearly. Also removed some things that weren't defined as a `CeleryProcess` and thus didn't need to be in the list.
It's a no-op change.
- Comment Pull Request
Celery config

Clean up solo_queues declaration in app_processes.py

---

environments/swiss/public.yml

Add comment on swiss DATADOG_INTEGRATIONS_ENABLED
so that if someone comes along who would like to enable integrations
they know they have the go-ahead
Taken from a slack coversation:
> Danny Roberts [12:10 PM]
>  Hey I just wanted to confirm we’re okay with swiss not having datadog integrations enabled, including the basic endpoint checks: https://github.com/dimagi/commcare-cloud/blob/cfc4c794f1a36c2e935a9ed69fea206c778c7efa/environments/swiss/public.yml#L4
> GitHub
> dimagi/commcare-cloud
> Tools for standing up and managing a CommCare HQ server environment - dimagi/commcare-cloud
> If anyone knows anything specific about the decision not to enable datadog integrations there, I can add it as a comment to that file
> @snopoke looks like it was a matter of just not needing it? …

Add comment on swiss DATADOG_INTEGRATIONS_ENABLED

---

environments/icds-cas/public.yml

Add back previously broken UCR comparison test due to issues
icds
UCR comparison
hopefully the reports are working again and we can retest these.
@emord seem right?

add delivery death list report back to UCR_COMPARISONS

---

environments/production/app-processes.yml

Adds more Celery resources to deal with the repeat record queue.
Fixes (improves?) [HI-451: Delay in Data Forwarding](https://dimagi-dev.atlassian.net/browse/HI-451).
production
production app-processes.yml
This is the result of some wild guesswork on my part. I haven't absorbed enough from the Celery docs to understand our Celery config. I'm sure this change will add more resources to deal with the problem, but I don't know if this is the best way to do it.
Here are some things I'd like to understand so I can know whether this change is "right", or even "good".
- **workers vs processes:** This [SO answer](https://stackoverflow.com/a/32046332) distinguishes between Celery workers (`num_workers`) and worker processes (`concurrency` and `autoscale`). The [Celery …

Throw more resources at the repeat record queue

---

src/commcare_cloud/terraform/modules/network/main.tf
src/commcare_cloud/terraform/modules/openvpn/main.tf

We use the Group tag to classify AWS costs, and I found a few more sources for untagged costs

Add cost tags for openvpn and network

---

environments/india/app-processes.yml

Fixes https://dimagi-dev.atlassian.net/browse/ICDS-405
Better allocates resources for india's celery.
india
celery
gevent queues should be used for tasks which are I/O bound. These are things like  external requests to other services (analytics, email, repeats,etc).
Previously the analytics queue was in a non-gevent queue which clogged the queue with tons of events (and would have caused a lot of process restarting). async_restore_queue and celery_periodic have non-I/O bound tasks which would clog the gevent queue (resulting in large backups of emails/analytics)
@dannyroberts I think a long term outcome of this should be enforcing a queue is always/never gevent in the celery process schema. How does that work into platform reliability's current work on celery?

Fix india celery queues

---

environments/production/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/celery_bash_runner.sh.j2
src/commcare_cloud/environment/schemas/app_processes.py
src/commcare_cloud/environmental-defaults/app-processes.yml

Run celery processes with [`ddtrace-run`](https://docs.datadoghq.com/tracing/languages/python/)
Probable fix for https://sentry.io/organizations/dimagi/issues/918618547, based on absence of errors in trace-agent.log after deploying to celery0-production.
Will deploy to other celery machines after review/approval.
production
commcarehq ansible role
@snopoke @dannyroberts

Use ddtrace-run with celery

---

environments/production/app-processes.yml

This issue was observed in the background_queue on production: https://github.com/celery/celery/issues/5120
Using gevent avoids the bug.  These changes are currently running on production.
I'd recommend applying similar changes to other workers on an as-needed basis until a bugfix becomes available.  background_queue was chosen because the workers would never recover from this issue.  Other queues sometimes are going down but are recovering on their own.

fix WorkerLostError in production background_queue

---

docs/commcare-cloud/env/index.md
environments/production/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_workers.conf.j2
src/commcare_cloud/environment/schemas/app_processes.py
src/commcare_cloud/environmental-defaults/app-processes.yml

Updates include:
1) Remove ```dd-trace``` from production.  Memory issues are reproduced when ```dd-trace``` is running and you run:
```
from corehq.apps.export.tasks import saved_exports
saved_exports.delay()
```
2) Remove ```maxtasksperchild``` from all workers in prefork.  This addresses https://github.com/celery/celery/issues/5120.  This has a risk of causing memory leaks if there are many tasks in the queue and the child process is never stopped.  However, I think this is more of a theoretical risk than a practical risk and, if it were to appear, could be addressed by adding more workers so queues don't get backlogged.
3) Runs ```background_queue``` in prefork.  I switched it to run in gevent to avoid https://github.com/celery/celery/issues/5120, but this caused the bug: …

improvements for production celery stability

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Revert dimagi/commcare-cloud#2713 after reviewing the [Mobile Request Success dashboard](https://app.datadoghq.com/dashboard/a4u-nfz-gex/mobile-request-success) and concluding that this change made no difference in submission success rates on prod.

Revert "Undo split prod webworkers"

---

environments/echis/app-processes.yml
environments/icds-cas/app-processes.yml
environments/india/app-processes.yml
environments/pna/app-processes.yml
environments/staging/app-processes.yml
environments/swiss/app-processes.yml

Removing ```max_tasks_per_child``` from production worked well (https://github.com/dimagi/commcare-cloud/pull/2719) so I'm applying these changes to all environments.

discontinue using max_tasks_per_child

---

environments/production/app-processes.yml

```async_restore_queue``` gets backed up during high load times.  celery0 and celery2 are underutilized in both CPU and memory, so I'm increasing the number of workers from 1 to 2.  I expect to revisit this later in the week and possibly continue to increase the number of workers.

double number of async_restore_queue workers on celery0 and celery2

---

environments/icds-cas/postgresql.yml

This sets the acceptable lag to 0 this was specifically changed to allow the bulk user upload to go smoothly without error. Else it was causing this error: 
```
File "/home/cchq/www/icds/releases/2019-03-19_22.04/python_env/local/lib/python2.7/site-packages/celery/app/trace.py", line 375, in trace_task
R = retval = fun(*args, **kwargs)
File "/home/cchq/www/icds/releases/2019-03-19_22.04/python_env/local/lib/python2.7/site-packages/celery/app/trace.py", line 632, in __protected_call__
return self.run(*args, **kwargs)
File "/home/cchq/www/icds/releases/2019-03-19_22.04/corehq/apps/users/tasks.py", line 43, in bulk_upload_async
task=task,
File "/home/cchq/www/icds/releases/2019-03-19_22.04/corehq/apps/users/bulkupload.py", line 547, in …
```

Set the accepted lag to 0

---

environments/icds-cas/app-processes.yml

The ```icds_aggregation_queue``` worker was suffering from the same issue as ```background_queue``` on production: https://github.com/dimagi/commcare-cloud/pull/2719
Changing to prefork avoids https://github.com/celery/celery/issues/3377
I applied these changes and ```icds_aggregation_queue``` is now processing successfully: https://app.datadoghq.com/dashboard/bdu-k5b-bz5/celery-overview?tile_size=m&page=0&is_auto=false&from_ts=1552914000000&to_ts=1553086800000&live=true&tpl_var_environment=icds&fullscreen_widget=185712938

use prefork for icds_aggregation_queue

---

environments/production/terraform.yml

The fullest two couchdb disks, couch7 and couch8, are at 95% and 91% during their daily peak. This aims to get them down to around 86%. I will be deleting some large views next week which should get the usage down a little more. The total increase will cost +$90/mo (+900GB @ $.10/GB/mo).
production
production couchdb disk

Minimally increase couch{7,8} disk to keep them under 88%

---

environments/production/app-processes.yml

https://github.com/dimagi/commcare-cloud/pull/2724 helped prevent ```async_restore_queue``` from getting backlogged.  I'm making this change to provide a little more buffer, and because these two machines are still underutilized.
code buddy @mkangia

double num_workers for async_restore_queue on celery0 and celery2

---

environments/icds-cas/public.yml

Removing UCR comparisons from ICDS
ICDS
UCR
Most of these aren't being used since @czue completed the person case UCR work and they are causing (harmless) [sentry errors](https://sentry.io/organizations/dimagi/issues/944647902/?project=136860&referrer=slack). The rest of them have known discrepancies as part of the MPR, meaning that comparisons aren't particularly useful going forward.

Remove UCR comparisons from icds

---

commcare-cloud-bootstrap/commcare_cloud_bootstrap.py
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/helpers.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/commands/ansible/service.py
src/commcare_cloud/commands/terraform/terraform_migrate_state.py
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/environment/main.py

Send an event to datadog when a commcare-cloud command is run (if it loads the ansible vault). This will provide a basic audit trail of commcare-cloud changes applied to environments with datadog monitoring.
All environments with datadog enabled and having proper datadog credentials in the `secrets` section of the corresponding ansible vault.
The following have `DATADOG_ENABLED: True` in *public.yml*:
- production
- icds
- india/softlayer
- swiss
- pna
- staging
- 64-test?
Events are only sent when ansible vault variables are loaded since some of those variables are needed to send the event. It would be possible to always prompt for the vault password for every commcare-cloud command, and we may want to consider that for some additional commands in the future, but I …

Record commcare-cloud command events in datadog

---

src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer_hba.conf.j2

The current template was relying on the fact that on some environments (e.g. ICDS, india)
pgbouncer_host is always the same as host. On staging and production, which use Amazon RDS,
that becomes a problem. Not sure exactly when this took effect, but it became an issue
when this template was used to build a new pgproxy machine on staging, which would not allow
connections from any of machines except for the commcarehq_proxy db.
Currently this is for staging, but this is more correct for all environments.

Make pgbouncer_hba reference pgbouncer_host

---

environments/production/app-processes.yml

celery2 is quite underutilized, so let's double the capacity to process saved_export_queue tasks.

add saved_exports_queue workers to celery2

---

environments/production/app-processes.yml

Continuing to increase resources for saved_export_queue.  Ideally I would like this task to be scheduled for completion by midnight EST so if there are issues, I'll be awake to debug them.
Current machine utilization:
https://app.datadoghq.com/dash/host/665473534?live=false&tile_size=m&page=0&is_auto=false&from_ts=1553557381993&to_ts=1553606775000
https://app.datadoghq.com/dash/host/665473537?live=false&tile_size=m&page=0&is_auto=false&from_ts=1553557866139&to_ts=1553606806000

double concurrency of saved_export_queue workers in production

---

environments/icds-cas/inventory/postgresql.csv

Stopping pgsynclogstandby0 to proceed for deltion of node.
This will yield extra disk space for other crucial nodes. 
```paste below
```
* Before
```paste below
```
* After
```paste below
```

Removed pgsynclogstandby0

---

environments/production/terraform.yml

We've been getting oscillating disk usage warnings for about a month now, and some of the disks really are uncomfortably full. I did out what it would take for each disk to get down to 65% full (at their daily peak) and came up with these numbers. Will cost an extra $930/mo or so, but it puts us in a safer place and will make the disk warnings a stronger signal.
  | current max (%) | current disk (GB) | target max (%) | new disk (GB) | increase (GB)
-- | -- | -- | -- | -- | --
couch3 | 82 | 5500 | 65 | 6938 | 1438
couch4 | 80 | 5500 | 65 | 6769 | 1269
couch5 | 83 | 5500 | 65 | 7023 | 1523
couch7 | 77 | 6100 | 65 | 7226 | 1126
couch8 | 86 | 5800 | 65 | 7674 | 1874
couch9 | 89 | 5500 | 65 | 7531 | 2031
  | **current spend** | $3,390/mo |   | **increase spend** | $926/mo
production

Resize prod couch disks to target 65% full

---

environments/icds-cas/app-processes.yml

https://dimagi-dev.atlassian.net/browse/ICDS-414
```UpdateUserSyncHistoryPillow``` has a low CPU load, so I'm not worried about adding load to ```pillow0```.  I've increased the number of kafka partitions for ```synclog-sql``` to 16.

increase number of UpdateUserSyncHistoryPillow processes

---

environments/icds-cas/postgresql.yml

https://dimagi-dev.atlassian.net/browse/HI-125
Accounting should never use the standby servers, since accounting often assumes a ```.save()``` operation to have effect immediately after it is called.
We now cache the current subscription, which used to be the largest source of accounting load by a lot.

accounting should never use standby DBs

---

environments/icds-cas/app-processes.yml

Followup to https://github.com/dimagi/commcare-cloud/pull/2758
@calellowitz 
@gbova

Remove celery112 from app processes

---

changelog/0019-update-rabbitmq-logging.yml
docs/changelog/0019-update-rabbitmq-logging.md
docs/changelog/index.md
src/commcare_cloud/ansible/deploy_db.yml
src/commcare_cloud/ansible/deploy_rabbitmq.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/main.yml
src/commcare_cloud/ansible/roles/rabbitmq/templates/rabbitmq.config.j2

I think upgrading to Celery4 has increased the number of connections and disconnections occurring on RabbitMQ which has greatly increased the logging and is filling up the disks.
all (optional)

add rabbitmq config with warning level logging

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/manage_commcare_cloud/make_docs.py

nit: Corrected heading level for command examples in documentation.
None.
N/A
Commands are H4 headings. Their examples were also H4 headings, and so they appeared alongside them in the contents as if they were also commands. This change corrects that.

Examples from H4 to H5

---

src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py

After all the diffs, have `manage-commcare-cloud update-datadog-monitors` print out the full list of untracked monitors. This is will be a useful part of helping us keep config files in sync with datadog. A next step will be to have a tool to ease the bootstrapping process to make configs out of these untracked monitors.
Datadog Monitoring
Current output:
```
FYI you also have some untracked monitors. No change will be applied for these:
- Untracked monitor 309189 'Django response times high' (no change will be applied)
- Untracked monitor 582119 'Datadog can't connect to pgbouncer' (no change will be applied)
- Untracked monitor 598865 'Riak service on {{host.name}}' (no change will be applied)
- Untracked monitor 654754 'ES Cluster Status ALERT' (no change will be applied)
- Untracked …
```

Have update-datadog-monitors print out list of untracked monitors

---

src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py
src/commcare_cloud/manage_commcare_cloud/monitors/es_cluster_status.yml
src/commcare_cloud/manage_commcare_cloud/monitors/riak_process_up.yml

Applied diff to datadog and then ran again and found there were spurious diffs, as well as one alert that wasn't updating. I cleaned up the diff until there were no diffs on subsequent runs, and made the tool louder when there's an error updating.

Clean up datadog monitors diff

---

environments/india/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py

Adding ":bionic" to the `group` tag was always sort of a hack, and has small annoying downstream effects. This cleans it up by specifying bionic in a separate `os: bionic` property.
Just staging for now. (The india aws env is not yet in use.)
Terraform, Bionic upgrade
The diff on staging only changes the servers' group tag (e.g. from 'webworkers:bionic' to just 'webworkers'). This is part of the point, since we use that tag for e.g. analyzing costs and it's annoying to have them split into groups like that.
Staging diff:
```
~ module.server__airflow1-staging.aws_instance.server
tags.%:           "3" => "3"
tags.Environment: "staging" => "staging"
tags.Group:       "airflow:bionic" => "airflow"
tags.Name:        "airflow1-staging" => "airflow1-staging"
~ …
```

 Give terraform server spec an `os` (trusty/bionic)

---

environments/datadog_envs.yml

Send india to #alerts-india and softlayer to #alerts-softlayer
to confirm the hypothesis that #alerts-softlayer will be empty.
After that we can remove softlayer from datadog_envs.yml altogether.
India
Datadog Monitoring
This will change the << notification_block >> portion of each monitor

Send india to #alerts-india and softlayer to #alerts-softlayer

---

src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

@Rohit25negi @biyeun @emord 
This adds two libraries needed for weasyprint, which is added in https://github.com/dimagi/commcare-hq/pull/23707/files

add packages for weasyprint

---

environments/india/public.yml

Softlayer support suggested I do this as part of fixing some network issues that come up when I try to set up the tunnel to AWS. This would only fix part of it (access to the public internet).
India
India softlayer-aws tunnel

Set india to use google nameservers

---

environments/production/app-processes.yml

Distribute some of `export_download_queue` and `email_queue` onto new celery6, overall increasing processing allocated to those queues.
I identified these queues by looking at this graph: https://app.datadoghq.com/dashboard/bdu-k5b-bz5/celery-overview?tile_size=m&page=0&is_auto=false&from_ts=1555432200000&to_ts=1555518600000&live=false&tpl_var_celery_queue=*&tpl_var_celery_task=*&tpl_var_environment=production&fullscreen_widget=1447409977947274
production
Celery

Add more "blip" queues to celery6

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/public.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
src/commcare_cloud/ansible/roles/ufw/tasks/main.yml
src/commcare_cloud/ansible/roles/ufw/tasks/proxy_ufw.yml

The bionic image on AWS has AWS Enhanced Networking enabled, which means among other things it calls the private interface `ens5` instead of `eth0`
AWS envs using bionic (staging, production)
Bionic

Fix private interface for enhanced network enabled AWS instances

---

requirements.txt
setup.py

I noticed this was causing a version conflict locally, including on a fresh install.

Fix s3transfer version conflict by setting a lower bound to boto3

---

src/commcare_cloud/fab/operations/release.py

Fix submodule fetch during deploy by running `git fetch orgin` in each submodule of the `current` directory before cloning it.
potentially all, in this case I was seeing the issue on production, and we've seen it before.
Deploy

Fix submodule fetch during deploy

---

environments/production/terraform.yml

Since RDS is managed through terraform, we have to set these settings separately there. For now just setting on the main db, but we can of course turn it on for others as well.
This is already applied.
production
RDS

Apply pg_stat_statement settings from other environments to pgmain0-production

---

environments/production/app-processes.yml

In response to yesterday's downtime on the UCR queue, I'm doubling the capacity, spread across two machines.
I haven't dug into what caused the downtime, but we do know that in this case as many others simply restarting the processor for the `ucr_queue` fixed it. My prediction is that simply adding enough redundancy to hold us over to the next deploy (which will restart all services) will go a long way towards preventing issues with a single processor leading to service disruption.
In this case though it looks like the queue being blocked was somehow triggered by the deploy, as it starts immediately after deploy.
production
Celery

Add redundancy to production ucr_queue

---

src/commcare_cloud/commands/ansible/ansible_playbook.py

run commands through ansible shell instead of through fab
Also now the reload also respects the `--limit` arg
Fixes https://github.com/dimagi/commcare-cloud/issues/2571
None
`update-supervisor-confs` command

Streamline reloading supervisor in update-supervisor-confs

---

src/commcare_cloud/ansible/roles/elasticsearch/templates/config/logging.yml.j2

This is a different attempt at fixing the same problem https://github.com/dimagi/commcare-cloud/pull/2533 was intended to fix, and which it didn't seem to fix. The symptom is an es machine occasionally become unresponsive, due to too high a rate of writing to "the console" and overloading "the serial port". I do not have a clear mental model of what those things mean. This potential fix is @calellowitz brainchild.
production

Disable elasticsearch console logging

---

src/commcare_cloud/ansible/letsencrypt_cert.yml

HTTPS for swiss wasn't working today, I didn't have to renew but just reload nginx to make it work. Presumably the certs renewed but nginx didn't get reloaded (perhaps because there was no deploy on swiss in a while.). 
I think if the `--renew-hook` worked correctly this would have been prevented. I think we should probably use `--post-hook`
```
root@commcarealmanach:~# certbot  --help renew | grep hook
changes. It also calls --pre-hook and --post-hook
hook commands are not called. (default: False)
--pre-hook PRE_HOOK   Command to be run in a shell before obtaining any
that have identical pre-hooks, only the first will be
--post-hook POST_HOOK
were stopped by --pre-hook. This is only run if an
hooks, only one will be run. (default: None)
--deploy-hook DEPLOY_HOOK
--disable-hook-validation …
```

Fix certbot renew hook 

---

environments/production/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/environment/schemas/terraform.py

The goal is to make it difficult to create a new "trusty" machine by mistake
Ubuntu upgrade
This change produces no diff (terraform or otherwise)

Make os (bionic|trusty) in terraform spec required with no default

---

src/commcare_cloud/ansible/roles/common_installs/tasks/bionic_apt_installs.yml

Friday when I was adding web4-staging I also had issues with `ufw` giving an opaque error on the first few passes, then I added this and run common_installs.yml and then the `ufw` commands worked. Not sure if it was this change or the re-running of some other part that made the difference, but I don't think this could hurt.

Install ufw on bionic

---

environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
src/commcare_cloud/commands/terraform/aws.py

Build wasn't failing when `aws-fill-inventory` fails because of a poorly formatted `inventory.ini.j2`; now it will. I also then fixed the staging inventory template and rendered it.

Fix staging inventory template and render it

---

control/init.sh

Since after this we won't auto-replace py3 virtualenvs on the control machine, I ran manual cleanup on staging to remove all py3 envs. (Since I know that they were all created in error, rolled out by mistake and then discovered, while working on https://github.com/dimagi/commcare-cloud/pull/2822.)
To clean up I ran
```
cchq staging run-shell-command control 'ls /home/*/.virtualenvs/ansible/bin/python3 | sed "s|/bin/python3||" | xargs rm -rf' -b
```
and then I also ran
```
cchq staging run-shell-command control 'rm -rf /home/droberts/.virtualenvs/ansible' -b
cchq --control staging ping all
```
just to test the experience, and as I predicted and hoped, the script properly recreates the missing virtualenv with no complaint, so it's a seamless experience.

Print loud warning instead of auto replacing a py3 virtualenv

---

src/commcare_cloud/commands/terraform/terraform.py

Previously, it would error if the password wasn't in vault, even if it didn't need it. E.g.
```
$ cchq india terraform plan
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting
Vault Password for 'india':
File "/Users/droberts/.virtualenvs/ccc/bin/cchq", line 11, in <module>
load_entry_point('commcare-cloud', 'console_scripts', 'cchq')()
File "/Users/droberts/dimagi/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 166, in main
exit_code = call_commcare_cloud()
File "/Users/droberts/dimagi/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 157, in call_commcare_cloud
exit_code = commands[args.command].run(args, unknown_args)
File "/Users/droberts/dimagi/commcare-cloud/src/commcare_cloud/commands/t …
```

Make terraform skip attempt to fetch rds password when no rds_instances are configured

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/public.yml

I noticed we were getting e.g. web0-india.india.commcarehq.org in
datadog. I'd like to use the same convention we have on staging and
production, which would be just web0-india. In order to keep existing
softlayer machines' hostnames the same, I also manually change their
hostnames to *.india.commcarehq.org.

Do not add india.commcarehq.org to AWS india hosts

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

The hundreds of round trips to backing services in softlayer are adding many seconds to longer requests: https://app.datadoghq.com/dashboard/g9s-pw6-tpg/hq-vitals?tile_size=s&page=0&is_auto=false&from_ts=1556215200000&to_ts=1556820000000&live=false&tpl_var_environment=india&fullscreen_widget=406795560566138.
Until there is a better rollout plan, I will revert to removing these.

Temporarily remove web[0-1]-india from webworkers list

---

src/commcare_cloud/ansible/roles/kafka/tasks/main.yml

@sanjay2916 I ran this again and noticed installing the systemd script was failing.
After deploying (`cchq staging ansible-playbook deploy_kafka.yml`) with this change, we stopped receiving this error: https://sentry.io/organizations/dimagi/issues/1004425291/?environment=staging&project=136860&query=is%3Aunresolved&statsPeriod=14d, though I'm not sure that this change is what caused that. There were other changes, notably that both kafka0 and kafka1's IP addresses were listed in the kafka and zookeeper settings, and deploying removed kafka0's IP address

Fix "Install Kafka systemd script" for bionic

---

environments/staging/aws-resources.yml
environments/staging/inventory.ini

when we run terraform plan after Swapping of elastic IP's manually, it's reverting back and if we edit terraform scripts, we will miss naming conversion and we will update the new IP in DNS

Changing Elastic IP for proxy server in staging environment

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/ansible/downtime.py
src/commcare_cloud/environment/paths.py

Query datadog for downtime record instead of storing it locally so that if the user ending the downtime is not the same as the user who started the downtime it will still get ended correctly on Datadog.
Also added an end time for the downtime to safeguard against it not being cancelled.

don't store downtime locally

---

src/commcare_cloud/ansible/roles/datadog/templates/http_check.yaml.j2

Make datadog not check the "heartbeat" endpoint anymore. Also, apply the same skip logic on staging to celery as we did to heartbeat
all (but it's largely invisible/cleanup)

Kill "heartbeat" http check, supplanted by "celery" check

---

environments/icds-cas/inventory/postgresql.csv
environments/icds-cas/postgresql.yml

Since we have seen high CPU on pgshard8 we are going to try promote pgshard8standby to see if it has the same issues.

swap pgshard8 and pgshard8standby

---

environments/swiss/app-processes.yml

Swiss doesn't tend to have long backlogs, and is having issues with too much memory being used, so this seems like a reasonable way to reclaim some memory.
swiss

Merge swiss celery into fewer processes

---

commcare-cloud-bootstrap/commcare_cloud_bootstrap.py
src/commcare_cloud/commands/migrations/config.py
src/commcare_cloud/commands/migrations/copy_files.py
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/paths.py
src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py
src/commcare_cloud/manage_commcare_cloud/make_changelog.py
tests/test_couch_migration.py
tests/test_postgresql_config.py

Replace yaml.load => yaml.safe_load throughout
to get rid of this message when running commands:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
meta_json = yaml.load(f)
```

Fix yaml.load deprecation warnings

---

environments/swiss/public.yml
src/commcare_cloud/ansible/roles/backups/tasks/main.yml
src/commcare_cloud/ansible/roles/backups/tasks/set_up_aws_credentials.yml
src/commcare_cloud/ansible/roles/couchdb/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb/templates/aws_credentials.j2
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2/templates/aws_credentials.j2
src/commcare_cloud/ansible/roles/pg_backup/tasks/backup_plain.yml
src/commcare_cloud/ansible/roles/pg_backup/templates/plain/aws_credentials.j2

The last backup from swiss was uploaded in July 2018. The snapshots were getting made on disk, but the script for uploading to their object storage had gotten broken. This PR fixes that.
swiss

Fix swiss backup

---

src/commcare_cloud/ansible/roles/ecryptfs/tasks/remove-tmp.yml

See error in https://travis-ci.org/dimagi/commcare-cloud/jobs/538792824 (Raw: https://api.travis-ci.org/v3/job/538792824/log.txt)
> ```
> TASK [Remove cron job] *********************************************************
> fatal: [10.0.0.196]: FAILED! => {"changed": false, "msg": "missing parameter(s) required by 'cron_file': user"}
> ```
Just slowly chipping away at the little broken things in the "prove-deploy" build until we have a clean full stack deploy

[pv-deploy] Fix task to remove cron file (possible ansible 2.8 change)

---

src/commcare_cloud/ansible/deploy_postgres.yml
src/commcare_cloud/ansible/letsencrypt_cert.yml
src/commcare_cloud/ansible/roles/bootstrap-machine/tasks/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/bionic_apt_installs.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/trusty_apt_installs.yml
src/commcare_cloud/ansible/roles/couchdb/tasks/main.yml
src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
src/commcare_cloud/ansible/roles/git/tasks/main.yml
src/commcare_cloud/ansible/roles/java/tasks/main.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml
src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml
src/commcare_cloud/ansible/roles/pg_backup/tasks/backup_pgbackrest.yml
src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
src/commcare_cloud/ansible/roles/python/tasks/main.yml
src/commcare_cloud/ansible/roles/ruby_install/tasks/main.yml
src/commcare_cloud/ansible/roles/shared_dir/tasks/install.yml
src/commcare_cloud/ansible/roles/zookeeper/tasks/main.yml

[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: "{{ item }}"`, please use `name:
['postgresql-{{ postgresql_version }}-plproxy', 'postgresql-contrib-{{ postgresql_version }}', 'postgresql-server-dev-{{ postgresql_version }}', 'python-docutils', 'libpq-dev', 'python-psycopg2', 'unzip']` and remove
the loop. This feature will be removed in version 2.11.

fix apt deprecation warnings

---

src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml

Change pg wal archive to 12 hours
icds
postgres
@snopoke We found this was 2160 minutes on the ICDS server and the server was almost out of space. Is there a reason that deviates from the 60 minutes in the codebase? We removed all logs from greater than six hours ago (720 min) manually. The cron task still has 2160 minutes

Update pg wal archive cron

---

environments/development/inventory.ini
environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/terraform.yml
src/commcare_cloud/ansible/deploy_citusdb.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/main.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_cordinator.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_worker.yml
src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer_hba.conf.j2
src/commcare_cloud/ansible/roles/postgresql_base/templates/pg_hba.conf.j2

`citus_cordinator` is misspelt and it's long
and harder to type than `citus_master`

rename citus_cordinator to citus_master

---

src/commcare_cloud/ansible/deploy_proxy.yml

Remove letsencrypt cert when fake_ssl_certs are used
none
proxy
this seemed unnecessary if letsencrypt isn't being used. I think that this could be further filtered for sites that have their ssl certs defined, though I'm not sure if we have any manually defined ssl certs anymore

Remove letsencrypt cert when fake_ssl_certs are used

---

src/commcare_cloud/ansible/roles/common_installs/tasks/bionic_apt_installs.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml
src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml

Node and NPM can't be co-installed with couchdb on bionic
none (future bionic monoliths)
couchdb2 requires libcurl4-openssl-dev which requires libssl-dev (happens to be version 1.1.0 in bioinic)
npm (through node-gyp and I think one other dependency) requires libssl1.0.0-dev which is incompatible with libssl-dev
installing npm forces libcurl4 to uninstall and I have no idea what effect that would have on couch. So as a resolution, I'm doing something similar to what we've been doing in trusty. Install from the official node source repository. When installing from that repository, it also includes npm so we don't need to install it separately package information: https://deb.nodesource.com/node_8.x/dists/bionic/main/binary-amd64/Packages

fix npm issues in bionic

---

src/commcare_cloud/ansible/roles/kafka/meta/main.yml
src/commcare_cloud/ansible/roles/kafka/tasks/main.yml

Removes kafkat
none
kafka
I brought this up on #devops but I don't think that anyone actually uses this. Ethan linked to a [kafka migration confluence page](https://confluence.dimagi.com/pages/viewpage.action?spaceKey=internal&title=Migrating+a+Kafka+cluster) from 2 years ago, but that is not how we've been migrating kafka recently (really haven't been migrating at all, just wiping it and installing a new server with no data)
I'm inclined to remove programs that aren't standard or documented in some workflow. If we want to document that migration in the commcare-cloud docs I'm happy to keep it, but it seems unnecessary for now

Remove kafkat

---

src/commcare_cloud/ansible/roles/rabbitmq/tasks/main.yml
src/commcare_cloud/environment/main.py

Removes rabbitmq as a hard requirement
none
rabbitmq/couchdb
As noted in https://dimagi-dev.atlassian.net/browse/SLTNS-192 the [erlang dependencies for couchdb2](https://github.com/dimagi/commcare-cloud/pull/2886/commits/24f83b6bca5aa08720c6d89c2a30ea97af41615c#diff-3402d5d869f77f376e1694a0fffa614aR8) are in conflict with the erlang versions needed to run rabbitmq on bionic, which means rabbitmq and couchdb cannot be run on the same server. 
My solution to this is to remove the requirement to have rabbitmq at all and instead use redis as the broker. This is our [default in commcare-hq](https://github.com/dimagi/commcare-hq/blob/master/settings.py#L512), though it does mean you can lose tasks if your tasks take too long and redis begins evicting keys. This should be …

remove rabbitmq requirement

---

environments/india/terraform.yml
src/commcare_cloud/terraform/modules/network/main.tf

Now that the migration is over, I rolled this out to shut down the AWS side of the VPN, and I manually powered off the gateway device in softlayer.
In order to apply the changes, I had to make a small change in the some .tf files for it to treat `external_routes  = []` properly, which previously errored. I made sure to test that there's no change before changing the value of `external_routes` here.
(It also occurred to me that the VPN is still up on production even though I think we're now finally not using it. For some period there were questions about whether some site were still getting routed through the proxy so I will double check before doing anything.)
india

Close india softlayer-to-AWS VPN tunnel

---

environments/echis/public.yml
environments/icds-cas/public.yml
environments/icds-new/public.yml
environments/india/public.yml
environments/pna/public.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/public.yml
environments/swiss/public.yml
src/commcare_cloud/ansible/group_vars/redis.yml

I'm having trouble finding what the benefits of setting this at all are over setting to 0 (which means as much memory as the underlying OS allows), but it's currently set very low and that seems like a plausible explanation for occasional evictions and generally low % of unfreeable memory (https://app.datadoghq.com/dashboard/nbz-bie-nip/host-groups?screenId=nbz-bie-nip&screenName=host-groups&abstraction_level=1&aggregate_up=false&display_timeline=false&from_ts=1546365120000&is_auto=false&live=false&page=0&per_page=30&tile_size=m&to_ts=1559926320000&tpl_var_environment=production&tpl_var_host_group=redis&use_date_happened=true).
production
It will require restarting the redis service, which may cause 500s while it blocks to restore the AOF into memory

Increase production redis_maxmemory to 16G (of 32G machine)

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/ansible/roles/redis/templates/monit.redis.j2
src/commcare_cloud/ansible/roles/shared_dir/tasks/cleanup_client.yml
src/commcare_cloud/ansible/roles/shared_dir/tasks/install.yml
src/commcare_cloud/ansible/roles/shared_dir/tasks/setup_client.yml
src/commcare_cloud/ansible/roles/shared_dir/tasks/setup_host.yml

Use systemctl to start/stop redis
staging & india
redis
the monit config for redis is currently broken as bionic uses systemd as a process manager and our redis library only installs /etc/init.d if systemd is not the process manager https://github.com/DavidWittman/ansible-redis/blob/cfe5d92a721b5b137bbbff20c57e038c5691c463/tasks/server.yml#L9-L22
monit status is currently green on staging and india because it uses the same pid file to check for status. if anyone tries monit start/stop on either of those environments it will fail
A follow up to this may be "do we need monit in a world where we have systemd?" or "how do we simplify our process managemnt?" @dannyroberts I think you'll have the most context on answering that question as part of plat-reliability

Fix redis monit

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

Celery is mostly powered just find on india, but experiences problems that it does not gracefully recover from when memory occasionally spikes and causes a process to be killed by the OOM killer. The last couple day's it's been causing the background_queue to get blocked until someone restarts it
india

Add swap to celery1-india to avoid OOMs

---

environments/production/terraform.yml

Eventually I will add 60 extra GB on all the es machines, but I wanted to test out increasing `es10` from `600 GB` to `660 GB`. I will merge this commit only once I make the changes on AWS. 
production
Updating `volume_size` in `terraform.yml`

Increase disk size on es10 (prod) from 600 to 660

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
src/commcare_cloud/commands/terraform/aws.py

Set `datavol_device` automatically on AWS envs based on `block_device` for the server in `terraform.yml`. This makes it so you just have to say in `terraform.yml` that a server should have a block device, and then it'll automatically be given the inventory variable it needs to make use of it.
Just aws envs

Set datavol_device automatically on AWS envs

---

environments/production/terraform.yml

Upgrading the remaining elastic search nodes to 660 GB in preparation for enabling Case Search index on pro + domains
production
`terraform.yml`

upgrade remaining ES nodes to 660 GB

---

src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml

When using systemd, on ubuntu 18.04 we need to enable supervisor to start on boot. 
I think this wasn't happening on 14.04 because upstart allows you to specify this directly: https://github.com/dimagi/commcare-cloud/blob/97b5ff49992e137131bca2dd66782f40574805fe/src/commcare_cloud/ansible/roles/supervisor/templates/supervisord.upstart.conf.j2#L3

Start supervisor on boot

---

src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
src/commcare_cloud/terraform/modules/postgresql/main.tf

A new version of `terraform-aws-modules/rds/aws` causes problems on a clean install, and the latest version of `terraform` cli is not compatible with our code currently. This encodes those two issues and keeps any errors more helpful.

Pin terraform cli version and rds module version

---

src/commcare_cloud/commands/ansible/ops_tool.py
src/commcare_cloud/commcare_cloud.py

I've written this temporarily a few times - decided to make it permanent.
Could probably use more work but it's all I need for now.
For ICDS this outputs:
```
Pooling  | Worker Queues                                    | Processes    | Concurrency  | Avg Concurrency per worker
-------  | -------------                                    | ---------    | -----------  | --------------------------
prefork  | background_queue,analytics_queue                 | 1            | 6            | 6           
prefork  | beat                                             | 1            | 1            | 1           
prefork  | case_rule_queue                                  | 1            | 2            | 2           
prefork  | celery,export_download_queue,case_import_queue   | 1            | 8 …
```

celery resource report

---

src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

Not sure if there's a more direct way to install the right package, but this works.
@dimagi/py3

Uninstall existing Python 3.6 so it can be replaced with 3.6.8 from PPA

---

src/commcare_cloud/ansible/deploy_commcarehq.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/formplayer.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/pillowtop.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/proxy_websockets.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/webworkers.yml

I started out wanting to just remove the supervisor conf for running this noop management command (in a loop over and over for the last 9 months!) https://github.com/dimagi/commcare-hq/blob/d260492c9655bddde714aa5d81e507c757e596c2/corehq/apps/reminders/management/commands/run_reminder_queue.py
In the process, I realized the code for removing supervisor conf files we no longer need was very broken, and fixed that all up. I tested that on india production it doesn't remove any files except for the one I'm removing in this PR (which it does remove).
all

Fix supervisor service management & Remove run_reminder_queue

---

src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/tasks/set_up_dbs.yml
src/commcare_cloud/ansible/roles/redis/tasks/main.yml

Adds retries to places where tasks were failing when certain services hadn't yet come up after the previous command.

Retry until things come up

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2

The default location for this pid file is /run/nginx.pid
/var/run is symlinked to /run on Ubuntu.
When running the whole install playbook, we run into this bug since when nginx
is installed it has the pid file set as /run/nginx.pid;
https://trac.nginx.org/nginx/ticket/796
If the `deploy-proxy` playbook is run on environments where nginx is already existing, reloading nginx might fail after this change. `service nginx stop` and `service nginx start` is required to be run. 
All

Don't change nginx pid location to the same file

---

src/commcare_cloud/terraform/modules/network/main.tf
src/commcare_cloud/terraform/modules/network/outputs.tf
src/commcare_cloud/terraform/modules/server/main.tf

These two otherwise unrelated issues both were causing meaningless terraform diffs—diffs that showed up again even immediately after cleanly applying. This PR gets rid of those diffs, and other than removing unneeded resources/settings doesn't make any meaningful changes to our environments.

Fix meaningless terraform diffs

---

environments/production/terraform.yml

This reflects changes I made manually in the AWS console to the production couch cluster:
- remove old Trusty nodes `couch{3,4,5,7,8,9}` (were already stopped)
- remove broken Bionic nodes `couch{10,11}` (were already stopped)
- increase disk from 3T to 4T on `couch{12,13,14,15}`
Note that couch15 is currently "part of the couchdb cluster" but has no shards assigned to it and thus doesn't serve any reads or receive any writes. It is an extra free node we created during firefighting yesterday to test operations on and provide some slack in case of the unknown, but I will likely remove on Monday if there are no further issues.
production

Update production terraform.yml to final couchdb cluster state

---

docs/commcare-cloud/deploy.md

Updates the deploy documentation for clarity. 
I removed the `hotfix` instructions as I think those are internal only (no one else can push to the repo), and it is documented internally here: https://confluence.dimagi.com/display/commcarehq/Deploy+Process
I'm going to self-merge this as we need to send it externally on Monday morning, but I'd still love your feedback, and will make updates in a separate PR.

Update deploy documentation

---

docs/services/kafka.md

Note that kafka migrations can occur online
none
kafka
I went through http://kafka.apache.org/082/documentation.html#basic_ops_cluster_expansion a few times to verify that this is the case and I've since rebalanced all of our topics (in batches) across all kafka servers while services were online and no errors came up

Change note about online kafka migration

---

environments/production/public.yml
src/commcare_cloud/ansible/roles/couchdb2/vars/main.yml

Extend the time window during which compaction can happen from 1pm-5:30pm ET to 1pm-1am. In addition, compact at a lower fragmentation threshold. This will allow us to stay at an overall disk usage in steady state.
production

Compact production CouchDB more aggressively

---

docs/setup/new_environment.md
src/commcare_cloud/fab/config.example.py

Makes local setup a bit easier. @proteusvacuum @dannyroberts Does this seem like a reasonable default?

Default GITHUB_APIKEY=None

---

src/commcare_cloud/ansible/deploy_db.yml
src/commcare_cloud/ansible/roles/backups/tasks/main.yml
src/commcare_cloud/ansible/roles/backups/templates/check_s3_backup.py.j2

it now checks for a recent daily and weekly backup, prints out whether
it found them, and exits with -1 if there isn't a recent daily backup or
there isn't a recent weekly backup
I'm not sure what the most sensical way to hook this check up to a datadog monitor is, but I figured I'd start by fixing the broken script that was clearly meant to do something like what I'm trying to do

Fix check_s3_backup.py script and change its check

---

src/commcare_cloud/ansible/letsencrypt_cert.yml

This fixes this letsencrypt ansible playbook for new versions of ansible

Ansible cron module now requires user

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2

Add http referer to nginx timing logs
all
proxy
We include this in the rt_cache logs already, but our datadog parser currently only parses the timing logs.
Companion to https://github.com/dimagi/datadog-parsers/pull/33

Add http referer to nginx timing logs

---

environments/icds-cas/inventory/commcare.csv

Convert half of the `hq_webworkers` to `mobile_webworkers`
`icds`
Based on metrics from the last day the `hq_webworkers` usage stays below 10% while the `mobile_webworkers` is up at 80-90%:

assign more webworkers to mobile

---

environments/production/terraform.yml

Reverts dimagi/commcare-cloud#2898
I'll roll this out once I get the go ahead from @esoergel (or else close in favor of something else).
The three machines `celery{0,2,3}-production` haven't had memory peaks since I think Jun 12: https://app.datadoghq.com/dashboard/nbz-bie-nip/host-groups?abstraction_level=1&aggregate_up=false&display_timeline=false&from_ts=1557154920000&is_auto=false&live=false&page=0&per_page=30&tile_size=m&to_ts=1562338920000&tpl_var_environment=production&tpl_var_host_group=celery&use_date_happened=true&fullscreen_widget=3806476073669242&fullscreen_section=overview

Revert "Increase production celery resources for async_restore_queue"

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/pillowtop.yml

I noticed that this is running on every pillow machine.

only run one instance of pillow retry queue

---

environments/production/app-processes.yml

We're running into this issue when running prod webworkers in python 3:
https://github.com/DataDog/dd-trace-py/issues/373#issuecomment-485607536

remove ddtrace from prod webworkers until it is upgraded

---

environments/production/app-processes.yml

High CPU usage was noted for webworkers, [choking to 100% at all times](https://app.datadoghq.com/dashboard/g9s-pw6-tpg/hq-vitals?from_ts=1562911302662&fullscreen_section=overview&fullscreen_widget=379741435&live=true&tile_size=m&to_ts=1562925702662).
A quick fix was to reduce the concurrency to half.
production
This was deployed
This looks related to python3 migration since the CPU has been high for last 2-3 days that coincides with the migration. A better change might be to add more CPUs.

reduce factor to 1

---

src/commcare_cloud/ansible/roles/common/tasks/main.yml

UMASK determines the default file permissions. New ICDS machines were being setup with stricter default permissions which was breaking deploy. This sets them back to debian defaults

set umask to 022

---

src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/schemas/app_processes.py

Some commands apply limits to the inventory before calling
other commands. This change ignores those limits in places
that expect all hosts to be returned from the inventory.

ignore inventory limits when getting hosts

---

environments/icds-cas/app-processes.yml

I think the thread_local we are using to override db settings is persisting across tasks that share workers. This will ensure that each task gets a fresh worker. The added overheaded of spinning up a new worker should be insignificant given how long each task runs.

do not reuse celery workers for agg

---

src/commcare_cloud/ansible/roles/nginx/templates/site.j2
src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Allow first time syncs to pass through without rate limits
icds
nginx
based off my previous work here: https://github.com/dimagi/commcare-cloud/pull/953
As currently implemented it would not rate limit when `X-CommCareHQ-LastSyncToken` is not passed. If the header exists, it falls back to rate limiting based on `$server_name`

Limit based on mobile header for synclogs

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Following up on https://github.com/dimagi/commcare-cloud/pull/3037. Spoke with @ctsims about this method
icds
nginx
With this PR the behavior will be:
Incremental syncs will be limited to 15 r/s with burst of 10 requests
Non-incremental syncs will be subject to 15 r/s, but have a burst of 100 requests.
To receive a 412 (if we lost the user's synclog) they must be able to get through the first rate limiting. If they get into the 412 they should be able to get into the burst of 90 requests in the non-incremental sync queue on a retry.

Better prioritization of non-incremental syncs

---

environments/production/public.yml

Because of https://github.com/dimagi/commcare-cloud/pull/2930 and https://github.com/dimagi/commcare-cloud/pull/3018, hq_webworkers have been running with the ddtrace django app but without being run by `run-ddtrace`. I think you need both for ddtrace to be effective.
There's some small chance in my mind that running without run-ddtrace but with the ddtrace django app causes some kind of issue under load resulting in what we saw earlier today—because we were seeing high CPU only on hq_webworkers—but I'm not that hopeful, seems not that likely.
production
To roll out

Remove ddtrace app from production LOCAL_APPS for webworkers

---

environments/icds-cas/inventory/postgresql.csv

This was introduced when we had to [swap with standby](https://github.com/dimagi/commcare-cloud/pull/3019/files). We should make sure to update TCL hostnames correctly always
@Rohit25negi

fix TCL hostname for synclogdb

---

src/commcare_cloud/ansible/roles/citusdb/tasks/setup_cordinator.yml

Exclude hosts in `pg_standby` group when adding workers to the master.

don't add standby nodes to master

---

docs/commcare-cloud/basics.md

Fix after-reboot command in basics. It requires an inventory group, so I left the default to `all` since there's already a `--limit` already in the command
none

Fix after-reboot command in basics

---

src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_pillowtop.conf.j2

Increases supervisor stop timeout for for pillows to allow current batch to finish. I was sort of guessing on this one since our timing is done in buckets and those end at "over 10s". However, this should have no effect on anything other than UCR pillows and 2 minutes seemed long enough to be safe but short enough not to cause issues, we can fine tune as appropriate.
Relevant HQ PR
https://github.com/dimagi/commcare-hq/pull/24947

increase pillow stop time

---

src/commcare_cloud/ansible/deploy_commcarehq.yml
src/commcare_cloud/ansible/roles/couchdb/tasks/main.yml
src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml
src/commcare_cloud/ansible/roles/ksplice/tasks/main.yml
src/commcare_cloud/ansible/roles/pg_backup/tasks/backup_plain.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/main.yml

[DEPRECATION WARNING]: evaluating XXX as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future.

fix 'bare variable' deprecation warning

---

changelog/0023-upgrade-to-python-3.yml
docs/changelog/0023-upgrade-to-python-3.md

Add note about running django-manage commands in python 3
none
changelog
This is optional as we're already running services in python 3 when the other command is set.

Add note about running django-manage commands in python 3

---

src/commcare_cloud/ansible/roles/bootstrap-users/tasks/main.yml

Replacement of https://github.com/dimagi/commcare-cloud/pull/3060
Ubuntu 18 defaults to 45 days validity for passwords.

clear password expiry

---

environments/icds-cas/public.yml

Reverts https://github.com/dimagi/commcare-cloud/pull/2216 which was only intended to be for a short time
icds
kafka
This should result in roughly half disk space being used.
This does require brief downtime to change because it requires a kafka restart, though I am going to investigate using replicas so that it would not require dowtime

Use default kafka log retention for icds

---

.travis/environments/travis/postgresql.yml
commcare-cloud-bootstrap/environment/postgresql.yml
environments/development/postgresql.yml
environments/enikshay-reference/postgresql.yml
environments/icds-cas/postgresql.yml
src/commcare_cloud/ansible/roles/postgresql_base/defaults/main.yml

This will allow queries on standby nodes to last up to 3 min before being cancelled.

set postgresql_max_standby_delay for ICDS

---

src/commcare_cloud/ansible/roles/airflow/templates/airflow.cfg.j2

This should fix airflow's ability to send email (which I tested using airflow's send_email method). It's not clear yet whether airflow is triggering that method at all on failure, which I am investigating.
@calellowitz @snopoke

Airflow config; remove quotes, escape special chars

---

environments/icds-cas/app-processes.yml
src/commcare_cloud/environment/schemas/app_processes.py

Customise celery blockage thresholds for ICDS.
These get used to determine celery uptime. I'd like to configure these appropriately for ICDS so that we can get some useful uptime metrics.

set blockage_thresholds

---

src/commcare_cloud/ansible/roles/couchdb2/templates/extras.ini.j2

Removes a known performance bottleneck in Couch 2.1. Its the default behavior in 2.3
https://github.com/apache/couchdb/pull/1627
icds
couchdb

Run a rexi server on every node

---

environments/icds-cas/app-processes.yml

Max tasks per child and high task turnover do not play nicely together. It is also no longer necessary due to https://github.com/dimagi/commcare-hq/pull/24910

remove max_tasks_per_child

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Device logs make up 15% of overall submissions on ICDS and at peak times we get as much as 30 per second. This constitutes a significant portion of requests.
We are already dumping device logs at the Django level but only after we've done various amounts of processing on them (as well as all the overhead that comes from login etc).
This PR adds an nginx location which will accept any request and return a 201 response with the OpenRosa response body.
Setting the `log_receiver_url` in the app will direct device logs to this endpoint.
Note that we have also set `logenabled=no` in the app config which should disable sending device logs at all but this also requires an LTS update which take a long time to roll out.
https://dimagi-dev.atlassian.net/browse/IIO-321
ICDS

nginx location for dumping devicelogs

---

environments/production/app-processes.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml
src/commcare_cloud/commands/ansible/ops_tool.py
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/schemas/app_processes.py

(Builds off https://github.com/dimagi/commcare-cloud/pull/3120 even though they seem somewhat unrelated.)
Rearrange produciton celery
- have most queues processed in triplicate, symmetrically
- have all non-queue celery stuff and a few non-redundant processors run on one another machine
production

Rearrange production celery bigtime

---

src/commcare_cloud/terraform/modules/openvpn/variables.tf

This previous filter recently started coming up empty. It doesn't matter at all for existing environments. For a new one, if I'm wrong and there are other AMIs for this owner, then that'll become apparent pretty quickly. (Also as a practical note, there are no plans to set up a new AWS environment anytime soon.)

Clear filter for "OpenVPN Access Server 2.6.1"

---

src/commcare_cloud/commands/ansible/ops_tool.py

And improve the way it looks when interpreted as markdown.
Here's the new output (for production) directly pasted (which github renders as markdown):
Pooling  | Worker Queues                   | Processes    | Concurrency  | Avg Concurrency per worker | Worker Hosts
-------  | -------------                   | ---------    | -----------  | -------------------------- | ------------
gevent   | `analytics_queue`               | 1            | 10           | 10           | celery9
prefork  | `async_restore_queue`           | 3            | 24           | 8            | celery10,celery7,celery9
prefork  | `background_queue`              | 1            | 8            | 8            | celery9
prefork  | `beat`                          | 1            | 1            | 1            | celery12 …

Add "Worker Hosts" to celery-resource-report

---

src/commcare_cloud/ansible/roles/datadog/tasks/main.yml

Specify dd-agent as owner for datadog files. Datadog wasn't starting on new ICDS couch machines because these were owned by root
all
datadog

Fix datadog ownership

---

src/commcare_cloud/ansible/roles/bootstrap-users/tasks/remove_users.yml
src/commcare_cloud/ansible/roles/bootstrap-users/templates/sudoers.j2
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

This changes the last accidental holdouts to use py3:
- django-manage
- the sudoers file (which includes the virtualenv python and pip as a whitelisted commands)
all

Make django-manage and sudoers use py3

---

docs/commcare-cloud/backup.md
environments/swiss/public.yml
src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/backups/tasks/main.yml
src/commcare_cloud/ansible/roles/backups/tasks/set_up_check_s3_backups.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/pg_backup/tasks/backup.yml
src/commcare_cloud/ansible/roles/pg_backup/tasks/backup_plain.yml

This we do daily backups on swiss but if they fail it's pretty silent. This adds a check that looks for the presence of a recent daily and weekly backup (just by matching filename) in s3, on a daily basis, and emails out if there's not.
swiss

Run s3 backup checks daily on swiss

---

src/commcare_cloud/ansible/roles/bootstrap-machine/tasks/main.yml
src/commcare_cloud/ansible/roles/common/tasks/main.yml

Prior to this the umask would only take effect after next login. It was also set after common installs were run making commands like `virtualenv-clone` fail.

set umask during bootrap and set for current session

---

src/commcare_cloud/fab/operations/staticfiles.py

Delete yaml file instead of py when force updating staticfiles.
This was changed ~week ago and may mean that hotfix + force_update_static has been broken since then https://github.com/dimagi/commcare-hq/pull/25027
all

Delete yaml file instead of py.

---

src/commcare_cloud/fab/operations/release.py

I'm not sure why this started failing but I encountered it while setting up new VMs on ICDS. When executed inside the `with cd()` context the returned list is empty (despite actually executing the command to list the submodules).
I did not debug any further.

 get submodule list before entering 'cd' context

---

src/commcare_cloud/ansible/roles/ansible-control/tasks/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

New Ubuntu VMs on Vmware have umask set to 0002 which makes pip installs unusable by non-privileged users. Setting the umask during install should fix that.

add umask for pip installs

---

src/commcare_cloud/ansible/roles/pgbouncer/tasks/main.yml

This was missing since pgbouncer was split out from the postgres role
pgbouncer
Without this pgbouncer get's restarted on every run of the role.

register no_tags in pgbouncer role

---

src/commcare_cloud/ansible/deploy_proxy.yml
src/commcare_cloud/ansible/roles/nginx/handlers/main.yml
src/commcare_cloud/ansible/roles/nginx/tasks/install.yml
src/commcare_cloud/ansible/roles/nginx/vars/main.yml

This should address CVE-2019-9511, CVE-2019-9513, CVE-2019-9516:
https://www.nginx.com/blog/nginx-updates-mitigate-august-2019-http-2-vulnerabilities/
all
- Security Pull Request
There will be a blip of downtime as we replace the nginx server, so will be worth coordinating the rollout time
nginx
It took a little trial and error to figure out how to install the newer versions of nginx, but I ended up following https://www.linuxbabe.com/ubuntu/install-nginx-latest-version-ubuntu-18-04 on staging, first manually as I was figuring it out, and then ported it to ansible, and tested it runs cleanly on the (already upgraded) staging proxy. I haven't yet tested its ability to upgrade from scratch, but I'll do so before rolling it out on other environments

Upgrade to nginx 1.17.3

---

docs/changelog/0004-add-analytics-queue.md
docs/changelog/0005-support-multiple-kafak-brokers.md
docs/changelog/0006-new-case-importer-celery-queue.md
docs/changelog/0007-reorganize-pillows.md
docs/changelog/0008-blob-metadata-part-1.md
docs/changelog/0009-blob-metadata-part-2.md
docs/changelog/0012-generalize-load-case-from-fixture.md
docs/changelog/0015-separate-celery-datadog-http-check.md
docs/changelog/0016-invoke-celery-directly.md
docs/changelog/0019-remove-celery-results-backend-from-localsettings.md
docs/changelog/0023-upgrade-to-python-3.md
src/commcare_cloud/manage_commcare_cloud/changelog.md.j2

I noticed this potential confusion in https://forum.dimagi.com/t/python-2-deprecation-notice-30-days-to-upgrade/6699/7 (though it may not have been the source of their question).
none

Fix {min,max}_commcare_version text in changelog entries

---

docs/setup/new_environment.md

In response to https://forum.dimagi.com/t/python-2-deprecation-notice-30-days-to-upgrade/6699/9 I noticed our new_environment docs don't tell you to run it with `-e 'CCHQ_IS_FRESH_INSTALL=1'` on the first time setup, but I think that's just a mistake. A couple lines below it is included in the retry command.
new setups

Add -e 'CCHQ_IS_FRESH_INSTALL=1' to first time setup

---

src/commcare_cloud/ansible/roles/nginx/tasks/certs.yml

Allow specifying nginx certs explicitly.
This will support 3rd parties who already have certificates which they wish to use.

restore tasks for custom certs

---

src/commcare_cloud/environment/schemas/postgresql.py

Since citus hosts aren't part of the `postgresql` group they DBs assigned to them were not getting included in the `by_host` output.
* icds
* PostgreSQL, CitusDB, pgbouncer
This affects the the `pgbouncer.ini` file

include citus_master hosts in PG hosts

---

environments/icds-cas/public.yml

This has moved to a pillow on ICDS so once the pillow has caught up we can disable the save via celery.
ICDS
See https://github.com/dimagi/commcare-cloud/pull/3100, https://github.com/dimagi/commcare-hq/pull/24973

turn off case messaging sync on save

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

This hasn't officially been the `[django_manage]` machine since early July, but I forgot to remove the machine. In this case I also forgot to _stop_ it. The extra cost we incurred isn't crazy (~$80) but still worth doing.
production

Remove djangomanage0-production

---

src/commcare_cloud/ansible/roles/bootstrap-users/tasks/main.yml

This fixes --first-time deploy, which I think was first broken in https://github.com/dimagi/commcare-cloud/pull/3064. I haven't re-run this on a fresh install, but I think the premise is correct
all

Fix bootstrap-users by making the suoders file edit the last task

---

src/commcare_cloud/commands/ansible/helpers.py
src/commcare_cloud/commands/ansible/service.py
tests/test_service.py

Optimise the 'supervisor' based service commands to run more commands in parallel.
Service commands for:
* pillowtop
* celery
When starting / stopping / restarting celery and pillowtop processes a separate ansible command is run for each host (usually) in serial. This can be a very slow process.
Since we generally have celery and pillow processes isolated to dedicated VMs it should be possible to operate on them all at once rather than per host.
This change should make running operations like this perform just a single ansible play:
```
cchq <env> service pillowtop restart
cchq <env> service celery stop
``` 
Note: this builds on https://github.com/dimagi/commcare-cloud/pull/3169

optimize service operations

---

environments/icds-cas/app-processes.yml

This reverts commit 79e9a535d8bd181bbab795fa37ab5941b99c0f59.
Reverted this to try and get through the pillow error queue faster but it turns out the slow part is getting the errors into the queue - not the processing side.

Revert "Revert "Add more case messaging pillows""

---

environments/production/terraform.yml

Terminating trusty os(ubuntu 14.04) HQ and Mobile web workers in a production environment

Terminating trusty os(ubuntu 14.04) HQ and Mobile Web workers in a production environment

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/formplayer.py
src/commcare_cloud/fab/operations/supervisor.py

by removing it from the main deploy
Web Apps and App Preview break for a few minutes every time we deploy, which is daily on prod. We do fairly little active development on formplayer these days, so this will have little practical day-to-day consequences, and I think it's not terrible from a "philosophical" perspective either. So I propose we just don't deploy formplayer unless we explicitly want to, thereby removing 90% of the damage this flaw in formplayer architecture causes.
all

Make fab deploy_formplayer the only way to deploy formplayer

---

src/commcare_cloud/commands/ansible/helpers.py

Small fix to https://github.com/dimagi/commcare-cloud/pull/3170.
general
Fixes
```
(ccc) francine:commcare-cloud droberts$ cchq production service celery restart --only=repeat_record_queue
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting
File "/Users/droberts/.virtualenvs/ccc/bin/cchq", line 11, in <module>
load_entry_point('commcare-cloud', 'console_scripts', 'cchq')()
File "/Users/droberts/dimagi/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 168, in main
exit_code = call_commcare_cloud()
File "/Users/droberts/dimagi/commcare-cloud/src/commcare_cloud/commcare_cloud.py", line 159, in call_commcare_cloud
exit_code = commands[args.command].run(args, unknown_args)
File …
```

Fix _get_simple_processes for missing groups

---

src/commcare_cloud/fab/fabfile.py

My temporary fix is to just restart formplayer after deploy,
even though it wasnt actually updated. And since there's a restart there
will still be the 1-2m of formplayer downtime that we're "used" to. The
longer term fix will be to move the formplayer directory out from inside
the commcare-hq code directory so that deploying commcare doesn't change
the file pointed to by the formplayer jar path that supervisor uses to run the jar.
The serious formplayer issue was I believe introduced by https://github.com/dimagi/commcare-cloud/pull/3174 (though we had seen it pop up very occasionally before—in retrospect possibly the rare time when we deployed and formplayer wasn't restarted). I think that PR is still overall in the right direction, so rather than revert it, I'm going to just put in the …

Fix serious formplayer issue after deploy with stop-gap measure

---

src/commcare_cloud/fab/operations/release.py

Since we use pip-compile to generate the requirements files and that
'prod-requirements' includes 'requirements' there is no need to run pip install with both. It can cause
problems if the same dependency exists in both but with different versions.
deploy

only install from a single requirements file

---

src/commcare_cloud/commcare_cloud.py

I'm kind of embarrassed now that I didn't make this PR sooner. This cuts the setup time in half when you're using the `--control` flag; the first `~/init-ansible` here was just being used to get into the git directory, and it's a silly and expensive way to do that.

Make --control flag faster by doing setup just once

---

src/commcare_cloud/ansible/roles/nginx/tasks/install.yml

As @emord noted here https://github.com/dimagi/commcare-cloud/pull/3140#issuecomment-523080936, the new nginx packages we're using don't create sites-enabled and sites-available by themselves

Fix install nginx

---

src/commcare_cloud/ansible/roles/bootstrap-users/tasks/remove_users.yml

Check if a user exists before looking for processes to kill
users
This will prevent errors from `ps` by not looking for processes belonging to users to don't exist

check user exists before killing processes

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/sentry.py
src/commcare_cloud/commcare_cloud.py

A utility command to export Sentry events.
I've found this useful on a few occasions.
Sentry
Example usage:
```
cchq icds export-sentry-events --api-key XXX --query MissingFormXml --start 2019-08-20T08:50:00 --end 2019-08-20T09:45:00 --project-id 12345 > events.txt
```

export sentry events command

---

src/commcare_cloud/fab/operations/formplayer.py
src/commcare_cloud/fab/operations/release.py

As far as I can tell formplayer releases continue to accumulate and are copied from release to release.
Staging had 60GB of formplayer releases.
Deploy
This will remove all formplayer releases except the current one and the one prior to that.

clean formplayer releases

---

changelog/0027-fix-python3-virtualenv.yml
docs/changelog/0027-fix-python3-virtualenv.md
src/commcare_cloud/manage_commcare_cloud/make_changelog.py

{{ deploy_env }} in markdown was being rendered as an empty string
none

Fix the way `{{` is rendered in the docs

---

environments/staging/public.yml

Adds the following to staging's localsettings so that QA can carry out changes related to requirejs updates for the login and password pages.
```
OBFUSCATE_PASSWORD_FOR_NIC_COMPLIANCE: True
ENABLE_DRACONIAN_SECURITY_FEATURES: yes
```
staging
localsettings on staging

enable obfuscate passwords and draconian security on staging

---

environments/production/terraform.yml

As per https://dimagi-dev.atlassian.net/browse/PLAT-188
As shown in https://aws.amazon.com/ec2/pricing/on-demand/, this will take the celery machines from
- 8 variable-perf CPU and 32GB RAM to
- 8 consistent-perf CPU and 64GB RAM
For celery12 (which runs side processes) I'm doing the analogous thing but down one size.
This can be rolled out one machine at a time, so no downtime expected (but restart alerts expected). Restarting celery 12 will temporarily interrupt beat, queuing processes, etc., but I think not to an extent that any user will notice
production
Celery

Increase production celery memory

---

scripts/example-apply-terraform-rolling-restart.sh
scripts/example-apply-terraform-to-single-server-and-bring-back-up.sh
scripts/example-terraform-resize-disk.sh

Without -r, read -s will strip backspaces from the password you enter
This only effects some example scripts I use to glue together some operations

Use read -r arg to respect backspaces in input

---

environments/icds-cas/public.yml

LFU is relatively new eviction model that targets keys
which are used less frequently than others. This may
improve our cache usage. It also gives us access to the
`--hotkeys` command which lists keys that are most frequently
accessed.
https://redis.io/topics/lru-cache#the-new-lfu-mode
ICDS
Redis

change redis to use LFU

---

environments/staging/public.yml

temporarily enables the ICDS login page on staging so that we can test the requirejs changes to login js
staging
localsettings

temporarily turn on ICDS login pages on staging

---

changelog/0024-define-management-commands.yml
changelog/0025-rename-management-commands.yml
changelog/0026-move-remaining-management-commands.yml
docs/changelog/0024-define-management-commands.md
docs/changelog/0025-rename-management-commands.md
docs/changelog/0026-move-remaining-management-commands.md

I think even though these are supposed to be roughly no-op, it makes sense to tell people to update supervisor confs right after. Related to https://dimagi-dev.atlassian.net/browse/PLAT-209
none

Add command to roll out supervisor changes to end of recent changelog entries

---

environments/icds-cas/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

This sets `ICDS_USE_CITUS` in localsettings, which causes the dashboard to default to citus
ICDS

set icds_use_citus

---

environments/production/terraform.yml

Terminating old trusty Elasticsearch instances on production environment

Terminating old trusty Elasticsearch instances on production environment

---

src/commcare_cloud/ansible/roles/backups/tasks/set_up_check_s3_backups.yml
src/commcare_cloud/ansible/roles/backups/templates/check_s3_backup.py.j2

There were some issues with the backup check, the most major of which was a typo in the line that was meant to email the results (but instead just echo something).
mostly just swiss

Fix swiss backup checks

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

Limit the bandwidth usage per request for multimedia downloads. The limit will only kick in after the first 100k has been sent which mean it should only get applied to larger files like videos.
This works in combination with the rate limit to limit the bandwidth usage. 
At this rate a 12M file will take ~30s to download.
Setting the rate limit to 50r/s means our max bandwith usage for MM would be 24MiB/s.
ICDS
nginx
We could also add `limit_rate_after 100k` to only limit larger files but that makes it much harder to know what our max usage will be.

limit MM download bandwidth to 500k per request

---

src/commcare_cloud/ansible/roles/nginx/vars/cas_ssl.yml

App download caching has been broken for a long time (since `username` was added as a request param): https://github.com/dimagi/commcare-android/pull/1747
This changes the cache key to exclude username. 
ICDS
nginx cache
This takes a the approach or stripping out the username but leaving the rest of the URL intact. I felt this was safer than only using specific parts of the URI in the key (https://github.com/dimagi/commcare-cloud/commit/566ed45d8c6d9e3358e6fc8fb225965eef82f56a) since if the URI changes the cache may not work but at least we won't be serving incorrect resources.
I used https://github.com/nginxinc/NGINX-Demos/tree/master/nginx-regex-tester to test the regexes.

exclude username from app download cache key

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/deploy.py

Following up on https://github.com/dimagi/commcare-cloud/pull/3174. I realized we currently didn't have an "official" way to deploy formplayer ever since pulling out formplayer_deploy from normal deploy and shortly after switching to the deploy command.
Normal deploy includes a reminder to deploy formplayer occasionally with
the command to do so.
Normal deploy:
Formplayer deploy:
all
Deploy (formplayer)

Add interface for deploying formplayer

---

src/commcare_cloud/ansible/roles/haproxy/templates/service.j2
src/commcare_cloud/ansible/roles/rabbitmq/tasks/config-cluster.yml

When selecting a var from a different host you must use the var name for that host.

fix references to vars from other hosts

---

environments/staging/public.yml

adds `STATIC_ROOT` back to localsettings on staging as it was before
staging
localsettings

add static root back in on staging localsettings

---

src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2

This wasn't caught because I'd done a few iterations on staging and by chance there were config files in the place it was looking. This updates it to look for the config files in the correct place.
all

Fix issue where new formplayer deploy leaves it unable to find config files

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/formplayer.py
src/commcare_cloud/fab/operations/supervisor.py

I think we're finally ready to stop restarting formplayer during normal deploy. This PR will continuing restarting it as long as it detects that formplayer is running from the old release location (in which case the restart is necessary). Any env that has had `cchq <env> deploy formplayer` run on it since 16 hours ago or so will have formplayer running from the new location, and will not have formplayer restarted on normal deploys after this PR is merged.
I've tested the old/new formplayer location detection logic on staging (new) and india (old), and it worked as intended.
all
- Change/Bugfix Pull Request
formplayer

Stop restarting formplayer during normal deploy

---

src/commcare_cloud/fab/operations/release.py

Formplayer was moved to ansible https://github.com/dimagi/commcare-cloud/pull/3268 and so these properties do not exist on the enviroments using the new format
all

Fix formplayer deploy

---

environments/production/terraform.yml

Terminating trusty RabbitMQ and formplayer Instances on prod environment

Terminating trusty RabbitMQ and formplayer Instances on prod environment

---

control/init.sh

This makes it take a little longer to run, but fixes tests. Next step is
to debug the "wait" that causes the timeout.
I've started debugging here https://github.com/dimagi/commcare-cloud/pull/3288, but didn't get to a better fix fast enough and all the builds have been failing for a week now

Fix travis timeout by removing concurrency from control/init.sh

---

control/init.sh

Fixes the travis build. This fixes the same issue https://github.com/dimagi/commcare-cloud/pull/3294 did but in a better way.
This adds back the minor concurrency to `control/init.sh`, while skipping background processes not stated by the script.

Wait only for specific processes in init script to fix travis timeout

---

src/commcare_cloud/ansible/roles/datadog/tasks/add_integrations.yml

Fix datadog_integration_airflow error when it's undefined. `|bool` doesn't accept an undefined variable, so I think this was the intention to start with.

Fix datadog_integration_airflow error when undefined

---

environments/production/terraform.yml

Terminating trusty couchproxy0 and pgbouncer0 servers on prod env

Terminating trusty couchproxy0 and pgbouncer0 servers on prod env 

---

environments/production/terraform.yml

We are currently underusing our m5 RIs, so this is just cost optimization. Doubles RAM and keeps number of vCPU the same (but reduces standardized CPU performance by about 5.8%).
production

Change djangomanage1-production c5 => m5

---

src/commcare_cloud/commands/terraform/templates/terraform.tf.j2

Ṫerraform refuses to work with shared state files created by a future version.
Today I ran into this when my terraform refused to operate because the shared
state file was created with terraform 0.11.15. My first attempt to solve
was to install 0.11.15, but this proved difficult, as my current method
of installing terraform on my Mac, Homebrew, did not recognize this version.
On terraform's own versions page https://releases.hashicorp.com/terraform/
0.11.15 is listed as "0.11.15-oci", which is nonstandard version naming
and the terraform github repo does not list 0.11.15 as a release at all.
It gives me no pleasure to force those with 0.11.15 to downgrade,
but it appears to be our best option here, given that Mac/Homebrew
is a common way to handle installs on our team, and the strange …

Require terraform < 0.11.15

---

src/commcare_cloud/ansible/setup_pg_logical_replication.yml

https://sentry.io/organizations/dimagi/issues/1260738676/?referrer=slack
Context: https://github.com/2ndQuadrant/pglogical/issues/176
Occurred when deploying https://github.com/dimagi/commcare-hq/pull/25569/files#diff-09066e20e199c5840c772df7e9c996d9
We need to grant usage permissions to use DDL commands after setting up a pglogical subscriber. I did this manually (ex: `commcare-cloud icds run-shell-command pgshard20 -b --become-user postgres "psql -c 'GRANT USAGE ON SCHEMA pglogical TO hqweb2postgres;' commcarehq_p20 ")` for ICDS's databases, but I'm incorporating this in pglogical setup. No other environment has used pglogical to split shards, so no other cleanup is necessary.
icds
postgres

Grant usage permissions to commcare user

---

src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/datadog/templates/postgres.yaml.j2

This adds a gauge for PG databases for number of locks that are blocking queries. I've used this quite a bit when changing the dashboard agg and also understanding our recent pillow issues.
I think it would be useful to have as a metric to better understand how this fluctuates throughout the day. I'm not sure how useful it will be to non-ICDS environments, but it doesn't seem like it would hurt
all
postgres

Add gauge for number of locks not granted

---

.travis/spec.yml

It benefits us to limit the number of different instance classes we use, because then we have more flexibility with our discount purchases. Just happened to come across this and it seemed like a small thing worth changing.

Use t3 instead of t2 for "prove-deploy" build
