dimagi/commcare-cloud

environments/production/terraform.yml

Changing the InstanceType for pgshards on production enviornment

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

Followup to https://github.com/dimagi/commcare-cloud/pull/4250

Add comment about managing ManualDenyList IPs in AWS console

---

control/init.sh
src/commcare_cloud/manage_commcare_cloud/install.py
src/commcare_cloud/manage_commcare_cloud/manage_commcare_cloud.py

all, but only affects developers running deploy

Make control/init.sh less chatty

---

environments/production/terraform.yml

spike in `DefaultChangeFeedPillow`
production

Increase memory on pillow1-production

---

environments/production/terraform.yml

Increasing the storage for pgshards and CouchDb data nodes

---

environments/production/terraform.yml

to see if it helps with the midnight UTC memory spikes
likely not a long term solution
production

Increase size of production mobile_webworkers

---

environments/production/terraform.yml

Double RAM on pgbouncer to get out of OOM cycle

---

environments/production/terraform.yml

Not sure whether the logging changes are sufficient by themselves; still figuring out how they work.
Size changes already applied, params are applied and pending reboot.
production

Increase production pgshard sizes and add better logging

---

src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2

This was applied on production and india already (manually in the console) but this PR brings terraform into line with it
production

Give RDS instnaces enhanced monitoring with 60s interval

---

src/commcare_cloud/terraform/modules/postgresql/main.tf

Enable RDS logging to cloudwatch

---

environments/india/public.yml
environments/swiss/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11456
production

add saas reporting email to both swiss and india envs

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://github.com/dimagi/commcare-hq/pull/28691
ICDS

allow passing IGNORE_ALL_DEMO_USER_SUBMISSIONS

---

src/commcare_cloud/ansible/roles/citusdb/tasks/main.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_cordinator.yml
src/commcare_cloud/ansible/roles/citusdb/tasks/setup_worker.yml

Refactor to remove duplication

remove duplication

---

environments/production/terraform.yml

Changing the InstanceType for prod mobile webworkers

Changing the InstanceType for prod mobile webworkers

---

docs/firefighting/index.md

https://dimagi-dev.atlassian.net/browse/SAAS-11489
docs only

add docs for troubleshooting missing forms in ES

---

docs/firefighting/index.md

* Use `stale_data_in_es` command since it has a number of advantages over the other one (PR to remove https://github.com/dimagi/commcare-hq/pull/28737)
* A bit of reformatting and re-wording

update missing ES data docs to use different commands

---

.isort.cfg

Add isort config

---

src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml

Add redis.log to cloudwatch

---

environments/production/terraform.yml

P1 with postgres machines having issues
production's pgmain, pgsynclog, and pgshard machines

upgrade pg machines

---

environments/production/terraform.yml

reverts https://github.com/dimagi/commcare-cloud/pull/4338/files because we'll do pgbouncer later.
prod

reverts pgbouncer resizing

---

docs/howto/tips.md
docs/index.md

I've wanted something like this for a while. If it becomes too big it could be split out by service in future.

tips and tricks

---

docs/firefighting/index.md

Also document tools and general process for recovering from failed internal cluster replication.
[Inspirational fire doc](https://docs.google.com/document/d/1c5sEZrGVxK8bzIG4DvZtDsjqzQR54BAJLw3neiOpON8/edit#)
all using clustered couch / documentation only

Document new Couch DB maintenance process

---

docs/firefighting/index.md

Originally expected to update a confluence page but was led here. It is still unclear to me if this belongs here or not so curious to hear other opinions.
None

Add instructions to restart a machine

---

docs/setup/new_environment.md

Monolith install doc updates

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11548
We should do this soon. I believe I can run this and it won't cause any downtime?
production

increase pgsynclog0 max_storage

---

environments/production/terraform.yml

increase shard size and slow threshold

---

commcare-cloud-bootstrap/commcare_cloud_bootstrap.py

Explicitly use io.open in commcare-cloud-bootstrap.py

---

src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/formplayer.py
src/commcare_cloud/fab/operations/release.py

remove unused / legacy fabric code

---

environments/production/postgresql.yml

move pgmain to pgbouncer3 to even out network traffic

---

src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
src/commcare_cloud/commands/terraform/terraform_migrate_state.py

don't access "exception.message"

---

docs/firefighting/celery.md

Add instructions to restart a celery queue to firefighting docs

---

docs/firefighting/celery.md
src/commcare_cloud/manage_commcare_cloud/monitors/agent_check.yml

I also updated the alert in datadog related to the change in `agent_check.yml` with more detailed instructions.
None

Added intermittent datadog connection errors to celery firefighting docs

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

https://dimagi-dev.atlassian.net/browse/SAAS-11601
This is a followup to @sanjay2916's work, and done earlier than planned as part of an incident.
production

Remove old formplayer machines

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
src/commcare_cloud/ansible/roles/commcarehq/defaults/main.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2

https://dimagi-dev.atlassian.net/browse/SAAS-10159
Production

add formplayer debug options

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

add debug to c014

---

environments/production/aws-resources.yml

Looks like this slipped in in https://github.com/dimagi/commcare-cloud/pull/4382/files
productions

Run `cchq production aws-fill-inventory` to fix build

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
src/commcare_cloud/ansible/roles/commcarehq/defaults/main.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2

I had to manually change the `inventory.ini` file because I could not get the command to work, but I think I did so correctly 
Production

use g1 gc and string dedup for c014

---

environments/staging/terraform.yml

bump memory on staging control to get rid of OOMs when updating users

---

environments/production/terraform.yml

Changing InstanceType for RabbitMQ servers on production environment

---

environments/production/terraform.yml

This is another stop-gap while we work on https://dimagi-dev.atlassian.net/browse/SAAS-11380 more urgently
production

Increase pgsynclog0-production max_storage

---

environments/production/postgresql.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11634
Production

consolidated pgbouncer to pgbouncer5

---

environments/staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

[Resolve security warnings](https://dimagi-dev.atlassian.net/browse/SAAS-11207)
This is only a change to staging in order to play around with some values related to strict transport security. 
Staging

Add Django SecurityMiddleware to staging

---

environments/production/postgresql.yml
environments/production/terraform.yml

Move synclog db pgbouncer to own machine

---

environments/production/public.yml

Keep production formplayer sqlite dbs longer (10d)

---

docs/firefighting/index.md

Add docs for managing pillows

---

src/commcare_cloud/commcare_cloud.py

This upgrade has been tested mostly on 3.6, so we should recommend this version in the error message.

Recommend Python 3.6

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

We stopped having issues with the one machine this was rolled out on, and it doesn't seem to have caused any new issues. I'd expect this to fix similar problems popping up on c023 as well, and be something that all machines generally could benefit from.
production

Use java memory optimizations on all production formplayer machines

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Ran with
```
cchq production deploy-stack --limit formplayer_c014 --tags=monit --branch=dmr/monit-formplayer-c014
```
production

Add monit to formplayer_c014

---

environments/india/terraform.yml
environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

Decommission of ES data nodes on production environment

---

environments/production/app-processes.yml

Splitting of the pillows on production env

---

environments/production/app-processes.yml
environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

Removing Pillow1 server from production environment

---

environments/production/postgresql.yml

Increasing the postgresql_max_connections on pgbouncer3

---

environments/production/terraform.yml

Changing the InstanceType for pgbouncer3

---

environments/production/app-processes.yml

increased xform-pillow processes from 16 to 32

---

environments/india/terraform.yml

I rolled this out when I made #4462 and intended to commit it in the same PR but didn't.
This was applied already about 12h ago.
india

Put pgbouncer1-india into the pgformplayer_nlb

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

Removing ES24 from Prod ES cluster

---

docs/commcare-cloud/env/postgresql_yml.md

Document some new variables added in #4447 
None

Document pgbouncer_host, pgbouncer_hosts, and pgbouncer_endpoint

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

Config changes we used to test #4454 on india.
india

Check pgbouncer-multiprocess setup on india

---

environments/production/terraform.yml

Changing instancetype for pgbouncer5

---

src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2

I don't think we are using actuator for anything and anyway, these properties are not correctly named, they should be `management.server.*`
None

remove incorrect actuator properties

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

Changing InstanceType for couchdb data nodes on production environment

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

https://dimagi-dev.atlassian.net/browse/SAAS-11774
Production

Set pgbouncer_processes=2 on pgbouncer5

---

environments/production/proxy.yml

Shyam noticed there were errors in the log showing that we had hit this limit
production

Increase couchproxy max worker connections on production

---

environments/production/public.yml

Reduce production COUCH_REINDEX_SCHEDULE to every 5 minutes

---

docs/commcare-cloud/basics.md

I saw a typo so I fixed it.
None

Minor typo

---

environments/india/terraform.yml

Increased the root volume from 30GB to 60GB as we are running into disk space issues. 
Production

root volume resized for India celery instances

---

environments/production/terraform.yml

Changing InstanceType for pgsynclog0 on production environment

---

environments/production/terraform.yml

Increasing the Disk Size for kafka1 and Changing Instancetype for pgsynclog0

---

environments/staging/public.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-11782
Staging Kafka

upgrading kafka in staging to 2.6.1

---

environments/production/terraform.yml

Increasing the memory for ES masters on production enviornment

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

https://dimagi-dev.atlassian.net/browse/SAAS-11731
cchq env terraform init
cchq env terraform plan -target aws_lb_target_group.front_end 
cchq env terraform apply -target aws_lb_target_group.front_end 
Staging
india
production

updating the healthz endpoint for alb

---

src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_formplayer_spring.conf.j2

This is a standard practice that should decrease pressure on the GC and the system memory management.
https://dimagi-dev.atlassian.net/browse/SAAS-11801
All

Set Xms same as Xmx on formplayers

---

docs/services/kafka/upgrade.md
environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11631
Production Kafka has been upgraded to 2.6.1.

upgrading kafka in production to 2.6.1

---

environments/staging/public.yml
src/commcare_cloud/ansible/roles/formplayer/templates/application.properties.j2

Enable local caching on staging formplayer.
staging
(Already rolled out)

enable formplayer caching on staging

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2

Add swap (2G) to pgproxy2-staging

---

environments/india/aws-resources.yml
environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/terraform.yml

Removing airflow1-india server

---

environments/india/public.yml

Removing airflow parameters from India env

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

Removing the es29,es30 and es31 from Production ES Cluster

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

Removing es25,es26,es27 and es28 from the production env

---

environments/india/app-processes.yml

Production India
cc: @shyamkumarlchauhan

enabled dedicated_migrations_process for case and xform pillows in India Env

---

environments/production/terraform.yml

Increasing disk size for esmaster5-production server

---

control/check_install.sh

```
line 75: syntax error: unexpected end of file
```

Fix syntax error in check_install.sh

---

environments/staging/public.yml

To make it easier to test the connection issues: https://dimagi-dev.atlassian.net/browse/SAAS-11870
staging

disable formplayer caching on staging

---

environments/india/terraform.yml

Increasing the disksize for pillow2-india server

---

environments/india/terraform.yml

Increasing the Disk size for elasticsearch data nodes

---

src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml
src/commcare_cloud/ansible/roles/formplayer/templates/logback-spring.xml.j2

formpalyer config changes

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml

Enabling multi process for pgbouncer9-production Instance

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Enabling multi process for pgbouncer7

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Enabling multi process for pgbouncer6

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Enabling multi process for pgbouncer3

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11982
Production

increased RDS disk size

---

environments/india/postgresql.yml
environments/india/public.yml
environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/postgresql.yml
environments/production/public.yml
environments/production/terraform.yml

Preparation for rolling out [SQL auditcare](https://github.com/dimagi/commcare-hq/pull/29377).
production and india

SQL auditcare configuration for prod and india

---

src/commcare_cloud/environment/schemas/meta.py
src/commcare_cloud/fab/utils.py

Reverts dimagi/commcare-cloud#4601
Prematurely merged. Intended to test this first.

Revert "Update password text to token for Github"

---

environments/production/fab-settings.yml
src/commcare_cloud/fab/fabfile.py

This will provide a warning during deploy if it is outside of the maintenance window.
Production

set acceptable maintenance window for production

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/terraform.yml

Decommission of 10% of formplayer servers and downsize of pgsynclog0-production Instance

---

environments/production/terraform.yml

Downgrade of pgauditcare0-production and pgbouncer5-production

---

src/commcare_cloud/commands/ansible/service.py

Fix service --only=<queue>:<num> when num is 0

---

environments/production/terraform.yml

Downsize of pgbouncer8-production and pgucr0-production

---

environments/india/public.yml
environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/public.yml
environments/staging/public.yml
src/commcare_cloud/ansible/deploy_efs_mount_shared_dir.yml
src/commcare_cloud/ansible/deploy_nfs_efs_data_sync.yml
src/commcare_cloud/ansible/deploy_shared_dir.yml

I am adding the required changes to mount the EFS file-system on NFS client hosts.
_Information about changes_:
**_src/commcare_cloud/ansible/deploy_shared_dir.yml_** - updating with play-book name (deploy_efs_mount_shared_dir.yml)
updating AWS production resource  file and required variables of EFS ansible role : **_environments/production/aws-resources.yml_** and **_environments/production/inventory.ini.j2_**
Environment : Production
Verified migration process in Staging & India envs.
review request: @dannyroberts

updated Production resources files - NFS to EFS migration plan ref: SAAS-12000

---

environments/production/terraform.yml

Changing InstanceType for pgauditcare0-production

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/terraform.yml

Decommission of the 10% of the formplayer servers

---

docs/howto/transfer-domain.md

https://dimagi-dev.atlassian.net/browse/SC-1370
None

Add troubleshooting section to dump/load docs

---

environments/production/terraform.yml

Downsize of the pgauditcare0-production

---

environments/production/terraform.yml

Downsizing the pgbouncer6 and pgbouncer7

---

environments/production/terraform.yml

Downgrading the pgbouncer3 and pgbouncer9

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/terraform.yml

@prem-fissionhq I think these are your changes from Saturday. I noticed the config on master was out of date and couldn't find a corresponding PR. Forgive me if I just missed it
production

Bring production config into line with actual aws resources

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12077
production

Add resources to production couchdb cluster

---

environments/production/terraform.yml

Changing the InstanceType for CouchDB nodes

---

environments/production/public.yml
environments/staging/public.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2/templates/extras.ini.j2

https://dimagi-dev.atlassian.net/browse/SAAS-12077
production

Increase couchdb os_process_limit

---

docs/setup/new_environment.md

The new environment QA doc wasn't yet linked anywhere
None

Add "testing" section to new environment doc

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12077
production

Set production couchdb_os_process_limit to 1000

---

environments/production/app-processes.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12077
production

Lower concurrency for repeat_record_queue in production to 1 x 6

---

environments/production/terraform.yml

Downsize of the pgformplayer0-production and pgbouncer3-production

---

src/commcare_cloud/ansible/roles/datadog/vars/main.yml

See https://github.com/dimagi/datadog-parsers/pull/38
ALL

update datadog parsers version to include couch.requests metric

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/terraform.yml

Downsize of the formplayer cluster

---

src/commcare_cloud/commands/utils.py
tests/test_timeago.py

Follow up from https://github.com/dimagi/commcare-cloud/pull/4623#discussion_r614296909

tests for timeago

---

src/commcare_cloud/commands/deploy/commcare.py
src/commcare_cloud/commands/deploy/formplayer.py
src/commcare_cloud/commands/deploy/utils.py
src/commcare_cloud/fab/fabfile.py

Companion to [move deploy notifications to commcare-cloud](https://github.com/dimagi/commcare-hq/pull/29576) and [send email](https://github.com/dimagi/commcare-hq/pull/29575)

move HQ deploy notifications to commcare-cloud

---

environments/staging/terraform.yml

Increasing the disk size for couch6

---

environments/staging/terraform.yml

Increasing the disk size for couch7 and couch8

---

src/commcare_cloud/commands/deploy/command.py
src/commcare_cloud/environment/remote.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/release.py
src/commcare_cloud/fab/utils.py

fix '--resume' and refactor DeployMetadata

---

src/commcare_cloud/ansible/roles/bootstrap-users/defaults/main.yml
src/commcare_cloud/ansible/roles/bootstrap-users/tasks/main.yml
src/commcare_cloud/cli_utils.py
src/commcare_cloud/commands/ansible/ansible_playbook.py

https://dimagi-dev.atlassian.net/browse/SAAS-11294
OLD PR: https://github.com/dimagi/commcare-cloud/pull/4261
Update-user-key:
deprecating `cchq <env> update-user-key <username>` command. 
Update-users: 
`cchq <env> update-users`
enabled `exclusive:yes` attribute to the authorized_key module while adding ssh_keys into ansible user's authorized_key file. 
This is to remove all retried users ssh_keys and only active ssh_keys are having given access to ansible user. 
User_input section:
Adding user_input section where are asking to enter the valid `ssh_username` (ex: pkasha is my ssh_username) of the user running the update-user command. Using this we are making sure that the above given ssh_user's ssh_key is present in the new ssh_pubkey_list. If given ssh_username is not in …

updated update-users command and deprecating update-user-key

---

environments/staging/aws-resources.yml
environments/staging/terraform.yml

Staging
relevant PR: https://github.com/dimagi/commcare-cloud/pull/4684
Terminated formplayer3 node. 
We have replaced this node with formplayer5.

removed staging formplayer3 server

---

src/commcare_cloud/commands/deploy/sentry.py

Reported by user on the Forum: https://forum.dimagi.com/t/update-config-failing/8171/6
https://pastebin.com/pE3QdCGg

handle key error

---

src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.ini.j2

Staging
Production
Applied on Staging yesterday and today we have applied on production.

modifying pgbouncer tcp_keepalive timeout to 120 from 300

---

src/commcare_cloud/fab/deploy_diff.py

Came across this recently because I had merged 2 PRs via Github into a parent branch that was not master. I went to deploy staging today and was alarmed to see those PRs (the first and the last one below) were about to be deployed, especially since the parent branch hasn't been merged yet. 
I saw that this code searches for "Merge pull request" in the commit message and is why it picked up these 2 branches as well. This change makes sure the merge commit is actually on master, so now we will only display merged PRs on master.

Only display merged PRs on master

---

src/commcare_cloud/fab/deploy_diff.py

Reverts dimagi/commcare-cloud#4693

Revert "Only display merged PRs on master"

---

src/commcare_cloud/fab/fabfile.py

Added here but it should not be needed: https://github.com/dimagi/commcare-cloud/pull/4685/files#r624963430

remove sudo password prompt

---

environments/production/terraform.yml

resizing mobile workers to fix memory issue

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12102
Production

Couchdb 3.1.1 on prod

---

docs/howto/transfer-domain.md

I don't think we actually have any documentation about this yet, so I'm
mostly putting this in here as a reminder.  Any project going through
this process will be working with Dimagi, so they can request Dimagi's
assistance with that, or we can build out docs on the feature when
needed.

Note that they should look in to rate limiting

---

src/commcare_cloud/environment/secrets/backends/ansible_vault/main.py

Note that the original YAML format is not preserved (comments, etc.).
All

Implement Ansible Vault _set_secret function

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2

Properly set tf_s3_bucket based on state_bucket

---

environments/production/terraform.yml
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
src/commcare_cloud/user_utils.py
tests/test_ssh.py

https://dimagi-dev.atlassian.net/browse/SAAS-11571
Production.
RDS minor version upgraded for below instances
Version: 9.6.15 --> 9.6.20
Instances:
- pgucr0
- pgsynclogs
- pgauditcare.

minor version (9.6.15 to 9.6.20) upgradation done for 3 rds instances

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

New openvpn_az variable and us-west-1 aws elb account for terraform

---

environments/production/inventory.ini
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12190
Explicitly adding `volume_encrypted: no` for control1 machine. This will help us in solving the resource replacement issue.

adding vol_encryption:no for control1 machine

---

src/commcare_cloud/terraform/modules/openvpn/main.tf

Changes automatically based on instance type and could trigger
a destructive terraform change.
All

Ignore ebs_optimized state for openvpn

---

environments/production/fab-settings.yml

Updating maintenance Period to align to start with 0600 UTC.
Production

updated maintenance period to start at 0600 UTC

---

environments/staging/terraform.yml

resizing couch12 to fix oom issue

---

src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12179

Add apt logs to keep record of software installs

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/ansible/couch_utils.py
src/commcare_cloud/commands/ansible/ops_tool.py
src/commcare_cloud/environment/main.py
tests/couch_migration_config/env1/public.yml
tests/couch_migration_config/plans/new_node/expected_couch_config.yml
tests/couch_migration_config/plans/new_node_empty/expected_couch_config.yml
tests/couch_migration_config/plans/reshard/expected_couch_config.yml

Fix CouchDB management commands for version >= 3

---

requirements.txt
setup.py

Upgrade couchdb-cluster-admin to 0.7.0

---

src/commcare_cloud/commands/terraform/constants.py

This PR contains only my changes extracted from [this](https://github.com/dimagi/commcare-cloud/pull/4728) ongoing PR. 
All

Add route to terraform constants.py file

---

src/commcare_cloud/terraform/modules/network/main.tf

fixing syntax/indent error w.r.t to terraform11

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11571
Production
pgformplayer0-production
pgmain0-production
pgshard1-production
pgshard2-production
pgshard3-production
pgshard4-production
pgshard5-production

upgrading rds minor version from 9.6.15 to 9.6.20

---

environments/production/app-processes.yml

Reverts dimagi/commcare-cloud#4765
Pillow is now caught up so removing this.

Revert "Add CaseSearch only pillow to prod"

---

environments/production/app-processes.yml

Reverts dimagi/commcare-cloud#4769
Now that the thursday cleanup is done, we can revert the revert of the revert.

Revert "Revert "Revert "Add CaseSearch only pillow to prod"""

---

environments/production/app-processes.yml

Reverts dimagi/commcare-cloud#4772

Revert "Revert "Revert "Revert "Add CaseSearch only pillow to prod""""

---

environments/production/app-processes.yml

Reverts dimagi/commcare-cloud#4776

Revert "Revert "Revert "Revert "Revert "Add CaseSearch only pillow to prod"""""

---

environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/public.yml
environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/internal_alb/main.tf
src/commcare_cloud/terraform/modules/internal_alb/variables.tf

Staging
Adding new module InternalALBs and adding new ALB for routing requests to Couch nodes.
Old PR: https://github.com/dimagi/commcare-cloud/pull/4741

Adding internal_albs module and created couchProxyAlb

---

src/commcare_cloud/user_utils.py

broken in https://github.com/dimagi/commcare-cloud/pull/4723

Fix update-users command

---

environments/_users/dimagi.yml
environments/_users/fissionlabs.yml

staging, swiss, india, production

Remove more users

---

environments/india/terraform.yml

switching to higher instance type due to current RAM issues

---

environments/india/proxy.yml
environments/production/proxy.yml
environments/staging/proxy.yml
environments/swiss/proxy.yml

[JIRA Ticket](https://dimagi-dev.atlassian.net/browse/SAAS-12042)
Bump HSTS value to 1 week. (I have a slack alert to remind me to do this at the beginning of every month)
Production, Staging, India, Swiss

Bump hsts value to 1 week

---

environments/staging/terraform.yml

This will be reverted when the migrations are finished.
Mirrors what was done for india migrations: https://github.com/dimagi/commcare-cloud/pull/4781
staging

Resize django-manage for Couch to SQL migrations

---

environments/_authorized_keys/rcostello.pub
environments/_users/dimagi.yml

add rcostello public key

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12312
Production

enabling cron task to delete older es logs

---

environments/production/terraform.yml

@
https://dimagi-dev.atlassian.net/browse/SAAS-12378
Production
@prem-fissionhq 
@shyamkumarlchauhan

Changed Formplayer instance type to r5.2xlarge

---

src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12453
staging india production

Logship /var/log/commands.log

---

environments/india/public.yml
environments/staging/public.yml
src/commcare_cloud/ansible/roles/common_installs/defaults/main.yml
src/commcare_cloud/ansible/roles/common_installs/handlers/main.yml
src/commcare_cloud/ansible/roles/common_installs/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12195
All
Applied on staging server as of now.

adding chrony package for better time syncronization

---

src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/terraform/modules/postgresql/main.tf

Disabling rds_enhanced_monitoring until monitoring role available.

Disabling rds_enhanced_monitoring until monitoring role avaliable

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12195
Production.

Production: installing chrony package for better time syncronization

---

docs/commcare-cloud/basics.md

https://dimagi-dev.atlassian.net/browse/SC-1663

Add a note to not use the ansible user

---

environments/production/public.yml
environments/staging/public.yml

Followup to feedback on [this PR](https://github.com/dimagi/commcare-cloud/pull/4841)
HQ part [here](https://github.com/dimagi/commcare-hq/pull/30206)

remove available custom rule values

---

environments/india/proxy.yml
environments/production/proxy.yml
environments/staging/proxy.yml
environments/swiss/proxy.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12042
Bump HSTS value to 1 month.
Production, India, Swiss, and Staging

Bump hsts value to 1 month

---

environments/production/terraform.yml

Increase pgauditcare0-production storage from 1TB to 2TB.
https://dimagi-dev.atlassian.net/browse/SAAS-12540
Production

Increase pgauditcare0-production storage

---

src/commcare_cloud/commands/terraform/aws.py

to make it run quickly. Followup to https://github.com/dimagi/commcare-cloud/pull/4702
None, just smoother tooling.

Add timeout to is_ec2_instance_in_account

---

environments/_users/fissionlabs.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12551
staging, india, swiss, production

Remove user rganne

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12576
production

Increase production formplayer machines to m5a.4xlarge

---

environments/india/inventory.ini
environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12548
India.
Replacing existing EBS volume with AWS encrypted EBS volume
Plan doc: https://docs.google.com/document/d/1k15O1d7R-CwZVUVMps22az34pFXj7Z1WqUaCNzmdFC4/edit

Replacing existing EBS volume with AWS encrypted EBS volume on India Env

---

docs/monitoring/slack.md
environments/staging/meta.yml
src/commcare_cloud/commands/deploy/slack.py

* Slight change to "Deploy Started" message (remove the emoji)
* Add a reaction to the message on success failure (:heavy_check_mark: or :x: )
* Update docs

tweaks to slack deploy integration

---

changelog/0044-migrate-forms-to-sql.yml
docs/changelog/0044-migrate-forms-to-sql.md

Updated change log because the old link has been 404ing since the migration code was deleted.
all (docs/process only)

Add forms migration max version

---

src/commcare_cloud/commands/deploy/slack.py

Add text to the slack messages that will get shown in notifications. This should fix the 'content can not be displayed' messages.
https://stackoverflow.com/a/56327506/632517

add notification text to slack messages

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12562
India.
During Cost optimization planning we observed that resources are underutilized. Therefore, we have planned to right-size the instance.

resizing the formplayer instance from t3.2xlarge to t3.xlarge

---

src/commcare_cloud/ansible/roles/couchdb2-preinstall/tasks/main.yml
src/commcare_cloud/ansible/roles/couchdb2-preinstall/vars/main.yml

CouchDB >= 3.0.0 -> 1:20.3.8.26-1
CouchDB < 3.0.0 -> 1:19.3.6.13-1
https://dimagi-dev.atlassian.net/browse/SAAS-12222
All

Update erlang dependency version for CouchDB

---

src/commcare_cloud/ansible/roles/couchdb2/handlers/main.yml
src/commcare_cloud/ansible/roles/couchdb2/tasks/main.yml

CouchDB skip restart when only changing config

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12564
Production
During Cost optimization planning we observed that resources are underutilized. Therefore, we have planned to right-size the instance.

resizing the production proxy servers

---

environments/production/terraform.yml

resizing mobile webworkers as we are facing OOM and servers becoming unresponsive.

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

https://dimagi-dev.atlassian.net/browse/SAAS-12596
Production

increase couch swap size

---

environments/production/inventory.ini
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12548
Production.
Replacing existing EBS volume with AWS encrypted EBS volume
Plan doc: https://docs.google.com/document/d/1k15O1d7R-CwZVUVMps22az34pFXj7Z1WqUaCNzmdFC4/edit

 Replacing existing EBS volume with AWS encrypted EBS volume on Prod Couch nodes

---

environments/staging/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11793
Staging

upgrade rds postgres version from 9.6.20 to 10.17 version

---

src/commcare_cloud/terraform/modules/server/main.tf

Reverts dimagi/commcare-cloud#4896

Revert "fixing root volume tags removal issue when new state imported"

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12654
India

resizing India redis cluster to fix eviction issues

---

src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

rather than hard-coding celery[0]
This was something I encountered today.

Make forward-port find the correct celery machine for flower

---

control/check_install.sh
docs/setup/manual_installation.md
src/commcare_cloud/config.example.py
src/commcare_cloud/github.py

This PR is geared towards making the steps outlined in this section https://dimagi.github.io/commcare-cloud/setup/manual_installation.html#setup (which this PR also edits for clarity) cleaner to follow as the complete personal control machine environment setup for new users.
None

Streamline control install

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12656 / https://dimagi-dev.atlassian.net/browse/SAAS-12566
production

Remove pgbouncer9 from pgformplayer-nlb-production

---

environments/india/aws-resources.yml
environments/india/inventory.ini

https://dimagi-dev.atlassian.net/browse/SAAS-12554
India

replacing pgformplayer_nlb with new NLB with 3subnets

---

src/commcare_cloud/ansible/deploy_cloudwatch_logs.yml
src/commcare_cloud/ansible/deploy_couchdb2.yml
src/commcare_cloud/ansible/roles/couchdb2/templates/extras.ini.j2

https://dimagi-dev.atlassian.net/browse/SAAS-12624
All

Update CouchDB log configuration

---

environments/_authorized_keys/spokhriyal.pub
environments/_users/dimagi.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12660
All

Offboard Shivam Pokhriyal

---

environments/_users/dimagi-interns.yml
environments/_users/dimagi.yml

Ticket: [SAAS-12653](https://dimagi-dev.atlassian.net/browse/SAAS-12653)
All environments.

Add mlee as full-time dev

---

environments/_users/dimagi.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12660
All

Offboard Shivam Pokhriyal (fix)

---

src/commcare_cloud/ansible/roles/couchdb2/templates/monit.couchdb2.j2

https://dimagi-dev.atlassian.net/browse/SAAS-12638
staging
india
production

chaning monit restart command for couchdb2

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11793
India

upgrade pgmain0-india postgres version from 9.6.20 to 10.17 version

---

environments/production/inventory.ini
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12617
Production

doubling the instance size and reducing total number of instances

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12567
Production 
During Cost optimization planning we observed that resources are underutilized. Therefore, we have planned to reduce the instance capacity of the HQ worker instances.

resizing HQ workers instance capacity

---

environments/production/postgresql.yml
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12566
Addresses errors due to the rollout of, and builds on, https://github.com/dimagi/commcare-cloud/pull/4922

Consolidate pgbouncer machines

---

src/commcare_cloud/commands/deploy/slack.py

We still have the emoji reaction which seems sufficient.

drop slack reply on deploy completion

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12566
Followup to https://github.com/dimagi/commcare-cloud/pull/4922
production

Split production pgbouncer machines into two groups

---

environments/india/proxy.yml
environments/production/proxy.yml
environments/staging/proxy.yml
environments/swiss/proxy.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12042
The end goal is 1 year. We probably could just update to 1 year now, but 1 month to 1 year felt like a big jump.
Production, India, Swiss, and Staging

Bump hsts value to 4 months

---

environments/_authorized_keys/adunn.pub
environments/_users/dimagi.yml

https://confluence.dimagi.com/pages/viewpage.action?pageId=106629646
Holding off on merge pending explicit approval
All

Add Addison as Dimagi user

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12737
Production
pgucr0-production
pgsynclog0-production
pgauditcare0-production

upgrading rds instance postgres version from 9.6.20 to 10.17

---

environments/india/inventory.ini
environments/production/inventory.ini
environments/staging/inventory.ini
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.tfvars.j2
src/commcare_cloud/terraform/modules/network/main.tf
src/commcare_cloud/terraform/modules/network/variables.tf

https://dimagi-dev.atlassian.net/browse/SAAS-11275
To be merged on Nov 1, with the openvpn machines themselves manually stopped today.

Remove OpenVPN!

---

environments/india/terraform.yml
environments/production/terraform.yml

to ELBSecurityPolicy-FS-1-2-Res-2020-10, as announced in https://forum.dimagi.com/t/network-security-update-on-www-commcarehq-org-india-commcarehq-org/8502.
https://dimagi-dev.atlassian.net/browse/SAAS-12091
india, production

Update ssl_policy on india and production

---

environments/staging/public.yml

This has already been deployed.
staging

Python 3.9 on staging

---

environments/india/terraform.yml
environments/production/terraform.yml
environments/staging/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12600
Adding server_auto_recovery option to the webworker instance group

adding auto recovery on webworkers staging, india and production

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12775
1. PRODUCTION ENVIRONMENT

Reducing the size of mobile_webworkers

---

environments/staging/public.yml

Reverts dimagi/commcare-cloud#4968

Revert "Revert "Python 3.9 on staging""

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12783
production

Increase storage on pgauditcare0-production

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12786
Production

increase_couchDB_diskspace_to_90GB

---

docs/index.md
docs/services/email.md

Local hosters were confused about why they couldn't send emails. 
Docs only.

Add docs on setting up email

---

src/commcare_cloud/commands/deploy/commcare.py

This call got left out at some point. It's already included in the formplayer deploy.

notify when deploy fails

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12809
Production

resizing ES coordinator nodes from r5.4x to r5.2x

---

environments/production/inventory.ini
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12568
Production

Reducing 1 es datanode from each az

---

environments/production/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_workers.conf.j2
src/commcare_cloud/environment/schemas/app_processes.py

https://dimagi-dev.atlassian.net/browse/SAAS-12815
All

Add celery variable for prefetch-multiplier

---

src/commcare_cloud/fab/operations/formplayer.py

Fix broken build path for revert

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12832
production

Set vacuum_cost_limit to 1000 for pgformplayer0-production

---

environments/india/public.yml

Upgrade India to Python 3.9

---

environments/production/app-processes.yml

Removal approved by client via email on Nov. 1.
https://github.com/dimagi/commcare-hq/pull/30810
Production.

Remove M4ChangeFormFluffPillow

---

environments/production/app-processes.yml

Cleaning up after the temporary increases yesterday
Production

undo temporary increase in reminder processing

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-132
Production.

Upgrade Production to Python 3.9

---

src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/paths.py
tests/test_environment.py

All, since https://github.com/dimagi/commcare-cloud/pull/5006 has been merged.

Use default python_version from group_vars/all.yml

---

commcare-cloud-bootstrap/commcare_cloud_bootstrap.py
commcare-cloud-bootstrap/environment/private.yml.j2

This PR swaps the uuid library out for the [secrets](https://docs.python.org/3/library/secrets.html) library (new in Python 3.6) which is intended for managing passwords, tokens, etc.
None. This change only affects commcare-cloud-bootstrap, tools for bootstrapping new environments.

Better passwords

---

setup.py
src/commcare_cloud/commands/terraform/tests/test_postgresql_units.py
tests/__init__.py
tests/test_couch_migration.py
tests/test_file_migration.py
tests/test_getinventory.py
tests/test_schemas.py
tests/test_ssh.py

Inspired by https://github.com/dimagi/commcare-hq/pull/30728
None. Tests only.

Allow tests to be run without installing mock

---

src/commcare_cloud/environment/schemas/app_processes.py

This has been pretty noisy lately, and 30 seems like a more reasonable proxy for when we would have an issue.
All

Increase reminder_queue threshold

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2
src/commcare_cloud/ansible/roles/bootstrap-users/defaults/main.yml
src/commcare_cloud/ansible/roles/bootstrap-users/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12853
All

Set fixed gid and uid for ansible and cchq users

---

environments/production/inventory.ini.j2
environments/production/postgresql.yml

Double default pool size and number of processes

---

environments/production/postgresql.yml

rremoving nlb and adding pgbouncer host

---

environments/production/inventory.ini.j2
environments/production/postgresql.yml

This reverts commit b2590872d60081aca3301cbe40f153b0faf19109.
Production

Revert "increase default pool size and number of processes"

---

environments/production/app-processes.yml

Add celery_bXXX machines to app_processes.yml

---

environments/production/app-processes.yml

Reverts dimagi/commcare-cloud#5042
I'm opening the change ends up using too much memory/cpu and we want to revert. If that's the case then you can approve and merge.

Revert "Update app-processes.yml"

---

environments/production/postgresql.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12891
Production

Revert "removing nlb and adding pgbouncer host"

---

environments/production/terraform.yml

resizing_mobile_webworkers

---

src/commcare_cloud/terraform/modules/postgresql/main.tf

https://dimagi-dev.atlassian.net/browse/SAAS-12879
Tested on staging, works, no issues
all aws envs

Enable RDS performance insights

---

environments/production/terraform.yml
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/postgresql/main.tf

https://dimagi-dev.atlassian.net/browse/SAAS-11932
production

Add tagging for cross region backup

---

environments/production/terraform.yml

Past increases proved insufficient
Production

increase wal settings again

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Followup to https://github.com/dimagi/commcare-cloud/pull/5083. 🤦🏻

Set CHECK_REPEATERS_PARTITION_COUNT if defined

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12915
Production

resizing elasticache cluster

---

environments/production/app-processes.yml
environments/production/inventory.ini.j2
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12853
Production

Replace old celery nodes with new ones on AZ c

---

src/commcare_cloud/ansible/roles/couchdb2/templates/extras.ini.j2

This reverts commit 6b3d99d9e60aa5e1bf427bc9cfbf29ef3dc07630.
All

Revert "lower compaction ratio"

---

environments/production/terraform.yml

increase pgshard5 disk space with 50%

---

src/commcare_cloud/commands/terraform/constants.py

https://github.com/dimagi/commcare-hq/pull/30977

Add latest XSS-body WAF urls

---

environments/production/postgresql.yml
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12952
production

Adjust pgformplayer0-production pgbouncer_pool_size and max_wal_size

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

Exclude the "SQLiExtendedPatterns_BODY" WAF rule from "AWSManagedRulesSQLiRuleSet" 
https://dimagi-dev.atlassian.net/browse/SAAS-12955
All (already applied to 'prod')

disable the SQLiExtendedPatterns_BODY WAF rule

---

environments/staging/postgresql.yml
src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.ini.j2
src/commcare_cloud/environment/schemas/postgresql.py
tests/test_envs/2018-04-04-development-snapshot/.generated.yml
tests/test_envs/2018-04-04-enikshay-snapshot/.generated.yml
tests/test_envs/2018-04-04-icds-new-snapshot/.generated.yml
tests/test_envs/2018-04-04-pna-snapshot/.generated.yml
tests/test_envs/2018-04-04-production-snapshot/.generated.yml
tests/test_envs/2018-04-04-softlayer-snapshot/.generated.yml
tests/test_envs/2018-04-04-staging-snapshot/.generated.yml
tests/test_envs/2018-04-04-swiss-snapshot/.generated.yml

Allow setting pgbouncer_reserve_pool_size per db

---

environments/production/postgresql.yml
environments/production/terraform.yml

Increase pgformplayer0 size, reduce connections, increase shared_buffers

---

src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.ini.j2

See discussion in https://dimagi-dev.atlassian.net/browse/SAAS-12885?focusedCommentId=188443. This fixes the change introduced yesterday in #5110 
None

Fix pgbouncer param name reserve_pool in database config context

---

hosting_docs/source/prereqs/2-architecture.rst

**Note:** Base branch is **sr/docs**
Replaces PR #5040 (reverted in PR #5118).
fyi @proteusvacuum @Charl1996 
None. Documentation only.

Architecture overview, take 2

---

hosting_docs/source/prereqs/5b-hardware-mgmt.rst
hosting_docs/source/prereqs/index.rst

**Note:** Base branch is **sr/docs**
Ticket: [SC-1697](https://dimagi-dev.atlassian.net/browse/SC-1697)
Incorporates internal documentation given to partners, and reference to ANSI/BICSI 002 standard.
None. Documentation only.

Docs: Managing hardware

---

environments/production/app-processes.yml

Increase case-pillow processes

---

environments/production/postgresql.yml

Reduce total connections to pgmain0

---

environments/production/app-processes.yml

Decrease case-pillow processes

---

environments/production/terraform.yml

Scale up pgucr0 instance

---

environments/production/postgresql.yml

Reduce total connections to pgucr0

---

environments/production/app-processes.yml

Increase and distribute case-pillow processes

---

environments/production/app-processes.yml

Move more pillow-case processes

---

environments/production/terraform.yml

Scale down pgucr0 instance

---

environments/production/inventory.ini
environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-12966
Production

Reduced_10percent_formplayer_machines

---

environments/staging/public.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12901
Staging

Upgrade RabbitMQ to 3.9.13

---

environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13152
Production

Reduce_size_of_production_couch_nodes

---

environments/production/inventory.ini
environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-12966
Production

Reduce formplayer machines (10% at a time)

---

environments/staging/app-processes.yml

Add workers to ush_background_tasks

---

docs/commcare-cloud/commands/index.md
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

Added note to --tmux about session being specific to user

---

environments/production/postgresql.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13191
Production

Adjust and increase pgmain0 connections

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/postgresql.yml
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12967
Production 
Previous PR: https://github.com/dimagi/commcare-cloud/pull/5126

rebuilding pgformplayer rds with smaller size

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13198
Production.

increasing pgshard2 disk space

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/postgresql.yml
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12968
Production.

Rebuild main db with a smaller storage volume

---

environments/production/public.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-12901
**##### ENVIRONMENTS AFFECTED**
Production

production_rabbitmq_upgradation

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13206
Production

increased size of pgshard1 to 750GB

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13207
production

increased the disk size to 200GB on pgbouncer3

---

src/commcare_cloud/commands/terraform/constants.py

https://dimagi-dev.atlassian.net/browse/SAAS-13208
All environments

Update terraform command

---

environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13216
**ENVIRONMENTS AFFECTED**
production

increased_size_of_pgshard3_to_750GB

---

environments/production/terraform.yml

increased_size_of_pgshard4_to_750GB

---

environments/echis/app-processes.yml
environments/india/app-processes.yml
environments/pna/app-processes.yml
environments/swiss/app-processes.yml
src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_workers.conf.j2
src/commcare_cloud/environment/schemas/app_processes.py

Delete dead code related to the celery 'optimize' option, which has no
effect anymore.
All

Delete obsolete 'optimize' celery option code

---

environments/production/app-processes.yml
environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12901
Adding OLD_BROKER_URL

adding old_broker_url to fix localsettings.py credentials for read url

---

environments/production/app-processes.yml
environments/production/inventory.ini

https://dimagi-dev.atlassian.net/browse/SAAS-12901
Production rabbitmq

Saas 12901/revert rabbitmq oldversion

---

environments/staging/app-processes.yml

[staging] adjust celery processes

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12901
Production rabbitmq

removing b000 from migration and old rabbitmq urls

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-13177 
**ENVIRONMENTS AFFECTED**
Production

reducing_size_production_couch

---

docs/howto/add-celery-machines.md

Fixes a tiny mistake.
None. Docs only.

Tiny fix to docs

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12915
https://dimagi-dev.atlassian.net/browse/SAAS-12932
Production

switching back to previous instance type

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13156
India
Currently, we have 3 Kafka servers, out of which Kafka is running on only one server, We would like to utilize all 3 servers which also helps us in having Kafka HA.

making India kafka servers highly available with multi-az 

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12484
Production

making prod zookeeper multi-az

---

src/commcare_cloud/terraform/modules/ga_alb_waf/main.tf

[](https://dimagi-dev.atlassian.net/browse/SAAS-13133)
This is currently deployed on staging. It is intended to be applied to all enviornments.
This change allows us to whitelist specific URLs against Log4J, and provides a pattern we can follow for exceptions to managed rules in the future.
I did hardcode the specific URL pattern that is giving us issues. It might be worth going with this approach for now (as users are currently blocked), and then adding additional automation to handle this like `waf_allow`.
Also note that this PR reduces the capacity for of our whitelist rules from 100 to 50, as this new rule would put us over our capacity limit otherwise (and we were not using the full capacity for whitelist rules anyway)

updated WAF to account for Log4J

---

src/commcare_cloud/ansible/requirements.yml

Change cloudalchemy.prometheus source

---

src/commcare_cloud/commands/terraform/templates/terraform.tf.j2

https://dimagi-dev.atlassian.net/browse/SAAS-12886
All

upgrading terraform version to 13 and its respective providers versions

---

src/commcare_cloud/commands/terraform/templates/terraform.tf.j2

to support terraform 0.12 and 0.13
https://dimagi-dev.atlassian.net/browse/SAAS-13313
AWS envs

Change aws provider version down to 3.75.1

---

src/commcare_cloud/ansible/roles/bootstrap-users/tasks/main.yml
src/commcare_cloud/commands/ansible/ansible_playbook.py

Skip setting ansible and cchq uids and gids when running update-users
All

Fix update-users

---

docs/commcare-cloud/commands/index.md
requirements.txt
setup.py
src/commcare_cloud/help_cache/ansible-playbook.txt
src/commcare_cloud/help_cache/ansible.txt

Copy of https://github.com/dimagi/commcare-cloud/pull/4917

ansible version upgrade to 4.2.0. Copy of PR#4917

---

environments/india/terraform.yml

resizing India elasticsearch cluster

---

docs/commcare-cloud/commands/index.md
requirements.txt
setup.py
src/commcare_cloud/help_cache/ansible-playbook.txt
src/commcare_cloud/help_cache/ansible.txt

Reverts dimagi/commcare-cloud#5245
Reverting the PR as we have noticed compatibility issues with ansible-vault and aws.secrets plugin

Revert "ansible version upgrade to 4.2.0. Copy of PR#4917"

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12886
India

upgrading terraform version in India env

---

environments/swiss/postgresql.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12834
Swiss

Swiss: upgrading postgresql version to 10

---

environments/production/terraform.yml

**Ticket:**
https://dimagi-dev.atlassian.net/browse/SAAS-13378
**ENVIRONMENTS AFFECTED:**
Production

increase_50percent_volume_size_to_esnodes

---

environments/staging/fab-settings.yml

Staging branches YAML filename was changed in dimagi/commcare-hq#31446
- staging

Fix deploy notice (staging.yml)

---

src/commcare_cloud/commands/ansible/helpers.py
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

This removes the need for the `--control` parameter in `cchq --control <env> ssh <host>`
AWS SSM environments

SSH directly to any machine via SSM

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11914
Production

making ec2_metadata_tokens value to required

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-11914
India

 Updating ec2_metadata_tokens_required option and set to True on India

---

environments/production/terraform.yml

increasing the redis cluster size due to current issues with utilization

---

changelog/README.md

Fixes the changelog documentation URL which is updated.

update: changelog documentation URL

---

src/commcare_cloud/ansible/ansible.cfg

Define ansible remote_tmp

---

docs/monitoring/slack.md
environments/india/meta.yml
environments/production/meta.yml

add slack notifications to #gtd-dev-support for prod and india

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12886
Production

upgrading terraform version to 13 on production

---

environments/staging/app-processes.yml

[staging] adjust celery processes (2)

---

changelog/0048-update-supervisor-confs.yml
docs/changelog/0048-update-supervisor-confs.md
docs/changelog/index.md

Wording correction to #5302.
- all

Clarify incorrect wording in recent changlog entry.

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

https://dimagi-dev.atlassian.net/browse/SAAS-13578
Production

replace prod zookeeper with new encrypted servers

---

src/commcare_cloud/terraform/modules/server/main.tf

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-13583
**ENVIRONMENTS AFFECTED: -** Staging

EBS_volumes_skip_destroy_true

---

changelog/0049-upgrade-to-postgres-10.yml
docs/changelog/0049-upgrade-to-postgres-10.md
docs/changelog/index.md
hosting_docs/source/changelog/0049-upgrade-to-postgres-10.md
hosting_docs/source/changelog/index.md

https://dimagi-dev.atlassian.net/browse/SAAS-12770
Fixing date.

correcting date format

---

changelog/0049-upgrade-to-postgres-10.yml
docs/changelog/0049-upgrade-to-postgres-10.md
hosting_docs/source/changelog/0049-upgrade-to-postgres-10.md

https://dimagi-dev.atlassian.net/browse/SAAS-12770

link was not shown properly, fixed it

---

environments/production/terraform.yml

Change pillows instance type from r5a.8xlarge to r5a.12xlarge.
https://dimagi-dev.atlassian.net/browse/SAAS-13632
Production

Scale up pillows

---

src/commcare_cloud/ansible/roles/couchdb2-preinstall/tasks/main.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/install_latest.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13689
All

Temporary fix for broken erlang apt repository

---

docs/404.md

Add a 404 page

---

hosting_docs/source/backups_dr/2-backups-guide.rst
hosting_docs/source/reference/1-commcare-cloud/slack.rst
hosting_docs/source/reference/howto/add-celery-machines.rst

Top up updates made to old docs

---

changelog/0049-upgrade-to-postgres-10.yml
docs/changelog/0049-upgrade-to-postgres-10.md
docs/changelog/index.md
hosting_docs/source/changelog/0049-upgrade-to-postgres-10.md
hosting_docs/source/changelog/index.md

https://dimagi-dev.atlassian.net/browse/SAAS-12770
@dannyroberts please review my changes.

correcting wording and sentences.

---

hosting_docs/source/installation/migration/1-migrating-project.rst
quick_monolith_install/sample-environment/vault.yml.j2

This fixes the issue in quick-install where the usernames are being set to dynamic strings instead of static usernames.

Fix usernames in the config template file

---

environments/development/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Ticket: [SAAS-13703](https://dimagi-dev.atlassian.net/browse/SAAS-13703)
Relates to (but not affected by) dimagi/commcare-hq#31844. Will hold merge of this PR until that one is merged for validation.
None.

Remove unused `ENABLE_DRACONIAN_SECURITY_FEATURES` setting

---

environments/swiss/app-processes.yml

[swiss] Adjust celery processes

---

src/commcare_cloud/ansible/roles/kafka/tasks/main.yml

This fixes the bug introduced in this PR https://github.com/dimagi/commcare-cloud/pull/5169/files#r911632281
@dannyroberts 
@prem-fissionhq

Fix kafka download script when on default versions

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SC-2145
This is requried for migration of a project from Prod to a self hosted env.
This is already deployed onto the proxy machine.

Add a migration domain for ONSE

---

hosting_docs/source/installation/1-quick-monolith-install.rst
hosting_docs/source/installation/migration/1-migrating-project.rst

Clarifications in docs

---

hosting_docs/source/installation/migration/1-migrating-project.rst

Add a small but important note to local hosting docs.

Add a note to Step 1

---

environments/production/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-13737
**ENVIRONMENTS AFFECTED :** Production

Resizing_the_formplayers_in_production

---

environments/production/terraform.yml

**Ticket :**  https://dimagi-dev.atlassian.net/browse/SAAS-13737
**ENVIRONMENTS AFFECTED :**   Production

roll_back_formplayer_instance_size_to_m5a.4xlarge

---

environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2
src/commcare_cloud/commands/terraform/terraform.py
src/commcare_cloud/environment/schemas/terraform.py

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-13628
**ENVIRONMENTS AFFECTED: -** Staging

upgrade_tf-V0.14

---

src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/terraform/modules/efs_file_system/mount-point/output.tf
src/commcare_cloud/terraform/modules/efs_file_system/output.tf
src/commcare_cloud/terraform/modules/elasticache-cluster/output.tf
src/commcare_cloud/terraform/modules/logshipping/firehose_stream/outputs.tf
src/commcare_cloud/terraform/modules/logshipping/outputs.tf
src/commcare_cloud/terraform/modules/network/outputs.tf
src/commcare_cloud/terraform/modules/postgresql/main.tf
src/commcare_cloud/terraform/modules/server/iam/outputs.tf
src/commcare_cloud/terraform/modules/server/outputs.tf

warning_cleanup_for_interpolation_syntax
**ENVIRONMENTS AFFECTED: -** Staging, India and Production

warning_cleanup_for_interpolation_syntax

---

environments/india/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13628
ENVIRONMENTS AFFECTED:- India

india_upgrade_t-V0.14

---

environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13628
ENVIRONMENTS AFFECTED: Production

production_upgrade_t-V0.14

---

environments/staging/public.yml
src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/tasks/misc_v2.yml

https://dimagi-dev.atlassian.net/browse/USH-1722
Staging
(Production at a later date if testing on staging goes well)

install phonetic plugin

---

environments/india/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13634
India.

upgrade kafka version to 2.6.1 in India env.

---

hosting_docs/source/reference/1-commcare-cloud/2-configuration.rst

The main goal was to add docs for the `management_commands` section in `app_processes.yml` but I did a few other cleanups as well.

small docs updates

---

environments/production/terraform.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-13763
**ENVIRONMENTS AFFECTED: -** Production

changing_elasticache_instance_size_to_cache.r5.2xlarge

---

environments/staging/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13372
redis

Redis upgrade on staging  to 6.2 version

---

environments/staging/terraform.yml

getting error when particular version is defined, so correcting it

---

environments/production/terraform.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-13762
**ENVIRONMENTS AFFECTED: -** Production

Change_production_auditcare_instancetype_to_db.t3.2xlarge

---

environments/production/terraform.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-13857
**ENVIRONMENTS AFFECTED: -** Production

increasing_disk_space_for_esb_instances

---

environments/staging/app-processes.yml

[staging] adjust celery processes (3)

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/celery.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_flower.conf.j2

Add broker_api configuration directive for Flower and change its
Supervisor configuration file permissions (as it will now include
credentials).
All

Add broker_api configuration for Flower

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13869
production

change instance type of pgbouncer_a1

---

environments/staging/public.yml
hosting_docs/source/reference/howto/wipe_persistent_data.rst
hosting_docs/source/services/kafka.rst
src/commcare_cloud/ansible/wipe_kafka.yml

- Staging. 
- Updated reference docs. 
Old PR: https://github.com/dimagi/commcare-cloud/pull/5344

upgrading kafka from 2.6.1 to 3.2.0, and docs accordingly

---

environments/_users/dimagi-interns.yml

Follow-up for https://github.com/dimagi/commcare-cloud/pull/5410

Fix TypeError: 'NoneType' object is not iterable

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13372
india

redis upgrade to 6.2 on india

---

environments/swiss/public.yml
src/commcare_cloud/ansible/group_vars/redis.yml
src/commcare_cloud/ansible/roles/redis/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13372
Swiss

upgrade redis version on swiss server

---

environments/india/public.yml

India.
After merging the staging PR only.

planning to upgrade zookeeper on India env.

---

environments/india/public.yml

upgrade kafka from 2.6.1 to 3.20

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13372
Production

redis upgrade on production

---

environments/staging/public.yml

update es case index for phonetic testing
Staging

move case search name var

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-13885
**ENVIRONMENTS AFFECTED:** Production

changing_formplayer_instance_type_to_r6a.2xlarge

---

environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/logshipping/main.tf

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-13786
**ENVIRONMENTS AFFECTED:** Staging, India and Production

staging_terraform_upgradation_and_warnings_cleanup

---

environments/india/terraform.yml
environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13372
ENVIRONMENTS AFFECTED:  India and Production

changing_the_redis_version

---

environments/india/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13786
ENVIRONMENTS AFFECTED: India

terraform_upgrade_on_India_environment

---

environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13786
ENVIRONMENTS AFFECTED: Production

terraform_upgradation_on_production

---

environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/staging/inventory.ini
environments/staging/inventory.ini.j2

https://dimagi-dev.atlassian.net/browse/SAAS-13903

Remove couch_alb from the couchdb2 group

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

https://dimagi-dev.atlassian.net/browse/SAAS-13894
This goes along with https://github.com/dimagi/commcare-hq/pull/32071 and https://github.com/dimagi/commcare-hq/pull/32072, making it possible to set these to None

Allow s3 credentials to be None in localsettings

---

environments/production/public.yml

upgrading kafka in production

---

hosting_docs/source/installation/1-quick-monolith-install.rst

Noticed some typos, and just decided to read through it and make any modifications that felt beneficial.

Minor wording edits in monolith install docs

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13905
Production

reduce replica from 3 to 2 for elasticache

---

environments/production/public.yml

upgrading zookeeper in produciton env to 3.7.1

---

src/commcare_cloud/terraform/modules/server/iam/main.tf

https://dimagi-dev.atlassian.net/browse/SAAS-13894

Add EC2 role permissions for kissmetrics bucket

---

environments/swiss/inventory.ini
environments/swiss/public.yml

[swiss] Add missing filebeat_inputs definition

---

src/commcare_cloud/ansible/group_vars/elasticsearch.yml
src/commcare_cloud/ansible/roles/elasticsearch/templates/monit.elasticsearch.j2

https://forum.dimagi.com/t/error-when-running-commcare-cloud-monolith-django-manage-preindex-everything/9253
All

Elasticsearch small fixes

---

src/commcare_cloud/environment/secrets/backends/ansible_vault/tests/expected-generated-variables.yml
src/commcare_cloud/environment/secrets/backends/aws_secrets/tests/expected-generated-variables.yml
src/commcare_cloud/environment/secrets/secrets.yml

https://docs.google.com/document/d/1gbQcAC3H4kj22iMCMMKSYMVO5_7kt56qiS8OWkd6e34/edit#heading=h.f9dgxbqmorgx
Related HQ PR: https://github.com/dimagi/commcare-hq/pull/32112
Staging

Add abdm secrets config

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13918
production

downsize the elasticache cluster

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13884
Production

downsize pgmain1 to db.m5.4xlarge

---

environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-13891 
**ENVIRONMENTS AFFECTED: -** Production

Removing_old_escoordinator_nodes_from_terraform_file_and_ini.j2_file

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

ABDM client and client secret to be stored in AWS secrets
https://docs.google.com/document/d/1gbQcAC3H4kj22iMCMMKSYMVO5_7kt56qiS8OWkd6e34/edit#heading=h.f9dgxbqmorgx
localsettings.py of respective envs

Update localsettings.py template with ABDM secrets

---

src/commcare_cloud/ansible/roles/backups/tasks/set_up_check_s3_backups.yml
src/commcare_cloud/ansible/roles/backups/templates/backup_snapshots.py.j2
src/commcare_cloud/ansible/roles/backups/templates/check_s3_backup.py.j2
src/commcare_cloud/ansible/roles/backups/templates/create_blobdb_backup.sh.j2
src/commcare_cloud/ansible/roles/couchdb2/templates/create_couchdb_backup.sh.j2
src/commcare_cloud/ansible/roles/pg_backup/templates/plain/create_postgres_dump.sh.j2

Use python from cchq venv for backup scripts

---

environments/staging/public.yml
src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/tasks/misc_v2.yml

https://dimagi-dev.atlassian.net/browse/USH-1700
Production

install phonetic analysis plugin on prod

---

changelog/0051-historical-auditcare-data-migration.yml
hosting_docs/source/changelog/0051-historical-auditcare-data-migration.md

https://dimagi-dev.atlassian.net/browse/SAAS-13717
Add information about checking out the commit which would have the migration code. A part of https://github.com/dimagi/commcare-hq/pull/32086

update changelog and add checkout info in migration

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13886
production

downsize pgformplayer to db.m5.xlarge

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13887
production

downsize pgsynclog to db.m5.xlarge

---

environments/production/terraform.yml

adding more disk space to pgucr0

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13933
India

downsize india elasticache nodes to cache.t4g.medium

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13896
production

downsize esmaster node to r6a.large

---

hosting_docs/source/reference/firefighting/general.rst

Updating the firefighting documentation to reflect steps I took to investigate disk space issues

updated firefighting docs for disk space issues

---

environments/swiss/public.yml

Swiss: upgrading kafka to 3.2.0

---

environments/production/public.yml
environments/staging/public.yml

Adding the environment specific settings related to [this](https://github.com/dimagi/commcare-hq/pull/32138) PR.
All

Add setting to staging/production public.yml

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/postgresql.yml
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13889
Production

created new pgsynclog db with smaller disk

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/postgresql.yml
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13890
Production

created new pgformplayer db with smaller disk

---

environments/swiss/public.yml

upgrade zookeeper in swiss env

---

environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13971
ENVIRONMENTS AFFECTED: production

increase_the_disk_space_to_60GB

---

environments/_authorized_keys/jtang.pub
environments/_users/dimagi.yml

add jtang public key

---

environments/production/app-processes.yml

Increase repeat_record concurrency and set prefetch_multiplier to 1.
Production

Increase repeat_record concurrency

---

environments/india/public.yml
environments/production/public.yml
environments/staging/public.yml
environments/swiss/public.yml
src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/tasks/misc_v2.yml

https://dimagi-dev.atlassian.net/browse/USH-1700
staging
swiss
india
production

install phonetic plugin for elasticsearch

---

src/commcare_cloud/ansible/roles/kinesis_agent/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13989
This is the tool we use for log-shipping formplayer request/response logs to S3.

Update aws-kinesis-agent to 2.0.6

---

changelog/0056-upgrade-kafka_3.2.0.yml
hosting_docs/source/changelog/0056-upgrade-kafka_3.2.0.md
hosting_docs/source/changelog/index.md
hosting_docs/source/services/kafka.rst

Updating documentation with information on how to find the right scala version. please review and let me know your suggestions. 
cc: @dannyroberts @shyamkumarlchauhan

updated information related to scala version

---

environments/staging/terraform.yml

postgres upgrade to v13 on pgfformplayer staging

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13890
https://dimagi-dev.atlassian.net/browse/SAAS-13889
Production

removing old stopped pgsynclog1 and pgformplayer1 rds instances

---

environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-13997
**ENVIRONMENTS AFFECTED:** Staging

removing_servers_in_inventory_and_terraform_files

---

environments/pna/public.yml
environments/swiss/public.yml
quick_monolith_install/sample-environment/public.yml.j2
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

See https://github.com/dimagi/commcare-hq/pull/32244
~~Marking don't merge until https://github.com/dimagi/commcare-hq/pull/32244 is approved by product.~~ Approved.
This isn't directly dependent on the other PR since the feature in question is already 500ing.
All, but it's just removing dead code.

Removed CLOUDCARE_BASE_URL

---

environments/india/terraform.yml

upgrade postgres on pgmain rds

---

control/init.sh

Alternative solution to https://github.com/dimagi/commcare-cloud/pull/5527
This way we don't need to create an additional variable.

Check if venv name contains 3.10

---

src/commcare_cloud/commands/terraform/constants.py

Reverts dimagi/commcare-cloud#5489 temporally until https://github.com/dimagi/commcare-cloud/pull/5525 is merged

Revert "update constants with output of list_waf_allow_patterns"

---

hosting_docs/source/installation/2-manual-install.rst

Originally added on https://github.com/dimagi/commcare-cloud/pull/5424, I didn't like mixing a pure refactor with an addition to docs. This is just the refactor of existing docs.
I found it a bit hard to follow these docs previously, and felt that adding more clearly defined sections and better organization could help so that is what is being done here.
None

Minor changes to installation docs

---

environments/staging/postgresql.yml
environments/staging/public.yml
src/commcare_cloud/ansible/roles/common_installs/defaults/main.yml
src/commcare_cloud/ansible/roles/pg_backup/defaults/main.yml
src/commcare_cloud/ansible/roles/pg_repack/defaults/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/defaults/main.yml
src/commcare_cloud/ansible/roles/postgresql_base/templates/postgresql.conf.j2

postgres upgrade on pgproxy4

---

environments/production/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/backup/main.tf
src/commcare_cloud/terraform/modules/backup/variables.tf

so it applies cleanly on production.
This doesn't actually _change_ production. It just reconciles our terraform code with it. In a followup PR I will apply changes that I believe we want in order to streamline & standardize.
staging would be changed by this if it's applied.

Align terraform backup code with production

---

environments/india/public.yml

Case search reindex plan: https://docs.google.com/document/d/1OlU3k5bEjQydUIIwDaAfKdHr_vvZuzMFLO_iIP6vGpQ/edit#
india

add backfill pillow to india

---

environments/production/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/backup/main.tf
src/commcare_cloud/terraform/modules/backup/variables.tf

https://dimagi-dev.atlassian.net/browse/SAAS-11932
This has been applied already to staging. By my logic, none of these changes result in any meaningful functional changes.

Clean up aws backup plan settings

---

environments/india/app-processes.yml
environments/india/public.yml

Reverts dimagi/commcare-cloud#5557

Revert "add backfill pillow to india"

---

environments/production/app-processes.yml
environments/production/public.yml

Reverts dimagi/commcare-cloud#5521

Revert "temporary backfill pillow for case search ES"

---

environments/production/postgresql.yml
environments/production/terraform.yml

postgres upgrade on production

---

environments/staging/public.yml
src/commcare_cloud/ansible/roles/kafka/defaults/main.yml

kafka upgrade on staging

---

environments/production/postgresql.yml
environments/production/public.yml
environments/production/terraform.yml

postgres 14 upgrade

---

environments/india/postgresql.yml

postgres upgrade india env

---

environments/india/public.yml

upgrade kafka on india env

---

environments/staging/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14105
staging

increasing the disk space of staging control machine

---

environments/swiss/postgresql.yml
environments/swiss/public.yml

postgres and kafka upgrade on swiss

---

environments/production/public.yml

kafka upgrade production

---

environments/production/aws-resources.yml

ENVIRONMENTS AFFECTED: Production

remove_proxy_from_aws-resources.yml_file

---

changelog/0062-kafka-upgrade-to-3.2.3.yml
hosting_docs/source/changelog/0062-kafka-upgrade-to-3.2.3.md

changelog PR: https://github.com/dimagi/commcare-cloud/pull/5592#pullrequestreview-1172046874
none

fix refernce link

---

environments/staging/terraform.yml

postgres upgrade on staging

---

hosting_docs/source/reference/1-commcare-cloud/commands.md
src/commcare_cloud/commands/ansible/ops_tool.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/commands/migrations/copy_files.py
src/commcare_cloud/commands/utils.py

Also fix a few bugs in the `copy-files` command.
None.

Replace PrivilegedCommand with ansible

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13845
This PR applies https://github.com/dimagi/commcare-cloud/pull/5584 to production.
production

Use quarterly AWS Backups in production

---

changelog/0062-kafka-upgrade-to-3.2.3.yml
hosting_docs/source/changelog/0062-kafka-upgrade-to-3.2.3.md
hosting_docs/source/services/kafka.rst

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14047

changes in files for kafka

---

hosting_docs/source/services/kafka.rst

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14047

adding space to code-block

---

src/commcare_cloud/ansible/roles/datadog/templates/elastic.yaml.j2

https://dimagi-dev.atlassian.net/browse/SAAS-14135
all

adjust client-side request timeout value for datadog check

---

src/commcare_cloud/commands/terraform/templates/variables.tf.j2

Update Ubuntu Pro 18.04 AWS AMI search pattern

---

src/commcare_cloud/ansible/roles/datadog/templates/elastic.yaml.j2

Ticket: Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14134

removing_the_timeout_settings_in_elastic.yaml.j2_file

---

environments/_authorized_keys/pverma.pub
environments/_users/dimagi.yml

Adds pverma, new India-Div Developer, user and public ssh key

add user pverma and public key

---

hosting_docs/source/reference/1-commcare-cloud/commands.md
hosting_docs/source/reference/firefighting/celery.rst
src/commcare_cloud/ansible/perform_system_checks.yml
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/ansible/run_module.py
src/commcare_cloud/commands/deploy/commcare.py
src/commcare_cloud/commands/utils.py
src/commcare_cloud/commcare_cloud.py
src/commcare_cloud/fab/checks/check_servers.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/release.py

Additionally, various small cleanups. The main fabric -> ansible work is in the last four commits.
None.

Remove more fabric and convert some to ansible

---

src/commcare_cloud/commands/deploy/commcare.py

Previous error: `KeyError: 'stdout'`
None.

Improve _get_deployed_version() error

---

src/commcare_cloud/commands/deploy/commcare.py

Fix bug introduced in https://github.com/dimagi/commcare-cloud/pull/5625/files#diff-43d45817760a8bf46406bde4e52babc6acf9847e159de7c806cc2da931ab2776R204
tested fix on staging that it works okay

Fix return

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13888
production

Switch cross-region backup from pgauditcare0- to pgauditcare1-production

---

hosting_docs/source/services/postgresql/upgrade.rst

update documentation for postgres upgrade process

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/inventory.ini.j2
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13888
production

removed old pguaditcare0 instance

---

environments/staging/terraform.yml

Updating  engine_version to 14.4 in the following line https://github.com/dimagi/commcare-cloud/blob/master/environments/staging/terraform.yml#L357
ENVIRONMENTS AFFECTED: Staging

updating_the_engine_version_for_pgformplayer0_in_staging

---

.github/PULL_REQUEST_TEMPLATE.md

After not doing this a couple of times after creating new changelogs, I think a reminder in the PR template would be helpful.

Add section to PR template to announce new releases

---

.flake8

Same as https://github.com/dimagi/django-prbac/pull/68
n/a

Remove bad code from flake8 config

---

src/commcare_cloud/ansible/roles/formplayer/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14074
staging

fix for fsx setup

---

src/commcare_cloud/commands/migrations/couchdb.py

Fixes TypeError: can only concatenate str (not "list") to str
None.

list -> comma-delimited string

---

environments/production/app-processes.yml

Increase submission_reprocessing_queue concurrency

---

src/commcare_cloud/ansible/ping.yml
src/commcare_cloud/ansible/roles/kafka/templates/kafka-server.service.j2
src/commcare_cloud/ansible/service_playbooks/kafka.yml
src/commcare_cloud/ansible/stop_servers.yml
src/commcare_cloud/commands/ansible/service.py

'zookeeper' service was renamed to 'zookeeper-server' in a previous PR (#5135).
Update our code accordingly so that we reference the correct service.
All

Update occurrences of 'zookeeper' service name

---

hosting_docs/source/reference/1-commcare-cloud/1-installation.rst

Minor adjustments after going through this process with Dave.
None

Update manual installation docs

---

src/commcare_cloud/ansible/roles/commcarehq/tasks/main.yml
src/commcare_cloud/commands/deploy/command.py
src/commcare_cloud/commands/deploy/commcare.py
src/commcare_cloud/environment/main.py
src/commcare_cloud/environment/schemas/meta.py
src/commcare_cloud/fab/fabfile.py
src/commcare_cloud/fab/operations/release.py

Removing an obsolete setting to simplify deploy logic to make it easier to replace Fabric with Ansible.
None.

Remove git_repositories

---

src/commcare_cloud/ansible/roles/ssh/templates/sshd_config.j2
src/commcare_cloud/ansible/roles/supervisor/tasks/main.yml
src/commcare_cloud/commands/ansible/ansible_playbook.py
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py

Small things encountered while working on deploy automation

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14163
Production

couchdb disk shrink

---

src/commcare_cloud/ansible/roles/postgresql_base/tasks/main.yml

Unmet dependencies while installing pg_repack so added the required package to install the same

Added the dependencies for installing pg_repack

---

src/commcare_cloud/terraform/modules/elasticache-cluster/main.tf

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14194
Environments Affected: ALL

added cloudwatch log group creation and elasticache loging configuration

---

src/commcare_cloud/terraform/modules/elasticache-cluster/main.tf

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14194
Environments: All

adding_apply_immediately_true_parameter

---

environments/staging/aws-resources.yml
environments/staging/inventory.ini

https://dimagi-dev.atlassian.net/browse/SAAS-13636
staging

changed type of fsx

---

environments/staging/aws-resources.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14220
Staging
[SAAS-14220]: https://dimagi-dev.atlassian.net/browse/SAAS-14220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating the resources as per console in aws-resources.yml file

---

.github/workflows/tests.yml

Add Ubuntu 22.04 and Python 3.10 to GitHub Actions

---

hosting_docs/source/installation/migration/1-migrating-project.rst

https://dimagi-dev.atlassian.net/browse/SC-2090
NA

Docs to Provide help for domain migration testing

---

environments/staging/terraform.yml

Modifying the celery_instance_type as per the requisition
Staging

Modifying the instance type

---

src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/roles/java/defaults/main.yml

This PR moves the Java 17 bin path setting to Group variables.

Move bin path setting to group variables

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14287
Production

Adding 100GB disk aize in couchdb instances in production

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14309
Production

resize pgauditcare rds

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14306
Production

downsize formplayer RDS instance

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14307
production

changes instance type of pgucr rds instance

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14304
production

resize pgshard rds instance

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14379
production

Add 3GB to celery_c1{i}-production machines

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14307
**Environments Affected:** production

Changing pgucr RDS instance from db.m6g.2xlarge to db.m5.2xlarge

---

environments/production/public.yml

Production
I got the format wrong for local pillows. The list of pillows must reside in a group.

use proper grouping

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14352
**Environments Affected:** production

adding 175gb of couch disk

---

environments/india/terraform.yml
environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-13590
Production and India

Added awsmq resources to terraform.yml file

---

environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2
src/commcare_cloud/commands/terraform/templates/terraform.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/postgresql/main.tf

https://dimagi-dev.atlassian.net/browse/SAAS-14367
All AWS environments will have irrelevant diffs to apply that come from a change in the module that we're using. Besides that there are no changes.

Support gp3 on RDS

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14367
production

Make production RDS pgshard machines use gp3

---

hosting_docs/source/reference/firefighting/general.rst

[Ticket](https://dimagi-dev.atlassian.net/browse/SC-2542)
Added a section to mention the `commands.log` and `ansible.log` log files that might be useful to reference if something went wrong.

Mention some log files that might be useful for firefighting

---

src/commcare_cloud/commands/ansible/ops_tool.py

[Ticket](https://dimagi-dev.atlassian.net/browse/SC-2459)
We don't want old audit directories to hang around and bloating the audit directory. This PR removes all audit folders older than the fifth youngest audit. This happens after a new audit was created

Remove old audits

---

environments/production/public.yml

Last step of https://dimagi-dev.atlassian.net/browse/SAAS-14330
To be applied after the next deploy
Production

remove backfill pillow from settings

---

src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2

**Environments Affected :** Staging, India and Production

tf_hashes for all platforms in hashicorp/aws provider

---

environments/india/public.yml
environments/production/public.yml
environments/swiss/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14404
swiss
production
india

java17 upgrade for formplayer

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14395
Production

Changing the instance type from c6i.12xlarge to c6a.8xlarge

---

environments/_authorized_keys/ayadav.pub
environments/_users/dimagi.yml

https://dimagi-dev.atlassian.net/browse/SUPPORT-15986
Staging, India, Production

Add ayadav user & ssh key

---

environments/staging/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14372
Staging

Saas 14372/upgrade redis in staging to 7.0

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14372
India

Upgraded elasticcache engine version to 7 and enabled transit encryption

---

environments/india/terraform.yml
environments/production/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/environment/schemas/terraform.py

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14139
**Environments Affected:** Staging, India and Production.

tf_upgradation_in_all_environments

---

environments/india/terraform.yml
environments/production/terraform.yml
environments/staging/aws-resources.yml
environments/staging/inventory.ini
environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2

https://dimagi-dev.atlassian.net/browse/SAAS-13590
Production,India and Staging

SAAS-13590/Removed_awsmq_from_terraform.yml

---

environments/staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_flower.conf.j2

https://dimagi-dev.atlassian.net/browse/SAAS-13590
Staging

modified awsmq to false in public.yml

---

environments/production/terraform.yml
environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/backup/main.tf
src/commcare_cloud/terraform/modules/backup/variables.tf

https://dimagi-dev.atlassian.net/browse/SAAS-14421

Weekly retention

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14437
Production

change instance type for pgbouncer machines

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14436
Production

Downsize_pgauditcare_back_from_db.t3.2xlarge_to_db.m5.xlarge

---

environments/_authorized_keys/mriese.pub
environments/_users/dimagi.yml

Adds user and public ssh key for new USH developer mriese.

Add mriese user and public key

---

environments/production/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-14434
**Environments Affected :**  Production

resizing all es_a1{i} nodes from r5.4xlarge to r6a.4xlarge

---

src/commcare_cloud/ansible/roles/nodejs/tasks/main.yml

PR updates NodeJS to 16.x and npm to 8.x
https://dimagi-dev.atlassian.net/browse/SAAS-14265
HQ pr to update Node https://github.com/dimagi/commcare-hq/pull/32702
ALL

Update Node to 16.x and npm to 8.x

---

environments/production/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-14434

resizing all es_b1{i} nodes from r5.4xlarge to r6a.4xlarge

---

hosting_docs/source/backups_dr/2-backups-guide.rst
hosting_docs/source/backups_dr/4-dr-setup.rst

https://dimagi-dev.atlassian.net/browse/SC-2575
None

Add docs on DR

---

src/commcare_cloud/ansible/roles/bootstrap-machine/tasks/main.yml

Set adduser DIR_MODE to 0755

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14372
production

elasticache redis upgrade on production env

---

src/commcare_cloud/ansible/roles/nginx/templates/nginx.conf.j2
src/commcare_cloud/ansible/roles/nginx/vars/main.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14344

to fix the nginx error

---

environments/production/terraform.yml

Increase couchdb2 disk by 500GB to protect from being full

---

environments/production/inventory.ini
environments/production/inventory.ini.j2

Decrease swap size on couchdb nodes from 27 to 2GB

---

src/commcare_cloud/fab/diff_templates/console.txt.j2

https://github.com/dimagi/commcare-cloud/pull/5630#pullrequestreview-1342336933
All.

Do not print changelogs alert if there are none

---

src/commcare_cloud/ansible/requirements.yml

Update couchdb-cluster-apt reference

---

src/commcare_cloud/commands/deploy/command.py

Fixes `AttributeError` on `deploy formplayer`
All.

Remove obsolete fab_settings check

---

src/commcare_cloud/commands/ansible/run_module.py

Flag incomplete releases in list-releases output

---

hosting_docs/source/installation/2-manual-install.rst

Update 2-manual-install.rst with python setup that works on Jammy

---

src/commcare_cloud/ansible/group_vars/all.yml
src/commcare_cloud/ansible/group_vars/couchdb2.yml

Make couchdb_dir var always available to fix deploy_cloudwatch_logs.yml

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-14344
Environments Affected: India

Saas 14344/ubuntu22 proxy

---

src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_flower.conf.j2

Add missing trailing slash to broker_api url

---

hosting_docs/source/installation/2-manual-install.rst

Fix 'Add missing dependencies to installation docs'

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14510
india

switch instance type to t3a

---

environments/staging/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14344
**Environments Affected:** Staging

increase_the_disk_size_to_5GB_on_kafka_server

---

environments/production/terraform.yml

disk size increase on ES data nodes.
production

increase disk size on es nodes

---

environments/staging/terraform.yml

Just a small cost saving opportunity I noticed
staging

Downsize staging elasticache cluster to cache.t3.small

---

environments/production/terraform.yml
environments/staging/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14586
production

Set production cross region backup quarterly retention to 180 days

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14606
production

Limit production ES cross region backups to one zone of data notes

---

environments/production/terraform.yml
environments/staging/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14599

Change cross-region backup region

---

environments/production/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-14621

Increase kafka disks to 150 GB in production

---

environments/india/postgresql.yml
environments/india/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-14627
**Environments Affected :** India

adjust the pgbouncer setup to have a dedicated pgbouncer for UCR db

---

environments/india/terraform.yml
environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14595

adding storage_type: gp3 parameter for remaining rds_instances

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Leftover from https://github.com/dimagi/commcare-cloud/pull/5978/

Add template var for sms index

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14659
production

Increase production elasticache memory to cache.r6g.2xlarge

---

src/commcare_cloud/terraform/modules/backup/main.tf

https://dimagi-dev.atlassian.net/browse/SAAS-14517
This just makes it so we can't accidentally delete remote backups.

Lock remote vault

---

.flake8

To avoid errors like this one https://github.com/dimagi/commcare-cloud/actions/runs/5382260412/jobs/9767424842

Put .flake8 comment on its own line to avoid error

---

src/commcare_cloud/environment/schemas/terraform.py

This is to deal with the (pre-existing) lint errors on https://github.com/dimagi/commcare-cloud/pull/6009
None

Lint schemas/terraform.py (flake8)

---

environments/staging/terraform.yml
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/elasticache-cluster/main.tf
src/commcare_cloud/terraform/modules/elasticache-cluster/variables.tf

https://dimagi-dev.atlassian.net/browse/SAAS-14659
staging materially (india, production superficially by replacing the default parameter group with a custom parameter group that inherits all the same defaults with no changes)

Add ability to set maxmemory-policy=allkeys-lru and other redis params in Elasticache

---

src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2

**Environments Affected :** Staging, India and Production

adding hashes for windows_and_linux

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14657
india

increase disk size on es india

---

src/commcare_cloud/commands/terraform/templates/terraform.lock.hcl.j2

updating arm64 hash_values for linux and darwin

---

environments/staging/terraform.yml
src/commcare_cloud/ansible/roles/nginx/vars/main.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-14600

Update the security policy to support TLS 1.3 for ALB and for Nginx

---

environments/india/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-14600
**Environments Affected :** India

Update the security policy to support TLS 1.3 for ALB and Nginx in INDIA

---

environments/production/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-14600

Update the security policy to support TLS 1.3 for ALB and Nginx

---

src/commcare_cloud/ansible/roles/elasticsearch/defaults/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/templates/delete_older_es_logs.sh.j2

https://dimagi-dev.atlassian.net/browse/SAAS-14536
all env

compress and delete old es logs

---

environments/india/public.yml
src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12152
india

india es5 upgrade

---

docs/source/reference/1-commcare-cloud/commands.md
src/commcare_cloud/commands/inventory_lookup/inventory_lookup.py
src/commcare_cloud/commcare_cloud.py

Adds a command to copy files between a remote host and the local machine.
[Proposal doc](https://docs.google.com/document/d/1L6CLWa69-OiWpW_NF2vKKXH2xKiISis8bfMyyvpiKtU/edit#heading=h.wdykctzi9es0).
None.

scp command

---

requirements.txt
setup.py

https://dimagi-dev.atlassian.net/browse/SAAS-14733
All

Upgrade pyOpenSSL and cryptography, make requirements

---

requirements.txt
setup.py

There was previously a [PR](https://github.com/dimagi/commcare-cloud/pull/1846) made to remove this by @dannyroberts but it was later closed without explanation. Danny do you remember why you close that PR?
This was being resolved since `requests 2.19` was released.
https://github.com/psf/requests/issues/4681#issuecomment-396619205
None

Remove idna from setup.py

---

environments/india/terraform.yml

This is minor cleanup that I found while doing https://dimagi-dev.atlassian.net/browse/SAAS-14743.
india

Fix tags (used for cost analysis) on india EC2 instances

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14743
india

Downsize india webworkers from r5a.xlarge to r6a.large

---

src/commcare_cloud/ansible/roles/devops_scripts/tasks/main.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14342

fixing the issue with when condition

---

environments/staging/terraform.yml

correcting the instance type from t3a.xlarge to t3a.large

---

environments/india/aws-resources.yml
environments/india/inventory.ini
environments/india/inventory.ini.j2
environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14594
india

remove one es coordinator node from india env

---

environments/production/aws-resources.yml

Ticket:: https://dimagi-dev.atlassian.net/browse/SAAS-14749
Environments Affected: Production

removing couch23 entry

---

docs/source/installation/1-quick-monolith-install.rst
docs/source/installation/2-manual-install.rst
docs/source/prereqs/6-software-and-tools.rst
docs/source/reference/1-commcare-cloud/1-installation.rst
docs/source/reference/howto/configure-virtualbox.rst

This is followup from upgrading to Ubuntu 22.04, and should likely have been done on July 1 if not earlier.
None

Update documentation to reference Ubuntu 22.04

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14811

downsize the instance type

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

This PR adds ABDM configs in local settings required for said integration.
Corresponding PR on HQ:
https://github.com/dimagi/commcare-hq/pull/33325
Related PR for secrets (that was merged)
https://github.com/dimagi/commcare-cloud/pull/5460
Localsettings of all environments

Adds localsettings for ABDM integration

---

environments/india/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14784
india

downsize pgmain0 india

---

environments/production/app-processes.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14811

Change case-pillow num_processes from 49 to 33

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-12152
production

disable multiplexer on case_search

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-14811

Downsize AZ:B pillowtop instance

---

environments/staging/terraform.yml

**Ticket: ** https://dimagi-dev.atlassian.net/browse/SAAS-14730
**Environments Affected: ** Staging

remove_fsx_file_systems

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14740
Disables multiplexer on remaining indexes
Production

Disable multiplexer on  apps, domains, groups and sms index

---

environments/production/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14741
Production

update public.yml for upcoming es upgrade

---

environments/swiss/public.yml

https://dimagi-dev.atlassian.net/browse/SAAS-14916
Prepares Swiss Env to be upgraded to ES 5
Swiss

Prepare swiss env for es 5 upgrade

---

environments/production/terraform.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-14986
**Environments Affected: -** Production

resize mobile_webworkers from m6a.2xlarge to r6a.xlarge

---

environments/india/terraform.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-15021
**Environments Affected: -** India

Downsize elasticsearch datanodes from t3a.xlarge to r6a.large

---

environments/production/terraform.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-15018
**Environments Affected: -** Production

Downsize pgbouncer_a6(plproxy) from r5a.2xlarge to r6a.xlarge

---

environments/production/app-processes.yml

**Ticket: -** https://dimagi-dev.atlassian.net/browse/SAAS-15019
**Environments Affected: -** Production

changed the num_processes and total_processes for pillow_b2000

---

environments/production/app-processes.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-15019
**Environments Affected :** production

changed pillow_b2000 case-pillow_num_processes to 13 from 17

---

environments/production/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-15019

Downsize pillow_b2000 from r6a.8xlarge to r6a.4xlarge

---

.readthedocs.yml

Fix Readthedocs build

---

environments/production/terraform.yml

downsized data_nodes in az:A

---

environments/production/terraform.yml

Downsize elasticsearch data nodes from r6a.4xlarge to r7i.2xlarge

---

environments/production/terraform.yml

switching instance type to r7a.2xlarge

---

environments/production/terraform.yml

Ticket: https://dimagi-dev.atlassian.net/browse/SAAS-15050
Environments Affected: Production

change instance type for elasticsearch datanodes in AZ:A

---

environments/production/public.yml

[
Jira ticket](https://dimagi-dev.atlassian.net/browse/SAAS-15043)
Production

Add almanach-nigeria to the ALTERNATE_HOSTS list

---

environments/production/terraform.yml

revert to the original size, r6a.4xlarge for esdatanodes

---

environments/production/terraform.yml

https://dimagi-dev.atlassian.net/browse/SAAS-15123
production

Add a little more storage to production formplayer volumes

---

src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Followup to https://github.com/dimagi/commcare-cloud/pull/6169 🤦🏻 
Staging

Include MAX_MOBILE_UCR_LIMIT in settings template

---

environments/production/aws-resources.yml
environments/production/inventory.ini
environments/production/terraform.yml

Removing one datanode from each zone in Production

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-15129

Downsize pgshard2_and_pgshard3 to db.m5.xlarge

---

environments/production/terraform.yml

**Ticket:** https://dimagi-dev.atlassian.net/browse/SAAS-15129

switch pgshard1-production to db.m6g.xlarge

---

src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml

Very minor/nitpick type changes.
None

Reference as Elasticsearch

---

environments/production/terraform.yml

**Ticket :** https://dimagi-dev.atlassian.net/browse/SAAS-15129

switching pgshard{3,4,5} to db.m6g.2xlarge

---

docs/source/installation/2-manual-install.rst
docs/source/reference/howto/wipe_persistent_data.rst

Some documentation tweaks, based on recently deploying a monolith a couple of times.
None. Documentation only.

A few small documentation tweaks

---

docs/source/operations/2-deploys.rst

Very straightforward. I tested the updates locally.
None

Minor deploy related doc fixes

---

environments/production/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-15246

switching pgucr0-production and pgformplayer2-production to db.m6g

---

environments/production/app-processes.yml

USH: https://dimagi.atlassian.net/browse/USH-4105
SaaS request: https://dimagi.atlassian.net/browse/SAAS-15290
Production

enable APM tracing for Formplayer on production

---

docs/source/reference/howto/wipe_persistent_data.rst

Followup to https://github.com/dimagi/commcare-cloud/pull/6219
None

Specify that kafka/zookeeper paths may vary

---

environments/india/app-processes.yml

10 seems to perform a bit better than 20, and 100 was terrible so this seems like the sweet spot.
India

Change concurrency of reminder_queue on India

---

docs/source/installation/2-manual-install.rst
docs/source/installation/migration/1-migrating-project.rst

Followup to https://github.com/dimagi/commcare-cloud/pull/6214
None

More doc updates applicable to migrating data to a new instance

---

environments/production/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-15456

Change instance type of mobile web workers to m6a.2xlarge

---

environments/staging/app-processes.yml

https://dimagi.atlassian.net/browse/SAAS-15465
This is already the setup, which was applied from
https://github.com/dimagi/commcare-cloud/compare/ap/test-ddtrace-run . This PR is just a cleaner version of that, which I intend to merge to keep master up to date.
staging

Enable ddtrace on staging

---

environments/production/terraform.yml

Temporarily change the instance type to have more CPUs
Production

Change mobile worker instance type to c6a.8xlarge

---

environments/production/elasticsearch.yml

Doubles the shard count for the case-search index on production
Production

Double case-search shard count for new index

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

Ticket: https://dimagi.atlassian.net/browse/SAAS-15391
Environments Affected: India

updating the syntax for esmaster nodes

---

environments/staging/public.yml

Temporary PR to test. I ran from a branch, but didn't see the changes reflected in settings.
Staging

Add gherceg to test multiplexing

---

environments/production/app-processes.yml

Increase case pillow processing by adding 4 processes to the other pillow machine that currently does not have a case pillow process.
Production

Add case-pillow processes to pillow_a2000

---

src/commcare_cloud/ansible/roles/pgbouncer/templates/pgbouncer.users.j2
src/commcare_cloud/ansible/roles/postgresql_base/tasks/set_up_dbs.yml

https://dimagi.atlassian.net/browse/SAAS-14299
Reverses https://github.com/dimagi/commcare-cloud/pull/5989
This must be applied after https://github.com/dimagi/commcare-hq/pull/34751.

Drop unused repeaters_fdw_user in repeaters database

---

docs/source/installation/go-live-checklist.rst
docs/source/installation/index.rst
docs/source/installation/preparing-to-migrate.rst

Context: [Jira](https://dimagi.atlassian.net/browse/SC-3653)
Updates documentation based on lessons learned from recent migrations from prod to self-hosted environments.
None. This is a documentation-only change.

Update docs with lessons learned

---

environments/india/inventory.ini
environments/india/inventory.ini.j2

https://dimagi.atlassian.net/browse/SAAS-15391
replacing https://github.com/dimagi/commcare-cloud/pull/6328
India

Remove celerybeat_a1-india until ready

---

environments/production/app-processes.yml

https://dimagi.atlassian.net/browse/SAAS-15631
production

Increase production repeat_record_queue concurrency from 12 to 36

---

environments/production/app-processes.yml
environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-15747
production

Increase RAM to double the number of production case-pillow processors

---

docs/source/installation/migration/3-migrating-application.rst
docs/source/installation/migration/index.rst

https://dimagi.atlassian.net/browse/SC-3582
Documentation change

Add content around migrating commcare apps only

---

environments/staging/terraform.yml

Temporarily increase capacity for 3rd party testing.
Staging

Change staging webworkers from t3a.large to xlarge

---

src/commcare_cloud/ansible/deploy_citusdb.yml
src/commcare_cloud/ansible/deploy_formplayer.yml
src/commcare_cloud/ansible/deploy_postgres.yml
src/commcare_cloud/ansible/roles/cloudwatch_logs/tasks/main.yml
src/commcare_cloud/ansible/roles/elasticsearch/tasks/main.yml
src/commcare_cloud/ansible/roles/lpar2rrd/tasks/main.yml
src/commcare_cloud/ansible/roles/postgresql/tasks/main.yml
src/commcare_cloud/ansible/roles/rabbitmq/tasks/main.yml
src/commcare_cloud/ansible/roles/redis/tasks/main.yml
src/commcare_cloud/ansible/roles/sentry/tasks/main.yml

Ticket: https://dimagi.atlassian.net/browse/SAAS-14998
Environments Affected: All 3 environments - Staging, India and Production

Rewriting include as include_tasks as it is deprecated

---

src/commcare_cloud/commands/terraform/constants.py

Motivated by https://github.com/dimagi/commcare-hq/pull/35216, also makes a couple of updates from recent HQ PRs that missed it.
Planning to run on staging, prod, and india

Update WAF regex

---

environments/production/terraform.yml

**Ticket :**  https://dimagi.atlassian.net/browse/SAAS-16072

Decrease compute on es coordinator nodes

---

environments/production/terraform.yml

This reverts commit 0cbce83903f19f6027bb45d1c6d0601ee1464e9a.
https://dimagi.atlassian.net/browse/SAAS-16055
Production

Downsize ES coordinator nodes

---

src/commcare_cloud/commands/deploy/commcare.py

Updated error message when unable to get versions from host

---

environments/production/terraform.yml

**Ticket -** https://dimagi.atlassian.net/browse/SAAS-16173
**Environments Affected -** Production

Downsize mobile web workers

---

environments/staging/app-processes.yml

[Staging] Enable APM for formplayer

---

docs/source/installation/1-quick-monolith-install.rst
quick_monolith_install/bootstrap-env-playbook.yml
quick_monolith_install/cchq-install.sh

Minor text changes to docs

---

docs/source/installation/migration/1-migrating-project.rst

Minor documentation change. Followup to https://github.com/dimagi/commcare-hq/pull/35343 
None

Only one blob export needs to be run now

---

environments/production/app-processes.yml

[Jira ticket](https://dimagi.atlassian.net/browse/USH-4309)
Production

turn off apm trace

---

environments/production/terraform.yml

This is the current state in production.
Production

Make instance type accurate for rabbit15

---

requirements.txt
setup.py

This is just used in deploys and I have tested it with deploy on staging and deploy went smooth.
All

Update pygithub to latest version

---

environments/production/public.yml

Swap apps index on prod. 
Prod

Swap apps index on Prod

---

environments/production/public.yml

These are the required changes needed for upcoming ES 5-6 upgrade. 
Production

[Production] - Changes required for es 5-6 upgrade

---

environments/production/app-processes.yml

Followup to https://github.com/dimagi/commcare-cloud/pull/6528
Production

Dedicated processes for all partitions

---

environments/production/terraform.yml

Use a machine with higher network capacity for ES coordinators.
Production

Add more network capacity to coordinators

---

environments/backup-production/public.yml
environments/production/public.yml

[USH-5891](https://dimagi.atlassian.net/browse/USH-5891)
Production
to announce a new commcare-cloud release. 
[USH-5891]: https://dimagi.atlassian.net/browse/USH-5891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove co-carecoordination-perf from BHA index

---

environments/production/terraform.yml
src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2
src/commcare_cloud/environment/schemas/terraform.py
src/commcare_cloud/terraform/modules/postgresql/main.tf

https://dimagi.atlassian.net/browse/SAAS-17362
Can be applied using
```
cchq production terraform apply -target module.postgresql__pgshard1-production -target module.postgresql__pgshard2-production -target module.postgresql__pgshard3-production -target module.postgresql__pgshard4-production -target module.postgresql__pgshard5-production
```
production

Increase IOPS on production pgshard RDS instances

---

environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-17400
Increase disk size of kafka machines on production.
Production

Increase disk size of kafka machines on production

---

.github/workflows/codeql.yml
.github/workflows/trivy.yml

https://dimagi.atlassian.net/browse/USH-5721
Same as the change done to HQ in https://github.com/dimagi/commcare-hq/pull/36212
None

Run CodeQL on all PRs

---

environments/production/postgresql.yml

https://dimagi.atlassian.net/browse/SAAS-17395
Production

Double ucr db connections

---

environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-17448
Logic for why only 10GB can be found in the related ticket.
Production

Add 10GB of disk to kafka machines

---

environments/production/terraform.yml

Increase Pgmain iops to 18000
https://dimagi.atlassian.net/browse/SAAS-17469
Prod

increase iops to 18000

---

environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-17468
Followup to https://github.com/dimagi/commcare-cloud/pull/6532 which hasn't been merged yet.
Production

Set storage to 1000GB on couch11

---

environments/production/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-17334

Downsize the disk on couch12 to 1000gb

---

environments/production/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-17334

Downsize the disk on couch_a0 to 1000gb

---

environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-17513
Production

Scale down mobile webworker machines

---

environments/production/app-processes.yml
environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-17513
Production

Scale down case pillow machine and processes

---

environments/staging/app-processes.yml

https://dimagi.atlassian.net/browse/USH-5968
Staging

Disable datadog APM traces

---

environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-17513
Reverts https://github.com/dimagi/commcare-cloud/pull/6515
Production

Scale down HQ webworkers

---

changelog/0087-upgrade-to-es-6.yml
docs/source/changelog/0087-upgrade-to-es-6.md

Add a missed variable in changelog and also updates the update-config and restart commands 
All

Fixes issues es6 upgrade changelog

---

changelog/0087-upgrade-to-es-6.yml
docs/source/changelog/0087-upgrade-to-es-6.md

While fixing the commands in https://github.com/dimagi/commcare-cloud/pull/6576 , I made a typo in `update-config`, instead of using `-`, I added `_`.

Replace update_config with update-config

---

environments/production/terraform.yml

Temporary action while https://dimagi.atlassian.net/browse/SAAS-17562 is rolled out.
Production

Double memory on celery machines temporarily

---

src/commcare_cloud/ansible/library/setup_virtualenv.py
src/commcare_cloud/ansible/roles/commcarehq/tasks/git_repository.yml

Building on https://github.com/dimagi/commcare-cloud/pull/6567
- Fix `setup_virtualenv` docs and examples
- Add `uv sync` to initial git repo set up
https://dimagi.atlassian.net/browse/SAAS-17528
all

A couple more dependency management changes

---

environments/production/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-17569

Downsize celery servers to r6a.2xlarge

---

src/commcare_cloud/ansible/library/setup_virtualenv.py
tests/test_deploy/test_setup_virtualenv.py

https://dimagi.atlassian.net/browse/SAAS-16584
all

Do not create python_env-3.9 link to 3.13 venv

---

environments/production/terraform.yml

https://dimagi.atlassian.net/browse/SAAS-17640
Production

Add network capacity to ES coorindators

---

environments/production/app-processes.yml
environments/production/terraform.yml

Increase case pillow processing

---

src/commcare_cloud/ansible/deploy_proxy.yml

https://dimagi.atlassian.net/browse/SAAS-17737?focusedCommentId=384519
all

Avoid namespace pollution from earlier task

---

environments/backup-production/public.yml
environments/production/public.yml
environments/staging/public.yml

[Jira Ticket](https://dimagi.atlassian.net/browse/USH-5971)
As part of the [main PR](https://github.com/dimagi/commcare-hq/pull/36607) that creates the index. 
Production (and backup production)

Add co-carecoordination-perf to CASE_SEARCH_SUB_INDICES

---

environments/eu/terraform.yml
environments/india/terraform.yml

Temporarily increase memory on django manage

---

environments/eu/public.yml

https://dimagi.atlassian.net/browse/QA-7805
EU

Update alternate hosts for eu

---

environments/production/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-18078
**Environment :** Production

Downsize ES coordinator nodes to r6a.2xlarge

---

environments/staging/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-18348

Add 5 GB disk to all couch nodes on staging

---

environments/echis/public.yml
environments/staging/inventory.ini
environments/staging/inventory.ini.j2
environments/staging/public.yml
src/commcare_cloud/commands/terraform/aws.py
src/commcare_cloud/commands/terraform/templates/commcarehq.tf.j2
src/commcare_cloud/environment/schemas/terraform.py

Was tested a few years back in https://dimagi.atlassian.net/browse/SAAS-13590
We are no longer pursuing this, and we shouldn't need to communicate anything to self hosters as we never supported AmazonMQ officially.
I confirmed we don't have a lingering AmazonMQ setup on staging fwiw.
Staging and echis?

Remove code related to AmazonMQ testing

---

environments/backup-production/public.yml
environments/eu/public.yml
environments/india/public.yml
environments/production/public.yml
environments/staging/public.yml
src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2

Link to ticket [here](https://dimagi.atlassian.net/browse/CCCT-1372).
Link to related HQ PR [here](https://github.com/dimagi/commcare-hq/pull/36803).
- production
- staging
- backup-production

add credentials url to settings

---

environments/india/terraform.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-18156
**Environments Affected :** EU

Downsize djangomanage machine in india to t3a.small

---

environments/production/terraform.yml

**Environments :** Production
**Tickets** 
1. https://dimagi.atlassian.net/browse/SAAS-18480
2. https://dimagi.atlassian.net/browse/SAAS-18489

Downsize pillow servers

---

environments/production/app-processes.yml

The hope is to optimize memory consumption (less processes) while also increasing throughput (one partition per worker rather than two).
It may be possible to increase the number of partitions to further improve throughput.
https://dimagi.atlassian.net/browse/SAAS-18518
Production

Use gevent in production pillows

---

environments/production/public.yml

**Ticket :** https://dimagi.atlassian.net/browse/SAAS-18422
**Environment :** Production

delete expired certificate

---

environments/staging/app-processes.yml

Followup to https://github.com/dimagi/commcare-cloud/pull/6695#discussion_r2408077028
None

Improve text for demo case pillow
